- mingw-w64-qt6-multimedia/PKGBUILD
Per https://github.com/msys2/MINGW-packages/issues/17330#issuecomment-1566413954
> qt6-multimedia: split out backend packages

- mingw-w64-pycairo/PKGBUILD
> pycairo: Update to 1.24.0

- mingw-w64-ghex/003-gui-app.patch
- mingw-w64-ghex/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17560
> ghex: update to 44.1

- mingw-w64-mupdf/003-makefile-add-mupdf-gl-icon.patch
- mingw-w64-mupdf/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17579
> mupdf: update to 1.22.2

- mingw-w64-darktable/PKGBUILD
> darktable: update to 4.4.0

- mingw-w64-tk/003-fix-forbidden-colon-in-paths.mingw.patch
- mingw-w64-tk/004-install-man.mingw.patch
- mingw-w64-tk/005-install-pkgconf.mingw.patch
- mingw-w64-tk/006-prevent-tclStubsPtr-segfault.patch
- mingw-w64-tk/008-dont-link-shared-with--static-libgcc.patch
- mingw-w64-tk/011-win-arm64.patch
- mingw-w64-tk/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17600
> tk: Add pkgconfig file

- mingw-w64-gtk4/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17561
> gtk4: split gstreamer media plugin to separate package

- mingw-w64-aalib/0001-Apply-patch-for-MSYS2.patch
- mingw-w64-aalib/0003-aalib-m4-quote-macro-name.patch
- mingw-w64-aalib/0004-aalib-m4-use-correct-variable.patch
- mingw-w64-aalib/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17645
> aalib: Fix aalib.m4

- mingw-w64-cairo/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17643
> cairo: Build static library separately

- mingw-w64-gettext/0030-fix-wbindtextdomain-backport.patch
- mingw-w64-gettext/PKGBUILD
> gettext: backport wbindtextdomain fixes

- mingw-w64-transmission/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17754
> transmission: Add missing dependencies

- mingw-w64-totem-pl-parser/PKGBUILD
> totem-pl-parser: remove libsoup dependency

- mingw-w64-angleproject/001-add-mingw-toolchain.patch
- mingw-w64-angleproject/002-buildflags-fixes.patch
- mingw-w64-angleproject/003-angle-src-fixes.patch
- mingw-w64-angleproject/004-swiftshader-updates.patch
- mingw-w64-angleproject/005-vulkan-memory-allocator-updates.patch
- mingw-w64-angleproject/006-spirv-updates.patch
- mingw-w64-angleproject/007-vulkan-loader-updates.patch
- mingw-w64-angleproject/PKGBUILD
- enable vulkan backend
- linked with internal vulkan statically
> angleproject: update to 2.1.r21358

- mingw-w64-angleproject/008-arm64-mingw-intrinsic.patch
- mingw-w64-angleproject/PKGBUILD
mingw-w64 doesn't have _ReadStatusReg, so use inline asm
> angleproject: try to fix the build with clangarm64

- mingw-w64-capstone/PKGBUILD
- mingw-w64-capstone/mingw_python.patch
Changes:
* Use Ninja instead of make.
* Follow PKGBUILD template.
* Rebase patch.
Fixes https://github.com/msys2/MINGW-packages/pull/17767
> capstone: update to 5.0

- mingw-w64-capstone/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17779
> capstone: Add static library

- mingw-w64-gst-plugins-rs/PKGBUILD
gst-plugin-aws fails to build on 32bit
> gst-plugins-rs: Update to 0.10.11

- mingw-w64-rapidjson/0008-cmake-relocate-dirs.patch
- mingw-w64-rapidjson/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17530
> rapidjson: Fix case in cmake variables

- mingw-w64-zimg/0001-zimg-export-def-symbols.patch
- mingw-w64-zimg/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17834
> zimg: Fix exporting APIs from import library

- mingw-w64-assimp/0001-fix-wrong-project-version.patch
- mingw-w64-assimp/PKGBUILD
I don't know why, but the .pc file says version 5.2.4.
> Assimp: fix wrong version in .pc file

- mingw-w64-postgresql/PKGBUILD
- mingw-w64-postgresql/postgresql-15.1-clang-16.patch
Fixes errors when rebuilding with Clang 16.
> postgresql: update to 15.3

- mingw-w64-podman/PKGBUILD
> podman: Update to 4.6.0

- mingw-w64-qt6-3d/PKGBUILD
- mingw-w64-qt6-5compat/PKGBUILD
- mingw-w64-qt6-activeqt/PKGBUILD
- mingw-w64-qt6-base/004-qt-6.2.0-win32-g-Add-QMAKE_EXTENSION_IMPORTLIB-defaulting-to-.patch
- mingw-w64-qt6-base/PKGBUILD
- mingw-w64-qt6-charts/PKGBUILD
- mingw-w64-qt6-connectivity/PKGBUILD
- mingw-w64-qt6-declarative/PKGBUILD
- mingw-w64-qt6-languageserver/PKGBUILD
- mingw-w64-qt6-multimedia/PKGBUILD
- mingw-w64-qt6-quick3d/PKGBUILD
- mingw-w64-qt6-quicktimeline/PKGBUILD
- mingw-w64-qt6-shadertools/PKGBUILD
Part one of three, plit out from #17913
> qt6: update to 6.5.2 (1/3)

- mingw-w64-yt-dlp/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17921
> yt-dlp: Add package

- mingw-w64-raylib/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17955
> raylib: Add static library

- mingw-w64-spdlog/PKGBUILD
> spdlog: Update to 1.12.0

- mingw-w64-inkscape/PKGBUILD
also move boost from makedepends to depends -> Fixes #17972
> inkscape: Update to 1.3

- mingw-w64-qt6-base/001-appending-qt6-to-remove-qt5-conflict.patch
- mingw-w64-qt6-base/PKGBUILD
> Qt6: fix WINDEPLOYQT_EXECUTABLE variable

- mingw-w64-visualizationlibrary/0001-vl-remove-std-mem-fun-ref.patch
- mingw-w64-visualizationlibrary/0002-vl-fix-wx-macros.patch
- mingw-w64-visualizationlibrary/0003-vl-fix-clang-errors.patch
- mingw-w64-visualizationlibrary/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17943
> visualizationlibrary: Add package

- mingw-w64-python/0141-Search-DLLs-only-on-paths-added-using-add_dll_direct.patch
- mingw-w64-python/PKGBUILD
see https://github.com/msys2-contrib/cpython-mingw/pull/144
> python: update

- mingw-w64-cargo-c/PKGBUILD
> cargo-c: update to 0.9.23

- mingw-w64-blosc2/0001-blosc2-cmake-fix-install.patch
- mingw-w64-blosc2/PKGBUILD
Also remove full install path in cmake files
> blosc2: Fix installing cmake file

- mingw-w64-mpv/PKGBUILD
- mingw-w64-mujs/001-makefile-fix.patch
- mingw-w64-mujs/PKGBUILD
> mpv: enable javascript

- mingw-w64-glslang/PKGBUILD
> glslang: restore glslangValidator

- mingw-w64-cglm/PKGBUILD
Also enable default packaging options
> cglm: split docs into separate package

- mingw-w64-p11-kit/PKGBUILD
See https://github.com/p11-glue/p11-kit/issues/539
> p11-kit: backport fix to fix the gnutls build

- mingw-w64-nerd-fonts/PKGBUILD
> Add nerd fonts, take 2

- mingw-w64-jolt-physics/0001-fix-missing-uint.patch
- mingw-w64-jolt-physics/PKGBUILD
What is the policy of msys2 regarding vector extensions ? What minimum processor (and thus extensions)  do you expect ?
> Add Jolt-Physics package

- mingw-w64-llama.cpp/PKGBUILD
> Add llama.cpp

- mingw-w64-spirv-headers/PKGBUILD
- mingw-w64-spirv-tools/002-Do-not-statically-link-to-the-C-runtime-with-mingw.patch
- mingw-w64-spirv-tools/PKGBUILD
- mingw-w64-vulkan-validation-layers/PKGBUILD
> Update vulkan-validation-layers/spirv-tools to 1.3.261/2023.4rc2

- mingw-w64-7zip/PKGBUILD
- mingw-w64-7zip/clang-arm-target-fixes.patch
For release notes, see
https://sourceforge.net/p/sevenzip/discussion/45797/thread/3f550826d8/
> 7zip: upgrade to 23.01

- mingw-w64-qt-creator/001-fix-finding-yaml-cpp-0.8.0.patch
- mingw-w64-qt-creator/PKGBUILD
> qt-creator: update to 11.0.2

- mingw-w64-nerd-fonts/PKGBUILD
I left package group as is. if it confuses someone I'll remove it. also added missing fonts
> nerd-fonts: add missing fonts and improve recipe

- mingw-w64-dtc/PKGBUILD
removed patch is included in this new release
> dtc: Update to 1.7.0

- mingw-w64-qemu/PKGBUILD
- mingw-w64-qemu/msys2.examples.tests.sh
see https://wiki.qemu.org/Planning/8.1 for further information
> qemu: Update to 8.1.0

- mingw-w64-v8/PKGBUILD
See comment here: https://github.com/msys2/MINGW-packages/pull/18000#issuecomment-1694662796
> Remove redundant dependency

- mingw-w64-starship/PKGBUILD
needed for theme prompts
important question: can we use package group as dependency? (edit: for the answer read comments below https://github.com/msys2/MINGW-packages/pull/18196#issuecomment-1680036783)
> starship: optdepend on nerd fonts

- mingw-w64-scotch/0002-pipe-fix.patch
- mingw-w64-scotch/0004-dummysizes-regex.patch
- mingw-w64-scotch/PKGBUILD
* rebase patches.
* allow multiple jobs with make command.
> scotch: update to 7.0.4

- mingw-w64-android-tools/0001-android-tools-cmake.patch
- mingw-w64-android-tools/0002-android-tools-vendor.patch
- mingw-w64-android-tools/PKGBUILD
* Changes:
- 0001: Enable building liblp for fastboot.
- 0002: Remove some upstream hunks and fix libziparchive.
> android-tools: update to 34.0.4

- mingw-w64-python-poetry/8400.patch
- mingw-w64-python-poetry/PKGBUILD
and add some context to the jsonschema patching while at it
> poetry: backport fix for newer python-build

- mingw-w64-qt5-static/PKGBUILD
It fails to build on i686 (both mingw32 and clang32), Anyone interested in it is welcome to fix it.
> qt5-static: update to 5.15.10

- mingw-w64-libssh2/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/18451
> libssh2: Disable rpath to fix pkgconfig file

- mingw-w64-armadillo/PKGBUILD
- mingw-w64-ensmallen/PKGBUILD
- mingw-w64-mlpack/PKGBUILD
Do mention if separate PRs are more convenient
cc fortran toolchain/linalg knowers about armadillo, but its mostly header only so should work out
> armadillo, emsmallen, mlpack: update

- mingw-w64-64tass/PKGBUILD
A new version was released yesterday.
> 64tass: update to 1.59.3120

- mingw-w64-qt5-static/0005-qtconnectivity-add-callback-attribute.patch
- mingw-w64-qt5-static/PKGBUILD
Adopt patch by @Biswa96 from ec6dda0bd483fb45d37f2438723913eee7e9b803.
> qt5-static: Fix building in 32 bit environment

- mingw-w64-glib2/0004-disable-explicit-ms-bitfields.patch
- mingw-w64-glib2/PKGBUILD
> glib2: Update to 2.78.0

- mingw-w64-gobject-introspection/0002-relocate-tools.patch
- mingw-w64-gobject-introspection/PKGBUILD
> gobject-introspection: Update to 1.78.0

- mingw-w64-python-pygame/002-camera-extension-fixes.patch
- mingw-w64-python-pygame/PKGBUILD
Updated pygame from 2.4.0 to 2.5.1
Fixes https://github.com/msys2/MINGW-packages/issues/18476
> [pygame] Update to 2.5.1

- mingw-w64-appstream/PKGBUILD
> Add appstream

- mingw-w64-libadwaita/PKGBUILD
depends on #18494 being in staging
> libadwaita: Update to 1.4.0

- mingw-w64-python-pygame/PKGBUILD
It's a simple bug fixes releases ([official patchnotes](https://github.com/pygame/pygame/releases/tag/2.5.2))
> python-pygame: update to 2.5.2

- mingw-w64-jj/PKGBUILD
notable changes:
- build with all features
- add split package for docs
- add completions for shells
> jj: update to 0.9.0

- mingw-w64-python-mutagen/PKGBUILD
- mingw-w64-yt-dlp/PKGBUILD
according to "pip check", pycryptodomex is still missing
> yt-dlp: add some missing dependencies

- mingw-w64-clblast/0001-CMake-Fix-DLL-install-directory-in-mingw.patch
- mingw-w64-clblast/0002-CMake-install-pkgconfig-file.patch
- mingw-w64-clblast/PKGBUILD
Also install pkgconfig file
Fixes https://github.com/msys2/MINGW-packages/issues/18577
> clblast: Fix DLL path in cmake files

- mingw-w64-freecad/001-fix-build-on-mingw.patch
- mingw-w64-freecad/PKGBUILD
Sorry, I couldn't make it build for UCRT64.
> [new-package] freecad 0.21.1

- mingw-w64-dia/PKGBUILD
Brings  both
- https://gitlab.gnome.org/GNOME/dia/-/merge_requests/101 
- https://gitlab.gnome.org/GNOME/dia/-/merge_requests/106
> dia: Use source with patches already applied

- mingw-w64-pkg-config/PKGBUILD
> pkg-config: build without stack protector

- mingw-w64-OpenSceneGraph/PKGBUILD
Backports https://github.com/openscenegraph/OpenSceneGraph/issues/946
> osg: Backport osgFadeText segfault fix

- mingw-w64-pkgconf/384ade5f316367f15da9dbf09853e06fe29bf2bf.patch
- mingw-w64-pkgconf/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/18634
Upstream issue: https://github.com/pkgconf/pkgconf/issues/326
> pkgconf: revert commit causing issues with PKG_CONFIG_PATH

- mingw-w64-meson/PKGBUILD
See https://github.com/mesonbuild/meson/issues/12271#issuecomment-1741686263
> meson: revert commit that breaks glib tools lookup

- mingw-w64-python-fastapi/PKGBUILD
> python-fastapi: Update to 0.103.2

- mingw-w64-mdbook/PKGBUILD
> mdbook: Update to 0.4.35

- mingw-w64-cargo-tauri/PKGBUILD
> cargo-tauri: New package

- mingw-w64-exiv2/004-BMFF-fix-handling-of-boxes-with-zero-length-or-type.patch
- mingw-w64-exiv2/PKGBUILD
> exiv2: backport some more fixes for 0.28.0

- mingw-w64-mdbook-pikchr/PKGBUILD
> mdbook-pikchr: Update to 0.1.7

- mingw-w64-python-h5pyd/PKGBUILD
> python-h5pyd: New package

- mingw-w64-glib2/0001-Add-support-for-TLS-callbacks-on-Windows.patch
- mingw-w64-glib2/PKGBUILD
> glib2: Backport patch to fix issue in static build

- mingw-w64-sqlite-orm/PKGBUILD
> sqlite-orm: New package

- mingw-w64-python-glfw/PKGBUILD
> python-glfw: New package

- mingw-w64-python-pyglm/PKGBUILD
> python-pyglm: New package

- mingw-w64-purpose/PKGBUILD
On the way to building kdenlive
> purpose: New package

- mingw-w64-libipt/PKGBUILD
* version bump
* changed to use tags instead of commit id
* adjustment to current version by disabling C11 threads
> libipt update

- mingw-w64-hidapi/0001-hidapi-cmake-add-soversion.patch
- mingw-w64-hidapi/PKGBUILD
Required for projects using cmake to detect hidapi
> hidapi: use cmake instead of autotools

- mingw-w64-qemu/PKGBUILD
see https://lists.gnu.org/archive/html/qemu-devel/2023-10/msg04870.html for details
> qemu: update to 8.1.2

- mingw-w64-cargo-create-tauri-app/PKGBUILD
> cargo-create-tauri-app: New package

- mingw-w64-emacs/003-Fix-touchpad-scrolling-on-MS-Windows.patch
- mingw-w64-emacs/PKGBUILD
> emacs: Fix touchpad scrolling on MS-Windows

- mingw-w64-upx/PKGBUILD
Maybe this helps with https://github.com/msys2/MSYS2-packages/issues/4111
> Add upx 4.1.0

- mingw-w64-pyqt6-sip/PKGBUILD
- mingw-w64-pyqt6/001-fix-build-with-Qt-6.6.patch
- mingw-w64-pyqt6/PKGBUILD
PyQt6 doesn't support Qt6 6.6 yet.
Disable QtBluetooth bindings for now.
> update pyqt6/pyqt6-sip to 6.5.3/13.6.0

- mingw-w64-meson/PKGBUILD
drop patch which is included in this new release
> meson: Update to 1.2.3

- mingw-w64-python-mysqlclient/0001-mysqlclient-setup-fix-linking.patch
- mingw-w64-python-mysqlclient/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/18911
> python-mysqlclient: Add package

- mingw-w64-glibmm-2.68/PKGBUILD
- mingw-w64-glibmm/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/18960
> glibmm: Fix static library linking with glib2

- mingw-w64-python-psutil/0001-mingw-fixes-without-loadlib.patch
- mingw-w64-python-psutil/0002-pyparsepid.patch
- mingw-w64-python-psutil/PKGBUILD
Issue 18460
https://github.com/msys2/MINGW-packages/issues/18460
> python-psutil: quick fix for psutil stack *** stack smashing detected ***

- mingw-w64-cmake/PKGBUILD
> cmake: Add cmcldeps as a separate package.

- mingw-w64-mpv/PKGBUILD
- mingw-w64-vapoursynth/0003-no-registry-setup-py.patch
- mingw-w64-vapoursynth/0004-vapoursynth-check-empty-registry.patch
- mingw-w64-vapoursynth/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/18989
> vapoursynth: update to 65

- mingw-w64-mpv/PKGBUILD
> mpv: switch to yt-dlp

- mingw-w64-faad2/PKGBUILD
* Port to cmake
* remove yasm dep, seems unused
* manually copy the man page, since that seems to be missing
> faad2: Update to 2.11.0

- mingw-w64-gnutls/PKGBUILD
the removed patch is included in this release
> gnutls: Update to 3.8.2

- mingw-w64-czkawka/PKGBUILD
this provides two separate packages for cli and gui version
> [new package] czkawka 6.1.0

- mingw-w64-nerd-fonts/PKGBUILD
> nerd-fonts: update to 3.1.0

- mingw-w64-qemu/PKGBUILD
see https://lists.gnu.org/archive/html/qemu-devel/2023-11/msg04715.html for details
> qemu: update to 8.1.3

- mingw-w64-openssl/002-relocation.patch
- mingw-w64-openssl/PKGBUILD
package-grokker shows nothing.
> openssl: update to 3.2.0

- mingw-w64-keepassxc/PKGBUILD
> keepassxc: Enable docs in arm64 builds

- mingw-w64-ngraph-gtk/PKGBUILD
set lt_cv_deplibs_check_method so we get a shared lib
> ngraph-gtk: cleanup and fix build

- mingw-w64-mruby/0001-use-setjmp-for-clang.patch
- mingw-w64-mruby/PKGBUILD
> mruby: use setjmp instead of __builtin_setjmp

- mingw-w64-inkscape/PKGBUILD
> inkscape: drop cython makedep

- mingw-w64-libplacebo/0001-add-cflags-private.patch
- mingw-w64-libplacebo/PKGBUILD
so that passing "--static --cflags" gives "-DPL_STATIC"
> libplacebo: add Cflags.private to .pc file; use xxhash

- mingw-w64-python-docx/PKGBUILD
- mingw-w64-python-docxcompose/PKGBUILD
- mingw-w64-python-docxtpl/PKGBUILD
Also added `python-docx` and `python-docxcompose`.
> python-docxtpl: New package

- mingw-w64-ripgrep/PKGBUILD
> ripgrep: update to 14.0.3

- mingw-w64-whisper.cpp/0003-server-fix-missing-lib.patch
- mingw-w64-whisper.cpp/0004-download-models-pwd.patch
- mingw-w64-whisper.cpp/PKGBUILD
This adds the download command, so to get a running server you just need to:
```console
whisper.cpp-download-ggml-model.sh base.en
whisper.cpp-server.exe
```
> whisper.cpp: Update to 1.5.1

- mingw-w64-slim-simulator/PKGBUILD
Just a very simple update to the new version. No major changes needed.
> Updating slim-simulator to v4.1

- mingw-w64-ngspice/PKGBUILD
- mingw-w64-ngspice/ngspice-CLANG32.install
- mingw-w64-ngspice/ngspice-CLANG64.install
- mingw-w64-ngspice/ngspice-CLANGARM64.install
- mingw-w64-ngspice/ngspice-MINGW32.install
- mingw-w64-ngspice/ngspice-MINGW64.install
- mingw-w64-ngspice/ngspice-UCRT64.install
Fixes https://github.com/msys2/MINGW-packages/issues/19283
Fixes https://github.com/msys2/MINGW-packages/issues/12535
> ngspice: Add console program

- mingw-w64-oh-my-posh/PKGBUILD
actually not familiar with Go, but build changes seems useful
> oh-my-posh: update to 19.2.1

- mingw-w64-asio/PKGBUILD
This reverts some hunks from 64bda161072457ec0a52c1ca3d52852b3cee0702 commit and installs pkgconfig file also.
See #19323 
@oscarfv @podsvirov
> asio: Re-add building with autotools

- mingw-w64-qt6-pdf/001-use-system-libs.patch
- mingw-w64-qt6-pdf/002-use-mingw-python3.patch
- mingw-w64-qt6-pdf/PKGBUILD
Actually It's part of QtWebEngine but I prefered to make it a separate package to not confuse users about the availability of qtwebengine.
> [new-package] qt6-pdf 6.6.1

- mingw-w64-cmake/PKGBUILD
Disable some components on i686
> cmake: update to 3.28.1

- mingw-w64-libplacebo-demos/PKGBUILD
> libplacebo-demos: Add package

- mingw-w64-fd/PKGBUILD
switched to make to simplify things
> fd: update to 9.0.0

- mingw-w64-watchexec/PKGBUILD
> watchexec: update to 1.24.2

- mingw-w64-gw/PKGBUILD
> GW version bump to v0.9.0

- mingw-w64-freerdp/0001-fix-some-cmake-warnings.patch
- mingw-w64-freerdp/0002-undef-interface.patch
- mingw-w64-freerdp/PKGBUILD
after cjson package cmake files were fixed
> freerdp: Enable Azure AD authentication (WITH_AAD=ON)

- mingw-w64-gw/PKGBUILD
> gw version v0.9.1

- mingw-w64-SDL2_image/PKGBUILD
- mingw-w64-libavif/PKGBUILD
> libavif: Build static library

- mingw-w64-netcdf/PKGBUILD
> netcdf: Fix static linking with libxml2

- mingw-w64-gnucobol/PKGBUILD
> gnucobol: Update to 3.2

- mingw-w64-grpc/002-fix-building-python-module.patch
- mingw-w64-grpc/PKGBUILD
Fixes #19541
based on @Biswa96 work.
> grpc: build python module

- mingw-w64-alacritty/PKGBUILD
https://github.com/alacritty/alacritty/pull/6846 is merged, so CLANGARM64 should work now. will remove draft after release
> alacritty: update to 0.13.0

- mingw-w64-libaec/PKGBUILD
upstream removed the executable
> libaec: Update to 1.1.2

- mingw-w64-picotool/PKGBUILD
Add picotool package from
https://github.com/raspberrypi/picotool
Inspired by picotool arch Linux package.
Statically linked libraries so users can use it outside msys too.
Final binary size is ~1.32MB
> feat: add picotool

- mingw-w64-libnpupnp/PKGBUILD
> libnpupnp: add

- mingw-w64-directxmath/PKGBUILD
Note that the version numbers did not increase this time.
> mingw-w64-directxmath - Update to latest hotfix version.

- mingw-w64-sl/PKGBUILD
> sl: new package

- mingw-w64-scalapack/0002-scalapack-fix-bindir.patch
- mingw-w64-scalapack/PKGBUILD
> scalapack: Fix binary installation directory

- mingw-w64-langkit_support/PKGBUILD
- mingw-w64-libadalang/PKGBUILD
for packages with older versions, to make sure they still build
> Some ada rebuilds

- mingw-w64-oh-my-posh/PKGBUILD
install completions with another style (inspired by Arch). set ldflags at build
> oh-my-posh: update to 19.4.0

- mingw-w64-openjph/0001-cmake-mingw-fixes.patch
- mingw-w64-openjph/PKGBUILD
I guess we drop 32-bit after all...
> openjph: update to 0.10.2

- mingw-w64-fpm/PKGBUILD
Updates fpm version, related GitHub Release: https://github.com/fortran-lang/fpm/releases
> fpm: update to 0.10.0

- mingw-w64-starship/PKGBUILD
take 2. hope it will work at this time
@jeremyd2019
> starship: apply another `libz-ng-sys` update

- mingw-w64-imagemagick/PKGBUILD
> imagemagick: Enable libtool option

- mingw-w64-sane/001-fix-build-on-mingw.patch
- mingw-w64-sane/PKGBUILD
for which I have a scanner.
still not working though
> sane: add the genesys backend

- mingw-w64-python-lsprotocol/PKGBUILD
- mingw-w64-python-pygls/PKGBUILD
- mingw-w64-python-pyhamcrest/PKGBUILD
- mingw-w64-python-ruff-lsp/PKGBUILD
> [new package] python-ruff-lsp 0.0.49

- mingw-w64-kvazaar/PKGBUILD
> kvazaar: Update to 2.3.0

- mingw-w64-libsecret/0001-port-to.mingw.patch
- mingw-w64-libsecret/0002-remove-dbus-portal.patch
- mingw-w64-libsecret/PKGBUILD
some minor patch refreshes and a missing include
> libsecret: Update to 0.21.2

- mingw-w64-kvazaar/PKGBUILD
See https://github.com/msys2/MINGW-packages/pull/19800#issuecomment-1898162038
> kvazaar: backport pkgconfig fix

- mingw-w64-soci/PKGBUILD
- mingw-w64-soci/soci-4.0.0.patch
- mingw-w64-soci/soci-cmake-sociconfig.patch
- mingw-w64-soci/soci-tests-catch.patch
- update patches
- enable test suite
- compile with c++14
> soci: update patches

- mingw-w64-emscripten/PKGBUILD
> emscripten: fix login scripts

- mingw-w64-python-psutil/0001-mingw-fixes-without-loadlib.patch
- mingw-w64-python-psutil/0003-avoid-duplicate-symbols.patch
- mingw-w64-python-psutil/PKGBUILD
Could someone test this package.
> python-psutil: update to 5.9.8

- mingw-w64-curl/0003-libpsl-static-libs.patch
- mingw-w64-curl/PKGBUILD
> curl: Update to 8.6.0

- .github/workflows/main.yml
To get rid of those warnings about node16
> CI: update configure-pagefile-action to 1.4

- mingw-w64-ctpl-git/PKGBUILD
This is in reality a downgrade since we lose a few commits after the 0.3.4 release.
> ctpl: Update to 0.3.4

- mingw-w64-calceph/PKGBUILD
> calceph: update to 3.5.5

- mingw-w64-python-h5py/PKGBUILD
> python-h5py: Rebuild for HD5 update

- mingw-w64-libbacktrace/0001-libbacktrace-no-undefined.patch
- mingw-w64-libbacktrace/PKGBUILD
- mingw-w64-libbacktrace/libbacktrace.pc
> libbacktrace: Fix prefix field in pkgconfig file

- mingw-w64-jq/PKGBUILD
> jq: Fix version number

- mingw-w64-giflib/001-mingw-build.patch
- mingw-w64-giflib/PKGBUILD
> giflib: Update to 5.2.2

- mingw-w64-pidgin/PKGBUILD
remove patch included in the release
> pidgin: Update to 2.14.13

- mingw-w64-lua-luarocks/0001-luarocks_msys2_mingw_w64.patch
- mingw-w64-lua-luarocks/PKGBUILD
Update Luarocks to version 3.9.2
> luarocks: Update to 3.9.2

- mingw-w64-stoken/PKGBUILD
Add the mingw-w64-stoken package.
> [new package] stoken 0.92

- mingw-w64-freerdp/0002-take-size_t-out-of-the-for-loop-declaration.patch
- mingw-w64-freerdp/PKGBUILD
> Update freerdp to 3.3.0

- mingw-w64-unrar/0001-fix-makefile.patch
- mingw-w64-unrar/PKGBUILD
> unrar: Update to 7.0.7

- mingw-w64-libzen/PKGBUILD
> new package: libzen

- mingw-w64-mediainfo/001-missing-rc-mingw.patch
- mingw-w64-mediainfo/PKGBUILD
Depends on https://github.com/msys2/MINGW-packages/pull/20245
> New package: mediainfo

- mingw-w64-libnice/PKGBUILD
remove patch included in the new release
> libnice: Update to 0.1.22

- mingw-w64-liblc3/PKGBUILD
> Add liblc3

- mingw-w64-mlt/0004-mingw64-presets.patch
- mingw-w64-mlt/PKGBUILD
> mlt: Update to 7.22.0

- mingw-w64-shotcut/PKGBUILD
Requires https://github.com/msys2/MINGW-packages/pull/18872
> shotcut: Update to 24.02

- mingw-w64-luajit/003-lua51-modules-paths.patch
- mingw-w64-luajit/PKGBUILD
This was previously changed in 703c7bae2f16853ecb254de2944d4fece2078920 commit.
Fixes #20297
> luajit: Fix module search path

- mingw-w64-luajit/PKGBUILD
> luajit: update to 2.1.1710088188

- mingw-w64-lite-xl/0001-lite-xl-meson-fix-install.patch
- mingw-w64-lite-xl/PKGBUILD
> lite-xl: add package

- mingw-w64-libqalculate/PKGBUILD
- mingw-w64-qalculate-gtk/PKGBUILD
- mingw-w64-qalculate-qt/PKGBUILD
Fixes #20181
Fixes #20180
Fixes #20179
> libqalculate, qalculate-qt, qalculate-gtk: add package

- mingw-w64-clang/0005-use-SOVERSION-on-mingw.patch
- mingw-w64-clang/PKGBUILD
Hopefully It fixes it this time.
> llvm: fix llvm-config (take-2)

- mingw-w64-librist/PKGBUILD
- mingw-w64-mbedtls/0001-mbedtls-pkgconfig-add-bcrypt.patch
- mingw-w64-mbedtls/PKGBUILD
For this thread https://github.com/m-ab-s/media-autobuild_suite/issues/2593
> mbedtls: Add pkgconfig file

- mingw-w64-breeze/001-breeze-settings-win32.patch
- mingw-w64-breeze/PKGBUILD
Reintroduces breeze-settings like the KF5 package has.
> breeze: Bring parity with KF5

- mingw-w64-kdenlive/PKGBUILD
- mingw-w64-kiconthemes/PKGBUILD
> New package: kdenlive 24.02.0 🎬

- mingw-w64-starship/PKGBUILD
all patches are included in the new release
> starship: update to 1.18.0

- mingw-w64-python-py2exe/001-setup-fix.patch
- mingw-w64-python-py2exe/PKGBUILD
> python-py2exe: Add missing memimporter module

- mingw-w64-libgit2/0003-libgit2-cmake-fix-pkgconfig.patch
- mingw-w64-libgit2/PKGBUILD
This fixes the pkgconfig issue as discussed in #20409
> libgit2: Fix pkgconfig file path relocation

- mingw-w64-delta/PKGBUILD
> delta: redesign the recipe

- mingw-w64-cargo-local-registry/PKGBUILD
> cargo-local-registry: redesign the recipe

- mingw-w64-starship/PKGBUILD
starship desn't use libgit2 anywhere
> starship: redesign the recipe

- mingw-w64-libraw/0002-libraw-datastream-utf8-api.patch
- mingw-w64-libraw/PKGBUILD
Cf. https://github.com/LibRaw/LibRaw/issues/632
> libraw: fix datastream API when running in UTF-8 locale

- mingw-w64-pkgconf/PKGBUILD
> pkgconf: update to 2.2.0

- mingw-w64-zoxide/PKGBUILD
> [new package] zoxide 0.9.4

- mingw-w64-directxtex/PKGBUILD
- mingw-w64-directxtk/PKGBUILD
- mingw-w64-efxc2/PKGBUILD
an improved version of fxc2 compiler from myself.
> New package - mingw-w64-efxc2.

- mingw-w64-pragtical/0001-pragtical-meson-fix-install.patch
- mingw-w64-pragtical/PKGBUILD
Based on `mingw-w64-lite-xl` by @Biswa96
Fixes #20199
> Add `mingw-w64-pragtical`

- mingw-w64-geany/0004-meson-Prevent-showing-console-after-running-geany-in.patch
- mingw-w64-geany/0005-meson-Add-icon-with-geany-program.patch
- mingw-w64-geany/PKGBUILD
Fixes #20520
Fixes #20519
Fixes #20518
> geany: Fix console window popup, add icon

- mingw-w64-geany/PKGBUILD
> geany: Install geany run helper to run built programs

- mingw-w64-fastfetch/PKGBUILD
Fix a regression introduced in v2.9.0
> fastfetch: update to 2.9.1

- mingw-w64-cddlib/PKGBUILD
This PR adds [cddlib](https://github.com/cddlib/cddlib), a library which provides "an efficient implementation of the Double Description Method"
> cddlib: new package

- mingw-w64-rust/PKGBUILD
https://blog.rust-lang.org/2024/04/09/cve-2024-24576.html
> rust: update to 1.77.2

- mingw-w64-shaderc/0001-fix-glslang-hlsl-linking-order.patch
- mingw-w64-shaderc/PKGBUILD
> shaderc: update to 2024.0

- mingw-w64-gcc/PKGBUILD
> gcc: enable plugin support (on x86_64)

- mingw-w64-mosquitto/0001-mosquitto-2.0.18-fix-static-libname.patch
- mingw-w64-mosquitto/0002-mosquitto-2.0.18-pkgconf-static-cflags.patch
- mingw-w64-mosquitto/PKGBUILD
> mosquitto: fix static linking

- mingw-w64-notepad++/PKGBUILD
- mingw-w64-notepad++/notepad++
Addresses https://github.com/msys2/MINGW-packages/issues/20490
> notepad++: fix exception on posix locale, use localization option

- mingw-w64-mosquitto/0002-mosquitto-2.0.18-pkgconf-static-cflags.patch
- mingw-w64-mosquitto/PKGBUILD
> mosquitto: Add openssl library in pkgconfig files for static linking

- mingw-w64-python-cx-freeze/PKGBUILD
> python-cx-freeze: update to 7.0.0

- mingw-w64-manim/PKGBUILD
~~`sed`ing is not required now~~
> manim: update to 0.18.0.post0

- mingw-w64-qemu/PKGBUILD
- mingw-w64-qemu/msys2.examples.tests.sh
I've added virglrenderer as dependency as proposed in https://github.com/msys2/MINGW-packages/issues/20280
Let's see...
> qemu: update to 9.0.0

- mingw-w64-python-cx-freeze/001-pr2357.patch
- mingw-w64-python-cx-freeze/PKGBUILD
https://github.com/marcelotduarte/cx_Freeze/pull/2357
> python-cx-freeze: backport PR2357

- mingw-w64-aom/PKGBUILD
Unfortunately I don't have the bandwidth to follow this up upstream...
> aom: disable SVE on ARM64 for now

- mingw-w64-calceph/PKGBUILD
switch from autotools to cmake.
> calceph: update to version 4.0.0

- mingw-w64-kcmutils-qt5/0001-kcmutils-qt5-workaround-kf6-conflict.patch
- mingw-w64-kcmutils-qt5/PKGBUILD
- mingw-w64-kconfig-qt5/0001-kconfig-qt5-workaround-kf6-conflict.patch
- mingw-w64-kconfig-qt5/PKGBUILD
- mingw-w64-kguiaddons-qt5/PKGBUILD
- mingw-w64-kio-qt5/002-kio-qt5-workaround-kf6-conflict.patch
- mingw-w64-kio-qt5/PKGBUILD
- mingw-w64-kwallet-qt5/PKGBUILD
- mingw-w64-purpose-qt5/0001-purpose-qt5-workaround-kf6-conflict.patch
- mingw-w64-purpose-qt5/PKGBUILD
Fixes #20379
@wszqkzqk @BLumia
> Resolve file conflicts between KF5 and KF6 packages

- mingw-w64-python-pytest-datafiles/PKGBUILD
I will use it to implement check() in python-cx-freeze.
> python-pytest-datafiles: add new package

- mingw-w64-gnutls/PKGBUILD
Upstream PR: https://gitlab.com/gnutls/gnutls/-/merge_requests/1830
Fixes #20736
> gnutls: backort regression fix

- mingw-w64-openssl/PKGBUILD
> openssl: fix .pc files

- mingw-w64-ninja/PKGBUILD
Both removed patches are part of the new release
> ninja: Update to 1.12.0

- mingw-w64-uutils-coreutils/PKGBUILD
the issue didn't disappear, but I found that generating doesn't fail for some progs. draft until I investigate it
> uutils-coreutils: update to 0.0.26

- mingw-w64-flang/PKGBUILD
- mingw-w64-libc++/PKGBUILD
- mingw-w64-libclc/PKGBUILD
- mingw-w64-lldb/PKGBUILD
- mingw-w64-llvm-openmp/PKGBUILD
- mingw-w64-mlir/PKGBUILD
- mingw-w64-polly/PKGBUILD
After #20792 only updated mingw-w64-llvm
> update remaining llvm packages to 18.1.5

- mingw-w64-kate/PKGBUILD
> kate: update to 24.02.2

- mingw-w64-libzip/0001-libzip-pkgconfig-add-cflags-private.patch
- mingw-w64-libzip/PKGBUILD
> libzip: Add Cflags.private in pkgconfig file

- mingw-w64-mcfgthread/PKGBUILD
https://github.com/lhmouse/mcfgthread/releases/tag/v1.8-ga
> mcfgthread: update to v1.8.1

- mingw-w64-mypaint/PKGBUILD
- mingw-w64-mypaint/mypaint-CLANG64.install
- mingw-w64-mypaint/mypaint-CLANGARM64.install
- mingw-w64-mypaint/mypaint-MINGW64.install
- mingw-w64-mypaint/mypaint-UCRT64.install
> mypaint: Fix brushes directory path relocation

- mingw-w64-kiconthemes/PKGBUILD
Fixes #20687
Thanks to Hannah von Reth (hvonreth) for all the suggestions and fixes in upstream.
> kiconthemes: Add breeze-icons dependency for loading icons from DLL

- mingw-w64-svt-av1/PKGBUILD
Switch from yasm to nasm, as recommended in the changelog
> svt-av1: Update to 2.1.0

- mingw-w64-xmake/PKGBUILD
What is https://github.com/msys2/MINGW-packages/actions/runs/9217271624/job/25358959159?pr=20987#step:11:1234? Although MINGW32/xmake works on my device.
> xmake: update to 2.9.2

- mingw-w64-curl/0001-Make-cURL-relocatable.patch
- mingw-w64-curl/PKGBUILD
> curl: Update to 8.8.0

- mingw-w64-glib2/PKGBUILD
> glib2: Enable introspection

- mingw-w64-libgit2/PKGBUILD
Required for static linking with rav1e
@1480c1
> libgit2: Add static library

- mingw-w64-libplist/002-dont-include-winmain-in-static.patch
- mingw-w64-libplist/003-fix-py-soext.patch
- mingw-w64-libplist/PKGBUILD
> libplist: update to 2.6.0

- mingw-w64-openfa/PKGBUILD
initial port of the library openfa
> [openfa] initial port of the version 20231011.0.2

- mingw-w64-swi-prolog/PKGBUILD
- Disable ODBC as it links to MSVC one.
- Remove tests package
> swi-prolog: link to mingw-w64-python

- mingw-w64-curl/0004-more-static-fixes.patch
- mingw-w64-curl/PKGBUILD
- mingw-w64-nghttp2/002-nghttp2-pkgconfig-add-cflags-private.patch
- mingw-w64-nghttp2/PKGBUILD
- mingw-w64-nghttp3/002-nghttp3-pkgconfig-add-cflags-private.patch
- mingw-w64-nghttp3/PKGBUILD
> curl: Fix static linking with nghttp2 and nghttp3

- mingw-w64-libslirp/PKGBUILD
> libslirp: allow static linking with LIBSLIRP_STATIC macro

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v868-about-taiwan/
> notepad++: Update to 8.6.8

- mingw-w64-duckdb/0001-duckdb-cmake-fix-lld-unknown-exclude-libs.patch
- mingw-w64-duckdb/0002-duckdb-cmake-fix-install-directory.patch
- mingw-w64-duckdb/0003-duckdb-cmake-fix-import-prefix-relocation.patch
- mingw-w64-duckdb/PKGBUILD
> duckdb: Add package

- mingw-w64-qqc2-desktop-style/PKGBUILD
> qqc2-desktop-style: New package

- mingw-w64-kdenlive/001-default-style.patch
- mingw-w64-kdenlive/PKGBUILD
> kdenlive: Default to Fusion style until org.kde.desktop can be used

- mingw-w64-zycore-c/PKGBUILD
- mingw-w64-zydis/PKGBUILD
> [new package] zydis 4.1.0

- mingw-w64-elisa/PKGBUILD
- mingw-w64-kirigami-addons/PKGBUILD
<details><summary> Elisa running in Windows 10 x86_64 🎧 🎵 </summary>
</details>
> elisa: Add package

- mingw-w64-python-aafigure/PKGBUILD
- mingw-w64-python-pyphen/PKGBUILD
- mingw-w64-python-rst2pdf/PKGBUILD
- mingw-w64-python-wheel/PKGBUILD
mingw-w64-python-aafigure - new package.
mingw-w64-python-pyphen - new package.
> mingw-w64-rst2pdf - add optional dependencies.

- mingw-w64-mcfgthread/PKGBUILD
This fixes some issues about MSVC.
https://github.com/lhmouse/mcfgthread/releases/tag/v1.8-ga.2
> mcfgthread: Update to 1.8.2

- mingw-w64-python-lief/0001-fmt-no-private-clang-header.patch
- mingw-w64-python-lief/PKGBUILD
> python-lief: rebuild; fix build for clang; restore mingw32

- mingw-w64-mold/PKGBUILD
Fix #15462
Tested it works (but no lto support).
> mold: don't use mimalloc which causes segfault

- mingw-w64-mold/PKGBUILD
and backport fix for lto support: https://github.com/rui314/mold/pull/1287
> mold: update to 2.32.0

- mingw-w64-blender/PKGBUILD
- mingw-w64-blender/ffmpeg-7-1.patch
- mingw-w64-blender/ffmpeg-7-2.patch
one PR was force pushed and merged in the meantime, so the checksum is different
> blender: backport ffmpeg 7 fixes

- mingw-w64-xevd/010-xevd-disable-werror.patch
- mingw-w64-xevd/PKGBUILD
https://github.com/mpeg5/xevd/
for ffmpeg
> xevd: Add 0.5.0

- mingw-w64-xeve/010-xeve-disable-werror.patch
- mingw-w64-xeve/PKGBUILD
https://github.com/mpeg5/xeve/
for ffmpeg
> xeve: Add 0.5.0

- mingw-w64-lua/PKGBUILD
> lua: update to 5.4.7

- mingw-w64-tiled/PKGBUILD
_This is a release candidate!_
> tiled: update to 1.11.0

- mingw-w64-zed/PKGBUILD
for a list of breaking changes see https://github.com/zed-industries/zed/releases/tag/v0.141.2
> zed: update to 0.141.3

- mingw-w64-eza/PKGBUILD
> [new package] eza 0.18.21

- mingw-w64-ghostscript/001-mingw-build.patch
- mingw-w64-ghostscript/PKGBUILD
* refresh patch
* disable new compiler error
> ghostscript: Update to 10.03.1

- mingw-w64-luafilesystem/001-makefile-for-mingw.patch
- mingw-w64-luafilesystem/PKGBUILD
According to the [LuaFileSystem homepage](https://lunarmodules.github.io/luafilesystem/):
> LuaFileSystem is a [Lua](http://www.lua.org/) library developed to complement the set of functions related to file systems offered by the standard Lua distribution.
> 
> LuaFileSystem offers a portable way to access the underlying directory structure and file attributes.
> 
> LuaFileSystem is free software and uses the same [license](https://lunarmodules.github.io/luafilesystem/license.html) as Lua 5.x (MIT).
At the moment, LuaFileSystem is the second most downloaded Lua library (+8.3M) on [LuaRocks](https://luarocks.org/), the main package manager to share Lua modules.
In the PKGBUILD script provided here, it is building LuaFileSystem for every mingw_arch, and every Lua version available here …
> [new-package] luafilesystem

- mingw-w64-boost/PKGBUILD
- mingw-w64-boost/boost-1.85.0-container-aliasing.patch
backport patch taken from gentoo (thanks!)
Fixes #17977
> boost: backport fix for fix aliasing violation in boost::container

- mingw-w64-volk/0001-volk-remove-full-python-path-shebang.patch
- mingw-w64-volk/0002-volk-modtool-remove-py-extension.patch
- mingw-w64-volk/PKGBUILD
> volk: Remove full python path in shebang

- mingw-w64-python-maturin/PKGBUILD
added a prepare step for dependencies fetch
> python-maturin: update to 1.7.0

- mingw-w64-gst-libav/0001-libav-ffmpeg7.patch
- mingw-w64-gst-libav/PKGBUILD
- mingw-w64-gst-plugins-base/0001-plugins-base-ffmpeg7.patch
- mingw-w64-gst-plugins-base/PKGBUILD
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/7148
> gstreamer: backport ffmpeg v7 compat patch

- mingw-w64-ossia-score/PKGBUILD
NB: i'm the software author :)
> ossia-score: update to 3.2.4

- mingw-w64-tme/PKGBUILD
Latest changes to tme, including preliminary support for separate openvpn library, emscripten build support, etc. Enhanced support for multiple display hosts.
> tme: Update to 0.12rc12

- mingw-w64-gw/PKGBUILD
> Updated to GW v0.10.1

- mingw-w64-chafa/PKGBUILD
> chafa: enable man and gtk-doc

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v869-about-taiwan/
> notepad++: Update to 8.6.9

- mingw-w64-python-igraph/PKGBUILD
This fixes #21316, also thank you for the feedback on texttable
also related
https://github.com/igraph/python-igraph/issues/769
https://github.com/igraph/python-igraph/issues/574
> add package python-igraph

- mingw-w64-python-py2exe/211.patch
- mingw-w64-python-py2exe/PKGBUILD
https://github.com/py2exe/py2exe/pull/211
> py2exe: fix build with newer setuptools

- mingw-w64-zed/PKGBUILD
draft for now as https://github.com/zed-industries/zed/issues/13575 is still here
> zed: update to 0.144.4

- mingw-w64-qt5-static/PKGBUILD
> qt5-static: fix prl files

- mingw-w64-bat/PKGBUILD
and switch to git source while at it
fixes #21462
> bat: add completions

- mingw-w64-gitoxide/PKGBUILD
it's still far from being a `git` replacement, but some good features are already implemented
> [new package] gitoxide 0.37.0

- mingw-w64-fastfetch/PKGBUILD
https://github.com/fastfetch-cli/fastfetch/releases/tag/2.20.0
> fastfetch: update to 2.20.0

- mingw-w64-nodejs/0008-Link-with-municode-and-extern-wmain-for-Unicode.patch
- mingw-w64-nodejs/0101-node-buildflags-fixes.patch
- mingw-w64-nodejs/PKGBUILD
> nodejs: update to 22.5.1

- mingw-w64-libavif/PKGBUILD
remove patch included in the new release
> libavif: Update to 1.1.1

- mingw-w64-curl/PKGBUILD
https://github.com/curl/curl/pull/14285#issuecomment-2259880050
> curl: Update to 8.9.1

- mingw-w64-rust/0007-clang-subsystem.patch
- mingw-w64-rust/PKGBUILD
> rust: update to 1.80.0

- mingw-w64-mcfgthread/PKGBUILD
https://github.com/lhmouse/mcfgthread/releases/tag/v1.8-ga.3
> mcfgthread: Update to 1.8.3

- mingw-w64-ollama/0001-use-ninja-cc.patch
- mingw-w64-ollama/0002-remove-cmake-arch.patch
- mingw-w64-ollama/PKGBUILD
* refresh patches
* remove dependency on make+gcc
> ollama: Update to 0.1.45

- mingw-w64-fastfetch/PKGBUILD
https://github.com/fastfetch-cli/fastfetch/releases/tag/2.21.0
> fastfetch: update to 2.21.0

- mingw-w64-rust-analyzer/PKGBUILD
~and add `rust` as `rust-src` dependency~
> [new package] rust-analyzer 20240805

- mingw-w64-ffmpeg4.4/PKGBUILD
drops some patches included in the release
> ffmpeg4.4: Update to 4.4.5

- mingw-w64-wabt/0001-replace-arm64-with-aarch64.patch
- mingw-w64-wabt/PKGBUILD
- The WebAssembly Binary Toolkit is a suite of tools for WebAssembly
- It has a wasm-strip tool, which can be used to strip objects for wasm.
> New package: wabt

- mingw-w64-vlc/0100-more-ffmpeg7-fixes.patch
- mingw-w64-vlc/5574.patch
- mingw-w64-vlc/PKGBUILD
> vlc: backport ffmpeg7 fixes

- mingw-w64-gr/PKGBUILD
and remove unused QHULL_VERSION_STRING build option
> gr: Update to 0.73.7

- mingw-w64-headers-git/PKGBUILD
See https://github.com/mingw-w64/mingw-w64/issues/57
> mingw-w64-headers: revert a recent potentially problematic commit

- mingw-w64-rufus/PKGBUILD
- mingw-w64-rufus/ucrt-build.patch
test target is not defined, removing
> rufus: enable ucrt64

- mingw-w64-qt5-static/0012-mingw-add-extra-flags.patch
- mingw-w64-qt5-static/PKGBUILD
> qt5-static: revert unnecessary sed

- mingw-w64-liboqs/0001-build-shared.patch
- mingw-w64-liboqs/PKGBUILD
liboqs is a C library for prototyping and experimenting with quantum-resistant cryptography
> add liboqs 0.10.0

- mingw-w64-fastfetch/PKGBUILD
Actually no changes to Windows side...
> fastfetch: update to 2.21.3

- mingw-w64-codeblocks/001-makefile-wxsmith-add-no-undefined.patch
- mingw-w64-codeblocks/PKGBUILD
> codeblocks: Enable wxSmith plugin

- mingw-w64-libmd/PKGBUILD
> libmd: Add package

- mingw-w64-wasm-pack/PKGBUILD
- mingw-w64-wasm-pack/bzip2-use-pkgconfig.patch
- mingw-w64-wasm-pack/zstd-sys-remove-statik.patch
> wasm-pack: update to 0.13.0

- mingw-w64-blake3/PKGBUILD
> blake3: update to 1.5.4

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/7a6c241e4...121331cff
> mingw-w64: Update to 121331cffd

- mingw-w64-swi-prolog/PKGBUILD
I have split the package into the components defined by cmake_install.cmake (core, packages, archive etc.)
> SWI-Prolog: new version 9.2.6

- mingw-w64-hub/PKGBUILD
> hub: Fix installation directory of shell completions

- mingw-w64-libkqueue/PKGBUILD
This MR adds a libkqueue package to MINGW-packages
> Add Libkqueue Package

- mingw-w64-libkqueue/0001-libkqueue-cmake-remove-werror.patch
- mingw-w64-libkqueue/0002-libkqueue-cmake-fix-static-library-name.patch
- mingw-w64-libkqueue/0003-libkqueue-cmake-fix-install-directory.patch
- mingw-w64-libkqueue/0004-libkqueue-fix-pkgconfig-file.patch
- mingw-w64-libkqueue/PKGBUILD
> libkqueue: Fix static library name, install directory and pkgconfig file

- mingw-w64-ffmpeg/PKGBUILD
> ffmpeg: Enable drawtext feature

- mingw-w64-flann/0001-flann-remove-fullpath-pkgconfig.patch
- mingw-w64-flann/0002-flann-cmake-fix-omp-library.patch
- mingw-w64-flann/PKGBUILD
> flann: add package

- mingw-w64-libultrahdr/PKGBUILD
Cf. https://archlinux.org/packages/extra/x86_64/libultrahdr/
> libultrahdr: new package

- mingw-w64-wezterm/PKGBUILD
- mingw-w64-wezterm/mingw-build.patch
> [new package] wezterm 20240203.110809.5046fc22

- mingw-w64-imagemagick/PKGBUILD
Oops, too soon, obviously not in staging yet... 😊
> imagemagick: enable uhdr coder

- mingw-w64-libultrahdr/PKGBUILD
Also added `angleproject` to deps to enable EGL features.
> libultrahdr: rebuild for tag change

- mingw-w64-cbindgen/PKGBUILD
> [new package] cbindgen 0.27.0

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/121331cff...c6bf4bdf6
> mingw-w64: Update to c6bf4bdf65

- mingw-w64-neocmakelsp/PKGBUILD
> neocmakelsp: init at 0.8.1

- mingw-w64-neocmakelsp/0001-neocmakelsp-meson-disable-cargo-build.patch
- mingw-w64-neocmakelsp/PKGBUILD
> neocmakelsp: Fix package by building cargo and meson projects separately

- mingw-w64-ansifilter/PKGBUILD
> ansifilter: init at 2.20

- mingw-w64-hayagriva/PKGBUILD
> hayagriva: init at 0.5.3

- mingw-w64-angleproject/002-buildflags-fixes.patch
- mingw-w64-angleproject/PKGBUILD
> angleproject: remove extra suffix on static libs

- mingw-w64-fastfetch/PKGBUILD
https://github.com/fastfetch-cli/fastfetch/releases/tag/2.23.0
> fastfetch: update to 2.23.0

- mingw-w64-angleproject/001-add-mingw-toolchain.patch
- mingw-w64-angleproject/PKGBUILD
Can someone test building this on arm64?
> angleproject: fix building on arm64

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/c6bf4bdf6...5c63f0a96
> mingw-w64: Update to 5c63f0a966

- mingw-w64-asm-lsp/PKGBUILD
> asm-lsp: add package

- mingw-w64-mcfgthread/PKGBUILD
https://github.com/lhmouse/mcfgthread/releases/tag/v1.8-ga.4
> mcfgthread: Update to 1.8.4

- mingw-w64-swi-prolog/01-console-add-stdbool.patch
- mingw-w64-swi-prolog/02-xpce-create-fix-declaration.patch
- mingw-w64-swi-prolog/PKGBUILD
minor fixes in subpackage organization
added swi-prolog-x (graphics subsystem)
> swi-prolog: new version 9.2.7

- mingw-w64-ark/0001-ark-define-QT_STAT_LNK-macro.patch
- mingw-w64-ark/0002-ark-disable-zip-plugin.patch
- mingw-w64-ark/PKGBUILD
I have used the ucrt64 ark package in Windows 10 to open a .tar.xz file.
<details><summary>Click here to see the screenshot of ark</summary>
</details>
> ark: add package

- mingw-w64-gobject-introspection/PKGBUILD
patch is included in the new release
> gobject-introspection: Update to 1.82.0

- mingw-w64-gtk-doc/0001-exeext.patch
- mingw-w64-gtk-doc/PKGBUILD
> gtk-doc: Update to 1.34.0

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v87-about-taiwan/
> notepad++: Update to 8.7

- mingw-w64-rssguard/001-cmake-update.patch
- mingw-w64-rssguard/002-comply-to-fhs.patch
- mingw-w64-rssguard/003-fix-default-setting.patch
- mingw-w64-rssguard/004-misc-fixes.patch
- mingw-w64-rssguard/PKGBUILD
- lite version for now (without qt6-webengine)
> rssguard: 4.7.3 [new package]

- mingw-w64-kcontacts/PKGBUILD
- mingw-w64-kdeconnect/0001-kdeconnect-workaround-missing-in4addr_any.patch
- mingw-w64-kdeconnect/0002-kdeconnect-workaround-disable-plugins.patch
- mingw-w64-kdeconnect/0003-kdeconnect-remove-in-sal.patch
- mingw-w64-kdeconnect/PKGBUILD
- mingw-w64-kpeople/PKGBUILD
I have used the ucrt64 kdeconnect package in Windows 10 with an Android phone.
<details><summary>Click here to see the screenshot of kdeconnect</summary>
</details>
> kdeconnect: add package

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/5c63f0a96...0be496546
> mingw-w64: Update to 0be496546a

- mingw-w64-fastfetch/PKGBUILD
> fastfetch: update 2.26.1

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/0be496546...335ffe5b7
> mingw-w64: Update to 335ffe5b71

- mingw-w64-codeblocks/006-Update-ax_cxx_compile_stdcxx.m4.patch
- mingw-w64-codeblocks/007-makefile-wxsmith-plugin-export-fix.patch
- mingw-w64-codeblocks/PKGBUILD
> mingw-w64-codeblocks: Changed wxSmith plugin build fix and

- mingw-w64-kdeconnect/0002-kdeconnect-cmake-add-fexceptions.patch
- mingw-w64-kdeconnect/0003-kdeconnect-remove-in-sal.patch
- mingw-w64-kdeconnect/PKGBUILD
mingw-w64 was missing some symbols for those plugins which were added in https://github.com/mingw-w64/mingw-w64/commit/d08d56ea1f355eda0519407dad45376a5c719998
> kdeconnect: Enable pausemusic and systemvolume plugins

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/335ffe5b7...8f7b5ce36
> mingw-w64: Update to 8f7b5ce363

- mingw-w64-helix/PKGBUILD
- mingw-w64-helix/fix-runtime-dir.patch
- mingw-w64-helix/helix.sh
> helix: fix hx.exe installation dir

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/8f7b5ce36...6cd6fee9c
> mingw-w64: Update to 6cd6fee9c0

- mingw-w64-pyinstaller-hooks-contrib/PKGBUILD
- mingw-w64-pyinstaller/PKGBUILD
- mingw-w64-python-altgraph/PKGBUILD
Also added `pyinstaller-hooks-contrib` 2024.8 and `python-altgraph` 0.17.4.
> [new package] pyinstaller 6.10.0

- mingw-w64-pyinstaller/PKGBUILD
Anybody can check this for `CLANGARM64`?
> pyinstaller: add cc to makedepends

- mingw-w64-imagemagick/001-7.1.1.39-relocate.patch
- mingw-w64-imagemagick/PKGBUILD
~~Looks like the patch needs updating, not sure when I'll get around to it...~~
> imagemagick: update to 7.1.1.39

- mingw-w64-minidump-stackwalk/PKGBUILD
what about packaging more utilities from rust-minidump?
> minidump-rustwalk: update to 0.22.2

- mingw-w64-python-archinfo/PKGBUILD
> [new package] python-archinfo

- mingw-w64-python-scikit-build-core/PKGBUILD
depends on #22227
It will be used to build LIEF 0.15.1
> python-scikit-build-core: new package

- mingw-w64-cargo-c/.gitignore
- mingw-w64-cargo-c/001-add-lib-prefix-on-windows-gnu.patch
- mingw-w64-cargo-c/PKGBUILD
> cargo-c: update to 0.10.5

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/cdf6b16b8...ac299df46
> mingw-w64: Update to ac299df46a

- mingw-w64-python-mpi4py/PKGBUILD
It compiles on my computer because I have Microsoft's msmpi SDK installed, I don't know what will happen on the CI.
> Add python-mpi4py package

- mingw-w64-gitoxide/.gitignore
- mingw-w64-gitoxide/PKGBUILD
- mingw-w64-gitoxide/ntapi-link-ntdll-arm64.patch
> gitoxide: update to 0.38.0

- mingw-w64-qt6-graphs/PKGBUILD
- mingw-w64-qt6-grpc/PKGBUILD
- mingw-w64-qt6-httpserver/PKGBUILD
- mingw-w64-qt6-imageformats/PKGBUILD
- mingw-w64-qt6-location/PKGBUILD
- mingw-w64-qt6-lottie/PKGBUILD
- mingw-w64-qt6-networkauth/PKGBUILD
- mingw-w64-qt6-pdf/001-use-system-libs.patch
- mingw-w64-qt6-pdf/PKGBUILD
- mingw-w64-qt6-positioning/PKGBUILD
- mingw-w64-qt6-quick3dphysics/PKGBUILD
- mingw-w64-qt6-quickeffectmaker/PKGBUILD
- mingw-w64-qt6-remoteobjects/PKGBUILD
- mingw-w64-qt6-scxml/PKGBUILD
- mingw-w64-qt6-sensors/PKGBUILD
- mingw-w64-qt6-serialbus/PKGBUILD
- mingw-w64-qt6-serialport/PKGBUILD
- mingw-w64-qt6-speech/PKGBUILD
- mingw-w64-qt6-virtualkeyboard/PKGBUILD
- mingw-w64-qt6-webchannel/PKGBUILD
- mingw-w64-qt6-websockets/PKGBUILD
- mingw-w64-qt6-webview/PKGBUILD
> qt6: update to 6.8.0 - Part2

- mingw-w64-tomlplusplus/PKGBUILD
> [new package] tomlplusplus 3.4.0

- mingw-w64-qt6-base/PKGBUILD
> qt6-base: Avoid recursion in time-zone abbreviation look-up with ICU

- mingw-w64-mesonlsp/.gitignore
- mingw-w64-mesonlsp/PKGBUILD
> [new package] mesonlsp 4.3.7

- mingw-w64-rnnoise/PKGBUILD
> [new package] rnnoise 0.2

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
to apply https://sourceforge.net/p/mingw-w64/mingw-w64/ci/99684a93993bd8288993c0f47014624523bca0cf/
> update mingw-w64 to 0d4221712

- mingw-w64-paraview/005-avoid-file-conflict-with-vtk.patch
- mingw-w64-paraview/PKGBUILD
> paraview: avoid file conflict with VTK

- mingw-w64-mcfgthread/PKGBUILD
https://github.com/lhmouse/mcfgthread/releases/tag/v1.9-ga.1
> mcfgthread: Upgrade to 1.9.1

- mingw-w64-python-pipx/PKGBUILD
- mingw-w64-python-userpath/PKGBUILD
> python-pipx: new package

- mingw-w64-libheif/PKGBUILD
PR included in the new release
> libheif: Update to 1.19.1

- mingw-w64-mcfgthread/PKGBUILD
@lhmouse that's what I meant :) 
I suppose that tag has ${major}.${minor}-ga.${patch} format, so this pkgver expansion should be always correct. pushed repo checksums while at it
> mcfgthread: apply small fixes

- mingw-w64-wakatime/.gitignore
- mingw-w64-wakatime/PKGBUILD
> [new package] wakatime 1.102.5

- mingw-w64-typst-lsp/.gitignore
- mingw-w64-typst-lsp/PKGBUILD
> [new package] typst-lsp 0.13.0

- mingw-w64-fastfetch/PKGBUILD
https://github.com/fastfetch-cli/fastfetch/releases/tag/2.29.0
> fastfetch: update to 2.29.0

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v871-released/
> notepad++: Update to 8.7.1

- mingw-w64-headers-git/0001-remove-ireference-boolean.patch
- mingw-w64-headers-git/PKGBUILD
> headers-git: Workaround redefinition error in windows.foundation.h

- mingw-w64-python-setuptools/0011-add-support-for-windmc.patch
- mingw-w64-python-setuptools/PKGBUILD
- update to latest
- add support for windmc
> setuptools: update to 75.3.0

- mingw-w64-gimp3/0001-clang-rc-files-fix.patch
- mingw-w64-gimp3/0003-dont-install-external-files.patch
- mingw-w64-gimp3/PKGBUILD
Needs https://github.com/msys2/MINGW-packages/pull/22434
> gimp3: Update to RC1

- mingw-w64-jsoncpp/PKGBUILD
- disable object library
- install license file
> jsoncpp: disable object library

- mingw-w64-curl/PKGBUILD
See https://github.com/curl/curl/issues/15496 and https://github.com/curl/curl/issues/15513
> curl: Fix regression reading netrc

- mingw-w64-libgit2/PKGBUILD
See https://github.com/msys2/MINGW-packages/issues/22459#issuecomment-2466576725
> libgit2: backport a feature for nix

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/c6857dc97...cf5c50cce
> mingw-w64: Update to cf5c50cce0

- mingw-w64-zed/PKGBUILD
> zed: update to 0.161.2

- mingw-w64-python-qmk/PKGBUILD
> python-qmk: update to 1.1.6

- mingw-w64-gdal/PKGBUILD
> gdal: rebuild

- mingw-w64-tme/PKGBUILD
This release candidate contains some improvements and enhancements to functionality. Most notably, it adds support for automatic decompression of gzip files from tapes for faster installation. It also fixes an issue with some ARM64 platforms.
> tme: Update to 0.12rc14

- mingw-w64-fastfetch/PKGBUILD
Also remove mingw64 which is known to be buggy
> fastfetch: update to 2.30.1

- mingw-w64-vigra/0020-Fix-llvm19-build.patch
- mingw-w64-vigra/PKGBUILD
See https://github.com/ukoethe/vigra/issues/591
> vigra: llvm19 build fixes

- mingw-w64-gedit-plugins/PKGBUILD
- mingw-w64-gedit/PKGBUILD
gedit: update list of dependencies.
> gedit: update list of dependencies

- mingw-w64-premake/PKGBUILD
> premake: Update to 5.0beta3

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v872-released/
> notepad++: Update to 8.7.2

- mingw-w64-wasm-bindgen/Cargo.lock
- mingw-w64-wasm-bindgen/PKGBUILD
closes https://github.com/msys2/MINGW-packages/security/dependabot/4
> wasm-bindgen: update lockfile

- mingw-w64-libultrahdr/001-pkg-config.patch
- mingw-w64-libultrahdr/PKGBUILD
Reported [upstream](https://github.com/google/libultrahdr/issues/289), but they seem unsure of it yet...
> libultrahdr: tweak pc cflags

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v873-released/
> notepad++: Update to 8.7.3

- mingw-w64-pkcs11-helper/PKGBUILD
pkcs11-helper is a relatively popular package, see here: https://repology.org/project/pkcs11-helper/packages
> [new-package] pkcs11-helper 1.30.0

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v874-released/
> notepad++: Update to 8.7.4

- mingw-w64-zed/.gitignore
- mingw-w64-zed/PKGBUILD
> zed: update to 0.164.2

- mingw-w64-python-rtree/0001-fix-mingw-finder.patch
- mingw-w64-python-rtree/PKGBUILD
Tested and working with `spyder`
> python-rtree: update to 1.3.0

- mingw-w64-itstool/0001-Fix-the-crash-from-912099.patch
- mingw-w64-itstool/0002-Fix-insufficiently-quoted-regular-expressions.patch
- mingw-w64-itstool/PKGBUILD
* Import two patches from ArchLinux repository.
* Change python3 to python in dependency list.
* Change http to https in URLs.
* Fixes  #22755
> itstool: Fix insufficiently quoted regular expressions

- mingw-w64-verilator/PKGBUILD
> verilator: update to 5.030

- mingw-w64-qemu/PKGBUILD
see https://wiki.qemu.org/ChangeLog/9.2
> qemu: Update to 9.2.0

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/8bcd5fc1a...a2d19218d
> mingw-w64: Update to a2d19218dd

- mingw-w64-ruff/PKGBUILD
> ruff: update to 0.8.3

- mingw-w64-libdispatch/PKGBUILD
> libdispatch: update to 6.0.3

- mingw-w64-c3c/PKGBUILD
- mingw-w64-c3c/install-man.patch
> c3c: update to 0.6.5

- mingw-w64-meson/PKGBUILD
> meson: Update to 1.6.1

- mingw-w64-fastfetch/PKGBUILD
https://github.com/fastfetch-cli/fastfetch/releases/tag/2.32.1
> fastfetch: update to 2.32.1

- mingw-w64-calculix-ccx/PKGBUILD
- mingw-w64-calculix-ccx/ccx_numeric_format.patch
Fixes #22630 
@3rav could you test artifacts for UCRT64, after It finishes building.
> calculix-ccx: Fix numeric output format on UCRT64.

- mingw-w64-filezilla/PKGBUILD
- mingw-w64-libfilezilla/PKGBUILD
- mingw-w64-libfilezilla/add-specialization-for-char_traits-uint8_t.patch
> filezilla: update to 3.68.1

- mingw-w64-wezterm/PKGBUILD
> wezterm: add missing libssh2 dep

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v875-released/
> notepad++: Update to 8.7.5

- mingw-w64-zig/PKGBUILD
> zig: update to 0.14.0-dev.2487

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/03d8a40f5...63f3f2846
> mingw-w64: Update to 63f3f28463

- mingw-w64-vk-bootstrap/PKGBUILD
Add this new and popular package that makes vulkan development way easier than it used to be.
This package should be synced with vulkan-headers in version number.
> Add vk-bootstrap

- mingw-w64-vulkan-memory-allocator/PKGBUILD
Update vulkan memory allocator to 3.2
> update vma to 3.2

- mingw-w64-python-spyder/PKGBUILD
detected at https://github.com/msys2/MINGW-packages/actions/runs/12596575672/job/35108092042?pr=22979#step:8:550
> python-spyder: fix dependencies list

- mingw-w64-kdiagram/PKGBUILD
> kdiagram: add package

- mingw-w64-keepawake/PKGBUILD
drop libgit2 from depends; fix build
> keepawake: rebuild

- mingw-w64-gpgme/PKGBUILD
- mingw-w64-gpgme/relocatable-cmake.patch
> gpgme: Relocate paths in qgpgme-qt6 cmake file

- mingw-w64-stlink/0001-cmake-find-libusb.patch
- mingw-w64-stlink/0002-cmake-remove-broken-things.patch
- mingw-w64-stlink/0003-chip-config-relocate.patch
- mingw-w64-stlink/PKGBUILD
* refresh patches
* split out general build fixes out of the libusb patch
* add patch for relocation of new config files
Fixes #23063
> stlink: Update to 1.8.0

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/63f3f2846...ce0d0bfb7
> mingw-w64: Update to ce0d0bfb70

- mingw-w64-sdl3/PKGBUILD
> SDL3: add package

- mingw-w64-fastfetch/PKGBUILD
https://github.com/fastfetch-cli/fastfetch/releases/tag/2.34.1
> fastfetch: update to 2.34.1

- mingw-w64-vulkan-volk/PKGBUILD
> vulkan-volk: Update to 1.4.304

- mingw-w64-gitui/PKGBUILD
> gitui: update to 0.27.0

- mingw-w64-pango/0001-disable-dwrite.patch
- mingw-w64-pango/PKGBUILD
> pango: Update to 1.56.1

- mingw-w64-cargo-c/001-add-lib-prefix-on-windows-gnu.patch
- mingw-w64-cargo-c/PKGBUILD
> cargo-c: update to 0.10.9

- mingw-w64-7zip/PKGBUILD
It should be standalone.
Fixes #23182
> 7zip: statically link 7zCon.sfx

- mingw-w64-meshoptimizer/PKGBUILD
Add this new package, widely used in game industry (according to their homepage).
This package also provided [`gltfpack`](https://meshoptimizer.org/gltf/).
> [New package]: Meshoptimizer

- mingw-w64-hackrf/001-libusb.patch
- mingw-w64-hackrf/002-fftw.patch
- mingw-w64-hackrf/PKGBUILD
A new package for interacting with an RF device called HackRF :)
> hackrf: Initial package

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v876-released/
> notepad++: Update to 8.7.6

- mingw-w64-mcfgthread/PKGBUILD
https://github.com/lhmouse/mcfgthread/releases/tag/v2.0-ga.1
> mcfgthread: Update to 2.0.1

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/ce0d0bfb7...ea22a99cb
> mingw-w64: Update to ea22a99cb0

- mingw-w64-turbo/.gitignore
- mingw-w64-turbo/PKGBUILD
> turbo: update to 2.4.0

- mingw-w64-python-zxing-cpp/0001-setup-check-msc-python.patch
- mingw-w64-python-zxing-cpp/PKGBUILD
> python-zxing-cpp: Add package

- mingw-w64-python-cx-freeze/PKGBUILD
> python-cx-freeze 7.2.9 with arm64 support [WIP]

- mingw-w64-zed/.gitignore
- mingw-w64-zed/PKGBUILD
- remove backports
- cleanup deps
> zed: update to 0.172.8

- mingw-w64-yazi/PKGBUILD
versioning scheme has been changed upstream
> yazi: update to 25.2.7

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v877-released/
> notepad++: Update to 8.7.7

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/ea22a99cb...9e8f2a7b5
> mingw-w64: Update to 9e8f2a7b5d

- mingw-w64-raylib/PKGBUILD
> Unvendor glfw from raylib

- mingw-w64-turbo/.gitignore
- mingw-w64-turbo/PKGBUILD
> turbo: update to 2.4.1

- mingw-w64-libgd/PKGBUILD
See https://github.com/msys2/MINGW-packages/issues/23346
> libgd: drop libimagequant for mingw32

- mingw-w64-python-pillow/PKGBUILD
See https://github.com/msys2/MINGW-packages/issues/23346
> python-pillow: drop libimagequant for mingw32

- mingw-w64-libimagequant/PKGBUILD
> libimagequant: re-create broken importlib with dlltool

- mingw-w64-qemu/PKGBUILD
see https://gitlab.com/qemu-project/qemu/-/commits/stable-9.2
> qemu: Update to 9.2.1

- mingw-w64-python/PKGBUILD
See https://github.com/python/cpython/pull/130049
We also didn't notice
> python: build with full lto

- mingw-w64-cargo-c/PKGBUILD
> cargo-c: backport implib generation fix

- mingw-w64-zed/PKGBUILD
- mingw-w64-zed/aws-lc-clang-build.patch
thank you, @mati865, for pointing to a fix
> zed: restore clang64

- mingw-w64-gtk3/PKGBUILD
> gtk3: backport keyboard layout change crash fix

- mingw-w64-python-aenum/PKGBUILD
Added `python-aenum` package.
```
>>> from aenum import Enum
>>> class Color(Enum):
...     RED = 1
...     GREEN = 2
...     BLUE = 3
>>> Color.RED
<Color.RED: 1>
>>> Color.BLUE
<Color.BLUE: 3>
```
> [new package] python-aenum 3.1.15

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/9e8f2a7b5...079e6092b
> mingw-w64: Update to 079e6092b3

- mingw-w64-vulkan-memory-allocator/PKGBUILD
> Vulkan Memory Allocator: update to 3.2.1

- mingw-w64-zstd/PKGBUILD
- mingw-w64-zstd/zstd-1.4.0-fileio-mingw.patch
> zstd: Update to 1.5.7

- mingw-w64-eza/PKGBUILD
> eza: update to 0.20.22

- mingw-w64-uv/PKGBUILD
> uv: update to 0.6.2

- mingw-w64-sqlitestudio/001-destdir.patch
- mingw-w64-sqlitestudio/002-wineditline-link.patch
- mingw-w64-sqlitestudio/003-win32-libs.patch
- mingw-w64-sqlitestudio/PKGBUILD
> [new package] sqlitestudio, sqlitestudio-plugins

- mingw-w64-turbo/PKGBUILD
- mingw-w64-turbo/rust-1.85.0-fixes.patch
patch is taken from https://github.com/vercel/turborepo/pull/10024. but this causes a regression (?) on Windows
> turbo: update to 2.4.4

- mingw-w64-sdl3-image/0001-sdl3-image-3.2.0-find-jxl-fix.patch
- mingw-w64-sdl3-image/0002-sdl3-image-3.2.0-find-tiff-fix.patch
- mingw-w64-sdl3-image/PKGBUILD
Upstream changes (https://github.com/libsdl-org/SDL_image/pull/528) was added.
> sdl3-image: fix find libjxl

- mingw-w64-oh-my-posh/PKGBUILD
there has been a while since latest release, so pushing it unscheduled. completions were removed in https://github.com/JanDeDobbeleer/oh-my-posh/commit/e5b95692df4a736db006348985dddd06387b362e
> oh-my-posh: update to 25.0.0

- mingw-w64-zed/.gitignore
- mingw-w64-zed/672a472a23ec260f2766b1e6f2075a9f94384935.patch
- mingw-w64-zed/PKGBUILD
- mingw-w64-zed/zed-CLANG64.install
- mingw-w64-zed/zed-MINGW64.install
- mingw-w64-zed/zed-UCRT64.install
- mingw-w64-zed/zed-cli-set-path.patch
backported patches for cli to make it work on Windows. I'll try to upstream my patch. added a post_upgrade warning to let users know
> zed: update to 0.175.5

- mingw-w64-libuv/.gitignore
- mingw-w64-libuv/PKGBUILD
> libuv: backport a fix for Windows 1607.

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/079e6092b...343bce7b0
> mingw-w64: Update to 343bce7b02

- mingw-w64-aegisub/0001-workaround-try-except.patch
- mingw-w64-aegisub/0002-meson-remove-msvc-option.patch
- mingw-w64-aegisub/0003-fix-macro-for-mingw.patch
- mingw-w64-aegisub/0004-workaround-wxGlobalSEInformation-not-found.patch
- mingw-w64-aegisub/PKGBUILD
* Fixes #23525 
I can not figure out the compiler errors in other msystems. Please feel free to add the patches fixing those errors.
> aegisub: add package

- mingw-w64-python-pglive/0001-update-numpy-dep.patch
- mingw-w64-python-pglive/PKGBUILD
Added `python-pglive` package.
```
$ python all_plot_types.py
```
> [new package] python-pglive 0.8.2

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/343bce7b0...b02533108
> mingw-w64: Update to b025331084

- mingw-w64-cargo-edit/PKGBUILD
- mingw-w64-cargo-generate/PKGBUILD
- mingw-w64-jj/PKGBUILD
this tool can help us in future libgit2 rebuilds for rust-based packages. rebuild some packages using this tool
> [new package] cargo-edit 0.13.1

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v878-we-are-with-ukraine/
> notepad++: Update to 8.7.8

- mingw-w64-uutils-coreutils/PKGBUILD
set PROG_PREFIX because this package shouldn't conflict with cygwin coreutils
fixes https://github.com/msys2/MINGW-packages/issues/18916
> uutils-coreutils: update to 0.0.30

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/b02533108...49111ba98
> mingw-w64: Update to 49111ba982

- mingw-w64-freecad/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/22600
> freecad: Disable Addon Manager

- mingw-w64-gst-plugins-rs/.gitignore
- mingw-w64-gst-plugins-rs/PKGBUILD
- mingw-w64-gst-plugins-rs/aws-lc-clang-build.patch
currently fails with absolutely strange cmake error (that wasn't a Zed case)
> gst-plugins-rs: update to 1.26.0

- mingw-w64-vk-bootstrap/PKGBUILD
> vk-bootstrap: update to 1.4.310

- mingw-w64-gdal/PKGBUILD
> gdal: Update to 3.10.2

- mingw-w64-cfitsio/001-fix-pkgconf.patch
- mingw-w64-cfitsio/PKGBUILD
The pkgconf file issue had already been reported upstream: https://github.com/HEASARC/cfitsio/issues/38
> cfitsio: update to 4.6.0

- mingw-w64-codeblocks/PKGBUILD
> codeblocks: Update to SVN revision 13634 and

- mingw-w64-konversation/PKGBUILD
> konversation: add package

- mingw-w64-python-hererocks/PKGBUILD
Based on: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hererocks and existing mingw python packages
> new package: python-hererocks

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/49111ba98...850703ae4
> mingw-w64: Update to 850703ae46

- mingw-w64-qemu/PKGBUILD
see https://wiki.qemu.org/ChangeLog/9.2 and https://gitlab.com/qemu-project/qemu/-/commits/stable-9.2
> qemu: Update to 9.2.3

- mingw-w64-blake3/PKGBUILD
for clang only: https://github.com/BLAKE3-team/BLAKE3/blob/83a60d9da6a44b719e258926e568c203d3b4dd36/c/dependencies/tbb/CMakeLists.txt#L2
> libblake3: enable tbb feature

- mingw-w64-aichat/PKGBUILD
AIChat is an all-in-one LLM CLI tool featuring Shell Assistant, Chat-REPL, RAG, AI Tools & Agents, with access to OpenAI, Claude, Gemini, Ollama, Groq, and more.
> aichat: new package

- mingw-w64-python-setuptools/0011-add-support-for-windmc.patch
- mingw-w64-python-setuptools/PKGBUILD
> python-setuptools: Update to 78.1.0

- mingw-w64-octave/PKGBUILD
> octave: update to 10.1.0

- mingw-w64-mold/PKGBUILD
> mold: stop using mimalloc

- mingw-w64-curl/0001-Make-cURL-relocatable.patch
- mingw-w64-curl/PKGBUILD
> curl: Update to 8.13.0

- mingw-w64-jj/PKGBUILD
> jj: update to 0.28.0

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v879-we-are-with-ukraine/
> notepad++: Update to 8.7.9

- mingw-w64-rust/PKGBUILD
> rust: add `wasm32v1-none` target back

- mingw-w64-python-jupyter_notebook/PKGBUILD
- mingw-w64-python-jupyterlab/PKGBUILD
~~Waiting for [notebook](https://packages.msys2.org/base/mingw-w64-python-jupyter_notebook) `v7.4.0`.~~
> python-jupyterlab/jupyter_notebook: update to 4.4.0/7.4.0

- mingw-w64-whisper.cpp/PKGBUILD
* the github repo moved
* the old tags are gone, but there are releases now
> whisper.cpp: Update to 1.7.5

- mingw-w64-ffts/0003-CMake-Install-pkgconfig-file.patch
- mingw-w64-ffts/0004-aarm64-valloc.patch
- mingw-w64-ffts/PKGBUILD
- mingw-w64-scopehal-apps/PKGBUILD
> ffts, scopehal-apps: Enable aarch64 builds

- mingw-w64-blake3/PKGBUILD
and try with tbb for all envs (previously it was restricted upstream)
> blake3: update to 1.8.2

- mingw-w64-gedit-plugins/PKGBUILD
- mingw-w64-gedit/PKGBUILD
- mingw-w64-libgedit-amtk/PKGBUILD
- mingw-w64-libgedit-gfls/PKGBUILD
- mingw-w64-libgedit-gtksourceview/PKGBUILD
- mingw-w64-libgedit-tepl/PKGBUILD
> gedit: update to 48.2

- mingw-w64-qemu/PKGBUILD
- mingw-w64-qemu/msys2.examples.tests.sh
see https://wiki.qemu.org/ChangeLog/10.0
> qemu: Update to 10.0.0

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/1e8b1ccdd...71699efcb
> mingw-w64: Update to 71699efcbf

- mingw-w64-python-fabric/PKGBUILD
> [new package] python-fabric 3.2.2

- mingw-w64-nerd-fonts/PKGBUILD
+2 new fonts, Ubuntu font license is now listed in spdx
> nerd-fonts: update to 3.4.0

- mingw-w64-svg2pdf/PKGBUILD
> [new package] svg2pdf 0.13.0

- mingw-w64-gojq/PKGBUILD
> [new package] gojq 0.12.17

- mingw-w64-python-pyodbc/0001-build-fix.patch
- mingw-w64-python-pyodbc/0002-missing-odbc3.8.patch
- mingw-w64-python-pyodbc/PKGBUILD
> new package: python-pyodbc

- mingw-w64-directxmesh/PKGBUILD
use new BUILD_SHARED_LIBS option
> directxmesh: Update to 1.6.8

- mingw-w64-testu01/0001-various-fixes.patch
- mingw-w64-testu01/PKGBUILD
TestU01 is a software library, implemented in the ANSI C language, and offering a collection of utilities for the empirical statistical testing of uniform random number generators.
* https://simul.iro.umontreal.ca/testu01/tu01.html
* https://en.wikipedia.org/wiki/TestU01
> TestU01: New package

- mingw-w64-sqlite3/0002-fix-building-sqldiff.patch
- mingw-w64-sqlite3/0004-dont-misuse-tcl-extern.patch
- mingw-w64-sqlite3/0005-fix-name-and-install-dir.patch
- mingw-w64-sqlite3/Makefile.ext.in
- mingw-w64-sqlite3/PKGBUILD
Port to new build system
vfstrace fails to build, so skip for now
> sqlite3: Update to 3.49.1

- mingw-w64-notepad++/PKGBUILD
see ReleaseNotes https://notepad-plus-plus.org/news/v881-we-are-with-ukraine/
> notepad++: Update to 8.8.1

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/71699efcb...6b2176247
> mingw-w64: Update to 6b2176247a

- mingw-w64-gcc/0021-PR14940-Allow-a-PCH-to-be-mapped-to-a-different-addr.patch
- mingw-w64-gcc/PKGBUILD
Reference: https://github.com/gcc-mirror/gcc/commit/16e301adf7b653c72d5c3cae1c7287877f3f20ff
> gcc: Backport PCH fix from master

- mingw-w64-genromfs/0001-build-mingw.patch
- mingw-w64-genromfs/PKGBUILD
The same as https://github.com/msys2/MSYS2-packages/tree/master/genromfs but pached to build and run on MINGW instead.
> Add mingw-w64-genromfs

- mingw-w64-python-pikepdf/PKGBUILD
* Read and write PDFs with Python, powered by qpdf
> python-pikepdf: new package

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/6b2176247...01c28cf2e
> mingw-w64: Update to 01c28cf2ef

- mingw-w64-python-pyproj/PKGBUILD
> new package: python-pyproj

- mingw-w64-binutils/4000-fix-DEBUG_S_INLINEELINES.patch
- mingw-w64-binutils/PKGBUILD
- mingw-w64-gcc/3001-fix-codeview-crashes.patch
- mingw-w64-gcc/PKGBUILD
> gcc: apply codeview fixes

- mingw-w64-ollama/0002-fix-dynamic-libraries-path.patch
- mingw-w64-ollama/PKGBUILD
* 0002-fix-dynamic-libraries-path.patch: refresh
> ollama: Update to 0.6.8

- mingw-w64-vk-bootstrap/PKGBUILD
Update to match the latest vulkan header version in MSYS2
> vk-bootstrap: update to 1.4.313

- mingw-w64-python-pyshp/PKGBUILD
Python read/write support for ESRI Shapefile format
> New Package: pyshp

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/ad150be87...7e3f2dd90
> mingw-w64: Update to 7e3f2dd90c

- mingw-w64-python-pysfcgal/PKGBUILD
- mingw-w64-sfcgal/PKGBUILD
Update SFCGAL and PySFCGAL
NEWS : https://gitlab.com/sfcgal/SFCGAL/-/releases/v2.1.0
As usual, tested on our CI for msys2: https://gitlab.com/sfcgal/SFCGAL/-/blob/master/.github/workflows/msys.yml?ref_type=heads
Thanks
> SFCGAL: Update to 2.1.0

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/7e3f2dd90...9c1dcbf0c
> mingw-w64: Update to 9c1dcbf0c6

- mingw-w64-64tass/PKGBUILD
A new version was released last week.
> 64tass: update to 1.60.3243

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/2ca6f1348...4a3edb6f8
> mingw-w64: Update to 4a3edb6f81

- mingw-w64-meson/0004-fix-gtk-doc.patch
- mingw-w64-meson/PKGBUILD
* 0004-fix-gtk-doc.patch: refresh
* the other PR is included in the new release
Fixes #24204
> meson: Update to 1.8.1

- mingw-w64-bullet/PKGBUILD
> bullet: Replace python3 with python in dependencies

- mingw-w64-edit/PKGBUILD
do it in prepare with std's manifest file
> edit: don't fetch deps at build step

- mingw-w64-ollama/0001-no-static-linking.patch
- mingw-w64-ollama/PKGBUILD
* 0001-no-static-linking.patch: refresh
* add missing openblas runtime dep
> ollama: Update to 0.7.1

- mingw-w64-sip/003-template-error.patch
- mingw-w64-sip/PKGBUILD
- mingw-w64-wxPython/PKGBUILD
> wxPython: Update to 4.2.3

- mingw-w64-grpc/PKGBUILD
> grpc: Rebuild for protobuf 31.0

- mingw-w64-premake/PKGBUILD
> premake: update to 5.0beta6

- mingw-w64-qemu/PKGBUILD
see https://gitlab.com/qemu-project/qemu/-/commits/stable-10.0 for updates
> qemu: Update to 10.0.2

- mingw-w64-ruff/PKGBUILD
and try to remove fetching workaround
> ruff: update to 0.11.12

- mingw-w64-verilator/PKGBUILD
> [verilator]: Update to newest version

- mingw-w64-curl/PKGBUILD
* remove patches include in the release
* some cleanups
> curl: Update to 8.14.1

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/1a99f8514...b45abfec4
> mingw-w64: Update to b45abfec4e

- mingw-w64-python-numba/0001-adjust-numpy-req.patch
- mingw-w64-python-numba/PKGBUILD
- mingw-w64-python-numpy/PKGBUILD
> python-numpy: Update to 2.3.0

- mingw-w64-include-what-you-use/PKGBUILD
remove backport included in a new release
> include-what-you-use: update to 0.24

- mingw-w64-double-conversion/PKGBUILD
- mingw-w64-double-conversion/cmake-dual-lib.patch
- mingw-w64-double-conversion/cmake-version.patch
> double-conversion: Implement cmake config to switch between shared/static link

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/b45abfec4...f5469ff36
> mingw-w64: Update to f5469ff365

- mingw-w64-openblas/006-find-openmp-before-usage.patch
- mingw-w64-openblas/PKGBUILD
> openblas: Fix CMake config file.

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/f5469ff36...b351226e3
> mingw-w64: Update to b351226e32

- mingw-w64-python-docopt/PKGBUILD
- mingw-w64-python-pykwalify/PKGBUILD
pyKwalify is a library for YAML/JSON validation.
> Add mingw-w64-python-pykwalify

- mingw-w64-fluidsynth/PKGBUILD
the importlib name was changed in
https://github.com/FluidSynth/fluidsynth/issues/1543
> fluidsynth: Update to 2.4.6

- mingw-w64-gw/PKGBUILD
Added angleproject to dependencies
> Update GW to v1.2.4

- mingw-w64-python-rtree/0001-fix-mingw-finder.patch
- mingw-w64-python-rtree/PKGBUILD
> python-rtree: update libspatialindex_c DLL name

- mingw-w64-podman/PKGBUILD
Update podman to version 5.5.2.
> podman: update to 5.5.2

- mingw-w64-git-lfs/PKGBUILD
Update git-lfs to version 3.7.0.
> git-lfs: update to 3.7.0

- mingw-w64-python-fonttools/PKGBUILD
Update python-fonttools to 4.58.5.
> python-fonttools: update to 4.58.5

- mingw-w64-notepad++/PKGBUILD
see ReleaseNotes https://notepad-plus-plus.org/news/v883-self-signed-certificate/
> notepad++: Update to 8.8.3

- mingw-w64-gexiv2/PKGBUILD
This fixes a bug in gimp: https://gitlab.gnome.org/GNOME/gimp/-/issues/14384 which we plan to release a revision
> gexiv2: update to 0.14.6

- mingw-w64-fastgltf/PKGBUILD
> fastgltf: update to 0.9.0

- mingw-w64-python-aiohttp/PKGBUILD
Update python-aiohttp to 3.12.14.
>  python-aiohttp: update to 3.12.14

- mingw-w64-python-setuptools/PKGBUILD
See https://github.com/pypa/setuptools/pull/5047
> setuptools: fix launcher manifest path

- mingw-w64-libgphoto2/0003-missing-min-max.patch
- mingw-w64-libgphoto2/PKGBUILD
- mingw-w64-libgphoto2/libgphoto2-gp_system_filename-fix.patch
Unfortunately will not be able to deal w/ the failure for a while, so feel free to take over, thanks.
> libghpoto2: update to 2.5.32

- mingw-w64-samply/PKGBUILD
Command-line sampling profiler for macOS, Linux, and Windows.
> samply: Add 0.13.1

- mingw-w64-python-astroid/PKGBUILD
> python-astroid: update to 3.3.11

- mingw-w64-ossia-score/001-aarch64.patch
- mingw-w64-ossia-score/PKGBUILD
> ossia-score: Enable aarch64 builds

- mingw-w64-sleef/PKGBUILD
suggested in https://github.com/msys2/MSYS2-packages/issues/2250#issuecomment-753526550
> sleef: Add 3.9.0

- mingw-w64-uasm/PKGBUILD
upstream removed the makefile, so use this one.. close enough
Fixes #24402
> uasm: Update to 2.57

- mingw-w64-curl/0001-Make-cURL-relocatable.patch
- mingw-w64-curl/PKGBUILD
> curl: Update to 8.15.0

- mingw-w64-python-immutabledict/PKGBUILD
Add the python `immutabledict` package.
> [new package] python-immutabledict 4.2.1

- mingw-w64-fltk/PKGBUILD
Update to 1.4.4
Cairo support is also confirmed working.
> fltk: update to 1.4.4 and enable cairo support

- mingw-w64-unbound/PKGBUILD
Also needs bison and flex to build.
> unbound: update to 1.23.1

- mingw-w64-qemu/PKGBUILD
see https://gitlab.com/qemu-project/qemu/-/commits/stable-10.0 for changes
> qemu: Update to 10.0.3

- mingw-w64-crt-git/0001-crt-mingw_pformat-Initialize-mbstate_t-structure-pro.patch
- mingw-w64-crt-git/PKGBUILD
> crt: backport mingw_pformat fix for recent regression

- mingw-w64-uv/PKGBUILD
> uv: update to 0.8.3

- mingw-w64-sqlite3/0005-remove-dl-flags.patch
- mingw-w64-sqlite3/PKGBUILD
> sqlite3: remove -ldl flags from pkg-config output

- mingw-w64-python-path/PKGBUILD
Checks also use more-itertools, so add it as check dependency.
> python-path: update to 17.1.1

- mingw-w64-python-faker/PKGBUILD
Checks also use python-freezegun.
> python-faker: update to 37.5.3

- mingw-w64-kdoctools/PKGBUILD
This reverts commit 0726f2930da890d8394d5531049618a396613e01.
> Revert "revert kdoctools update"

- mingw-w64-mesa/PKGBUILD
> mesa: update 25.1.7

- mingw-w64-binutils/PKGBUILD
> binutils: backport windres crash fix

- mingw-w64-python-databases/PKGBUILD
Based on https://github.com/encode/databases/pull/540
Optional depends:
> [new package] python-databases 0.9.0

- mingw-w64-gcc/PKGBUILD
cf588f1a8e7406ced5b08f32f9d23f015a240a31.patch: included in this release
> gcc: Update to 15.2.0

- mingw-w64-ggml/PKGBUILD
- mingw-w64-llama.cpp/PKGBUILD
- mingw-w64-whisper.cpp/PKGBUILD
* Update ggml/llama.cpp/whisper.cpp to latest possible based on last ggml sync in upstream
* Fix check() execution in ggml PKGBUILD
> Update ggml/llama.cpp/whisper.cpp to latest possible based on ggml 0.0.2404

- mingw-w64-nicotine+/PKGBUILD
- mingw-w64-nicotine+/pyscript2exe.py
forgot that we have such handy script...
> nicotine+: use pyscript2exe

- mingw-w64-notepad++/PKGBUILD
see https://notepad-plus-plus.org/news/v884-released/
> notepad++: Update to 8.8.4

- mingw-w64-bzip3/PKGBUILD
GitHub repository moved to new URL.
> bzip3: update to 1.5.3 + add msys2_references

- mingw-w64-zycore-c/PKGBUILD
> zycore-c: update to 1.5.2

- mingw-w64-python-pyft232/PKGBUILD
- mingw-w64-python-pylablib/PKGBUILD
Add `python-pylablib` package.
> [new package] python-pylablib 1.4.3

- mingw-w64-clipper2/PKGBUILD
- mingw-w64-manifold/0001-build-mingw.patch
- mingw-w64-manifold/PKGBUILD
Add new dependencies for blender build
> Blender deps

- mingw-w64-sequoia-sq/PKGBUILD
* Fix the build issue as mentioned in #25254
> sequoia-sq: enable building for ucrt64

- mingw-w64-fq/PKGBUILD
> fq: init at 0.12.0

- mingw-w64-mypaint-brushes2/0001-change-surfacemap-inputs.patch
- mingw-w64-mypaint-brushes2/PKGBUILD
See: https://gitlab.gnome.org/GNOME/gimp/-/issues/14461
> mypaint-brushes2: Change old surfacemap inputs to gridmap

- mingw-w64-gr/0001-ffmpg8-fix.patch
- mingw-w64-gr/0002-missing-cmake-dep.patch
- mingw-w64-gr/PKGBUILD
> gr: Update to 0.73.17

- mingw-w64-exiv2/PKGBUILD
> exiv2: backport ABI break fix

- mingw-w64-unpaper/PKGBUILD
* A post-processing tool for scanned sheets of paper
> unpaper: new package

- mingw-w64-aubio/PKGBUILD
- mingw-w64-ffmpeg7.1/PKGBUILD
- mingw-w64-ffmpeg7.1/d1ed5c06e3edc5f2b5f3664c80121fa55b0baa95.patch
- mingw-w64-handbrake/PKGBUILD
- mingw-w64-vlc/PKGBUILD
Same as 81e68e2b427605c7d404d12 but this time for 7.1
> Add ffmpeg7.1

- mingw-w64-ffmpeg/PKGBUILD
enables various vulkan related things (ffv1_vulkan encoder + various filters)
> ffmpeg: build with shaderc

- mingw-w64-zed/PKGBUILD
- mingw-w64-zed/zed-bump-cargo-about.patch
> zed: update to 0.202.7

- mingw-w64-cava/PKGBUILD
Try to guess the song I am listening 🙂
> cava: add package

- mingw-w64-cmake/PKGBUILD
Reference: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/11134
Reference: https://github.com/curl/curl/commit/1a12663d06d9c42fd40a8655d5247f7afeeb8e1e
> cmake: Fix build issue when using system curl

- mingw-w64-directxmath/001-path-adjustment.patch
- mingw-w64-directxmath/PKGBUILD
- mingw-w64-directxmesh/PKGBUILD
That's the working part of https://github.com/msys2/MINGW-packages/pull/25700.
> Update directxmath and directxmesh

- mingw-w64-libxml2/PKGBUILD
This reverts commit a25ad279901d5ba85d4e8a0a710eb24720d2bc4d.
> Reapply "libxml2: Don't export DllMain."

- mingw-w64-sundials/PKGBUILD
> sundials: update to 7.5.0

- mingw-w64-notepad++/PKGBUILD
see ReleaseNotes https://notepad-plus-plus.org/news/v886-released/
> notepad++: Update to 8.8.6

- mingw-w64-wasmer/PKGBUILD
- mingw-w64-wasmer/reproducible-builds.patch
> wasmer: update to 6.1.0
