msys2/MINGW-packages

- mingw-w64-gcc/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17599
> gcc: backport codeview support

- mingw-w64-lua/0001-When-running-lua-on-mintty-or-other.patch
- mingw-w64-lua/PKGBUILD
- mingw-w64-lua/link-implib.patch
- mingw-w64-lua51/0001-When-running-lua-on-mintty-or-other.patch
- mingw-w64-lua51/PKGBUILD
- mingw-w64-lua51/link-implib.patch
- mingw-w64-lua53/PKGBUILD
- mingw-w64-lua53/cygpty.patch
- mingw-w64-lua53/implib.patch
- mingw-w64-luajit/001-mintty-cygpty-isatty.patch
- mingw-w64-luajit/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17472
All the changed patch files have been recreated with `git diff`. None of them are handwritten anymore. This ensures that `patch` and `git apply` always properly works.
> lua lua51 lua53 luajit: fix broken mintty patch and remove winpty wrappers and dependencies

- mingw-w64-python-jellyfish/PKGBUILD
Successful ARM64 CI run: https://github.com/msys2-arm/MINGW-packages/actions/runs/5394138325/jobs/9794885039
> python-jellyfish: add aarch64 workaround for windows-targets 0.48.0

- mingw-w64-lcms2/PKGBUILD
There was a request for GIMP to add an option for LittleCMS optimization (https://gitlab.gnome.org/GNOME/gimp/-/issues/9536). This requires the lcms2 Fast Float plug-in to be built with lcms2. [A comment by lillolollo](https://gitlab.gnome.org/GNOME/gimp/-/issues/9536#note_1760997) indicated this can be done by adding the -Dfastfloat=true flag to PKGBUILD.
I have tested this locally and confirmed it still builds lcms2, now with the Fast Float plug-in as well. If anything else is needed, please let me know!
> lcms2: Enable Fast Float plugin to be built

- mingw-w64-lcms2/PKGBUILD
Following up from https://github.com/msys2/MINGW-packages/pull/17655 @Biswa96 @cmyk-student 
Let's provide all the licensing information at the very least.
I can't verify/confirm if linking w/ `lcms2_fast_float` but not using any of its symbols is sufficient to avoid actual linkage. Perhaps it relies on `strip` being run on the object, don't know if that would always be the case...
> lcms2: update licensing info

- mingw-w64-openal/0004-pkgconfig-add-Cflags-private.patch
- mingw-w64-openal/PKGBUILD
This defines AL_LIBTYPE_STATIC macro while static linking. Previously, that macro was only defined in pkgconfig file of static openal build.
> openal: Add Cflags.private in pkgconfig file

- mingw-w64-librsvg/PKGBUILD
No longer needed with windows-targets 0.48.1
see https://github.com/msys2/MINGW-packages/pull/17671#discussion_r1248543246
> librsvg: remove clangarm64 workaround

- mingw-w64-guile1.8/0003-Fix-the-SRFI-60-copy-bit-documentation.patch
- mingw-w64-guile1.8/0004-Define-_GNU_SOURCE-to-fix-the-GNU-kFreeBSD-build.patch
- mingw-w64-guile1.8/0005-Don-t-access-uninitialised-memory-in-scm_to_sockaddr.patch
- mingw-w64-guile1.8/0006-Make-sockets.test-more-robust.patch
- mingw-w64-guile1.8/0007-Mark-Unused-modules-are-removed-gc-test-as-unresolve.patch
- mingw-w64-guile1.8/0008-Fix-problems-in-guile-tut.texi-that-cause-makeinfo-t.patch
- mingw-w64-guile1.8/0009-Fix-r5rs.texi-makeinfo-failure-by-applying-changes-f.patch
- mingw-w64-guile1.8/0010-Fix-test-suite-failure-caused-by-formfeed-difference.patch
- mingw-w64-guile1.8/0011-Fix-incompatibility-with-automake-1.13-specify-seria.patch
- mingw-w64-guile1.8/0012-remove-spurious-declarations-in-c-tokenize.lex.patch
- mingw-w64-guile1.8/0013-Fix-configure-stack-grow-direction-code.patch
- mingw-w64-guile1.8/0014-Fix-failed-overflow-detection-with-optimization.patch
- mingw-w64-guile1.8/0015-Fix-failed-test-num2integral-and-test-conversion-on-i386.patch
- mingw-w64-guile1.8/0016-Avoid-dll-versions.patch
- mingw-w64-guile1.8/0017-Try-windows-conversion-of-%load-path-on-MinGW.patch
- mingw-w64-guile1.8/0018-Fix-environ-manipulation-for-ucrt-on-MinGW.patch
- mingw-w64-guile1.8/0100-Disable-all-failed-tests-for-mingw-w64.patch
- mingw-w64-guile1.8/PKGBUILD
A lightweight guile version for MINGW32 and CLANG32. Currently even the only version available for MINGW. Especially useful for linking against libguile. If MSYS2 is also installed, no need to set GUILE_LOAD_PATH, ref. patch 0017. Fixes for localtime() on CLANG32, ref. patch 0018.
> guile1.8: new package (lightweight guile version, 32 bit only)

- mingw-w64-python2/0100-MINGW-BASE-use-NT-thread-model.patch
- mingw-w64-python2/1030-use-gnu_printf-in-format.patch
- mingw-w64-python2/PKGBUILD
this backports https://github.com/msys2/MINGW-packages/blob/d8414ad1842901eacfdb580acc3c25c118ca82f9/mingw-w64-python/0050-use-gnu_printf-in-format.patch from our Python 3 package, to use printf instead of gnu_printf which clang doesn't support.
as pointed out here: https://github.com/mesonbuild/meson/pull/11530#issuecomment-1532351609
> python2: fix unknown gnu_printf format attribute for clang

- mingw-w64-pango/PKGBUILD
This defines some glib2 macro to remove dllimport attribute in static library.
Fixes https://github.com/msys2/MINGW-packages/issues/17651
> pango: Fix glib2 linking in static library

- mingw-w64-cjson/PKGBUILD
From the release notes:
* Add an option for ENABLE_CJSON_VERSION_SO in CMakeLists.txt, see https://github.com/DaveGamble/cJSON/pull/534
* Add cmake_policy to CMakeLists.txt, see https://github.com/DaveGamble/cJSON/pull/613
* Add cJSON_SetBoolValue, see https://github.com/DaveGamble/cJSON/pull/639
* Add meson documentation, see https://github.com/DaveGamble/cJSON/pull/761
* Fix memory leak in merge_patch, see https://github.com/DaveGamble/cJSON/pull/611
* Fix conflicting target names 'uninstall', see https://github.com/DaveGamble/cJSON/pull/617
* Bump cmake version to 3.0 and use new version syntax, see https://github.com/DaveGamble/cJSON/pull/587
* Print int without decimal places, see https://github.com/DaveGamble/cJSON/pull/630
* Fix 'cjson_utils-static' target not exist, see …
> update cJSON to 1.7.16

- mingw-w64-fluidsynth/PKGBUILD
* Static library was disabled in be39dbce28188b59fb8aef2ae95d1449a2ee947b commit.
* This defines some glib2 macro to remove dllimport attribute in static library.
* Also use prefix in pkgconfig file for Libs.private field.
Fixes https://github.com/msys2/MINGW-packages/issues/17664
> fluidsynth: Add static library

- mingw-w64-mkvtoolnix/PKGBUILD
`boost` is now required as of 74.0.0: https://www.bunkus.org/blog/2023/02/mkvtoolnix-v74-released/
> mkvtoolnix: update to 78.0

- mingw-w64-gimp3/0004-clang-windres.patch
- mingw-w64-gimp3/PKGBUILD
fixes #17727
* refresh patch
* lua is available for arm64 now
* remove default options
* remove patch included in the release
> gimp3: Update to 2.99.16

- mingw-w64-gdk-pixbuf2/PKGBUILD
* Removes DllMain symbol in static library.
* Remove glib2 symbols with __imp decoration i.e. without dllimport attribute.
Fixes https://github.com/msys2/MINGW-packages/issues/17643
> gdk-pixbuf2: Build static library separately

- mingw-w64-cairo/PKGBUILD
This defines some glib2 macro to remove dllimport attribute in libcairo-gobject.a static library. This removes the following symbols from libcairo-gobject.a:
```
__imp_g_boxed_type_register_static
__imp_g_enum_register_static
__imp_g_free
__imp_g_intern_static_string
__imp_g_memdup2
__imp_g_once_init_enter
__imp_g_once_init_leave
```
Fixes https://github.com/msys2/MINGW-packages/issues/17651
> cairo: Fix glib2 linking in static library

- mingw-w64-harfbuzz/PKGBUILD
This defines some glib2 macro to remove dllimport attribute in libharfbuzz.a and libharfbuzz-gobject.a files. This removes the following symbols from libharfbuzz-gobject.a:
```
__imp_g_boxed_type_register_static
__imp_g_enum_register_static
__imp_g_flags_register_static
__imp_g_intern_static_string
__imp_g_once_init_enter
__imp_g_once_init_leave
```
> harfbuzz: Fix glib2 linking in static library

- mingw-w64-gitg/PKGBUILD
it no longer depends on it since v41
> gitg: remove dependency on libsoup

- mingw-w64-ncurses/PKGBUILD
That should be including a fix for the issue also addressed in #17494.
> ncurses: update to 6.4.20230708

- mingw-w64-libpaper/0001-fix-relocation.patch
- mingw-w64-libpaper/PKGBUILD
gnulib assumes the path format matches what we pass to configure, so make sure we only pass unix paths to the gnulib relocation functions.
> libpaper: fix relocation

- mingw-w64-cargo-local-registry/PKGBUILD
for windows-gnullvm fix.  Less hacky than the previous sed approach used
in other packages before 0.48.1 was published.
> cargo-local-registry: update windows-targets crate

- mingw-w64-cargo-c/PKGBUILD
windows-targets has been updated to 0.48.1, so remove the workaround for arm64
> cargo-c: Update to 0.9.21

- mingw-w64-hunspell/01-relocate.patch
- mingw-w64-hunspell/PKGBUILD
properly free the result of single_path_relocation() and replace pathlist_relocation() with get_relocated_path_list() which returns a heap allocated string instead.
> hunspell: some relocation cleanups

- mingw-w64-gst-plugins-good/PKGBUILD
the soup element dlopens one of libsoup2 or 3 depending on what is already loaded, so this shouldn't make a difference for the build. But default to libsoup3 so the newer lib gets loaded if possible.
> gst-plugins-good: depend on libsoup3

- mingw-w64-gdk-pixbuf2/PKGBUILD
- mingw-w64-gdk-pixbuf2/fix-missing-meson-dep.patch
Fixes https://github.com/msys2/MINGW-packages/pull/17829
> gdk-pixbuf2: Add missing gdiplus dependency for static library

- mingw-w64-alacritty/PKGBUILD
Alacritty - a cross-platform, OpenGL terminal emulator.
Successfully builds, but I can't test it now.
@jeremyd2019 any thoughts on CLANGARM64 compatibility?
> alacritty: new package

- mingw-w64-openexr/0007-export-TypedAttribute-value.patch
- mingw-w64-openexr/PKGBUILD
This removes inline specifier to export TypedAttribute::value which was already declared with dllexport attribute.
Fixes https://github.com/msys2/MINGW-packages/issues/17757
>  openexr: Fix exporting TypedAttribute::value for GIMP

- mingw-w64-python-pygments/PKGBUILD
This should be reverted once jinja is built
> pygments: disable docs temporarily during rebuilds

- mingw-w64-mypaint/PKGBUILD
"U" as the mode for universal line endings has been deprecated for a while and has been removed in Python 3.11. Universal line endings are the default now.
The CLANG* environments are failing currently (because numpy hasn't been rebuilt yet).
But this should fix the build error at least with GCC.
> mypaint: fix compatibility with Python 3.11

- mingw-w64-vapoursynth/PKGBUILD
Changes:
* Add python-setuptools in makedepends for setup.py.
* Move cython to makedepends.
* Use LDFLAGS for linker option.
> vapoursynth: update to 62

- mingw-w64-gdal/PKGBUILD
`xsimd` is a transient dependency of `arrow`. Without it installed, including `arrow`'s CMake module fails to import the target and leaves some variables in a bad state (e.g., `CMAKE_MODULE_PATH`).
> gdal: Add `xsimd` to makedepends.

- mingw-w64-python-greenlet/PKGBUILD
This fixes the following error with clang32
src/greenlet/platform/switch_x86_unix.h:54:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
> python-greenlet: Remove deprecated register keyword for clang32

- mingw-w64-ogre3d/PKGBUILD
`cc1plus` OOMs when trying to compile the Python bindings on MINGW32.
I also tried to switch to `-DCMAKE_BUILD_TYPE=None` and adding `-Os` and/or `-flarge-source-files`. But that doesn't make any difference.
Without the Python bindings, the rest still builds without issues for me on MINGW32. (I don't know if they are needed by any reverse dependencies though.)
> ogre3d: De-activate Python bindings for MINGW32

- mingw-w64-python-jinja-docs/PKGBUILD
- mingw-w64-python-jinja/PKGBUILD
due to jinja having many reverse dependencies and the dep cycle with sphinx we need some way to break the cycle. Split out the docs build into a separate PKGBUILD.
> Add separate python-jinja-docs

- mingw-w64-blender/0040-missing-header.patch
- mingw-w64-blender/PKGBUILD
Trying to build blender in MINGW64 fails with errors like the following:
```
FAILED: extern/glog/CMakeFiles/extern_glog.dir/src/signalhandler.cc.obj
C:\msys64\mingw64\bin\g++.exe -DFREE_WINDOWS -DGFLAGS_DLL_DECL="" -DGFLAGS_DLL_DECLARE_FLAG="" -DGFLAGS_DLL_DEFINE_FLAG="" -DGOOGLE_GLOG_DLL_DECL="" -DNDEBUG -DWIN32 -DWITH_ASSERT_ABORT -DWITH_OPENGL -D_WIN32_WINNT=0x603 -D__LITTLE_ENDIAN__ -D__MMX__ -D__SSE2__ -D__SSE__ -ID:/repo/MSYS2/MINGW-packages/mingw-w64-blender/src/blender-3.5.0/extern/glog/src -ID:/repo/MSYS2/MINGW-packages/mingw-w64-blender/src/blender-3.5.0/extern/gflags/src -ID:/repo/MSYS2/MINGW-packages/mingw-w64-blender/src/blender-3.5.0/extern/glog/src/windows -march=nocona -msahf -mtune=generic -O2 -pipe -w -fopenmp -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing …
```
> blender: add missing header

- mingw-w64-python-pycryptodome/PKGBUILD
See also Legrandin/pycryptodome#757.  This may also be due to a bug in mingw-w64, that `__cpuid` prototype is present on ARM.
> pycryptodome: fix arm64 build

- mingw-w64-gi-docgen/PKGBUILD
- mingw-w64-meson-python/PKGBUILD
- mingw-w64-mypy/PKGBUILD
- mingw-w64-python-autopep8/PKGBUILD
- mingw-w64-python-black/PKGBUILD
- mingw-w64-python-build/PKGBUILD
- mingw-w64-python-flit-scm/PKGBUILD
- mingw-w64-python-flit/PKGBUILD
- mingw-w64-python-hatch-fancy-pypi-readme/PKGBUILD
- mingw-w64-python-hatchling/PKGBUILD
- mingw-w64-python-jupyter_notebook_shim/PKGBUILD
- mingw-w64-python-lsp-black/PKGBUILD
- mingw-w64-python-maturin/PKGBUILD
- mingw-w64-python-nvchecker/PKGBUILD
- mingw-w64-python-pdm-backend/PKGBUILD
- mingw-w64-python-pip-tools/PKGBUILD
- mingw-w64-python-poetry/PKGBUILD
- mingw-w64-python-pydocstyle/PKGBUILD
- mingw-w64-python-pylint/PKGBUILD
- mingw-w64-python-pyproject-api/PKGBUILD
- mingw-w64-python-pyproject-hooks/PKGBUILD
- mingw-w64-python-pytest/PKGBUILD
- mingw-w64-python-pytoolconfig/PKGBUILD
- mingw-w64-python-scikit-build/PKGBUILD
- mingw-w64-python-setuptools-scm/PKGBUILD
- mingw-w64-python-tox/PKGBUILD
- mingw-w64-python-versioningit/PKGBUILD
- mingw-w64-sip/PKGBUILD
In Python 3.11 tomli is also available in the stdlib and various packages use it if available instead of the tomli package.
Remove the tomli dependency for packages which don't require it with Python 3.11 anymore.
> python-tomli cleanup

- mingw-w64-starship/PKGBUILD
don't know why, but it fails on i686. should we disable it?
upd.: i686 is disabled, but it will be fixed soon. see further conversation for details
> starship: update to 1.16.0

- mingw-w64-libiff/0001-libiff-fix-shared-library.patch
- mingw-w64-libiff/PKGBUILD
- mingw-w64-libilbm/0001-libilbm-fix-shared-library.patch
- mingw-w64-libilbm/PKGBUILD
* Add -no-undefined option to build shared library.
* Add -export-symbols options with libiff.def file to export proper APIs.
* Remove LIBRARY name in libiff.def to use proper name in import library.
> libiff: Fix building shared library

- mingw-w64-openssl/PKGBUILD
also fix the build in case mingw perl is installed by forcing the msys one
> openssl: Update to 3.1.2

- mingw-w64-python/PKGBUILD
due to some PATHSEP fixes the original shebang now uses forward slashes and the sed no longer had any effect.
Instead of fixing the cygpath call just replace the shebang without matching, so this doesn't happen again.
Fixes #17929
> python: fix shebang of scripts like idle3

- mingw-w64-mesa/0003-addrlib-workaround-old-cpu-target.patch
- mingw-w64-mesa/0004-radv-add-stdcall-attribute.patch
- mingw-w64-mesa/PKGBUILD
```
_tzcnt_u32 requires Skylake or newer CPU[1]. So, it fails to build in
msys2/mingw environment because the default target is older nocona.
The attached patch allows to check __builtin_ctz first. This reverts
the logic from 5bb1fc80fa2c91a6204d89c59b7288e941f94481 commit.
This fixes the following compiler error
bmiintrin.h: In function 'unsigned int Addr::BitScanForward(unsigned int)':
bmiintrin.h:116:1: error: inlining failed in call to 'always_inline' 'unsigned int _tzcnt_u32(unsigned int)':
target specific option mismatch
116 | _tzcnt_u32 (unsigned int __X)
| ^~~~~~~~~~
../../src/amd/addrlib/src/core/addrcommon.h:360:23: note: called from here
360 |     out = ::_tzcnt_u32(mask);
|           ~~~~~~~~~~~~^~~~~~
[1]: https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.htm …
```
> mesa: Fix building AMD vulkan driver

- mingw-w64-python-lief/0001-fix-exported-API-pymodule.patch
- mingw-w64-python-lief/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17942
> python-lief: Fix exported API from python module

- mingw-w64-arpack/PKGBUILD
The last time ARPACK was built for CLANG64, Flang was still broken for complex values on Windows.
Rebuild now that lowering of complex values with Flang is fixed.
See also here for a downstream issue:
https://octave.discourse.group/t/compilation-with-flang-on-windows/4734/6
> arpack: Rebuild with updated Flang for issue with complex numbers

- mingw-w64-ffmpeg/PKGBUILD
> ffmpeg: backport patch to fix the build with binutils 2.41

- mingw-w64-ffmpeg4.4/PKGBUILD
> ffmpeg4.4: backport patch to fix the build with binutils 2.41

- mingw-w64-embree/002-arm64-no-mm-malloc.patch
- mingw-w64-embree/PKGBUILD
It was removed in https://github.com/mingw-w64/mingw-w64/commit/6affcc5d15b9caabb5891a Let's just used the default Windows API for this in all cases.
> embree: fix build error with clangarm64 due to missing _mm_malloc

- mingw-w64-embree3/002-arm64-no-mm-malloc.patch
- mingw-w64-embree3/PKGBUILD
It was removed in mingw-w64/mingw-w64@6affcc5d15b9caabb5891a Let's just used the default Windows API for this in all cases.
> embree3: fix build error with clangarm64 due to missing _mm_malloc

- mingw-w64-highway/PKGBUILD
The [releases are now signed](https://github.com/google/highway/releases/tag/1.0.5).
> highway: update to 1.0.5

- mingw-w64-emacs/PKGBUILD
`001-ucrt.patch` and `002-clang-fixes.patch` still work even though the line numbers don't match anymore. But I guess it's better to leave them as is to avoid introducing gratuitous changes?
As for the modification to the `build()` function, the emacs-29.1 update has added a `make sanity-check` target that invokes `emacs --batch --eval '(progn (defun f (n) (if (= 0 n) 1 (* n (f (- n 1))))) (princ (f 10)))'` after compilation. In the MinGW builds this returns `3628800`, but on the UCRT builds (including Clang) it returns nothing, which is why the check fails. 
I've modified the recipe so that it skips the sanity check for these versions: I believe the `001-ucrt.patch` is what causes this behaviour change (that or writing to `stdout` is fundamentally broken in the UCRT emacs build). …
> emacs: Update to 29.1

- mingw-w64-hyperfine/PKGBUILD
- mingw-w64-watchexec/PKGBUILD
Successful CLANGARM64 CI run: https://github.com/msys2-arm/MINGW-packages/actions/runs/5843684183/job/15846050647
> hyperfine, watchexec: update windows-targets for gnullvm support

- mingw-w64-python-pip/PKGBUILD
This fixes the following error with pip install command.
//python.exe: can't open file '\\\\pip-script.py': [Errno 2] No such file or directory
> python-pip: Use python-build to build

- mingw-w64-onefetch/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/pull/18083#issuecomment-1676330759
See https://github.com/o2sh/onefetch/issues/1143
Successful CLANGARM64 CI run: https://github.com/msys2-arm/MINGW-packages/actions/runs/5858975316/job/15884039932
> onefetch: update windows-targets for gnullvm support

- mingw-w64-graphicsmagick/002-tiff-transparency.patch
- mingw-w64-graphicsmagick/PKGBUILD
The latest version of GraphicsMagick is stricter when it comes to reading TIFF images with transparency. It is now a requirement that `TIFFTAG_EXTRASAMPLES` is defined in the image file for the alpha channel:
http://hg.code.sf.net/p/graphicsmagick/code/rev/5c6fd2a5e177
Afaict, that is conform to the standard:
https://www.awaresystems.be/imaging/tiff/tifftags/extrasamples.html
However, the TIFF files with transparency that are created by GraphicsMagick itself don't write that tag (with default parameters).
Add a patch that writes the necessary tag for TIFF images with transparency with default parameters.
With this patch, Octave's test for `imwrite` passes again.
It is still a pity that GraphicsMagick now refuses to read files completely that it wrote itself in previous versions. As it …
> graphicsmagick: Fix writing TIFF images with transparency

- mingw-w64-go/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/18166
> go: Include temporary fix for default environment variables

- mingw-w64-python-bsddb3/PKGBUILD
- mingw-w64-python-bsddb3/db-6.0-support.patch
- mingw-w64-python-bsddb3/unsupported-runtime-dirs.patch
Restore bsddb3 6.2.29 which was recently removed with #17874 due to build failures with clang, and also work around the clang build error.
Clang generates a compiler error against code which gcc treats as a warning. This change disables that error (only for clang) so the build can succeed. The code in question needs to be fixed (has been raised with the project), but this fix allows the build to succeed so downstream consumers (e.g. Gramps) can use the package.
Bumped up the package release. Built mingw64 gcc, clang and ucrt builds locally with success.
FYI @mmuetzel @Biswa96
> Restore bsddb3, fix clang build and bump package release

- mingw-w64-emacs/PKGBUILD
I don't know what this is, but someone requested it. Arch also enabled it:
https://gitlab.archlinux.org/archlinux/packaging/packages/emacs/-/commit/3c17a6ba310d252f15eabd
> emacs: enable tree-sitter

- mingw-w64-libtiff/0002-libtiff-install-headers.patch
- mingw-w64-libtiff/PKGBUILD
Also move the extra headers install logic to separate patch file
Fixes https://github.com/msys2/MINGW-packages/issues/18226
> libtiff: Add missing tif_hash_set.h

- mingw-w64-python-setuptools/0010-support-py_limited_api.patch
- mingw-w64-python-setuptools/PKGBUILD
This makes distutils link against python3 instead of python3.x when py_limited_api is set on the extension. With MSVC this is solved via pragma, which doesn't have an alternative with our toolchains.
This depends on libpython3.dll being installed, so https://github.com/msys2-contrib/cpython-mingw/pull/148
> python-setuptools: add support for py_limited_api

- mingw-w64-python-maturin/PKGBUILD
Remove clangarm64 workaround, should no longer be needed since windows-targets is new enough now.
Also enables the default feature set, so commands like "new" and "init" are now available, as if built with cargo.
> python-maturin: Update to 1.2.3

- mingw-w64-gpgme/PKGBUILD
- mingw-w64-gpgme/relocatable-cmake.patch
Changes:
* Remove hunks in relocatable-cmake.patch file which were fixed in upstream.
DLL name and path was fixed in this (libqgpgme-7.dll to libqgpgme-15.dll)
https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=commit;h=be0e653ce3039b1a81d23bed9dc99c0e60a7995a
* Disble modifying libtool file in build directory. Otherwise, it changes
the DLL name. That libtool logic was added in this commit
https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=commit;h=e622e36f1f32641c66b28a0de95c75ae35f6ca05
But the cmake files expect previous DLL names.
> gpgme: update to 1.22.0

- mingw-w64-spirv-cross/PKGBUILD
and remove python-nose dep, I can't find anything referencing it
> spirv-cross: Update to 1.3.261.0

- mingw-w64-tor/PKGBUILD
Add pgp keys to validate source tarball
> tor: update to 0.4.8.4

- mingw-w64-sqlite3/0001-sqlite-pcachetrace-include-sqlite3.patch
- mingw-w64-sqlite3/PKGBUILD
The new patch file fixes the following compiler error.
../../../sqlite-src-3430000/ext/misc/pcachetrace.c:29:8: error: unknown type name 'sqlite3_pcache_methods2'
29 | static sqlite3_pcache_methods2 pcacheBase;
|        ^~~~~~~~~~~~~~~~~~~~~~~
> sqlite3: update to 3.43.0

- mingw-w64-openblas/002-lgfortran-requires-lquadmath.patch
- mingw-w64-openblas/PKGBUILD
0.3.24 now supports Flang, but unfortunately Flang doesn't fully support OpenMP.
So We either build LAPACK with Flang and disable OpenMP or leave as It is (Build C_LAPACK)
> openblas: update to 0.3.24

- mingw-w64-SDL2_image/PKGBUILD
- mingw-w64-darktable/PKGBUILD
- mingw-w64-kimageformats-qt5/PKGBUILD
- mingw-w64-libavif/PKGBUILD
- mingw-w64-libgd/PKGBUILD
- mingw-w64-python-imagecodecs/PKGBUILD
Deps need patching/update because of API change and/or `SameMajor` CMake version matching policy.
> libavif: update to 1.0.1

- mingw-w64-hdf5/PKGBUILD
> Fix ZLIB and SZIP for HDF5

- mingw-w64-binutils/PKGBUILD
Makes `ld` faster. Should fix #7660.
> binutils: backport patch "optimize handle_COMDAT"

- mingw-w64-opensubdiv/PKGBUILD
* This halves the size of the package.
* Also remove full path reference in cmake files.
> opensubdiv: split docs into separate package

- mingw-w64-lsd/PKGBUILD
notable changes:
- changed upstream URL
- nerd-fonts are now in repo, uncomment optdepends
- install license in correct directory
> lsd: update to 1.0.0

- mingw-w64-python-build/0001-optional-colorama.patch
- mingw-w64-python-build/PKGBUILD
it's optional in our case, since it would break bootstrapping otherwise.
> python-build: remove colorama from dependencies

- mingw-w64-dust/PKGBUILD
took workaround from other packages that use windows-0.48.0 crate
> dust: try to fix building on aarch64

- mingw-w64-libwebp/PKGBUILD
since the upstream commit doesn't apply cleanly, take the backported one from mozilla for now
> libwebp: backport security fix

- mingw-w64-mpc/PKGBUILD
- mingw-w64-mpfr/PKGBUILD
I am building a static gcc toolchain, but these static libraries are missing. Is there any reason they are disabled? I think there is no harm in adding them, they seem to be included already for libgmp (which is part of this family of libs).
> mpc,mpfr: enable static libs

- mingw-w64-gmp/PKGBUILD
- mingw-w64-gmp/gmp-staticlib.diff
See discussion in https://github.com/msys2/MINGW-packages/pull/18470#issuecomment-1718052861
This introduces a macro `GMP_STATICLIB` that will allow applications to build against the static `libgmp.a` library, analogous to `LIBXML_STATIC` or `CURL_STATICLIB` or `NGHTTP2_STATICLIB` and so on.
> gmp: add macro to let applications link static

- mingw-w64-typst/PKGBUILD
should no longer be needed for newer windows-targets
> typst: remove windows-targets workaround

- mingw-w64-python-anyio/PKGBUILD
- mingw-w64-python-starlette/PKGBUILD
it's not compatible with newer anyio and starlette
see https://github.com/msys2/MINGW-packages/commit/41fd5f246e4a4a2fccdd61b0490d4b31c6f5dfd9#commitcomment-127546512
> fastapi reverts

- mingw-w64-jj/PKGBUILD
fixes #17553 
maybe will update package while at it (if needed) but later
just for interest, do we need to switch to versioned tag?
> jj: link to AUR's jujutsu

- mingw-w64-xvidcore/PKGBUILD
This fixes the following linker error with
* gcc:
ld.exe: cannot find -lxvidcore: No such file or directory
ld.exe: note to link with lib/xvidcore.a use -l:xvidcore.a or rename it to libxvidcore.a
* clang:
lld: error: unable to find library -lxvidcore
cc: error: linker command failed with exit code 1 (use -v to see invocation)
Fixes https://github.com/msys2/MINGW-packages/issues/18553
> xvidcore: Add lib prefix with static and import library name

- mingw-w64-hdf5/0001-hdf5-pkgconfig-use-requires-private.patch
- mingw-w64-hdf5/PKGBUILD
This adds openssl and curl in Requires.private field in hdf5.pc file.
Otherwise, those libraries were added in Libs.private with full path.
It caused linking errors like following.
ld.exe: cannot find -lC:/msys64/mingw64/lib/libcurl.dll.a: Invalid argument
ld.exe: cannot find -lC:/msys64/mingw64/lib/libssl.dll.a: Invalid argument
ld.exe: cannot find -lC:/msys64/mingw64/lib/libcrypto.dll.a: Invalid argument
ld.exe: cannot find -lC:/msys64/mingw64/lib/libz.dll.a: Invalid argument
ld.exe: cannot find -lC:/msys64/mingw64/lib/libsz.dll.a: Invalid argument
The remaining zlib and libaec are kept in Libs.private with the library
path stripped. Those compression libraries are in LINK_COMP_LIBS in
cmake file and that helps to separate them from curl and openssl.
Fixes …
> hdf5: Use Requires.private in pkgconfig file

- mingw-w64-jj/PKGBUILD
~~this provides 2 extra binaries: `fake-editor` and
`fake-diff-editor`~~ now not, see further conversation
> jj: switch to cargo install

- mingw-w64-vulkan-utility-libraries/PKGBUILD
* there was a copy/paste error in the license path
* Remove vk_enum_string_helper.h for now, should be fixed in the next vulkan sdk version
Fixes #18582
> vulkan-utility-libraries: fix file conflicts with vulkan-validation-layers

- mingw-w64-flang/0004-avoid-dependency-on-libcxx.patch
- mingw-w64-flang/0006-Rename-flang-new-flang-experimental-exec-to-flang.patch
- mingw-w64-flang/PKGBUILD
- mingw-w64-mlir/PKGBUILD
- mingw-w64-openmp/PKGBUILD
flang fails to build on GNU environments even we force clang+lld.
```
[268/359] Linking CXX executable bin\tco.exe
FAILED: bin/tco.exe 
cmd.exe /C "cd . && D:\M\msys64\mingw64\bin\clang++.exe -march=nocona -msahf -mtune=generic -O2 -pipe -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -ffunction-sections -fdata-sections -Wno-deprecated-copy -Wno-string-conversion -Wno-ctad-maybe-unsupported …
```
> llvm: update to 17.0.1 - Part2

- mingw-w64-libraw/0001-libraw-pkgconfig-remove-stdcxx.patch
- mingw-w64-libraw/PKGBUILD
libstdc++ is not available in clang environments.
> libraw: Remove hardcoded stdc++ in pkgconfig file

- mingw-w64-fmt/0001-no-private-clang-header.patch
- mingw-w64-fmt/PKGBUILD
> fmt: workaround for llvm 17

- mingw-w64-akira/PKGBUILD
> akira: Enable clang64 and clangarm64 builds

- mingw-w64-libxml++/PKGBUILD
```
ninja: Entering directory `C:/Dev/Github/MINGW-packages/mingw-w64-libxml++/src/build-aarch64-w64-mingw32'
ninja: no work to do.
1/19 dom_build_example                                       OK              0.09s
2/19 dom_parse_entities_example                              OK              0.09s
3/19 dom_parser_example                                      OK              0.07s
4/19 dom_parser_raw_example                                  OK              0.06s
5/19 dom_read_write_example                                  OK              0.05s
6/19 dom_update_namespace_example                            OK              0.04s
7/19 dom_xinclude_example                                    OK              0.13s
8/19 dom_xpath_example                                       OK              0.11s …
```
> libxml++: Enable aarch64 builds

- mingw-w64-arrow/PKGBUILD
- mingw-w64-python/0148-Use-shared-instead-of-mdll.patch
- mingw-w64-python/PKGBUILD
Confirm it by reenabling glib for arrow on clang environments where It was failing because if this bug.
> Python: use `-shared` instead if `-mdll`

- mingw-w64-glib2/PKGBUILD
While the .pc file already contains absolute paths to .exe glib tools without .exe in the pc, a recent meson change in meson made it no longer find the tools.
Since we created those .exe we might as well adjust the path in the .pc files, so that any meson error is at least no longer MSYS2 specific.
> glib2: add .exe extension in .pc file for wrappers we create

- mingw-w64-harfbuzz/PKGBUILD
- mingw-w64-pango/PKGBUILD
> Add CAIRO_WIN32_STATIC_BUILD for the static builds depending on cairo

- mingw-w64-librsvg/PKGBUILD
- mingw-w64-librsvg/glib-rs.patch
This fixes #18574. Basically this reverts https://github.com/gtk-rs/gtk-rs-core/commit/d14883cbb9f56a5b63af0ab6a600a76d5c6a49c2 which fixed some problem with dynamic linking on MSVC.
Also a bit of an experiment in packaging a patch for a rust dependency, which is perhaps something we may need to start doing more often. I tried to do it as clearly as possible. It works, but completely understand if you feel it is still too messy.
See upstream discussions: 
- https://github.com/gtk-rs/gtk-rs-core/pull/1199
- https://github.com/gtk-rs/gir/pull/1475
- https://gitlab.gnome.org/GNOME/librsvg/-/issues/896
> librsvg: fix static build

- mingw-w64-python-lazy-loader/PKGBUILD
- mingw-w64-python-scikit-image/PKGBUILD
Required for updating scikit-image and other "scientific Python" libraries: https://scientific-python.org/specs/
See also https://aur.archlinux.org/packages/python-lazy-loader
> python-lazy-loader: new package, update scikit-image

- mingw-w64-python-llvmlite/PKGBUILD
- mingw-w64-python-numba/PKGBUILD
see: https://github.com/numba/llvmlite/issues/994
see: https://github.com/numba/numba/issues/9041
I will disable i686 in dependent packages later.
> update numba/llvmlite to 0.58.1/0.41.1

- mingw-w64-ffmpeg/PKGBUILD
* This change fixes the following error with configure command.
ERROR: nvenc requested but not found
* The compiler error in config.log is as following.
test.c: In function 'f':
test.c:3:54: error: 'NV_ENC_PRESET_HQ_GUID' undeclared (first use in this function);
did you mean 'NV_ENC_PRESET_P7_GUID'?
3 | void f(void) { struct { const GUID guid; } s[] = { { NV_ENC_PRESET_HQ_GUID } }; }
|                                                      ^~~~~~~~~~~~~~~~~~~~~
|                                                      NV_ENC_PRESET_P7_GUID
> ffmpeg: rebuild for ffnvcodec-headers update

- mingw-w64-ffmpeg4.4/PKGBUILD
* This change fixes the following error with configure command.
ERROR: nvenc requested but not found
* The compiler error in config.log is as following.
test.c: In function 'f':
test.c:3:54: error: 'NV_ENC_PRESET_HQ_GUID' undeclared (first use in this function);
did you mean 'NV_ENC_PRESET_P7_GUID'?
3 | void f(void) { struct { const GUID guid; } s[] = { { NV_ENC_PRESET_HQ_GUID } }; }
|                                                      ^~~~~~~~~~~~~~~~~~~~~
|                                                      NV_ENC_PRESET_P7_GUID
> ffmpeg4.4: rebuild for ffnvcodec-headers update

- mingw-w64-calceph/PKGBUILD
The CALCEPH Library is designed to access the binary planetary ephemeris files
> calceph: new package

- mingw-w64-zeromq/PKGBUILD
This fixes the following compiler error in aarch64 build.
../zeromq-4.3.5/src/clock.cpp:251:48: error: use of undeclared identifier 'nsecs_per_usec'; did you mean 'usecs_per_sec'?
251 |     return static_cast<uint64_t> (ts.tv_sec) * nsecs_per_usec * usecs_per_sec
|                                                ^~~~~~~~~~~~~~
|                                                usecs_per_sec
../zeromq-4.3.5/src/clock.cpp:106:16: note: 'usecs_per_sec' declared here
106 | const uint64_t usecs_per_sec = 1000000;
|                ^
> zeromq: Fix aarch64 build

- mingw-w64-qt6-static/PKGBUILD
> qt6-static: re-introduce qtcharts.

- mingw-w64-python-qtconsole/PKGBUILD
Without this dependency the `jupyter-qtconsole` can't be launched.
> python-qtconsole: Add qt5-svg to depends

- mingw-w64-glib2/PKGBUILD
patch is included in this new release
> glib2: Update to 2.78.1

- mingw-w64-python-pysfcgal/PKGBUILD
- mingw-w64-sfcgal/PKGBUILD
Update to 1.5.0
Use new gitlab url
Changes: 
```
https://gitlab.com/sfcgal/SFCGAL/-/releases/v1.5.0
SFCGAL 1.5.0 (2023-10-30):
* Add visibility algorithms (Loïc Bartoletti)
* Straight Skeleton: Add a version with extrusion
* WKT: Fix triangle code (Loïc Bartoletti)
* Allow to disable GMPXX (Loïc Bartoletti, Fixes #249 and #252)
* Add polygon partition (Raphaël Delhome, Loïc Bartoletti)
* Minor typo correction (Regina Obe, #280)
* Remove CGAL unit test (Fix #257, Loïc Bartoletti)
* [C API] Add sfcgal_point_create_from_xyzm and sfcgal_point_create_from_xym functions (Loïc Bartoletti #274)
* Update CI and add FreeBSD, macOs CI (Loïc Bartoletti)
* Minors fixes (Loïc Bartoletti #269 and #270)
* Remove useless garden tests (Loïc Bartoletti)
* Fix SPDX-License-Identifier (Loïc Bartoletti …
```
> SFCGAL: Update to 1.5.0

- mingw-w64-mpv/PKGBUILD
- mingw-w64-vapoursynth/PKGBUILD
This reverts commit b8c3ea257b1ac2bff9126a67db2de41456802b52.
> vapoursynth: Re-enable clang32 due to OOM issue

- mingw-w64-suitesparse/PKGBUILD
Also skip building factory kernels for GraphBLAS and rely on the JIT compiler instead as proposed by upstream.
> suitesparse: update to 7.3.1

- mingw-w64-curl/0001-Make-cURL-relocatable.patch
- mingw-w64-curl/PKGBUILD
Use single_path_relocation_lib() everywhere which does the same as before.
> curl: port to simpler relocation API

- mingw-w64-connect/0001-Make-it-relocatable.patch
- mingw-w64-connect/PKGBUILD
And also fix it, since PARAMETER_FILE didn't have the same prefix and made relocation fail.
> connect: port to single_path_relocation

- mingw-w64-ffmpeg/0005-Win32-Add-path-relocation-to-frei0r-plugins-search.patch
- mingw-w64-ffmpeg/PKGBUILD
* only use single_path_relocation_lib()
* don't look at the other default paths, they can be a security issue since those paths are user writable by default
> ffmpeg: path relocation cleanups

- mingw-w64-gettext/0001-printf_parse-fix-off-by-two.patch
- mingw-w64-gettext/PKGBUILD
The `%I64` printf format family is a Windows-specific extension that has been handled for, like, eternity in `mingw-w64-gettext`. But the recent update to v0.22.3 broke that.
The reason for that is a story of two episodes:
- gnulib slipped in [a major refactoring](https://git.savannah.gnu.org/cgit/gnulib.git/commit/?id=480a59ba60fa0b43a1cebe218bbcea6a947f1e86) of the `printf()` format parsing into a commit whose purpose was to support new size specifiers.
Unfortunately, the code handling `%I64` was converted incorrectly, where it previously skipped the `64` part before looking for the conversion specifier (correct) but now no longer does so (incorrect) ([look for `'I'`](https://git.savannah.gnu.org/cgit/gnulib.git/diff/lib/printf-parse.c?id=480a59ba60fa0b43a1cebe218bbcea6a947f1e86) and …
> gettext: fix the regression where `%I64d` support was broken

- mingw-w64-libaribcaption/PKGBUILD
This seems to be a replacement for aribb24, at least ffmpeg can use it instead of aribb24, and it is maintained.
> Add libaribcaption 1.1.1

- mingw-w64-suitesparse/PKGBUILD
There is a relocation issue when it comes to the path to the compiler that is used for the JIT compilation in GraphBLAS. (Sorry, I didn't notice before. I accidentally tested with a locally compiled library without realizing.)
This should be fixed by cherry-picking the upstreamed change.
> suitesparse: Fix relocation issue with GraphBLAS JIT compiler

- mingw-w64-python-shtab/PKGBUILD
- mingw-w64-python-sphinx-argparse/PKGBUILD
- mingw-w64-python-tldr/PKGBUILD
also adds python-shtab and python-shpinx-argparse as dependencies.
~~currently I receive an error while building tldr. I have no idea what's wrong~~ fixed
> python-tldr: new package

- mingw-w64-cmake/PKGBUILD
this makes FindOpenMP() set the openmp version again for clang environments.
> cmake: fix openmp v5.1 support

- mingw-w64-keepassxc/PKGBUILD
Incorrect syntax caused it to display as:
Also added repository url.
> keepassxc: fix license syntax and add repository url

- mingw-w64-octave/PKGBUILD
- mingw-w64-sundials/PKGBUILD
I *think* I got rid of all dependencies that require MSMPI. But I can't actually test on Windows on ARM (because I don't have access to it).
I just checked if that configuration would build for a MINGW64 environment. It does and all checks still pass.
There should be no functional difference for the already distributed binaries.
> Next attempt to build sundials for Windows on ARM

- mingw-w64-wxwidgets3.2/PKGBUILD
add hack to fix wxPython CLANG builds.
> wxwidgets3.2: Update to 3.2.4 and

- mingw-w64-pidgin/PKGBUILD
Changelog from upstream: Remove a string from the Romanian translation that’s breaking iconv on Windows.
> mingw-w64-pidgin: Updated to 2.14.12

- mingw-w64-gst-plugins-rs/PKGBUILD
Move to the release tags using the general gstreamer version.
disable dav1d for now: Package 'dav1d' has version '1.3.0', required version is '<= 1.2.1'
> gst-plugins-rs: Update to 1.22.7

- mingw-w64-faad2/PKGBUILD
the missing man page has been fixed upstream, so remove that workaround
> faad2: Update to 2.11.1

- mingw-w64-libva/0001-libva-add-driver-path-relocation.patch
- mingw-w64-libva/PKGBUILD
needs mesa installed
```console
$ vainfo.exe
Trying display: win32
libva info: VA-API version 1.20.0
libva info: Trying to open C:\msys64\ucrt64\bin\vaon12_drv_video.dll
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
C:\msys64\ucrt64\bin\vainfo.exe: VA-API version: 1.20 (libva 2.20.0)
C:\msys64\ucrt64\bin\vainfo.exe: Driver version: Mesa Gallium driver 23.2.1 for D3D12 (Radeon RX 590 Series)
C:\msys64\ucrt64\bin\vainfo.exe: Supported profile and entrypoints
VAProfileH264ConstrainedBaseline: VAEntrypointVLD
VAProfileH264Main               : VAEntrypointVLD
VAProfileH264High               : VAEntrypointVLD
VAProfileHEVCMain               : VAEntrypointVLD
VAProfileHEVCMain10             : VAEntrypointVLD
VAProfileNone                   : …
```
> libva: add relocation support for the default drivers path

- mingw-w64-libvips/PKGBUILD
Hm, [the `.dll.a` import stubs are again being created although `shared_module()` is used](https://github.com/mesonbuild/meson/issues/12372), so this [might not be limited to meson-python](https://github.com/msys2/MINGW-packages/pull/18706#issuecomment-1747098489)...
P.S. Also seems to be the case w/ babl, gimp, and gdk-pixbuf among others.
> libvips: update to 8.15.0

- mingw-w64-libgcrypt/PKGBUILD
and refresh the active signing key list based on
https://gnupg.org/signature_key.html
> libgcrypt: Update to 1.10.3

- mingw-w64-wireshark/PKGBUILD
Switch-over the package to build from a tarball.
Also add new dependency nghttp3.
> wireshark: Update to 4.2.0

- mingw-w64-ffmpeg/0009-wrong-null-type.patch
- mingw-w64-ffmpeg/0015-guard-null-hw-frames-ctx.patch
- mingw-w64-ffmpeg/PKGBUILD
* Remove patch included in the release
* Add libva dependency, changelog mentions this should be supported now
* Replace libmfx with libvpl since, " libmfx is deprecated. Please run configure with --enable-libvpl to use libvpl instead."
* Add a patch to fix the clang32 build (the usual VK_NULL_HANDLE != NULL issue)
> ffmpeg: Update to 6.1

- mingw-w64-python-sqlmodel/0001-sqlmodel-0.0.12-fix-version.patch
- mingw-w64-python-sqlmodel/PKGBUILD
~~Based on https://github.com/tiangolo/sqlmodel/pull/563.~~
*UPDATE*: Good news. Porting to `SQLAlchemi 2.0` done there https://github.com/tiangolo/sqlmodel/pull/700.
> python-sqlmodel: New package

- mingw-w64-minidump-stackwalk/PKGBUILD
it seems that we can enable arm64 there
> minidump-stackwalk: update to 0.19.1

- mingw-w64-python-jellyfish/PKGBUILD
removed windows-targets workaround
> python-jellyfish: update to 1.0.3

- .github/workflows/main.yml
Or should it run on all environments?
> CI: Run package-grokker on both ucrt64 and clang64

- mingw-w64-python-maturin/PKGBUILD
ring dependency is updated in this release, enabling its features for aarch64
> python-maturin: update to 1.3.2

- mingw-w64-ruby/81a1fca366d9f5b49836e42acdb19f3ff0c8173c.patch
- mingw-w64-ruby/PKGBUILD
This fails now:
windres.exe --preprocessor=clang --preprocessor-arg=-E --preprocessor-arg=-xc a.rc -o a.o
We should probably report it to upstream to see what they say. This patch just removes the --preprocessor args, since the windres defaults are equivalent anyway.
> ruby: fix the build with recent llvm windres

- mingw-w64-gettext/PKGBUILD
In recent versions of `gettext`, `relocatable.o` is no longer linked into `libintl.a` directly, but indirectly via the (convenience) library `libgnu.a`.
While two versions of `relocatable.o` are still built (one that exports `DllMain` and one that doesn't), only one of those object files (the one that exports `DllMain`) is linked into the convenience library `libgnu.a`. That means that the *static* library `libintl.a` (that links all objects from that convenience library) now also exports `DllMain`.
Prevent that from happening by building static and shared libraries in separate steps.
This should be fixing the issue described in #19086.
> gettext: build static and shared libraries separately

- mingw-w64-msitools/002-use-paths-relative-to-the-installation-prefix.patch
- mingw-w64-msitools/PKGBUILD
This patch-set supersedes an earlier attempt: https://github.com/msys2/MINGW-packages/pull/18611
> msitools: Make DATADIR and LIBDIR relative to runtime installation location

- mingw-w64-86box/PKGBUILD
Haven't tested yet, but I ported 86Box over in upstream myself and built in on MSYS2 CLANGARM64 manually for many times, it should work.
> 86Box: Enable clangarm64

- mingw-w64-vlc/PKGBUILD
vlc 3 is not compatible with libplacebo v6 and blocks updating other packages. From a quick glance it only seems to affect the opengl video output, which isn't the default anyway, so hopefully shouldn't affect many users.
If this is a problem let us know.
> vlc: build without libplacebo

- mingw-w64-meson/PKGBUILD
While pkgconf is strictly not required to build things, it usually is and might lead to confusing when missing, or worse, when the msys pkgconf is installed and results in hard to understand errors.
> meson: depend on pkgconf

- mingw-w64-readline/0003-fd_set.patch
- mingw-w64-readline/PKGBUILD
0003-fd_set.patch: remove hunk which is included in readline82-004
https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-004
XXX: make mingw-w64 provide a dummy alarm(), this just worked because
old clang wasn't that strict.
> readline: Update to 8.2.007

- mingw-w64-python-numba/PKGBUILD
* don't strip
* don't call sed on the binary launcher
remove cython dep while at it, likely not needed
> numba: fix exe launcher

- mingw-w64-czkawka/PKGBUILD
see https://github.com/qarmin/czkawka/issues/1148
czkawka_gui binary throws SIGSEGV at startup. anyone interested feel free to help
> remove czkawka_gui for CLANG* enironments

- mingw-w64-sccache/PKGBUILD
- `--features all` is enabled by default, removing
- `WINAPI_NO_BUNDLED_LIBRARIES` needs to be set all the time, otherwise it's recompiled
- give another try for aarch64
> sccache: update to 0.7.4

- mingw-w64-ripgrep/PKGBUILD
~~- enabled clang32 (why wasn't it enabled?)~~ see https://github.com/msys2/MINGW-packages/pull/19221#issuecomment-1830400981
- cleanup
- fixed missing `--features 'pcre2'` in `cargo install`
> ripgrep: update to 14.0.2

- mingw-w64-onefetch/PKGBUILD
removed windows-targets workaround - updated upstream
added `WINAPI_NO_BUNDLED_LIBRARIES` in `check()` so it's not recompiled while testing
> onefetch: update to 2.19.0

- mingw-w64-gcc/PKGBUILD
I have tested the artifacts on my local machine building a small project:
Without PGO: 188s 190s 189s average~=189s
With PGO: 176s 177s 179s average~=177.3
A speedup = (189-177.3)/189 ~= 6%
Wait for other members to test and comment
> gcc: Build with PGO

- mingw-w64-clang/PKGBUILD
enabled only for clang64 and clangarm64
> clang: Build with PGO

- mingw-w64-llvm-15/PKGBUILD
Previously We could only link to its libraries. Now we could use the compilers to build.
> llvm-15: Make clang compiler functional by specifying SYSROOT

- mingw-w64-jj/PKGBUILD
added zlib dependency as needed by ntldd output
specified `-p jj-cli`, otherwise it's recompiled
> jj: update to 0.12.0

- mingw-w64-zxing-cpp/PKGBUILD
This is a fix for a c++ ABI breakage of the 2.2.0 release. Only of relevance if people want to run an executable that was compiled with dynamically linking against version 2.1.0 and is still supposed to run with a new dll (of version 2.2.1).
> zxing-cpp: update to 2.2.1

- mingw-w64-pastix/PKGBUILD
In new version "cmake: Fix example installation path"
> pastix: update to 6.3.2

- mingw-w64-mesa/0001-mesa-dzn-cast-void-pointer.patch
- mingw-w64-mesa/PKGBUILD
dzn started failing to build for unknown reasons. Trying to build 23.3,0 also fails in dzn so ir's a bug in a dependency. Maybe we need to update Directx-headers to the untagged v1.611.1.
> mesa: Update to 23.3.1

- mingw-w64-watchexec/PKGBUILD
- specified `-p watchexec-cli`, otherwise it's recompiled
- more competions
- some docs' cleanup
> watchexec: update to 1.24.1

- mingw-w64-libdovi/PKGBUILD
> libdovi: fix missing `--all-features` option

- mingw-w64-gtk3/PKGBUILD
move back to use the tarball, since there haven't been many updates recently, and cloning is slow and results in huge source packages.
> gtk3: Update to 3.24.39

- mingw-w64-uriparser/PKGBUILD
For some reason, when shared build installed after static one those files got removed!
> uriparser: restore uriparser-config-*.cmake files

- mingw-w64-python-pysfcgal/PKGBUILD
- mingw-w64-sfcgal/PKGBUILD
Update to 1.5.1
Changes:
```
1.5.1 (2023-12-21):
* Rewrite and fix visibility algorithm (Loïc Bartoletti)
* Apply clang-tidy fixes (Loïc Bartoletti)
* Add vcpkg CI and temporarily disable alpha-shapes for MSVC (Loïc Bartoletti)
```
> SFCGAL: Update to 1.5.1

- mingw-w64-clang/PKGBUILD
See https://github.com/msys2/MINGW-packages/pull/19157#issuecomment-1825285063
> clang: backport binutils windres compat changes

- mingw-w64-i2pd/PKGBUILD
We created minor release with OpenSSL 3.2.0 support fix, so now it can be updated.
> i2pd: update to 2.50.1

- mingw-w64-delta/PKGBUILD
- mingw-w64-libblocksruntime/PKGBUILD
~~wrote `git-delta-git` for AUR references so it properly links to it
(there is no other way to do it)~~
I decided it's better to just remove the reference
> {libblocksruntime,delta}: cleanup wrong references

- mingw-w64-python-versioneer/001-fix-build.patch
- mingw-w64-python-versioneer/PKGBUILD
This package is required for the latest constantly and pandas python packages.
But It fails to build because the prefix disk `D:\` is different that source disk `C:\`.
> [new-package] python-versioneer 0.29

- mingw-w64-libavif/0001-libavif-pkgconfig-add-private-deps.patch
- mingw-w64-libavif/PKGBUILD
This fixes static linking with sdl2_image library.
Fixes #19538
> libavif: Add private dependencies in pkgconfig file

- mingw-w64-android-tools/0004-fix-SetThreadDescription-name-collision.patch
- mingw-w64-android-tools/PKGBUILD
SetThreadDescription was added in https://github.com/mingw-w64/mingw-w64/commit/3a137bd87e commit.
Thanks to MehdiChinoune who found this issue.
> android-tools: Fix compiler error due to SetThreadDescription name collision

- mingw-w64-glpk/0003-no-embedded-zlib.patch
- mingw-w64-glpk/0004-no-embedded-suitesparse.patch
- mingw-w64-glpk/PKGBUILD
GLPK is a very stable library that gets updated only rarely. That means that the embedded zlib and SuiteSparse sources are pretty old by now.
Adopt patches from Debian to use the (more up-to-date) libraries instead:
https://salsa.debian.org/science-team/glpk/-/tree/6aef0457486b0bb014b755ac5c8408c8c697afd4/debian/patches
> glpk: Do not use embedded zlib nor embedded suitesparse

- mingw-w64-python-lxml/PKGBUILD
the build options forcing cython to run were no longer passed to setup.py which meant the cython patch preventing a crash was no longer included in the compiled C code, which re-surfaced crashes in the meson test suite for example.
> Fix lxml crashing

- mingw-w64-openjph/0001-cmake-mingw-fixes.patch
- mingw-w64-openjph/PKGBUILD
Turned off building sample binaries and TIFF support in this initial release due to https://github.com/aous72/OpenJPH/issues/114
> openjph: new package

- mingw-w64-python-llvmlite/PKGBUILD
> python-llvmlite: remove cython from makedepends

- mingw-w64-notepad++/PKGBUILD
- mingw-w64-notepad++/Parameters.h.patch
I've added the patch to get rid of clang64 compilation issues, will create a PR for upstream later:
```
VERBOSE=1 mingw32-make -f ../notepad-plus-plus-8.6.1/PowerEditor/gcc/makefile
...
+ compiling C:/MINGW-packages/mingw-w64-notepad++/src/notepad-plus-plus-8.6.1/PowerEditor/src/WinControls/Preference/preferenceDlg.cpp
g++ -include C:/MINGW-packages/mingw-w64-notepad++/src/notepad-plus-plus-8.6.1/PowerEditor/gcc/gcc-fixes.h -std=c++20 -O3 -Wno-alloc-size-larger-than -Wconversion -IC:/MINGW-packages/mingw-w64-notepad++/src/notepad-plus-plus-8.6.1/PowerEditor/../scintilla/include -IC:/MINGW-packages/mingw-w64-notepad++/src/notepad-plus-plus-8.6.1/PowerEditor/../lexilla/include -IC:/MINGW-packages/mingw-w64-notepad++/src/notepad-plus-plus-8.6.1/PowerEditor/src/. …
```
> notepad++: update to 8.6.1

- mingw-w64-opencv/PKGBUILD
Set C++ standard to 17 to fix broken protobuf support.
Thank's to @Biswa96 who came with the link
https://github.com/opencv/opencv/blob/4.9.0/cmake/OpenCVFindProtobuf.cmake#L84
Closes #19677
> mingw-w64-opencv: rebuild with cxx_std=17

- mingw-w64-lfortran/001-win-install.patch
- mingw-w64-lfortran/PKGBUILD
LFortran: Modern open-source (BSD licensed) interactive Fortran compiler built on top of LLVM.
LFortran is similar to Julia and can dynamically execute or statically compile Fortran code.
Add a patch (`001-win-install.patch`) to build LFortran in the MINGW64 environment, which will be subsequently committed to the [LFortran repository](https://github.com/lfortran/lfortran).
> [new package] lfortran 0.30.0

- mingw-w64-ruff/PKGBUILD
like in Arch. ruff itself doesn't depend on python module
> ruff: split into bin and python lib packages 

- mingw-w64-libjxl/PKGBUILD
Dry run for now - there's quite a few dependencies to be checked and rebuilt as the API has changed.
darktable 4.6 was already proofed ahead for 0.9.x
gimp ?
gimp3 ?
graphicsmagick ?
imagemagick ?
kimageformats-qt5 ?
krita ?
libvips ?
python-imagecodecs ?
SDL2_image ?
> libjxl: update to 0.9.1

- mingw-w64-orcus/001-fix-build-on-mingw.patch
- mingw-w64-orcus/002-workaround-for-gcc.patch
- mingw-w64-orcus/PKGBUILD
It looks like stdc++/filesystem is broken with GCC. 
- It fails to build when using std::filesystem
- It fails to link when force std::experimental::filesystem
- It fails to build also when trying to force boost::filesystem
In clang environments both std and boost filesystem build and link (didn't try std::experimental)
The library builds on ArchLinux and there is no reported issue about it, so It looks like a MINGW specific issue.
> [new-package] orcus 0.19.2

- mingw-w64-readline/0002-event-hook.patch
- mingw-w64-readline/PKGBUILD
This means we can apply all four patches unconditionally / they are more suitable for upstreaming.
> readline: Make event hook patch not break Unix build

- mingw-w64-nanovg/PKGBUILD
- mingw-w64-premake4/PKGBUILD
requires premake4, so bring it back
> nanovg: rebuild

- mingw-w64-ripgrep/PKGBUILD
a random investigation:
- `release-lto` profile enables strip and lto. see https://github.com/BurntSushi/ripgrep/blob/master/Cargo.toml#L74-L87
- `pkgconf` must be at makedepends, otherwise `pcre2` is recompiled from source and linked *staticly* (ntldd now shows a pcre2 dll). see https://github.com/BurntSushi/ripgrep?tab=readme-ov-file#building
- install completions in a new way
> ripgrep: improve package build

- mingw-w64-clucene/003-fix-pkgconfig-file.patch
- mingw-w64-clucene/004-fix-narrowing-conversions.patch
- mingw-w64-clucene/005-Replace-std-binary_function-with-typedefs.patch
- mingw-w64-clucene/PKGBUILD
https://gitlab.archlinux.org/archlinux/packaging/packages/clucene/-/blob/caf24cd2/clucene-narrowing-conversions.patch https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-cpp/clucene/files/clucene-2.3.3.4-fix-binary-function.patch?id=1ba9c12d
> clucene: Backport some patches from Arch and Gentoo

- mingw-w64-libmariadbclient/001-mingw-build.patch
- mingw-w64-libmariadbclient/004-fix-build-remote-io.patch
- mingw-w64-libmariadbclient/PKGBUILD
Offer more discoverability as mysqlclient by providing mysql_config.exe and mysqlclient.pc files which used by many projects to detect and link against MySQL.
> libmariadbclient: update to 3.3.8

- mingw-w64-ruff/PKGBUILD
I tried to apply workaround for fetching less deps, but maturin anyway downloads some more for other targets
> ruff: update to 0.1.14

- mingw-w64-libblocksruntime/0002-libblocksruntime-0.4.1-export-symbols.patch
- mingw-w64-libblocksruntime/PKGBUILD
Functions which are marked with `BLOCK_EXPORT`  are supposed to be externally visible, but miss the `__attribute__((dllexport))` attribute.  As a result, they are not exported from a .dll when compiled with clang.
Additionally, methods marked with `__attribute__((dllexport))`  cannot have the `__attribute__((weak))` attribute applied to them, so make that conditional on being compiled for non-Windows platforms.
Together with #19767, this helps compiling Objective C code on MinGW using the clang compiler.
> libBlocksRuntime: Mark public symbols with dllexport

- mingw-w64-PKGBUILD-templates/PKGBUILD.cargo-tarball.sh
- mingw-w64-bat/PKGBUILD
- mingw-w64-cargo-c/PKGBUILD
- mingw-w64-cargo-create-tauri-app/PKGBUILD
- mingw-w64-cargo-generate/PKGBUILD
- mingw-w64-cargo-local-registry/PKGBUILD
- mingw-w64-cargo-tauri/PKGBUILD
- mingw-w64-fd/PKGBUILD
- mingw-w64-hexyl/PKGBUILD
- mingw-w64-hyperfine/PKGBUILD
- mingw-w64-jj/PKGBUILD
- mingw-w64-mdbook-pikchr/PKGBUILD
- mingw-w64-mdbook/PKGBUILD
- mingw-w64-minidump-stackwalk/PKGBUILD
- mingw-w64-onefetch/PKGBUILD
- mingw-w64-ripgrep/PKGBUILD
- mingw-w64-sccache/PKGBUILD
- mingw-w64-starship/PKGBUILD
- mingw-w64-stork/PKGBUILD
- mingw-w64-tree-sitter/PKGBUILD
- mingw-w64-typst/PKGBUILD
- mingw-w64-uutils-coreutils/PKGBUILD
- mingw-w64-vivid/PKGBUILD
- mingw-w64-wasm-pack/PKGBUILD
- mingw-w64-watchexec/PKGBUILD
retry of #18231
what's changed:
- for packages that don't makedepend on `cargo-c`, `maturin`, `python` I specified target for fetching deps
- changed `--locked` to `--frozen` to ensure that there are no extra https requests (which means that extra deps are needed)
- small cleanup for some recipes (that includes trailing whitespaces and extra newlines, which my vscode trim automaticly)
there is no need to rebuild these packages as this doesn't affect `build()` stage, only `prepare()`
I'm open for any feedback as this could be a breaking change :)
update: removed this for `sccache`: it tries to download a unix-specific dependency at build
update2: I changed indent from tab to spaces for sccache, so it should looks now normally
> fetch less crates in preparation step, take 2

- mingw-w64-libdovi/PKGBUILD
> libdovi: Remove full path reference in pkgconfig file

- mingw-w64-clang/10b78cc8cea65e7e77d227af4027963f39402724.patch
- mingw-w64-clang/1709e8c656de69f6d823a3ae6773bf815e373909.patch
- mingw-w64-clang/1d5106d69cf475215887c42834158d710e586f1b.patch
- mingw-w64-clang/9e3d915d8ebf86e24c9ff58766be8e7c6aa7b0c0.patch
- mingw-w64-clang/PKGBUILD
- mingw-w64-clang/b81ba52e15d95c3353489d4ce2f61c3771714c28.patch
- mingw-w64-clang/c65ae76326040369bcd3a85678ab76e402140036.patch
This pull request:
Backports the following fixes for clang:
- https://github.com/llvm/llvm-project/pull/77797
- https://github.com/llvm/llvm-project/pull/77385 
- https://github.com/llvm/llvm-project/pull/77255
which support compiling Objective-C code on mingw using Clang.
Since these fixes are specific to mingw, I hope it's appropriate to backport them to this repository before they land in the next clang release.
Additionally, around the time this PR was being created, the llvm repository switched from a state where the first 14 characters of the commit hash were sufficient to uniquely identify a commit (e.g. `f55e5434dce360`)  to a state where 15 characters were required (e.g. `f55e5434dce360b`).
For example, I was able to have …
> Clang: Backport fixes for Objective-C on mingw

- mingw-w64-sccache/PKGBUILD
upstream finally updated ring dependency! enabling clangarm64
> sccache: update to 0.7.6

- mingw-w64-llama.cpp/PKGBUILD
* bump LLAMA_WIN_VER to fix the build (it uses newer APIs that reuqire it)
* disable LLAMA_NATIVE so our CFLAGS are used
* disable ccache since that breaks the build somehow (ccache errors out)
> llama.cpp: Update to r1967.256d1bb0

- mingw-w64-bat/PKGBUILD
- make it to match template
- add changes for dynamic linking
- set `GIT_DIR=/dev/null` to resolve
<details>
```
Failed to add dependency on the git state: failed to canonicalize ~/MINGW-packages/.git\logs/HEAD: Системе не удается найти указанный путь. (os error 3). Git state changes might not trigger a rebuild.
Failed to add dependency on the git state: failed to canonicalize ~/MINGW-packages/.git\index: Системе не удается найти указанный путь. (os error 3). Git state changes might not trigger a rebuild.
Failed to add dependency on the git state: failed to canonicalize ~/MINGW-packages/.git\logs/HEAD: Системе не удается найти указанный путь. (os error 3). Git state changes might not trigger a rebuild.
Failed to add dependency on the git state: failed to canonicalize …
```
> bat: redesign recipe

- mingw-w64-emacs/PKGBUILD
There was some talk on enabling it in https://github.com/msys2/MINGW-packages/pull/19810 with the concern that compilation might take too long. Turns out, it doesn't, the CI finished in a bit more than 30 minutes, compared to around 15 minutes without AOT. That's quite reasonable (Github [recently bumping their hosted runners to 4 CPU cores](https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/) certainly helps), thus I think AOT should be enabled to save a lot of compilation for users.
> emacs: Enable ahead of time native compilation

- mingw-w64-gettext/PKGBUILD
90% is tools which is not needed at runtime, and since it's easy to split this way just split the two sub projects into two packages.
Other packages can switch to add gettext-tools to makedepends and just gettext-runtime to depends.
Also removes expat dependency, turns out it doesn't need it since 0.19.7
> gettext: split into gettext-runtime and gettext-tools

- mingw-w64-gcc/2f7e7bfa3c6327793cdcdcb5c770b93cecd49bd0.patch
- mingw-w64-gcc/3eeb4801d6f45f6250fc77a6d3ab4e0115f8cfdd.patch
- mingw-w64-gcc/PKGBUILD
ArchLinux named just lto-dump, should we follow them or name gcc-lto-dump?
> gcc: refactor installation and add gcc-lto-dump package

- mingw-w64-enchant/PKGBUILD
A hotfix [release](https://github.com/AbiWord/enchant/releases/tag/v2.6.7):
> This release fixes a bug introduced in 2.6.6 that would cause Enchant to crash when used with Hunspell. Apologies!
> enchant: Update to 2.6.7

- mingw-w64-openpgl/004-arm64-no-mm-malloc.patch
- mingw-w64-openpgl/PKGBUILD
same as with https://github.com/msys2/MINGW-packages/blob/1b4f088e43b9f317233de9717ba69468a856c7aa/mingw-w64-embree/002-arm64-no-mm-malloc.patch
> openpgl: work around missing _mm_malloc() on arm64

- mingw-w64-libpreferencepanes/PKGBUILD
Packages the https://github.com/gnustep/apps-systempreferences library.
This package contains the library component only; and excludes the actual system preferences application and the supporting bundles.
The libpreferencepanes names was chosen in analogy with how this library is packaged in Ubuntu: https://packages.ubuntu.com/noble/libpreferencepanes1
> libpreferencepanes: new package

- mingw-w64-gst-plugins-bad/PKGBUILD
- mingw-w64-openh264/0001-openh264-install-executables.patch
- mingw-w64-openh264/PKGBUILD
Previously, all symbols were exported from import library. The meson build system now uses proper DEF to export symbols.
This issue was reported by @1480c1 ❤️
> openh264: port to meson, fix import library

- mingw-w64-gnustep-base/PKGBUILD
- mingw-w64-gnustep-gui/PKGBUILD
- mingw-w64-gnustep-make/PKGBUILD
- mingw-w64-libobjc2/PKGBUILD
- mingw-w64-libpreferencepanes/PKGBUILD
Upstream libobjc2 now has clang64 support (via https://github.com/gnustep/libobjc2/pull/276).
Cherry-pick that commit and add clang64 to the build matrix for libobjc2.  This cherry-picked commit also fixes the ".dll.a" suffix for library objects, so we no longer need to manually rename that file.
> libobjc2: Add clang64 support

- mingw-w64-python-jupyter_notebook/PKGBUILD
- mingw-w64-python-jupyterlab/PKGBUILD
Looks like we should wait for the next release of the `notebook`...
> python-jupyterlab/notebook: update to 4.1.1/7.1.0

- mingw-w64-gnustep-base/PKGBUILD
Adds the following patches from the main branch of [gnustep/libs-base](https://github.com/gnustep/libs-base) to allow the config check [gnustep/libs-base/config/config.initialize.m](https://github.com/gnustep/libs-base/blob/master/config/config.initialize.m) to build and pass during the gnustep-base package build:
* https://github.com/gnustep/libs-base/commit/fe863c981d61e50e3ea9cbe7f2b23135c1f2faf1
* https://github.com/gnustep/libs-base/commit/87fc1f5e2e4094f49b330bece89ba8aa4436c684
The practical effect is the build process will detect that it is building against a runtime with thread-safe +initialize, and builds linking against gnustep-base in the msys2 environment will no longer print this warning message when they become multi-threaded:
```
WARNING your program is becoming …
```
> mingw-w64-gnustep-base: add patches to fix config check failure for thread-safe +initialize

- mingw-w64-qtwebkit/PKGBUILD
See https://github.com/msys2/MINGW-packages/issues/20090#issuecomment-1950335792
> qtwebkit: restore mingw32; fix build with libxml2 2.12.0

- mingw-w64-czkawka/PKGBUILD
- czkawka_gui works on CLANG*
- new feature `libraw`
- dependencies cleanup (but anyway they are installed with gtk4)
> czkawka: update to 7.0.0

- mingw-w64-gimp3/0003-dont-install-external-files.patch
- mingw-w64-gimp3/PKGBUILD
- mingw-w64-gimp3/gimp-script-fu-interpreter.interp
- mingw-w64-gimp3/luajit.interp
* remove .interp files, seem to be installed by default now
* add new deps
* fix gimp installing system files again for some reason
* Remove compiler flags for ignoring errors, seems to be fixed now
* Disable enable-default-bin, to avoid symlinks
> gimp3: Update to 2.99.18

- mingw-w64-gitui/PKGBUILD
- local build showed that libgit2 dynamic lib is used (zlib not)
- remove vendor-openssl feature which broke clangarm64 build
> gitui: update to 0.25.0

- mingw-w64-libobjc2/PKGBUILD
Both libobjc2 and gcc-objc provide an Objective C runtime, so these packages conflict with each other.
> libobjc2: conflicts with the GCC Objective C runtime

- mingw-w64-gettext/0024-disable-gnu-format.patch
- mingw-w64-gettext/PKGBUILD
It doesn't match what the gettext functions allow, so revert to avoid build warnings for things like %I64u
> gettext: revert upstream adding a printf format attribute

- mingw-w64-gdal/PKGBUILD
Skipped podofo for now because of licensing - could be done as optional and dynamic only I guess if there is a request for it...
> gdal: enable libjxl and openexr

- mingw-w64-libpng/PKGBUILD
switch to mozilla for the apng patch, since the patch set on sourceforge is lagging behind and no longer applies.
> libpng: Update to 1.6.43

- mingw-w64-scotch/PKGBUILD
Is this acceptable?  It's better than just not having the package at all :)
> scotch: Build without PT-Scotch in aarch64 (due to missing MPI)

- mingw-w64-vala-language-server/PKGBUILD
Add `meson` to optdepends to support meson projects, which is widely used in the vala.
> vala-language-server: add meson to optdepends

- mingw-w64-winfile/001-cpp-17.patch
- mingw-w64-winfile/PKGBUILD
> winfile: Fix building with Clang after Clang 17 and enable aarch64 builds

- mingw-w64-emacs/003-aarch64-fixes.patch
- mingw-w64-emacs/PKGBUILD
- mingw-w64-emacs/emacs-ARM64.manifest
> emacs: Enable aarch64 builds

- mingw-w64-pcre2/PKGBUILD
This removes pcre2-8 symbols with dllimport attributes in pcre2-posix.a library.
Fixes #20234
> pcre2: Fix static library

- mingw-w64-ossia-score/PKGBUILD
ossia score ([ossia.io](https://ossia.io/)) is a software for creating live audio, video, light & multimedia shows and art installations.
Note: the last current stable release needs some patches for building. Next version will work directly, I'll update the PR asap.
> Init mingw-w64-ossia-score package

- mingw-w64-opus/001-aarch64-features.patch
- mingw-w64-opus/PKGBUILD
```
ninja: Entering directory `C:/M_P/mingw-w64-opus/src/build-CLANGARM64'
ninja: no work to do.
1/15 test_unit_types              OK               0.12s
2/15 test_unit_mathops            OK               0.11s
3/15 test_unit_laplace            OK               0.08s
4/15 test_unit_dft                OK               0.06s
5/15 test_unit_rotation           OK               0.05s
6/15 test_unit_mdct               OK               0.20s
7/15 test_opus_padding            OK               0.09s
8/15 test_opus_projection         OK               0.06s
9/15 test_unit_cwrs32             OK               1.00s
10/15 test_unit_cwrs32             OK               1.08s
11/15 test_unit_entropy            OK               2.17s
12/15 test_opus_api                OK               4.07s
13/15 …
```
> opus: Enable detection of NEON and other aarch64 features

- mingw-w64-llama.cpp/PKGBUILD
- mingw-w64-ollama/0001-Hijack-the-build-for-msys2-P.patch
- mingw-w64-ollama/PKGBUILD
ollama supports windows now! 
ollama is a LLM manager, makes it easy to run LLM models, like mixtral, or deepseek, (there is already a llama.cpp package, but with ollama you can serve frontend of many llms)
The build uses powershell because upstream uses powershell for windows even though there are bash files for linux only, they are very biased towards MSVC.
It is possible there are upstream changes that can be done. maybe use bash instead of powershell for msys2, I just patched some powershell parts that were biased towards MSVC.
> [New package] ollama

- mingw-w64-python-rtree/0001-fix-mingw-finder.patch
- mingw-w64-python-rtree/PKGBUILD
> python-rtree: fix loading spatialindex dll

- mingw-w64-faudio/PKGBUILD
Use the -DPLATFORM_WIN32=TRUE cmake parameter to activate the win32-specific code instead of using SDL2, remove the SDL2 dependency and increase the pkgrel.
> faudio: switch from SDL2 dep to PLATFORM_WIN32

- mingw-w64-libc++/PKGBUILD
Don't use compiler-rt on non-clang environments
> libc++: fix building libunwind on mingw32

- mingw-w64-unordered-dense/PKGBUILD
The Vulkan Validation Layers is about to switch from using [robin_hood_hashing](https://github.com/martinus/robin-hood-hashing) to [unordered_dense](https://github.com/martinus/unordered_dense).
> unordered_dense: new package

- mingw-w64-vala/PKGBUILD
Remove CFLAG `-Wno-incompatible-pointer-types` since upstream fixed it.
See also: https://gitlab.gnome.org/GNOME/vala/-/commit/23ec71b1a5c4cead3d1bdac82e184d0a63fa7b79
> vala: update to v0.56.16

- mingw-w64-czkawka/PKGBUILD
upstream recommends to use it instead of czkawka_gui as krokiet has more reliable GUI backend
starting from this PR I'll use this `"$(rustc -vV | sed -n 's/host: //p')"` to fetch target triple
> add krokiet as separate package for czkawka

- mingw-w64-qt6-base/013-qt-5.7.0-qdbus-manager-quit.patch
- mingw-w64-qt6-base/PKGBUILD
Similar as f6eacbcdd74cc836294e8e7337c5d3cf772a3117
Fixes #13198 (but with qt6)
> qt6-base: Fix zombie processes due to qt dbus

- mingw-w64-PKGBUILD-templates/PKGBUILD.cargo-tarball.sh
arch now uses `"$(rustc -vV | sed -n 's/host: //p')"` to fetch the target triple, which is more minimalist way than we use now
> cargo-tarball template: fetch target triple in another way at preparation step

- mingw-w64-neovim-qt/PKGBUILD
> neovim-qt: Enable aarch64 builds

- mingw-w64-transmission/PKGBUILD
> transmission: Enable aarch64 builds

- mingw-w64-octave/0003-no-community-support.patch
- mingw-w64-octave/PKGBUILD
Build with some packages that are available on CLANGARM64 now.
Build with Qt5 packages for MINGW32, build with Qt6 packages otherwise.
Suppress more warnings from Clang that seem to break the terminal somehow.
Drop some configure flags that are no longer needed.
Refresh a patch that no longer applied cleanly.
> octave: update to 9.1.0

- mingw-w64-libobjc2/PKGBUILD
The [v2.2.1](https://github.com/gnustep/libobjc2/releases/tag/v2.2.1) release contains all patches which were required to get libobjc2 building on MSYS2, so we can now build from vanilla upstream.
> libobjc2: Update to 2.2.1

- mingw-w64-libdispatch/001-link-libBlocksRuntime.patch
- mingw-w64-libdispatch/PKGBUILD
patch **is not** included in the new release https://github.com/apple/swift-corelibs-libdispatch/compare/swift-5.9.2-RELEASE...swift-5.10-RELEASE
> libdispatch: update to 5.10

- mingw-w64-pango/PKGBUILD
See https://gitlab.gnome.org/GNOME/pango/-/merge_requests/726
Since I see crashes in gtk4. This doesn't help in my case, but let's backport it anyway.
> pango: backport a Windows double free fix

- mingw-w64-xz/PKGBUILD
That doesn't contain a configure, so run autogen.
Also needs extra build depends for things already included
in the tarball.
And remove the signing key from the bad actor.
> xz: Switch from upstream tarball to git tarball

- mingw-w64-gtk4/0002-default-to-gl-instead-of-ngl.patch
- mingw-w64-gtk4/PKGBUILD
Upstream report: https://gitlab.gnome.org/GNOME/pango/-/issues/789
This switches the default from ngl to gl. The crashes can still be reproduced via:
GSK_RENDERER=ngl adwaita-1-demo.exe
> gtk4: default to the old "gl" renderer to work around crashes

- mingw-w64-mcfgthread/PKGBUILD
1. Migrate from autotools to meson.
2. Fix x87 `long double` test on ARM64EC (thanks to @Blackhex)
3. Make use of `GetSystemTimePreciseAsFileTime()` (win8) and `QueryInterruptTime()` (win10) when they are available.
4. Exclude system suspension from relative timeout intervals, like `CLOCK_MONOTONIC` on Linux.
5. Make headers usable with VC++. For C additional experimental options are required. See [devblog](https://devblogs.microsoft.com/cppblog/c11-atomics-in-visual-studio-2022-version-17-5-preview-2/).
> mcfgthread: Update to v1.7.1

- mingw-w64-efxc2/PKGBUILD
Release is primarily a fix for passing defines for the compiler.
> mingw-w64-efxc2 - update to latest release.

- mingw-w64-netcdf-fortran/PKGBUILD
There is a `netcdf.inc` file in the hdf4 installation directory. I am about to submit a new package, netcdf-fortran, which also has a `netcdf.inc` in the installation directory, and the two cause a conflict. According to Debian's solution (refer to [libhdf-dev](https://packages.debian.org/bookworm/amd64/libhdf4-dev/filelist) and [libnetcdff-dev](https://packages.debian.org/bookworm/amd64/libnetcdff-dev/filelist)), it is proposed to move the installation directory of hdf4 from include to include/hdf, please discuss.
> [new-package] netcdf-fortran 4.6.1

- mingw-w64-nerd-fonts/PKGBUILD
license refresh, source: https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib/fonts.json
> nerd-fonts: update to 3.2.1

- mingw-w64-swig/PKGBUILD
Since swig-4.2.0 has a bug, that [breaks FXRuby](https://github.com/larskanis/fxruby/actions/runs/8629979642/job/23655281538#step:6:55) CI runs.
> swig: Update to 4.2.1

- mingw-w64-PKGBUILD-templates/PKGBUILD.CMake-git.sh
- mingw-w64-PKGBUILD-templates/PKGBUILD.CMake-tarball.sh
- mingw-w64-PKGBUILD-templates/PKGBUILD.meson-tarball.sh
This helps to rule out all the cd commands and jumping between various directories.
> templates: Pass build directory as command line option of build system

- mingw-w64-podman/0001-etc-prefix.patch
- mingw-w64-podman/PKGBUILD
This is not compatible with podman 4, so all machines need to be reset:
With 4.9 (downgrade if needed):
podman machine stop
podman machine rm
With 5.0:
podman machine init
podman machine start
Also see https://blog.podman.io/2024/03/migration-of-podman-4-to-podman-5-machines/
> podman: Update to 5.0.1

- mingw-w64-libminpack/0001-pkgconfig-input-to-cmake.patch
- mingw-w64-libminpack/0002-minpack-c-cpp-header.patch
- mingw-w64-libminpack/0003-cmake-build-script.patch
- mingw-w64-libminpack/PKGBUILD
MINPACK [[1]](https://www.netlib.org/minpack/) [[2]](https://salsa.debian.org/science-team/minpack/-/tree/master?ref_type=heads) [[3]](https://aur.archlinux.org/packages/libminpack) is a battle-tested software written in Fortran 77 for solving a system of nonlinear equations and nonlinear least squares problems. It is widely used in science, and currently employed on SciPy optimization [[4]](https://github.com/scipy/scipy/tree/main/scipy/optimize/minpack).
For mingw32, mingw64 and ucrt64, the build script uses gfortran to perform the build. On clang64 and clangarm64, it uses LLVM flang to build.
I have tested minpack binaries on all mingw archs on my Windows 11 virtual machine even out of msys2 tree, exception goes to clangarm64. Since the toolset is the same used by clang64, I am …
> [new package] Initial libminpack insertion.

- mingw-w64-efxc2/PKGBUILD
This features conversion to C++ Standard 20.
> mingw-w64-efxc2 - update to latest version.

- mingw-w64-texinfo/PKGBUILD
- mingw-w64-texinfo/texinfo-install.hook.in
- mingw-w64-texinfo/texinfo-remove.hook.in
Fixes #631
The hook files are copied from msys2/texinfo directory.
The sed command in package function is copied from mingw glib2 directory.
> texinfo: Add package for info files

- mingw-w64-capstone/PKGBUILD
- mingw-w64-capstone/fix_pkgconf_version_on_cmake.patch
Capstone issue: https://github.com/capstone-engine/capstone/issues/2310
Fixes #20581
I recommend having a look at the Capstone issue first.
Fixes the pkgconfig bogus version, using a workaround until upstream fixes the root issue.
> Capstone: workaround on #20581

- mingw-w64-vtk/008-fix-vtkm_openmp-exported-target.patch
- mingw-w64-vtk/PKGBUILD
I've recently submitted a fix to VTK-m to ensure that exported targets for OpenMP do not point to nonexistent files in the MSYS2 vtk package. These files seem to come from the CI environment used to generate the packages and are mentionned in `/mingw64/lib/cmake/vtk/vtkm/VTKmTargets.cmake`:
```cmake
add_library(vtkm::openmp INTERFACE IMPORTED)
set_target_properties(vtkm::openmp PROPERTIES
INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:-fopenmp>"
INTERFACE_LINK_LIBRARIES "D:/a/msys64/mingw64/lib/libgomp.dll.a;D:/a/msys64/mingw64/lib/libmingwthrd.a;D:/a/msys64/mingw64/lib/libmingwthrd.a"
)
```
We have had build failures for our project due to these hard-coded paths. I've built a new package with the proposed changes and the appropriate target `OpenMP::OpenMP_CXX` is now used instead …
> vtk: fix exported target for `vtkm::openmp` pointing to nonexistent files

- mingw-w64-qt6-base/005-qt-6.7.0-opengl-header.patch
- mingw-w64-qt6-base/PKGBUILD
The Qt6 header `qopengl.h` includes `<GL/gl.h>` while trying to avoid the inclusion of `windows.h`. It does that by defining two preprocessor macros that would normally be defined by including `windows.h` in `<GL/gl.h>`. If these macros are defined, `<GL/gl.h>` does not include `windows.h`. At the end of `qopengl.h`, these preprocessor macros are undefined.
If a project tries to include `<GL/glu.h>` after (indirectly) including `qopengl.h`, the following happens:
* `<GL/glu.h>` includes `<GL/gl.h>` and expects that the necessary preprocessor macros are getting defined by including that header.
*  `<GL/gl.h>` was already included before (in `qopengl.h`) and the inclusion guards lead to `#include <GL/gl.h>` being a no-op at that point.
*  The necessary preprocessor macros are undefined …
> qt6-base: fix inclusion of OpenGL header after Qt6 header

- mingw-w64-swi-prolog/PKGBUILD
now includes the test suite, run with ?- test_installation.
> swi-prolog: update to 9.2.4

- mingw-w64-python-pytest-asyncio/PKGBUILD
- mingw-w64-python-pytest-cov/PKGBUILD
- mingw-w64-python-pytest-enabler/PKGBUILD
- mingw-w64-python-pytest-isort/PKGBUILD
- mingw-w64-python-pytest-mock/PKGBUILD
- mingw-w64-python-pytest-timeout/PKGBUILD
- mingw-w64-python-pytest/PKGBUILD
Also update:
mingw-w64-python-pytest-asyncio 0.23.6
mingw-w64-python-pytest-cov 5.0.0
mingw-w64-python-pytest-enabler 3.1.1
mingw-w64-python-pytest-isort  4.0.0
mingw-w64-python-pytest-mock 3.14.0
mingw-w64-python-pytest-timeout 2.3.1
> python-pytest: update to 8.1.2 and update plugins

- mingw-w64-libvpl/PKGBUILD
* 2.11 moved the tools to another project but we never built them
* 2.11 removed the option to not install examples, so manually delete them
> libvpl: Update to 2.11.0

- mingw-w64-gdk-pixbuf2/0004-build-all-loaders-plus-gdi.patch
- mingw-w64-gdk-pixbuf2/PKGBUILD
* Enable building less supported image formats which was disabled in this version.
See https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/commit/e052a112075a19fb75f1f2ff3de4c82923de13f2
* Import a fix for meson.build file.
See https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/commit/238893d8cd6f9c2616a05ab521a29651a17a38c2
> gdk-pixbuf: update to 2.42.11

- mingw-w64-python-coverage/PKGBUILD
- mingw-w64-python-execnet/PKGBUILD
- mingw-w64-python-pluggy/PKGBUILD
- mingw-w64-python-pytest/PKGBUILD
Also updates:
python-pluggy 1.5.0
python-execnet 2.1.1
python-coverage 7.5.1 (dependency of python-pytest-cov already updated)
> python-pytest: update to 8.2.0 and dependencies

- mingw-w64-libslirp/PKGBUILD
* Drop patch included in the new release
* Now contains symlinks, so do the double extract trick
> libslirp: Update to 4.8.0

- mingw-w64-groonga/PKGBUILD
Groonga version14.0.3 has just released [here](https://github.com/groonga/groonga/releases/tag/v14.0.3).
> groonga: update to 14.0.3

- mingw-w64-notepad++/PKGBUILD
- mingw-w64-notepad++/notepad++
To respect notepad++ settings for locale, it's no longer overridden based on default MSYS2 environment variable LC_CTYPE when started with wrapper script.
> notepad++: Update to 8.6.6

- mingw-w64-efxc2/PKGBUILD
Features new parameter support for /P, /setprivate. More silent unless parameter is added.
> mingw-w64-efxc2 - update to latest release

- mingw-w64-notepad++/PKGBUILD
Release note:
https://notepad-plus-plus.org/news/v867-released/
> notepad++: Update to 8.6.7

- mingw-w64-gcc/3001-fix-ice.patch
- mingw-w64-gcc/PKGBUILD
Patch taken from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115038#c4
Fixes #20879
Fixes #20864
Fixes #20861
> gcc: apply proposed upstream patch for seh_cfa_offset ICE regression

- mingw-w64-starship/PKGBUILD
zlib can't be linked statically nor dynamically as starship also uses `libz-ng-sys`: https://github.com/rust-lang/libz-sys/blob/main/build.rs#L16
> starship: update to 1.19.0

- mingw-w64-meson/PKGBUILD
see https://mesonbuild.com/Feature-autodetection.html#ccache and https://mesonbuild.com/Release-notes-for-0-61-0.html#added-support-for-sccache
> meson: add optdepends on sccache and ccache

- mingw-w64-gnustep-base/PKGBUILD
Adds patch for the merge commit from https://github.com/gnustep/libs-base/pull/405 to msys2 gnustep-base package
cc @qmfrederik
> gnustep-base: patch in some xml fixes from main branch of gnustep-base

- mingw-w64-zed/001-download-pc-windows-gnu-assets.patch
- mingw-w64-zed/002-link-sys-libs-dynamically.patch
- mingw-w64-zed/PKGBUILD
~~currently fails to build. see https://github.com/zed-industries/zed/issues/7847~~
> [new package] zed 0.136.2

- mingw-w64-kicad-doc/PKGBUILD
- mingw-w64-kicad-library/PKGBUILD
- mingw-w64-kicad/PKGBUILD
The newest doc tarball that I could find is for version 8.0.0-rc3.
Does someone know where newer doc tarballs could be found?
Should we remove the doc packages? Users could still find the online documentation.
> kicad: update to 8.0.2

- mingw-w64-curl/PKGBUILD
Enabling nghttp3 requires enabling openssl-quic or ngtcp2. I have enabled openssl-quic following Arch.
openssl-quci requires to use a single ssl backend which requires to disable `schannel` with openssl backend.
> curl: enable http3

- mingw-w64-ossia-score/PKGBUILD
Also this uses more dependencies from the host environment as requested.
> [ossia-score] Update to 3.2.0, reinstate clang arm64

- mingw-w64-emacs/PKGBUILD
This completes the fix for issue #631
> emacs: depend on texinfo for proper info directory update upon install

- .github/workflows/generate-srcinfo.yml
- .github/workflows/main.yml
- mingw-w64-glab/PKGBUILD
For cases where we pass "fetch-depth: 0" to get the full history, enable a treeless clone, since we only care about old commits, and not much more.
This should speed up cloning in theory.
> CI: do a treeless clone in case we need the history

- mingw-w64-gnustep-back/PKGBUILD
- mingw-w64-gnustep-base/PKGBUILD
- mingw-w64-gnustep-gui/PKGBUILD
- mingw-w64-gnustep-make/PKGBUILD
- mingw-w64-libpreferencepanes/PKGBUILD
- gnustep-make: 2.9.1 -> 2.9.2
- gnustep-base: 1.29.0 -> 1.30.0
- gnustep-gui: 0.30.0 -> 0.31.0
- gnustep-back: 0.30.0 -> 0.31.0
> GNUstep: update packages to the latest releases

- mingw-w64-python-xlsxwriter/PKGBUILD
Move it after pkgver is defined to fix it.
The empty version results in pacman failing to install the package since pacman 6.1
Fixes #21045
> python-xlsxwriter: fix undefined version in provides

- mingw-w64-fortran-stdlib/001-using-openblas.patch
- mingw-w64-fortran-stdlib/PKGBUILD
`Fortran-stdlib` comes with modern Reference-BLAS built into v0.6.0, and also provides macro definitions to use external BLAS and LAPACK.
This PR upgrades `Fortran-stdlib` to v0.6.0 and links to OpenBLAS for optimized performance by adding a CMake patch.
> Fortran-stdlib: v0.6.0

- mingw-w64-mesa/PKGBUILD
24.1.0 has many problems:
- [zink](https://gitlab.freedesktop.org/mesa/mesa/-/issues/11220), [llvmpipe and softpipe](https://gitlab.freedesktop.org/mesa/mesa/-/issues/11254) broke on Windows, leaving only dd3d12 OpenGL driver working;
- we can't build with `-Dshared-llvm=enabled` anymore.
> mesa: Update to 24.0.8

- mingw-w64-imagemagick/PKGBUILD
This reverts commit 0dff9a633d6dd0cb9f117fce7c9bde311e9a39c7
This was disabled due to compiler error with clang which was fixed in upstream.
https://github.com/ImageMagick/ImageMagick/commit/2fbf9383c574d08327f7e41db50d613003857604
https://github.com/ImageMagick/ImageMagick/commit/d32677a65e630fa4a36bd1994498234ca280cae2
Fixes #20983
> Revert "imagemagick: Use native Windows thread APIs"

- mingw-w64-groonga/PKGBUILD
Groonga version14.0.4 has just released [here](https://github.com/groonga/groonga/releases/tag/v14.0.4).
> Groonga: Update to 14.0.4

- mingw-w64-curl/0004-more-static-fixes.patch
- mingw-w64-curl/PKGBUILD
This adds the reference in Requires.private when the dependencies are found. Hence, this fixes pkgconfig file in gnutls and winssl versions.
> curl: Fix Requires.private field pkgconfig file

- mingw-w64-curl/0001-Make-cURL-relocatable.patch
- mingw-w64-curl/PKGBUILD
`pathtools.c` contains code that is also present in other static
MSYS2/mingw-w64-built libraries. To allow the linker to de-duplicate
this common object and avoid "multiple definition" linker errors, the
object must be kept separate from the rest of the library, that is
compiled into a single, "unity" object after
ee2184d939d4a99ab017b0f61222b0555d6b1467 #21021.
Ref: #21028
> curl: exclude pathtools.c from unity mode

- mingw-w64-rust/PKGBUILD
it's not required for a compiler, but for rust-analyzer. the same thing is already implemented in arch
> rust: add split package for source code

- mingw-w64-llama.cpp/PKGBUILD
```
$ llama.cpp -m /d/Temp/llama2.8_0.gguf -n 128 -e -p "What is the MSYS2 project?"
Log start
main: build = 3091 (2b3389677)
main: built with gcc.exe (Rev3, Built by MSYS2 project) 14.1.0 for x86_64-w64-mingw32
main: seed  = 1717953103
llama_model_loader: loaded meta data with 23 key-value pairs and 291 tensors from D:/Temp/llama2.8_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
llama_model_loader: - kv   3: …
```
> llama.cpp: Update to b3091

- mingw-w64-zydis/PKGBUILD
looks like it was triggered with zycore-c<=1.4.1
> zydis: remove -Wno-int-conversion

- mingw-w64-cmake/PKGBUILD
This fixes the following error with bash completion.
-bash: _split_longopt: command not found
> cmake: adapt to _split_longopt rename in bash-completion

- mingw-w64-python-ruamel.yaml.clib/PKGBUILD
> python-ruamel.yaml.clib: rebuild; fix build with gcc 14

- mingw-w64-kdenlive/PKGBUILD
dbus is already disabled with -DNODBUS=ON option and not required in Windows.
> kdenlive: Add kcolorscheme and remove kdbusaddons dependency

- mingw-w64-zed/PKGBUILD
- move _env into a build()
- ~at first try to remove workaround for gcc14~ didn't work
- add ZED_UPDATE_EXPLANATION (from Arch)
> zed: disable auto update

- mingw-w64-icu/PKGBUILD
icu is built without gnu extensions but in various places undefs `__STRICT_ANSI__` which enables code in the libstdc++ that depends on gnu extensions.
We worked around this by enabling the specific extensions this required but this upstream patch is better, to not touch `__STRICT_ANSI__` in the first place:
https://github.com/unicode-org/icu/pull/3003
> icu: backport build fix (remove need for -fext-numeric-literals)

- mingw-w64-zed/PKGBUILD
~[test] use mold as linker~ `mold: fatal: unknown -m argument: i386pep`
> zed: update to 0.140.5

- mingw-w64-ossia-score/PKGBUILD
full changelog: https://github.com/ossia/score/compare/v3.2.0...v3.2.1. looks like there is no other changes required
@jcelerier
> ossia-score: update to 3.2.1

- mingw-w64-lua-cjson/PKGBUILD
[Lua CJSON](https://github.com/openresty/lua-cjson) is a fast JSON encoding/parsing module for Lua (5.1+). Nowadays, **lua-cjson** is the most downloaded (+19M) Lua package on [LuaRocks](https://luarocks.org/) (the main package manager for Lua).
In the PKGBUILD script provided here, it is building lua-cjson for every mingw_arch, and every Lua version available here (current 5.4, 5.3 and 5.1).
* Current Lua (5.4): mingw-w64-*-lua-cjson
* Lua 5.1: mingw-w64-*-lua51-cjson
* Lua 5.3: mingw-w64-*-lua53-cjson
> [!NOTE]
> 
> If needed, I can place all these ```sed``` lines inside the ```prepare()``` function into patch files to make things more readable.
> [new-package] lua-cjson

- mingw-w64-ffmpeg4.4/PKGBUILD
It no longer builds and needs backports that no longer cleanly apply. While it's probably possibel to fix this there are not many 4.4 users left, so just disable that feature.
> ffmpeg4.4: disable nvenc

- mingw-w64-svt-av1/PKGBUILD
Note: decoder parts removed upstream, but doesn't seem anyone was linking to those.
> svt-av1: update to 2.1.1

- mingw-w64-cargo-c/001-add-lib-prefix-on-windows-gnu.patch
- mingw-w64-cargo-c/PKGBUILD
cargo-c can't use libgit2>=1.8.1 at the moment, let it use vendored library; switch to release-strip profile
> cargo-c: update to 0.10.1

- mingw-w64-harfbuzz/001-fix-build-with-chafa.patch
- mingw-w64-harfbuzz/PKGBUILD
- Split package the same as Arch  (utils, icu and cairo)
- Enable chafa support (on non i686)
> harfbuzz: update to 9.0.0

- mingw-w64-inkscape/007-no-console-clang.patch
- mingw-w64-inkscape/PKGBUILD
Interesting case. MinGW builds are defaulting to windows subsystem (i.e. UCRT64), but CLANG64 and CLANGARM64 are not, so explicitly set the flag.
> inkscape: Explicitly link as 'windows' subsystem

- mingw-w64-evince/0010-no-console.patch
- mingw-w64-evince/PKGBUILD
> evince: Set subsystem to 'windows'

- mingw-w64-mpv/PKGBUILD
- mingw-w64-mujs/PKGBUILD
- mingw-w64-vapoursynth/PKGBUILD
> mpv,mujs,vapoursynth: Enable aarch64 builds

- mingw-w64-texlive-bin/0005-untighten_version_check_zlib.patch
- mingw-w64-texlive-bin/0006-workaround-pathconf.patch
- mingw-w64-texlive-bin/0007-stat.patch
- mingw-w64-texlive-bin/PKGBUILD
This is an attempt to fix some build errors of the texlive-bin package. It is based on the changes from #19921.
It works around the issue with the conversion of path lists (https://github.com/msys2/msys2-runtime/issues/208) by manually converting the respective paths from relative to absolute using `cygpath`.
It also cherry-picks some fixes from upstream and uses the `-Wno-error=incompatible-pointer-types` work-around to avoid some build errors with GCC 14.
It still fails with errors (in an ICU header iiuc). Maybe, someone has hints how to fix that or would like to continue from here.
It fails with errors like the following for me locally:
```
In file included from C:/msys64/mingw64/include/unicode/ubidi.h:26,
from ../../../texk/web2c/xetexdir/XeTeXLayoutInterface.cpp:37: …
```
> texlive-bin: Rebuild with current runtime and compiler

- mingw-w64-libspelling/PKGBUILD
A GNOME library for spellchecking
This is the official gtk4 successor of `gtkspell` (gtk+2) and `gspell` (gtk+3).
Fixes #21294
> [new package] libspelling

- mingw-w64-libheif/PKGBUILD
Also, the `WITH_OPENJPH_DECODER` option is currently unused/not implemented.
> libheif: add upstream TIFF decoder patch

- mingw-w64-llvm-15/PKGBUILD
We need it at https://github.com/m-labs/artiq . 
Previously, llvmlite was depending on LLVM 14, which had these targets. Now it retargeted to newer LLVM, which broke both our platforms.
> llvm-15: Add ARM and RISCV targets

- mingw-w64-qt5-static/0009-add-missing-metatypes-configs.patch
- mingw-w64-qt5-static/0010-qmltyperegistrar-search-in-correct-directory.patch
- mingw-w64-qt5-static/0012-mingw-add-extra-flags.patch
- mingw-w64-qt5-static/0013-qtbase-use-system-libs.patch
- mingw-w64-qt5-static/0014-qtimageformats-use-system-libs.patch
- mingw-w64-qt5-static/0035-qt-5.3.2-dont-add-resource-files-to-qmake-libs.patch
- mingw-w64-qt5-static/0401-disable-warning-of-non-existent-files.patch
- mingw-w64-qt5-static/0402-deprecated-ucrt-functions.patch
- mingw-w64-qt5-static/0403-qtactiveqt-tools-avoid-race-condition.patch
- mingw-w64-qt5-static/0411-javascriptcore-disable-deprecated-warnings.patch
- mingw-w64-qt5-static/0412-jitstubs-underscore-symbol-name-for-x86.patch
- mingw-w64-qt5-static/PKGBUILD
- simplified PKGBUILD recipe
- build in silent mode
- make sure we link with static zlib and zstd
- fix qmltyperegistrar 'Cannot open foreign types file' error
- fix race condition when building qtactiveqt tools
- fix *.pc & *.prl files further by removing full path to libs
Fixes #21379
> qt5-static: update to 5.15.14

- mingw-w64-python-coverage/PKGBUILD
This updates Coverage.py to v7.6.0.
> python-coverage: update to 7.6.0

- mingw-w64-python-pyarrow/0001-arrow-setup-fix-cmake-generator.patch
- mingw-w64-python-pyarrow/PKGBUILD
> python-pyarrow: Add package

- mingw-w64-python-installer/004-zero-reservered-fields-in-startupinfo.patch
- mingw-w64-python-installer/PKGBUILD
simple_launcher currently copies the values of lpReserved2 and cbReserved2 from the parent process to the child. In some cases, these fields are used to pass information. For example, the MSVC C runtime uses the fields as part of its _spawn implementation to pass file descriptor information to the child. However, this information is invalid in the grand-child proces.
This issue is a cause of a bug when CMake attempts to launch a python-installer child process:
* https://gitlab.kitware.com/cmake/cmake/-/issues/25996
This patch corrects the issue by applying a patch to zero the fields.
> python-installer: Zero lpReserved2 and cbReserved2 fields in simple_launcher STARTUPINFOW

- mingw-w64-perl-encode-compat/PKGBUILD
- mingw-w64-perl-file-which/PKGBUILD
- mingw-w64-perl-html-tagset/PKGBUILD
- mingw-w64-perl-io-string/PKGBUILD
- mingw-w64-perl-win32-tieregistry/PKGBUILD
Each of these modules uses `mingw32-make` without declaring it as a build-time dependency. As a result, these packages have failed to rebuild and are stuck at the Perl 4.32.1 build. This patch-set corrects the issue by adding `${MINGW_PACKAGE_PREFIX}-make` to the `makedepends` and bumping the `pkgrel`.
> Fix perl module makedepends

- mingw-w64-python-pyvisa/PKGBUILD
Added `python-pyvisa` package.
Full build log [here](https://gist.github.com/fsagbuya/ae5d20e1819b5a6095b2216695bf1865).
```
$ python
Python 3.11.9 (main, Apr 12 2024, 09:55:30)  [GCC Clang 18.1.3 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvisa
>>> print(pyvisa.__version__)
1.14.1
```
> python-pyvisa: new package

- mingw-w64-python-pygments-docs/PKGBUILD
- mingw-w64-python-pygments/PKGBUILD
This helps to break the cyclic dependency between python-pygments and python-sphinx. The similar change was done with python-jinja.
> python-pygments: Split docs into separate package

- mingw-w64-qt5-base/PKGBUILD
Changing to -opengl dynamic will enable fallback code for loading ANGLE (libEGL.dll and libGLESv2.dll from package mingw-*-angleproject) as well as software rasterizers (opengl32sw.dll) at runtime. Currently -opengl desktop will only work with full-fledged OpenGL 2.x+ implementation, that is: Qt Quick 2 will not work in VMs or systems without 3D acceleration.
> qt5-base: Change OpenGL to "dynamic" mode to support fallbacks

- mingw-w64-cppdap/PKGBUILD
* Updates cppdap to [ver 1.65 ](https://github.com/google/cppdap/commit/37c744c294cbb24943a3913bbb67860d1609008c)
* Switch to git commit source since the project does not generate github release archives
> cppdap: update to 1.65

- mingw-w64-turbo/PKGBUILD
- mingw-w64-turbo/turbo-enable-lazy_cell.patch
- mingw-w64-turbo/zstd-sys-remove-statik.patch
`RUSTC_BOOTSTRAP=1` allows stable compiler to use nightly features
> [new package] turbo 2.0.9

- mingw-w64-python-pysfcgal/PKGBUILD
- mingw-w64-sfcgal/PKGBUILD
SFCGAL and PySFCGAL 1.5.2:
- https://gitlab.com/sfcgal/SFCGAL/-/releases/v1.5.2
- https://gitlab.com/sfcgal/PySFCGAL/-/releases/v1.5.2
> SFCGAL: Bump to 1.5.2

- mingw-w64-gxml/PKGBUILD
switch to using gitlab archive since the newer tarballs are missing
> gxml: Update to 0.20.4

- mingw-w64-PKGBUILD-templates/PKGBUILD.CMake-git.sh
- mingw-w64-PKGBUILD-templates/PKGBUILD.CMake-tarball.sh
- mingw-w64-PKGBUILD-templates/PKGBUILD.python.sh
There is really no need to, we can depend on PATH there
> PKGBUILD-templates: get rid of $MINGW_PREFIX/bin

- mingw-w64-libuhd/PKGBUILD
@chrisjohgorman I tried this and it worked _locally_
I think that `-DUHD_PYTHON_DIR` can be removed at all
> libuhd: fix python library install path

- mingw-w64-libuhd/0001-libraries_headers_and_pthread_setname_np_cast.patch
- mingw-w64-libuhd/PKGBUILD
- There was a small section of code commented out because I couldn't get it to build. A simple cast fixes this. Now we can use pthread_setname_np to set thread names.
- Use cygpath.exe to set a proper path for the _DEFAULT_INSTALL_PATH for uhd_images_downloader
- Move uhd_images_downlader.py and usrp2_card_burner.py to ${MINGW_PREFIX}/bin and change their names to uhd_images_downloader and usrp_card_burner respectively. The reflects the contents of /usr/bin in the arch package.
> libuhd: bugfixes

- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/config.toml
all previous configs should be the same as before, but:
- ~linked against shared llvm~ not supported
- remove rust-analyzer component (it will be added as separate package)
- add some extra options (copied from Arch)
- comment wasm-related configs (@ArchGuyWu you need to also append wasm targets to build.targets field)
edit: 
- ~add gettext-tools to makedepends for docs~ didn't fix anything
> rust: use hand-written config.toml

- mingw-w64-gnuradio/PKGBUILD
- mingw-w64-gnuradio/numpy-2.0.patch
- bump pkgrel
- remove makedepends on `gtk3` and `python-gobject` that were added to depends by https://github.com/msys2/MINGW-packages/pull/21553
- enable check to run test suite.  one case, `qa_throttle`, fails.
- add numpy-2.0.patch from arch to fix test case `qa_correlate_access_code`
- used `namcap` and `ntldd.exe` fix dependencies
- moved packages from makedepends to depends as they were determined to be dependencies
- removed dependencies that were installed as a dependency of another package eg. `libiio` is a dependency of `libad9361-iio`, `python-cairo` is a dependency of `python-gobject` and `fmt` is a dependency of `spdlog`.
- added packages that were python dependencies determined by `namcap`, `python-lxml`, `pyqtgraph` and `python-pyqt5`
- added dependency to …
> gnuradio: fixup dependencies

- mingw-w64-python-dulwich/PKGBUILD
Apparently this corrupts the exe.
Fixes #21582
> python-dulwich: don't sed exes

- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/config.toml
it takes too much memory to do that
> rust: don't generate debuginfo on i686

- mingw-w64-c-ares/PKGBUILD
c-ares is currently listed as 1.29.0 in MSYS2, this PR should update it to the current release of 1.33.0 which has many Windows-specific fixes.
Fixes #21585
> c-ares: update to 1.33.0

- mingw-w64-rust/0004-compiler-Use-wasm-ld-for-wasm-targets.patch
- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/config.toml
- mingw-w64-wasi-libc/PKGBUILD
- mingw-w64-wasm-component-ld/PKGBUILD
WebAssembly targets for Rust
WebAssembly (Wasm) defines a portable binary-code format and a corresponding text format for executable programs as well as software interfaces for facilitating interactions between such programs and their host environment. 
With this we're able to build one executable and run it anywhere, without the need to target for a specific platform.
[rust support for wasm](https://www.rust-lang.org/what/wasm)
> [new-package] rust-wasm

- mingw-w64-tme/PKGBUILD
Fix for module library directory search paths. Adjusted timer interrupts to get sun2 emulation working correctly. Improved mouse handling for relative modes like in SDL2. Other minor fixes and compilation improvements.
> tme: Update to 0.12rc13

- mingw-w64-virglrenderer/PKGBUILD
See https://gitlab.com/qemu-project/qemu/-/issues/2490 for the problem.
This commit adds a patch merged to virglrenderer to solve this problem.
> virglrenderer: Fix QEMU crash if D3D feature isn't enabled

- mingw-w64-rust/0008-disable-self-contained.patch
- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/config.toml
- add debuginfo only if `debug` option is set (see https://github.com/msys2/MINGW-packages/pull/21581#issuecomment-2276354980)
- add missing wasm32-unknown-unknown target
- remove self-contained directory for all targets
- `rust`: remove license installation as `rustdoc` is now a part of main package (it installs license files in doc directory)
- `rust-wasm`: don't strip binaries, add missing `wasi-libc` dependency
- enable frame-pointers ~and CFG (addresses #16833)~ in config.toml
> rust: update to 1.80.1

- mingw-w64-ossia-score/PKGBUILD
to avoid it git cloning some missing optional dependencies, which then fail to build.
> ossia-score: disable fetchcontent

- mingw-w64-rust-analyzer/PKGBUILD
~and add it as optional dependency for helix~ reverted, helix fails to build now
> rust-analyzer: update to 20240812

- mingw-w64-codeblocks/PKGBUILD
Stop building Valgrind plugin because Valgrind does not exist for Windows. 
Add optdepends on ${MINGW_PACKAGE_PREFIX}-clang-tools-extra.
> mingw-w64-codeblocks: Update _revision to 13539

- mingw-w64-rufus/PKGBUILD
UCRT64 fails with
```
In file included from C:/_/B/src/rufus-4.5/src/libcdio/iso9660/iso9660_fs.c:28:
C:/_/B/src/rufus-4.5/src/libcdio/config.h:43:18: error: static declaration of '_fseeki64' follows non-static declaration
43 | #define fseeko64 _fseeki64
|                  ^~~~~~~~~
In file included from C:/_/B/src/rufus-4.5/src/libcdio/iso9660/iso9660_fs.c:37:
D:/M/msys64/ucrt64/include/stdio.h:650:23: note: previous declaration of '_fseeki64' with type 'int(FILE *, long long int,  int)' {aka 'int(struct _iobuf *, long long int,  int)'}
650 |   _CRTIMP int __cdecl _fseeki64(FILE *_File,__int64 _Offset,int _Origin);
|                       ^~~~~~~~~
In file included from C:/_/B/src/rufus-4.5/src/libcdio/iso9660/iso9660_private.h:29,
from …
```
> [new package] rufus 4.5

- mingw-w64-neovim/0001-cmake-disable-bundling.patch
- mingw-w64-neovim/PKGBUILD
This PR updates neovim from 0.9.5 to 0.10.1 and fixes an issue during the compilation process while linking against `lpeg.dll` which is not easily possible. To circumvent the problem, neovim is patched to load the dll through Lua's `dlopen` mechanism instead. See #21313 for more details.
> neovim: update to 0.10.1

- mingw-w64-meson/PKGBUILD
- mingw-w64-python-certifi/PKGBUILD
- mingw-w64-python-werkzeug/PKGBUILD
- mingw-w64-python-yaml/PKGBUILD
- mingw-w64-python-zstandard/PKGBUILD
it should not longer be needed with newer setuptools
> Rebuild some packages without python-wheel

- mingw-w64-rust-analyzer/PKGBUILD
`CFG_RELEASE` sets a version of binary, so use custom version string
> rust-analyzer: update to 20240819

- mingw-w64-zed/PKGBUILD
upstream silently pushed v0.149.3 tag, while only pre-release is avialable in upstream releases
> zed: update to 0.149.3

- mingw-w64-wasm-bindgen/Cargo.lock
- mingw-w64-wasm-bindgen/PKGBUILD
link upstream issue re missing lock file
because github complains that it contains outdated dependencies, but the relevant packages can't be updated, so this wont help.
But update anyway while I'm already at it.
> wasm-bindgen: update lock file

- mingw-w64-swi-prolog/PKGBUILD
fixed sub-package description for *-archive
added missing dependency
added support for python binding
> SWI-Prolog 9.2.6: fixed dependencies

- mingw-w64-verilator/0001-Use-msys2-perl-since-it-doesn-t-work-with-windows-pe.patch
- mingw-w64-verilator/PKGBUILD
using msys2 perl instead of mingw perl, becuase otherwise verilator doesn't work? should fix #21706
> verilator: Fix msys2 perl bug

- mingw-w64-lldb/PKGBUILD
I am using `lldb-dap` in VSCode for debugging with the help of https://github.com/llvm/vscode-lldb. I noticed that `StackTrace` request was extremely slow. In my tests it takes 10s and makes debugging almost impossible. Luckily someone has fixed it in llvm https://github.com/llvm/llvm-project/pull/104874. This is a backport. Now `StackTrace` is instant.
> lldb-dap: fix extremely slow backtrace request

- mingw-w64-android-tools/0001-android-tools-cmake.patch
- mingw-w64-android-tools/0002-android-tools-vendor.patch
- mingw-w64-android-tools/PKGBUILD
vendor/boringssl/crypto/curve25519/internal.h hunk was added in upstream. https://boringssl.googlesource.com/boringssl.git/+/80b08dfe5ef7d9190fa28d8204f2f7e8612134ee%5E%21/
use bundled libusb as explained in release page.
> android-tools: update to 35.0.2

- mingw-w64-libc++/PKGBUILD
CMake doesn't react to the global env variable CPPFLAGS; feed the contents of it to CMake via CXXFLAGS.
This makes sure that libc++ is built with -D__USE_MINGW_ANSI_STDIO=1, which fixes the formatting output of long doubles on x86.
This should fix issues #21768 and #17795.
> libc++: Pass global CPPFLAGS to CMake via CXXFLAGS

- mingw-w64-gdk-pixbuf2/PKGBUILD
* libwmf: Load .wmf and .apm
* libavif: Load .avif
* libheif: Load .heif, .heic, and .avif
* libjxl: Load .jxl
* librsvg: Load .svg, .svgz, and .svg.gz
* webp-pixbuf-loader: Load .webp
> gdk-pixbuf2: update optdepends

- mingw-w64-json-glib/PKGBUILD
* docutils is used for generating man pages now
* enable auto features and disable the ones we don't need
* disable installed tests instead of deleting them afterwards
> json-glib: Update to 1.10.0

- mingw-w64-msmpi/PKGBUILD
- mingw-w64-msmpi/mpi.f90
The declaration of the subroutines are gathered from different locations in MPICH, slightly adapted where needed, and checked against the symbols that are exported by MSMPI.dll version 10.1.12498.52.
This allows for better compiler diagnostics when these subroutines are used in downstream sources. And it reduces the number of (bogus) warnings about supposedly mismatched types for subroutines that can be called with any type for some arguments.
> msmpi: Add more subroutines to the MPI_BASE Fortran module.

- mingw-w64-grpc/PKGBUILD
- mingw-w64-openldap/PKGBUILD
- mingw-w64-rufus/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
See https://github.com/msys2/MSYS2-packages/issues/4860 It was moved from CPPFLAGS to CFLAGS/CXXFLAGS.
> Adjust PKGBUILDs for CPPFLAGS removal from makepkg

- mingw-w64-codeblocks/005-codeblocks-plugin-fix.patch
- mingw-w64-codeblocks/PKGBUILD
The patch removes an invalid message when installing an cbplugin file.
Tim S.
> codeblocks: Update and apply patch to fix run-time issue

- mingw-w64-msmpi/PKGBUILD
- mingw-w64-msmpi/mpi.f90
`TYPE(*), DIMENSION(..)` is a Fortran 2008 idiom. Using it in the MPI module causes issues downstream in Fortran 90 projects.
See, e.g.: https://github.com/ElmerCSC/elmerfem/pull/559
Use an extension of gfortran to mark polymorphic types in a way that is compatible with Fortran 90.
Flang doesn't support polymorphic types at all currently. It fails when trying to use them with an error like the following:
```
error: loc("C:/msys64/home/Markus/test_ignore_flang.f90":43:3): C:/M/B/src/flang-18.1.8.src/lib/Lower/CallInterface.cpp:949: not yet implemented: support for polymorphic types
LLVM ERROR: aborting
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: C:/msys64/clang64/bin/flang -fc1 -triple …
```
> msmpi: Avoid Fortran 2008 idioms in Fortran 90 module

- mingw-w64-openssl/PKGBUILD
new domain and new signing key (see https://openssl-library.org/source/index.html)
> openssl: Update to 3.3.2

- mingw-w64-libavif/PKGBUILD
Has no affect on current package (these targets get overwritten by shared versions anyway), so no release bump.
Only affects future build times.
> libavif: slim down static builds

- mingw-w64-rust/0008-disable-self-contained-for-gnu-targets.patch
- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/config.toml
- mingw-w64-rust/fix-bootstrap-on-windows.patch
- disable self-contained for \*-windows-gnu\* targets only
- fix license installation for rust-wasm and rust-src packages
> rust: update to 1.81.0

- mingw-w64-rpi-imager/0001-rpi-imager-cmake-disable-bundled-dependencies.patch
- mingw-w64-rpi-imager/0002-rpi-imager-include-missing-header.patch
- mingw-w64-rpi-imager/PKGBUILD
I have used the package with Raspberry Pi 4B to write bootloader and Raspberry Pi OS.
<details><summary>Click here to see the screenshot of rpi-imager</summary>
</summary>
> rpi-imager: add package

- mingw-w64-abseil-cpp/0004-abseil-workaround-disable-local-time-zone.patch
- mingw-w64-abseil-cpp/PKGBUILD
This fixes the following compiler error.
time_zone_lookup.cc:102:14: error: use of undeclared identifier 'RuntimeClass_Windows_Globalization_Calendar'
> abseil-cpp: Workaround compiler error due to absence of ICalendar definition

- mingw-w64-qemu/PKGBUILD
- mingw-w64-qemu/msys2.examples.tests.sh
see https://wiki.qemu.org/ChangeLog/9.1
> qemu: update to 9.1.0

- mingw-w64-fastfetch/PKGBUILD
New deps `imagemagick` and `chafa` added for image logo printing.
https://github.com/fastfetch-cli/fastfetch/releases/tag/2.24.0
> fastfetch: update to 2.24.0

- mingw-w64-curl/0001-Make-cURL-relocatable.patch
- mingw-w64-curl/0004-more-static-fixes.patch
- mingw-w64-curl/PKGBUILD
* 0001-Make-cURL-relocatable.patch: refresh
* 0004-more-static-fixes.patch: fixed upstream
* FindNettle.cmake: fixed upstream
* Removal of CURL_USE_SCHANNEL for gnutls, this errors out now as not supported. I don't know if that just worked by accident before, or just the error was missing before. Either way, upstream doesn't support multiple backends with http3.
> curl: Update to 8.10.0

- mingw-w64-arpack/PKGBUILD
Package files for PARPACK in a split package to keep the dependency on MSMPI separate.
> arpack: package PARPACK

- mingw-w64-virglrenderer/PKGBUILD
No patching or CFLAGS required for MINGW64/UCRT64.
Only minimal patches for CLANG64.
For CLANG64 the same issues as documented in QEMU PR https://github.com/msys2/MINGW-packages/pull/21540 occur as they did in previous builds.
```
[32/47] Compiling C object src/libvirgl.a.p/vrend_blitter.c.obj
../virglrenderer-1.1.0/src/vrend_blitter.c:94:8: warning: unknown attribute 'gcc_struct' ignored [-Wunknown-attributes]
94 | struct PACKED blit_prog_key {
|        ^~~~~~
../virglrenderer-1.1.0/src/mesa/util/macros.h:207:35: note: expanded from macro 'PACKED'
207 | #    define PACKED __attribute__((gcc_struct,__packed__))
|                                   ^~~~~~~~~~
1 warning generated.
```
If QEMU is the only package requiring virglrenderer, maybe we should drop CLANG-builds for virglrenderer as …
> virglrenderer: Update to 1.1.0

- mingw-w64-PKGBUILD-templates/PKGBUILD.CMake-git.sh
- mingw-w64-PKGBUILD-templates/PKGBUILD.CMake-tarball.sh
- mingw-w64-PKGBUILD-templates/PKGBUILD.autotools-tarball.sh
- mingw-w64-PKGBUILD-templates/PKGBUILD.cargo-tarball.sh
- mingw-w64-PKGBUILD-templates/PKGBUILD.meson-tarball.sh
- mingw-w64-PKGBUILD-templates/PKGBUILD.python.sh
every functions start at `${srcdir}`. it's not required to pass full paths to `cd`
> templates: remove some `${srcdir}` references

- mingw-w64-gnustep-xctest/PKGBUILD
This is a test framework for Objective C applications, which attempts to be compatible with Apple's xctest.
> [new package] gnustep-xctest

- mingw-w64-helix/PKGBUILD
- mingw-w64-helix/disable-lto.patch
- mingw-w64-helix/icon.patch
icon.patch: use windres to add icon when target_env is gnu
disable-lto.patch: PKGBUILD failed at cargo test --locked --release, alternatively test without --release can work too
This is my first time to create a pull request, sorry in advanced if I cause any problems.
> helix: update to 24.07

- mingw-w64-cmake-bootstrap/0003-fix-find-python-on-mingw-aarch64.patch
- mingw-w64-cmake-bootstrap/0005-Default-to-ninja-generator.patch
- mingw-w64-cmake-bootstrap/PKGBUILD
- mingw-w64-cmake/PKGBUILD
A cmake variant that doesn't depend on any external dependencies and can be used for bootstrapping an env, and building a full cmake.
> Add cmake-bootstrap

- mingw-w64-gtk4/002-fix-memory-leak.patch
- mingw-w64-gtk4/PKGBUILD
https://gitlab.gnome.org/GNOME/gtk/-/issues/7013#note_2227756
> gtk4: backport memory leak fix

- mingw-w64-kdeconnect/0004-kdeconnect-cmake-disable-checking-winsdk.patch
- mingw-w64-kdeconnect/PKGBUILD
This should fix the following cmake error which happend in clangarm64.
CMake Error at CMakeLists.txt:104 (file):
file failed to open for reading (No such file or directory):
/registry/SDKManifest.xml
> kdeconnect: Fix building in absence of Windows SDK

- mingw-w64-rust/PKGBUILD
Prerequisite to disable bootstrap for CLANG envs: #219002
> rust: add gnullvm target for CLANG{32,64} envs

- mingw-w64-kicad-doc/PKGBUILD
- mingw-w64-kicad-library/PKGBUILD
- mingw-w64-kicad/007-Fix-compilation-with-Boost-1.86.patch
- mingw-w64-kicad/008-KIID-Use-Boost-uuids-own-hash-function-fix-Boost-1.8.patch
- mingw-w64-kicad/009-Fix-Boost-1.86-SHA1-one-last-time.patch
- mingw-w64-kicad/PKGBUILD
Had to add three patch files from 8.0 git branch because of boost library upgrade issues.
> Kicad update to version 8.0.5

- mingw-w64-gtk4/PKGBUILD
seems to work fine here, though not used by default on my machine and GSK_RENDERER=vulkan is needed
> gtk4: enable vulkan support

- mingw-w64-rust/0013-generate-import-libraries-on-gnullvm.patch
- mingw-w64-rust/PKGBUILD
backport of https://github.com/rust-lang/cargo/pull/14451
required for #22101
> rust: fix import library generating for gnullvm targets

- mingw-w64-wasmtime/.gitignore
- mingw-w64-wasmtime/PKGBUILD
- mingw-w64-wasmtime/zstd-sys-remove-statik.patch
`libwasmtime` is used in tree-sitter for wasm support
> [new package] wasmtime 25.0.1

- mingw-w64-wasmtime/PKGBUILD
Fix error when install both wasmtime and libwasmtime:
```
error: failed to commit transaction (conflicting files)
/ucrt64/share/licenses/wasmtime/LICENSE exists in both 'mingw-w64-ucrt-x86_64-wasmtime' and 'mingw-64-ucrt-x86_64-libwasmtime'
```
> libwasmtime: fix LICENSE file destination

- mingw-w64-qt5-speech/PKGBUILD
- mingw-w64-qt5-winextras/PKGBUILD
Following a discussion on Discord, see:
https://www.discord.com/channels/792780131906617355/794220101741838401/1283064557660803083 brought about by https://github.com/msys2/MINGW-packages/commit/a4f0579e14509d27927a94498c35e1ccddf29bf5 I suggested to restore for a while a couple of Qt5 packages that the [Mudlet](https://github.com/Mudlet/Mudlet) project I code for uses for its 32-Bit Windows builds until we have migrated as many of our Windows users up to 64-Bit builds as possible.
I was hoping that one of the MSYS2+Mingw-w64 team would have been able to find the time to make this change but after a couple of weeks of nothing happening I have decided to try and do it myself.
> qt5: restore some MINGW32 packages

- mingw-w64-gnucobol/PKGBUILD
json-c is the dependency most used with other package managers - and it is still available for mingw32
additional:
* fixed license from LGPL-3.0-only to LGPL-3.0-or-later
* use internet archive for static download (test dependency) that has gone offline
Note: pulling this may be postponed if the package is to be made available for MINGW32 (see #22133) which could be integrated into this PR (or be made available before/later separately, especially if it doesn't need an update to pkgrel).
> gnucobol: switch json dependency

- mingw-w64-cmake/PKGBUILD
cmake-bootstrap is now used for such purpose, so no need to keep "dead code" in general cmake package
> cmake: remove _bootstrap

- mingw-w64-slim-simulator/PKGBUILD
Updating to latest version. q5 dependency changed to qt6 in new version.
> slim-simulator: update to version 4.3

- mingw-w64-libjpeg-turbo/PKGBUILD
I was compiling the list of licenses I'm using for a project I'm working on and found that the license file was missing from the libjpeg-turbo package. This PR adds it in.
> libjpeg-turbo: Include LICENSE.md in package

- mingw-w64-helix/PKGBUILD
- mingw-w64-kate/PKGBUILD
helix: add some LSPs available from repo (can be found with `hx --health`)
kate: change rust to rust-analyzer
> kate, helix: change optdepends for LSPs

- mingw-w64-pyinstaller-hooks-contrib/PKGBUILD
- mingw-w64-pyinstaller/PKGBUILD
Windows Security treat `PyInstaller/bootloader/Windows-32bit-intel/*.exe` files as `Trojan:Win32/Wacatac.B!ml` for me.
But for bootloaders from `6.10.0` version all good.
Can anybody check or confirm this?
> pyinstaller: update to 6.11.0

- mingw-w64-python-jupyter_console/PKGBUILD
This fixes the following runtime error.
$ jupyter-console.exe
Fatal error in launcher: Unable to find an appended archive.
Fixes #22214
> python-jupyter_console: Do not strip launcher executable

- mingw-w64-gnustep-gui/PKGBUILD
This MR adds 2 patches to GNUstep GUI that fixes various problems with NSMenu items. Patching until the community is ready for an official release.
> gnustep-gui: Add NSMenu patch fixes

- mingw-w64-librsvg/0006-fix-query-with-rust-1-82.patch
- mingw-w64-librsvg/PKGBUILD
rust 1.82.0 doesn't like the target temp file being open while writing to it
> librsvg: rebuild and fix build with newer rust

- mingw-w64-dav1d/PKGBUILD
> WARNING: we removed some of the SSE2 optimizations, so if you care about systems without SSSE3, you should be careful when updating!
There is however runtime CPU detection, so this should affect only a (small?) portion of users w/ very old CPUs...
> dav1d: update to 1.5.0

- mingw-w64-nanobind/PKGBUILD
robin_map module is already included in nanobind tarball from pypi.
> nanobind: Remove redundant robin_map submodule download

- mingw-w64-python-aioquic/PKGBUILD
- mingw-w64-python-service-identity/PKGBUILD
Add [`python-aioquic`](https://github.com/aiortc/aioquic) so we can add support for the [QUIC transport](https://github.com/Xpra-org/xpra/blob/master/docs/Network/QUIC.md) in [`xpra`](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python-xpra/PKGBUILD). (this optional dependency will be submitted later as a separate PR)
This PR depends on `python-pylsqpack`: https://github.com/msys2/MINGW-packages/pull/22255
> add python-aioquic

- mingw-w64-petsc/PKGBUILD
- mingw-w64-slepc/PKGBUILD
Building SLEPc requires making the PETSc build package more relocatable.
> slepc: update to 3.22.0

- mingw-w64-qt6-3d/PKGBUILD
- mingw-w64-qt6-5compat/PKGBUILD
- mingw-w64-qt6-activeqt/PKGBUILD
- mingw-w64-qt6-base/001-appending-qt6-to-remove-qt5-conflict.patch
- mingw-w64-qt6-base/PKGBUILD
- mingw-w64-qt6-charts/PKGBUILD
- mingw-w64-qt6-connectivity/PKGBUILD
- mingw-w64-qt6-datavis3d/PKGBUILD
- mingw-w64-qt6-declarative/PKGBUILD
- mingw-w64-qt6-languageserver/PKGBUILD
- mingw-w64-qt6-multimedia/PKGBUILD
- mingw-w64-qt6-quick3d/PKGBUILD
- mingw-w64-qt6-quicktimeline/PKGBUILD
- mingw-w64-qt6-shadertools/PKGBUILD
- mingw-w64-qt6-svg/PKGBUILD
- mingw-w64-qt6-tools/PKGBUILD
- mingw-w64-qt6-translations/PKGBUILD
* Rebase qt6-base patches.
* Import a patch to fix qt6-base compilation.
* Remove debug package for qt6-languageserver because it now builds static library only without debug files.
Fixes #22267
> qt6: update to 6.8.0 - Part1

- mingw-w64-gmsh/PKGBUILD
Remove patches from upstream that are part of the newer version.
> gmsh: update to 4.13.1

- mingw-w64-openssl/002-relocation.patch
- mingw-w64-openssl/PKGBUILD
Refresh 002-relocation.patch.
The whole openssl dir code was changed upstream and now has everything in one place with the option to read the dirs from the Windows registry if built with OSSL_WINCTX defined.
The registry parts are from what I see namespaced by version and written by the official installer, so we probably don't want to use that to avoid any conflicts with the official installation.
The upside though is that we need to add relocation in fewer places now, and even the "openssl info" commands will use the new functions to now show proper Windows paths instead of the configure time cygwin ones.
Besides that there shouldn't be any functional change.
> openssl: Update to 3.4.0

- mingw-w64-tree-sitter/PKGBUILD
- mingw-w64-wasmtime/PKGBUILD
libwasmtime.a is broken, so make both packages dynamic only
> tree-sitter, libwasmtime: remove static libs

- .github/workflows/main.yml
so it will be sorted by priority: UCRT64 -> CLANG64 -> MINGW64 -> MINGW32 -> CLANG32. this changes the default job shown in "checks" tab, as it's a bit annoying to switch to UCRT64 job because MINGW64 is disabled for a particular package
> CI: change order of jobs

- mingw-w64-python-pip/0002-only-warn-for-externally-managed.patch
- mingw-w64-python-pip/PKGBUILD
We want users to move away from breaking their systems with pip, and upstream provides PEP 668 for this where pip will error out if the system packages are marked as externally managed (by pacman in this case).
In MSYS2 though it's not that easy to use venvs (mixing with system site packages is sometimes required), though things have improved with setuptools/meson-python/rust tooling in the last year. Also in many cases MSYS2 is mainly used in CI, so it's fine to break things as it's just a temporary VM.
To get the message still out there we downgrade the error to warning.
In the future we can escalate this further by making it an error in non-CI envs, and adding a sleep in CI, so it gets annoying but doesn't break things right away.
> pip: in case of EXTERNALLY-MANAGED only warn instead of erroring out

- mingw-w64-python3.12/EXTERNALLY-MANAGED
- mingw-w64-python3.12/PKGBUILD
> python3.12: add `EXTERNALLY-MANAGED` for PEP 668

- mingw-w64-zed/PKGBUILD
it's actually a dummy release to test the bot. update contains no changes, but I've found that using lld fixes #22071. I shouldn't have remove that workaround...
> zed: update to 0.159.9

- mingw-w64-libplist/001-ax_python_devel.patch
- mingw-w64-libplist/003-fix-py-soext.patch
- mingw-w64-libplist/PKGBUILD
Addtionally, change patch to no longer use the `distutils` module.
> libplist: fix detection of newer Python versions

- mingw-w64-libftdi/0003-no-distutils.patch
- mingw-w64-libftdi/PKGBUILD
> libftdi: install Python files in correct prefix

- mingw-w64-python-boto/0001-escape-backslash-in-strings.patch
- mingw-w64-python-boto/0002-update-vendored-six.patch
- mingw-w64-python-boto/PKGBUILD
- mingw-w64-python-zombie-imp/PKGBUILD
Fix some compatibility issues with Python 3.12.
Fedora is using `zombie-imp` to build this package. So, do the same here.
https://src.fedoraproject.org/rpms/python-boto/blob/rawhide/f/python-boto.spec#_63
> python-boto: updates for Python 3.12

- mingw-w64-python-jsonrpc-server/PKGBUILD
- mingw-w64-python-jupyter-nbviewer/PKGBUILD
The bundled version is outdated and incompatible with Python 3.12.
> python-jsonrpc-server: unbundle vendored versioneer

- mingw-w64-opencolorio/PKGBUILD
OSL is used only for optional unit tests, [currently not even built](https://github.com/msys2/MINGW-packages/blob/735bfdb3c592adde4c386d2578a16d6aaf2aeebb/mingw-w64-opencolorio/PKGBUILD#L69) (so it could be removed completely even).
> ocio: remove OSL circular dependency

- mingw-w64-gegl/PKGBUILD
> gegl: Update to 0.4.50

- mingw-w64-gpgme/0011-disable-docs.patch
- mingw-w64-gpgme/PKGBUILD
Building fails in the CLANGARM64 environment with a segfault(?) when trying to run one of the generator executables built during the build process:
```
incd="`test -f defsincdate || echo './'`defsincdate"; \
./mkdefsinc -C . --date "`cat $incd 2>/dev/null`" \
gpgme.texi uiserver.texi lesser.texi gpl.texi >defs.inc
mkdefsinc: taking date from 'gpgme.texi'
make[2]: *** [Makefile:905: defs.inc] Error 139
```
Disable building the documentation for the CLANGARM64 environment as a workaround.
> gpgme: disable docs for CLANGARM64 environment

- mingw-w64-libheif/PKGBUILD
Enable OpenH264 codec
Disable tests, fail to build
> libheif: update to 1.19.2

- mingw-w64-harfbuzz/PKGBUILD
drop cpp_std workaround for newer icu, harfbuzz now sets it automatically
> harfbuzz: Update to 10.1.0

- mingw-w64-python-xpra/PKGBUILD
also adds the pyvda dependency for workspace support (#22482)
> update xpra to v6.2.1

- mingw-w64-emacs/004-libtree-sitter.patch
- mingw-w64-emacs/PKGBUILD
introducing soversion broke emacs build due to hardcoded library names. I'm actually not familiar with this syntax so I added hardcoded name with soversion that must be changed at every libtree-sitter update... contributions welcome 
fixes #22508
> emacs: fix libtree-sitter linking

- mingw-w64-svt-av1/PKGBUILD
This fixes linking error with static library.
ld.exe: test.c:(.text+0x15): undefined reference to `svt_av1_get_version'
* Fixes #22439
> svt-av1: Disable LTO to fix static library

- mingw-w64-SDL2_mixer/PKGBUILD
> SDL2_mixer: Enable modplug library dependency explicitly

- mingw-w64-python-milc/0001-temp-remove-types-colorama.patch
- mingw-w64-python-milc/PKGBUILD
Bumping to latest release as requirement for updating `mingw-w64-x86_64-python-qmk` to `1.1.6`.
> python-milc: update to 1.9.0

- mingw-w64-scotch/PKGBUILD
Also, take better care to not mix build artifacts for 32-bit and 64-bit indexing. 
Fixes #22540.
~~Additionally, add missing dependency to libwinpthread.~~ (Edit: That might not have actually been missing. But it might be a new feature in version 7.0.5. I haven't checked that though.)
> scotch: update to 7.0.5

- mingw-w64-cargo-leptos/PKGBUILD
psm package update fixes aarch64 gnullvm support
> cargo-leptos: enable CLANGARM64

- mingw-w64-dcmtk/PKGBUILD
Cherry-pick patch from upstream.
See the build error in #22550.
```
[snip]
In file included from D:/M/msys64/clang64/include/dcmtk/ofstd/ofmem.h:27:
D:/M/msys64/clang64/include/dcmtk/ofstd/ofutil.h:79:18: error: no member named 'pt' in 'OFrvalue_storage<T, >'
79 |         : t( rhs.pt ) {}
|              ~~~ ^
```
> dcmtk: fix compilation with clang 19

- mingw-w64-gimp/0009-build-fix-svg-pixbuf-loader-check-with-librsvg-2.59.patch
- mingw-w64-gimp/0010-fix-compatibility-with-libheif-1.18.0.patch
- mingw-w64-gimp/PKGBUILD
Cherry-pick patch from upstream to avoid warnings that are elevated to an error in GCC 14.
See build error in #22550.
```
../../../gimp-2.10.38/plug-ins/file-tiff/file-tiff-load.c:1372:56: error: passing argument 2 of 'gimp_image_get_resolution' from incompatible pointer type [-Wincompatible-pointer-types]
1372 |                     gimp_image_get_resolution (*image, &xres, &yres);
|                                                        ^~~~~
|                                                        |
|                                                        gfloat * {aka float *}
In file included from ../../../gimp-2.10.38/libgimp/gimp_pdb_headers.h:55,
from ../../../gimp-2.10.38/libgimp/gimp.h:66,
from ../../../gimp-2.10.38/plug-ins/file-tiff/file-tiff-load.c:52: …
```
> gimp: rebuild with GCC 14

- mingw-w64-jsoncpp/0001-static-lib-name.patch
- mingw-w64-jsoncpp/PKGBUILD
> jsoncpp: correct name of static library

- mingw-w64-gst-plugins-bad/0004-check-d3d11-header.patch
- mingw-w64-gst-plugins-bad/PKGBUILD
Fixes build issue in CLANGARM64 environment (see #22550).
I can't test if the change actually fixes the build issues. But if the compilation is currently failing because that header can't be found, the configuration test should also fail for the same reason. The failing configuration test would avoid compiling the problematic source files.
> gst-plugins-bad: check for necessary header in configure test

- mingw-w64-lua/0004-fix-fseek-on-mingw.patch
- mingw-w64-lua/PKGBUILD
- mingw-w64-lua53/PKGBUILD
- mingw-w64-lua53/fix-fseek-on-mingw.patch
Around 4 months ago, in order to fix [https://github.com/msys2/MINGW-packages/issues/20892](https://github.com/msys2/MINGW-packages/issues/20892), I submitted a PR [https://github.com/msys2/MINGW-packages/pull/21266](https://github.com/msys2/MINGW-packages/pull/21266) that got merged with a workaround given by myself.
Today, looking for that issue in the Lua mailing list, I found that someone reported it at [http://lua-users.org/lists/lua-l/2015-05/msg00315.html](http://lua-users.org/lists/lua-l/2015-05/msg00315.html) and got a final solution at [http://lua-users.org/lists/lua-l/2015-05/msg00370.html](http://lua-users.org/lists/lua-l/2015-05/msg00370.html) provided by **Roberto Ierusalimschy** (Lua's author).
Thus, this current PR is just replacing my old solution with the one provided by …
> [lua, lua53] use fseek solution for mingw compilers provided by Lua's author

- mingw-w64-python/PKGBUILD
This affects MSYS2 specifically since it would find the msys "cmd" bash script when running shutil.which("cmd") instead of the system cmd.exe.
> python: backport shutil.which fixes

- mingw-w64-gimp3/PKGBUILD
gimp3 actually has some files that conflict with gimp package (at first gimp.exe)
> gimp3: add provides and conflicts fields

- mingw-w64-meson/PKGBUILD
at one moment cargo subprojects start failing to extract because of new `autolib` section in Cargo.toml. add an upstream fix for this section support
> meson: backport a fix for `autolib` sections in Cargo subprojects

- mingw-w64-tuxpaint/001-makefile.patch
- mingw-w64-tuxpaint/PKGBUILD
- cleanup patch
- remove python2 from optdepends, as a part of python2 removal
> tuxpaint: update to 0.9.34

- mingw-w64-gitoxide/PKGBUILD
also turns out libsqlite3-sys is no longer built with max-pure feature
> gitoxide: package shell completions; do not depend on sqlite

- mingw-w64-gimp/PKGBUILD
*as discussed below*:
mingw32 and mingw64 is used by gimp devs to make release. for remaining envs there is no sense to keep EOLed version of python, users can switch to gimp3, which is about to release soon
> gimp: rebuild without python2 for ucrt64 and clang64

- mingw-w64-gnucobol/0001-gnucobol-extras-include-srcdir.patch
- mingw-w64-gnucobol/0002-deprecated-ucrt-functions.patch
- mingw-w64-gnucobol/0003-missing-libxml2-header.patch
- mingw-w64-gnucobol/PKGBUILD
- PKGBUILD cleanup
- add missing libxml2 header
- fix deprecated ucrt functions
@GitMensch 
@lazka can we remove `epoch=1` ?
> gnucobol: fix building discrepancy

- mingw-w64-qucs-s/PKGBUILD
This an eletrical schematic and simulator using ngspice and quics own simulator.
Xyce can be used but Xyce hasn't been packaged yet.
What is also great is https://github.com/ra3xdh/qucs_s has msys2 on their CI
> Add qucs-s

- mingw-w64-wasm-bindgen/Cargo.lock
- mingw-w64-wasm-bindgen/PKGBUILD
closes https://github.com/msys2/MINGW-packages/security/dependabot/3
> wasm-bindgen: update to 0.2.97

- mingw-w64-chicken/PKGBUILD
* It doesn't respect CC, so pass explicitely.
* Also pass CFLAGS while at it.
* Silence build warning/error with newer GCC
* Try enabling parallel make
> chicken: Update to 5.4.0

- mingw-w64-mosquitto/0002-mosquitto-2.0.18-pkgconf-static-cflags.patch
- mingw-w64-mosquitto/0003-use-winpthreads.patch
- mingw-w64-mosquitto/PKGBUILD
It now requires threading and fails to build if disabled (likely not tested upstream) so try using winpthreads. Hopefully good enough.
> mosquitto: Update to 2.0.20

- mingw-w64-libjaylink/011-avoid-hidden-visibility.patch
- mingw-w64-libjaylink/PKGBUILD
- mingw-w64-openocd/PKGBUILD
> openocd: rebuild for libjaylink

- mingw-w64-groonga/PKGBUILD
Groonga version14.1.1 has just released [here](https://github.com/groonga/groonga/releases/tag/v14.1.1).
> Groonga: Update to 14.1.1

- mingw-w64-python-decouple/PKGBUILD
- mingw-w64-python-hightime/PKGBUILD
- mingw-w64-python-nidaqmx/0001-use-poetry-core-backend.patch
- mingw-w64-python-nidaqmx/PKGBUILD
- mingw-w64-python-tzlocal/PKGBUILD
Added `python-nidaqmx` package.
```
$ python
Python 3.11.9 (main, Apr 12 2024, 09:55:30)  [GCC Clang 18.1.3 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import nidaqmx
>>> print(nidaqmx.__version__)
1.0.1
```
Need to package dependencies:
> python-nidaqmx: new package

- mingw-w64-libgig/PKGBUILD
- mingw-w64-libgig/libgig-4.3.0-libdir.patch
fix #22740
the .patch comes from arch is so that the shared files are not namespaced, unless this is desirable for msys2?
> libgig: add package

- mingw-w64-python-toptica-lasersdk/PKGBUILD
Added `python-toptica-lasersdk` package.
```
$ lasersdk_gen
usage: lasersdk_gen [-h] [-m name] [-ul level] [-a] [-d] [-p cmd mon] [-c name] model_xml
Generate Python code from a DeCoP system description.
positional arguments:
model_xml             DeCoP system description file or device IP address
options:
-h, --help            show this help message and exit
-m name, --module name
set the name of the generated Python module
-ul level, --userlevel level
include properties up to this user level
-a, --async           generate asynchronous Python code
-d, --download        download system model from a device
-p cmd mon, --ports cmd mon
set default ports for network connections
-c name, --class name
set the name of the device class
```
> [new package] python-toptica-lasersdk 3.2.0

- mingw-w64-curl/PKGBUILD
remove backports included in the new release
> curl: Update to 8.11.1

- mingw-w64-octave/0005-makeinfo-perl.patch
- mingw-w64-octave/PKGBUILD
`libtool` and `autoconf` have been patched to better support LLVM Flang in the meantime. So, remove the workarounds that were needed earlier.
> octave: update to 9.3.0

- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/config.toml
this is not supported upstream, but a workaround was used. set build-dir in config.toml, make dest dirs names contain $MSYSTEM to match previous behavior
asking @filnet as a workaround's author is it ok to do so
> rust: don't build out of tree

- mingw-w64-python-pysfcgal/PKGBUILD
- mingw-w64-sfcgal/PKGBUILD
Update SFCGAL and PySFCGAL to 2.0.0
Fix PySFCGAL license SPDX
> SFCGAL: Update to 2.0.0

- mingw-w64-pcre2/PKGBUILD
Enable JIT compiler support. This option is enabled in various other package repositories including Arch, Debian, vcpkg, and Homebrew. I've only performed light testing and only on a CLANGARM64 build.
> pcre2: set --enable-jit

- mingw-w64-luajit/PKGBUILD
During this update, in the CI logs on my branch, I noticed some unusual ```wtdccm``` DLL runtime dependency of ```luajit```'s binary artifacts on every MSYS2 environment (mingw64, ucrt64, ...):
However, downloading the UCRT64 generated artifacts from GitHub, and running MSVC's dumpbin to list dependencies, I got these outputs:
* ```luajit.exe``` interpreter:
```cmd
dumpbin /DEPENDENTS luajit.exe
```
* ```lua51.dll```:
```cmd
dumpbin /DEPENDENTS lua51.dll
```
In my POV, it seems to be safe, because that ```wtdccm``` DLL most likely is some CI-related thing, and MSVC didn't list it as dependency. I tried to google for such dll, but I didn't find anything valuable to report here.
Maybe someone has a better explanation for this. Feel free to investigate further before merging.
> luajit: update to 2.1.1734355927

- mingw-w64-fox/PKGBUILD
"-Wno-register" avoids lot of clang errors kind of:
```
error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
```
> Enable fox for clangarm64

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libmangle-git/PKGBUILD
- mingw-w64-tools-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-winstorecompat-git/PKGBUILD
https://github.com/mingw-w64/mingw-w64/compare/a2d19218d...03d8a40f5
drop the revert since that should be fixed via https://github.com/mingw-w64/mingw-w64/commit/c9eca28decb3aa5213fe22ab1f9883df91d79806
> mingw-w64: Update to 03d8a40f57

- mingw-w64-libjpeg-turbo/0001-header-compat.mingw.patch
- mingw-w64-libjpeg-turbo/PKGBUILD
- mingw-w64-libjpeg-turbo/libjpeg-turbo-1.3.1-libmng-compatibility.patch
* files moved under src/
the patches and headers are all questionable since I can't find any context, but let's leave as is for now.
> libjpeg-turbo: Update to 3.1.0

- mingw-w64-python-maturin/PKGBUILD
> python-maturin: update to 1.8.0

- mingw-w64-python-pyopengl-accelerate/PKGBUILD
- mingw-w64-python-pyopengl-accelerate/pyopengl-array.patch
- mingw-w64-python-pyopengl-accelerate/pyopengl-version.patch
- mingw-w64-python-pyopengl/PKGBUILD
- mingw-w64-python-pyopengl/pyopengl-egl-open-warning.patch
- mingw-w64-python-pyopengl/pyopengl-version.patch
This update requires some explanations as [`pyopengl`](https://github.com/mcfletch/pyopengl) does not look actively maintained anymore:
* switched to github instead of pypi because the 3.1.8 release of `pyopengl-accelerate` release is missing from pypi: https://pypi.org/project/PyOpenGL-accelerate/
* added a "version" patch because the release on github forgot to bump the version: https://github.com/mcfletch/pyopengl/issues/123
* the "array" patch fixes compilation with newer toolchains, as per https://github.com/mcfletch/pyopengl/pull/112
* the checks are skipped because they fail on my test VM (even after installing `pygame`) despite `pyopengl` working just fine (perhaps they expect a real GPU to run?) - I have left them in, just commented out (I am not sure what the best practice is - …
> `pyopengl[-accelerate]`: update to 3.1.8

- mingw-w64-llama.cpp/PKGBUILD
* Introduce epoch field to indicate that new package version numbering scheme beginning with letter b is newer than old scheme beginning with letter r
* Amend output file renaming logic since llama.cpp outputs have changed significantly since last package update: only target files not already prefixed with word 'llama' (skipping DLLs), change prefix to 'llama' instead of 'llama.cpp' (consistent with new default convention), remove logic for renaming file 'main.exe' since this no longer exists (we instead have llama-cli and llama-server)
* Optimise build configuration: include more backends for GGML (Vulkan and OpenCL), add preferred openblas64 library as dependency, add openmp as build dependency, other option tweaks similar to ArchLinux PKGBUILD script
* More informative package …
> llama.cpp: update to b4394

- mingw-w64-x265/PKGBUILD
Back with 3.4 there was no tarball so we switched to bitbucket generated tarballs.
In the case of the 4.1 tag the version info is outdated resulting in the wrong version displayed when running x265, which was fixed after tagging the release, and which was then used to roll the tarball.
See https://bitbucket.org/multicoreware/x265_git/commits/branch/Release_4.1
Switch back to the tarballs to fix this.
Fixes #22931
> x265: switch back to using release tarballs

- mingw-w64-python-llvmlite/PKGBUILD
- mingw-w64-python-numba/5e917b96ae7033e994f185cb37329a07e56d51b6.patch
- mingw-w64-python-numba/PKGBUILD
update numba due to ImportError raised because of numpy version. this requires llvmlite update
> python-llvmlite: update to 0.44.0rc2; python-numba: update to 0.61.0rc2

- mingw-w64-doxygen/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
See https://github.com/doxygen/doxygen/pull/11302
This means we can remove the revert from mingw-w64 headers which was using the register keyword.
> doxygen: backport fix for 'register' undef issue

- mingw-w64-llama.cpp/PKGBUILD
It is now possible to switch on curl dependent features since the build errors on MSYS2 have been fixed through merging of https://github.com/ggerganov/llama.cpp/pull/11013
> llama.cpp : upgrade to b4404 and switch on curl library dependent features

- mingw-w64-gimp3/0002-skip-test-env.patch
- mingw-w64-gimp3/PKGBUILD
- `0002-skip-test-env.patch`: refresh
- remove options that are set to default value
- add `omp` as dependency explicitly
- `enable-default-bin` is fixed upstream
- add libbacktrace for non-i686 environments
- explicitly disable `libunwind` as it can't be found by meson (because gimp uses libunwind not from LLVM)
> gimp3: update to 3.0.0RC2

- mingw-w64-tomlplusplus/0001-tomlplusplus-fix-cmake-imported-location.patch
- mingw-w64-tomlplusplus/PKGBUILD
> tomlplusplus: Fix dll path in cmake imported location

- mingw-w64-fltk/PKGBUILD
If FLTK is built with GDI+, unloading the library leads to a deadlock (at least in Octave).
See also: https://octave.discourse.group/t/6097/11
Following up on the discussion in #22620.
> fltk: disable GDI+

- mingw-w64-cargo-local-registry/PKGBUILD
while working on https://github.com/msys2/MINGW-packages/pull/23050 I found that this package is not updated. the update contains some fixes for build. cherry-pick changes from libgit2-1.9.0 branch while at it
> cargo-local-registry: update to 0.2.7

- mingw-w64-kicad/007-llvm-libcxx-19.patch
- mingw-w64-kicad/PKGBUILD
Avoid instantiating the std::char_traits<T> template with arbitrary types.
That is no longer possible with the implementation of the C++ STL from LLVM 19.
> kicad: fix building with libc++ from LLVM 19

- mingw-w64-openblas/PKGBUILD
Turns out that, for `DYNAMIC_LIST` to considered, `DYNAMIC_ARCH=ON` is also required
> openblas: Properly enable dynamic cores on ARM64

- mingw-w64-wolfssl/PKGBUILD
The content in `cmake_options` variable is taken from [Arch Linux](https://gitlab.archlinux.org/archlinux/packaging/packages/wolfssl/-/blob/main/PKGBUILD?ref_type=heads#L31).
I haven't test it on CLANGARM64.
> wolfssl: new package

- mingw-w64-libpng/PKGBUILD
~~And try dropping the apng patches~~
~~* Arch dropped them long ago~~
~~* Gentoo is working on it~~
~~(see the removed comment for links)~~
> libpng: Update to 1.6.45

- mingw-w64-zed/PKGBUILD
this update can probably break python projects with venv on root (with MinGW CPython). let me know if this is an issue for you
> zed: update to 0.169.2

- mingw-w64-qemu/PKGBUILD
Upstream QEMU was fixed, by removing usage of gcc_struct attribute, and enabling plugins linkage using lld.
- https://gitlab.com/qemu-project/qemu/-/commit/8f5a4cfc7ed9e06e07fdd8e8fdf50ef3ea783f63
- https://gitlab.com/qemu-project/qemu/-/commit/923710b6d5b21d9b3fcecc7e6719cfa5a53de268
Those changes will be available for 10.0, but meanwhile, we can safely backport them on 9.2, as the gcc_struct attribute investigation was made on 9.2 release (see patch commit messages for more details and links).
Note: dependency virglrenderer is skipped because
mingw-w64-clang-X-virglrenderer is not available.
> qemu: reenable clang builds

- mingw-w64-librsvg/PKGBUILD
Stacked on top of https://github.com/msys2/MINGW-packages/pull/23136
> librsvg: drop LLD workaround

- mingw-w64-qt6-declarative/PKGBUILD
Currently the VectorImage QML component is missing caused by not having `Qt::Svg` module while building qt-declarative. This patch adds such dependency as [it's also what Arch Linux did currently](https://gitlab.archlinux.org/archlinux/packaging/packages/qt6-declarative/-/blob/32cc4776bae9a733b4825111cbd72c7b28aa53d7/PKGBUILD#L25).
> qt6-declarative: should also build vectorimage

- mingw-w64-zed/PKGBUILD
- mingw-w64-zed/zed-set-rustflags.patch
zed-set-rustflags.patch: cargo has a strange behavior regarding applying compilation flags. it ignores flags from .cargo/config.toml in case of RUSTFLAGS env var is set. this makes some useful flags ignored
> zed: update to 0.170.1

- mingw-w64-python-numba/5e917b96ae7033e994f185cb37329a07e56d51b6.patch
- mingw-w64-python-numba/PKGBUILD
it was removed in 258f6e303f1e4c29b794ecc55517c2c030b3220c while actually [it's not fixed](https://github.com/numba/numba/blob/0.61.0/numba/__init__.py#L42-L45)
> python-numba: restore patch to remove numpy version pinning

- mingw-w64-vk-bootstrap/PKGBUILD
The upstream skipped 1.4.304 and jump to 1.4.305. I think our vulkan headers will be updated to 305 soon anyway.
> vk-bootstrap: Update to 1.4.305

- mingw-w64-kstatusnotifieritem/PKGBUILD
This is a tier 2 KDE Framework package/library, which is required to build some KDE applications (NeoChat for example).
Note: GPG key is not tested since I have no idea about how to test it properly.
> [new package] kstatusnotifieritem

- mingw-w64-mpv/PKGBUILD
Those are disabled by default in meson_options.txt and were enabled before switching to meson. https://github.com/msys2/MINGW-packages/blob/e0d5ae00d1b21721da4371249145735b3c113cc1/mingw-w64-mpv/PKGBUILD#L73-L91
* Fixes #23211
> mpv: Enable cdda and dvdnav options

- mingw-w64-dwarfstack/001-aarch64-stack.patch
- mingw-w64-dwarfstack/002-no-int-conversion.patch
- mingw-w64-dwarfstack/PKGBUILD
```
Hernan@SURFACE7 CLANGARM64 
$ ./exception.exe
application crashed
code: 0xC0000005 (ACCESS_VIOLATION)
write access violation at 0x0000000000001234
base address: 0x00007FF6DB1C0000 (exception.exe)
stack 00: 0x00007FF6DB1C1BB0 (crasher.c:10:6) [crasher]
stack 01: 0x00007FF6DB1C146F (exception.c:117:3) [c]
stack 02: 0x00007FF6DB1C1483 (exception.c:122:3) [b]
stack 03: 0x00007FF6DB1C1497 (exception.c:127:3) [a]
stack 04: 0x00007FF6DB1C14CF (exception.c:134:3) [main]
stack 05: 0x00007FF6DB1C13CF (crtexe.c:266:15) [__tmainCRTStartup]
Segmentation fault
```
> dwarfstack: Enable aarch64 builds

- mingw-w64-binutils/0110-binutils-mingw-gnu-print.patch
- mingw-w64-binutils/2001-ld-option-to-move-default-bases-under-4GB.patch
- mingw-w64-binutils/PKGBUILD
* 0110-binutils-mingw-gnu-print.patch: gold was removed, so remove gold hunks
* 2001-ld-option-to-move-default-bases-under-4GB.patch: refresh
> binutils: Update to 2.44

- mingw-w64-lapack/PKGBUILD
Cherry-pick some patches from upstream to support building with `-integer-8` (i.e., the 64-bit integer variants of the libraries).
> lapack: update to 3.12.1

- mingw-w64-soapyhackrf/PKGBUILD
I am really sorry about this...
Last time, an "r" made it into the wrong place...
> SoapyHackRF: Fix package name typo

- mingw-w64-aria2/0001-less-strict-gettext-checks.patch
- mingw-w64-aria2/PKGBUILD
It would fail with this otherwise:
error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.18 but the autoconf macros are from gettext version 0.22
> aria2: fix build with new gettext

- mingw-w64-groonga/PKGBUILD
Groonga version15.0.0 has just released [here](https://github.com/groonga/groonga/releases/tag/v15.0.0).
> Groonga: Update to 15.0.0

- mingw-w64-gmsh/PKGBUILD
Cherry-pick patch from upstream.
Fixes #23374.
> gmsh: avoid issue with FLTK 1.4

- mingw-w64-python/0122-fixup-add-python-config-sh.patch
- mingw-w64-python/PKGBUILD
Since https://github.com/msys2/MSYS2-packages/commit/076c4a94a618413c8b22bed40ee13649434f5145 python-config would output cygwin paths instead of Windows paths since OSTYPE has changed.
This adjusts python-config to check for the new value.
> python: fix python-config output path format

- mingw-w64-cppdap/PKGBUILD
- mingw-w64-fribidi/PKGBUILD
- mingw-w64-gdk-pixbuf2/PKGBUILD
- mingw-w64-giflib/PKGBUILD
- mingw-w64-glib2/PKGBUILD
- mingw-w64-graphite2/PKGBUILD
- mingw-w64-highway/PKGBUILD
- mingw-w64-http-parser/PKGBUILD
- mingw-w64-lerc/PKGBUILD
- mingw-w64-libbacktrace/PKGBUILD
- mingw-w64-libdeflate/PKGBUILD
- mingw-w64-libdovi/PKGBUILD
- mingw-w64-libkqueue/PKGBUILD
- mingw-w64-liblc3/PKGBUILD
- mingw-w64-libraqm/PKGBUILD
- mingw-w64-libtiff/PKGBUILD
- mingw-w64-libwebp/PKGBUILD
- mingw-w64-p11-kit/PKGBUILD
- mingw-w64-pixman/PKGBUILD
- mingw-w64-rtmpdump/PKGBUILD
- mingw-w64-speex/PKGBUILD
- mingw-w64-srt/PKGBUILD
- mingw-w64-svt-av1/PKGBUILD
This populates the `msys2_repository_url` property for a couple of packages, helping expose that information in the SBOM which is generated for MSYS2.
> Populate msys2_repository_url

- mingw-w64-python-fortls/PKGBUILD
[`fortls`](https://github.com/fortran-lang/fortls) is a Language Server for Fortran that provides code completion, diagnostics, hovering, and more.
This package is also available in the AUR repository. For details, see its [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fortls) in the AUR repository.
> [new package] fortls-v3.1.2

- mingw-w64-pcre2/PKGBUILD
See https://github.com/PCRE2Project/pcre2/blob/c421b939e7e1e7caf8a3de89b86f8e3fa83317e4/SECURITY.md for the signing key change
> pcre2: Update to 10.45

- mingw-w64-groonga/PKGBUILD
Groonga version15.0.1 has just released [here](https://github.com/groonga/groonga/releases/tag/v15.0.1).
> Groonga: Update to 15.0.1

- mingw-w64-sqlitebrowser/0001-sqlitebrowser-install.patch
- mingw-w64-sqlitebrowser/0002-sqlitebrowser-linking.patch
- mingw-w64-sqlitebrowser/PKGBUILD
I wish that they supported https://utelle.github.io/SQLite3MultipleCiphers/ instead of just SQLCipher. 
The encrypted DBs I need support are not supported by SQLCipher alone which requires `[System.Data.SQLite] RC4` as https://github.com/msys2/MINGW-packages/pull/23246 does 😢
> sqlitebrowser: Update to 3.13.1 and build with SQLCipher

- mingw-w64-zed/PKGBUILD
> zed: update to 0.174.6

- mingw-w64-python-geoalchemy2/0001-geoalchemy2-0.17.1-search-spatialite.patch
- mingw-w64-python-geoalchemy2/PKGBUILD
Patch for auto resolve path to spatialite module (currently [path should be set manually](https://geoalchemy-2.readthedocs.io/en/latest/spatialite_dialect.html)).
I suggest checking the patch here, then suggest it to the upstream repository.
> python-geoalchemy2: support spatialite databases

- mingw-w64-cargo-c/PKGBUILD
- mingw-w64-gst-plugins-rs/PKGBUILD
- mingw-w64-keepawake/PKGBUILD
- mingw-w64-libdovi/PKGBUILD
- mingw-w64-libimagequant/PKGBUILD
- mingw-w64-rav1e/PKGBUILD
- remove backport
- remove workarounds for rdeps for future updates/rebuilds
> cargo-c: update to 0.10.11

- mingw-w64-PKGBUILD-templates/PKGBUILD.cargo-c-tarball.sh
with cargo-c downstream patch being dropped in 631e0ec2122c1b87f2dfb6588e3dbb2538ce0405 we start using `--meson-paths` option to get `lib` prefix for libraries. create a template to make this a bit more clear for maintainers
> add a template for cargo-c built package

- mingw-w64-pidgin/PKGBUILD
Requires:
- https://github.com/msys2/MINGW-packages/pull/23490
- https://github.com/msys2/MINGW-packages/pull/23489
- https://github.com/msys2/MINGW-packages/pull/23486
- https://github.com/msys2/MINGW-packages/pull/23491
> pidgin: Update to 2.14.14 and enable aarch64 builds

- mingw-w64-innoextract/PKGBUILD
There have been 82 revisions since version 1.9 was tagged, over 1,600 days passed, and https://github.com/dscharrer/innoextract/issues/176 does not exactly suggest that any new version will be tagged any time soon.
Yet version 1.9 is incompatible with many an InnoSetup version, while the code actually has been updated to handle the most recent one in https://github.com/dscharrer/innoextract/commit/e58f295d80c3.
So let's switch to the most recent development version (according to https://github.com/dscharrer/innoextract/blob/HEAD/VERSION it is "1.10-dev").
I verified manually that this version of `innoextract` can handle the recent Git for Windows installers, for example, while the most recent one in MSYS2 cannot.
> innoextract: update to the most recent version ("1.10-dev")

- mingw-w64-ghdl/PKGBUILD
This PR bumps ghdl for MinGW64 and UCRT64 from 4.1.0 to 5.0.1.
The patch for LLVM-19 isn't required anymore.
> ghdl: update to 5.0.1

- mingw-w64-fltk/PKGBUILD
According to FLTK: "[Its ABI and API are 100% backwards compatible with FLTK 1.4.0](https://www.fltk.org/articles.php?L1972)". Therefore there is no need to rebuild other packages that depend on it.
> fltk: update to 1.4.2

- mingw-w64-flang/0003-flang-Inherit-target-specific-code-for-BIND-C-types.patch
- mingw-w64-flang/PKGBUILD
Prompted by @MehdiChinoune's comment in https://github.com/llvm/llvm-project/issues/114035#issuecomment-2693354786.
I tried building the example in the original comment in that issue. It is executing fine for me with the changes from here.
@MehdiChinoune: Did you come across other projects that failed to compile with that error?
> flang: inherit target specific code for BIND(C) on Windows

- mingw-w64-stk/PKGBUILD
Adds [The Synthesis ToolKit in C++ (STK)](https://ccrma.stanford.edu/software/stk/)
Caveats:
* `jack2` is temporarily disabled for `*-clang-*`, the dependency does not yet exist for those.
```
pkg/mingw-w64-clang-aarch64-stk/
└── clangarm64
├── bin
│   └── libstk.dll
├── include
│   └── stk
│       ├── ADSR.h
│        [...]
│       └── WvOut.h
├── lib
│   ├── cmake
│   │   └── stk
│   │       ├── stk-config-release.cmake
│   │       └── stk-config.cmake
│   ├── libstk.a
│   └── libstk.dll.a
└── share
├── licenses
│   └── stk
│       └── LICENSE
└── stk
└── rawwaves
├── ahh.raw
[...]
└── twopeaks.raw
```
Related downstream:
* https://github.com/LMMS/lmms/issues/7526#issuecomment-2686158914
* https://github.com/LMMS/lmms/pull/7736
> [new-package] stk 5.0.1

- mingw-w64-groonga/PKGBUILD
Groonga version15.0.3 has just released [here](https://github.com/groonga/groonga/releases/tag/v15.0.3).
> Groonga: Update to 15.0.3

- mingw-w64-uutils-coreutils/PKGBUILD
linking dynamic libonig making rustc link libunwind.dll on CLANG* automatically. unconditional dependency on gcc-libs shouldn't hurt too much there. also set RUSTFLAGS to explicitly disable crt-static
> uutils-coreutils: depend on gcc-libs

- mingw-w64-zed/.gitignore
- mingw-w64-zed/PKGBUILD
aws-lc-sys@0.27.0 fixed CFLAGS handling so a compile flag workaround is not needed
> zed: update to 0.177.9

- mingw-w64-vulkanscenegraph/0003-arm64-macro-clash.patch
- mingw-w64-vulkanscenegraph/PKGBUILD
This is a known issue from eons ago when there are functions, classes or methods called `MemoryBarrier`. This only affects ARM64:
https://bugreports.qt.io/browse/QTBUG-77388?jql=reporter%20%3D%20hernan.c.martinez
https://codereview.qt-project.org/c/qt/qtbase/+/277243
> vsg: Fix macro clash in aarch64 when including PipelineBarrier.h

- mingw-w64-gnutls/PKGBUILD
* p11-kit does not support static builds, so avoid depending on it for the static lib only
* make sure p11-kit is also not in Requires.private by using the static .pc file
* Fix libintl import lib being referenced by path in the .pc file by passing --without-libintl-prefix
This fixes static linking against libgnutls.
Fixes #23287
> gnutls: fix the static build

- mingw-w64-libavif/PKGBUILD
I'm puzzled how 1.2.0 was built, nothing substantial was changed w.r.t. libargparse dependency since?!
https://github.com/AOMediaCodec/libavif/compare/v1.2.0...v1.2.1
It now looks like git needs to be added as makedepends for FetchContent to work (and also libxml2 for some new functionality...).
> libavif: update to 1.2.1

- mingw-w64-gimp/PKGBUILD
it's not needed for release binaries
fixes https://github.com/msys2/MINGW-packages/issues/22629
> gimp: disable debug console

- mingw-w64-lua-luarocks/0001-luarocks_msys2_mingw_w64.patch
- mingw-w64-lua-luarocks/PKGBUILD
Fixes [https://github.com/msys2/MINGW-packages/issues/23493](https://github.com/msys2/MINGW-packages/issues/23493)
Fixes the upstream issue [https://github.com/luarocks/luarocks/issues/1428](https://github.com/luarocks/luarocks/issues/1428) for MSYS2, because even though it was supposed to be fixed at [https://github.com/luarocks/luarocks/pull/1616](https://github.com/luarocks/luarocks/pull/1616), it still happens on MSYS2 even after a LuaRocks upgrade.
Changes:
* The first addition of code is responsible to fix [https://github.com/msys2/MINGW-packages/issues/23493](https://github.com/msys2/MINGW-packages/issues/23493);
* The second addition of code fixes [https://github.com/luarocks/luarocks/issues/1428](https://github.com/luarocks/luarocks/issues/1428).
> [!NOTE]
> 
> I'll try to …
> luarocks: fix C modules installation/removal on CLANG64 and CLANGARM64

- mingw-w64-gtk2/PKGBUILD
- mingw-w64-libglade/PKGBUILD
- mingw-w64-librest/PKGBUILD
- mingw-w64-libsoup/PKGBUILD
- mingw-w64-phodav/PKGBUILD
- mingw-w64-uhttpmock/PKGBUILD
yet another portion after gimp2 drop
follow up to #23709
> drop some librsvg rdeps (4/N)

- mingw-w64-opencolorio/PKGBUILD
@lazka I don't think this works around the upstream issue though...
> opencolorio: build using sse2neon from repo

- mingw-w64-mimalloc/0002-remove-the-lib-prefix-when-enabling-mimalloc-redirec.patch
- mingw-w64-mimalloc/PKGBUILD
The mimalloc-redirect feature supports only the following library names: `mimalloc.dll`, `mimalloc-override.dll`, `mimalloc-secure.dll`, `mimalloc-secure-debug.dll`, `mimalloc-debug.dll`, and `mimalloc-release.dll`, none of which include the `lib` prefix.
https://github.com/microsoft/mimalloc/pull/1045
> mimalloc: remove the `lib` prefix when enabling mimalloc-redirect

- mingw-w64-mimalloc/PKGBUILD
It just copies pre-built binaries that mimalloc has in git.
See https://github.com/microsoft/mimalloc/issues/836
> mimalloc: drop mimalloc-redirect, not open source

- mingw-w64-openexr/PKGBUILD
MINGW32 failure reported [upstream](https://github.com/AcademySoftwareFoundation/openexr/issues/2009).
> openexr: update to 3.3.3

- mingw-w64-SDL2_image/PKGBUILD
actually it should be `drop some 32-bit for librsvg rdeps (5/N)`, but there's only one package...
follow-up to #23723
> SDL2_image: drop mingw32

- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/config.toml
cc #23346
there is no sense of using rustfmt or clippy in i686 if you have x86_64 working
> rust: build only rustc and cargo for i686

- mingw-w64-meld3/PKGBUILD
- mingw-w64-meld3/pyscript2exe.py
So it can be started from native tools
Adjust compileall to not byte compile .py script in /bin
> meld3: provide an .exe launcher

- mingw-w64-groonga/PKGBUILD
Groonga version15.0.4 has just released [here](https://github.com/groonga/groonga/releases/tag/v15.0.4).
> Groonga: Update to 15.0.4

- mingw-w64-ghostscript/PKGBUILD
Reverts msys2/MINGW-packages#23821 because it's a dependency of gimp 🤦
> Revert "drop 32-bit for some librsvg rdeps (6/N)"

- mingw-w64-qt-installer-framework/PKGBUILD
drop two patches included in the release
> qt-installer-framework: Update to 4.9.0

- mingw-w64-sdl3-image/PKGBUILD
- Disable STB option so that libjpg and libpng are actually used.
(This is a similar case to #23804 )
> sdl3-image: update/fix configuration options:

- mingw-w64-libmikmod/PKGBUILD
windows native output drivers are more than enough.
( CC @Biswa96 as the last updater of the pkg )
> libmikmod: disable openal output.

- mingw-w64-sdl3-ttf/PKGBUILD
It was already enabled, but was missed in 'depends' list.
> sdl3-ttf: add harfbuzz to depends.

- mingw-w64-xeve/002-sys-sse2neon.patch
- mingw-w64-xeve/PKGBUILD
Simply using a newer sse2neon got it to compile
> xeve: Update to 0.5.1 and enable aarch64 builds

- mingw-w64-supertuxkart/PKGBUILD
Requires https://github.com/msys2/MINGW-packages/pull/23886
> supertuxkart: Make it buildable with CMake 4.0 and enable aarch64 builds

- mingw-w64-wasm-bindgen/.gitignore
- mingw-w64-wasm-bindgen/Cargo.lock
- mingw-w64-wasm-bindgen/PKGBUILD
closes https://github.com/msys2/MINGW-packages/security/dependabot/8
closes https://github.com/msys2/MINGW-packages/security/dependabot/1
closes https://github.com/msys2/MINGW-packages/security/dependabot/2
raytracer was used only in example, so let Cargo forget about it and remove raytracer from lockfile
> wasm-bindgen: update lockfile

- mingw-w64-sundials/PKGBUILD
Also, do not build Fortran modules in CLANG* environments.
Attempting to build them with LLVM Flang fails with errors like:
```
D:\M\msys64\clang64\bin\flang.exe -ID:\_\B\src\sundials-7.3.0\src\sundials\fmod_int64 -ID:/_/B/src/sundials-7.3.0/include -ID:/_/B/src/build-CLANG64/include -ID:/_/B/src/sundials-7.3.0/src/sundials -ID:/_/B/src/build-CLANG64/src/sundials -ID:/_/B/src/build-CLANG64/fortran_SHARED -O3 -module-dirfortran_SHARED -ffixed-line-length-72 -c src/sundials/fmod_int64/CMakeFiles/sundials_fcore_mod_obj_shared.dir/fsundials_core_mod.f90-pp.f90 -o src/sundials/fmod_int64/CMakeFiles/sundials_fcore_mod_obj_shared.dir/fsundials_core_mod.f90.obj
error: loc("D:/_/B/src/sundials-7.3.0/src/sundials/fmod_int64/fsundials_core_mod.f90":699:16): …
```
> sundials: update to 7.3.0

- mingw-w64-notepad++/002-windres-codepage.patch
- mingw-w64-notepad++/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/23915
> notepad++: Fix document controls in CLANG based builds

- mingw-w64-libetonyek/PKGBUILD
Requires https://github.com/msys2/MINGW-packages/pull/24003
> libetonyek: Enable aarch64 builds

- mingw-w64-luajit/PKGBUILD
1. The usual update changes
2. Changed from `https://luajit.org` to `http://luajit.org` (read the details below).
> [!NOTE]
> 
> At the time of writing, LuaJIT website [https://luajit.org](https://luajit.org) is running a self-signed certificate, and this is causing a problem to build the package when fetching the source code.
Looks like that LuaJIT is changing from `https` to `http` as it can be seen in the following screenshots:
* If you browse the git repo configured on `msys2_repository_url` at [https://repo.or.cz/w/luajit-2.0.git](https://repo.or.cz/w/luajit-2.0.git), it is showing the `http` address in the homepage URL and repository URL:
* If you visit LuaJIT's GitHub mirror [https://github.com/LuaJIT/LuaJIT](https://github.com/LuaJIT/LuaJIT) and hover the link to LuaJIT website, …
> luajit: update to 2.1.1744318430

- mingw-w64-pyside6/003-skip-remote.patch
- mingw-w64-pyside6/PKGBUILD
```
C:\Windows\system32\cmd.exe /C "cd . && D:\M\msys64\ucrt64\bin\g++.exe -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wp,-D__USE_MINGW_ANSI_STDIO=1 -DNOMINMAX -Os -DNDEBUG  -Wl,--gc-sections -shared -o sources\pyside6\PySide6\QtRemoteObjects.cp312-mingw_x86_64_ucrt_gnu.pyd -Wl,--major-image-version,0,--minor-image-version,0 sources/pyside6/PySide6/QtRemoteObjects/CMakeFiles/QtRemoteObjects.dir/PySide6/QtRemoteObjects/qabstractitemmodelreplica_wrapper.cpp.obj sources/pyside6/PySide6/QtRemoteObjects/CMakeFiles/QtRemoteObjects.dir/PySide6/QtRemoteObjects/qconnectionabstractserver_wrapper.cpp.obj sources/pyside6/PySide6/QtRemoteObjects/CMakeFiles/QtRemoteObjects.dir/PySide6/QtRemoteObjects/qremoteobjectabstractpersistedstore_wrapper.cpp.obj …
```
> pyside6: Update to 6.9.0

- mingw-w64-mcfgthread/PKGBUILD
https://github.com/lhmouse/mcfgthread/releases/tag/v2.1-ga.1
> mcfgthread: Update to 2.1.1

- mingw-w64-gettext/0001-restore-DllMain-symbol.patch
- mingw-w64-gettext/PKGBUILD
> gettext: do not include DllMain symbol in the static build

- mingw-w64-nsis/010-fix-clang-rc-file.patch
- mingw-w64-nsis/012-fix-zlib-is-none-if-not-found.patch
- mingw-w64-nsis/PKGBUILD
* 010-fix-clang-rc-file.patch: refresh
* 012-fix-zlib-is-none-if-not-found.patch: fixes scons error if cppunit is installed env['ZLIB_W32_DLL'] is None there and is checked for everywhere except there
> nsis: Update to 3.11

- mingw-w64-gst-plugins-base/0001-fix-gcc15-compiler-error.patch
- mingw-w64-gst-plugins-base/PKGBUILD
This reverts the workaround from c25fe7e95fb27afdc25b82f80ac31f69061b8a4c commit.
> gst-plugins-base: Fix compiler error with gcc 15

- mingw-w64-fltk/PKGBUILD
According to FLTK develoeprs: https://www.fltk.org/articles.php?L1984
>  Its ABI and API are 100% backwards compatible with FLTK 1.4.0.
> fltk: update to 1.4.3

- mingw-w64-libshout/PKGBUILD
it picks up a gettimeofday which isn't there
> libshout: rebuild

- mingw-w64-ktx-software/PKGBUILD
This pr will add KTX-software, provides many command line tools and a library for building, testing, and viewing KTX (Khronos Texture) format.
Texts below are copied from their [website](https://www.khronos.org/ktx/):
KTX (Khronos Texture) is an efficient, lightweight container format for reliably distributing GPU textures to diverse platforms and applications. The contents of a KTX file can range from a simple base-level 2D texture to a cubemap array texture with mipmaps. KTX files hold all the parameters needed for efficient texture loading into 3D APIs such as OpenGL® and Vulkan®, including access to individual mipmap levels
> ktx-software: new package

- mingw-w64-hdf5/0005-fix-extracted-library-names.patch
- mingw-w64-hdf5/0006-link-static-libs.patch
- mingw-w64-hdf5/PKGBUILD
- mingw-w64-libaec/0001-export-targets-for-shared-and-static.patch
- mingw-w64-libaec/PKGBUILD
The static libraries were linking to the shared libaec libraries. Build the static and shared libraries separately to be able to link to the respective libaec libraries.
Fix extraction of library names that are used in pkg-config file for static linking.
> hdf5: fixes for static libraries

- mingw-w64-groonga/PKGBUILD
Groonga version15.0.9 has just released [here](https://github.com/groonga/groonga/releases/tag/v15.0.9).
> Groonga: Update to 15.0.9

- mingw-w64-img2pdf/PKGBUILD
* Losslessly convert raster images to PDF
> img2pdf: new package

- mingw-w64-gst-plugins-rs/PKGBUILD
Otherwise gtk4paintablesink is going to use (GSK) shader render nodes, which aren't supported anymore.
Cfr https://gitlab.archlinux.org/archlinux/packaging/packages/gst-plugins-rs/-/blob/main/PKGBUILD?ref_type=heads#L91
> gst-plugins-rs: Enable feature for newer GTK

- mingw-w64-freeimage/FreeImage-3.18.0_unbundle.patch
- mingw-w64-freeimage/PKGBUILD
This PR resolves this build error:
```
MINGW64 /b/mingw-w64-freeimage
==> Making package: mingw-w64-freeimage 3.18.0-14 (Wed, May 14, 2025  1:29:38 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Found FreeImage3180.zip
-> Found FreeImage-3.18.0_mingw-makefiles.patch
-> Found FreeImage-3.18.0_unbundle.patch
-> Found freeimage-libraw-0.20.patch
-> Found freeimage-libraw-0.21.patch
-> Found freeimage-libtiff-4.4.0.patch
==> Validating source files with sha256sums...
FreeImage3180.zip ... Passed
FreeImage-3.18.0_mingw-makefiles.patch ... Passed
FreeImage-3.18.0_unbundle.patch ... Passed
freeimage-libraw-0.20.patch ... Passed
freeimage-libraw-0.21.patch ... Passed
freeimage-libtiff-4.4.0.patch ... Passed
==> Extracting sources...
-> …
```
> freeimage: Add include <cstdint> to compile with GCC 15.1

- mingw-w64-pdcurses/PKGBUILD
- mingw-w64-pdcurses/pdcurses.changelog
Side question: is it ok to have the following long list in the commit log details, or should I drop that (if it should be reduced, then how)?
potential relevant changes since previous PDCursesMod 4.4.0 from [HISTORY.md](https://github.com/Bill-Gray/PDCursesMod/releases):
PDCursesMod 4.5.1- 2025 May 12
=============================
Minor new features
------------------
- `testcurs` now allows one to specify mouse mask parameters more precisely, and/or to set a zero mouse interval (which should result in clicks being converted to presses and releases).  Also,  can test using the ncurses mouse interface instead of the 'classic' undocumented SysV mouse interface.
Bug fixes
---------
- When restarting Curses,  the foreground/background weren't stored, resulting in odd colors.
- The ncurses …
> pdcurses: update to PDCursesMod 4.5.1

- mingw-w64-codeblocks/201-Build-Fix-compilation-with-MSYS2-GCC-15.1.patch
- mingw-w64-codeblocks/PKGBUILD
The provides helps to avoid future run-time issues with CB plugins like the FORTRAN plugin using a different base version of wxWidgets. The CB plugin needs to depend on the wxWidgets versioned of the Code::Blocks IDE. 
The maintainer rejected fixing the problem before it happens.
> codeblocks: patches gcc 15.x bug issue

- mingw-w64-llvm/PKGBUILD
This is to minimize toolchain installation size on clang* environments.
> llvm: split a new package llvm-tools

- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/bootstrap.toml
closes #24312
_Just for note:_ 
- [wams32-unknown-emscripten](https://doc.rust-lang.org/stable/rustc/platform-support/wasm32-unknown-emscripten.html)
- [Alon Zakai's Blog](https://kripken.github.io/blog/): [Small WebAssembly Binaries with Rust + Emscripten](https://kripken.github.io/blog/binaryen/2018/04/18/rust-emscripten.html)
Cc: @ognevny, @kripken, @hoodmane, @juntyr
> rust-wasm: add target wasm32-unknown-emscripten

- mingw-w64-fpm/PKGBUILD
- mingw-w64-fpm/fpm_0_12_0_gcc15_bugfix.patch
fpm v0.12.0 crashes due to a gcc-15.1 bug:
https://fortran-lang.discourse.group/t/error-building-csv-fortran-with-fpm/9760/5
Fix: patch source using https://github.com/fortran-lang/fpm/pull/1147/files
cc: @zoziha @MehdiChinoune
> fpm: add gcc15 patch

- mingw-w64-cbindgen/PKGBUILD
Reverts msys2/MINGW-packages#24326
it should be blocked on msys2/MSYS2-packages#5413
> Revert "cbindgen: update to 0.29.0"

- mingw-w64-cbindgen/PKGBUILD
blocked on https://github.com/msys2/MSYS2-packages/pull/5413
at one second I forgot about it when I merged previous PR
> cbindgen: update to 0.29.0

- mingw-w64-double-conversion/PKGBUILD
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```
This workaround can be removed on next release, following https://github.com/google/double-conversion/pull/246.
> double-conversion: Fix build with cmake 4

- mingw-w64-podman/PKGBUILD
the source of gvisor-tap-vsock version moved from the makefile to go.mod
> podman: Update to 5.5.0

- mingw-w64-curl/PKGBUILD
This curl release had a memory bug so we backport the patch right away.
> curl 8.14 + hotfix

- mingw-w64-gst-plugins-rs/PKGBUILD
this will reduce binaries' size (but for CLANG only)
update: actually package size reduced from 109.70 MiB
> gst-plugins-rs: rebuild for dynamic libunwind in CLANG

- mingw-w64-mesonlsp/PKGBUILD
the upstream repo was archived on March actually, so probably it worth to drop the package
> mesonlsp: rebuild to remove unneded deps

- mingw-w64-rustup/PKGBUILD
- depend on actually linked libraries
- use shared libunwind on CLANG
- don't build deprecated curl backend: https://github.com/rust-lang/rustup/blob/5cabb50dddf3cf77050df892d28aa32cd0a4159a/CHANGELOG.md?plain=1#L9
> rustup: various improvements

- mingw-w64-calceph/PKGBUILD
update to the minor version 4.0.5
> calceph: update to 4.0.5

- mingw-w64-emacs/004-gcc-15.patch
- mingw-w64-emacs/PKGBUILD
https://github.com/msys2/MINGW-packages/issues/17343#issuecomment-2368903501
The workaround is no longer necessary because the issue was fixed upstream.
> emacs: adapt to gcc 15 and remove obsolete workaround

- mingw-w64-ninja/0001-fix-manifest-build.patch
- mingw-w64-ninja/PKGBUILD
Fixes #24479
the static lib is gone now, but from what I understand that's private anyway
> ninja: build with cmake+make; fix missing manifest

- mingw-w64-cmake-bootstrap/PKGBUILD
Remove the ninja dep since we build ninja with cmake too now since https://github.com/msys2/MINGW-packages/pull/24505 and this avoids a cycle.
> cmake-bootstrap: Update to 4.0.2

- mingw-w64-emacs/PKGBUILD
The case for `read' was fixed upstream long time ago, but it seems that another function is affected by the same issue on newer versions of the runtime. Instead of playing whack-a-mole, simply remove -D_FORTIFY_SOURCE from now on.
Fixes https://github.com/msys2/MINGW-packages/issues/24539
> emacs: put back workaround for #17343

- mingw-w64-zed/PKGBUILD
rebuild with our protoc and with ld on GCC environments
locally tested UCRT64 artifact, anyone feel free to do the same (previous time it also succeeded for me but not for other users)
> zed: remove some workarounds

- mingw-w64-wxwidgets3.2/PKGBUILD
In preparation for wxWidgets 3.3.x release package
> mingw-w64-wxwidgets3.2: Edit/add provides and conflicts

- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/bootstrap.toml
this is then first Rust relase that downgrades i686-mingw target to tier 2. that means that std and host tools are guaranteed to build, but full test suite won't be run for this target: https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html#tier-2-target-policy. currently this doesn't mean that 32-bit Rust will be dropped soon, but now you should be aware of possible issues while using it as a host
config change: 
- remove crt-static option, it didn't do what expected (this will link libunwind dynamically for gnullvm tools)
@mati865 I guess removing stage0 hack for aarch64 gnullvm won't hurt, right? and I saw you put an effort to make gnullvm targets tier 2 with **host tools**, so we can truly bootstrap all the targets soon
> rust: update to 1.88.0

- mingw-w64-notepad++/PKGBUILD
see ReleaseNotes https://notepad-plus-plus.org/news/v882-fix-security-issue/
> notepad++: Update to 8.8.2

- mingw-w64-qt6-base/008-freetype-fonts-fallback-dir.patch
- mingw-w64-qt6-base/PKGBUILD
Use a more reasonable fallback directory for fonts on Windows. The existing fallback points to a directory that no longer exists by default which causes warnings like the following on run-time:
```
QFontDatabase: Cannot find font directory C:/msys64/mingw64/qt6/libs/fonts.
Note that Qt no longer ships fonts. Deploy some (from
https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
```
The change is motivated by reports from Octave users. The proposed change would affect *all* downstream users of `QFontDatabase` though (in a positive way - I think).
@MehdiChinoune, @lazka, others: Is this change acceptable?
Note: Qt6 doesn't support fontconfig for Windows.
> qt6-base: better fallback path for freetype

- mingw-w64-gtk4/PKGBUILD
Since GTK `4.18`, AccessKit a11y backend is available ([blog post about it](https://blog.gtk.org/2025/05/12/an-accessibility-update/)).
This PR enable `accesskit` during build of GTK4 so GTK4 applications can now have accessibility in Windows.
- Add `accesskit-c` as dependency
- Enable `accesskit` during build phase
Also, this was tested to make accessibility works for Gajim under Windows and is also documented here:
https://dev.gajim.org/gajim/gajim/-/issues/11147#note_218968
> [gtk4] Enable accesskit during build phase

- mingw-w64-angleproject/002-buildflags-fixes.patch
- mingw-w64-angleproject/004-swiftshader-updates.patch
- mingw-w64-angleproject/PKGBUILD
- mingw-w64-angleproject/angleproject.pc
The `libGLESv2.a` static library bundled with `mingw-w64-angleproject` has lots of undefined symbols, because its `libANGLE` dependency is not built as a static library, but as a group of objects that are linked directly in the shared DLL library. While this works if you are building with ANGLE sources, it have problems as a package. So these modifications bring the `libangle.a` static library, so we can link against `libGLESv2.a` without any missing dependency.
Additionally, this PR also brings the `angleproject.pc`, which allows using `pkg-config` to get all the required information about ANGLE's libraries.
> Static libraries fix and pkg-config .pc file for mingw-w64-angleproject package

- mingw-w64-podman-compose/PKGBUILD
Update podman-compose to version 1.5.0.
_(Also see #24762, the update for podman 5.5.2. Both updates should work independently from each other, but it's probably a good idea to handle them in the same run.)_
> podman-compose: update to 1.5.0

- mingw-w64-sfcgal/0001-fix-pc-missing-libdir.patch
- mingw-w64-sfcgal/PKGBUILD
In case of libtool this leads to:
libtool:   error: require no space between '-L' and '-lSFCGAL'
> sfcgal: fix .pc file missing libdir

- mingw-w64-qgis/PKGBUILD
Revert to Qt5 to make it build on UCRT64 as the compiler crashes unexpectedly with no error message.
the app now launches but only UCRT64.
> qgis: update to 3.44.0

- mingw-w64-python-asgiref/PKGBUILD
Update python-asgiref to 3.9.1.
> python-asgiref: update to 3.9.1

- mingw-w64-live-media/PKGBUILD
Update live-media to 2022.12.01.
There are newer versions of live-media, but this one builds without having to got through patches or adjusting the build logic. I figured having a small update, although not to the newest version, is still better than no update at all. However, I am not sure whether this is acceptable for you. If you feel differently, then you are free to reject this pull request.
> live-media: update to 2022.12.01

- mingw-w64-gcc/0001-libstdc-Search-for-tzdata-on-Windows-msys.patch
- mingw-w64-gcc/PKGBUILD
Instead of the hard compiled version shipped with gcc.
> GCC: use msys tzdata at runtime

- mingw-w64-python-rencode/0001-Remove-extra-compile-args.patch
- mingw-w64-python-rencode/PKGBUILD
Update python-rencode to 1.0.8.
Depends on python-pytest for checks, even in 1.0.6.
> python-rencode: update to 1.0.8

- mingw-w64-python-aiosignal/PKGBUILD
Required for https://github.com/msys2/MINGW-packages/pull/24787 to pass.
> python-aiosignal: Update to 1.4.0

- mingw-w64-ada-url/PKGBUILD
Not sure whether this is sufficient to get proper upstream version tracking, but it's a start.
> ada-url: add msys2_references

- mingw-w64-rust/PKGBUILD
This is to distinguish between [Rust](https://release-monitoring.org/project/7635/) and the [Rubygem of the same name](https://release-monitoring.org/project/129160/).
> rust: extend msys2_references

- mingw-w64-itk/PKGBUILD
~Both of the patches are now included upstream and are not required anymore.~
The patch from 4f275769e37fa29754166c7eded2d84c0b33991a.patch (https://github.com/InsightSoftwareConsortium/ITK/commit/4f275769e37fa29754166c7eded2d84c0b33991a) is now included in version 5.4.4 as commit with different hash, see https://github.com/InsightSoftwareConsortium/ITK/commit/9c87ac96d1f55bcda8bb40ed6ef17502ea19bd38.
> itk: update to 5.4.4

- mingw-w64-libxml2/0040-workaround-xmllint-stdin-error.patch
- mingw-w64-libxml2/PKGBUILD
When using xmllint for example.
Using this patch for now to fix the regression.
Might need adjustments, see upstream issue.
Fixes #24888
> libxml2: fix regression for parsing from stdin

- mingw-w64-pyinstaller-hooks-contrib/PKGBUILD
Includes [bugfix ](https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/927) especially for `MSYS2` environment
> pyinstaller-hooks-contrib: update to 2025.8

- mingw-w64-sqlite3/0005-dont-require-dlopen-on-windows.patch
- mingw-w64-sqlite3/0005-remove-dl-flags.patch
- mingw-w64-sqlite3/PKGBUILD
Followup to https://github.com/msys2/MINGW-packages/pull/24985
> sqlite: don't require dlopen on Windows

- mingw-w64-mongo-c-driver/PKGBUILD
Arch Linux also uses [mongo-c-driver](https://archlinux.org/packages/extra/x86_64/mongo-c-driver/) as package name.
> mongo-c-driver: rename from mongoc to mongo-c-driver

- mingw-w64-openimageio/PKGBUILD
Ah, needs https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4851 now...
> openimageio: update to 3.0.9.0

- mingw-w64-rust/.gitignore
- mingw-w64-rust/0014-rustc-perf-less-verbose.patch
- mingw-w64-rust/0015-lesser-llvm-build.patch
- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/bootstrap.toml
- perform PGO for rustc via opt-dist tool (addresses #19273):
- various backports (available in 1.90.0) to match our environment better and fix some bugs
- do not profile LLVM, because it makes backend performance even worse: https://github.com/rust-lang/rust/issues/144318
- on UCRT64 do a separate LLVM build with clang+lld so it will be linkable with PGOed rustc
- bootstrap.toml changes to match requirements for opt-dist (and get some more optimizations)
- CXXFLAGS workaround to actually perform LTO for llvm-wrapper (from rustc_llvm)
- ensure that clang+lld is used for whole build on non-i686
> rust: update to 1.89.0

- mingw-w64-rust-analyzer/PKGBUILD
I somehow missed previous version, and new version was untagged...
> rust-analyzer: update to 20250804

- mingw-w64-osm-gps-map/PKGBUILD
A few distros are already patching the same way as libsoup2 is insecure and there is no ETA on new release from upstram... E.g.:
https://salsa.debian.org/debian-gis-team/osm-gps-map/-/commit/d2224755698c9f57c18273601fe6239a0d290684
https://github.com/Homebrew/homebrew-core/blob/bccf5505eadeebe4195577c65b7b74564d23196b/Formula/o/osm-gps-map.rb
> osm-gps-map: switch to libsoup3

- mingw-w64-zed/.gitignore
- mingw-w64-zed/PKGBUILD
- remove backports
- drop MINGW64, now Zed requires symbols from UCRT
> zed: update to 0.199.6

- mingw-w64-glaze/PKGBUILD
This version adds a new option `glaze_BUILD_INTEROP`, but I'm getting [build errors](https://github.com/user-attachments/files/21856650/log.txt) with it enabled, so I've left it off.
> glaze: update to 5.6.0

- mingw-w64-lf/PKGBUILD
> lf: new, 31

- mingw-w64-lapack/PKGBUILD
Remove the headers from the lapacke64 package. They are provided by the lapacke package to which there already is an optional dependency.
> lapack: avoid file conflicts in packages

- mingw-w64-mman-win32/PKGBUILD
Adds the mman-win32 library for use under MinGW environments.
> Add mman-win32 library

- mingw-w64-gegl/0002-ffmpeg8.patch
- mingw-w64-gegl/PKGBUILD
Replace removed APIs with newer variants suggested in the deprecations:
* https://github.com/FFmpeg/FFmpeg/commit/7d1d61cc5f57708434ba720b03234b3dd93a4d1e
* https://github.com/FFmpeg/FFmpeg/commit/3e06f6f04020bef32fa42bc9d7f96e76a46453aa
> gegl: build fixes for ffmpeg 8

- mingw-w64-sequoia-sq/PKGBUILD
- bzip2 is linked only when bzip2-sys is patched
- use an environment variable to link sqlite3
> sequoia-sq: correct runtime dependencies

- mingw-w64-wasm-bindgen/Cargo.lock
- mingw-w64-wasm-bindgen/PKGBUILD
`winapi` crate is nuked from this package :partying_face:
> wasm-bindgen: update to 0.2.101

- mingw-w64-podman/PKGBUILD
This update addressed GHSA-wp3j-xq48-xpjw / CVE-2025-9566 in the podman package.
> podman: update to 5.6.1

- mingw-w64-rio/PKGBUILD
Maybe I've overdone it a bit with the package URLs, but all of them are in the Git repository of rio, so it's probably not wrong to have them there.
> rio: update to 0.2.29

- mingw-w64-kate-wakatime/PKGBUILD
[kate-wakatime project](https://github.com/Tatsh/kate-wakatime)
[Linked as an official plugin](https://wakatime.com/kate)
This is my plugin for Kate to send statistics to [WakaTime](https://wakatime.com/) or any compatible host like self-hosted [Wakapi](https://github.com/muety/wakapi).
Related: https://github.com/Tatsh/kate-wakatime/issues/49
> New package: kate-wakatime

- mingw-w64-abseil-cpp/PKGBUILD
Previously, the package would contain only the dynamically linked version of the libraries. This changes the build script to build both dynamic and static libraries.
Fixes: #17852
> Build both shared and static versions of the abseil libraries.

- mingw-w64-python-winloop/PKGBUILD
https://github.com/Vizonex/Winloop is _An Alternative library for uvloop compatibility with windows_ ...
It can be used by https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python-xpra to speed up the QUIC transport.
Support for MSYS2 was added in this PR: https://github.com/Vizonex/Winloop/pull/65
> new package: winloop

- mingw-w64-pgmodeler/PKGBUILD
It was linking against the libxml2 dll directly which breaks our current hack to remove DLLMain from the imports.
Adjust to use import libs.
> pgmodeler: link against import libs

- mingw-w64-pdal/PKGBUILD
Will probably need rebuilds for qgis and vtk.
Edit: package-grokker does not list any packages for rebuild - a surprise, but I'm not complaining.
> pdal: update to 2.9.2

- mingw-w64-python-django/PKGBUILD
See <https://www.djangoproject.com/weblog/2025/oct/01/security-releases/> (contains fixes for CVE-2025-59681 + CVE-2025-59682).
> python-django: update to 5.2.7

- mingw-w64-croc/PKGBUILD
croc is a command-line tool to enable easy file transfer from one computer to another.
It's packaged in
* [Arch Linux](https://archlinux.org/packages/extra/x86_64/croc/)
* [Gentoo](https://packages.gentoo.org/packages/net-misc/croc)
* [T2 SDE](https://t2linux.com/packages/croc)
* [Void Linux](https://github.com/void-linux/void-packages/blob/c5f6c4638e7bb6695c637ea8f0bf0b3a200cf4c9/srcpkgs/croc/template)
... and a few others.
> croc: new package

- mingw-w64-uutils-coreutils/PKGBUILD
Spliting build() sometimes cause building twice at make build.
Arch dropped `build()` even it is part packaging guideline.
(`cargo` only install is needed for proper packaging guideline.)
> uutils-coreutils: Avoid building twice
