msys2/MINGW-packages

- mingw-w64-allegro/PKGBUILD
Allegro 5 is licensed under ZLIB
http://alleg.sourceforge.net/license.html
https://en.wikipedia.org/wiki/Zlib_License#Text
https://wiki.archlinux.org/index.php/PKGBUILD#license
> Fix Allegro 5 License is ZLIB

- mingw-w64-cgal/PKGBUILD
- mingw-w64-cgal/convex_hull_fix.patch
See:
http://cgal-discuss.949826.n4.nabble.com/Epick-convex-hull-3-assertion-td4660264.html
Useful for openscad-git, which needs this patch.
> cgal: Add convex-hull fix patch

- mingw-w64-dmake/003-fix-config-location.patch
- mingw-w64-dmake/PKGBUILD
Configuration is now loaded from `/mingw*/etc/dmake` instead of `/mingw*/bin/startup`. Some testing:
$ mv /mingw32/etc/dmake .
$ dmake
dmake.exe:  Error: -- Configuration file `C:\MSYS2\mingw32\bin\..\etc\dmake\startup.mk' not found
$ mv dmake /mingw32/etc
$ dmake
sample makefile executed
> Fix configuration directory in dmake

- mingw-w64-osmgpsmap-git/PKGBUILD
osm-gps-map is a Gtk+ widget for displaying OpenStreetMap tiles
> New package: osmgpsmap-git

- mingw-w64-dmake/004-disable-mkstemp-detection.patch
- mingw-w64-dmake/PKGBUILD
- mingw-w64-perl/005-disable-custom-mkstemp.patch
- mingw-w64-perl/PKGBUILD
Perl should now build with new patch and after dmake is rebuilt. Test case for dmake:
echo $(shell echo "%USERPROFILE%")
echo $(SHELL)
> perl and dmake: Fix issues with mkstemp

- mingw-w64-breakpad-svn/Makefile
- mingw-w64-breakpad-svn/PKGBUILD
- mingw-w64-breakpad-svn/README.sample
Install windows-specific headers
Install sample so correct installation of library and headers can be validated
by trying to build it by running make in /mingw(32|64)/share/doc/breakpad/sample
> breakpad-svn: Install headers and sample

- mingw-w64-cyrus-sasl/PKGBUILD
This library was not included in the package anymore when OpenSSL was disabled. Now OpenSSL is still disabled, with reason provided in comments, but libdigestmd5 has been restored.
> cyrus-sasl: Restore libdigestmd5

- mingw-w64-python-ipython/0001-unimplemented-readline-calls.patch
- mingw-w64-python-ipython/PKGBUILD
Added an ipython package. Split package for python2/3. It works well for the most part, with one lingering issue:
I could only get prompt coloring to work when readline was enabled. However, by default ipython stops using readline when it tries and fails to call pyreadline's GetOutputFile()-- I guess the readline in mingw-w64-python doesnt have this function? I'm new to the platform so I don't know why this function would be missing, but from reading through the project history it looks like you guys have had your fair share of readline fun, so maybe one of you knows.
To fix this issue, I patched ipython to continue using readline but use the fallback IOStream whenever it would have used the outputfile. This works fine for ConEmu, but the built in msys2_shell.bat it won't display colored …
> python-ipython: Added (still has an issue with built in terminal)

- mingw-w64-gtk3/0056-fix-create-window-for-wintab.patch
- mingw-w64-gtk3/0057-wintab-dont-check-position-of-null-device.patch
- mingw-w64-gtk3/PKGBUILD
(Asking for this may be a little cheeky, but these are fixes we very much do want in the MyPaint camp. I'd understand if you say to just wait for 3.14.8.)
Backport upstream fixes for failed initialization of input devices which rely on wintab.dll, resulting in no pressure on tablets and Gdk-CRITICAL errors. Affects MyPaint, and will affect GIMP too.
https://bugzilla.gnome.org/show_bug.cgi?id=743330
https://github.com/mypaint/mypaint/issues/178
These will hopefully hit stable in 3.14.8, https://git.gnome.org/browse/gtk+/log/?h=gtk-3-14 , so please revert this patch when that arrives in MSYS2.
> gtk3: backport wintab fixes for missing pressure

- mingw-w64-openocd-git/PKGBUILD
This removes the patches since they're no longer needed, as the latest
git version merged the fixes.
This also changes pkgver() to use tags instead of plain rev-list
--count and removes the tricky renaming that should no longer be
needed.
Signed-off-by: Paul Fertser <fercerpav@gmail.com>
> openocd-git: remove patches included by upstream

- mingw-w64-atk/PKGBUILD
- mingw-w64-cairo/PKGBUILD
- mingw-w64-drmingw-git/PKGBUILD
- mingw-w64-drmingw/PKGBUILD
- mingw-w64-enchant/PKGBUILD
- mingw-w64-freetype/PKGBUILD
- mingw-w64-gcc/PKGBUILD
- mingw-w64-gdk-pixbuf2/PKGBUILD
- mingw-w64-gettext/PKGBUILD
- mingw-w64-glib2/PKGBUILD
- mingw-w64-gtk2/PKGBUILD
- mingw-w64-gtkspell/PKGBUILD
- mingw-w64-hunspell/PKGBUILD
- mingw-w64-libiconv/PKGBUILD
- mingw-w64-libxml2/PKGBUILD
- mingw-w64-meanwhile/PKGBUILD
- mingw-w64-pango/PKGBUILD
- mingw-w64-perl/PKGBUILD
- mingw-w64-shared-mime-info/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
Fixes and/or improvements for the packages below. See commit messages for more details.
* atk
* cairo
* drmingw
* drmingw-git
* enchant
* freetype
* gcc-libs
* gdk-pixbuf2
* gettext
* glib2
* gtk2
* gtkspell
* hunspell
* libiconv
* libxml2
* meanwhile
* pango
* perl
* shared-mime-info
* winpthreads-git
> More license fixes

- mingw-w64-gtk-doc/PKGBUILD
The `chunk.xsl` stylesheet is now imported from local file instead of HTTP. This
stylesheet is provided by the docbook-xsl package.
> gtk-doc: Update to 1.21

- mingw-w64-apr/PKGBUILD
- mingw-w64-apr/apr_ssize_t.patch
- mingw-w64-apr/apr_wtypes.patch
This isn't quite ready to be merged and is a work in progress.
The main problem that I'm running into are compilation timing issues that are resolved (somehow) by running *makepkg-mingw* again until it succeeds. There's also a couple tests that exhibit the same phenomenon. It is strange because (after a couple patches) it compiles and links normally in a MINGW64 shell.
After this is up and running I can submit *apr-util*.
> apr: Added

- mingw-w64-atom-editor/PKGBUILD
- mingw-w64-breakpad-svn/PKGBUILD
- mingw-w64-docbook-xsl/PKGBUILD
- mingw-w64-gtk2/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-libxml2/PKGBUILD
- mingw-w64-openshadinglanguage-git/PKGBUILD
- mingw-w64-python-docutils/PKGBUILD
- mingw-w64-speex/PKGBUILD
- mingw-w64-waf/PKGBUILD
* Some packages were using `${pkgname}` instead of `${_realname}` for license paths.
* libxml2: Remove the Copyright file as this is the same as COPYING.
* breakpad: Adjust maintainer/contributor lines.
* gtk2: Specify license as LGPL2.1+.
> Some small fixes

- mingw-w64-curl/PKGBUILD
configuring with gnutls is conflict with openssl or winssl option.
removing it should be safe.
> curl: add winssl variant

- mingw-w64-glib2/0028-inode_directory.patch
- mingw-w64-glib2/PKGBUILD
gio's g_content_type_from_mime_type ("inode/directory")
not working in windows so reverting that
> glib2: fix not showing folder icons in gtkfilechooserdialog

- mingw-w64-coq/0001-Guess-the-libraries-are-located-at-lib-coq-instead-o.patch
- mingw-w64-coq/PKGBUILD
- mingw-w64-flexdll/0001-Fix-the-List.hd-exception.patch
- mingw-w64-flexdll/0002-Add-path-to-libcrt2.o-into-the-default-library-searc.patch
- mingw-w64-flexdll/0003-Remove-the-usages-of-stdout-to-workaround-the-missin.patch
- mingw-w64-flexdll/PKGBUILD
- mingw-w64-libart_lgpl/0001-Fix-an-installation-path-bug.patch
- mingw-w64-libart_lgpl/PKGBUILD
- mingw-w64-libart_lgpl/libart_lgpl-2.3.19-upstream_fix-1.patch
- mingw-w64-libgnomecanvas/PKGBUILD
- mingw-w64-ocaml-camlp4/0001-Properly-quote-preprocessor-command-to-ocamldep.patch
- mingw-w64-ocaml-camlp4/0002-Add-DESTDIR-in-configure.patch
- mingw-w64-ocaml-camlp4/PKGBUILD
- mingw-w64-ocaml-findlib/PKGBUILD
- mingw-w64-ocaml-lablgtk/0001-Fix-a-path-issue-during-installation.patch
- mingw-w64-ocaml-lablgtk/PKGBUILD
- mingw-w64-ocaml/0001-Rename-Makefile.mingw-to-Makefile.mingw32.patch
- mingw-w64-ocaml/0002-Adapt-to-msys2-directory-layout.patch
- mingw-w64-ocaml/0003-Install-manuals-in-msys2.patch
- mingw-w64-ocaml/0004-camlheader-has-the-extension-.exe-in-msys2.patch
- mingw-w64-ocaml/0005-Install-libraries-to-lib-ocaml-instead-of-lib.patch
- mingw-w64-ocaml/PKGBUILD
Known issues:
* Flexdll and ocaml depends on each other and thus need prebuilt packages to kick off the build. My packages can be found at https://github.com/eternalNight/MINGW-packages/raw/master/_bin/mingw-w64-i686-flexdll-0.31-1-any.pkg.tar.xz and https://github.com/eternalNight/MINGW-packages/raw/master/_bin/mingw-w64-x86_64-flexdll-0.31-1-any.pkg.tar.xz.
* When OCaml toplevel is killed by Ctrl-C, bash stops responding after displaying the "$" prompt. A normal quit from the toplevel does not trigger the issue.
> Add coq and its dependencies

- mingw-w64-lua-lpeg/PKGBUILD
- mingw-w64-lua-lpeg/lptypes-lua-503.patch
Because of the update of lua to version 5.3 (see #540) lua-lpeg needs to be updated
Changes:
* Changed directories for "lpeg.dll" and "re.lua"
* Enabled compatibility-defines for lua 5.2 also for later version of lua
* Added compatiblity-defines because of a rename in lua 5.3 ("luaL_checkint" -> "luaL_checkinteger")
> lua-lpeg: updated for lua 5.3

- mingw-w64-coq/PKGBUILD
- mingw-w64-flexdll/0004-use-lib-flexdll-as-the-default-library-path.patch
- mingw-w64-flexdll/PKGBUILD
- mingw-w64-ocaml-camlp4/0003-Guess-the-library-path-on-msys2.patch
- mingw-w64-ocaml-camlp4/PKGBUILD
- mingw-w64-ocaml/0006-Configure-the-relative-paths-for-ocaml-libraries-on-.patch
- mingw-w64-ocaml/0007-Convert-to-windows-path-before-checking-stats.patch
- mingw-w64-ocaml/PKGBUILD
I've add some patches to allow flexdll, ocaml and camlp4 to guess the paths of their libraries. The patchset can be found at https://github.com/eternalNight/MINGW-packages/tree/for-alexpux.
By the way, flexdll has been updated to 0.34 to fix a bug on 64bit systems. The binary packages to kick off the build can be found at https://github.com/eternalNight/MINGW-packages/tree/master/_bin.
However, lablgtk is broken after the update. I have fired an issue to the flexdll developers and am waiting for their response. As a result, I have to remove coqide support from the coq package temporarily due to it dependency on lablgtk. Please ignore ocaml-lablgtk for now. Thanks!
> Guess library path in ocaml, camlp4 and flexdll

- mingw-w64-sed/PKGBUILD
- mingw-w64-sed/msvc_invalid_parameter_handler.patch
A build of GNU sed for native Windows. The only dependency is libintl, and as far as I can see other packages don't explicitly declare a dependency on libintl, so I omitted that.
> New package sed

- mingw-w64-xalan-c/PKGBUILD
Minor patch to fix dependency problem because xerces-c has been updated to 3.1.2
> Fix xerces-c dependency in xalan-c

- mingw-w64-nettle/0001-fix-GMP_NUMB_BITS-check.patch
- mingw-w64-nettle/PKGBUILD
This patch enables ecc-224-modp.asm and ecc-521-modp.asm optimizations under win64
> nettle: Fix GMP_NUMB_BITS check in configure.ac

- mingw-w64-ocaml/PKGBUILD
The 0009 patch is not necessary any more as the ld.conf path issue is now resolved by a post-install routine.
Signed-off-by: Junjie Mao <eternal.n08@gmail.com>
> ocaml: remove the temporary patch during development

- mingw-w64-ca-certificates/ca-certificates-i686.install
- mingw-w64-ca-certificates/ca-certificates-x86_64.install
- mingw-w64-p11-kit/0011-p11-kit-spawn-external.patch
- mingw-w64-p11-kit/PKGBUILD
This fixes files not being written before p11-kit exits.
> Make p11-kit use spawn instead of exec to call external helper programs

- mingw-w64-jbigkit/PKGBUILD
- mingw-w64-libjpeg-turbo/PKGBUILD
- mingw-w64-libtiff/PKGBUILD
- mingw-w64-wxwidgets/PKGBUILD
- mingw-w64-xz/PKGBUILD
* Improve license fields.
* Install missing license files.
* Build wxWidgets without libtiff to avoid GPL infection. A better fix though is reverting 1806f3e because that turns libtiff and thus wxWidgets into GPL2-only.
> Licensing improvements for some packages

- mingw-w64-curl/PKGBUILD
SSPI support is necessary e.g. when accessing a TFS repository
and wants to use the credentials of the currently logged in user
via Windows Authentication (a sort of Kerberos):
git clone http://:@server/tfs/COLLECTION/TeamProject/_git/repo
or
git clone -c core.askpass=true http://server/tfs/COLLECTION/TeamProject/_git/repo
This fixes https://github.com/git-for-windows/git/issues/92
Signed-off-by: Ivo Bellin Salarin
> Include SSPI support in curl

- mingw-w64-scite/PKGBUILD
I also changed a dependency of the split "slave" package to require the same version of the "master" package
> scite: Updated to v3.5.5 (fixes wrap issue)

- mingw-w64-libiconv/PKGBUILD
There is a bug in MSYS2 where if someone wants to use the iconv program by installing libiconv, the program will fail without explanation when gettext is not installed. This is because gettext is not listed as dependency of libiconv, because libiconv is already a dependency for gettext, thus avoiding pacman warnings.
The circular dependency consists of gettext using libiconv for encoding conversion, and libiconv using gettext for translation of the iconv program. The libiconv package has been split into two separate packages to fix this:
* libiconv now contains only the library
* iconv is a new package containing the program
> Fix circular dependency between libiconv and gettext

- mingw-w64-gdal/PKGBUILD
- mingw-w64-libspatialite/PKGBUILD
- mingw-w64-spatialite-tools/PKGBUILD
When I installed mingw-w64-x86_64-gdal package , 
```
gdalinfo --formats
```
was giving missing dll erros. I have added the missing ``json-c`` and ``openjpeg2`` to dependencies
(it is also feels better to rebuild gdal package with updated libspatialite from https://github.com/Alexpux/MINGW-packages/pull/601 )
> GDAL: Add more libs to dependencies

- mingw-w64-libspatialite/PKGBUILD
- mingw-w64-spatialite-tools/PKGBUILD
The current version of spatialite packages gives the following errors:
```
$ pacman -S mingw-w64-x86_64-spatialite-tools
....
$ spatialite
SQLite header and source version mismatch
2015-04-08 12:16:33 8a8ffc862e96f57aa698f93de10dee28e69f6e09
2014-10-17 11:24:17 e4ab094f8afce0817f4074e823fabe59fc29ebb4
```
I guess this is because sqlite3 was updated.
Simple rebuilding the packages with mingw-package helped. Should we increase the versions?
> libpatialite, spatialite-tools: rebuild with newer sqlite3

- mingw-w64-curl/PKGBUILD
[Bugfixes][1]:
CURLOPT_HEADEROPT: default to separate
dist: include {src,lib}/checksrc.whitelist
connectionexists: fix build without NTLM
docs: distribute the CURLOPT_PINNEDPUBLICKEY man page, too
curl -z: do not write empty file on unmet condition
openssl: fix serial number output
curl_easy_getinfo.3: document 'internals' in CURLINFO_TLS_SESSION
sws: init http2 state properly
curl.1: fix typo 
[1]: http://curl.haxx.se/changes.html#7_42_1
> curl: Update to 7.42.1

- mingw-w64-emacs-git/PKGBUILD
- mingw-w64-emacs/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
-   Fixed dependencies;
-   Fixed problem with `-funroll-loops`;
-   Made source browsing available;
-   Fixed style inconsistencies;
-   Improved Windows POSIX Threads `PKGBUILD` a bit.
> emacs: Update

- mingw-w64-libsodium/PKGBUILD
Didn't test the 2 packages in repo requiring this but there is no soname bump so should be good to go :)
> libsodium: bump to 1.0.2

- mingw-w64-curl/0003-curl-mingw-text-mode-for-netrc.patch
- mingw-w64-curl/PKGBUILD
Open it in text mode to avoid considering CR as part of the line
> curl: Fix netrc parsing on Windows

- mingw-w64-clang-svn/0001-Add-Clang-MinGW-w64-driver.patch
splitDebugName signature has changed recently.
> clang_svn: splitDebugName signature has changed

- mingw-w64-armadillo/0001-mingw-config-fix.patch
- mingw-w64-armadillo/PKGBUILD
- mingw-w64-armadillo/armadillo-i686.install
- mingw-w64-armadillo/armadillo-x86_64.install
List of changes
- use optimized openblas lapack implementation instead of the netlib lapack
- fix dependencies
- fix build directory
- call make in build()
- add patch to set appropriate default settings in config.hpp
- fix cmake scripts
- install docs and license file
> armadillo: Fixes and refinements

- mingw-w64-ragel/PKGBUILD
It is based on:
* https://github.com/KaOS-Community-Packages/ragel/blob/master/PKGBUILD
* https://github.com/johnbartholomew/pkgbuilds/blob/master/ragel/PKGBUILD
And it works well locally in order to compile a library I wanted to use this for.
First proposed as a msys2 package [here](https://github.com/Alexpux/MSYS2-packages/pull/254).
> Add ragel as a tool

- mingw-w64-jq/PKGBUILD
Name           : mingw-w64-x86_64-jq
Version        : 1.4-1
Description    : Command-line JSON processor (mingw-w64)
Architecture   : any
URL            : http://stedolan.github.io/jq/
Licenses       : MIT
> jq: New package

- mingw-w64-tesseract-ocr/PKGBUILD
1. msys2 patches have already been applied in 3.04 rc1
2. change to use the current version from master branch
3. "We transferred code to https://github.com/tesseract-ocr/ and it looks like 3.04 release is very close. So this is the best time for testing and patching build/packaging system especially, it they want to have it in official release. Of course other patches are welcomed too."
> Prepare for upcoming 3.04 release of Tesseract-OCR

- mingw-w64-drmingw-git/PKGBUILD
Current Dr. MinGW packages do not work at all with separate debug symbols. This new version makes `.gnu_debuglink` work again in the git variant.
> Fix separate debug symbols in drmingw-git

- mingw-w64-gegl-git/PKGBUILD
* Added json-glib as a dependency to fix issue #656.
* Added intltool as a build dependency (it provides IT_PROG_INTLTOOL).
* Fixed the broken link to the project website.
> gegl-git fixes

- mingw-w64-win7appid/.gitignore
- mingw-w64-win7appid/LICENSE.txt
- mingw-w64-win7appid/PKGBUILD
- mingw-w64-win7appid/win7appid.1
win7appid is a very small, handy utility for setting the "App ID" of a shortcut file.  So I thought it might be nice to have a package for it.  I also converted the front page of the project's website into a man page!  
I use this tool on my pinned MSYS2 shortcuts in order to make my MSYS2 mintty windows get grouped under the pinned icon.  (I also have to [patch](https://gist.github.com/DavidEGrayson/30066232eb21c0c1492a) msys2/*.bat in order to set the same App ID on the mintty Windows.)
> Added win7appid package.

- mingw-w64-x265/PKGBUILD
The dll is for applications which can use x265 multi-library interface.
e.g. x265.exe and ffmpeg.exe.
> x265: Install 10 bit-depth dll (libx265_main10.dll).

- mingw-w64-drmingw-git/PKGBUILD
- mingw-w64-drmingw/PKGBUILD
* Fix duplicated license installation.
* Convert markdown readme to HTML.
> Some documentation fixes for Dr. MinGW

- mingw-w64-mpv/0001-Revert-win32-fix-desktop-directory.patch
- mingw-w64-mpv/PKGBUILD
This comes with a few changes:
- The Lua dependency has been fixed. mpv doesn't support Lua 5.3.
- librubberband is added as a dependency.
- libmpg123 has been removed (mpv no longer supports it.)
- LADSPA has been explicitly disabled. mpv auto-detects it, but it doesn't work on Windows yet because it relies on \<dlfcn.h>. af_ladspa is probably not important enough to add a dependency to dlfcn-win32 (it's disabled in the official builds as well.)
- A patch is included to fix a bad merge on mpv's release branch.
> mpv: Update to 0.9.2

- mingw-w64-mpv/PKGBUILD
I forgot this change, sorry. mpv 0.9.x uses an environment variable to determine whether it was started from the console wrapper (mpv.com.) The winpty wrapper also needs to set this for terminal input/output to work properly.
> Fix winpty wrapper for mpv 0.9.x

- mingw-w64-catch/PKGBUILD
This pull request updates the Catch package to version 1.2.0.  As of today, Catch now uses semantic versioning and git tags, so I was able to improve the script to use the tag instead of using the "develop" branch.
> catch: Update to 1.2.0.

- mingw-w64-drmingw/PKGBUILD
- mingw-w64-drmingw/install-files.patch
This fixes import library for release-based flavor since 0.7.4 now provides the missing exchndl header.
> Update Dr. MinGW to latest

- mingw-w64-openssl/PKGBUILD
- mingw-w64-openssl/openssl-0.9.6-x509.patch
- mingw-w64-openssl/openssl-1.0.0a-ldflags.patch
- mingw-w64-openssl/openssl-1.0.0d-windres.patch
- mingw-w64-openssl/openssl-1.0.1-x32.patch
- mingw-w64-openssl/openssl-1.0.1i-relocation.patch
- mingw-w64-openssl/openssl-1.0.2a-parallel-build.patch
Updated Openssl to Version 1.0.2d
This release is a fix of CVE-2015-1793
Changes: 
* updated version number
* fixed patches
* updated md5 sums
> Updated Openssl to Version 1.0.2d

- mingw-w64-libtool/0008-tests.patch
- mingw-w64-libtool/PKGBUILD
Here are some (really ugly) fixes for the libtool test suite so that the tests will succeed under the MinGW-W64 build environment. I am particularly not proud of the one in mdemo.at; I tried at length to determine what was causing the crash but I couldn't figure it out. The tests don't run by default since they take a very long time, but at least if someone wants to run them then this patch will enable them to do so.
I also split the package into libtool and libltdl, since it was that way in the MSYS2 repo.
> libtool: fix tests

- mingw-w64-aspell-es/001-unixy-dirs.patch
- mingw-w64-aspell-es/PKGBUILD
The generated pkg name contain the full upstream version (1.11-2). (See `pkgver` assignment). This differs from what Alexey did on `aspell-en`, but IMO it is more correct to include the full upstream version on the generated pkg file name.
> aspell-es: New package

- mingw-w64-ffmpeg/PKGBUILD
This enables lossless DTS-HD MA decoding in FFmpeg. mpv in particular will prefer libdcadec over FFmpeg's internal DTS decoder when it's available.
> ffmpeg: Use libdcadec

- mingw-w64-libidn/PKGBUILD
Passing --disable-rpath prevents -R/mingw{32,64}/lib from showing up in libidn's pkg-config file.
> Disable rpath in libidn to keep -R flags out of pkg-config.

- mingw-w64-fontconfig/PKGBUILD
Fontconfig isn't passing in a prefix-based library path when attempting to check for libiconv causing detection to fail.  Configuring it with --with-libiconv corrects this.
> Fontconfig doesn't pass in a library directory when checking for libiconv

- mingw-w64-xz-git/PKGBUILD
My fault, I didn't test git repository URL since I used --noextract in Travis CI. Sorry for my mistake.
> xz-git: Fix git repository URL.

- mingw-w64-connect/PKGBUILD
The connect.exe helper is a very useful helper when trying to connect to
SSH through a SOCKS or HTTP proxy.
It comes in particularly handy when users are stuck behind restrictive
firewalls. If even one HTTP proxy is accessible that allows to connect to
port 22 of the desired outside machine, `connect.exe` can be used in
conjunction with the `ProxyCommand` directive in `$HOME/.ssh/config` to
allow regular ssh and scp connections. Example:
-- snippet of $HOME/.ssh/config --
Host github.com
User git
ProxyCommand connect -H proxy.local.net:8080 %h %p
-- end snippet
If a SOCKS proxy is available, the same directive works when `-H` is
replaced with the `-S` option.
> Add the mingw-w64-connect package

- mingw-w64-clang/PKGBUILD
Without groff build failed
```
llvm[2]: Installing MAN Clang Tools Documentation
groff -Tps -man /MINGW-packages/mingw-w64-clang/src/build-x86_64-w64-mingw32/tools/clang/docs/tools/clang.1 > /MINGW-packages/mingw-w64-clang/src/build-x86_64-w64-mingw32/tools/clang/docs/tools/clang.ps
/bin/sh: groff: command not found
Makefile:76: recipe for target '/MINGW-packages/mingw-w64-clang/src/build-x86_64-w64-mingw32/tools/clang/docs/tools/clang.ps' failed
```
> Add groff dependency in clang

- mingw-w64-aspell-de/001-unixy-dirs.patch
- mingw-w64-aspell-de/PKGBUILD
- mingw-w64-aspell-fr/001-unixy-dirs.patch
- mingw-w64-aspell-fr/PKGBUILD
The packages for the German and French aspell dictionaries proposed in this pull request were created by adjusting the PKGBUILD script and associated patch of the English aspell dictionary package. The packages build, install, and uninstall fine on an up-to-date MSYS2 installation using the MinGW-W64 toolchains for i686 and x86_64 on Windows 7. The dictionaries have been tested using the aspell integration in Emacs flyspell-mode.
> German and French aspell dictionary packages

- mingw-w64-msmtp/0001-include-winsock2.patch
- mingw-w64-msmtp/0002-dont-redefine-winver-constant.patch
- mingw-w64-msmtp/PKGBUILD
This package provides a minimal SMTP client for use in the command-line and in shell scripts. We used to ship this with Git for Windows 1.x and the plan is to ship it with 2.x again, providing support for sending patches as mails directly via SMTP.
This was lightly tested by sending two (unencrypted) mails. (Successfully, of course.)
> Add the msmtp package

- mingw-w64-universal-ctags-git/PKGBUILD
This is a maintained fork of Exuberant Ctags, which is already present as a MinGW-package.
As Exuberant Ctags is virtually unmaintained for several years, and Universal Ctags includes lots of fixes and new features over Exuberant Ctags, I suggest to build and provide a binary package.
> universal-ctags-git: New package

- mingw-w64-xpdf/PKGBUILD
This package only contains the utilities (pdfimages, pdftotext, etc) but
not the viewer because Xpdf's viewer works only with X11.
> Add the Xpdf package

- mingw-w64-gettext/121-keep-posix-path.patch
- mingw-w64-gettext/PKGBUILD
The `libintl-8.dll` file from mingw-w64-x86_64-gettext 0.19.5.1-1 has
the path `D:/develop/msys64/mingw64/share/locale` hard-coded. As a
consequence, programs that link to libintl-8.dll may try to open said
directory. In many setups, `D:\` actually refers to a CD/DVD drive which
means that the user may see this nasty error message:
There is no disk in the drive. Please insert a disk into drive D:
Let's not do that, but instead hard-code the *POSIX* path into that
`.dll` file, i.e. `/mingw64/share/locale`.
This fixes https://github.com/git-for-windows/git/issues/329
> Do not hard-code DOS paths in libintl-8.dll

- mingw-w64-glbinding/PKGBUILD
Package had single quotes in source URL so `${pkgver}` wasn't expanded in the string. Also I fixed documentation installation.
> glbinding: Fix the package URL, install the documentation

- mingw-w64-antiword/PKGBUILD
[Antiword](http://www.winfield.demon.nl/) is a free MS Word reader for Linux and RISC OS. There are ports to FreeBSD, BeOS, OS/2, Mac OS X, Amiga, VMS, NetWare, Plan9, EPOC, Zaurus PDA, MorphOS, Tru64/OSF, Minix, Solaris and DOS. Antiword converts the binary files from Word 2, 6, 7, 97, 2000, 2002 and 2003 to plain text and to PostScript. It simplifies comparison between two Word documents.
`makepkg-mingw -s` has slight trouble building this package, because `bsdtar` doesn't handle symlinks properly. This results in `makepkg-mingw -s` reproducible failing on the first try to build Antiword and succeeding on the second run. I could introduce a [workaroundby using GNU `tar`](https://bbs.archlinux.org/viewtopic.php?id=70030) if you think that's better.
> Add the Antiword Package

- mingw-w64-mbedtls/PKGBUILD
- mingw-w64-mbedtls/dll-location.patch
- mingw-w64-mbedtls/symlink-test.patch
mbed TLS is an open source and commercial SSL library licensed by ARM
Limited.
There are 2 versions of this library: GPLv2 licensed and Apache 2.0. I packaged the Apache 2.0 one because it is their main license. This package builds static and shared libraries. Upstream doesn't provide `Config.cmake` file, should I try to create one?. Also I am not sure if I put the documentation in correct place.
> Add the mbedtls package.

- mingw-w64-curl/0003-curl-detect-ipv6-on-windows.patch
- mingw-w64-curl/PKGBUILD
The support is already there, of course, it was just not auto-detected
correctly.
This fixes https://github.com/git-for-windows/git/issues/370
> curl: enable IPv6 support

- mingw-w64-python-nuitka/PKGBUILD
There's a new upstream version [available](http://nuitka.net/pages/download.html): 0.5.14.3. Could mingw-w64-python-nuitka be updated please?
Branch contains a fix for #788 that gets it running on my system, but it's otherwise untested.
(I'll assume setuptools alone should be responsible for the `#!` line.)
> Nuitka: update to 0.5.14.3, fix #788

- mingw-w64-mbedtls/PKGBUILD
A bugfix release, patch notes [here](https://tls.mbed.org/tech-updates/releases/mbedtls-2.1.1-and-1.3.13-and-polarssl-1.2.16-released).
> mbedtls: Update to version 2.1.1

- mingw-w64-usbview/01-strsafe-after-tchar.patch
- mingw-w64-usbview/02-sal.patch
- mingw-w64-usbview/03-resource-fix.patch
- mingw-w64-usbview/PKGBUILD
- mingw-w64-usbview/my_xmlhelper.c
This pull request adds a package for usbview, a sample GUI application from Microsoft that shows interesting information about connected USB controllers and devices.
Three caveats:
* It uses an older ZIP file from Microsoft's website because the [latest one on github](https://github.com/Microsoft/Windows-driver-samples/tree/master/usb/usbview) cannot yet be compiled with mingw-w64 because of some missing structs/typedefs.  I will probably submit patches to mingw-w64 so we can eventually compile it.
* It compiles with warnings because of macro redefinitions and arrays that are assumed to have one element.
* xmlhelper.cpp uses .NET, so this package replaces it with a dummy file that just shows an error message.  This build will not be able to save data as an XML file.
If either of these …
> Added mingw-w64-usbview.

- mingw-w64-mbedtls/PKGBUILD
- mingw-w64-mbedtls/enable-features.patch
Also disable zlib support because it is not used, because TLS compression is
unsafe (CRIME). Remove dummy error reporting function.
Is SSE2 common enough to keep it enabled (on both i686 and x86_64)? If not I can move it into a separate patch.
> mbedtls: Enable SSE2 and threading support via pthread.

- mingw-w64-antiword/0001-Make-antiword.exe-relocatable-on-Windows.patch
- mingw-w64-antiword/PKGBUILD
Unfortunately, I had tested antiword only lightly before it was submitted. A very important part of `antiword` is to handle encodings, and those mapping files are in the `share/` directory. Sadly, antiword had no code to make itself relocatable, therefore I taught it this new trick.
> Fix antiword by making it relocatable

- mingw-w64-curl/0004-NTLM-Reset-auth-done-when-using-a-fresh-connection.patch
- mingw-w64-curl/PKGBUILD
Under certain circumstances, an NTLM proxy connection will be reused.
If that is the case, the state of the authentication needs to be
handled properly.
There is a bug in cURL 7.44.0 that has been fixed in cURL's `master`
already (https://github.com/bagder/curl/commit/f65e07ca5) and this
patch backports it.
This fixes https://github.com/git-for-windows/git/issues/373
> curl: fix NTLM proxy when reusing connection

- mingw-w64-libass/PKGBUILD
This adds DirectWrite font selection, so fontconfig is now only needed for Windows XP. Also, the enca dependency was dropped and the PKGBUILD was changed to use the release tarball (Arch did this as well.)
> libass: Update to 0.13.0

- mingw-w64-gtk3/PKGBUILD
Repeatedly re-running prepare() was causing /usr/bin/patch to brokenly
append 0056-missing-file-toarray-pl.patch's "+" lines to toarray.pl every
time, with a mangled "#!" line half-way through the resultant mess.
Surprisingly, this line noise is invalid Perl syntax.
The broken "#!" line problem was seemingly caused by a lack of the "-n"
flag to echo, but for some reason the redirection itself was not blanking
the file at all. There's some weird underlying bug here, but the workaround
is to remove the previously created file on each prepare().
> gtk3: fix bad patch reapply that breaks toarray.pl

- mingw-w64-mbedtls/PKGBUILD
8 security patches, 1 bugfix
Changelog: https://tls.mbed.org/tech-updates/releases/mbedtls-2.1.2-and-1.3.14-and-polarssl-1.2.17-released
Should I use SHA-256 checksums? I don't know if I SHA-1 is good enough, since `gnutls` and `openssl` package both use PGP key. Upstream doesn't PGP sign their relases.
> mbedtls: Update to 2.1.2

- mingw-w64-gdk-pixbuf2/PKGBUILD
OS-specific auto-detections for this were dropped upstream,
so a configure-time enable flag is needed now.
Without this, the SVG module cannot be loaded correctly at runtime.
Closes Alexpux/MINGW-packages#818.
> gdk-pixbuf2: enable relocations

- mingw-w64-confuse/PKGBUILD
Thanks to some recent pull requests of mine, this library can be compiled and tested totally fine on MSYS2.  I'm interested in adding an MSYS2 package for it because it is an optional dependency of libftdi, which is an optional dependency of avrdude.
I'm not sure why, but the arch package name is [confuse](https://www.archlinux.org/packages/community/x86_64/confuse/) instead of "libconfuse", so I copied their naming.
> New package: confuse

- mingw-w64-gtk3/0080-backport-notebook-tab-drag-fixes.patch
- mingw-w64-gtk3/PKGBUILD
Fix some crashes seen when dragging tabs out of a notebook widget.
On the win32 backend, the second or later attempt to drag a tab out of
a GtkNotebook supporting reordering of tabs would segfault.
https://bugzilla.gnome.org/show_bug.cgi?id=756160
This commit backports the upstream fixes below onto GTK 3.18.2.
These will hopefully be incorporated into the release after 3.18.2,
so this commit can be reverted when MINGW-packages builds GTK >= 3.18.3.
1. 00b39e4a82401f407a2df2e2e35a18ede88b41ea
"W32: Add missing reference taking in gdk_device_virtual_grab()"
2. c8604923598aad745a65ec16eb79113c97649345
"Clean up handling of _gdk_win32_grab_cursor".
3. 25483304cdc967c374a435200416affb573583f8
"Minor cleanup. Replace a unref-and-unset combination with g_clear_object."
> gtk3: backport fixes for notebook tab-drag crashes

- mingw-w64-gdk-pixbuf2/0002-gdk-pixbuf-introspection.patch
- mingw-w64-gdk-pixbuf2/PKGBUILD
This fix utf8 support functions in typelib, without that pixbuf2 can only work with paths which have ascii characters
> gdk-pixbuf2: introspection patch

- mingw-w64-python-setuptools/PKGBUILD
Disclaimer:  I don't fully understand how python-setuptools works and I am having some weird issues where pip thinks that version 18.3.2 is installed, even though I installed my 18.4 package.  However, this pull request only changes a version number and a checksum, and I think it will help out users who try to install pips using the `-U` option, e.g. `pip install -U cryptography`.  I was discussing this problem here:
https://github.com/ARMmbed/yotta_windows_installer/issues/13#issuecomment-149430588
> python-setuptools: Update to 18.4.

- mingw-w64-gtk3/0090-backport-fix-introspection-syntax.patch
- mingw-w64-gtk3/PKGBUILD
Backport upstream's fix for a syntax error (missing colon) in the annotations.
https://git.gnome.org/browse/gtk+/commit/?id=f703ea65995f4c8bd5c7e1c554a36d5ca835067d
This doesn't address Alexpux/MINGW-packages#845, but it's probably worth having in our builds.
> gtk3: backport an upsteam GI syntax fix

- mingw-w64-SDL2_mixer/PKGBUILD
- mingw-w64-SDL_mixer/PKGBUILD
Build the SDL*_mixer libraries against libmad instead of smpeg for
MP3 playback. The libmad backend is much more popular and the smpeg
backend reportedly caused issues for e.g. Doom Retro:
bradharding/doomretro@fda2fe3 .
Fixes https://github.com/Alexpux/MINGW-packages/issues/863
NB: The libmad library is licensed under the GPL, so linking against
this dependency will effectively turn the whole SDL*_mixer libraries
GPL licensed.
NB2: Should we ever have to autoreconf the source tree, we might want
to add the dependency on *-smpeg back (though unused) for the mere
presence of the macros in the smpeg.m4 file.
> SDL*_mixer: build against libmad instead of smpeg

- mingw-w64-glib2/PKGBUILD
This also fixes a segfault with 32bit applications.
> glib2: update to version 2.46.2

- mingw-w64-SDL2_mixer/PKGBUILD
- mingw-w64-SDL2_mixer/SDL2_mixer-find_lib.mingw.patch
- mingw-w64-SDL_mixer/PKGBUILD
- mingw-w64-SDL_mixer/SDL_mixer-find_lib.mingw.patch
This avoids hard dependencies against the libraries providing the
music backends (with the exception of libmad). Instead, if the
libraries are found in the search path, they are loaded as plug-ins at
run-time.
Fixes https://github.com/Alexpux/MINGW-packages/issues/865
First, the ./configure script did check only for $host being
*-mingw32*, so it skipped the relevant parts for $host=*-mingw64*.
Then, the ./configure script did check for the wrong library names for
both libfluidsynth*.dll and ibvorbisidec*.dll.
Finally, the find_lib() function in the ./configure script searched
for the shared libraries in the wrong directories. Fixed this by
adding $PATH to the search paths.
> SDL*_mixer: help ./configure find shared libraries for dynamic loading

- mingw-w64-mbedtls/PKGBUILD
64bit builds ok, but I am having trouble building `mingw32` build, but it seems that its a local problem:
```
-- Check for working C compiler: G:/msys64/mingw32/bin/i686-w64-mingw32-gcc.exe -- broken
CMake Error at G:/msys64/mingw32/share/cmake-3.3/Modules/CMakeTestCCompiler.cmake:61 (message):
The C compiler "G:/msys64/mingw32/bin/i686-w64-mingw32-gcc.exe" is not able
to compile a simple test program.
It fails with the following output:
Change Dir: D:/MINGW-packages/mingw-w64-mbedtls/src/build-i686-w64-mingw32/CMakeFiles/CMakeTmp
Run Build Command:"G:/msys64/usr/bin/make.exe" "cmTC_cfdd6/fast"
/usr/bin/make -f CMakeFiles/cmTC_cfdd6.dir/build.make
CMakeFiles/cmTC_cfdd6.dir/build
0 [main] make 7444 G:\msys64\usr\bin\make.exe: *** fatal error in forked process - fork: can't reserve memory …
```
> mbedtls: Updated to 2.2.0

- mingw-w64-python-zope.event/PKGBUILD
- mingw-w64-python-zope.interface/PKGBUILD
zope.interface is required for python.twisted (and I used zope.event to run the tests)
> Add packages for zope.event and zope.interface Python modules #893

- mingw-w64-c-ares/PKGBUILD
Adding this `validpgpkeys` entry allows makepkg to successfully verify all the source files.  I did *not* securely verify that this is the right key to use because the c-ares project doesn't make it easy to do so.
By the way, I got the full fingerprint by running:
~~~~
gpg --recv-keys 78E11C6B279D5C91
gpg --list-keys --fingerprint 78E11C6B279D5C91
~~~~
> c-ares: Added validpgpkeys.  Fixes #888.

- mingw-w64-gdl2/001-pixbuf.patch
- mingw-w64-gdl2/PKGBUILD
- mingw-w64-gdlmm2/000-C11.patch
- mingw-w64-gdlmm2/PKGBUILD
- mingw-w64-gtk2/PKGBUILD
1. Native input method interface is necessary for other language.
And If you use Windows 8 or later without this module, gtk2 will crash when system input method was set Chinese, Japanese or others.
2 . I add gdl library for gtk+ 2.0
> We use gtk2 for windows, so we need a buildin ime for windows

- mingw-w64-cmake/PKGBUILD
- mingw-w64-cmake/dont-install-bundle.patch
- mingw-w64-cmake/qt5-static-plugin-support.patch
- mingw-w64-cotire/PKGBUILD
I tested `automoc`, `autorcc` and `autostaticplugins`, i have nothing to test `autouic` with though, but it should work nonetheless. 
CMake 3.4 split off `cmQtAutoGeneratorInitializer.cxx` from `cmQtAutoGenerators.cxx` and `GetLinkImplementationClosure` moved from `cmTarget` to `cmGeneratorTarget`. 
The hunk with most of the implementation actually applied without error, but at the wrong position in the source. 
The path in cotire’s packaging has to be changed with every major CMake release. (CMake only searches in the module directory of the current version)
> Issue #923, CMake 3.4.1, cotire

- mingw-w64-emacs/PKGBUILD
- mingw-w64-emacs/emacs-24.5-w32-ime.diff
Emacs has a problem about Japanese language input with Widows GUI.
A patch is provided from following URL to fix this problem, and I applied it.
https://gist.github.com/rzl24ozi/a282260d2dd136daab14
> emacs: Apply IME patch for Japanese language input

- mingw-w64-avrdude/01-libtool.patch
- mingw-w64-avrdude/02-ddk-headers.patch
- mingw-w64-avrdude/03-handle-printing.patch
- mingw-w64-avrdude/04-no-giveio.patch
- mingw-w64-avrdude/PKGBUILD
- mingw-w64-libftdi/PKGBUILD
This pull request adds AVRDUDE, a utility that is very popular in the maker community because it allows you to upload programs to AVR microcontrollers using a wide variety of hardware programmers or bootloaders.  It is used inside the Arduino IDE.
This pull request also adds libftdi, because it is an (optional) dependency of AVRDUDE.
I listed libconfuse as a run-time dependency of libftdi because libftdi seems to be finding  C:/msys64/mingw32/lib/libconfuse.dll.a during its build configuration but I am not totally sure about that, because the compiled DLLs do not seem to depend on libconfuse.dll.
> Added libftdi and avrdude.

- mingw-w64-gitg/PKGBUILD
Now that gitg does not depend on webkit we should be able
to build it without problems
> gitg: update to version 3.19.1

- mingw-w64-gitg/PKGBUILD
- mingw-w64-gitg/gitg-i686.install
- mingw-w64-gitg/gitg-x86_64.install
See that it will still not build due to the gio-unix dep.
This will be fixed by patch later on.
> gitg: add missing deps

- mingw-w64-jucipp-git/PKGBUILD
* provides/replaces are now arrays
* removed unnessessary libclangmm download (this happens in prepare() through submodule init and update)
* updated pkgver
Not sure if pkgrel should be set to 2 though, so I leave this up to you.
> jucipp-git: working PKGBUILD

- mingw-w64-cego/PKGBUILD
Fix in CegoTableManager::deleteDataTable ( renamed to deleteDataTableEntry )
Since we allow now parallel updates, the method must check if the target tuple has already been touched by another transaction. Otherwise, invalid double entries could occur in case of concurrent updates on the same tuple. 
If a concurrent transaction is detected, the method returns false. This return value is used by the updateTuple method to decide, if the subsequent insert operation must be performed.
> Update to cego version 2.28.2

- mingw-w64-mpv/PKGBUILD
This might require the latest ANGLE update (the binaries don't seem to be in repo.msys2.org yet.)
As for the build error in #810, I think it's just a race condition. Hopefully it won't happen again. If it does, I hate to say it, but I think the solution is just to run the build again.
> mpv: Update to 0.14.0

- mingw-w64-avrdude/PKGBUILD
- Added validpgpkeys
- Added a dependency on libusb-compat because there is code in AVRDUDE that uses it and cannot use libusb-1.0 (fixes #947).
> avrdude fixes

- mingw-w64-curl/0004-cURL-Get-relocatable-base-from-dll.patch
- mingw-w64-curl/PKGBUILD
Currently, cURL uses the path to the current executable to figure out
where the certificates are. This works as long as all executables are in
/mingw64/bin/ (or /mingw32/bin/).
However, the entire point of having a DLL with a linkable .dll.a is to
be able to use it in executables that other people build. For example,
if an .exe lives in %HOME%\bin, the path used by our libcurl to look up
the certificates is all wrong.
Same problem with Git for Windows: its executables are hidden away from
the user, in the /mingw64/libexec/git-core/ directory. So the path to
the certificates is all wrong again.
So let's just use the path to the *cURL library* instead of the path to
the current .exe. This requires Win32 API available in Windows XP & 2003
and later, well within the Windows versions supported …
> cURL: Get relocatable base from .dll instead of .exe

- mingw-w64-sqlite3/PKGBUILD
SQLite updated to 3.10.0. The --disable-editline --enable-readline flags are needed to get SQLite to use readline as editline is now the default, likely due to licensing.
> Updated SQLite to 3.10.0

- mingw-w64-pkg-config/0001-fix-double-slash-in-test.patch
- mingw-w64-pkg-config/PKGBUILD
There were some minor issues preventing the tests for pkg-config from passing.  Nothing was wrong with the actual program, so there is no need to rebuild the package.
> pkg-config: Fixed tests.  This fixes issue #982.

- mingw-w64-enet/PKGBUILD
Please review new PKGBUILD: Nothing to do in "prepare()". No need to run "./configure".
> Create PKGBUILD for enet 1.3.13 (http://enet.bespin.org/)

- mingw-w64-oniguruma/PKGBUILD
The URL seems to have been switched to https://github.com/kkos/oniguruma
> Update URL for oniguruma

- .drone.yml
- drone/build.sh
Similar to https://github.com/Alexpux/MSYS2-packages/pull/431, this patch add build script for MINGW packages, using mingw32 compilers.
mingw64 will be added once some strange Wine64 bugs are fixed (like https://bugs.wine-staging.com/show_bug.cgi?id=623)
Currently the server has only one CPU core, running on AWS. In the coming days I'll start to upgrade the server with more cores.
> Add drone build script.

- mingw-w64-gitg/PKGBUILD
Hopefully the CI scripts works fine with pull request... Good luck to me...
BTW, the package fail to build here:
http://wine-ci.org/fracting/MINGW-packages/12/1
```
CC       gitg/gitg_gitg-gitg-application.o
../gitg-3.19.6/gitg/gitg-application.c:128:2: error: unknown type name 'GtkShortcutsWindow'
GtkShortcutsWindow* d_shortcuts;
^
gitg-application.c: In function 'gitg_application_on_shortcuts_activated':
gitg-application.c:1411:2: error: unknown type name 'GtkShortcutsWindow'
gitg-application.c:1413:2: error: unknown type name 'GtkShortcutsWindow'
gitg-application.c:1426:3: error: unknown type name 'GtkShortcutsWindow'
/home/nacho/checkout/gnome/gitg/gitg/gitg-application.vala:284:38: error: 'GTK_TYPE_SHORTCUTS_WINDOW' undeclared (first use in this function) …
```
> mingw-w64-gitg: This is a dummy patch to test the build system.

- .drone.yml
- mingw-w64-tcllib/PKGBUILD
https://github.com/Alexpux/MINGW-packages/pull/1045 doesn't build on CI server, see:
http://wine-ci.org/Alexpux/MINGW-packages/12
I manually verified on Windows in order to confirm it is not a CI server bug.
However, there is a CI server bug which reports fake success for matrix build at irc (and only at irc), I think this fake report is very misleading, so I temporary disable matrix build, will re-enable after fix irc notify.
> Tcllib fix md5

- appveyor.sh
- appveyor.yml
This adds AppVeyor CI for MSYS2 packages. When commits update package recipes, `makepkg-mingw` will be automatically executed for building the new package versions. Alexey, once you create your account in AppVeyor, simply pushing new commits should trigger the automated builds.
Since multiple packages can be touched and built per commit and some packages may take more than one hour for building, it is also interesting to ask AppVeyor for increasing the time limit to a few hours or something. I think they will be receptive about this.
> AppVeyor continuous integration

- mingw-w64-FreeImage/PKGBUILD
The renaming of LibRaw to libraw breaks FreeImage due to missing dll.
FreeImage uses the old dependency.
> Fixes dependency renaming of LibRaw to libraw

- mingw-w64-libbotan/PKGBUILD
- mingw-w64-libbotan/remove-GetTickCount64.patch
Is this patch okay? Making `_WIN32_WINNT` equal to `0x0600` breaks complitability with < Windows Vista.
> libbotan: Updated to 1.11.28

- mingw-w64-gcc/PKGBUILD
This has been reported as a problem several times, that `cc` in mingw64 shell points to `/usr/bin/cc` or nothing (depending on whether the user installed the `gcc` package).
> mingw-w64-gcc: Add cc.exe

- mingw-w64-gcc/000-relocatex-libintl-0.18.3.1.mingw.patch
- mingw-w64-gcc/PKGBUILD
- mingw-w64-gettext/00-relocatex-libintl-0.18.3.1.patch
- mingw-w64-gettext/PKGBUILD
When compiling code on 64-bit systems, the default return value of previously undeclared functions is `int`, as in *32-bit* integer value. This is a problem when the return value is actually a pointer. It becomes a real problem when the upper 32 bits of the register used to return that pointer are still set from previous usage (as is the case e.g. when the [`FLG_LDR_TOP_DOWN` global flag](https://technet.microsoft.com/en-us/library/cc779664%28v=ws.10%29.aspx) is set, as pretty much all return addresses have pretty much all of the upper 32 bits set to 1).
This is the problem that let anything using `bindtextdomain()` of the `gettext-runtime` package cause segmentation faults in this developer's tests.
Declaring the functions before using them miraculously fixes the segmentation faults. …
> Fix relocatable gettext-runtime on 64-bit systems

- ci-build.sh
Fix the build failure in http://wine-ci.org/Alexpux/MINGW-packages/52
Test in http://wine-ci.org/fracting/MINGW-packages/46
Do you prefer `pacman -Syyu`, or `pacman -Syy`, or anything else?
`pacman -Sy` doesn't work for me, i guess `pacman -Syu` doesn't work as well.
Please review before merge :)
If we agree on what's preferred, i'll submit a similar pull request to MSYS2-packages.
Thanks!
> Continuous Integration: Upgrade system before installing dependencies.

- ci-build.sh
This pull request is to fix the build failure discovered in http://wine-ci.org/Alexpux/MINGW-packages/65
> Continuous Integration: Avoid building a package repeatly if it was touched by multiple commits in a pull request.

- mingw-w64-openscenegraph/PKGBUILD
- mingw-w64-osgearth/0004-Fixed-debug-library-names.patch
- mingw-w64-osgearth/0005-Fixed-crash-due-to-probable-GCC-5.3.0-optimizer-bug.patch
- mingw-w64-osgearth/PKGBUILD
Adds debug package to osgearth (as done in OpenSceneGraph)
Also patches a crash due to a probable GCC 5.3.0 optimizer bug.
$ ll *.xz
-rw-r--r-- 1 Utilisateur None  7909732 Feb  6 11:50 mingw-w64-i686-osgearth-2.7-2-any.pkg.tar.xz
-rw-r--r-- 1 Utilisateur None 92577072 Feb  6 11:51 mingw-w64-i686-osgearth-debug-2.7-2-any.pkg.tar.xz
-rw-r--r-- 1 Utilisateur None  7727752 Feb  6 12:16 mingw-w64-x86_64-osgearth-2.7-2-any.pkg.tar.xz
-rw-r--r-- 1 Utilisateur None 94028220 Feb  6 12:17 mingw-w64-x86_64-osgearth-debug-2.7-2-any.pkg.tar.xz
> osgearth: add debug package (osgearth is now a split package...)

- mingw-w64-catch/PKGBUILD
Just updating to the next version of catch.  I tested that the package builds correctly and that the catch-based test suite of one of my projects passes.
> Update catch to 1.3.4.

- mingw-w64-fontconfig/PKGBUILD
This allows native Windows software to understand the output of `pkg-config` when used with `fontconfig`. Fixes #872.
Please make sure that I'm replacing the paths in a way that's consistent with MSYS2's conventions, since this is my first contribution to MSYS2.
> Change MSYS2-specific paths in fontconfig.pc to use pkg-config prefixes

- mingw-w64-ruby/0004-rbinstall-destdir.patch
- mingw-w64-ruby/PKGBUILD
See #1070 for more discussion.
By the way, the ruby package installs some `.bat` and `.cmd` files to /mingw64/bin.  I'm not sure if we like that or not.
I can add myself as a maintainer for this package if you guys would like.  Ruby is my go-to language for a lot of things.
> ruby: Fix the installation of the bundled gems.

- mingw-w64-qt-installer-framework/PKGBUILD
Without this patch, qt-installer-framework failed to build:
```
C:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -ljasper\r\r
C:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lwebp\r\r
collect2.exe: error: ld returned 1 exit status\r\r
Makefile.Release:83: recipe for target '../../bin/archivegen.exe' failed\r
```
http://wine-ci.org/fracting/MINGW-packages/6
Let's wait the CI build before merge :)
> mingw-w64-qt-installer-framework: Fix makedepends.

- appveyor.yml
- ci-build.sh
** Please review before merge **
Dear folks,
This pull request has two changes:
Firstly, it adds `C:\msys64\usr\bin\pacman --sync --refresh --refresh --needed --noconfirm msys2-runtime msys2-runtime-devel bash pacman pacman-mirrors` to appveyor.yml, this is a workaround, once we support `update-core --noconfirm`, the long version of command line could be replaced.
Secondly, it moves `Prepare` after `Detect`, so when no package is changed, we don't need to waste time and waste bandwidth on system upgrade.
@renatosilva how do you think about this solution, which is slightly different to what we discussed last time? Please share your thoughts, thanks!
> CI: Update core packages before full system upgrade.

- mingw-w64-ncurses/PKGBUILD
* fix to point to a versioned source URL
(to have a stable content/checksum)
* update source to the latest version
* use sha256 checksums
* fix 'pkgdesc'
Ref: https://github.com/Alexpux/MINGW-packages/pull/1077
> ncurses 6.0-20160220

- mingw-w64-nodejs/0107-cygpath-conversion-in-npm-shell-wrapper.patch
- mingw-w64-nodejs/PKGBUILD
Make the npm shell script always calls cygpath if that command is
available and the node executable is "node.exe".
Fixes issue #1039.
> Path conversion in npm shell wrapper

- mingw-w64-atom-editor/PKGBUILD
- mingw-w64-atom-shell/PKGBUILD
* fix two `shasum` checksum types (with `SKIP` content) to `sha256sum`
* add a missing dependency
> atom-editor, atom-shell: fix invalid checksum-types

- mingw-w64-ncurses/PKGBUILD
Taken from:
https://github.com/Alexpux/MSYS2-packages/blob/master/ncurses/PKGBUILD#L13
> ncurses: fix to recognize source package type

- mingw-w64-bzip2/PKGBUILD
Mingw bzip2 doesn't work when installed in fresh msys2.
Found this issue when debugging a Wine bug.
Cross Reference: https://bugs.wine-staging.com/show_bug.cgi?id=656
MINGW bzip2 randomly hang when call from `file -bizL ../babl-0.1.14.tar.bz2 `
> mingw-w64-bzip2: Add mingw-w64-gcc-libs as depends.

- mingw-w64-OpenBLAS-git/PKGBUILD
- mingw-w64-atom-editor/PKGBUILD
- mingw-w64-atom-shell/PKGBUILD
- mingw-w64-babl/PKGBUILD
- mingw-w64-clutter/PKGBUILD
- mingw-w64-freerdp-git/PKGBUILD
- mingw-w64-gegl/PKGBUILD
- mingw-w64-glib2-git/PKGBUILD
- mingw-w64-gtk3-git/PKGBUILD
- mingw-w64-libdvdcss/PKGBUILD
- mingw-w64-libdvdnav/PKGBUILD
- mingw-w64-libdvdread/PKGBUILD
- mingw-w64-nanovg-git/PKGBUILD
- mingw-w64-nim/PKGBUILD
- mingw-w64-nimble/PKGBUILD
- mingw-w64-octopi-git/PKGBUILD
- mingw-w64-opencollada-git/PKGBUILD
- mingw-w64-osmgpsmap-git/PKGBUILD
- mingw-w64-pitivi-git/PKGBUILD
- mingw-w64-vlc-git/PKGBUILD
- mingw-w64-x264/PKGBUILD
- mingw-w64-zlib/PKGBUILD
* mark git urls as such with `git+` prefix
* revert git.videolang.org urls to use cleartext git protocol
(http/https access appears to be down)
> fix git urls

- mingw-w64-libdvdcss/PKGBUILD
- mingw-w64-libdvdnav/PKGBUILD
- mingw-w64-libdvdread/PKGBUILD
- mingw-w64-vlc-git/PKGBUILD
- mingw-w64-x264/PKGBUILD
Apologise for not getting this right the first (and second) time around.
videolan.org Git URL is in the form of
secure: https://git.videolan.org/git/repo.git
insecure: git://git.videolan.org/repo.git
> fix git.videolan.org urls and switch to secure again

- mingw-w64-libxml2/PKGBUILD
Looks like the `libxml2-2.9.2-catalog-revert.patch` has been merged upstream.
> update libxml2 with upstream

- mingw-w64-catch/01-fix-paren-pragma.patch
- mingw-w64-catch/PKGBUILD
The patch I'm adding in this pull request has also been sent to the upstream developer: https://github.com/philsquared/Catch/pull/604
> catch: Update to 1.3.5, add a patch to fix a warning, and add check()

- mingw-w64-cpptest/PKGBUILD
- mingw-w64-cpptest/cpptest-1.1.2.patch
Add the CppTest library (http://cpptest.sourceforge.net/). It is a check dependency for the uriparser library (http://uriparser.sourceforge.net/), which in turn is a hard runtime dependency for the libkml (https://github.com/google/libkml/) library.
> cpptest version 1.1.2 (package release 1)

- mingw-w64-cpptest/PKGBUILD
- mingw-w64-cpptest/cpptest-1.1.2.patch
- mingw-w64-uriparser/PKGBUILD
- mingw-w64-uriparser/uriparser-0.8.4.patch
Add the uriparser library (http://uriparser.sourceforge.net/). It is a hard runtime dependency for the libkml (https://github.com/google/libkml/) library, which in turn is an optional runtime dependency for the GDAL (http://www.gdal.org/) library.
> Add uriparser

- mingw-w64-clang/PKGBUILD
Just fix issue with validpgpkeys.  Also ignore failure when moving files
from src to the llvm source-code tree.  A build process might have done
that earlier.
Note that I wish to deal with libunwind as a separate issue.
> Fix package

- mingw-w64-cppcheck/PKGBUILD
* To avoid to install Qt5 and python2 if not needed
> cppcheck: make some dependencies optional

- mingw-w64-libkml/PKGBUILD
curl is a check dependency, python is both a make and optional dependency (using libkml python bindings should be up to the user)
> Adjust libkml dependencies

- mingw-w64-glog/PKGBUILD
- mingw-w64-glog/glog-0.3.4.4d391fe.patch
Installation of config.h is not necessary because it is not used by the public headers
> Fix header installation for glog

- mingw-w64-nanodbc/PKGBUILD
- mingw-w64-nanodbc/nanodbc-2.12.1.patch
Updated CMakeLists.txt:
- Removed unicode option. Instead, build both libraries
- Lib with unicode support postfixed with "_unicode"
> nanodbc: compile both unicode and non-unicode

- appveyor.yml
- ci-build.sh
- ci-library.sh
**Support for package deployment**
The CI system can now deploy built packages to remote repositories. AppVeyor has been configured to export packages to Bintray. Drone can be configured to perform similar export as well. Services other than Bintray can also be configured. Alexey, deployment should start working once you complete the following configuration:
1. Create a Bintray account named the same as your AppVeyor account.
2. Create the Bintray generic repository _msys2_.
3. Create the Bintray packages _ci.mingw_ and _ci.msys_.
4. Replace `BINTRAY_TOKEN_ENCRYPTED_BY_APPVEYOR` with the actual value.
The same procedure can be used for repository clones, with the additional step of replacing `DEPLOY_ACCOUNT` with your own GitHub username. Leaving this unchanged will keep deployment …
> Improvements for continuous integration

- mingw-w64-libmikmod/PKGBUILD
Turns out openal is indeed a run-time dependency of libmikmod:
```
$ objdump -x /mingw32/bin/libmikmod-3.dll | grep 'DLL Name'
DLL Name: dsound.dll
DLL Name: KERNEL32.dll
DLL Name: msvcrt.dll
DLL Name: USER32.dll
DLL Name: WINMM.DLL
DLL Name: libopenal-1.dll
DLL Name: libgcc_s_dw2-1.dll
```
> libmikmod: move openal from makedepends to depends

- mingw-w64-SDL_mixer/PKGBUILD
It turns out that openal is not a run-time dependency of sdl_mixer, not even of libmikmod. It is merely needed to build the test compile triggered by sdl_mixer's configure script, because the string returned by `libmikmod-config --libs` contains `-lopenal`.
> SDL_mixer: move openal to makedepends

- mingw-w64-SDL_mixer/PKGBUILD
Fix configure error:
```
aclocal-1.15: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:579: warning: macro 'AM_PATH_SMPEG' not found in library
autoreconf: running: /usr/bin/autoconf --force
configure.in:580: error: possibly undefined macro: AM_PATH_SMPEG
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
==> ERROR: A failure occurred in prepare().
Aborting...
==> Removing installed dependencies...
```
> mingw-w64-SDL_mixer: Add mingw-w64-smpeg as makedepends.

- mingw-w64-gtk-engines/PKGBUILD
Would be great to have in MSYS2 if you are developing for GTK2 or using it from MSYS2. This PKGBUILD is an direct port from ArchLinux. Works great on both versions even with custom themes - i686 & x86_64.
> Theme engines for GTK+ 2 (mingw-w64)

- mingw-w64-glbinding/PKGBUILD
Adds some useful tools like:
```
mingw-w64-x86_64-glbinding /mingw64/bin/glcontexts.exe
mingw-w64-x86_64-glbinding /mingw64/bin/glfunctions.exe
mingw-w64-x86_64-glbinding /mingw64/bin/glmeta.exe
mingw-w64-x86_64-glbinding /mingw64/bin/glqueries.exe
```
P.S I have asked upstream about including static libraries: [issue](https://github.com/cginternals/glbinding/issues/165)
> glbinding: Add missing glfw dependency for tools

- mingw-w64-gcc/PKGBUILD
Delete a file that was created by patch for second go-around or rebuild.
> Remove file created by patch.

- mingw-w64-qt5-git/PKGBUILD
With this, it finally completes the package creation process.
I had to disable the qttranslations module due to a lrelease issue described in #1180 
Also, I've added the _make_doc flag to allow to speed up the final phase
> qt5-git: fix the package stage to complete the process

- mingw-w64-editrights/PKGBUILD
Changed mirror since cybermirror.org is under maintenace and is not even listed on https://cygwin.com/mirrors.html
Also fix PKGBUILD.
> editrights: fix pkgbuild

- mingw-w64-jucipp-git/PKGBUILD
Feel free to make this package installable through pacman -S. juCi++ has been very stable since v1.0.0 release, and I'll update the pkgver whenever we have major changes.
> jucipp-git: Update PKGBUILD

- mingw-w64-angleproject-git/PKGBUILD
Local build of mingw-w64-i686-mpv doesn't fail anymore however still fails on Tea-CI. AppVeyor still on angleprojct build.
Tea-ci:
```
Checking for MinGW                                                : no 
Checking for POSIX environment                                    : no 
Checking for development environment                              : not found any of mingw, posix 
Unable to find either POSIX or MinGW-w64 environment, or compiler does not work.
```
AppVeyor:
```
looking for conflicting packages...
:: gyp-git and gyp-svn are in conflict (gyp). Remove gyp-svn? [y/N] error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: gyp-git and gyp-svn are in conflict
==> ERROR: 'pacman' failed to install missing dependencies.
==> …
```
> angleproject: update to fix build of mpv 32-bit

- mingw-w64-wkhtmltopdf/PKGBUILD
- mingw-w64-wkhtmltopdf/wkhtmltopdf-0.13.patch
Add wkhtmltopdf library (http://wkhtmltopdf.org/).
Note: I could not use the release tarball from version 0.12, as it depends on Qt 4.8. I had to take the development version from git branch labeled "0.13", which is already using Qt 5.x
> Add wkhtmltopdf

- mingw-w64-libidn/0003-nfkc.c-Fix-Win64-crash.patch
- mingw-w64-libidn/0004-nfkc.c-Fixed-invalid-var-types.patch
- mingw-w64-libidn/PKGBUILD
As title says.
Patch 0003 is most important.
Upstream was informed but no reaction for a few days.
Discovered while debugging crash in curl's simple command `curl -v http://яндекс.рф`.
More info:
https://github.com/curl/curl/issues/731
http://lists.gnu.org/archive/html/help-libidn/2016-03/msg00002.html
> Fix crash in libidn on Win64

- mingw-w64-python-numpy/0007-disable-64bit-experimental-warning.patch
- mingw-w64-python-numpy/PKGBUILD
Every time a user, or another python program, imports numpy on a 64-bit Windows machine, it prints a warning telling people to report bugs upstream.
```
>>> import numpy
C:\msys64\mingw64\lib\python2.7\site-packages/numpy/core/__init__.py:14: Warning: Numpy built with MINGW-W64 on Windows 64 bits is experimental, and only available for
testing. You are advised not to use it for production.
CRASHES ARE TO BE EXPECTED - PLEASE REPORT THEM TO NUMPY DEVELOPERS
from . import multiarray
```
Now, I use numpy and programs that depend on it a lot, and seeing this thing pop up all the time in my terminal is extremely annoying. I'm positive that other developers that use the 64-bit numpy package would appreciate that the warning be disabled by default, so here's a patch that takes it out.
> python-numpy: add patch to disable 64-bit warning

- mingw-w64-avrdude/PKGBUILD
I tested this pull request by programming an AVR with the resulting (32-bit) AVRDUDE package.
> avrdude: Update to 6.3.

- mingw-w64-python-cx_Freeze/0001-fix-manifest-processor-arch.patch
- mingw-w64-python-cx_Freeze/PKGBUILD
This patch fixes `ImportError: DLL load failed: %1 is not a valid Win32 application.` when running modules packaged by cx_freeze on 64bit machines. This has to do with mixing Python 64 with 32bit modules. Switching the application manifest's `processorArchitecture="x86"` to `processorArchitecture="*"` fixes this problem. The star indicates that all processor architectures are supported.
This was [fixed upstream](https://bitbucket.org/anthony_tuininga/cx_freeze/pull-requests/71/changed-x86-in-windows-manifest-to/diff) in cx_Freeze 4.3.4. This patch wouldn't be necessary if the package itself was updated, but I was never able to get the latest version to successfully build.
> python-cx_Freeze: add patch to fix manifest arch

- mingw-w64-libjpeg-turbo/0002-md5sum-fix.patch
- mingw-w64-libjpeg-turbo/PKGBUILD
Fixes a check() error that md5cmp hangs on all inputs
> libjpeg-turbo: fix md5 code with backport from trunk

- mingw-w64-ghostscript/PKGBUILD
- mingw-w64-ghostscript/ghostscript-sys-zlib.patch
- mingw-w64-ghostscript/libspectre.patch
- mingw-w64-ghostscript/mingw-build.patch
Patches refreshed. Also removed `configure' from ghostscript-sys-zlib.patch since
the PKGBUILD will run autoconf anyway.
> mingw-w64-ghostscript: refresh patches

- mingw-w64-ccache/MinGW-add-ifdeds.patch
- mingw-w64-ccache/PKGBUILD
Patching these 2 files seems to be enough. Upstream patch https://git.samba.org/?p=ccache.git;a=commit;h=361d9ad46d3276148f5b64654bb775205b728318
makepkg*.config flag `ccache` doesn't work, maybe we should change package() and install it Arch way? https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/ccache
Adressing https://github.com/Alexpux/MINGW-packages/issues/1292
EDIT: fixed links
EDIT2: Updated license
> ccache: update to 3.2.4

- mingw-w64-mpv/PKGBUILD
No problems locally, hope bots will build now.
Commented line moving encoding-profiles.conf because it isn't created without `--enable-encoding` flag:
https://github.com/mpv-player/mpv/releases/tag/v0.17.0
> build: disable encoding mode by default (uses deprecated FFmpeg APIs)
EDIT: Finally AppVeyor didn't fail.
> mpv: update to 0.17.0

- mingw-w64-pidgin++-bzr/001-autotools-and-fhs-pidgin.patch
- mingw-w64-pidgin++-bzr/002-autotools-and-fhs-pidgin++.patch
- mingw-w64-pidgin++-bzr/003-autotools-and-fhs-adaptation.patch
- mingw-w64-pidgin++-bzr/004-build-fixes.patch
- mingw-w64-pidgin++-bzr/005-fix-save-suffix.patch
- mingw-w64-pidgin++-bzr/006-gtk-customizations.patch
- mingw-w64-pidgin++-bzr/PKGBUILD
- mingw-w64-pidgin++/001-autotools-and-fhs-pidgin.patch
- mingw-w64-pidgin++/002-autotools-and-fhs-pidgin++.patch
- mingw-w64-pidgin++/003-autotools-and-fhs-adaptation.patch
- mingw-w64-pidgin++/004-build-fixes.patch
- mingw-w64-pidgin++/005-fix-save-suffix.patch
- mingw-w64-pidgin++/006-gtk-customizations.patch
- mingw-w64-pidgin++/PKGBUILD
- mingw-w64-pidgin-hg/001-build-fixes.patch
- mingw-w64-pidgin-hg/002-finch-fixes.patch
- mingw-w64-pidgin-hg/PKGBUILD
- mingw-w64-pidgin/001-autotools-and-fhs.patch
- mingw-w64-pidgin/002-build-fixes.patch
- mingw-w64-pidgin/PKGBUILD
The command-line Finch client is now built for the 3.x series of Pidgin. The Pidgin++ package has been reimplemented and is now buildable, also the development version has been added. Other improvements are mentioned in commits. Requires [MSYS2-packages#96](https://github.com/Alexpux/MSYS2-packages/pull/96).
> Improvements for Pidgin and Pidgin++

- mingw-w64-ccache/PKGBUILD
Add shortcuts for gcc.
makepkg-mingw doesn't use it after changing `ccache` flag in `makepkg_mingw32.conf` and `makepkg_mingw64.conf`. I suppose it is makepkg-mingw bug and I'll further investigate it.
Manual compilation after exporting `export PATH="/mingw32/lib/ccache/bin/:$PATH"` for 32-bits or `export PATH="/mingw64/lib/ccache/bin/:$PATH"` for 64-bits works fine.
> ccache: add shortcuts for gcc

- mingw-w64-pidgin++-bzr/PKGBUILD
Install the GTK+ customizations like already implemented in release-based version.
> Adjustment in development version of Pidgin++

- mingw-w64-evince/PKGBUILD
Evince is missing nss as dependency.
Fixes https://github.com/Alexpux/MINGW-packages/issues/1310
> evince: add nss as dependency

- mingw-w64-opus/0002-win32-only-use-dllexport-when-building-dll.patch
- mingw-w64-opus/PKGBUILD
Fixes compilation with shared FFmpeg, when trying to use opus static library.
Chromium and Firefox instead define an empty OPUS_EXPORT when building, which disables dllexport for both shared and static libs, but it's only a problem for the static library, not the shared.
~~Patch from http://lists.xiph.org/pipermail/opus/2015-October/003175.html~~
~~Can't tell why it wasn't committed.~~
Patch was applied upstream in git, so it can be removed when next release is out.
> opus: Only use dllexport for the dll

- mingw-w64-jsoncpp/PKGBUILD
Upstream CMake deficiencies are to blame, I think, in this case, since I'm pretty sure I worked around this in my branch of the repo, but this is just a simple sed post-install that can fix up consuming jsoncpp by CMake-using packages.
First time contributing to msys2 - wasn't sure if I needed to bump any of the versions, etc. or do any other special things with the commit, so be kind and let me know if I messed this one up, thanks!
> jsoncpp: Fix ${MINGW_PREFIX} getting hard-coded into the CMake package files

- mingw-w64-catch/PKGBUILD
I tested this and it builds fine on my machine.
By the way, I don't have an urgent desire to use this latest version of Catch.  The old one worked fine for my purposes.  But I just feel like I am doing my part to keep MSYS2 up-to-date which is generally good for all users.
> Catch: Update to 1.5.0.

- appveyor.yml
- ci-build.sh
Fix for the incomplete system update in AppVeyor after new pacman extended the core package list and the explicit references became outdated. This was causing the core update to be completed only in ci-build script, and the regular update to be left behind. For example, [MSYS2-packages#575](https://github.com/Alexpux/MSYS2-packages/pull/575) seems to have reproduced the problem.
Package downgrades are now enabled for regular updates and for AppVeyor core updates, so removed versions are properly detected. Git is now explicitly installed in AppVeyor since the external one is not anymore visible after minimal path has been implemented.
> Fixes for continuous integration

- mingw-w64-gtk3-git/PKGBUILD
Builds from the git package fail when `gtk-doc` is not installed, dues to the presence of the following line in `prepare()`. The fix is simple: depend on `gtk-doc`.
```sh
[[ -f gtk-doc.make ]] || cp /usr/share/gtk-doc/data/gtk-doc.make .
```
> gtk3-git: need gtk-doc in makedepends

- mingw-w64-ffmpeg/PKGBUILD
Both i686 and x86_64 don't crash.
> ffmpeg: update to 3.0.2

- mingw-w64-libmaxminddb/0001-libmaxminddb-1.2.0-mingw-no-undefined.patch
- mingw-w64-libmaxminddb/PKGBUILD
- mingw-w64-libmaxminddb/mingw-no-undefined.patch
Upgrade to 1.2.0 and adjust mingw-no-undefined patch for new ver.
> mingw-w64-libmaxminddb - upgrade to 1.2.0

- mingw-w64-libmariadbclient/001-2.2.3-fix-libnames-mingw.patch
- mingw-w64-libmariadbclient/PKGBUILD
Upgrade to version 2.2.3 and adjust libname patch for new version.
> mingw-w64-libmariadbclient - upgrade to 2.2.3

- appveyor.yml
- ci-build.sh
- ci-library.sh
* Proper detection of package installation failures, avoiding false positives such as #1376.
* Explicitly set a default shell in AppVeyor, avoiding failures like reproduced by [MSYS2-packages#587](https://github.com/Alexpux/MSYS2-packages/pull/587).
> Fix for continuous integration

- mingw-w64-harfbuzz/PKGBUILD
mingw-w64-harfbuzz - upgrade to version 1.2.7.
> mingw-w64-harfbuzz - 1.2.7 - Upgrade to new version

- mingw-w64-iso-codes/PKGBUILD
mingw-w64-iso-codes:: 3.68 - update to latest version
> mingw-w64-iso-codes:: 3.68 - update to latest version

- mingw-w64-devcon-git/PKGBUILD
Our mingw-w64 crt globs wildcards it sees on `argv` by default because it was configured with `--enable-wildcard`.  That prevents us from running commands like `devcon hwids *`, which is the correct way to list the hardware IDs of all the devices on the system.  This pull request disables wildcard globbing for devcon.
Note that to run that command in Bash, you would actually have to type:
devcon hwids \*
> devcon-git: Disable wildcard globbing.

- mingw-w64-libssh/PKGBUILD
- mingw-w64-libssh/mingw-as-unix.patch
mingw-w64-libssh: 0.7.3: Update to latest version and rekey
mingw-as-unix patch
> mingw-w64-libssh: 0.7.3: Update to latest version and rekey mingw-as-unix patch

- mingw-w64-qt5-static/0042-qt-5.4.0-static-cmake-also-link-plugins-and-plugin-deps.patch
- mingw-w64-qt5-static/PKGBUILD
- mingw-w64-qt5/0042-qt-5.4.0-static-cmake-also-link-plugins-and-plugin-deps.patch
- mingw-w64-qt5/PKGBUILD
update cmake patch 0042 to exclude Qt5Qml factory plugins from the fix and avoid duplicate includes later in Qt5QmlConfigExtras.cmake
see https://github.com/Alexpux/MINGW-packages/issues/1364
> qt5[-static]: update cmake patch 0042 - exclude Qt5Qml factory plugins

- mingw-w64-unibilium/0001-unibilium-msys-makefile.patch
- mingw-w64-unibilium/PKGBUILD
Recipe for the unibilium library. The patch disables asan CFLAGS and removes the default terminfo paths.
> Add unibilium

- mingw-w64-libmypaint-git/PKGBUILD
libmypaint is splitting off from MyPaint fully now.
Build for this lib is now a simple autotools thing. I've tested that it works properly from MSYS2 using makepkg-mingw for both MINGW64 and MINGW32.
> Add mingw-w64-libmypaint-git

- .drone.yml
Now we bring 64 bit support to Tea CI, next step is adding package uploading script so users can have a convenient way to download testing packages.
> Continuous Integration: Enable 64 bit build.

- appveyor.yml
AppVeyor has [recently updated](https://github.com/appveyor/ci/issues/765) the MSYS2 installation, so manual installation of git and latest pacman is not necessary anymore.
> Updates for continuous integration

- mingw-w64-libssh/PKGBUILD
- mingw-w64-libssh/mingw-as-unix.patch
Previous update stopped including pkg-config files which are needed for ex. FFmpeg.
> libssh: repackage missing pkg-config files

- mingw-w64-libxml++2.6/PKGBUILD
Version 2.6 and 3.0 can be installed in parallel
for smoother transition.
This commit just reverts the old PKGBUILD into a separate directory.
The availability of the 2.6 version should close #1343.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alexpux/mingw-packages/1417)
> Put back LibXML++ 2.6

- mingw-w64-libzip/PKGBUILD
- mingw-w64-libzip/configure.patch
Fixes #1418.
This fixes a bug found in the current libzip package preventing the user from adding a new file to an existing archive.
> libzip: updated to version 1.1.2 and fixed bug

- mingw-w64-curl/0001-curl-relocation.patch
- mingw-w64-curl/PKGBUILD
mingw-w64-culr: 7.49.0 Update to latest version
rekey relocation patch
Add all valid pgp keys.
> mingw-w64-curl: 7.49.0 Update to latest version

- mingw-w64-gcc-git/PKGBUILD
According to <https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70936>, GCC's '--with-gxx-include-dir' configure option is causing a relocation bug, We'd better remove it.
The newly added standard-conforming <cstdlib> and <cmath> C++ headers since GCC 6 suffer from this bug. A relocated GCC will complain about inability to find <stdlib.h> and <math.h>, respectively.
In addition, removal of this option changes the paths where GCC searches for libstdc++ headers. We make GCC search for them in the default directories by removing '--enable-version-specific-runtime-libs' as well.
---
Here is an abridged IRC log in #gcc on OFTC today:
> [16:12:21] \<lh_mouse> The #include_next bug. it hasn't been fixed.
> [16:12:25] \<jwakely> lh_mouse: your problems were on mingw though, right?
> [16:12:54] …
> Averted the relocation bug.

- mingw-w64-gcc-git/PKGBUILD
This a general patch for gcc-5-branch and gcc-6-branch that fixes issues mentioned in #1374 and #1437.
* In #1374:
The relocation bug mentioned in #1374 is a [GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70936) and has been averted.
libvtv*.dll is now excluded from packaging, though the reason why it isn't built is still unknown.
* In #1437:
Modification of the library path introduces problems when packaging DLLs. Libraries are known to be subject to this bug are `libatomic*`, `libgomp*`, `libquadmath*`, `libssp*`, `libobjc*` and `libgfortan*`.
The `build()` function now removes the destination directory before it invokes `make install` so missing libraries are now reported as errors. Otherwise, if a successful package has been created already, `makepkg` might be happy with …
> Fixed packaging stuff.

- mingw-w64-angleproject-git/PKGBUILD
- vsprintf doesn't exist anywhere in the source; remove sed
- don't run sed on .git files and dir (fixes indexv2 errors)
- add missing define to gyp
- use official url
> angle: Update to 2.1.r5785

- mingw-w64-gdb-git/0003-MinGW-w64-Use-gnu-printf.patch
- mingw-w64-gdb-git/PKGBUILD
`makepkg` previously failed with:
```
[...]
==> Starting prepare()...
Applying: MinGW-w64: Two fixes for 'unusual' files.
Applying: MinGW-w64: Fix libibery configure
Applying: MinGW-w64: Use gnu-printf
error: patch failed: gas/read.c:4413
error: gas/read.c: patch does not apply
Patch failed at 0001 MinGW-w64: Use gnu-printf
[...]
```
> gdb-git: Fix patch

- mingw-w64-libvpx/0009-use-strtok_r.mingw.patch
- mingw-w64-libvpx/PKGBUILD
mingw-w64 provides strtok_r(), defined in "string.h", so there is no need to use strtok_s().  This has the added benefit that libvpx will work under Windows XP.
> Use strtok_r() under mingw-w64 to support winxp

- mingw-w64-x265/0001-winxp-condition-var.mingw.patch
- mingw-w64-x265/PKGBUILD
Instead of using _WIN32_WINNT to determine whether Windows XP support code in "winxp.cpp" and "winxp.h" is needed, enable it for 32-bit builds.
Also, pass -DWINXP_SUPPORT:BOOL=TRUE to cmake under 32-bit builds to enable Windows XP support.
> Make x265 support winxp

- mingw-w64-glew/PKGBUILD
mingw-w64-glew - 1:13.0 - build 32-bit and 64-bit binaries in separate dirs
> mingw-w64-glew - 1:13.0 - build 32-bit and 64-bit binaries in separate dirs

- mingw-w64-attica-qt5/PKGBUILD
- mingw-w64-karchive-qt5/PKGBUILD
- mingw-w64-kcodecs-qt5/PKGBUILD
- mingw-w64-kconfig-qt5/PKGBUILD
- mingw-w64-kcoreaddons-qt5/PKGBUILD
- mingw-w64-kcrash-qt5/PKGBUILD
- mingw-w64-kdbusaddons-qt5/PKGBUILD
- mingw-w64-kglobalaccel-qt5/PKGBUILD
- mingw-w64-kguiaddons-qt5/PKGBUILD
- mingw-w64-ki18n-qt5/PKGBUILD
- mingw-w64-kidletime-qt5/PKGBUILD
- mingw-w64-kimageformats-qt5/PKGBUILD
- mingw-w64-kitemmodels-qt5/PKGBUILD
- mingw-w64-kitemviews-qt5/PKGBUILD
- mingw-w64-kjs-qt5/PKGBUILD
- mingw-w64-kplotting-qt5/PKGBUILD
- mingw-w64-kwidgetsaddons-qt5/PKGBUILD
- mingw-w64-kwindowsystem-qt5/PKGBUILD
- mingw-w64-solid-qt5/PKGBUILD
1. add -DECM_MKSPECS_INSTALL_DIR= to MSYS2_ARG_CONV_EXCL so mkspecs files are placed in /mingw{32,64} instead of /msys{32,64}/mingw{32,64}
2. change deprecated LIB_INSTALL_DIR with KDE_INSTALL_LIBDIR
3. place mkspecs files in ${QT5_PREFIX}/share/qt5/mkspecs (Qt5 mkspecs dir) instead of ${QT5_PREFIX} which points to root /mingw{32,64}
Since @mingwandroid maintains KDEF5 he should decide about this PR.
> KDEF5 fixes for build process

- mingw-w64-ffmpeg/PKGBUILD
libdcadec removed upstream https://ffmpeg.org/pipermail/ffmpeg-cvslog/2016-March/098996.html
There are references to `$(cygpath -m /)` inside /lib/pkgconfig/*.pc files and someone more experienced should take a look at it.
> ffmpeg: update to 3.1

- mingw-w64-angleproject-git/PKGBUILD
- mingw-w64-mpv/PKGBUILD
With both old and updated angle there is issue with 32 bit `LIBEGL.DLL`.
Without angle update 64 bit mpv was throwing warnings/error when playing certain video files.
I do NOT recommend using 32 bit mpv (64 bit seems to be fine) with mesa package installed:
```
[vo/opengl] Initializing OpenGL backend 'angle'
[vo/opengl] Failed to load LIBEGL.DLL
[vo/opengl] Initializing OpenGL backend 'angle-es2'
[vo/opengl] Not using this by default.
[vo/opengl] Initializing OpenGL backend 'win'
[vo/opengl] GL_VERSION='3.0 Mesa 11.2.0 (git-aa91c51)'
[vo/opengl] Detected desktop OpenGL 3.0.
[vo/opengl] GL_VENDOR='VMware, Inc.'
[vo/opengl] GL_RENDERER='Gallium 0.4 on llvmpipe (LLVM 3.8, 128 bits)'
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='1.30'
[vo/opengl] Loaded extension GL_ARB_sync.
[vo/opengl] Loaded …
```
> mpv: update to 0.18.0

- mingw-w64-qt5/0125-qt5-windeployqt-fixes.patch
- mingw-w64-qt5/PKGBUILD
This makes it actually possible to run. It doesn't actually get all the lib dependencies because of the extra ones we link to, but it useful for deploying plugins.
> qt5: fix windeployqt

- mingw-w64-nlopt/PKGBUILD
Issues with the build system resulted in the generation of libraries with absent/non-functioning Fortran API. The build system does weird things to generate the C++ library, and then goes back and redoes everything to generate the normal C library. After some discussion and investigation with people in the Freenode `##fortran` community, we were able to build working packages if a `make distclean` statement is placed inbetween those two build stages. I still have some suspicions about whether some Fortran related packages need to be in the build dependencies, but that depends on what is considered "standard" to be installed on the machine generating the packages for the repository.
> Update PKGBUILD for mingw-w64-nlopt

- mingw-w64-glfw/003-3.2-cmake-install.patch
- mingw-w64-glfw/PKGBUILD
allow CMake to find_package(glfw3) without symbolic links.
In CMakeLists.txt of other projects, `find_package(glfw3)` had failed because `/mingw64/lib/cmake/glfw3/glfw3Targets-noconfig.cmake` required glfw3.dll at `${_IMPORT_PREFIX}/lib/` but the DLL was moved into `${_IMPORT_PREFIX}/bin/`.
After this commit, the `glfw3Targets-noconfig.cmake` requires `${_IMPORT_PREFIX}/bin/glfw3.dll`.
> glfw: change args of install() for find_package

- mingw-w64-sqlite3/PKGBUILD
_msize is the Win32 version of malloc_usable_size, but SQLite doesn't use
it on MinGW for some reason. This commit fixes that, as _msize is more
optimized than SQLite's homegrown implementation (according to the documentation).
> Updated SQLite3 to latest release and enabled usage of _msize function.

- mingw-w64-ffmpeg/PKGBUILD
This is ABI bugfix release, should replace 3.1 ASAP
> ffmpeg: update to 3.1.1

- mingw-w64-python-cx_Freeze/PKGBUILD
- mingw-w64-python-nuitka/PKGBUILD
- mingw-w64-python-pillow/PKGBUILD
- mingw-w64-python-rst2pdf/PKGBUILD
Fixes #1492 
Based on python-sphinx package.
There are some files containing `C:/building/msys64/mingw{32
,64}` left in /mingw{32,64}/bin:
```
croco-0.6-config
curl-config
python-config.sh
python2-pyuic5.bat
python3-config
python3.5-config
python3.5m-config
pyuic5.bat
xml2-config
xslt-config
```
> python-{cx_freeze,nuitka,pillow,rst2pdf}: fix shebang

- mingw-w64-emacs-git/PKGBUILD
This makes the build more similar to what the defaults used by stock
emacs and makepkg-mingw. Most of the removed options either didn't apply
to Windows or the selected value was the same as the default.
> emacs-git: remove unnecessary options

- mingw-w64-fontconfig/fontconfig-i686.install
- mingw-w64-fontconfig/fontconfig-x86_64.install
Each time fontconfig is installed or updated, a lengthy
process of font cache update is started automatically.
In certain use-cases, f.e. when one if its dependents
is used for automated build purposes, this causes an
unnecessary and unwanted delay in the process. On
AppVeyor CI free-tier in particular, this process takes
about 5 minutes.
This patch adds the ability to disable this automatic
font cache update, by setting the environment variable
`MSYS2_FC_CACHE_SKIP` to any non-empty value, prior
to lauching `pacman`.
> fontconfig: allow to disable auto font-cache update

- mingw-w64-python-pyzmq/001-mingw-python.patch
- mingw-w64-python-pyzmq/PKGBUILD
I've patched setup.py to shortcut a lot of the platform == win hacks on MSYS. Perhaps this will make the CI build happier. It does get rid of a warning that it can't find libzmq when the build script tries to copy it for MSVC's sake.
> Possibly improve pyzmq build

- mingw-w64-libffi/PKGBUILD
- mingw-w64-libffi/fix_return_size.patch
libffi was broken on 64-bit, any c function returning a struct > 8 bytes and not a multiple of 16 will cause a segfault. This is because between 3.1 and 3.2 somebody changed (size != 1 || size != 2 || size != 4 || size != 8) into (size & (1 | 2 | 4 | 8) == 0), which is not the same.
As an alternative, downgrading to 3.1 or upgrading to git should also fix it.
> Fix libffi 3.2.1 on 64-bit

- mingw-w64-wxwidgets/PKGBUILD
- mingw-w64-wxwidgets/wxWidgets-3.0.2-gcc6-abs.patch
Fix for issue #1578 for the changed ABI in GCC 6.1.
Bumped pkgrel and added patch from upstream for wxWidgets issue 17147 to
fix compile errors regarding overloaded abs() function in the Scintilla editor component.
Referenced wxWidgets bug http://trac.wxwidgets.org/ticket/17147
> Update wxWidgets build files for GCC 6

- mingw-w64-python-jupyter_client/PKGBUILD
Make jupyter_client automatically pull ipykernel. Otherwise, jupyter-console won't work unless
the user manually install ipykernel:
λ python3 C:\msys64\mingw64\bin\jupyter-console
[ZMQTerminalIPythonApp] WARNING | Native kernel (python3) is not available
File "C:\msys64\mingw64\lib\python3.5\site-packages\jupyter_client\kernelspec.py", line 173, in get_kernel_spec
resource_dir = d[kernel_name.lower()]
KeyError: 'python3'
During handling of the above exception, another exception occurred:
File "C:\msys64\mingw64\bin\jupyter-console", line 5, in <module>
app.main()
File "C:\msys64\mingw64\lib\python3.5\site-packages\jupyter_core\application.py", line 267, in launch_instance
return super(JupyterApp, …
> Added python-ipykernel as dependency

- mingw-w64-gdk-pixbuf2/0003-fix-dllmain.patch
- mingw-w64-gdk-pixbuf2/PKGBUILD
- mingw-w64-glib2/0004-glib-prefer-constructors-over-DllMain.patch
- mingw-w64-glib2/PKGBUILD
This fixes part of the problem in https://github.com/Alexpux/MINGW-packages/issues/988.
The [current patch](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-glib2/0004-glib-prefer-constructors-over-DllMain.patch) to avoid `DllMain` is incomplete. If we statically link librsvg or cairo we get **multiple definition of DllMain** linking erros.
The current PR works around `DllMain` for static builds of `gobject.a` and `gdk-pixbuf.a` and only enables `DllMain` when building the shared library.
> Fixes for DllMain in glib2

- mingw-w64-gcc/0017-disable-weak-refs.patch
- mingw-w64-gcc/PKGBUILD
Fixes relocation errors mentioned in #1580
Idea from https://github.com/gcc-mirror/gcc/commit/40c727c8722ab47a821e2fe371f1b6b96be0200d
> gcc: disable weak refs in x86_64

- mingw-w64-ngspice/PKGBUILD
Currently ngspice installs header files is ${MINGW_PREFIX}/share/ngspice/include, which is not usual.
This merge request changes the path to ${MINGW_PREFIX}/include to conform with commonly accepted standards.
> ngspice: Fix path for header files

- mingw-w64-gtk3/PKGBUILD
Here is an update of GTK+ 3. It compiles and works fine for me.
> gtk3: update to version 3.20.9

- mingw-w64-dbus/PKGBUILD
Seems to work fine.
Compiles successfully without `--disable-Werror` so removing it.
> dbus: update to 1.10.10 and enable check

- mingw-w64-boost/PKGBUILD
- mingw-w64-boost/boost-1.60.0-shared_ptr_registration.patch
Fixes the boost-1.60.0 issue described here: https://github.com/boostorg/python/pull/59
and here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-fff5d70162
I have rebuilt the MinGW Boost packages on my Windows machine with the patched recipe and they work fine.
> Fixes boost 1.60.0 issue

- mingw-w64-lua-bitop/PKGBUILD
The bit module, from Luajit, for regular Lua.
Bitop is compatible with lua 5.2 but not 5.3, which is why I did not add a lua-bitop package as well.
> Add lua51-bitop

- mingw-w64-libvterm-bzr/PKGBUILD
libvterm is an abstract terminal emulator library, used by Neovim to implement terminal support.
> Add libvterm-bzr

- mingw-w64-cmake/0002-Implement-Qt5-static-plugin-support.patch
- mingw-w64-cmake/PKGBUILD
Fixes #1577 
Part of 0002-Implement-Qt5-static-plugin-support.patch had to be recreated due to fuzz and miscompilation
@Optiligence could you test if resolves your issues?
Also it would be great if someone could test static plugins.
> cmake: update to 3.6.1

- mingw-w64-libarchive/PKGBUILD
See https://bugs.archlinux.org/task/49888
This broke at least cmake.
> libarchive: it depends on lz4 since 3.2.1

- mingw-w64-libarchive/PKGBUILD
https://bugs.archlinux.org/task/49888
fixes Alexpux/MINGW-packages#1663
> add lz4 dependency to libarchive

- mingw-w64-openscenegraph-git/PKGBUILD
was removed by mistake in last commit
>  openscenegraph-git: put back release package DESTDIR

- mingw-w64-jq/PKGBUILD
Oniguruma is a required dependency since version 1.5
> jq: make it depend on oniguruma

- mingw-w64-qt5-static/PKGBUILD
- mingw-w64-qt5/PKGBUILD
see https://blog.qt.io/blog/2016/06/08/qt-5-6-1-released/
compiles fine up until it hits https://github.com/Alexpux/MINGW-packages/issues/1689
> qt5[-static]: upgrade to hot fix 5.6.1-1

- mingw-w64-python-psutil/0001-MSYS-Allow-detecting-when-running-on-MSYS.patch
- mingw-w64-python-psutil/0002-msys-Fixes-for-msys2.patch
- mingw-w64-python-psutil/PKGBUILD
psutil (process and system utilities) is a cross-platform library for retrieving information on running processes and system utilization (CPU, memory, disks, network) in Python. It is useful mainly for system monitoring, profiling and limiting process resources and management of running processes.
I cared for this library so I could install wdb, so I haven't checked the rest of it.
> adding python-psutil: 4.3.0

- mingw-w64-cairo/0027-win32-print-fix-unbounded-surface-assertion.patch
- mingw-w64-cairo/PKGBUILD
Taken from upstream:
https://cgit.freedesktop.org/cairo/commit/?id=90d50cd92315d6760069ad8062aba5e297370b20
Discussion at:
https://lists.cairographics.org/archives/cairo/2016-June/027445.html
> cairo win32-print: fix unbounded surface assertion

- mingw-w64-qt5-static/0126-qt5-Workaround-crashes-in-QtQml-code-related-to-dead-store.patch
- mingw-w64-qt5-static/PKGBUILD
- mingw-w64-qt5/0126-qt5-Workaround-crashes-in-QtQml-code-related-to-dead-store.patch
- mingw-w64-qt5/PKGBUILD
workaround crashes in QtQml code related to dead-store elimination
see https://bugreports.qt.io/browse/QTBUG-55482
> qt5[-static]: add upstream patch for QTBUG-55482

- mingw-w64-SDL2_mixer/PKGBUILD
- mingw-w64-SDL2_mixer/SDL2_mixer-2.0.1-find_lib.mingw.patch
While #865 was fixed by my pull request #867, the fix was completely
removed from SDL2_mixer in 276d9bd. Now this fixes #1641.
Bring back dynamic loading of shared libraries, this time by patching
configure.in and subsequently running autoreconf.
> SDL2_Mixer: help ./configure find shared libraries for dynamic loading again

- mingw-w64-imagemagick/002-7.0.3.1-build-fixes.patch
- mingw-w64-imagemagick/PKGBUILD
- mingw-w64-libraqm/PKGBUILD
- mingw-w64-libraqm/libraqm-enable-shared.patch
- mingw-w64-libwebp/PKGBUILD
imagemagick - 7.0.3.1 -
Update to latest version
add libraqm as dependency
Drop winpath.patch reference
rekey 002-7.0.3.1-build-fixes.patch
libwebp - 0.5.1
Update to latest version
add libwebpextras to package
libraqm - 0.2.0
Update to latest version
add patch to build static and shared libs
> ImageMagick and dependencies

- mingw-w64-SDL2_mixer/PKGBUILD
- mingw-w64-SDL2_mixer/SDL2_mixer-2.0.1-libtool_windres.mingw.patch
* Bump pkgrel to 2.
* Add smpeg2 to makedepends, some of its M4 macros are needed by autoreconf.
* Add another patch to compile version.rc into a libtool object (which suddenyl became
necessary after running autoreconf).
* Unpack the zip archive with bsdtar. @mati865: I believe we prefer the zip file over
tar.gz, because the latter contains symlinks that we have trouble to unpack.
> SDL2_Mixer: build fixes

- mingw-w64-libtool/PKGBUILD
@Alexpux, I don't know if it's required, but updating binutils from 2.25 to 2.27 is a big deal and libtool wasn't updated since then.
Now when we are at current binutils the ABI should be stable. So after upgrading GCC recompilation of libtool should be sufficient and we shouldn't have to recompile binutils.
> libtool: rebuild after binutils change

- mingw-w64-waf/PKGBUILD
Is there a switch to include *all* tools? Maybe that should be done in the future.
> Waf: Update to 1.9.4 and include unity tool

- mingw-w64-ghc/0001-Add-Windows-import-library-support-to-the-Runtime-Li.patch
- mingw-w64-ghc/0001-Add-relocation-type-R_X86_64_REX_GOTPCRELX.patch
- mingw-w64-ghc/0001-Enable-checkProddableBlock-on-x86_64.patch
- mingw-w64-ghc/0001-Fix-configure-detection.patch
- mingw-w64-ghc/0001-Fix-incorrect-calculated-relocations-on-Windows-x86_.patch
- mingw-w64-ghc/0001-Remove-special-casing-of-Windows-in-generic-files.patch
- mingw-w64-ghc/0001-Rework-CC-CC_STAGE0-handling-in-configure.ac.patch
- mingw-w64-ghc/0001-Switch-to-LLVM-version-3.8.patch
- mingw-w64-ghc/0001-Unstaged.patch
- mingw-w64-ghc/0001-configure.ac-Remove-checks-for-bug-9439.patch
- mingw-w64-ghc/PKGBUILD
- mingw-w64-ghc/build.mk
I am quite satisfied that this builds without an inplace _mingw_ tree and runs without that.
In other words, this is a clean _ghc_ build for _mingw_, if you know what I am talking about.
But it still needs _ghc_ along with _alex_ and _happy_ to build itself, which we can't get around.
I am not sure how to put these in _makedepends_ or _prepare()_.
It also works with _mingw-llvm_ 3.8.
> Add ghc 8.0.1

- mingw-w64-rust/PKGBUILD
Alright, so this is my first pull request to MINGW, tell me if I'm doing something wrong.
All the changes were based on Arch Linux's rust PKGBUILD, PR #1094 or the previous PKGBUILD.
It builds LLVM itself, so it takes FOREVER to build. I believe once we get CLANG/LLVM on 3.9 it should build with the system's LLVM.
> Update Rust to 1.12.0

- mingw-w64-poco/014-unbundled-expat.patch
- mingw-w64-poco/PKGBUILD
fixes #1823
xmlparse.cpp (expat) was included in mingw32 build when POCO_UNBUNDLED is set and caused 'XMLUtf8Encode undefined reference' error when building
> Poco 1.6.0 PKGBUILD fix

- mingw-w64-kicad-doc/PKGBUILD
- mingw-w64-kicad-git/PKGBUILD
I created a new package kicad-doc that packages already created doc files for the KiCad project to avoid having to port the packages needed to create the doc files under MSys2.
Tim S.
> Fixed build issue in kicad-git

- mingw-w64-go/PKGBUILD
Just a small update to the go package to 1.7.1. This is also a reminder to update the official pacman repo. The current version is 1.4.2 which was released at the start of 2015!
> Updated the go package to 1.7.1

- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/force-curl-rust.patch
Update rust package to 1.12.1. Small changes in preparation for version 1.13.0: https://blog.rust-lang.org/2016/10/20/Rust-1.12.1.html 
I noticed that 1.12.0 hasn't been updated in the official pacman repo. Is there a reason for that? Is there a way I can get that updated?
CI will fail because it will time out.
> Updated rust package to 1.12.1

- mingw-w64-gdb/PKGBUILD
Enables text interface (TUI) in the build of GDB. The TUI can be used only in cmd.exe and not in mintty, and is somewhat buggy on Windows 10 as documented in #1744. Nevertheless, it serves its purpose.
> Adds a TUI in GNU debugger, GDB.

- mingw-w64-gdk-pixbuf2/0001-windows-Remove-old-codepage-ABI-compat-code.patch
- mingw-w64-gdk-pixbuf2/PKGBUILD
This makes GdkPixbuf.Pixbuf.savev() work in bindings
and removes the need to fixup the .gir file
after build.
Doesn't break ABI/API.
For more info see the patch or the upstream bug report:
https://bugzilla.gnome.org/show_bug.cgi?id=773760
> gdk-pixbuf: Fix gi API

- mingw-w64-chromaprint/PKGBUILD
fftw is smaller and has less dependencies. This is the only
thing pulling in ffmpeg in gstreamer afaics
(besides the optdepends in opencv)
> chromaprint: use fftw instead of ffmpeg

- mingw-w64-curl/PKGBUILD
There are 11 security advisories associated with this version. It's rather important to update.
> cURL: update to v7.51.0

- mingw-w64-gst-plugins-bad/PKGBUILD
> gst-plugins-bad: depend on libsrtp

- mingw-w64-gst-plugins-good/PKGBUILD
- mingw-w64-gst-plugins-good/Revert-directsoundsink-Fix-sleep-for-buffer-time-low.patch
See https://bugzilla.gnome.org/show_bug.cgi?id=773681
The added patch reverts the git commit introducing this bug.
> gst-plugins-good: Fix 100 CPU when using directsoundsink

- mingw-w64-python2/0670-msys-convert_path-fix-and-root-hack.patch
- mingw-w64-python3/0670-msys-convert_path-fix-and-root-hack.patch
Found this bug because on msys2, `python setup.py bdist_wheel` produces totally empty wheels, save for metadata! Turns out that `bdist_wheel` calls `install` with a chroot into the build directory set. Without this patch, applying the chroot caused the internal install to get installed to the root of the drive, so nothing ever got copied to the wheel.
This is the result of a solid 6 hours of debugging hahaha
> Python: Fixed patch for distutils.util.change_root to account for cases when neither path has a drive letter

- mingw-w64-imagemagick/001-7.0.1.3-relocate.patch
- mingw-w64-imagemagick/002-7.0.3.1-build-fixes.patch
- mingw-w64-imagemagick/004-7.0.3.5-build-fixes.patch
- mingw-w64-imagemagick/PKGBUILD
Additionally:
Fixed the issue of not finding the coder and filter modules.  Fixes: #1885 
Updated constants to Imagemagick-7
Fixed compile warnings due to redefinition of MAGICKCORE_HAVE_ERF
> ImageMagick: Update to 7.0.3.5

- mingw-w64-sfml/PKGBUILD
Please build and distribute updated i686 and x86_64 packages.
> mingw-w64-sfml: updated to release version 2.4.1

- mingw-w64-gcc/0017-diagnostic-color.patch
- mingw-w64-gcc/PKGBUILD
Patch by Hannes Domani <ssbssa@yahoo.de>, see
https://sourceforge.net/p/msys2/mailman/message/34910994/
> gcc: Detect mintty or the Windows console for diagnostic colors

- mingw-w64-clang/0502-hack-to-use-64-bit-time-for-mingw.patch
- mingw-w64-clang/PKGBUILD
> clang: fix 32 bit LLDB build

- mingw-w64-gtk3-git/PKGBUILD
Gtk 3.22.x was [split off to branch gtk-3-22 last month](https://blog.gtk.org/2016/10/11/this-week-in-gtk-19/), but more notably master is now off chasing gtk4 (and also not building on MSYS2). Until everything shakes out, make gtk3-git build the stable branch, but allow easy branch switching in case people want to try to experiment with master.
> gtk3-git: chase stable, but add branch var

- mingw-w64-gtk3-git/PKGBUILD
Git master has added some AX_* macros, meaning that autoconf-archive is now required if building that branch.
The build is still broken though. This just gets it further.
```
$ MINGW_INSTALLS=mingw64 makepkg-mingw -sf
[...]
libtool: compile:  x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I.. -DG_LOG_DOMAIN=\"Gdk\" -DG_LOG_USE_STRUCTURED=1 -DGDK_COMPILATION -I.. -I../gdk -I.. -DG_ENABLE_DEBUG -DG_ENABLE_CONSISTENCY_CHECKS -DGLIB_MIN_REQUIRED_VERSION=GLIB_VERSION_2_48 -DGLIB_MAX_ALLOWED_VERSION=GLIB_VERSION_2_50 -pthread -mms-bitfields -IC:/msys64/mingw64/include/pango-1.0 -IC:/msys64/mingw64/include/gdk-pixbuf-2.0 -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/cairo -IC:/msys64/mingw64/include/pixman-1 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/freetype2 …
```
> gtk3-git (@master): add missing makedepend

- mingw-w64-rust/PKGBUILD
Do not merge this yet.
I've got rust building on 64-bit and 32-bit mingw, but cargo (rust's package manager) stubbornly won't listen to any flags I give it, so it won't compile on i686.
Is it okay if we just don't include cargo with the i686 version? If yes than wait on merging this, if not just merge it, it'll be useful to some people.
> Updated rust package to 1.13, rustc now compiles on i686

- styrene-git/PKGBUILD
Styrene is a developer tool for bundling up combinations of local native builds and binary MSYS packages into convenient app bundles shaped for regular Windows users. "All" developers need to do is maintain their normal .desktop files and write a config file for their app. The Styrene tool takes care of all the repackaging and installer-making details.
https://github.com/achadwick/styrene
Would it be OK to incorporate this relatively early draft of the tool into MINGW-packages in -git form? Stable PKGBUILD to follow when this thing is actually stable.
As discussed in Alexpux/MSYS-packages#759, the code belongs in MINGW-packages.
> Add styrene-git

- mingw-w64-opencv/0008-calib3d-fix-missing-cv-redirectError-symbol-error.patch
- mingw-w64-opencv/PKGBUILD
Requires vtk 7.0.0-2.
Switched to the official opencv repo.
opencv_contrib is needed by gst-plugins-bad to build the opencv plugin.
> opencv: add opencv_contrib

- mingw-w64-libxml2/0026-mingw-relocate.patch
- mingw-w64-libxml2/PKGBUILD
Also eliminating one compile time warning due to LIBXML-STATIC redefinition
Fixes #1864 , partially #1670
> libxml2: Eliminating hard-coded paths in pkg-config and xml-config files

- mingw-w64-docbook-xml/PKGBUILD
- mingw-w64-docbook-xml/docbook-xml-i686.install
- mingw-w64-docbook-xml/docbook-xml-x86_64.install
I have tested 5.0 sample documents using:
`XML_CATALOG_FILES="/mingw64/etc/xml/catalog" xmllint  --noout --nonet --relaxng http://docbook.org/xml/5.0/rng/docbook.rng valid.xml`
resulted:
```
Resolve: sysID http://docbook.org/xml/5.0/rng/docbook.rng
10564 Parsing catalog C:/Dev/msys64/mingw64/etc/xml/catalog
C:/Dev/msys64/mingw64/etc/xml/catalog added to file hash
C:/Dev/msys64/mingw64/etc/xml/docbook-xml not found in file hash
10564 Parsing catalog C:/Dev/msys64/mingw64/etc/xml/docbook-xml
C:/Dev/msys64/mingw64/etc/xml/docbook-xml added to file hash
Trying system delegate C:/Dev/msys64/mingw64/etc/xml/docbook-xml
Using rewriting rule http://docbook.org/xml/5.0
valid.xml validates
```
And with an invalid file:
`XML_CATALOG_FILES="/mingw64/etc/xml/catalog" xmllint  --noout --nonet --relaxng …
> docbook-xml: adding v 5.0

- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/force-pthread.patch
~~Probably `RUSTFLAGS="$RUSTFLAGS -C link-args='-lffi -lpthread'"` can be removed but I'm waiting for compilation to finish.~~ If everything goes well I'll update this PR.
CC @hcorion
EDIT: `RUSTFLAGS` must stay for now.
> rust: link to pthread and use _Unwind_Resume

- mingw-w64-uchardet/PKGBUILD
uchardet shouldn't conflict with uchardet-git since it does not exist in msys2 repos. 
I have a custom made package named uchardet-git and pacman always tries to replace it with uchardet from the repos on executing `pacman -Syyu`. For now I have to name my custom package as uchardet (without -git part) as a workaround.
This commit fixes it.
Also removed unnecessary git dependency.
> uchardet: Fix PKGBUILD

- mingw-w64-python3-cairo-git/PKGBUILD
Addresses the build failures in Alexpux/MINGW-packages#195.
> python3-cairo-git: package(): fix argument order

- mingw-w64-chromaprint/PKGBUILD
- boost is no longer needed
- KissFFT used instead of FFTW to remove another dependency (slightly slower)
- avoid potential dependency on swresample/avresample (untested)
- add static lib
> chromaprint: update to 1.4

- mingw-w64-unbound/PKGBUILD
Hello,
I have been able to get the newest version of unbound to build correctly. The only other change I have made is to overwrite the libtool path used by the make file to point to ${MINGW_PREFIX}/bin instead of the one that comes with the unbound package as this seemed to fully resolve the issue I was seeing before.
> Fix mingw-w64-unbound to build correctly

- mingw-w64-gdk-pixbuf2/gdk-pixbuf2-i686.install
- mingw-w64-gdk-pixbuf2/gdk-pixbuf2-x86_64.install
> gdk-pixbuf2: install script: correcting path to loaders.cache

- mingw-w64-gdk-pixbuf2/0001-windows-rework-loaders-cache-relocation-support.patch
- mingw-w64-gdk-pixbuf2/PKGBUILD
Changes the loaders cache format to use paths relative to the
package installation directory.
This is the last thing preventing gtk+ apps from working
if the msys2 root is renamed.
Also submitted upstream:
https://bugzilla.gnome.org/show_bug.cgi?id=776081
> gdk-pixbuf2: Make loaders cache relocatable

- mingw-w64-adwaita-icon-theme/0001-symbolic-re-render-send-to.patch
- mingw-w64-adwaita-icon-theme/PKGBUILD
News summary:
3.21.2
- network-wireless-connected improvements
- document-edit, text-editor, modem-symbolic shape improvement
- baseline-align folders
- reshape folders
- add a context-menu cursor
- improve grab and dnd-no-drop cursors
3.21.91
- user-available-symbolic transparency fix
- calculator app icon update
- fixed cursors
- folder-download-symbolic style fixes
- vertical visual centering for go-up, go-down-symbolic icons
3.22.0
- simplified input-tablet-symbolic
- opacity fixes for networking-vpn-acquring
- invisible go-down-symbolic
> Adwaita icon theme: update to 3.22.0

- mingw-w64-pngcrush/PKGBUILD
> pngcrush: 1.8.8 --> 1.8.10

- mingw-w64-hunspell-en/PKGBUILD
By default hunspell needs en_US instead of en_US-large.
> rename {lang}-large to {lang}

- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/force-pthread.patch
Tested and builds both 64-bit and 32-bit.
> Updated rust to 1.14.0

- mingw-w64-lua/PKGBUILD
As per title. The install path for Lua's license was incorrect.
> Fix Lua license install path

- mingw-w64-ngraph-gtk/PKGBUILD
I want to add ngraph-gtk package to MINGW-package.
Ngraph is the program to create scientific 2-dimensional graphs for researchers and engineers.
Graphs can be exported to PostScript, SVG, PNG or PDF format.
https://github.com/htrb/ngraph-gtk/
> add ngraph-gtk package.

- mingw-w64-libmypaint-git/PKGBUILD
- mingw-w64-libmypaint/PKGBUILD
* `libmypaint-git` was generating the wrong DLL name (`msys-` prefix in `/mingw*/bin`)
* `libmypaint*`: were mistakenly depending on `gobject-introspection`.
> libmypaint*: various fixes

- mingw-w64-libusb/PKGBUILD
From 1.0.21 libusb provides an alteranative to the regular WinUSB
backend called UsbDk, available from https://github.com/daynix/UsbDk .
This new backend allows to dynamically take control over any USB
device without removing the vendor driver.
The resulting libusb libraries have compatible binary APIs but are
mutually exclusive.
> RFC: libusb: bump version to 1.0.21 and build a UsbDk variant

- mingw-w64-catch/PKGBUILD
I briefly tested the resulting catch 1.6.0 package (64-bit version only) and it seems to work fine.
> catch: Update from 1.5.0 to 1.6.0.

- mingw-w64-clang/0112-objc-eh-personality.patch
- mingw-w64-clang/PKGBUILD
#2078 
Use the correct ObjC EH personality
This fixes ObjC exceptions on Win64 (which uses SEH), among others.
Patch by Jonathan Schleifer!
git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@291408 91177308-0d34-0410-b5e6-96231b3b80d8
> Add support for SjLj and SEH Exception Handling for ObjC language

- mingw-w64-diffutils/PKGBUILD
Closes Alexpux/MINGW-packages#2048.
> diffutils: gettext is a runtime dependency

- mingw-w64-pygobject/PKGBUILD
If it's omitted, build failures like the following happen:
```
checking for python module _thread... yes
checking whether to enable threading in pygobject... yes
../pygobject-3.22.0/configure: line 13778: ./libtool: No such file or directory
checking for x86_64-w64-mingw32-pkg-config... /mingw64/bin/x86_64-w64-mingw32-pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.38.0... yes (version 2.50.2)
checking for FFI... yes
checking for GIO... yes
checking for GI... yes
checking for CAIRO... yes
checking for PYCAIRO... no
configure: error: Package requirements (py3cairo >= 1.10.0
) were not met:
No package 'py3cairo' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, …
```
> pygobject: python-cairo is a build-time dep

- mingw-w64-gtk2/0013-fix-dead-keys-part-1.patch
- mingw-w64-gtk2/0018-fix-gdkwin32keys-header.patch
- mingw-w64-gtk2/PKGBUILD
Adding [the official patch](https://bugzilla.gnome.org/show_bug.cgi?id=775163) that is missing from #1979. It completes the series of commits that were only partially merged there.
This pull request also rolls back custom fixes for this header issue that were introduced here afterwards.
I've tested that it works by compiling Geany successfully with this version.
> gtk2: Use gdkwin32keys.h patch from upstream instead of a custom fix

- mingw-w64-opencl-headers/PKGBUILD
See issue #2116 (mingw-w64-opencl-headers: missing cl_d3d10.h and cl_d3d11.h).
> opencl-headers: add d3d and dx9 headers

- mingw-w64-snappy/PKGBUILD
the tests were never copied to the build directory
so i’m not sure how check() ever worked the way it was before
> snappy: update to 1.1.4

- mingw-w64-qt5/PKGBUILD
Fix for the static compile, so currently unused for most people
> mingw-w64-qt5/PKGBUILD: fixed the sql build options for qt 5.8.0

- mingw-w64-osslsigncode/PKGBUILD
Turns out this was the full error:
```
$ osslsigncode
F:/msys64/mingw64/bin/osslsigncode.exe: error while loading shared libraries: libgsf-1-114.dll: cannot open shared object file: No such file or directory
```
osslsigncode uses libgsf for `.msi` support.
> osslsigncode: add libgsf as a dependency

- mingw-w64-libcerf/PKGBUILD
- mingw-w64-mesa/PKGBUILD
- mingw-w64-mingw-w64-libsigsegv-git/PKGBUILD
- mingw-w64-mingw-w64-libsigsegv-git/fix-win64.patch
- mingw-w64-readline/PKGBUILD
- mingw-w64-readline/readline70-001
- mingw-w64-readline/readline70-002
- mingw-w64-readline/readline70-003
mingw-w64-readline - 7.0 - patchlevel 3
mingw-w64-libcerf - 1.5 - new package
mingw-w64-libsigsegv - git version - new package
> mingw-w64-mesa - 3.0.4 - Update to latest version

- mingw-w64-git-lfs/0001-Translate-git-paths-from-msys-to-windows.patch
- mingw-w64-git-lfs/PKGBUILD
- Fetch go dependencies in prepare() instead of build.
- Use actual git sources for git-lfs instead of fetching them with go get.
> git-lfs: bump version + some cleaning

- mingw-w64-rust/PKGBUILD
- mingw-w64-rust/pass-windows-paths-to-python-script.patch
Tested 64 bit rust and cargo, currently I don't have time to build and test 32 bit.
`pass-windows-paths-to-python-script.patch` will be helpful at next release when `--disable-rustbuild` is removed. I had no time to fully fix new build system.
> rust: update to 1.15.1

- mingw-w64-mesa/PKGBUILD
- mingw-w64-mesa/osmesa.pc
Besides, the header files are necessary for using osmesa. 
I wonder why they were deleted in a070cca548397fa11feb7dd4485aafdafaddfe40.
> mesa: update to version 17.0.0

- mingw-w64-zlib/010-unzip-add-function-unzOpenBuffer.patch
- mingw-w64-zlib/PKGBUILD
Fixed the minizip checkout to specific commit revision, and updated line numbers in one patch.
> mingw-w64-zlib: fixed patches for latest minizip

- mingw-w64-make/PKGBUILD
- mingw-w64-make/make-getopt.patch
- mingw-w64-make/make-linebuf-mingw.patch
Fixes many build problems in current git snapshot.
> mingw-w64-make: switch from git to official 4.2.1 release

- mingw-w64-python-requests/PKGBUILD
- mingw-w64-python-sphinx/PKGBUILD
Add a build for `mingw-w64-python-requests` since Sphinx depends on it.
> Python requests v2.13.0

- mingw-w64-curl/0001-Make-cURL-relocatable.patch
- mingw-w64-curl/0002-cURL-Get-relocatable-base-from-.dll-instead-of-.exe.patch
- mingw-w64-curl/0003-urldata-include-curl_sspi.h-when-Windows-SSPI-is-ena.patch
- mingw-w64-curl/PKGBUILD
This required a backport of a fix that already made it into cURL's
master branch for a build error discovered only after 7.53.0 was
released.
While at it, I just regenerated the patch files for easier future
adjustments (of course, the easiest would be to just maintain these
patches in a long-running Git branch instead of patch files, but that
is too much to hope for).
> cURL 7.53.0

- mingw-w64-curl/PKGBUILD
*UPDATE: Only mingw-w64-curl/PKGBUILD was modified (see discussion below).*
New package provides cURL compiled with WinSSL. It will be used with git as an alternative option to the ca-cert file: https://github.com/git-for-windows/git/issues/301#issuecomment-281644692.
I copied all the patches and the PKGBUILD file from `mingw-w64-curl` to `mingw-w64-curl-winssl` and modified the PKGBUILD files so that they're still the same except the value of the `_variant` variable.
The same technique is used in `mingw-w64-qt5` and `mingw-w64-qt5-static` packages. If there is a better way to share sources and patches among different packages, I'm ready to do some rework of the changes.
`mingw-w64-curl-winssl` provides the same binary files as `mingw-w64-curl`, so they're marked as conflict. You cannot …
> mingw-w64-curl: add name suffix to alternative packages

- mingw-w64-inkscape/PKGBUILD
Inkscape 0.92 has some new dependencies.
We now have libvisio (#2194) and already had potrace for some time.
> Inkscape: update dependencies

- mingw-w64-gcc-git/PKGBUILD
`tar` is required by `libtool` which is part of `base-devel` group.
> gcc-git: generate _realpkgver from given branch

- mingw-w64-gcc-git/PKGBUILD
- mingw-w64-gcc/PKGBUILD
mingw-w64-gcc and mingw-w64-gcc-git have minor differences in the PKGBUILD. For example mingw-w64-gcc-git specifies more "provides" sections for the tools. To make the maintenance easier, I unified mingw-w64-gcc and mingw-w64-gcc-git, by taking some code from mingw-w64-gcc-git to mingw-w64-gcc.
> mingw-w64-gcc{,-git}: unified layout, and minor code cleanup

- mingw-w64-npm/PKGBUILD
After mailing AppVeyor support they said CI is fixed.
This PR was created to verify it.
Also there was typo in npm PKGBUILD
> npm: minor correction to PKGBUILD

- mingw-w64-libsystre/PKGBUILD
- mingw-w64-libtre-git/001-autotools.patch
- mingw-w64-libtre-git/PKGBUILD
build of `mingw-w64-libsystre` was broken with a trivial problem missing round braces around provides, conflicts and replaces. build of `mingw-w64-libtre-git` did not specify a git commit, and the upstream head had changes.
> fixed tre libs build

- mingw-w64-gdb/PKGBUILD
- mingw-w64-gdb/gdb-7.12-dynamic-libs.patch
Fixes https://github.com/Alexpux/MSYS2-packages/issues/716.
Future versions of gdb will have a flag for that[1].
[1] https://sourceware.org/bugzilla/show_bug.cgi?id=21187
> gdb: Fix crash on mingw32

- mingw-w64-xmlstarlet/PKGBUILD
Minor whitespace change, for consistency between different PKGBUILD files. Renamed `_name` to `_realname`.
> mingw-w64-xmlstarlet: use realname instead of name

- mingw-w64-jxrlib/PKGBUILD
`jxrlib` download had a broken the sha256, so I switched to the Debian launchpad download. The packages are identical except that the lauchpad version does not ship the pre-compiled binaries `hdr2hdr.exe` and `imagecomp.exe`.
I also slightly changed the PKGBUILD formatting.
> mingw-w64-jxrlib: changed download to launchpad offical

- mingw-w64-opencv/0008-mingw-w64-cmake-lib-path.patch
- mingw-w64-opencv/PKGBUILD
When trying to fix the ITK builds I ran into a problem with the opencv cmake files. As you can see in the patch, opencv looks for the lib path at `${OpenCV_CONFIG_PATH}/${OpenCV_ARCH}/${OpenCV_RUNTIME}/lib`. However, mingw stores the lib files under `${OpenCV_CONFIG_PATH}/lib`, where `OpenCV_CONFIG_PATH` is e.g. `/msys64/mingw64` and doesn't separate them into arch etc like the original makefile does.
> Fix detection of opencv lib path

- FAIL_LIST.md
- mingw-w64-itk/PKGBUILD
This fixes the ITK builds.
Before this can be built however, a new package of VTK needs to be released on pacman because pacman does not have the latest build as described here: https://github.com/Alexpux/MINGW-packages/issues/1670#issuecomment-285211099.
After that OpenCV should be able to be built and there needs to be a new release of it using the fix from https://github.com/Alexpux/MINGW-packages/pull/2268.
Finally, after the VTK and OpenCV pacman packages are updated, this PR will be buildable. I tested it locally with the fixes described above applied.
> Fix ITK builds.

- mingw-w64-mbedtls/PKGBUILD
Fixes CVE-2017-2784
https://tls.mbed.org/tech-updates/security-advisories/mbedtls-security-advisory-2017-01
> mbedtls: Updated to 2.4.2 (security update)

- mingw-w64-wineditline/PKGBUILD
> wineditline: Updates to 2.201

- mingw-w64-xapian-core/PKGBUILD
The official download server has an expired SSL certificate and I can not get it to work.
Switched to Ubuntu mirror.
I also tried updating xapian to 1.4.3, but it has a problem (missing link against math library).
I've reported the issue upstream.
> mingw-w64-xapian-core: switched (broken) download server

- mingw-w64-matio/PKGBUILD
Added a native C++ Matlab file reader with support for Matlab files version 4, 5, and 7.3 (with hdf5).
> mingw-w64-matio: added

- mingw-w64-hyphen/PKGBUILD
- mingw-w64-lcov/PKGBUILD
- mingw-w64-ngspice/PKGBUILD
- mingw-w64-udis86/PKGBUILD
sourceforge.io is for user's subdomains, not for download servers
seem that [someone](https://github.com/Alexpux/MINGW-packages/commit/92975171013db4c0c4b6298c94795ed2808bdb28) overplayed with sed :laughing:
> downloads.sourceforge.io -> downloads.sourceforge.net

- mingw-w64-xapian-core/0001-exp10-build-fix.patch
- mingw-w64-xapian-core/PKGBUILD
mingw-w64-xapian-core: updated to 1.4.3 and switched back to official download server.
Includes a patch against an exp10() missing dependency. Tested on i686 and x86_64.
> mingw-w64-xapian-core: updated to 1.4.3

- mingw-w64-python3-cairo/PKGBUILD
msys2 python3 should not be a dependency of mingw-w64-python3-cairo, removed.
As discussed in https://github.com/Alexpux/MINGW-packages/issues/2318
> mingw-w64-python3-cairo: removed msys2 python3 from makedepends

- mingw-w64-chipmunk/PKGBUILD
The newest cocos2d-x need chipmunk 7 to run.
> upgrade build script for chipmunk 7.0.1

- mingw-w64-gtkspell/001-localedir-relocation.patch
- mingw-w64-gtkspell/PKGBUILD
Translations were not working because `LOCALEDIR` was an absolute path (`C:/building/msys64/mingw64/share/locale`).
> gtkspell: fix relocation of translations

- mingw-w64-python3/0950-mingw-w64-XP3-compat-GetProcAddress-GetTickCount64.patch
On Windows XP SP3 there is no GetTickCount64, current workaround for this problem has a bug: ```GetProcAddress(hKernel32, "GetTickCount64")``` returns ```NULL```, but next if compares result with ```-1``` and so it tries to call function by ```NULL``` address. This leads to segfault.
> python3: segfault fix in GetTickCount64

- mingw-w64-python-appdirs/PKGBUILD
- mingw-w64-python-beautifulsoup4/PKGBUILD
- mingw-w64-python-chardet/PKGBUILD
- mingw-w64-python-coverage/PKGBUILD
- mingw-w64-python-html5lib/LICENSE
- mingw-w64-python-html5lib/PKGBUILD
- mingw-w64-python-lxml/PKGBUILD
- mingw-w64-python-lxml/use-distutils-get_platform.patch
- mingw-w64-python-nose/PKGBUILD
- mingw-w64-python-packaging/PKGBUILD
- mingw-w64-python-pbr/PKGBUILD
- mingw-w64-python-pretend/PKGBUILD
- mingw-w64-python-py/PKGBUILD
- mingw-w64-python-pyparsing/PKGBUILD
- mingw-w64-python-webencodings/PKGBUILD
mingw-w64-python-lxml  - 3.7.3 - Update to latest version, update patch
mingw-w64-python-nose - 1.3.7 - make aliases (nosetests2 and nosetest3 to faciltate upgrading python to 3.6)
mingw-w64-python-pbr - 2.0.0 - Update to latest version
mingw-w64-python-py - 1.4.33 - Update to latest version
mingw-w64-python-pyparsing - 2.2.0 Update to latest version
mingw-w64-python-beautifulsoup4 - 4.5.3 - New Package
mingw-w64-python-chardet - 2.3.0 - New Package
mingw-w64-python-html5lib - 0.9999999 - New Package
mingw-w64-python-packaging - 16.0 - New Package
mingw-w64-python-pretend - 1.0.0 - New Package
mingw-w64-python-webencodings - 0.5.1 - New Package
> mingw-w64-ptyhon-coverage - 4.3.4 - Update to latest version

- mingw-w64-libmicrohttpd/PKGBUILD
Restored compatibility with WinXP
> Updated GNU libmicrohttpd to latest upstream version (0.9.53)

- mingw-w64-ffmpeg/PKGBUILD
Check fails with `SDL_main` maybe its needed to uncomment that workaround?
> ffmpeg: Updated to 3.3

- mingw-w64-thrift/0001-thrift-build-option-defines.patch
- mingw-w64-thrift/PKGBUILD
Use newer than WinXP as default build target
> mingw-w64-thrift: use newer than WinXP as default build target

- mingw-w64-mypaint-git/PKGBUILD
MyPaint now uses setuptools for installation. No more SCons! Although build needs to be a clean build currently, because of silly layout reasons.
https://github.com/mypaint/mypaint/projects/4
> mypaint-git: upstream has switched to setuptools.

- mingw-w64-fox/PKGBUILD
This fixes segfaults in FXString.vformat() on Windows-10.
See discussion here:
https://sourceforge.net/p/foxgui/mailman/message/35797127/
> Update fox toolkit to 1.6.54

- mingw-w64-gdk-pixbuf2/PKGBUILD
(they were disabled in 5b53585ec2b119eaf37517d84ab2a1940430146b)
GDI+ loaders neet to be built into gdk-pixbuf to prevent the bug described in https://bugzilla.redhat.com/show_bug.cgi?id=795152#c1 (see also https://bugs.launchpad.net/inkscape/+bug/1467103)
> gdk-pixbuf2: re-enable gdiplus loaders

- mingw-w64-qemu/PKGBUILD
Fixes #1407.
Tbh I'm not sure if enabling libusb is correct. The [commit disabling](https://github.com/Alexpux/MINGW-packages/commit/1be509d7aaef5deede76a3632e926ea26ed97799) it only said it was disabled to fix build issues. At least on my setup I can build with it enabled (and also with the other disabled features enabled).
> qemu: Update to 2.9.0 , add missing dependency, and enable libusb feature again

- mingw-w64-wxwidgets/PKGBUILD
Changed download URL to "https://github.com/wxWidgets/wxWidgets/releases/download/v${pkgver}/wxWidgets-${pkgver}.tar.bz2".
Moved "${MINGW_PACKAGE_PREFIX}-cppunit" to checkdepends.
Added more "--with-libs" to configure command.
Deleted patch files that no longer worked.
Commented out out the applying of "wxWidgets-3.0.0-gcc-codelight.patch".
I believe the codelight patch is no longer needed.
> wxwidgets: Updated version to "3.0.3".

- mingw-w64-binutils-git/PKGBUILD
- mingw-w64-gcc-git/PKGBUILD
- mingw-w64-gdb-git/PKGBUILD
Use encrypted Git protocol for gcc.gnu.org and sourceware.org VCS servers.
> improve vcs protocols

- mingw-w64-gcc-git/0017-gcc-7-branch-Enable-std-experimental-filesystem.patch
- mingw-w64-gcc-git/PKGBUILD
1. Fix patch for std::experimental::filesystem for gcc-7-branch.
2. `git archive` seems not supporting HTTPS. Revert to the GIT protocol.
> mingw-w64-gcc-git: Fix patch 0017 and PKGBUILD.

- mingw-w64-gtk3/0001-Revert-clipboard-Try-the-mimetype-first.patch
- mingw-w64-gtk3/PKGBUILD
- mingw-w64-gtk3/gtk3-sassc-fix.patch
This release fixes DnD images being stuck in the top left screen corner:
https://bugzilla.gnome.org/show_bug.cgi?id=781737
Requires two patches:
A small build fix commited right after the release:
https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=1a489831b39d0c1583bd4d5e8583f65c1ba880e0
A revert of the following:
https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=7d9450fb60b03dcead85a462f30f24e60119c520
because it causes pasting to break, see https://bugzilla.gnome.org/show_bug.cgi?id=782453
> gtk3: Update to 3.22.13

- mingw-w64-git-lfs/0001-Translate-git-paths-from-msys-to-windows.patch
- mingw-w64-git-lfs/PKGBUILD
Some problems:
* ~~bsdtar chokes on the zip. Switching to the tar.gz release doesn't help. I can unzip it fine with the bsdtar on my Arch box, so it might be a problem with MSYS2 or a bug that was fixed in newer versions. As a workaround you can simply run makepkg-mingw twice, for some reason it only chokes on the zip when operating in a clean directory. I might try upgrading the libarchive PKGBUILD later to see if that helps.~~ (Resolved by Alexpux/MSYS2-packages#880)
* GOROOT is set via a /mingwXX/etc/profile.d script, but makepkg-mingw doesn't pull them in. To get that environment variable I have to manually source the script, but the right fix might be to modify either makepkg-mingw or change how GOROOT is set.
* We can now build man pages, I just had to install the ronn gem to the …
> Update git-lfs to v2.0.2

- mingw-w64-libsass/PKGBUILD
- mingw-w64-sassc/PKGBUILD
See http://sass-lang.com and http://libsass.org
sassc is needed for working on the Adwaita theme in GTK+ and also is
an optional build dependency there (upstream includes the generated css
in tree atm)
> Add libsass and sassc

- mingw-w64-gcc/0130-libstdc++-in-out.patch
- mingw-w64-gcc/PKGBUILD
In C/C++ code, the names `__in` and `__out` have a special meaning in Microsoft-style code, and a recent commit to mingw-w64 (b7f44b677f43c3bb5f771ff5a430206de040c48c) made those definitions be more visible, causing compilation errors in libstdc++ headers which try to use `__in` and `__out` as variable names.  For what it's worth, this pull request adds a patch to mingw-w64-gcc (but not mingw-w64-gcc-git) which should fix the issue, but the mingw-w64-gcc package is not currently compiling so I was unable to really test this pull request.  I usually don't make a pull request if I can't build the package in question, and I would personally prefer to use `sed` instead of a 3000-line patch, but Alexey asked for this.
> mingw-w64-gcc: Add a patch to fix the __in/__out name collision.

- mingw-w64-binutils-git/PKGBUILD
- mingw-w64-gcc-git/PKGBUILD
- mingw-w64-gdb-git/PKGBUILD
Cloning/updating repos through the HTTPS protocol results in Gigabytes of data transferred.
This reverts commit 113e9130aebbc000c6c840fdb41dcdd0e20fa188.
> Revert "improve vcs protocols (#2451)"

- mingw-w64-python-colorama/PKGBUILD
Also remove the check() target. colorama doesn't ship tests in the
tarball and the check() is broken anyway.
> python-colorama: Update to 0.3.9

- mingw-w64-cmake/PKGBUILD
- mingw-w64-cmake/cm_codecvt.patch
perform conversion for more than one character in cm_codecvt
codecvt::do_out returned std::codecvt::error when called for more than 1 char
the Ninja (and NMake) generator use this codecvt and therefore failed when writing files
since this works in the official CMake binary release
i’d infer that msvc calls this function ? one char at a time ?
i’m not sure this patch is correct, but it seems to work
upstream bugreport https://gitlab.kitware.com/cmake/cmake/issues/16893
> cmake: patch cm_codecvt (fix #2462)

- mingw-w64-nasm/PKGBUILD
Required for x264 git AVX-512 instructions support.
> nasm: update to 2.13.01

- mingw-w64-portaudio/PKGBUILD
- mingw-w64-portaudio/fix-build.patch
For some reason it either builds a static or a shared one.
Just build it twice and install both.
> portaudio: include static library. Fixes #2317

- mingw-w64-cmake/0004-Implement-Qt5-static-plugin-support.patch
- mingw-w64-cmake/PKGBUILD
hunk was incorrectly rebased
removed 1 working autogen if present
and crashed when no additional autogen was used
> cmake: fix regression

- mingw-w64-fmt/PKGBUILD
I'd like to add this recipe for fmt (formerly fmtlib).
Tests seem to pass locally.
The library ships with some `.cc` files in `include/fmt` (for header-only usage), I hope that's alright.
> Added new package: fmt

- mingw-w64-opencv/PKGBUILD
It currently links agains a missing libwebp-6.dll and needs a rebuild.
* libopencv_hdf320.dll depends on libhdf5
* libopencv_imgcodecs320.dll depends on libwebp
* libopencv_text320.dll depends on libtesseract
> opencv: Add some missing dependencies. Fixes #2420

- mingw-w64-libtiff/PKGBUILD
enable the tiff-cxx library in configure. This PR also adds a few minor improvements in quoting paths.
> mingw-w64-libtiff/PKGBUILD: enable the tiff-cxx library

- mingw-w64-cling-git/PKGBUILD
Fixes a basic build error with wrong paths relative to srcdir. After pulling the sources with git, most sources are in `$srcdir/../` and not `$srcdir/`. We make a copy into `$srcdir/` so the rest of the build can progress.
This PR does not make cling build successfully. But it removes a simple blocker problem very early on.
I also added better quoting in several places.
> mingw-w64-cling-git/PKGBUILD: several minor build improvements

- appveyor.yml
This saves 22 characters on absolute paths during building
I think this should help with GStreamer builds
> appveyor: Set shorter clone folder

- mingw-w64-gst-editing-services/PKGBUILD
- mingw-w64-gst-libav/PKGBUILD
- mingw-w64-gst-plugins-bad/0002-fix-link-order.patch
- mingw-w64-gst-plugins-bad/PKGBUILD
- mingw-w64-gst-plugins-base/PKGBUILD
- mingw-w64-gst-plugins-good/PKGBUILD
- mingw-w64-gst-plugins-ugly/PKGBUILD
- mingw-w64-gst-python/PKGBUILD
- mingw-w64-gst-rtsp-server/PKGBUILD
- mingw-w64-gstreamer/PKGBUILD
I've added some conflicts to prevent upgrade errors for plugins moving between packages. I'm not sure if that's desirable.
Release notes: https://gstreamer.freedesktop.org/releases/1.12/
All in all GStreamer no longer depends on libmimic and libmad.
> gstreamer: Update to 1.12.0

- mingw-w64-libzip/PKGBUILD
Copy zipconf.h to where it can be found by the main header.
Remove redundant slashes after `${pkgdir}`.
> Fix #2254: libzip is missing zipconf.h header

- mingw-w64-fontconfig/PKGBUILD
- mingw-w64-fontconfig/fix-cache-update.patch
See https://cgit.freedesktop.org/fontconfig/commit/?id=79058f4e911487275323e9314
> fontconfig: add an upstream patch to fix the cache update. Fixes #2550

- mingw-w64-ag/0001-lang-Allow-both-extensions-and-full-filenames.patch
- mingw-w64-ag/0002-win32-Detect-Cygwin-MSYS-PTY.patch
- mingw-w64-ag/0003-options-Fix-ordering-problems-with-color.patch
- mingw-w64-ag/0004-lang-Add-autotools-ac-am-in-m4-pc.patch
- mingw-w64-ag/0005-lang-Add-to-make-Makefile-Makefile.Debug-Makefile.Re.patch
- mingw-w64-ag/0006-lang-Add-makepkg-PKGBUILD-diff-patch-in-install.patch
- mingw-w64-ag/0007-lang-Add-cmake-CMakeLists.txt-CMakeCache.txt.patch
- mingw-w64-ag/PKGBUILD
* Update to 2.0.0.
* Import a patch to detect mintty from ggreer/the_silver_searcher#1099.
This fixes a well known problem which has been reported many times:
#431, Alexpux/MSYS2-packages#491, Alexpux/MSYS2-packages#730, etc.
A few days ago, I created a PR on the ag repository: ggreer/the_silver_searcher#1099.
I believe this is very useful for MSYS2 users, but I'm not sure it will be merged soon.
So I create this PR.
> ag: Update to 2.0.0 and support detecting mintty

- mingw-w64-gtest/0000-Fix-compilation-of-googletest-with-MinGW-using-Win32-threads.patch
- mingw-w64-gtest/0001-Fix-Mingw-w64-build.patch
- mingw-w64-gtest/PKGBUILD
Googletest merged with Googlemock after 1.7.0, so add gmock too.
Backport two commits fixing compilation on MinGW made after 1.8.0 release.
> Update gtest to 1.8.0

- mingw-w64-fontconfig/PKGBUILD
This changes the build to a srcdir=builddir build.
srcdir!=builddir was broken upstream and I reported it at
https://bugs.freedesktop.org/show_bug.cgi?id=101280 but the provided patches didn't help.
> fontconfig: Update to 2.12.3

- mingw-w64-ffmpeg/PKGBUILD
Remove workaround for --enable-libopenjpeg and parallel make.
It seems to build fine here without those changes.
> ffmpeg: Update to 3.3.2

- mingw-w64-python3/0540-mingw-semicolon-DELIM.patch
- mingw-w64-python3/0750-builddir-fixes.patch
- mingw-w64-python3/1600-fix-disable-blake2-sse.patch
- mingw-w64-python3/PKGBUILD
This fixes the remaining problems I had with Python 3.6.1 and the faulthandler module.
3.6.2 will be released in two weeks, so if there are no plans to update the repo in the mean time feel free to ignore/close this PR and I will create a new one once the final 3.6.2 is out.
> python3: Update to 3.6.2rc1

- mingw-w64-python-pluggy/PKGBUILD
- mingw-w64-python-pytest/PKGBUILD
In the last update the vendored pluggy was patched out, this
adds it pack as a new package.
> python-pytest: Add missing pluggy dependency

- mingw-w64-mbedtls/PKGBUILD
https://tls.mbed.org/tech-updates/releases/mbedtls-2.5.1-2.1.8-and-1.3.20-released
> mbedtls: Updated to 2.5.1

- mingw-w64-jasper/PKGBUILD
- mingw-w64-jasper/jasper-static-fix.patch
To use the static library you need to define JAS_DLL to zero.
-D JAS_DLL=0
I am trying to update qt5-git and I need this or another fix to enable linking to an static jasper library.
Tim S.
> jasper: Added patch file to fix static library link error.

- mingw-w64-python3/1650-expose-sem_unlink.patch
- mingw-w64-python3/PKGBUILD
- mingw-w64-python3/smoketests.py
With non-mingw builds POSIX_SEMAPHORES_NOT_ENABLED is not defined and
sem_unlink is a no-op. Change it so that the no-op sem_unlink is also exposed under mingw.
This adds a minimal test suite which makes it easier to catch regressions
in the future for common MSYS2 related bugs.
> python3: Make multiprocessing.Queue work; Add some tests. Fixes #837

- mingw-w64-crypto++-git/PKGBUILD
- mingw-w64-gst-rtsp-server-git/PKGBUILD
- mingw-w64-rust-git/PKGBUILD
Instead of building the same name as as the non-git variant
build a -git variant and provide/conflict the normal one.
As is the case with other git packages.
> Fix some missing -git suffixes in some git PKGBUILDS

- mingw-w64-qt5/PKGBUILD
By adding configure_opts for static build.
Static build uses "-no-icu", "-dbus-linked", and "-qt-freetype".
Added defines for static build of:
JAS_DLL=0
DBUS_STATIC_BUILD
Added library configuration info of:
DBUS_LIBS=-ldbus-1 -lws2_32 -liphlpapi
And, added shared guard around export of "PKG_CONFIG".
Only had enough hard disk space to test building the 64 bit static release without docs or examples.
But, it built and installed without issues.
It took me many hours to figure out the export "PKG_CONFIG" was causing the static build issue.
Tim S.
> qt5: Fixed static library build issues.

- mingw-w64-gdb-git/0001-MinGW-w64-Two-fixes-for-unusual-files.patch
- mingw-w64-gdb-git/0005-Mitigate-gdb-bug-21057.patch
- mingw-w64-gdb-git/0006-Disable-checks-using-setenv-or-unsetenv-as-they-do-n.patch
- mingw-w64-gdb-git/PKGBUILD
The `_base_ver` variable in `PKGBUILD` seems unused. Why was it there after all? `gdb --version` says `8.0` despite that value.
> mingw-w64-gdb-git: Update patches for the master branch.

- mingw-w64-gcc/PKGBUILD
I'm getting the _ITM_RU1 relocation errors again from https://github.com/Alexpux/MINGW-packages/issues/1580
Wasn't the weak references in 64-bit patch merged upstream already?
Edit: (^ It was added to master the same day of the 7.1 release, so no.)
> gcc: actually apply the patches

- mingw-w64-fontconfig/PKGBUILD
Added `mingw-w64-python3-lxml` to makedepends to fix https://github.com/Alexpux/MINGW-packages/issues/2602
> mingw-w64-fontconfig: added python3-lxml to makedepends

- mingw-w64-libcaca/PKGBUILD
Also use --disable-doc to make the build work without doxygen.
> libcaca: Move cppunit to makedepends/checkdepends

- mingw-w64-freetds/0001-Don-t-use-MSYS2-file-libws2_32.patch
- mingw-w64-freetds/0002-Enable-inet_pton-definition-in-MINGW-i686-build.patch
- mingw-w64-freetds/PKGBUILD
This adds a build script for [FreeTDS](http://www.freetds.org/). I'll open a pull request for the required patch.
I tested the package by using `tsql.exe` (which is part of the resulting package) and by building and running [tiny_tds](https://github.com/rails-sqlserver/tiny_tds) against the installed libraries.
> Add freetds build script

- mingw-w64-intel-tbb/PKGBUILD
Change cpp0x=1 to stdver=c++11 as suggested by the deprecation warning
printed by the build script.
Change license to Apache:
"TBB Version 4.4 and any older version will be under GPL license TBB
Version 2017 and all future versions will be under Apache v2.0
license."
> intel-tbb: Update to 2017_20170604

- mingw-w64-python-certifi/PKGBUILD
Remove mercurial makedep, not needed afaics
> python-certifi: Update to 2017.7.27.1

- mingw-w64-librsvg/PKGBUILD
Also fixes a bug uncovered by running glib master. One of
the arguments passed to glib-mkenums was converted to a path
and ended up in the generated C source.
> librsvg: Update to 2.40.18

- mingw-w64-jsonrpc-glib/PKGBUILD
- mingw-w64-meson/PKGBUILD
- mingw-w64-meson/color-term.patch
- mingw-w64-meson/force-func-detect.patch
- mingw-w64-meson/gtkdoc-exec-perl.patch
- mingw-w64-meson/no-script-suffix.patch
- mingw-w64-template-glib/PKGBUILD
* meson detects posix_memalign and stpcpy but both fails to link in
the end, so force disable them for now. This makes glib2 master build
using the new meson build system.
* remove the script suffixes so the naming is more in line with the
documentation and other tools.
* fix gtkdoc invocation by using msys2 perl
* enable colored output with mintty
* Update to 0.41.2
> meson: Various improvements

- mingw-w64-lua-mpack/PKGBUILD
Adds lua-mpack 1.0.4
There are more recent releases 1.0.5/1.0.6. But I cant build those in mingw (this should be fixed in the next release https://github.com/libmpack/libmpack-lua/pull/5)
> Add lua-mpack

- mingw-w64-icu/PKGBUILD
The recent icu update #2424 breaks XP support, see #2708.
With this patch we can support XP a little longer (before we probably have to drop it completely in icu 59)
> icu: disable use of _strtod_l

- mingw-w64-openjpeg2/0007-fix-build-2.2.0.patch
- mingw-w64-openjpeg2/PKGBUILD
Include a build fix from upstream master. See https://github.com/uclouvain/openjpeg/issues/994
> openjpeg2: Update to 2.2.0

- mingw-w64-pango/PKGBUILD
The new tarballs are created with meson so we have to run autogen.sh
and the tarballs no longer contain the built documentation.
> pango: Update to 1.40.10

- mingw-w64-firebird2-git/0030-Use-nullptr.patch
- mingw-w64-firebird2-git/0031-Fix-compiler-flags.patch
- mingw-w64-firebird2-git/PKGBUILD
I am mainly an C Programmer working to better my C++ knowledge.
I have not tested the package; because I have no idea how to test it.
Used compiler option "-std=gnu++11" because I could not figure out how to fix the build error below.
Changed package to options=('debug' 'strip') because '!debug' is causing error in running create_db.exe empty.fdb during build.
See also #2747 and #2536
Error # 1 fixed by 0030-Use-nullptr.patch
../src/jrd/gds.cpp:278:7: error: conflicting declaration 'const UCHAR zero []'
zero[]  = { op_line, 0 },
^
In file included from ../src/jrd/../jrd/../jrd/val.h:32:0,
from ../src/jrd/../jrd/jrd.h:39,
from ../src/jrd/gds.cpp:151:
../src/jrd/../jrd/../jrd/../include/fb_blk.h:115:15: note: previous declaration as 'void* zero'
static void * zero = (void *) 0;
^~~~
Error # …
> Firebird2-git

- mingw-w64-mbedtls/PKGBUILD
https://tls.mbed.org/tech-updates/releases/mbedtls-2.6.0-2.1.9-and-1.3.21-released
> mbedtls: Updated to 2.6.0

- mingw-w64-exiv2/0001-fix-tests.patch
- mingw-w64-exiv2/PKGBUILD
That requires rebuild for programs which are using this library due to changing ABI. I'm aware of only on such package (gexiv2)
> exiv2: Turn on unicode paths.

- mingw-w64-cairo/0027-win32-print-fix-unbounded-surface-assertion.patch
- mingw-w64-cairo/PKGBUILD
This fixes crashes when using the cairo-win32 print backend.
Reported upstream (see https://bugs.freedesktop.org/show_bug.cgi?id=101833) but 
upstream seems to be working a bit slowly these days...
> cairo: add patch to fix unbounded surface assertion

- mingw-w64-python-pillow/PKGBUILD
Pillow can make use of libraqm since version 4.2.0 (i.e. links against it since f46e8b3fc1e729d4fb593bff924ab4f28a70c006) and therefore is now missing a dependency.
(alternative would be to use [`--disable-raqm` build flag](https://pillow.readthedocs.io/en/latest/installation.html#build-options))
> pillow: Add missing dependency (libraqm)

- mingw-w64-pyqt5/001-mingw-python.patch
- mingw-w64-pyqt5/PKGBUILD
- mingw-w64-sip/PKGBUILD
Had to update sip to 4.19.3 as required by pyqt5.
pyqt5 5.9 works with both Qt 5.9.0 and Qt 5.9.1.
Tested with a basic hello world application.
> pyqt5: Update to 5.9 and related changes

- mingw-w64-soundtouch/PKGBUILD
As far as I can see no API/ABI break:
https://www.surina.net/soundtouch/README.html
> soundtouch: Update to 2.0.0

- mingw-w64-gdb-git/0006-Disable-checks-using-setenv-or-unsetenv-as-they-do-n.patch
- mingw-w64-gdb-git/PKGBUILD
This makes `mingw-w64-gdb-git` build again.
> mingw-w64-gdb-git: Fix patch 0006 according to upstream changes.

- mingw-w64-gcc-git/0018-gcc-7-branch-Enable-a-native-GCC-to-color-diagnostic-messages-sen.patch
- mingw-w64-gcc-git/PKGBUILD
This fixes a few typos in comments in the original patch and adds a handler for the `ESC [ n J` (Erase Display, ED) sequence.
> gcc-git: Update diagnostic color patch.

- mingw-w64-aspell/0008-cache-Attempt-to-prevent-premature-destruction-of-gl.patch
- mingw-w64-aspell/PKGBUILD
This allows to build with gcc 7 and fixes a segmentation fault.
(see previous description and patch by @jtanx for details)
<s>Unfortunately Aspell is still incompatible with recent versions of winpthreads making it SEGFAULT frequently, see #904 (and links in that bug).
Downgrading winpthreads temporarily is a workaround in some cases but is not really possible in others (e.g. I just realized that Inkscape, which is linked against the shared Aspell library, crashes *every* time on exit due to this issue).
Any help with this would be highly appreciated!
(P.S. In principle this could be merged, but as long as no fix is found there's probably not much reason to package a release candidate at this point; just wanted to make it available in case somebody want to try to build it)</s>
> Aspell: update to 0.60.7-rc1 and fix segmentation fault

- mingw-w64-plplot/Include-wx-msw-wrapwin.h-instead-of-Windows.h.patch
- mingw-w64-plplot/PKGBUILD
I have only been testing the build under Windows 10 32 bit. I have not had the energy to get my Windows 7 64 bit laptop up and running; I have installed the 32 bit package; but, have no idea of how to test and see if it works. Tim S.
plplot: Updated to version 5.13.0 and fixed building of package.
Added >=3.6.2 to cmake depends.
Changed include of "Windows.h" to "wx/msw/wrapwin.h" via patch file.
Removed "Fix CMake FindSWIG" code from package.
And, Removed local folder names from package.
And, added defines:
DEFAULT_NO_BINDINGS=ON
ENABLE_ada=ON
ENABLE_cxx=ON
ENABLE_f95=ON
ENABLE_tcl=ON
ENABLE_tk=ON
ENABLE_wxwidgets=ON
ENABLE_itk=OFF
> plplot: Updated to version 5.13.0 and fixed building of package.

- mingw-w64-libcello-git/PKGBUILD
This fixes an unintended rename in 4d8828efed588cf6c8
I missed that pkgbase was included in pkgname when renaming it.
Thanks to @filnet for catching this.
> libcello-git: fix pkgname

- mingw-w64-PKGBUILD-common/kde-frameworks5
- mingw-w64-attica-qt5/PKGBUILD
- mingw-w64-extra-cmake-modules/PKGBUILD
- mingw-w64-karchive-qt5/PKGBUILD
- mingw-w64-kcodecs-qt5/PKGBUILD
- mingw-w64-kconfig-qt5/PKGBUILD
- mingw-w64-kcoreaddons-qt5/PKGBUILD
- mingw-w64-kcrash-qt5/PKGBUILD
- mingw-w64-kdbusaddons-qt5/PKGBUILD
- mingw-w64-kdoctools-qt5/PKGBUILD
- mingw-w64-kdoctools-qt5/catalog_path.patch
- mingw-w64-kglobalaccel-qt5/PKGBUILD
- mingw-w64-kguiaddons-qt5/PKGBUILD
- mingw-w64-ki18n-qt5/PKGBUILD
- mingw-w64-kidletime-qt5/PKGBUILD
- mingw-w64-kimageformats-qt5/PKGBUILD
- mingw-w64-kitemmodels-qt5/PKGBUILD
- mingw-w64-kitemviews-qt5/PKGBUILD
- mingw-w64-kjs-qt5/PKGBUILD
- mingw-w64-kplotting-qt5/PKGBUILD
- mingw-w64-kwidgetsaddons-qt5/PKGBUILD
- mingw-w64-kwindowsystem-qt5/PKGBUILD
- mingw-w64-solid-qt5/PKGBUILD
- mingw-w64-syntax-highlighting-qt5/PKGBUILD
- mingw-w64-threadweaver-qt5/PKGBUILD
Update existing kf5 framework libraries to 5.38.0, including extra-cmake-modules (ECM).
Also adds some additional kf5 libs:
* KDocTools (Needed for building KJS)
* KSyntaxHighlighting
* ThreadWeaver
I may add more in the future if these end up working.
> Update kf5 libs to 5.38.0

- mingw-w64-gdal/PKGBUILD
When testnig https://github.com/osmcode/libosmium with MSYS2, noticed that current gdal binaries were broken (asking missing dlls like libcryptopp.dll and libnetcdf.dll). Added the missing libraries to dependencies, but the package also needs rebuilding with new Poppler (currently it wants libpoppler-67 dll with libpoppler-70 present).
Postgresql client is also needed to run .exe-s , but currently postgres is a monolyt package (server+client) and I do not know if it should be a mandatory dependency.
> gdal: add crypto++ and netcdf dependencies

- mingw-w64-gdb-git/PKGBUILD
The bundled one since GDB 8.0 does not handle backspaces correctly in CMD, and it crashes x64 build recently.
> gdb-git: Use system readline instead of the bundled one.

- mingw-w64-clang/0101-Allow-build-static-clang-library-for-mingw.patch
- mingw-w64-clang/0102-fix-libclang-name-for-mingw.patch
- mingw-w64-clang/0103-Set-the-x86-arch-name-to-i686-for-mingw-w64.patch
- mingw-w64-clang/0104-link-pthread-with-mingw.patch
- mingw-w64-clang/0105-use-emulated-tls-with-mingw.patch
- mingw-w64-clang/0106-MinGW-use-flto-visibility-public-std-CC1-arg-to-get-.patch
- mingw-w64-clang/PKGBUILD
It fixes `undefined reference to _imp___cxa*` errors.
@martell Saleem told me to try with `-flto-visibility-public-std` and my very limited testing shows it resolves issue on both MSYS2 and Ubuntu (clang 5.0) when using static libstdc++ (MSVC use it in some cases already). Any thoughts?
Minimal testcase (example command `clang++ -std=gnu++14 -static test.cc`):
```
#include <string>
int main() { std::u16string b; }
```
@Alexpux sorry for another release in short time but you don't have to hurry. This fix alone isn't very important because of multiple definition errors that happen often when using static libstdc++ with clang (I can even revert `pkgrel` to 1).
> clang: add patch enabling -flto-visibility-public-std

- mingw-w64-plplot/PKGBUILD
Added "patch" and "bsdtar>=3.3" to make depends.
Added this define "ENABLE_qt=OFF" and
changed the "ENABLE_f95=ON" define to "ENABLE_fortran=ON".
Also, added paths and libname to help find the qhull lib.
In addition, added code to find the correct Python library.
The gdlib/libgd is still not being found. I hope this second try fixes the 64 bit build problem.
This time using python2 like the package did before I started editing it.
Tim S.
> plplot: Added to makedepends and changed defines passed to cmake.

- mingw-w64-glib2/PKGBUILD
Before build you must update the gtk-doc package
> glib2: updated to 2.54.0.

- mingw-w64-protobuf/PKGBUILD
add missing dep
disable tests as building does not work
> protobuf: update to 3.4.1

- mingw-w64-libgd/PKGBUILD
- mingw-w64-libgd/libgd-export-pkg-config-build-in-subdirs.patch
Also fixing the pkg-config and gdlib-config, after the lib and headers were moved back from their subfolder to the /lib and /include folder, the .PC and the gdlib-config scripts were still pointing to the subfolders - this is now also fixed.
> libgd: Update to 2.2.5

- mingw-w64-docbook-xsl/PKGBUILD
Upstream has moved to github: https://github.com/docbook/xslt10-stylesheets
> docbook-xsl: Update to 1.79.2

- mingw-w64-libevent/PKGBUILD
- mingw-w64-libevent/event2-02-win32.patch
- mingw-w64-transmission/PKGBUILD
- mingw-w64-transmission/skip-broken-cmake-rc.patch
* Adds transmission bittorrent client using gtk3
* Updates libevent (dll version bump, but nothing depends on it)
and add patch from upstream transmission. Otherwise tracker
connections fail.
* More of the included libraries could be packaged separately,
but this is a start..
> Add transmission package

- mingw-w64-docbook-xsl/0001-add-back-old-uri-rewrite.patch
- mingw-w64-docbook-xsl/PKGBUILD
The last release changed the URI rewrites from sourceforge to
docbook.org. Things like gtk-doc docs reference the sourceforge ones,
so add them back.
> docbook-xsl: fix uri rewrites

- mingw-w64-atk/PKGBUILD
no longer needed, upstream uses autoconf-archive now
> atk: Drop gnome-common dependency

- mingw-w64-harfbuzz/PKGBUILD
While trying to fix fontconfig; I was getting these messages that I thought was wrong.
Tim S.
updating font cache... C:/Apps64/MSys2/mingw64/bin/fc-cache.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
done.
warning: dependency cycle detected:
warning: mingw-w64-i686-harfbuzz will be installed before its mingw-w64-i686-freetype dependency
warning: dependency cycle detected:
warning: mingw-w64-i686-cairo will be installed before its mingw-w64-i686-freetype dependency
warning: dependency cycle detected:
warning: mingw-w64-i686-fontconfig will be installed before its mingw-w64-i686-freetype dependency
> harfbuzz: Make cairo an optional depends.

- mingw-w64-glib2/PKGBUILD
- mingw-w64-gtk-doc/0002-fixxref-rebase-Don-t-depend-on-glib-being-installed.patch
- mingw-w64-gtk-doc/PKGBUILD
* Fix wrong python exe wrapper for glib-gettextize
* Move to mingw gtk-doc
* Add gtk-doc patch for https://bugzilla.gnome.org/show_bug.cgi?id=787768
> glib: Update to 2.54.1 v2

- mingw-w64-opencv/0013-dnn_modern-NO_STRICT-fix.patch
- mingw-w64-opencv/PKGBUILD
- mingw-w64-suitesparse/0003-mingw-w64-no-CUDA.patch
- mingw-w64-suitesparse/PKGBUILD
opencv 3.3.0 and suitesparse 4.5.5 compiling error fixed.
> opencv and suitesparse compile error fix.

- mingw-w64-curl/PKGBUILD
`curl` will have `rtmp` support if it's built against GnuTLS, a
non-default variant currently. `librtmp` is built against GnuTLS,
so at the moment the curl executable and `libcurl.dll` will link
against both OpenSSL and GnuTLS, with the latter pulling in
a long list of additional library dependencies (gmp nettle hogweed
tasn1 p11-kit). After this change curl would only depend on OpenSSL
by default. `rtmp` is a rarely used protocol with `curl` and there
are alternative tools to achieve the same functionality, e.g.
`rtmpdump` and `ffmpeg`. For these reasons, I believe it'd
be more optimal not to include its functionality in curl by default,
allowing to use the libcurl library with less overhead for most
use-cases.
If `rtmp` support in `curl` is deemed critical in MSYS2, another
approach is …
> Limit curl rtmp support to the GnuTLS variant

- mingw-w64-gtk3/0001-gtkwindow-Don-t-force-enable-CSD-under-Windows.patch
- mingw-w64-gtk3/PKGBUILD
So that for example gtk3-demo-application.exe uses the default
Windows window decorations.
> gtk3: Don't force enable client side decoration

- mingw-w64-curl/PKGBUILD
In both the openssl and gnutls variants. MultiSSL has
been introduced in curl 7.56.0 and allows multiple
SSL backends to be linked at the same time. It's then
possible to select between them at runtime.
Ref: https://curl.haxx.se/libcurl/c/curl_global_sslset.html
Ref: https://github.com/curl/curl/commit/1328f69d53f2f2e937696ea954c480412b018451
Also fix quote in `--with-nghttp2=` option.
> curl: enable MultiSSL mode by enabling WinSSL

- mingw-w64-python3/1701-disable-broken-gdbm-module.patch
- mingw-w64-python3/PKGBUILD
gdbm is broken and as a result breaks dbm/shelve (dbm.open fails)
Don't include it so the dbm.dumb backend is used instead,
like with the official CPython build.
> python3: Disable broken gdbm module

- mingw-w64-python2/2701-disable-broken-gdbm-module.patch
- mingw-w64-python2/PKGBUILD
gdbm is broken and as a result breaks anydbm/shelve (anydbm.open fails).
Don't include it so the dumbdbm backend is used instead,
like with the official CPython build.
> python2: Disable broken gdbm module

- mingw-w64-gst-libav/PKGBUILD
No need to include ffmpeg since it's likely getting pulled in by something
else anyway. This is also what Arch Linux does.
> gst-libav: Build with system ffmpeg instead of internal one

- mingw-w64-gtk2/0017-fix-dead-keys-part-4.patch
- mingw-w64-gtk2/PKGBUILD
It was accidentally removed in e652682263f0ed6df32d5cb49d0b5882dcb9e4b1.
While it is true it landed upstream it is not yet available in a packaged release, see upstream commit https://github.com/GNOME/gtk/commit/79b2a92fe59e03cdd12cb8108a1e7b117c94f4c3
> gtk2: restore patch

- mingw-w64-SDL2/PKGBUILD
TODO: find out why this doesn't build with libsamplerate support
> SDL2: update to 2.0.7

- mingw-w64-clang/PKGBUILD
This simply adds NVPTX support to the LLVM built by the `mingw-w64-*-clang` package. It's very handy to have this in the MinGW-w64 package, since it's quite a hassle to build a usable LLVM from source on Windows (principally due to `llvm-config.exe` bugs, which I'd like to send PR's for upstream once I have the time). This will marginally increase the package build time and the size of `LLVM.dll`.
This is especially handy for [accelerate-llvm-ptx](https://hackage.haskell.org/package/accelerate-llvm-ptx) users on Windows, since the Stack Haskell build tool provides a sandboxed MinGW anyway.
I managed to build this on my machine without issue and the resulting package seems to work. Apologies if I've forgotten something or I'm doing something wrong; this is the first MinGW development I've …
> Add NVPTX target to LLVM.

- mingw-w64-libmfx/PKGBUILD
This adds the libmfx package, the Intel Media Dispatcher toolkit.
> Add libmfx package (version 1.23)

- mingw-w64-SDL2_mixer/PKGBUILD
- mingw-w64-SDL2_mixer/SDL2_mixer-2.0.1-find_lib.mingw.patch
Link in the libraries instead of relying on dlopen().
Support for these formats is pretty much expected nowadays and we
depend on the corresponding packages anyway. I am not applying this
to modplug and fluidsynth as well, because they support more exotic
formats and pull in some rather heavy-weight dependencies
(e.g. libglib in the case of fluidsynth).
> SDL2_Mixer: link in MP3, Ogg Vorbis and FLAC support libraries

- mingw-w64-hdf5/PKGBUILD
- mingw-w64-hdf5/hdf5-cmake-size-type-checks.patch
This patch is not extensively tested. I found in hdf5 build log many warnings that `H5_SIZEOF_PTRDIFF_T` is not defined, so I added this fix for cmake to define `H5_SIZEOF_PTRDIFF_T` on MinGW/MSYS2. The build and library works for me, but I did not perform heavy testing.
> mingw-w64-hdf5: enable ptrdiff_t in cmake on MinGW/MSYS2

- mingw-w64-qhttpengine/PKGBUILD
This pull request adds a `PKGBUILD` for [QHttpEngine](https://github.com/nitroshare/qhttpengine), a library that provides a simple HTTP server for Qt applications. It requires CMake to build and its only runtime dependencies are the base Qt5 libraries.
> Add QHttpEngine.

- mingw-w64-libblocksruntime/0001-libblocksruntime-0.4.1-fix-shared-installation.patch
- mingw-w64-libblocksruntime/PKGBUILD
This adds libblocksruntime, needed by some packages on Unix platforms, such as the Swift programming language.
> Add libblocksruntime (version 0.4.1)

- mingw-w64-qmdnsengine/PKGBUILD
This pull request adds a PKGBUILD for [QMdnsEngine](https://github.com/nitroshare/qmdnsengine), a library that provides support both for discovering and providing services using mDNS (multicast DNS). It requires CMake to build and its only runtime dependencies are the base Qt5 libraries.
> Add QMdnsEngine.

- mingw-w64-SDL2_image/PKGBUILD
Link in the PNG library instead of relying on dlopen().
For proper read/write support for the most popular image format
the library should be linked in, we depend on the corresponding
package anyway.
> SDL2_image: link in PNG support library

- mingw-w64-goocanvas/001-convert-python-path-to-unix.patch
- mingw-w64-goocanvas/PKGBUILD
And while at it move to mingw gtk-doc and fix some
path conversation problems with newer glib-mkenums.
> goocanvas: Update to 2.0.4. Fixes #3131

- mingw-w64-libvisio/0001-libvisio-compare_dates_in_utc.patch
- mingw-w64-libvisio/PKGBUILD
The solution to fix the test (see second commit) is not overly beautiful but it was the best I could come up with short of disabling the test or actually changing the OSs timezone.
If anybody knows a better solution I'm open for feedback.
> libvisio: update to version 0.1.6

- mingw-w64-gnucobol/001-mingw-gnucobol-2.2-fixformatwarnings.patch
- mingw-w64-gnucobol/002-mingw-gnucobol-2.2-skipcursestests.patch
- mingw-w64-gnucobol/PKGBUILD
- mingw-w64-gnucobol/cobenv.cmd
- mingw-w64-gnucobol/cobenv.sh
Instead of the svn one (which I still would like to update to allow people to use "latest") this is the package for the most current release version.
A note concerning the patches:
* 001 will *only* work with MSYS2 (building), not with old mingw and not with any other environment - if I remember correctly this will just remove the format warnings during compilation (with the additional `-D__USE_MINGW_ANSI_STDIO=1`
* 002 is (slightly changed) in svn version already and will therefore be removed with the next release and not integrated in the svn package
A question: Is it possible to install the package with adjusting the user's environment? The generated binaries get the install-prefix' path hard-wired into them (always did) and won't work anywhere as the binaries need to use Windows paths …
> release package for GnuCOBOL (currently at version 2.2)

- mingw-w64-tcl/001-fix-relocation.patch
- mingw-w64-tcl/PKGBUILD
Fixes an issues with tcl not finding the '/lib' folder if the library is not it a `/bin` subfolder
> tcl: minor relocation fix

- mingw-w64-libmicrohttpd/PKGBUILD
* updated to version 0.9.57
* removed dependency on libgcrypt,
* enforced configure https flag to ensure that HTTPS support will be built.
> libmicrohttpd: updated to version 0.9.57, improved

- mingw-w64-potrace/PKGBUILD
This pull request changes the potrace package from version 1.13 to 1.15 which contains important bug and security fixes.  Both i686 and x86_64 packages build and I could not find any issues with inkscape which is the only package dependent upon potrace.
> Upgrade potrace from 1.13 to 1.15.

- mingw-w64-python2-enum/PKGBUILD
This adds the python2-enum package (version 0.4.6).
Good thing this does not conflict with python2-enum34.
> add python2-enum (version 0.4.6)

- mingw-w64-python2/2700-cygpty-isatty-disable-readline.patch
- mingw-w64-python2/PKGBUILD
Set USE_DYNFILEID for ptycheck so it dynamically enables pty checking only if the API is available.
Building still requires Vista+
Context: https://github.com/Alexpux/MINGW-packages/pull/2806#issuecomment-348658740
> python2: Restore WinXP support

- mingw-w64-python-pyamg/PKGBUILD
This adds python-pyamg, Algebraic Multigrid Solvers in Python (version 3.3.2).
> add python-pyamg (version 3.3.2)

- mingw-w64-libmicrohttpd/PKGBUILD
GNU libmicrohttpd updated to latest upstream version 0.9.58
Like in Arch repo, curl was moved to checkdepends, because it is required only for tests.
> libmicrohttpd: updated to v0.9.58

- mingw-w64-mono/0001-mono-5.4.1.7-fix-build.patch
- mingw-w64-mono/0002-mono-5.4.1.7-avoid-appending-prefix.patch
- mingw-w64-mono/0003-mono-5.4.1.7-fix-runtime.patch
- mingw-w64-mono/PKGBUILD
- mingw-w64-mono/bootstrap/0001-mono-5.4.1.7-fix-build.patch
- mingw-w64-mono/bootstrap/0002-mono-5.4.1.7-avoid-appending-prefix.patch
- mingw-w64-mono/bootstrap/0003-mono-5.4.1.7-fix-runtime.patch
- mingw-w64-mono/bootstrap/PKGBUILD
This adds the mono package (version 5.4.1.7), a C# and .NET Framework implementation.
Unfortunately it requires an already existing installation of mingw-w64-mono for bootstrapping; however, I've uploaded existing mingw-w64-mono packages here for installation and bootstrapping:
https://github.com/Adsun701/msys2-mingw-binary-packages
Thanks.
> add mono package (version 5.4.1.7)

- mingw-w64-zimg/PKGBUILD
This updates zimg to 2.6.3 and removes the git specificity from winpthreads dependency.
> zimg: update to 2.6.3 and remove git prefix from winpthreads dependency

- mingw-w64-geoip/PKGBUILD
This updates geoip to 1.6.11. Previously the version of geoip was 1.6.9.
> geoip: update to 1.6.11

- mingw-w64-make/PKGBUILD
Closes Alexpux/MINGW-packages#2233, Alexpux/MSYS2-packages#828,
Alexpux/MSYS2-packages#842.
> make: gettext is a runtime dependency

- mingw-w64-gegl/PKGBUILD
$ pacman -S mingw-w64-i686-gimp
...
$ gimp-2.9.exe
GEGL-Message: Module 'M:\mingw32\lib\gegl-0.3\matting-levin.dll' load error: 'M:\mingw32\lib\gegl-0.3\matting-levin.dll': The specified module could not be found.
...
Suitesparse is present on the main build system, so GEGL gets built with --with-umfpack. Thus if suitesparse is not manually installed by the user, matting-levin.dll has missing imports from libumfpack.dll, rendering the 'gegl:matting-levin' operation present but unusable.
> Add suitesparse dependency to gegl

- mingw-w64-gtkglext/PKGBUILD
Someone on IRC ran into this one while building packages on msys2 in Windows.
Basically `glib-mkenums --fprod "/* foo */"` was emitting `C:/mingw64/* foo */`, which of course confused the compiler. A newline before the comment, borrowed from the next Makefile rule, gets makepkg-mingw to pass for me.
This problem already has a fix in gtkglext git master, see [GNOME bug 608034](https://bugzilla.gnome.org/show_bug.cgi?id=608034), but this particular package looks unmaintained for a while.
I leave it to the maintainers to decide if this stop-gap solution is the right thing.
> add a minor patch to gtkglext to fix building natively with makepkg-mingw

- mingw-w64-yaml-cpp/PKGBUILD
Not rebuilding yaml-cpp since the latest boost update caused warnings during linking in an application of mine: https://github.com/carrotIndustries/horizon/issues/46
We also need to update the checksum, since it github recompressed the tarball. A tarball with the original checksum is available at http://pkgs.fedoraproject.org/repo/pkgs/yaml-cpp/yaml-cpp-0.5.3.tar.gz/64200ca0bf5e0af065804d8d3e8f6d42/yaml-cpp-0.5.3.tar.gz  The contents haven't changed.
> rebuild yaml-cpp due to boost update

- mingw-w64-libgdiplus/PKGBUILD
This updates libgdiplus to latest version 5.6.
> libgdiplus: update to 5.6

- mingw-w64-mono-basic/0001-mono-basic-4.6-fix-slash-vs-hyphen.patch
- mingw-w64-mono-basic/PKGBUILD
This adds mono-basic (version 4.6), mono's implementation of the VB.NET compiler.
This currently will fail the tests because my updated version of mono (which fixes the bin scripts) has not been uploaded to the repository yet.
> add mono-basic package (version 4.6)

- mingw-w64-fmt/0001-fmt-4.1.0-fix-runtime-installation.patch
- mingw-w64-fmt/PKGBUILD
This updates fmt to 4.1.0 and removes failing tests.
> fmt: update to 4.1.0 and remove failing tests

- mingw-w64-argon2/PKGBUILD
Requesting to add the Argon2 library/binary to msys2 repository. This is being used in the [KeePassXC](https://github.com/keepassxreboot/keepassxc) project to provide a modern key derivation function. I tested this on a fresh MSYS2 install using the wiki instructions.
> Add Argon2 package from P-H-C/phc-winner-argon2

- mingw-w64-exiv2/0002-memoryallocation.patch
- mingw-w64-exiv2/PKGBUILD
We have discovered a serious [performance problem](https://github.com/Exiv2/exiv2/issues/200), this simple patch is addressing the current release until the new release will fix this on a permanent basis.
> Exiv2: backport a memory allocation patch

- mingw-w64-snappy/PKGBUILD
This fixes snappy's build via checkdepends, and also removes typo in url.
Sorry for not responding very quickly.
> snappy: fix build's checkdepends and url

- mingw-w64-glib2/PKGBUILD
Python 3 is the default on Linux for most distros now, so it's a good idea
to use the same tools as everyone else.
I've built a few packages depending on glib and everything seems to work with py3.
> glib2: Update to 2.54.3; Switch to Python 3 for the build tools

- mingw-w64-libtasn1/PKGBUILD
This updates libtasn1 to the latest version, 4.13.
> libtasn1: update to 4.13

- mingw-w64-python3/1800-link-win-resource-files-and-build-pythonw.patch
- mingw-w64-python3/PKGBUILD
Use windres to build the resource files and include them in the
dll and executables. Since we need a different resource for the
console/gui version move the creation of the python3w.exe file from
the PKGBUILD into the Makefile.
With a bit of luck this should allow one to opt into the new long paths
feature on Windows 10, like with the official builds.
(no Windows 10 here, can't test)
> python3: include official .rc files for the dlls/execs. See #3139

- mingw-w64-gobject-introspection/PKGBUILD
When you pass --pkg to g-ir-scanner it uses pkg-config.
And without mingw pkg-config it might use msys pkg-config which
leads to weird errors, see https://github.com/Alexpux/MINGW-packages/issues/2198
Better depend on it.
> gobject-introspection: depend on pkg-config

- mingw-w64-gtk3/PKGBUILD
gdbus-codegen uses Python 3 now, and it is part of glib2 which depends
on python3 anyway.
> gtk3: Remove python2 makedep

- appveyor.yml
With a mingw gdb build the auto test discovery takes 1.5 minutes, since
we don't have any tests disable them.
> appveyor: disable test discovery

- mingw-w64-gdb/PKGBUILD
- mingw-w64-gdb/python-configure-path-fixes.patch
Previously python-config-u, a python-configure which returns unix paths,
was passed to configure. Passing a python executable of python-config
which returns Windows paths breaks the relocatable support somehow.
This patch converts the exec-prefix result of the python-config script
to a unix path so that things work as before.
> gdb: fix python relocatable support. See #3329

- mingw-w64-mbedtls/PKGBUILD
[mbed TLS Security Advisory 2018-01](https://tls.mbed.org/tech-updates/security-advisories/mbedtls-security-advisory-2018-01)
> mbedtls: Updated to 2.7.0

- mingw-w64-hdf4/PKGBUILD
The hdf4 library has been superseded by hdf5, but many scientists need both hdf4 as well as hdf5 to do their job (i.e. work with legacy systems in gdal).
This is mostly to enable the gdal driver, i.e. we could build gdal with `--enable-hdf4 --enable-hdf5`. The build script is a bit of a hack because the upstream authors only test with MSVC, so we need to disable some `_WIN32` macros. The resulting libs has been tested to support `--enable-hdf4` in `mingw-w64-gdal`.
> add hdf4 package (for use in gdal)

- mingw-w64-rocksdb/0001-fix-get-version-on-windows.patch
- mingw-w64-rocksdb/0002-suppress-unused-warnings.patch
- mingw-w64-rocksdb/0003-add-with-gflags-option.patch
- mingw-w64-rocksdb/PKGBUILD
WIP as there are some issues:
1/ when packaging there is this warning:
`WARNING: Package contains reference to $(cygpath -m /)`
2/ when compiling rocksdb with more libraries (lz4, bz2, snappy) then osgearth fails to link.
osgearth does not pick up the additional "external" libraries needed by rocksdb.
> rocksdb: new package

- mingw-w64-gst-python/PKGBUILD
Adds a Python 2 variant of the package called gst-python2 like in Arch.
Drops the gstreamer plugin (libgstpythonplugin) because it creates problems
with Python applications loading the plugins. The plugin links against py3
and when loaded from a Python 2 procedss or vice versa it loads pygobject
+ gst overrides again which leads to gtype conflicts. See #2034
> gst-python: Add Python 2 variant; Drop libgstpythonplugin. Fixes #2034

- mingw-w64-soil/PKGBUILD
Tested using
```
MINGW_INSTALLS=mingw64 makepkg-mingw -sLf
pacman -U mingw-w64-x86_64-soil-1.16.0-1-any.pkg.tar.xz
```
as well as
```
MINGW_INSTALLS=mingw32 makepkg-mingw -sLf
pacman -U mingw-w64-i686-soil-1.16.0-1-any.pkg.tar.xz
```
Both worked just fine when building a project with a SOIL dependency.
Related to issue #3369
> Add SOIL package

- mingw-w64-gnupg/PKGBUILD
- mingw-w64-pinentry/PKGBUILD
Removed make parallel opts because makepkg setted MAKEOPTS and added pinentry dependency to gnupg
> Remove make parallel opts and add pinentry dep to gnupg

- mingw-w64-argon2/PKGBUILD
From https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/argon2&id=fdf4c3b0da6a02d52ce845b511edadbf66b4711a
It's causing illegal instructions when run in Ivy Bridge CPUs without AVX2.
> argon2: build without optimizations

- mingw-w64-djview/PKGBUILD
- mingw-w64-djvulibre/PKGBUILD
- mingw-w64-graphicsmagick/PKGBUILD
- mingw-w64-pdf2djvu/PKGBUILD
graphicsmagic - 2.3.28 - add gcc-libs, libwinpthreads, and txt2html as dependencies.  Rebuilding using txt2html to generate HTML documentation.
pdf2djvu - 0.9.8 - add exiv2, gettext, libiconv, poppler to dependendencies.  Add nose2 to checkdepends for future-proofing
djview - 4.10.6 - New package.  Portable DjVu viewer using the QT5 library.
> djvulibre - 3.5.27 add libtiff and libiconv as dependencies

- mingw-w64-gst-plugins-ugly/0001-x264enc-fix-build-with-newer-x264-with-support-for-m.patch
- mingw-w64-gst-plugins-ugly/PKGBUILD
Adds the patch from https://bugzilla.gnome.org/show_bug.cgi?id=792111
> gst-plugins-ugly: include upstream patch for x264 API changes. Fixes #3379

- mingw-w64-python-packaging/PKGBUILD
- mingw-w64-python-sphinx/PKGBUILD
- mingw-w64-python-urllib3/PKGBUILD
Some dependencies are not correct.
Sphinx now requires 'packaging', and 'packaging' requires 'pyparsing'.
Also sort the lists in the alphabetical order.
Remove chardet, idna and urllib3 from the dependencies of sphinx, because they are
not directly required by it. They are required by 'requests'
and it already has them as the dependencies.
Move certifi from sphinx to urllib3.
> python-{sphinx,packaging,urllib3}: Fix dependencies

- mingw-w64-mpv/PKGBUILD
Fixes #3450. The lua51 package has a dll that's required to execute mpv.exe.
> mpv: add missing lua51 dependency

- mingw-w64-SDL2/PKGBUILD
- mingw-w64-SDL2_image/PKGBUILD
This PR updates the SDL2 libs to SDL 2.0.8 and SDL2_image to 2.0.3.
> SDL: Updates to SDL 2.0.8 and SDL2_image 2.0.3

- mingw-w64-fontconfig/0003-fix-link-libintl.patch
- mingw-w64-fontconfig/PKGBUILD
This release brings greatly reduced font cache creation times (https://bugs.freedesktop.org/show_bug.cgi?id=64766)
Includes a post-release build fix.
> fontconfig: update to version 2.13.0

- mingw-w64-ngraph-gtk/PKGBUILD
New upstream version 6.07.06 is released.
> ngraph-gtk: new upstream release version 6.07.06.

- mingw-w64-glib-openssl/PKGBUILD
- mingw-w64-glib-openssl/fix-cert-path.patch
Allows glib to use openssl for TLS instead of gnutls
> glib-openssl: New package

- mingw-w64-cppcheck/PKGBUILD
specify path to compiler to reduce chance that it will be called with the wrong compiler.
Make copies of source-code for each platform.  Othwise, you can get an error about unrecognized formats with w Win64 binary is used with a 32-bit binary build process.
Enable QChart.
enable build tests.
> Rebuild with imprevements

- mingw-w64-jq/PKGBUILD
- mingw-w64-oniguruma/PKGBUILD
mingw-w64-jq - 3.5 - Rebuild to prevent breakage
mingw-w64-oniguruma - 8.6.0 - Update to latest version
> Update jq, oniguruma

- mingw-w64-openssl/PKGBUILD
Out of curiosity: For [RubyInstaller](https://rubyinstaller.org) we're using OpenSSL-1.1.0 already, with an adjusted path-relocation patch. Are there plans to switch MSYS2/MINGW to OpenSSL-1.1.0 as well?
See: https://github.com/oneclick/rubyinstaller2-packages/tree/master/mingw-w64-openssl
> openssl: Update to 1.0.2o

- mingw-w64-wxWidgets/PKGBUILD
And, commented out the check function I added in the recent past.
I decided it makes no sense to run the check function just to build the samples.
Note: The sample and the tests do build now. Did not run either the samples or the tests.
In version 3.0.3, the non gui test seg faulted; and, that is likely still true.
Tim S.
> wxWidgets: Update to 3.0.4

- mingw-w64-poppler/003-fix-introspection.patch
- mingw-w64-poppler/PKGBUILD
Add the build directory to the library search path
> poppler: fix introspection build

- mingw-w64-mbedtls/PKGBUILD
https://tls.mbed.org/tech-updates/releases/mbedtls-2.8.0-2.7.2-and-2.1.11-released
> mbedtls: Updated to 2.8.0 [Security update]

- mingw-w64-sqlite3/PKGBUILD
The current package (ver 3.23.0) downloads a wrong amalgamation version (sqlite-autoconf-3210000.tar.gz instead of sqlite-autoconf-3230000.tar.gz)
So this commit in practice updates sqlite3 from version 3.21
> sqlite3: Update to 3.23.1

- mingw-w64-meld3/PKGBUILD
- mingw-w64-meld3/dont-use-private-api.patch
I think this type was supposed to be private in pango and not exported in the gir.
But it was anyway with the autotools build and now no longer is with the meson one.
The code in question was trying to set the win32 pango backend which is also
possible through an env var, so just do that instead and make sure we do it
before importing pango.
> meld3: fix "has no attribute Win32FontMap" error on start. Fixes #3610

- mingw-w64-fribidi/PKGBUILD
> fribidi: update source url to new location

- mingw-w64-http-parser/PKGBUILD
This updates http-parser to 2.8.1 and adds a missing import library for the dll.
> http-parser: update to 2.8.1

- mingw-w64-cmake/0001-Windows-Add-missing-stringapiset.h-include.patch
- mingw-w64-cmake/0003-Disable-response-files-for-MSYS-Generator.patch
- mingw-w64-cmake/0004-Implement-Qt5-static-plugin-support.patch
- mingw-w64-cmake/0005-Do-not-install-Qt-bundle-in-cmake-gui.patch
- mingw-w64-cmake/0006-pkg-config-Add-dont-define-prefix-when-PKG_CONFIG_WI.patch
- mingw-w64-cmake/0007-Do-not-generate-import-libs-for-exes.patch
- mingw-w64-cmake/0008-Output-line-numbers-in-callstacks.patch
- mingw-w64-cmake/PKGBUILD
The patch series was recreated by applying it to a CMake git checkout at
v3.10.1, and then rebasing it onto v3.11.0.
Patch 0004-Implement-Qt5-static-plugin-support.patch had to be
extensively redone, to support a refactoring in the Qt5 auto-gen support
in CMake 3.11.0. The rest of the patches are changed only due to
artifacts of this rebasing.
> cmake: Update to 3.11.0 (#3545)

- mingw-w64-protobuf/PKGBUILD
This updates protobuf to 3.5.2 and removes a failing check() function.
> protobuf: update to 3.5.2.

- mingw-w64-libcerf/0001-libcerf-1.5-fix-shared-lib.patch
- mingw-w64-libcerf/PKGBUILD
Previously the libcerf dll and its import library failed to build due to a lack of a -no-undefined flag. This commit fixes it.
> libcerf: fix shared build

- mingw-w64-wineditline/001-fix-installing.patch
- mingw-w64-wineditline/PKGBUILD
This updates wineditline to 2.205 and adds dos2unix as makedepends due
to troublesome crlf endings.
> wineditline: update to 2.205

- mingw-w64-ffcall/PKGBUILD
This adds ffcall (version 2.1).
I know that #2958 already has libffcall 2.0, but somehow it never got merged.
> add ffcall (version 2.1)

- mingw-w64-freetype/PKGBUILD
It no longer provides freetype-config by default, but some msys2 packages
use it, so re-enable with --enable-freetype-config for now as suggested in
the changelog.
> freetype: Update to 2.9.1

- mingw-w64-gst-libav/PKGBUILD
gst-libav does not support ffmpeg 4.0 yet, see #3668
> gst-libav: switch back to using an internal ffmpeg build. See #3668

- mingw-w64-gdb-git/0008-Avert-the-crash-when-using-info-register-on-Windows-.patch
- mingw-w64-gdb-git/PKGBUILD
Reference: https://sourceware.org/bugzilla/show_bug.cgi?id=22854
> gdb-git: Fix crash when using `info register` on Win64.

- mingw-w64-python-setuptools-scm/PKGBUILD
This updates python-setuptools-scm to 2.0.0.
> python-setuptools-scm: update to 2.0.0

- mingw-w64-mbedtls/PKGBUILD
https://tls.mbed.org/tech-updates/releases/mbedtls-2.9.0-2.7.3-and-2.1.12-released
> mbedtls: Updated to 2.9.0 [Security update]

- mingw-w64-OpenSceneGraph/PKGBUILD
> osg: fix copy license when pkgver contains dash

- mingw-w64-pngcrush/PKGBUILD
This updates pngcrush to 1.8.13.
> pngcrush: update to 1.8.13

- mingw-w64-x265/PKGBUILD
This updates x265 to 2.7 and enables all bit depths as well as dynamic HDR10.
> x265: update to 2.7

- appveyor.yml
PATH on appveyor contains 80+ directories and we don't need any of it.
> appveyor: Reduce PATH to the default Windows entries + git

- mingw-w64-python-backcall/PKGBUILD
It seems to me that the new `ipython `version requires this package. without that `ipython --version `gave me an error:
```
$ ipython --version
File "C:/msys64/mingw64/bin/ipython", line 4, in <module>
from IPython import start_ipython
File "C:/msys64/mingw64/lib/python3.6/site-packages\IPython\__init__.py", line 55, in <module>
from .terminal.embed import embed
File "C:/msys64/mingw64/lib/python3.6/site-packages\IPython\terminal\embed.py", line 15, in <module>
from IPython.core.interactiveshell import DummyMod, InteractiveShell
File "C:/msys64/mingw64/lib/python3.6/site-packages\IPython\core\interactiveshell.py", line 41, in <module>
from IPython.core.events import EventManager, available_events
File …
```
> New package: python-backcall

- mingw-w64-nghttp2/PKGBUILD
This updates nghttp2 to 1.31.1.
> nghttp2: update to 1.31.1

- mingw-w64-cython/PKGBUILD
This should fix a problem where cython .install scripts got mixed up. This fixes #3759.
> cython: fix .install file mixup

- mingw-w64-libgpg-error/PKGBUILD
This updates libgpg-error to 1.31.
> libgpg-error: update to 1.31

- mingw-w64-python-cffi/PKGBUILD
This updates python-cffi to 1.11.5.
> python-cffi: update to 1.11.5

- mingw-w64-python-wrapt/PKGBUILD
This fixes an unnecessary depends on python-six for python-wrapt.
> python-wrapt: fix depends

- mingw-w64-python-dateutil/PKGBUILD
This updates python-dateutil to 2.7.3 and adds a missing
python-setuptools-scm build dependency.
> python-dateutil: update to 2.7.3

- mingw-w64-glib-networking/PKGBUILD
This updates glib-networking to 2.56.1.
> glib-networking: update to 2.56.1.

- mingw-w64-jq/PKGBUILD
- mingw-w64-oniguruma/PKGBUILD
This updates oniguruma to 6.8.2 and rebuilds jq.
> oniguruma: update to 6.8.2 and rebuild jq

- mingw-w64-python-numpy/0003-gfortran-better-version-check.patch
- mingw-w64-python-numpy/0008-detect-mingw-environment2.patch
- mingw-w64-python-numpy/PKGBUILD
`numpy.test()` is similar to previous version:
```
----------------------------------------------------------------------
Ran 6416 tests in 29.883s
FAILED (KNOWNFAIL=29, SKIP=23, errors=1, failures=13)
```
> python-numpy: Update to 1.14.3

- mingw-w64-atk/PKGBUILD
This updates atk to 2.28.1 and adds gtk-doc to makedepends.
> atk: update to 2.28.1 and add missing makedepends

- mingw-w64-glib2/PKGBUILD
- mingw-w64-glib2/W32-gstdio-Dont-try-to-get-reparse-tag-uncondition.patch
> glib2: backport fix for the gtk3 file chooser not listing drives. Fixes #3584

- mingw-w64-gettext/122-Use-LF-as-newline-in-envsubst.patch
- mingw-w64-gettext/PKGBUILD
Add 122-Use-LF-as-newline-in-envsubst.patch
Also, adds "git" to makedepends; it is needed by "autogen.sh".
Tim S.
> gettext: Fix envsubst bug of newline being CR/LF (MSYS2 bug 735)

- mingw-w64-gtksourceview3/0007-fix-dllmain-typo-thread-to-process.patch
- mingw-w64-gtksourceview3/PKGBUILD
Release of global resources was accidently performed
on any thread exit instead of process exit/dll unload.
Premature releasing caused different stability problems.
This fixes https://github.com/Alexpux/MINGW-packages/issues/3510
> Patch fixing stability typo in libgtksourceview-3.0-1.dll's DllMain

- mingw-w64-intel-tbb/PKGBUILD
This updates intel-tbb to 2018_20180312.
> intel-tbb: update to 2018_20180312

- mingw-w64-python3/PKGBUILD
This formula didn't build because it is missing continuation characters.
> python3: fix typos

- mingw-w64-rhash/PKGBUILD
This package was failing build because it would install straight to the system `/mingw32` instead of the local package directory.
> rhash: do not install to system root while building

- mingw-w64-ninja/PKGBUILD
This package no longer builds with msys2 'python' so we use mingw-w64-python3 just like we do for the related mingw-w64-meson package.
> ninja: use python3 to build

- mingw-w64-python3-ipython/PKGBUILD
ipython attempts imports of the following missing runtime deps:
python3-backcall
python3-colorama
> python3-ipython: add missing deps

- mingw-w64-gdb-git/0005-Mitigate-gdb-bug-21057.patch
- mingw-w64-gdb-git/0009-Revert-changes-in-5045b3d-on-doc-gdb.texinfo.patch
- mingw-w64-gdb-git/PKGBUILD
This makes patch 0005 apply again.
This only fixes the patch in question. At this moment gdbserver doesn't compile.
> gdb-git: Update patch due to upstream changes.

- mingw-w64-quantlib/PKGBUILD
This updates quantlib to 1.13 and adds boost to depends as well as
makedepends.
> quantlib: update to 1.13

- mingw-w64-python-numpy/PKGBUILD
This updates python-numpy to 1.14.5.
> python-numpy: update to 1.14.5

- mingw-w64-tesseract-ocr/PKGBUILD
The V3 branch of tesseract requires training data from the v3 branch. The master branch of the training data is now serving data for the experimental tesseract v4.
> tesseract: download correct training data

- mingw-w64-gcc-git/0019-gcc-8-branch-Backport-patches-for-std-filesystem-from-master.patch
- mingw-w64-gcc-git/PKGBUILD
This makes the patch in question apply again, which was broken by
~~r262404~~r262388 on GCC SVN.
Reference: https://gcc.gnu.org/viewcvs?rev=262388&root=gcc&view=rev
> gcc-git: Fix filesystem patch.

- mingw-w64-ruby/0005-rbinstall-rake-bash.patch
- mingw-w64-ruby/PKGBUILD
Patch to get rid of the error produced when invoking the mingw build of rake from bash.
Addresses issue https://github.com/Alexpux/MINGW-packages/issues/4021
> Patch for error-free invocation of rake under bash #4021

- mingw-w64-python-setuptools/PKGBUILD
Looks like prepare() got passed the version at some point? It's at least
not happening here and breaks the build due to the patch not getting applied.
> setuptools: remove hardcoded Python versions; fix build

- mingw-w64-python-atomicwrites/PKGBUILD
- mingw-w64-python-pytest/PKGBUILD
```python
File "tests/runtests.py", line 9, in <module>
import pytest
File "C:\msys64\MINGW64\lib\python2.7\site-packages/pytest.py", line 9, in <module>
from _pytest.config import main, UsageError, cmdline, hookspec, hookimpl
File "C:\msys64\MINGW64\lib\python2.7\site-packages/_pytest/config/__init__.py", line 19, in <module>
import _pytest.assertion
File "C:\msys64\MINGW64\lib\python2.7\site-packages/_pytest/assertion/__init__.py", line 9, in <module>
from _pytest.assertion import rewrite
File "C:\msys64\MINGW64\lib\python2.7\site-packages/_pytest/assertion/rewrite.py", line 15, in <module>
import atomicwrites
ImportError: No module named atomicwrites
```
> pytest: fix missing atomicwrites dependency

- mingw-w64-python3-jupyter-notebook/PKGBUILD
Please note that can be built only without logging - a `bower `error will stop building if you use `-L` switch
>  New package: python3-jupyter-notebook (Version: 5.5.0) 

- mingw-w64-meson/0004-python-find-path.patch
- mingw-w64-meson/PKGBUILD
meson uses the py.exe to figure out the path of the default python2/3
but msys2 python doesn't install it. This leads to it finding the
system Python and getting the wrong path.
This fixes the gobject-introspection build with meson (not the default yet..)
> meson: fix python module in case the official Python is installed

- mingw-w64-PKGBUILD-templates/PKGBUILD.setup-py-python-pkg
Add export SETUPTOOLS_SCM_PRETEND_VERSION=$pkgver to prepare for setuptools-scm if necessary.  That's required for release versions (not a git repository)
Clearly denote a section in the python2 and python3 install sections for .exe's and other scripts that are deployed in the /mingw*/bin directories  Also note what needs to removed for packages that do not do this.
For python2 scripts and .exe's, add code to rename scripts and executables to avoid a name conflict with python3 packages.
> Revisions to the mingw-w64-python package template.

- mingw-w64-gcc/PKGBUILD
*makes binutils(except ld) support lto objects by default(liblto_plugin-0.dll)
*more info [here](https://github.com/bminor/binutils-gdb/blob/master/bfd/plugin.c#L329)
> gcc: install plugins for binutils

- mingw-w64-qt5-static/0036-qt-5.3.2-win32-qt5-static-cmake-link-ws2_32-and--static.patch
- mingw-w64-qt5-static/0042-qt-5.4.0-static-cmake-also-link-plugins-and-plugin-deps.patch
- mingw-w64-qt5-static/PKGBUILD
- mingw-w64-qt5/0036-qt-5.3.2-win32-qt5-static-cmake-link-ws2_32-and--static.patch
- mingw-w64-qt5/0042-qt-5.4.0-static-cmake-also-link-plugins-and-plugin-deps.patch
- mingw-w64-qt5/PKGBUILD
actually set INTERFACE_LINK_LIBRARIES in patch 0042
append so subsequent calls for different configurations don’t reset each other
the only thing set was IMPORTED_LINK_INTERFACE_LIBRARIES_${Configuration}
and that was overridden by a non-empty INTERFACE_LINK_LIBRARIES
i believe there never was a INTERFACE_LINK_LIBRARIES_${Configuration}
don’t overwrite but append INTERFACE_LINK_LIBRARIES in patch 0036
> qt5-static: fix #4081

- mingw-w64-sfml/PKGBUILD
- mingw-w64-sfml/mingw-w64-msys2.patch
This change updates sfml to 2.5.0. mingw-w64-msys2.patch has been adapted to the modifications of sfml 2.5.0, and patch has been added to makedepends in PKGBUILD.
> sfml: Update to 2.5.0

- mingw-w64-python-prometheus-client/PKGBUILD
- mingw-w64-python3-jupyter-notebook/PKGBUILD
There is also a new dependency (`python-prometheus-client`) which I have added:
- New package: python-prometheus-client (Version: 0.2.0)
- python3-jupyter-notebook: Update to 5.6.0
due to npm issue, build python3-jupyter-notebook without logging, ie: `makepkg -sCf`
> python3-jupyter-notebook: Update to 5.6.0

- mingw-w64-ngraph-gtk/PKGBUILD
new upstream version 6.07.07 is released.
> ngraph-gtk new upstream version 6.07.07.

- mingw-w64-python3/0500-add-python-config-sh.patch
- mingw-w64-python3/PKGBUILD
"python3-config --ldflags --cflags" doesn't return anything because
"$*" results in one string, not sure why this was changed in the first place.
Switch it back to "$@" which expands to multiple words.
Noticed because I wondered why this patch is needed on Windows only:
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gobject-introspection/0055-fix-python-detection.patch
> python3: fix python3-config handling of multiple arguments

- mingw-w64-x86_64-cross-binutils/PKGBUILD
*multiple packages are generated from _targets array
*built tools can be used with clang or gcc in cross-compilation
*ccache can be used to speed up building this
> Add universal pkgbuild for cross-binutils

- mingw-w64-glib2/0001-glib2-mr-226.patch
- mingw-w64-glib2/PKGBUILD
Patch taken from https://gitlab.gnome.org/GNOME/glib/merge_requests/226
Requires a rebuild of the affected applications.
> glib2: fix stack corruption by g_stat() for 64bit build. Fixes #4134

- mingw-w64-python-pillow/PKGBUILD
This updates python-pillow to 5.2.0.
> python-pillow: update to 5.2.0

- mingw-w64-python-hypothesis/PKGBUILD
This updates python-hypothesis to 3.67.1.
> python-hypothesis: update to 3.67.1

- mingw-w64-python-pystemmer/PKGBUILD
This rebuilds python-pystemmer against python 3.7, while adding cython to makedepends to fix building.
> python-pystemmer: rebuild, fix build

- mingw-w64-enchant/001_fix_relocation.patch
- mingw-w64-enchant/PKGBUILD
This fixes relocation support of enchant which was not working since the update to enchant-2 (#4008) and therefore rendered this package useless.
> enchant: fix relocation support

- mingw-w64-python-numexpr/PKGBUILD
This updates python-numexpr to 2.6.7.
> python-numexpr: update to 2.6.7

- mingw-w64-python-lxml/PKGBUILD
This updates python-lxml to 4.2.4.
> python-lxml: update to 4.2.4

- mingw-w64-libatomic_ops/PKGBUILD
This updates libatomic_ops to 7.6.6. Both shared libraries and static libraries are now built.
> libatomic_ops: update to 7.6.6

- mingw-w64-libvncserver/PKGBUILD
Note that shared libs are disabled currently since they don't build successfully on Windows yet.
> Add libvncserver/libvncclient.

- mingw-w64-p11-kit/PKGBUILD
This updates p11-kit to 0.23.13.
> p11-kit: update to 0.23.13

- mingw-w64-intel-tbb/PKGBUILD
This updates intel-tbb to 2018_20180618.
> intel-tbb: update to 2018_20180618

- mingw-w64-libatomic_ops/PKGBUILD
This replaces erroneous tabs with spaces for the PKGBUILD for libatomic_ops.
> libatomic_ops: replace tabs with spaces

- mingw-w64-python-cryptography/PKGBUILD
This updates python-cryptography to 2.3.1.
> python-cryptography: update to 2.3.1

- mingw-w64-python-pytest/PKGBUILD
This updates python-pytest to 3.7.1.
> python-pytest: update to 3.7.1

- mingw-w64-python-more-itertools/PKGBUILD
This updates python-more-itertools to 4.3.1.
> python-more-itertools: update to 4.3.1

- mingw-w64-python-certifi/PKGBUILD
This updates python-certifi to 2018.8.13.
> python-certifi: update to 2018.8.13

- mingw-w64-pycairo/PKGBUILD
This updates pycairo to 1.17.1.
> pycairo: update to 1.17.1

- mingw-w64-gdcm/PKGBUILD
> gdcm: update to 2.8.7

- mingw-w64-gtk-vnc/PKGBUILD
This updates gtk-vnc to 0.9.0.
> gtk-vnc: update to 0.9.0

- mingw-w64-python-reportlab/PKGBUILD
This updates python-reportlab to 3.5.5.
> python-reportlab: update to 3.5.5

- mingw-w64-python-scandir/PKGBUILD
This updates python-scandir to 1.9.0.
> python-scandir: update to 1.9.0

- mingw-w64-protobuf/PKGBUILD
This updates protobuf to 3.6.1.
> protobuf: update to 3.6.1

- mingw-w64-python-pytest/PKGBUILD
This updates python-pytest to 3.7.2.
> python-pytest: update to 3.7.2

- mingw-w64-harfbuzz/PKGBUILD
- mingw-w64-python-fonttools/PKGBUILD
- mingw-w64-python-fonttools/fonttools2-i686.install
- mingw-w64-python-fonttools/fonttools2-x86_64.install
- mingw-w64-python-fonttools/fonttools3-i686.install
- mingw-w64-python-fonttools/fonttools3-x86_64.install
mingw-w64-harfbuzz - 1.8.8 - add python3-fonttools  as a test dependency - compile with both Uniscribe and DirectWrite support options
mingw-w64-python-fonttools - 3.29 - Converts OpenType and TrueType fonts to and from XML
> two packages where one depends upon the other.

- mingw-w64-python-greenlet/PKGBUILD
This updates python-greenlet to 0.4.14.
> python-greenlet: update to 0.4.14

- mingw-w64-gtk2/0013_fix_mouse_events.patch
- mingw-w64-gtk2/PKGBUILD
This prevents transparent top-level windows from intercepting mouse events as often the case with screen capturing software (e.g, Skype), see https://bugzilla.gnome.org/show_bug.cgi?id=780979
> gtk2: add patch from GIMP project

- mingw-w64-ruby-cairo/PKGBUILD
This updates ruby-cairo to 1.15.14.
> ruby-cairo: update to 1.15.14

- mingw-w64-python-ndg-httpsclient/PKGBUILD
This updates python-ndg-httpsclient to 0.5.1.
> python-ndg-httpsclient: update to 0.5.1

- mingw-w64-python-reportlab/PKGBUILD
This updates python-reportlab to 3.5.6.
> python-reportlab: update to 3.5.6

- mingw-w64-PKGBUILD-templates/PKGBUILD.setup-py-python-pkg
- mingw-w64-PKGBUILD-templates/python-exe-installs/somepackage2-i686.install
- mingw-w64-PKGBUILD-templates/python-exe-installs/somepackage2-x86_64.install
- mingw-w64-PKGBUILD-templates/python-exe-installs/somepackage3-i686.install
- mingw-w64-PKGBUILD-templates/python-exe-installs/somepackage3-x86_64.install
Fix for setup.py template, a fix for running python-compiled .EXE bin scripts.  zyjr /zrcr od do,[;u sm rmytu  [pomy.  Added a directory containing the installs to complete the fixup on the user's system so that the scrips have fully-qualified paths that differ from the packager.  This seems to be best way of doing this with packages such as whell and some other things I've working on.
> PKGBUILD.setup-py - fixes for patch and .EXE installs.

- mingw-w64-python-certifi/PKGBUILD
This updates python-certifi to 2018.8.24.
> python-certifi: update to 2018.8.24

- mingw-w64-gpgme/0007-mkdefsinc-use-CPPFLAGS.patch
- mingw-w64-gpgme/PKGBUILD
This fixes the build on the CI and some Windows systems
see #4165 
thanks to @vyache-slav for providing the patch
> gpgme: make mkdefsinc use CPPFLAGS

- mingw-w64-nasm/0001-Remove-invalid-pure_func-qualifiers.patch
- mingw-w64-nasm/PKGBUILD
Fix compilation with GCC 8: https://bugzilla.nasm.us/show_bug.cgi?id=3392461
> nasm: fix build for gcc-8

- mingw-w64-p11-kit/PKGBUILD
This updates p11-kit to 0.23.14.
> p11-kit: update to 0.23.14

- mingw-w64-python-hypothesis/PKGBUILD
This updates python-hypothesis to 3.70.3.
> python-hypothesis: update to 3.70.3

- mingw-w64-python-imagesize/PKGBUILD
This updates python-imagesize to 1.1.0.
> python-imagesize: update to 1.1.0

- mingw-w64-glib2/PKGBUILD
Filed upstream: https://gitlab.gnome.org/GNOME/glib/issues/1516
> glib2: remove internal static libs from .pc files. Fixes #4364

- mingw-w64-curl/PKGBUILD
- mingw-w64-nghttp2/PKGBUILD
mingw-w64-nghttp2 - Update to 1.33.0 -nghttp2 is used by curl for http2 support.
> mingw-w64-curl - Update to 7.61.1

- mingw-w64-python-pytest/PKGBUILD
This updates python-pytest to 3.7.4.
> python-pytest: update to 3.7.4

- mingw-w64-python-lxml/PKGBUILD
This updates python-lxml to 4.2.5.
.asc file no longer exists, so removed from sources array.
> python-lxml: update to 4.2.5

- mingw-w64-gettext/122-Use-LF-as-newline-in-envsubst.patch
- mingw-w64-gettext/PKGBUILD
This patch changes to binary mode to output linefeed and the changes back to prior mode.
The original patch changed to text mode after using binary mode.
After thinking about it, I decided this was wrong; and, changed the patch to restore the prior mode.
Tim S.
> gettext: Update 122-Use-LF-as-newline-in-envsubst.patch

- mingw-w64-libssh/PKGBUILD
> libssh: update to 0.8.3

- mingw-w64-python-numpy/PKGBUILD
This updates python-numpy to 1.15.2.
> python-numpy: update to 1.15.2

- mingw-w64-python-pycparser/PKGBUILD
This updates python-pycparser to 2.19.
> python-pycparser: update to 2.19

- mingw-w64-allegro/PKGBUILD
WebP image support has been added to Allegro in 5.2.3
> allegro: depend on libwebp

- mingw-w64-mbedtls/PKGBUILD
https://tls.mbed.org/tech-updates/releases/mbedtls-2.13.0-2.7.6-and-2.1.15-released
> mbedtls: Update to 2.13.0

- mingw-w64-srt/0006-no-msvc-compat-headers.patch
- mingw-w64-srt/PKGBUILD
They error out if msvc isn't used and we are C99 compatible anyway.
This fixes the gst-plugins-bad build (at least some of it)
> srt: don't include msvc compat headers for stdint/inttypes

- mingw-w64-python3/2100-configure-fix-openssl-checks.patch
- mingw-w64-python3/PKGBUILD
openssl no longer includes windows.h and requires the user to do so first.
with those checks failing python gets built without openssl support.
> python3: fix openssl build checks

- mingw-w64-gcc/0020-gcc-8.2.0-Backport-patches-for-std-variant-_M_destructive_move.patch
- mingw-w64-gcc/PKGBUILD
Fix the problem of gcc-8.2.0 about std::swap on std::variant
The problem is reported at:
https://www.mail-archive.com/gcc-bugs@gcc.gnu.org/msg581872.html
This is fixed by replacing a header using the version fetched from gcc 8.2.1
So this patch has to be removed when we move to real 8.2.1
See issue #4477
> Fix the problem of gcc-8.2.0 about std::swap on std::variant

- mingw-w64-qt5-static/0042-qt-5.4.0-static-cmake-also-link-plugins-and-plugin-deps.patch
- mingw-w64-qt5-static/0301-remove-evr-declaration.patch
- mingw-w64-qt5-static/PKGBUILD
- mingw-w64-qt5/0042-qt-5.4.0-static-cmake-also-link-plugins-and-plugin-deps.patch
- mingw-w64-qt5/PKGBUILD
collect deps for Qt5::$${CMAKE_MODULE_NAME} instead of Qt5::Core
(regression from 796a15ede3e71a56282c5553b87ca0fbe8fcba64)
appaned multiple items instead of using _list_sep manually
add missing 0301 patch for qt5-static
> qt5 fixes (fix #4455)

- mingw-w64-python-markdown/PKGBUILD
This updates python-markdown to 3.0.1.
> python-markdown: update to 3.0.1

- mingw-w64-qt5-static/0042-qt-5.4.0-static-cmake-also-link-plugins-and-plugin-deps.patch
- mingw-w64-qt5-static/PKGBUILD
- mingw-w64-qt5/0042-qt-5.4.0-static-cmake-also-link-plugins-and-plugin-deps.patch
- mingw-w64-qt5/PKGBUILD
add the basic dependencies independent of the configuration (they are the same for all configuration anyway)
since _populate_$${CMAKE_MODULE_NAME}_target_properties is called twice – for DEBUG and RELEASE – and we APPEND here, they are duplicated in the end, which isn’t nice, but also unproblematic
originally the second call overwrites the configuration independent values with the second call, which is kinda stupid
however, the static dependencies _are_ configuration dependent, which requires MAP_IMPORTED_CONFIG_<CONFIG> to be set for MINSIZEREL and RELWITHDEBINFO to work
for these 2 special configuration, this actually makes the first change redundant
configurations other than the 4 default ones (also an empty CMAKE_BUILD_TYPE) will work with the first change for the shared version – as …
> qt5 fix configurations that are neither debug nor release (fix #4495)

- mingw-w64-gpgme/PKGBUILD
- mingw-w64-gpgme/gpgmepp-portable-types.patch
- mingw-w64-gpgme/relocatable-cmake.patch
* Use computed relative paths in CMake files instead of absolute MSYS paths
* Use portable `gpgme_off_t` and `gpgme_ssize_t` to fix link issues in clients
> Fixes for gpgme++

- mingw-w64-codelite-git/PKGBUILD
CodeLite requires libclang during run-time.
> codelite-git: Move "${MINGW_PACKAGE_PREFIX}-clang" to run-time depends

- mingw-w64-python-defusexml/PKGBUILD
- mingw-w64-python2-backports.os/PKGBUILD
- mingw-w64-python3-jupyter-nbconvert/PKGBUILD
mingw-w64-python3-nbconvert-nbconvert - 5.4 - require mingw-w64-python-defusexml
> mingw-w64-python-defusexml - 0.5.0 - New package required by nbconvert

- mingw-w64-python-scikit-learn/PKGBUILD
There are deep directory structures, make sure your base directory is short when you build.
> python-scikit-learn: Update to 0.20.0

- mingw-w64-plplot/PKGBUILD
- mingw-w64-plplot/fix-install-dir.patch
- mingw-w64-plplot/fix-qhull-lib.patch
I add 2 patchs to plplot build to:
* Disable the link of qhull in pkg-config because it is statically link in plplot (see #2880).
* Add the support for reading the install directory of plplot to allow data files (e.g. fonts) to be retrieved.
> Fixed plplot qhull link and install dir

- mingw-w64-python3/1900-ctypes-dont-depend-on-internal-libffi.patch
- mingw-w64-python3/PKGBUILD
https://github.com/python/cpython/pull/9258 changed callproc to
use functions from the internal libffi which we don't use.
Just copy the functions into callproc directly instead.
> python3: fix ctypes module build. Fixes #4572

- mingw-w64-nghttp2/PKGBUILD
This updates nghttp2 to 1.34.0.
> nghttp2: update to 1.34.0

- mingw-w64-c-ares/0002-Add-static-pkg-config.patch
- mingw-w64-c-ares/PKGBUILD
This updates c-ares to 1.15.0.
> c-ares: update to 1.15.0

- mingw-w64-python-dateutil/PKGBUILD
- mingw-w64-python-freezegun/PKGBUILD
- mingw-w64-python-hypothesis/PKGBUILD
- mingw-w64-python-pluggy/PKGBUILD
- mingw-w64-python-pytest-xdist/PKGBUILD
- mingw-w64-python-pytest/PKGBUILD
- mingw-w64-python-pytz/PKGBUILD
python-hypothesis - 2.80.0 - Update to latest version
python-pluggy - 0.8.0 - Clarified dependencies, enable testing
python-pytest - 2.9.3 - Update to latest version
python-pytz - 2018.6 - Update to latest version
python-freezegun - 0.3.11 - new package required for testing dateutils
python-pytest-xdist - 1.23.2 - required by python-coverage
> python-dateutil - 2.7.5 Update to latest version

- mingw-w64-tesseract-data/PKGBUILD
The new version of tesseract (https://github.com/Alexpux/MINGW-packages/pull/4603) uses a new format for training data, see [tesseract wiki](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files).
> tesseract-data: update to 4.0.0

- mingw-w64-libsigc++/PKGBUILD
This updates libsigc++ to 2.10.1.
> libsigc++: update to 2.10.1

- mingw-w64-cgns/0001-stat32i64-is-msvc-specific.patch
- mingw-w64-cgns/PKGBUILD
The CGNS library and tools are used to store and process data related to
computational fluid dynamics.
I had to backport a small patch to fix an issue with compiling with MinGW. Other than that, this is a straight forward package.
Patch reference: https://github.com/CGNS/CGNS/commit/e22bbdb767d6d310d085c37f9bd55f4de16baa74
Signed-off-by: Francis Giraldeau <francis.giraldeau@nrc-cnrc.gc.ca>
> Add CFD General Notation System tools and library

- mingw-w64-cvode/PKGBUILD
CVODE is a solver for systems of ordinary differential equations.
More info: https://computation.llnl.gov/projects/sundials/sundials-software
This package is straight forward. The only issue was the DLLs are installed in the lib directory. I move them in the package step from lib to bin. 
Signed-off-by: Francis Giraldeau <francis.giraldeau@nrc-cnrc.gc.ca>
> Add cvode package

- mingw-w64-python-tox/PKGBUILD
- mingw-w64-python-tox/tox2-i686.install
- mingw-w64-python-tox/tox2-x86_64.install
- mingw-w64-python-tox/tox3-i686.install
- mingw-w64-python-tox/tox3-x86_64.install
Add dependency on python-filelock and python-toml
add commented code for tests (those hang)
Make sure tox .exe's will run from MSYS command line.
> python-tox - 3.5.3

- mingw-w64-python-pbr/PKGBUILD
Update with new information
added tests
Fixup dependencies for tests and build.  Setuptools as a depends is NO typo
use PBR_VERSION to stamp build with proper version for consistency checks with pip.
> python-pbr - 5.1.1 - Various fixes

- mingw-w64-python-setuptools/PKGBUILD
Since pip got unvendored in #4379 the Python classes of system packages
and vendored packages clash. This removes the vendored packages from
setuptools so only system dependencies are used in both pip and setuptools.
The downside of this is that it's not officially supported by upstream
and this creates cyclic dependencies and makes bootstrapping harder.
If this turns out to be a problem we should probably revert this
and #4379.
> python-setuptools: unvendor dependencies. Fixes #4623
