msys2/MINGW-packages

mingw-w64-cgal/PKGBUILD

Sorry, forgot to do this in previous PR.

cgal: update pkgrel to 2

---

mingw-w64-breakpad-svn/PKGBUILD

This is a mingw version of breakpad, including the client library. It needs to be tested.

breakpad-svn: New package

---

mingw-w64-nim/0001-Use-unixy-filenames-even-on-Windows.patch
mingw-w64-nim/0002-Recognize-mingw-in-build.sh.patch
mingw-w64-nim/PKGBUILD
mingw-w64-nimble/PKGBUILD

Nim currently can't find neither nim.cfg or any library under lib/nim.
Requested by @mingwandroid.

WIP new package: nim compiler, nimble package manager

---

mingw-w64-nimble/PKGBUILD

WIP nimble: Fixed URL and possibly a mistake in package()

---

mingw-w64-json-c/PKGBUILD

From https://github.com/json-c/json-c , latest stable official tarball.
This is one of MyPaint's dependencies, and it'd be great to have it available in the same way as all our other deps.
Closes Alexpux/MINGW-packages#429

Add libjson-c

---

mingw-w64-pngcrush/LICENSE
mingw-w64-pngcrush/PKGBUILD

64-bit build went okay, haven't tried 32-bit yet.

pngcrush: Updated to 1.7.83

---

mingw-w64-opusfile/PKGBUILD

Hello!
This is my first mingw package. Please link me to any stuff that I didn't read :)
Thanks!

opusfile: New package

---

mingw-w64-gexiv2/001-win.patch
mingw-w64-gexiv2/PKGBUILD

Is there any guidance how to pack such stuff?

gexiv2: fix install of typelib and python overrides

---

mingw-w64-goocanvas/001-convert-python-path-to-unix.patch
mingw-w64-goocanvas/002-fix-introspection.patch
mingw-w64-goocanvas/PKGBUILD

This enable introspection support: build goocanvas typelib and python overrides

goocanvas: adding introspection support

---

mingw-w64-qt5-static/PKGBUILD
mingw-w64-qt5/PKGBUILD

- I haven't tested with 5.4.1 yet (because the change is minor and I think it won't break the build)

qt5: update to 5.4.1

---

mingw-w64-cmake/PKGBUILD

Update went fine, but I don't really know CMake, so I can't test it properly.

cmake: updated to v3.2.1, added missing dependency

---

mingw-w64-port-scanner/PKGBUILD
mingw-w64-port-scanner/paths.patch

Small utility.
Could be also a nice example of how to do relocation.

port-scanner: New package

---

mingw-w64-glpk/PKGBUILD
mingw-w64-glpk/timeval-64bit.patch

Thanks @mingwandroid for helping me with the crash.

glpk: Fix crash in 64-bit build, add GMP support

---

mingw-w64-opencollada-git/PKGBUILD

opencollada: Update to r1079, fix cmake files

---

mingw-w64-lua/PKGBUILD
mingw-w64-lua/implib.patch
mingw-w64-lua/searchpath.patch

Updated lua to version 5.3
Changes:
* updated version number
* updated md5sums
* updated patchfile locations

lua: updated to 5.3

---

mingw-w64-python-icu/PKGBUILD

import PyICU
PyICU.VERSION
can segfault

python-icu: fix version string

---

mingw-w64-gdk-pixbuf2/0002-gdk-pixbuf-introspection.patch
mingw-w64-gdk-pixbuf2/PKGBUILD

gdk-pixbuf2: fix introspection

---

mingw-w64-editrights/PKGBUILD
mingw-w64-editrights/uncygwinize.patch

editrights: New package

---

mingw-w64-wxwidgets/PKGBUILD

also added the static build instructions in.

enabled opengl support and forced gdi+ graphics context

---

mingw-w64-curl/0004-sasl_sspi-Populate-domain-from-the-realm-in-the-chal.patch
mingw-w64-curl/PKGBUILD

cherry-picked from upstream commit
59f3f92ba6150e9a5a57f71b6e781802148916d0

curl: Fix digest authentication

---

mingw-w64-clang-svn/PKGBUILD

pkgver is changed somehow. I don't know much about pacman if that's normal or not.

Fix the md5sum for the patch file in pkg build.

---

mingw-w64-gplugin/001-win.patch
mingw-w64-gplugin/PKGBUILD
mingw-w64-pidgin-hg/001-win.patch
mingw-w64-pidgin-hg/PKGBUILD

unfortunately pidgin hangs on start, like the previous pkgbuild version

new package gplugin; enabled plugins and introspection in pidgin-hg

---

mingw-w64-tor/PKGBUILD

tor: New package

---

mingw-w64-portmidi/PKGBUILD
mingw-w64-portmidi/enable-install-on-windows.patch

portmidi: New library

---

mingw-w64-ladspa-sdk/PKGBUILD
mingw-w64-rubberband/PKGBUILD
mingw-w64-vamp-plugin-sdk/PKGBUILD

As I originally requested in [#639](https://github.com/Alexpux/MINGW-packages/issues/639)
This is Rubberband and Vamp-SDK (a dependency of Rubberband not currently in the repo).  I compiled and tested both 32 and 64 bit Rubberband successfully using the PKGBUILDs from this pull request.

Rubberband

---

mingw-w64-tesseract-ocr-eng/PKGBUILD
mingw-w64-tesseract-ocr-osd/PKGBUILD
mingw-w64-tesseract-ocr/PKGBUILD

All recent changes are only being made on github. Please update the source files. Thanks!

change Tesseract-ocr source to github

---

mingw-w64-cmake-git/PKGBUILD
mingw-w64-cmake/PKGBUILD

This misplaced file is merely a website redirect.

Fix useless file installed by CMake in root directory

---

mingw-w64-rust/PKGBUILD

Not fully tested in makepkg-mingw

rust: Update to 1.1.0

---

mingw-w64-catch/PKGBUILD

Trying this pull request again.  Thanks!

catch: Update to 1.2.1.

---

mingw-w64-tesseract-ocr/PKGBUILD

More details at
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-dev/8e0F2cK2YzU/EHH59yMJIowJ

Update for Tesseract-ocr 3.04.00 release

---

mingw-w64-kicad-git/PKGBUILD

* Use only git sources
* Make the rev count align with the upstream BZR rev

Update kicad 

---

mingw-w64-mypaint/PKGBUILD
mingw-w64-mypaint/mypaint-i686.install
mingw-w64-mypaint/mypaint-x86_64.install

PKGBUILD for the latest release tarball distributed on github. Is it reasonable to add a mypaint-git as well?

Add mypaint

---

mingw-w64-winsparkle-git/Makefile
mingw-w64-winsparkle-git/PKGBUILD

This fixes build of new version and/or build with GCC 5.

Fix winsparkle build

---

FAIL_LIST.md
mingw-w64-tclvfs/001-fix-detect-mingw.patch
mingw-w64-tclvfs/PKGBUILD

SF CVS service is working again.

tclvfs: Fixed MinGW detection

---

mingw-w64-xz-git/PKGBUILD

Tested with Travis CI: https://travis-ci.org/fracting/xz/jobs/73616615#L3205
Note that I didn't test 64bit version. Also I didn't test git fetch, I use source code fetch by host git in Travis CI.
Thanks for review!

Add xz-git package.

---

mingw-w64-libvorbis/PKGBUILD

Update libvorbis to 1.3.5

---

mingw-w64-gettext/PKGBUILD

Bump pkgrel of mingw-w64-gettext to allow a new release

---

mingw-w64-freetype/PKGBUILD

freetype: Fix hard coded path prefix.

---

mingw-w64-libbotan/PKGBUILD
mingw-w64-libbotan/boost-link.patch
mingw-w64-libbotan/disable-mkgmtime.patch
mingw-w64-libbotan/winsock-link.patch

[Botan](http://botan.randombit.net/) (Japanese for peony) is a C++ cryptography library released under the permissive Simplified BSD license.
Currently package can only provide static libraries due to an upstream [issue](https://github.com/randombit/botan/issues/289) (and its not easy to patch because a custom build system is used).

Add libbotan package

---

mingw-w64-osgqtquick/PKGBUILD

osgQtQuick - OpenSceneGraph QML Modules
Main project page:
https://github.com/podsvirov/osgqtquick
After install package you can type from mingw32 or mingw64 shell:
wget https://github.com/podsvirov/osgqtquick/raw/develop/tests/sokoban.qml
qmlscene sokoban.qml
It will run test game script.

Add osgQtQuick packages

---

mingw-w64-libharu/PKGBUILD
mingw-w64-libharu/win_lib.patch
mingw-w64-libharu/win_various_install_files.patch
mingw-w64-muparser/CMakeLists.txt
mingw-w64-muparser/PKGBUILD
mingw-w64-podofo/PKGBUILD
mingw-w64-podofo/win.patch

This is new PKGBUILD for [PoDoFo](http://podofo.sourceforge.net/), [muparser](http://muparser.beltoforion.de/) and [libHaru](http://libharu.org/).
It's my firsts PKGBUILD for MSYS2 so they can have several mistakes...

Add PoDoFo, muparser and libHaru

---

mingw-w64-libtorrent-rasterbar/PKGBUILD

Just a simple update for libtorrent-rasterbar

update libtorrent-rasterbar to 1.0.6

---

mingw-w64-fox/PKGBUILD
mingw-w64-fox/fox-1-rdynamic.patch
mingw-w64-fox/fox-2-FXTrayIcon.patch
mingw-w64-fox/fox-3-chart.patch

New package for [FOX toolkit] (http://fox-toolkit.org)

fox-toolkit package

---

mingw-w64-midori/PKGBUILD

Just some midori changes. It's still highly wip. A while back the midori team added support for debugging using dr mingw so hopefully this will help figure out what's going with the 64bit side of things. Again, wip

Small midori update (WIP changes)

---

mingw-w64-hub/PKGBUILD

go: fix build

---

mingw-w64-scite/PKGBUILD
mingw-w64-sqlite-analyzer/PKGBUILD
mingw-w64-sqlite3/PKGBUILD

scite: Update to v3.6.2
sqlite3, sqlite-analyzer: Update to v3.9.2

Some updates

---

mingw-w64-pngcrush/PKGBUILD

pngcrush: Update to v1.7.88

---

mingw-w64-extra-cmake-modules/PKGBUILD
mingw-w64-png2ico/PKGBUILD
mingw-w64-png2ico/fix_include.diff

We might need to discuss the disabled patch for ecm

Add png2ico as dep to exm, update ecm

---

mingw-w64-gprbuild-gpl/0001_gnat_vmsp.patch
mingw-w64-gprbuild-gpl/PKGBUILD
mingw-w64-gtkada/PKGBUILD
mingw-w64-gtkada/space_issue.patch
mingw-w64-xmlada-gpl/PKGBUILD

1. fix gtkada build issue
2. build mingw ada tools first version with gcc (not gprbuild)

ada gtk solution for mingw

---

mingw-w64-kicad-git/PKGBUILD

hello, here is the fix for https://github.com/KiCad/kicad-doc/issues/211

fix kicad doc mirror

---

mingw-w64-glade3/PKGBUILD
mingw-w64-glade3/glade3-i686.install
mingw-w64-glade3/glade3-x86_64.install
mingw-w64-gtksourceviewmm2/000-C11.patch
mingw-w64-gtksourceviewmm2/PKGBUILD
mingw-w64-sqlheavy/000-libvala.patch
mingw-w64-sqlheavy/PKGBUILD

gtksourceviewmm  for gtk+-2.0
glade3.8.5
sqlheavy 0.1.1: sqlite3 gobject api wrap

more useful gtk+-2.0 modules

---

mingw-w64-libtorrent-rasterbar/PKGBUILD

added static instructions for building static libtorrent and updated

---

mingw-w64-cocos2dx-git/PKGBUILD

cocos2dx-git : Add missing depends

---

mingw-w64-hdf5/PKGBUILD
mingw-w64-szip/PKGBUILD

Add static libraries for hdf5 and szip

---

mingw-w64-catch/PKGBUILD

For the packages I contribute, I try to monitor the upstream projects for new releases.  A new version of Catch was released just yesterday, so this pull request updates our MSYS2 package.

catch: Update to version 1.3.1.

---

mingw-w64-python-cycler/PKGBUILD
mingw-w64-python-matplotlib/PKGBUILD

python-cycler: Created PKGBUILD
python-matplotlib: Added python-cycler as dependency to matplotlib>=1.5

python-cycler: New package

---

mingw-w64-cego/PKGBUILD
mingw-w64-lfcxml/PKGBUILD

After git pull --rebase another try to get things in sync ..

Another try to pull lfcxml-1.2.1 and cego-2.28.1

---

mingw-w64-cego/PKGBUILD
mingw-w64-dragon/PKGBUILD
mingw-w64-lfcxml/PKGBUILD

This pull adds the PKGBUILD file for the dragon software package from www.lemke-it.com.
Dragon is a parser generator used to generate object oriented C++ or Java code.
For more information, please check www.lemke-it.com

Added PKGBUILD file for dragon parser generator

---

mingw-w64-cego/PKGBUILD
mingw-w64-dragon/PKGBUILD
mingw-w64-lfcxml/PKGBUILD

Update lfcxml to version 1.2.2
Update dragon to version 1.4.1
Update cego to version 2.28.3

Package version update

---

mingw-w64-osgearth/0001-Fix-mingw-debug-build.patch
mingw-w64-osgearth/0002-Forced-include-headers-for-Qt5-moc-on-files-without-.patch
mingw-w64-osgearth/0003-Build-fix-against-OSG-3.4.0-and-OSG-3.5.0.patch
mingw-w64-osgearth/PKGBUILD

This adds [osgearth](http://osgearth.org)

mingw-w64-osgearth: Initial commit. v2.7

---

mingw-w64-global/002-fix-sigset_t-undefined.txt
mingw-w64-global/PKGBUILD
mingw-w64-global/glo652.txt

GNU GLOBAL source code tagging system (mingw-w64)

New package GNU global

---

mingw-w64-quantlib/PKGBUILD

This release specifically fixes the windows build.

Fix quantlib windows build

---

mingw-w64-v8/PKGBUILD

1) corrected directory in lines 37 and 73
2) added fix for python call in line 49
3) upped versionto 4.3.66

Updated PKGBUILD for mingw-w64-v8

---

.drone.yml
drone/build.sh

This is a similar patch like https://github.com/Alexpux/MSYS2-packages/pull/434
Hopefully it works as expect, I'll do more tests once it's merged. Thanks!

drone: Fix build script. Introduce matrix builds.

---

drone/build.sh

Shame for the syntax error.
Now it's a good chance to test the pull request system...

Fix syntax.

---

.drone.yml
drone/build.sh

This is a sync of https://github.com/Alexpux/MSYS2-packages/pull/437

drone: Improve PKGBUILD detection. Switch irc notify to #msys2-ci.

---

mingw-w64-libswift/PKGBUILD

Added LibSwift to msys2 for the first time"

Added Libswift to msys2 repo

---

ci-build.sh

This time should be fine.
Testing here: http://wine-ci.org/Alexpux/MINGW-packages/36

Continuous Integration: Test package installaton after successful build.

---

mingw-w64-fossil/PKGBUILD
mingw-w64-fossil/readline.patch
mingw-w64-fossil/win.patch
mingw-w64-sqlite-analyzer/PKGBUILD
mingw-w64-sqlite-analyzer/lemon.patch
mingw-w64-sqlite3/PKGBUILD

Update+fix sqlite3, sqlite-analyzer and fossil

---

ci-build.sh

Colored output and source code refactoring.

Improvements for continuous integration

---

mingw-w64-pidgin/001-autotools-and-fhs.patch
mingw-w64-pidgin/002-build-fixes.patch
mingw-w64-pidgin/PKGBUILD

This adds the current release 2.x with autotools/FHS support. Thanks to @DoctorWho11 for finding [the patch](https://build.opensuse.org/package/view_file/windows:mingw:win32/mingw32-pidgin/pidgin-2.10.11-autotools.patch) that implements this.

New package pidgin

---

mingw-w64-openblas/PKGBUILD

Detected by our nice stress testing in https://github.com/Alexpux/MINGW-packages/pull/1077 :)

mingw-w64-openblas: Fix install.

---

mingw-w64-sqlite-analyzer/PKGBUILD
mingw-w64-sqlite3/PKGBUILD

Another problem detected by our nice stress testing: https://github.com/Alexpux/MINGW-packages/pull/1077 
(Please wait for CI build result, I haven't test locally yet)

Sqlite checksum updates

---

mingw-w64-openssl/PKGBUILD

For https://github.com/Alexpux/MINGW-packages/issues/1086

openssl: Add ca-certificates as optdepends.

---

mingw-w64-dmake/PKGBUILD
mingw-w64-gcc/PKGBUILD

Ref: https://github.com/Alexpux/MINGW-packages/pull/1077#issuecomment-186880520

two fixes to the previous, url update commit

---

mingw-w64-gtest/PKGBUILD
mingw-w64-msgpack-c/0010-detect-mingw.patch
mingw-w64-msgpack-c/PKGBUILD

* Google Test 1.7.0
* Msgpack for C/C++

Add new packages: gtest, msgpack-c

---

mingw-w64-tesseract-ocr/PKGBUILD

https://github.com/tesseract-ocr/tesseract/releases
https://github.com/tesseract-ocr/tesseract/archive/3.04.01.tar.gz

Update Tesseract Pkgbuild to use 3.04.01 release

---

mingw-w64-extra-cmake-modules/PKGBUILD

Hi Alexey,
this little thing is merely a test of the work-flow for me, in case I'll come up with more contributions in the future.
Thanks,
Marko

ECM: update to latest KF5 version

---

mingw-w64-gtest/PKGBUILD
mingw-w64-msgpack-c/PKGBUILD

gtest, msgpack-c: Add suffix "(mingw-w64)" to `pkgdesc`

---

mingw-w64-tesseract-ocr-eng/PKGBUILD

Tesseract-OCR-eng traineddata

---

mingw-w64-ceres-solver/PKGBUILD

Add ceres-solver library (http://ceres-solver.org/) version 1.11.0

Add ceres-solver

---

mingw-w64-ceres-solver/PKGBUILD
mingw-w64-ceres-solver/ceres-solver-1.11.0.patch

Update ceres-solver CMakeList.txt files to:
- install cmake config files to MINGW_PREFIX/lib/cmake/Ceres; and
- correctly detect OpenBLAS without a special command-line option in the cmake call

Update ceres-solver CMakeList.txt files

---

mingw-w64-cereal/PKGBUILD
mingw-w64-cereal/cereal-1.1.2.patch

Add cereal library (http://uscilab.github.io/cereal/) version 1.1.2

Add cereal

---

mingw-w64-LASzip/LASzip-2.2.0.patch
mingw-w64-LASzip/PKGBUILD

Add LASzip library (http://www.laszip.org/) version 2.2.0, which is a dependency for the libLAS library (http://www.liblas.org/).

Add LASzip

---

mingw-w64-LASzip/LASzip-2.2.0.patch
mingw-w64-LASzip/PKGBUILD
mingw-w64-libLAS/PKGBUILD
mingw-w64-libLAS/libLAS-1.8.0.patch

Add libLAS library (http://www.liblas.org/) version 1.8.0.

Add libLAS

---

.drone.yml

This is a sync of https://github.com/Alexpux/MSYS2-packages/pull/501

Drone CI: Always pull latest image.

---

.gitattributes
mingw-w64-pdfium-git/PKGBUILD
mingw-w64-pdfium-git/pdfium-2679.2b2cbeb.patch
mingw-w64-pdfium-git/pdfium-2681.r2604.30410ce.patch

Add Google's pdfium library from git repo (https://pdfium.googlesource.com/pdfium/)

Add pdfium

---

mingw-w64-cego/PKGBUILD
mingw-w64-lfcbase/PKGBUILD
mingw-w64-lfcxml/PKGBUILD

Updated lfcbase-1.8.0, lfcxml-1.2.3, cego-2.29.4

Updated to new version

---

mingw-w64-luajit-git/PKGBUILD

Fix depend and bump version

---

mingw-w64-mpv/PKGBUILD

[DO NOT MERGE] Fix depends and bump version

---

mingw-w64-qt5-git/PKGBUILD

qt5-git: fix missing newline in depends

---

.drone.yml

fracting/msys32 will be deprecated.

CI: Switch image to teaci/msys32.

---

mingw-w64-python-decorator/PKGBUILD
mingw-w64-python-ipython/PKGBUILD
mingw-w64-python-ipython_genutils/PKGBUILD
mingw-w64-python-path/PKGBUILD
mingw-w64-python-pickleshare/PKGBUILD
mingw-w64-python-simplegeneric/PKGBUILD
mingw-w64-python-traitlets/PKGBUILD

python-path: Created PKGBUILD
python-pickleshare: Created PKGBUILD
python-simplegeneric: Created PKGBUILD
python-traitlets: Created PKGBUILD
python-ipython: Added python-traitlets, python-simplegeneric, python-pickleshare, python-path, python-ipython_genutils as dependency

Fix IPython dependencies

---

mingw-w64-arm-none-eabi-binutils/PKGBUILD
mingw-w64-dbus/PKGBUILD

Revert checksum-only changes from previous pull request.

Fix checksums for a couple of packages

---

mingw-w64-graphite2/PKGBUILD

This should fix the error *could not remove database entry* when updating the system.

Adjustment in graphite2 recipe

---

mingw-w64-arpack/PKGBUILD

Upgrade to version 3.3.0 and do "make check" to run the testsuite.  With
this version, also run their bootstrap script.

Upgrade to 3.3.0 and run tests

---

mingw-w64-purple-skypeweb-git/Makefile
mingw-w64-purple-skypeweb-git/PKGBUILD
mingw-w64-purple-skypeweb/Makefile
mingw-w64-purple-skypeweb/PKGBUILD

This adds the SkypeWeb plugin to libpurple clients such as Finch, Pidgin and Pidgin++.

New package for Pidgin SkypeWeb

---

mingw-w64-osgearth-git/0001-Fixed-crash-due-to-probable-GCC-5.3.0-optimizer-bug.patch
mingw-w64-osgearth-git/PKGBUILD

based on mingw-w64-openscenegraph-git
no need to distribute

osgearth-git: new package

---

mingw-w64-openssl/PKGBUILD

openssl: update to new release

---

mingw-w64-graphite2/003-graphite2-1.3.8-staticbuild.patch
mingw-w64-graphite2/PKGBUILD

mingw-w64-graphite2 - 1.3.8 - build and install static library through patch.

mingw-w64-graphite2 - 1.3.8 - build and install static library

---

mingw-w64-waf/PKGBUILD

mingw-w64-waf - 1.8.20 - update to new version

mingw-w64-waf - 1.8.20 - update to new version

---

mingw-w64-winsparkle/PKGBUILD
mingw-w64-winsparkle/winsparkle-0.5.patch

WinSparkle library version 0.5, replacing package "winsparkle-git"

Add winsparkle

---

mingw-w64-librsync/PKGBUILD
mingw-w64-librsync/library-location.patch

Upstream is also on GitHub: https://github.com/librsync/librsync

mingw-w64-librsync: Add new package, v2.0.0

---

mingw-w64-libmypaint/PKGBUILD

As requested, a PKGBUILD for our latest [pre]release, https://github.com/mypaint/libmypaint/releases/tag/v1.3.0-beta.0

Add libmypaint

---

README.md
appveyor.yml
mingw-w64-octopi-git/0011-MSYS2-Changes-to-various-system-calls.patch
mingw-w64-octopi-git/PKGBUILD

Updates for Alexpux/MSYS2-packages#612.

Updates for filesystem changes

---

mingw-w64-go/PKGBUILD

go: update to 1.6.2

---

mingw-w64-googletest-git/PKGBUILD
mingw-w64-googletest-git/googletest-0a43962.patch

Add googletest and googlemock libraries from GitHub (https://github.com/google/googletest)

Add googletest and googlemock

---

mingw-w64-curl/0001-curl-relocation.patch
mingw-w64-curl/PKGBUILD

curl 7.49.1: Update to latest version and rekey patch

curl 7.49.1: Update to latest version and rekey patch

---

mingw-w64-libmypaint/PKGBUILD

New tarball release is out, so I've updated the MINGW-packages build.

libmypaint: update for v1.3.0-beta.1

---

mingw-w64-python-sphinx/PKGBUILD

python{2,3}-imagesize added to depends

python{2,3}-sphinx: update and add missing depend

---

mingw-w64-libmicrohttpd/PKGBUILD

A can maintain this package as I'm maintainer of upstream.

update libmicorhttpd to latest version

---

ci-build.sh
ci-library.sh

Fix saneman installation and update, see #1504.

Fixes for continuous integration

---

mingw-w64-purple-facebook-git/001-build-fixes.patch
mingw-w64-purple-facebook-git/PKGBUILD
mingw-w64-purple-facebook/001-build-fixes.patch
mingw-w64-purple-facebook/PKGBUILD
mingw-w64-purple-hangouts-hg/Makefile
mingw-w64-purple-hangouts-hg/PKGBUILD

Hangouts and Facebook protocols for libpurple clients.

New packages for Purple Hangouts and Facebook

---

mingw-w64-qt5-git/0050-disable-default-lib-include-detection.patch
mingw-w64-qt5-git/PKGBUILD

This is the damn patch that caused it:
https://codereview.qt-project.org/#/c/157817/

Add patch 0050 to resolve wrong qmake lib/include detection

---

ci-library.sh

Same to
https://github.com/Alexpux/MSYS2-packages/pull/649

CI: Use --needed when installing pactoys.

---

mingw-w64-libsignal-protocol-c-git/PKGBUILD

Native library for the Signal/Axolotl protocol.

New package for Signal protocol

---

mingw-w64-wxwidgets/PKGBUILD
mingw-w64-wxwidgets/wxWidgets-3.0.2-windows-version.patch

This fixes the issues described in #1226.

wxWidgets: Fix issues on Windows 10.

---

mingw-w64-fontconfig/PKGBUILD

Simply  updates fontconfig to 2.12.0.
Patches still apply.

Update Fontconfig to 2.12.0

---

mingw-w64-geoip/PKGBUILD

geoip: new package, 1.6.9 version

---

mingw-w64-soci/PKGBUILD
mingw-w64-soci/soci-3.2.3.patch

SOCI library from http://soci.sourceforge.net/ (on GitHub: https://github.com/SOCI/soci)

add SOCI library (version 3.2.3)

---

mingw-w64-clucene/PKGBUILD
mingw-w64-clucene/clucene-core-2.3.3.4.patch

CLucene library from http://clucene.sourceforge.net/

add CLucene

---

mingw-w64-python-networkx/PKGBUILD
mingw-w64-python-openmdao/PKGBUILD
mingw-w64-python-sqlitedict/PKGBUILD
mingw-w64-python-wcwidth/PKGBUILD

python-openmdao:  http://openmdao.org/
python-networkx: https://networkx.github.io/
python-sqlitedict: https://pypi.python.org/pypi/sqlitedict

Created PKGBUILD

---

mingw-w64-cego/PKGBUILD
mingw-w64-lfcbase/PKGBUILD

Updated lfcbase to version 1.8.9
Updated cego to version 2.30.20

Updated lfcbase + cego

---

mingw-w64-qt-solutions-git/0001-Don-t-install-the-libraries-in-win32.patch
mingw-w64-qt-solutions-git/PKGBUILD

The qt-solutions package wasn't building, I updated it to the latest git and it compiles cleanly with qt5

Updating qt-solutions package

---

mingw-w64-lmdbxx/PKGBUILD

lmdb++ (C++ wrapper for LMDB) from http://lmdbxx.sourceforge.net/
GitHub repo: https://github.com/bendiken/lmdbxx

Add lmdb++

---

mingw-w64-antlr3/PKGBUILD

ANTLR3 library from http://www.antlr3.org/
GitHub repo: https://github.com/antlr/antlr3

Add ANTLR3

---

mingw-w64-mpfr/PKGBUILD
mingw-w64-mpfr/mpfr-3.1.4-p3.patch

Update MPFR to 3.1.4-p3 version

---

mingw-w64-ffmpeg/PKGBUILD

Upated PKGBUILD and switched to .tar.xz file format.

ffmpeg updated to version 3.1.2

---

mingw-w64-cego/PKGBUILD
mingw-w64-lfcbase/PKGBUILD

Update cego to version 2.30.26

Update lfcbase to version 1.8.10

---

mingw-w64-pugixml/CMakelist-deploy-in-subdirs.patch
mingw-w64-pugixml/PKGBUILD

Added pugixml package. Compiles and seems to work fine.
As this is my first package contribution, please bear with me if I made errors. Feedback always welcome
-Developer site: [http://pugixml.org/](http://pugixml.org/)
-Github repo: [https://github.com/zeux/pugixml](https://github.com/zeux/pugixml)

Add pugixml

---

mingw-w64-sqlightning-git/PKGBUILD
mingw-w64-sqlightning/PKGBUILD

sqlightning library (master branch on https://github.com/LMDB/sqlightning)

Add sqlightning

---

mingw-w64-gdk-pixbuf2/PKGBUILD

but branch 2.35.x isn't it the development branch?

gdk-pixbuf2: update to 2.35.4.

---

mingw-w64-webkitgtk3/PKGBUILD
mingw-w64-webkitgtk3/webkitgtk-2.4.9-abs.patch

Fixes https://github.com/Alexpux/MINGW-packages/issues/1715

webkitgt: add patch for compilation with GCC 6

---

mingw-w64-osm-gps-map/PKGBUILD

Added osm-gps-map package. Compiles and seems to work fine.

Added osm-gps-map library

---

mingw-w64-cmake/PKGBUILD
mingw-w64-curl/PKGBUILD
mingw-w64-expat/PKGBUILD
mingw-w64-jsoncpp/PKGBUILD
mingw-w64-ncurses/PKGBUILD

cmake - 2.6.2
curl 7.50.3
expat - 2.2.0
jsoncpp - 1.7.5
ncurses - 6.0 - 20160917

Update cmake and some dpenedances to latest versions

---

mingw-w64-git-lfs/0001-Translate-git-paths-from-msys-to-windows.patch
mingw-w64-git-lfs/PKGBUILD

This adds a PKGBUILD for git-lfs: https://git-lfs.github.com

add PKGBUILD for git-lfs

---

mingw-w64-libgd/PKGBUILD
mingw-w64-libgd/libgd-export-pkg-config-build-in-subdirs.patch

Had to apply a small patch to be able to compile on Windows/MSYS2.

Added libgd package

---

mingw-w64-cppcheck/0020-change-cfg-path.patch
mingw-w64-cppcheck/PKGBUILD

Additional changes:
* fix search directory of "cfg"

cppcheck: update to 1.75

---

mingw-w64-lua-luacom-git/001-Fix-Lua51-prefix.patch
mingw-w64-lua-luacom-git/002-CMake-AR.patch
mingw-w64-lua-luacom-git/003-Lua_51_PATH.patch
mingw-w64-lua-luacom-git/004-Lua_51_INC.patch
mingw-w64-lua-luacom-git/PKGBUILD
mingw-w64-lua-luacom-git/luacom.def
mingw-w64-lua-luacom-git/luacom.pc

luacom is a package to operate Microsoft office in Lua script

luacom for lua5.1

---

mingw-w64-antlr4-git/PKGBUILD
mingw-w64-antlr4-git/antlr4-4.5.3.r4904.6f62821.patch

ANTLR4 C++ runtime
https://github.com/DanMcLaughlin/antlr4/tree/master/runtime/Cpp

Add ANTLR4

---

mingw-w64-vtk/PKGBUILD

see https://github.com/Alexpux/MINGW-packages/issues/1670

vtk: fix generated cmake files to not reference C:/building

---

mingw-w64-libgphoto2/PKGBUILD
mingw-w64-libgphoto2/libgphoto2-gp_system_filename-fix.patch

libgphoto2 is a free, redistributable, ready to use set of digital camera software applications.

Added libgphoto2 library

---

mingw-w64-mypaint-git/PKGBUILD
mingw-w64-mypaint-git/mypaint-i686.install
mingw-w64-mypaint-git/mypaint-x86_64.install

Add a package for building MyPaint master from git. Byproduct of making app-level "-git" test packages at my end for achadwick/styrene#3 ☺
(I don't expect regular binary builds of this, of course!)

Add mypaint-git

---

mingw-w64-gdal/PKGBUILD

Updated GDAL to version 2.1.1 as it contains some important bug fixes compared to previous version.

Updated GDAL to version 2.1.1

---

mingw-w64-lua-lsqlite3/Makefile.mingw
mingw-w64-lua-lsqlite3/PKGBUILD
mingw-w64-lua-lsqlite3/installpath.lua
mingw-w64-lua-lsqlite3/lunit.lua

lua sqlite3 wrapper for lua5.1

lua sqlite3 wrapper

---

mingw-w64-flickcurl/PKGBUILD
mingw-w64-flickcurl/flickcurl-1.26-build.patch

Both shared and static libraries, tested and works.

Adding library: flickcurl

---

mingw-w64-portaudio/PKGBUILD

A fresh new stable release since January 30, 2014!

PortAudio updated to stable release 190600_20161030

---

mingw-w64-nsis/PKGBUILD

nsis: makedepend on dos2unix

---

mingw-w64-graphene/PKGBUILD

Seemingly now a build dependency of git GTK.
Introspection isn't working yet.

Add graphene

---

mingw-w64-mcfgthread-git/PKGBUILD

@mingwandroid 
Do you have any interest in it? :joy:

mingw-w64-mcfgthread-git: New package.

---

ci-library.sh

This fix makes color output working in appveyor CI builds

Appveyor: fix color output

---

mingw-w64-lua-luarocks/PKGBUILD
mingw-w64-lua-luarocks/README.md
mingw-w64-lua-luarocks/luarocks-i686.install
mingw-w64-lua-luarocks/luarocks-x86_64.install
mingw-w64-lua-luarocks/mingw32-msys2.patch

LuaRocks is the package manager for Lua modules.

luarocks for mingw64 in MSYS2

---

mingw-w64-jansson/PKGBUILD
mingw-w64-nghttp2/PKGBUILD
mingw-w64-spdylay/PKGBUILD
mingw-w64-spdylay/spdylay-1.4.0-fix-zlib.patch

mingw-w64-nghttp2 - 1.16.1 - Update to latest version and use spdylay
mingw-w64-spdylay -  1,49,0 - New package - SPDY protocol version 2,3, and 3.1 implementation

mingw-w64-jansson - 2.9 - Update to latest version

---

mingw-w64-docbook-dsssl/PKGBUILD
mingw-w64-docbook-dsssl/docbook-dsssl-i686.install
mingw-w64-docbook-dsssl/docbook-dsssl-x86_64.install
mingw-w64-docbook-dsssl/docbook-style-dsssl.Makefile
mingw-w64-docbook-mathml/LICENSE
mingw-w64-docbook-mathml/PKGBUILD
mingw-w64-docbook-mathml/docbook-mathml-i686.install
mingw-w64-docbook-mathml/docbook-mathml-x86_64.install
mingw-w64-docbook-sgml/PKGBUILD
mingw-w64-docbook-sgml/docbook-sgml-i686.install
mingw-w64-docbook-sgml/docbook-sgml-x86_64.install
mingw-w64-docbook-sgml31/PKGBUILD
mingw-w64-docbook-sgml31/docbook-sgml31-i686.install
mingw-w64-docbook-sgml31/docbook-sgml31-x86_64.install
mingw-w64-sgml-common/PKGBUILD
mingw-w64-sgml-common/sgml-common-0.6.3-manpage-1.patch
mingw-w64-sgml-common/sgml-common-0.6.3-sysconfdir.patch
mingw-w64-sgml-common/sgml-common-i686.install
mingw-w64-sgml-common/sgml-common-x86_64.install

mingw-w64-docbook-dssl - 1.79 - New package
mingw-w64-docbook-mathml -  1.1CR1 - New Package
mingw-w64-docbook-sgml - 4.5 - New Package
mingw-w64-docbook-sgml31 - 3.1 - New Package (legacy)
mingw-w64-sgml-common - 0.63 - New Package

More Docbook stuff

---

mingw-w64-enca/PKGBUILD
mingw-w64-ffmpeg/PKGBUILD
mingw-w64-fontconfig/PKGBUILD
mingw-w64-libass/PKGBUILD
mingw-w64-mpv/PKGBUILD

This also updates related packages (fontconfig, libass, ffmpeg, enca.)

Update mpv to 0.22.0

---

mingw-w64-fossil/PKGBUILD

- due to not found zlib1.dll
- also make use of new download location

fossil: revbump needed

---

mingw-w64-globjects/PKGBUILD
mingw-w64-globjects/config-export-location.patch
mingw-w64-globjects/mingw-unix-layout.patch

[globjects ](https://github.com/cginternals/globjects)is an MIT licensed, cross-platform C++ wrapper for OpenGL API objects.

globjects: Add new package

---

mingw-w64-glfw/PKGBUILD
mingw-w64-glm/PKGBUILD
mingw-w64-mesa/PKGBUILD
mingw-w64-nanovg-git/PKGBUILD

mingw-w64-glfw - 3.2.1 - add vulkan-headers as makedependency.  Update to latest version
mingw-w64-glm - 0.9.8.3 - Update to latest version
mingw-w64-mesa - 13.0.2  - Update to latest version.  Added graw.dll and libgraw.a to package.  Got Win32 32-bit version
mingw-w64-nanovg-git - Updated to latest version on git and did some minor tweeking

some OpenGL things

---

mingw-w64-libmypaint/PKGBUILD

Libmypaint version 1.3.0 has just been released: <https://github.com/mypaint/libmypaint/releases/tag/v1.3.0>. I've updated the PKGBUILD, please can it be merged?

libmypaint: update to 1.3.0

---

mingw-w64-gdal/PKGBUILD
mingw-w64-gdal/fix_nullptr_check.patch

The patch is also commited into gdal repo which is pending at the moment: https://github.com/OSGeo/gdal/pull/179.

Updated GDAL to version 2.1.2 and added patch for null pointer issue.

---

mingw-w64-jpegoptim/PKGBUILD

New package: Jpegoptim 1.4.4

---

mingw-w64-openocd-git/PKGBUILD

I have commented provides and conflicts which produce error during makepkg and I have added a dependency: libftdi

Update OpenOCD pkgbuild

---

mingw-w64-libbotan/PKGBUILD

libbotan: Updated to 2.0.0

---

mingw-w64-glslang/PKGBUILD
mingw-w64-opencl-headers/PKGBUILD
mingw-w64-spirv-tools/PKGBUILD

mingw-w64-glslang - 3.0.git2.eee9d53 - New package
mingw-w64-spirv-tools - 2016.6 - New package

mingw-w64-opencl-headers - 2.1.20161129 - Update to latest version

---

mingw-w64-qrencode/PKGBUILD

It's a C library for encoding data in a QR Code symbol.

PKGBUILD for qrencode library.

---

mingw-w64-aztecgen/PKGBUILD
mingw-w64-aztecgen/aztecgen-noexcept.patch
mingw-w64-aztecgen/aztecgen-typename_fix.patch
mingw-w64-aztecgen/aztecgen-unix_slashes.patch

It's a simple library for encoding "Aztec Code" barcodes.
Patches fix various build issues.

PKGBUILD for aztecgen library.

---

mingw-w64-oce/oce-i686.install
mingw-w64-oce/oce-x86_64.install

Remove hardcoded path from OCE release cmake files

---

mingw-w64-grpc/0001-grpc-mingw64.patch
mingw-w64-grpc/PKGBUILD

Update with back-ported build system changes from git snapshot onto 1.0.1.

mingw-w64-grpc: updated grpc to 1.0.1

---

mingw-w64-gtk2/0017-fix-dead-keys-part-4.patch
mingw-w64-gtk2/PKGBUILD

gtk2: restore XP compatibility

---

mingw-w64-gdb/PKGBUILD
mingw-w64-gdb/gdb-7.12-readline-mingw.patch

Fixes issue #1952
We revert to using Readline from GDB
We apply a patch from GDB master related to Readline and Mingw
TUI works too.

Fixes buggy readline 7 in GDB

---

mingw-w64-meld3/PKGBUILD

pkgbuild works but the software not very well. Someone can try?

[Don't create the package] meld: updated to 3.16.4.

---

mingw-w64-clang/0009-fix-llvm-config-shared-lib-version-on-win32.patch
mingw-w64-clang/PKGBUILD

Fixes https://github.com/Alexpux/MINGW-packages/issues/2107

clang: fix llvm-config shared lib detection

---

mingw-w64-mypaint/PKGBUILD

As used for <https://github.com/mypaint/mypaint/releases/tag/v1.2.1>.

mypaint: update for 1.2.1 release

---

mingw-w64-openocd/PKGBUILD

Signed-off-by: Paul Fertser <fercerpav@gmail.com>

openocd: package stable 0.10.0 release

---

mingw-w64-grpc/PKGBUILD

emmenlau grpc 1.1.0-pre1 update

---

mingw-w64-gdb-git/0005-Mitigate-gdb-bug-21057.patch
mingw-w64-gdb-git/PKGBUILD

See https://sourceware.org/bugzilla/show_bug.cgi?id=21057.

Mitigate gdb bug 21057.

---

mingw-w64-mcfgthread-git/PKGBUILD

Should this be how we handle package splitting in the future? :joy::joy::joy:

mingw-w64-mcfgthread-git/PKGBUILD: Do smart package splitting.

---

mingw-w64-mpv/PKGBUILD

mpv: update to 0.24

---

mingw-w64-libcdr/PKGBUILD
mingw-w64-libvisio/PKGBUILD

First package, so let me know if I should change something...

Add "mingw-w64-libvisio" and update dependencies and license for "mingw-w64-libcdr"

---

mingw-w64-curl/PKGBUILD

... backing out the backported patch...

Update cURL to v7.53.1

---

mingw-w64-gflags/PKGBUILD
mingw-w64-gflags/gflags-2.2.0.patch

- use release version instead of git commit
- update patch

Update gflags to release 2.2.0

---

mingw-w64-flatbuffers/PKGBUILD
mingw-w64-flatbuffers/flatbuffers-1.6.0.patch

- compile shared library also
- patch CMakeLists.txt to install .dll to bin folder
- exclude CONTRIBUTING.md from extracting
*note: "CONTRIBUTING.md" was failing to extract on my machine, so I had to workaround it

Update flatbuffers to release 1.6.0

---

mingw-w64-allegro/PKGBUILD

Also add an opus/opusfile dependency.

Update Allegro to 5.2.2

---

mingw-w64-gdcm/PKGBUILD

A slightly older version of the Grassroots DICOM library

mingw-w64-gdcm: initial revision

---

mingw-w64-osgearth/0002-geos-3_6_1-support.patch
mingw-w64-osgearth/PKGBUILD

intial fix was causing crashes
see https://github.com/gwaldron/osgearth/pull/848

osgearth: fix the geos 3.6.1 support patch

---

mingw-w64-grpc/0001-grpc-1_1_4-sin6.patch
mingw-w64-grpc/PKGBUILD

Build tested on x86_64 and i686.

mingw-w64-grpc: updated to 1.1.4

---

mingw-w64-mathgl/PKGBUILD
mingw-w64-mathgl/mathgl-2.3.5.1.patch

MathGL from http://mathgl.sourceforge.net/doc_en/Main.html
There are many optional dependencies that I made requirements (for the sake of simplicity, since I do not know exactly which of them are truly optional and which are needed at run-time).

Add package MathGL (version 2.3.5.1)

---

mingw-w64-gtk3/PKGBUILD

I tested the build with i686 and x86_64

gtk3: updated to 3.22.10

---

mingw-w64-libspectre/PKGBUILD

Seems that out-of-source build not working for 0.2.8

libspectre

---

mingw-w64-sqlcipher/01-fix_dep.diff
mingw-w64-sqlcipher/PKGBUILD

Closes https://github.com/Alexpux/MINGW-packages/issues/2323

sqlcipher: new package

---

mingw-w64-ngraph-gtk/PKGBUILD

new version of ngraph-gtk 6.07.03 is released.

new upstream release.

---

mingw-w64-enchant/PKGBUILD

This closes #2364.
Should there be any issues with the Aspell back-end I'm not aware of let me know...

Enchant: re-enable Aspell backend

---

mingw-w64-curl/PKGBUILD

curl: update to v7.54.0

---

mingw-w64-gcc/PKGBUILD
mingw-w64-gdb/PKGBUILD

Fixup for https://github.com/Alexpux/MINGW-packages/pull/2354
Closes https://github.com/Alexpux/MINGW-packages/issues/2396

{gcc,gdb}: fix checksums

---

mingw-w64-gcc/PKGBUILD
mingw-w64-gcc/gcc7-pr79665.patch

According to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79665
this patch should fix code generation and instructions etc.
Also this can apply to gcc 7 too whenever it's decided to move to gcc 7

This new patch should help generate better code

---

mingw-w64-binaryen/PKGBUILD

binaryen (WebAssembly compiler) release 1.37.10 from https://github.com/WebAssembly/binaryen

Add package binaryen

---

mingw-w64-xmlsec/01-shared-linking.patch
mingw-w64-xmlsec/PKGBUILD

All tests except one were running successfully.

New package: xmlsec Fixes #2404

---

mingw-w64-cppunit/Add-define-guard-for-NOMINMAX.patch
mingw-w64-cppunit/PKGBUILD

And, added make check/check method.
I also had to add a patch to fix build errors.
Tim S.

cppunit: Updated to version "1.14.0".

---

mingw-w64-libgpg-error/07-windows-build.patch
mingw-w64-libgpg-error/PKGBUILD

libgpg-error: Update to 1.27

---

mingw-w64-chromaprint/PKGBUILD

* Fix website url
* Adjust source url to github
* Remove fix for missing PROJECT_VERSION, fixed upstream:
https://github.com/acoustid/chromaprint/commit/321ee9402a3a1

chromaprint: Update to 1.4.2

---

mingw-w64-gnutls/PKGBUILD

* Switch from ftp to https
* Update validpgpkeys

gnutls: Update to 3.5.12

---

mingw-w64-libgcrypt/PKGBUILD

* Adding make check
* Fixes #2460

libgcrypt: update to 1.7.7

---

mingw-w64-libmicrohttpd/PKGBUILD

libmicrohttpd: update to v0.9.55

---

mingw-w64-jsonrpc-glib/PKGBUILD

For now i disabled introspection due to an error that i didn't solve.

jsonrpc-glib: new package.

---

mingw-w64-qt5/PKGBUILD

*don't unpack unused modules
*perform dead code elimination

qt5: some improvements

---

mingw-w64-python-sphinx/PKGBUILD

python-sphinx: Fix dependencies

---

mingw-w64-armadillo/PKGBUILD

Armadillo: update to 7.950.1

---

mingw-w64-nodejs/0001-Fix-python-invocation-to-python2.patch
mingw-w64-nodejs/0002-Fix-system-icu-build.patch
mingw-w64-nodejs/0003-Include-win32-headers.h-in-v8-atomicops.h.patch
mingw-w64-nodejs/0004-Define-localtime_s-for-MinGW.patch
mingw-w64-nodejs/0005-Remove-.lib-suffix-on-linked-libraries.patch
mingw-w64-nodejs/0006-Define-_WIN32_WINNT-in-node.gyp.patch
mingw-w64-nodejs/0007-Skip-sys-resource-and-unneeded-includes-in-node.cc.patch
mingw-w64-nodejs/0008-Link-with-municode-and-extern-wmain-for-Unicode.patch
mingw-w64-nodejs/0009-Remove-no_rand_screen-from-s_client-invocation.patch
mingw-w64-nodejs/0010-Fix-incorrect-test-assumptions-for-MinGW.patch
mingw-w64-nodejs/0011-detect-architecture.patch
mingw-w64-nodejs/0012-Use-shell-wrapper-script-for-npm-on-MSYS2-MinGW-w64.patch
mingw-w64-nodejs/0013-Revert-to-FHS-installation-paths-on-Windows-tests-no.patch
mingw-w64-nodejs/PKGBUILD

It compiled locally but let's see how it will work on CI.

nodejs: update to 6.11.0 and include npm

---

mingw-w64-gdal/0002-libproj4-dll-name.patch
mingw-w64-gdal/PKGBUILD
mingw-w64-osgearth/PKGBUILD

OsgEarth and gdal improvments

---

mingw-w64-cmake/PKGBUILD

cmake: correctly apply all patches with helper function

---

mingw-w64-glslang/001-install-missing-dll.patch
mingw-w64-glslang/PKGBUILD
mingw-w64-vpp-git/PKGBUILD

GCC 7.1.0 is required for compiling vcc.

some vulkan stuff

---

mingw-w64-libmariadbclient/PKGBUILD
mingw-w64-libmariadbclient/fix-pthread.patch

Upgrade + patch for 2.3.3. upstream.

update libmariadbclient to 2.3.3

---

mingw-w64-tulip/001-fix-tulip-python-install.patch
mingw-w64-tulip/002-fix-undo-redo-crash.patch
mingw-w64-tulip/PKGBUILD

Add tulip 5.0.0 package: a large graphs analysis, drawing and visualization framework (http://tulip.labri.fr/)

add tulip 5.0.0 package

---

mingw-w64-cego/PKGBUILD
mingw-w64-lfcbase/PKGBUILD

version update
lfcbase : Update to version 1.10.0
cego : Update to version 2.34.0

cego + lfcbase

---

mingw-w64-openblas/PKGBUILD

due to wrong commit, i created a new pull request

openblas: Update to 2.20

---

mingw-w64-glog/PKGBUILD
mingw-w64-glog/glog-0.3.5.patch

glog: Update to 0.3.5

---

mingw-w64-libdvdread/PKGBUILD

libdvdread: fix git-path

---

mingw-w64-pygobject2/PKGBUILD
mingw-w64-pygobject2/gio-types.patch

See:
https://bugzilla.gnome.org/show_bug.cgi?id=668522

fix some spurious flag warnings with gtk

---

mingw-w64-odt2txt/0001-Compile-for-Msys2.patch
mingw-w64-odt2txt/PKGBUILD

Add odt2txt to use it on git-for-windows
@dscho suggest this is better place for https://github.com/Alexpux/MSYS2-packages/pull/964

odt2txt: Convert openDocuments to txt

---

mingw-w64-libidn2/PKGBUILD

Added libidn 2.0.3 for mingw32 and mingw64

Added package libidn2

---

mingw-w64-qbs/PKGBUILD

qbs: update to 1.8.1

---

mingw-w64-openal/0001-versioned-w32-dll.mingw.patch
mingw-w64-openal/PKGBUILD

refresh patch (and checked that the resulting file tree/dll names are the same)

openal: Update to 1.18.1

---

mingw-w64-libxslt/PKGBUILD
mingw-w64-vala/PKGBUILD

Already had this open as #2711 which doesn't allow me to reopen. Still not sure what's the problem, maybe it solved itself in the meantime.

vala: Update to 0.36.4 [broken]

---

mingw-w64-ngraph-gtk/PKGBUILD

new upstream version 6.07.04 is released.

 ngraph-gtk: Update to 6.07.04

---

mingw-w64-ffmpeg/PKGBUILD
mingw-w64-ffmpeg/ffmpeg-libopenjpeg22.patch

ffmpeg: Support libopenjpeg2.2

---

mingw-w64-lensfun/PKGBUILD
mingw-w64-lensfun/lensfun-update-data.patch

lensfun 0.3.2: Fix absolut path problem in lensfun-update-data

---

mingw-w64-libraqm/PKGBUILD

also fix license installation path

libraqm: Update to 0.3.0

---

mingw-w64-python2/2700-cygpty-isatty-disable-readline.patch
mingw-w64-python2/PKGBUILD
mingw-w64-python3/1700-cygpty-isatty-disable-readline.patch
mingw-w64-python3/PKGBUILD

Fix potential buffer overflow.

python2,3: Update iscygpty

---

mingw-w64-ag/0002-win32-Detect-Cygwin-MSYS-PTY.patch
mingw-w64-ag/0004-lang-Add-autotools-ac-am-in-m4-pc.patch
mingw-w64-ag/PKGBUILD

* Fix conflicts.
* Update iscygpty.
Fix potential buffer overflow.

ag: Update to 2.1.0

---

mingw-w64-astyle/PKGBUILD
mingw-w64-astyle/mingw-w64-fix-install.patch

astyle: Update to 3.0.1

---

mingw-w64-rhash/001-mingw.patch
mingw-w64-rhash/PKGBUILD

rhash: Update to 1.3.5

---

FAIL_LIST.md
README.md

I only removed packages from the FAIL_LIST.md; when, I found them using pacman -Ss.
Once, I get my 64 bit Windows 7 Laptop running; I plan to test the remaining packages in FAIL_LIST.md.
I also fixed broken link in README.md.
Tim S.

Updated FAIL_LIST.md and README.md

---

mingw-w64-kauth-qt5/PKGBUILD
mingw-w64-kcompletion-qt5/PKGBUILD
mingw-w64-kconfigwidgets-qt5/PKGBUILD
mingw-w64-kiconthemes-qt5/PKGBUILD
mingw-w64-kservice-qt5/PKGBUILD
mingw-w64-ktextwidgets-qt5/PKGBUILD
mingw-w64-sonnet-qt5/PKGBUILD

- sonnet (T1 - supports aspell and hunspell)
- kcompletion (T2)
- kauth (T2 - uses dummy backend on Windows)
- kconfigwidgets (T3)
- kiconthemes (T3)
- kservice (T3)
- ktextwidgets (T3)

Add more KF5 libraries:

---

mingw-w64-kactivities-qt5/PKGBUILD
mingw-w64-kfilemetadata-qt5/PKGBUILD
mingw-w64-kjobwidgets-qt5/PKGBUILD
mingw-w64-kpackage-qt5/PKGBUILD
mingw-w64-kunitconversion-qt5/PKGBUILD
mingw-w64-kxmlgui-qt5/PKGBUILD

* kactivities (T2)
* kfilemetadata (T2, no epub/catdoc support)
* kjobwidgets (T2)
* kpackage (T2)
* kunitconversion (T2)
* kxmlgui (T3)

Add more KF5 libraries

---

mingw-w64-gexiv2/PKGBUILD
mingw-w64-gtk-doc/0001-Always-open-files-in-text-mode-and-always-use-utf-8.patch
mingw-w64-gtk-doc/PKGBUILD
mingw-w64-gtk-doc/win-fixes.patch

I'll try to upstream the first patch next.
edit: https://bugzilla.gnome.org/show_bug.cgi?id=787862

gexiv2: Switch to mingw gtk-doc + some more gtk-doc fixes

---

mingw-w64-gnuplot/01-gnuplot.patch
mingw-w64-gnuplot/PKGBUILD

This is a first version of the package using the mingw make file included in the package but this makefile has some limitations. Will look whether the default makefile can produce a better result

New package: gnuplot

---

mingw-w64-crt-git/PKGBUILD

fix patch checksum for crt-git

---

mingw-w64-fontconfig/PKGBUILD

and switch back to out-of-tree builds as that seems to work again.

fontconfig: Update to 2.12.5

---

mingw-w64-libsoup/PKGBUILD

fix https://github.com/Alexpux/MINGW-packages/issues/2949

fix build of libsoup

---

mingw-w64-clang/PKGBUILD

Signed-off-by: Mateusz Mikula <mati865@gmail.com>
https://github.com/Alexpux/MINGW-packages/issues/2928

clang: don't link polly into LLVM tools

---

mingw-w64-cego/PKGBUILD
mingw-w64-lfcbase/PKGBUILD
mingw-w64-lfcxml/PKGBUILD

added build for shared libraries also for lfcbase and lfcxml

cego : update to version 2.35.11

---

mingw-w64-qt5-git/PKGBUILD

qt5-git: Changed pkgbase to match folder name.
And, added provides "${MINGW_PACKAGE_PREFIX}-qt5-base${_namesuff}".
qt5-git: Changed location of git folder.
Tim S.

qt5-git: Changed pkgbase to match folder name.

---

mingw-w64-miniupnpc/001-link-libraries.patch
mingw-w64-miniupnpc/PKGBUILD

latest release snapshot which fixes some security related bugs

miniupnpc: Update to 2.0.20170509

---

mingw-w64-plplot/PKGBUILD

Had to define PLD_png and etc to ON to get libGD to be searched.
Tim S.

plplot: Added more gdlib defines.

---

mingw-w64-gphoto2/PKGBUILD
mingw-w64-libgphoto2/PKGBUILD

libgphoto2: Update to 2.5.15

---

mingw-w64-libbotan/PKGBUILD
mingw-w64-libbotan/python-destdir.patch
mingw-w64-libbotan/python3-install.patch
mingw-w64-libbotan/winsock-link.patch

Fixes `CVE-2017-14737` https://botan.randombit.net/news.html

libbotan: Updated to 2.3.0

---

mingw-w64-curl/PKGBUILD

via native Windows wldap32 library

curl: enable ldap and ldaps protocols

---

mingw-w64-SDL2_mixer/PKGBUILD
mingw-w64-SDL2_mixer/SDL2_mixer-2.0.1-find_lib.mingw.patch
mingw-w64-SDL2_mixer/SDL2_mixer-2.0.1-libtool_windres.mingw.patch

Sdl2_mixer: update to 2.0.2

---

mingw-w64-SDL2_image/PKGBUILD

SDL2_image: update to 2.0.2

---

mingw-w64-zimg/PKGBUILD

I'm submitting this package because it is a dependency of FFmpeg on a lot of Linux systems.

Add zimg package (version 2.6.1)

---

mingw-w64-xavs/0001-xavs-0.1.55-fix-dynamic-build.patch
mingw-w64-xavs/0002-xavs-0.1.55-fix-asm.patch
mingw-w64-xavs/PKGBUILD

This adds xavs, the free avs (Chinese Audio Video Standard) encoder.

Add xavs package (version 0.1.55)

---

mingw-w64-xlnt/PKGBUILD

xlnt: update to 1.2.0

---

mingw-w64-libsoxr/0001-libsoxr-fix-pc-file-installation.patch
mingw-w64-libsoxr/0002-libsoxr-fix-documentation-installation.patch
mingw-w64-libsoxr/PKGBUILD

This adds libsoxr, a audio resampling library.

Add libsoxr package (version 0.1.2)

---

mingw-w64-gnutls/PKGBUILD

Update GnuTLS to latest version

Update GnuTLS to version 3.6.1

---

mingw-w64-kvazaar/0001-kvazaar-1.1.0-gcc7-fix.patch
mingw-w64-kvazaar/PKGBUILD

This adds the kvazaar HEVC encoder.

Add kvazaar package (version 1.1.0)

---

mingw-w64-python-scandir/PKGBUILD
mingw-w64-vulkan/PKGBUILD

Just some stuff I noticed while reading through `git log`, hopefully it's self-explanatory.
This is my first PR, please tell me if I missed anything.

python-scandir, vulkan: Fix typos

---

mingw-w64-openssl/PKGBUILD

Upgrade OpenSSL to v1.0.2m

---

mingw-w64-fastjar/PKGBUILD

This adds the fastjar package.

Add fastjar package (version 0.98)

---

mingw-w64-seexpr/0001-seexpr-2.11-fix-cxxflags.patch
mingw-w64-seexpr/0002-seexpr-2.11-fix-inline-error.patch
mingw-w64-seexpr/0003-seexpr-2.11-fix-dll-installation.patch
mingw-w64-seexpr/PKGBUILD

This adds Walt Disney's SeExpr.

Add seexpr package (version 2.11)

---

mingw-w64-ngraph-gtk/PKGBUILD

the new version 6.07.05 is released.

new upstream release: mingw-w64-ngraph-gtk.

---

mingw-w64-lasem/PKGBUILD
mingw-w64-mtex2MML/PKGBUILD
mingw-w64-mtex2MML/mtex2MML.patch

This is my first time creating a MINGW package.  Everything builds and works.

added mtex2MML

---

mingw-w64-cmark/PKGBUILD

This adds the cmark package (version 0.28.3).

add cmark package (version 0.28.3)

---

mingw-w64-alembic/0001-alembic-1.7.3-fix-windows-build.patch
mingw-w64-alembic/0002-alembic-1.7.3-remove-msc_ver-and-fix-builtins-and-includes.patch
mingw-w64-alembic/PKGBUILD

This adds the alembic package (version 1.7.3).

add alembic package (version 1.7.3)

---

mingw-w64-ptex/0001-ptex-2.1.28-remove-msc_ver.patch
mingw-w64-ptex/0002-ptex-2.1.28-install-dll-correctly.patch
mingw-w64-ptex/PKGBUILD

This adds ptex, an open source texture mapping library by Walt Disney Animation Studios.

add ptex (version 2.1.28)

---

mingw-w64-4th/PKGBUILD

This adds 4th, a Forth compiler.

add 4th package (version 3.62.5)

---

mingw-w64-python-pywavelets/PKGBUILD

This adds python-pywavelets (version 0.5.2).

add python-pywavelets (version 0.5.2)

---

mingw-w64-libsigsegv/0001-libsigsegv-2.11-fix-assembly.patch
mingw-w64-libsigsegv/PKGBUILD

This adds libsigsegv (version 2.11).

add libsigsegv package (version 2.11)

---

mingw-w64-antlr4-runtime-cpp/PKGBUILD

ANTLR version 4.7.1 was released on 2017-12-09

Update C++ runtime of ANTLR4 to version 4.7.1

---

mingw-w64-libao/PKGBUILD

add libao package (version 1.2.2)

---

mingw-w64-libcue/PKGBUILD

add libcue package (version 2.2.0)

---

mingw-w64-unixodbc/0001-unixodbc-2.3.4-int.patch
mingw-w64-unixodbc/PKGBUILD

add unixodbc package (version 2.3.4)

---

mingw-w64-darktable/01-darktable-fix-empty-set.patch
mingw-w64-darktable/PKGBUILD

Only builds for x64, 32-bit version won't compile and not supported.

New package: darktable

---

mingw-w64-mono/PKGBUILD
mingw-w64-mono/bootstrap/PKGBUILD

mono: fix commands in bin script files

---

mingw-w64-python-attrs/PKGBUILD
mingw-w64-python-py/PKGBUILD
mingw-w64-python-pytest/PKGBUILD

Update py, pluggy and add new dependencies
Add newly required python-attrs package

python-pytest: Update to 3.3.1 and update dependencies

---

mingw-w64-cmake/0001-Windows-Add-missing-stringapiset.h-include.patch
mingw-w64-cmake/0003-Disable-response-files-for-MSYS-Generator.patch
mingw-w64-cmake/0004-Implement-Qt5-static-plugin-support.patch
mingw-w64-cmake/0005-Do-not-install-Qt-bundle-in-cmake-gui.patch
mingw-w64-cmake/0006-pkg-config-Add-dont-define-prefix-when-PKG_CONFIG_WI.patch
mingw-w64-cmake/0007-Do-not-generate-import-libs-for-exes.patch
mingw-w64-cmake/0008-Output-line-numbers-in-callstacks.patch
mingw-w64-cmake/PKGBUILD

This pull request upgrades to CMake 3.10.1, and rebases the existing patches against it.

CMake 3.10.1

---

mingw-w64-libidl2/0001-libidl2-0.8.14-remove-def-file.patch
mingw-w64-libidl2/PKGBUILD

This adds libidl2 (version 0.8.14).

add libidl2 (version 0.8.14)

---

mingw-w64-optipng/PKGBUILD

This updates optipng to 0.7.7.

optipng: update to 0.7.7

---

mingw-w64-ruby-dbus/PKGBUILD

This adds ruby-dbus (version 0.14.1).

add ruby-dbus (version 0.14.1)

---

mingw-w64-ruby-pkg-config/PKGBUILD

This adds ruby-pkg-config (version 1.2.8).

add ruby-pkg-config (version 1.2.8)

---

mingw-w64-ruby-native-package-installer/PKGBUILD

This adds ruby-native-package-installer (version 1.0.6).

add ruby-native-package-installer (version 1.0.6)

---

mingw-w64-pyrex/PKGBUILD

This adds pyrex (version 0.9.9).

add pyrex (version 0.9.9)

---

mingw-w64-fdk-aac/PKGBUILD

This updates fdk-aac to 0.1.5.

fdk-aac: update to 0.1.5

---

mingw-w64-shine/0001-shine-3.1.1-fix-include.patch
mingw-w64-shine/PKGBUILD

This adds shine (version 3.1.1).

add shine (version 3.1.1)

---

mingw-w64-libilbc/PKGBUILD

This adds libilbc (version 2.0.2).

add libilbc (version 2.0.2)

---

mingw-w64-libfilezilla/PKGBUILD

add libfilezilla (version 0.11.1)

---

mingw-w64-gdal/PKGBUILD

see https://github.com/Alexpux/MINGW-packages/issues/3169

gdal: make postgresql dependency non optional

---

mingw-w64-zimg/PKGBUILD

This updates zimg to the latest version, 2.7.

zimg: update to 2.7

---

mingw-w64-ruby-cairo/PKGBUILD

This adds ruby-cairo (version 1.15.11).

add ruby-cairo (version 1.15.11)

---

mingw-w64-qpdf/0001-fix-printf-on-mingw-w64.patch
mingw-w64-qpdf/PKGBUILD
mingw-w64-qpdf/PKGBUILD.orig

I have added a package for [QPDF](http://qpdf.sourceforge.net/) a command-line program that does structural, content-preserving transformations on PDF files. An extremely useful program for manipulating PDFs.

add qpdf 7.0.0

---

mingw-w64-vo-amrwbenc/PKGBUILD

This adds vo-amrwbenc (version 0.1.3).

add vo-amrwbenc (version 0.1.3)

---

mingw-w64-libsoup/PKGBUILD

libsoup: Update to 2.60.3

---

mingw-w64-libsigsegv/PKGBUILD

This updates libsigsegv to latest version 2.12.

libsigsegv: update to 2.12

---

mingw-w64-pdf2djvu/PKGBUILD

Adds [pdf2djvu](https://jwilk.net/software/pdf2djvu) a great tool to convert PDF to DjVu.

add pdf2djvu 0.9.8

---

mingw-w64-geany-plugins/001-no-undefined.patch
mingw-w64-geany-plugins/PKGBUILD
mingw-w64-geany/PKGBUILD

Debian has switched to gtk+3, let's try the same :)
Seems to work fine here.

geany/geany-plugins: Update to 1.32; switch to GTK+3

---

mingw-w64-gobject-introspection/0024-Support-passing-arguments-to-g-ir-scanner-through-a-.all.patch
mingw-w64-gobject-introspection/PKGBUILD
mingw-w64-gobject-introspection/py3-fixes.patch

I've tested building gtk3, gstreamer and pygobject with it.

gobject-introspection: Move to Python 3

---

mingw-w64-darktable/PKGBUILD

This is an attempt to fix #3314

darktable: adding BINARY_PACKAGE_BUILD

---

mingw-w64-binutils/0200-remove-provide-qualifiers.patch
mingw-w64-binutils/PKGBUILD

See https://sourceware.org/bugzilla/show_bug.cgi?id=22762.
Fixes #3330 .

binutils - add upstream patch for bug in version 2.30

---

appveyor.yml

See https://github.com/Alexpux/MSYS2-packages/issues/1141

appveyor: default to yes for all system update related pacman questions

---

mingw-w64-zimg/PKGBUILD

This updates zimg to the latest version, 2.7.4.

zimg: update to 2.7.4

---

mingw-w64-libraqm/PKGBUILD
mingw-w64-python-pillow/002-shared-openjpeg.patch
mingw-w64-python-pillow/PKGBUILD
mingw-w64-python-pillow/dlopen-fix.patch

libraqm - 0.4.0 Update to latest version

Pillow - 5.0.0 - update to latest version.  Demote libraqm to optdepends

---

mingw-w64-libtimidity/PKGBUILD

This adds libtimidity-0.2.5 as a mingw-package.

add libtimidity package

---

mingw-w64-verilator/PKGBUILD

Verilator 3.920

---

mingw-w64-python-colorspacious/PKGBUILD

Simple to use module for doing color conversions in CIECAM, XYZ, sRGB, etc

add colorspacious python module

---

mingw-w64-flif/PKGBUILD
mingw-w64-flif/fix-win32-build.patch
mingw-w64-libraqm/PKGBUILD

mingw-w64-libraqm - 0.5 - Update to new version

mingw-w64-flif - 0.3 - New package.

---

mingw-w64-lua-lgi/PKGBUILD

update lgi to 0.9.2

---

mingw-w64-scummvm/0001-mingw-w64-compilation-fix.patch
mingw-w64-scummvm/PKGBUILD

After learning how to make PKGBUILDS, I thought it might be funny if there's a mingw-package of ScummVM (https://www.scummvm.org).
So here we go.

New package: scummvm-2.0.0

---

mingw-w64-vrpn/0001-msys2-fix-jsoncpp-related-link-failure.patch
mingw-w64-vrpn/PKGBUILD

The Virtual-Reality Peripheral Network
See https://github.com/vrpn/vrpn/issues/201

vrpn: New package

---

mingw-w64-libosmscout/PKGBUILD

Great lib for offline rendering and routing using the openstreetmap data. It has various render backends for qt, opengl and android/ios. 
Even though its been around for some years and they even got a GSOC student last year its known to less people then it deserves. Having it available on msys2 would help it alot getting more attention and visibility by easing the installation hurdles.
See: 
-https://github.com/Framstag/libosmscout/
-https://wiki.openstreetmap.org/wiki/Libosmscout
-http://libosmscout.sourceforge.net/examples/screenshots/

new package: libosmscout 1.0.1

---

mingw-w64-brotli/PKGBUILD
mingw-w64-curl/0001-Make-cURL-relocatable.patch
mingw-w64-curl/PKGBUILD
mingw-w64-nghttp2/PKGBUILD

nubgw-w64-curl - 7.59.0, update to latest versionm, add brotli as dependency, rekey patch
mingw-w64-nghttp2 - 1.31.0 - Update to latest version

mingw-w64-brotli - 1.0.3 - New package

---

mingw-w64-pango/0001-build-move-usp10-before-gdi32.patch
mingw-w64-pango/PKGBUILD

pango: fix win7/mingw64 build. See #3122

---

mingw-w64-libfilezilla/PKGBUILD

This updates libfilezilla to 0.12.1.

libfilezilla: update to 0.12.1

---

mingw-w64-meson/0001-gtk-doc-Use-LD_LIBRARY_PATH-to-modify-PATH-on-W32.patch
mingw-w64-meson/PKGBUILD

Also adds https://github.com/mesonbuild/meson/issues/3307

meson: Update to 0.45.1 and add patch for gtk-doc fix

---

mingw-w64-libzip/PKGBUILD

This adds static libraries to libzip. Fixes #3561.

libzip: add static libs

---

mingw-w64-ruby-pkg-config/PKGBUILD

This updates ruby-pkg-config to 1.3.0.

ruby-pkg-config: update to 1.3.0.

---

mingw-w64-ruby-cairo/PKGBUILD

This updates ruby-cairo to 1.15.12.

ruby-cairo: update to 1.15.12

---

mingw-w64-gdb-git/0007-Make-GDB-compile-on-MinGW-targets-again.patch
mingw-w64-gdb-git/PKGBUILD

gdb-git: Add patch for upstream changes.

---

mingw-w64-gsfont/PKGBUILD
mingw-w64-imagemagick/002-7.0.4.1-build-fixes.patch
mingw-w64-imagemagick/PKGBUILD

imagemagick - 7.0.7.28 -  depend upon flif, gsofts, and tdjavu
gsfonts - new package for imagemagick, Ghostscript, and possibly some other stuff

imagemagick and gsfonts

---

mingw-w64-c-ares/0002-Add-static-pkg-config.patch
mingw-w64-c-ares/PKGBUILD

This updates c-ares to 1.14.0.

c-ares: update to 1.14.0

---

mingw-w64-jansson/PKGBUILD

jansson: update to 2.11

---

mingw-w64-osl/0001-osl-0.9.2-fix-shared-libs.patch
mingw-w64-osl/PKGBUILD

This adds osl (version 0.9.2).

add osl (version 0.9.2)

---

mingw-w64-irrlicht/PKGBUILD

This updates irrlicht to 1.8.4.

irrlicht: update to 1.8.4

---

mingw-w64-libunistring/PKGBUILD

This updates libunistring to 0.9.9.

libunistring: update to 0.9.9

---

mingw-w64-python-setuptools/PKGBUILD

This updates python-setuptools to 39.1.0.

python-setuptools: update to 39.1.0

---

mingw-w64-json-c/PKGBUILD

This updates json-c to 0.13.1_20180305.

json-c: update to 0.13.1_20180305

---

mingw-w64-libbsdf/PKGBUILD

This updates libbsdf to 0.9.7.

libbsdf: update to 0.9.7.

---

mingw-w64-lcms2/PKGBUILD

lcms2: update to 2.9

---

mingw-w64-glpk/PKGBUILD
mingw-w64-glpk/fix-platform-check.patch
mingw-w64-glpk/timeval-64bit.patch

glpk: update to 4.65

---

mingw-w64-fltk/PKGBUILD

fltk: update to 1.3.4.2

---

mingw-w64-apr/PKGBUILD

apr: update to 1.6.3.

---

mingw-w64-astyle/PKGBUILD

astyle: update to 3.1

---

mingw-w64-xz/PKGBUILD

xz: update to 5.2.4.

---

mingw-w64-glm/0001-glm-0.9.8.5-fix-platform-error.patch
mingw-w64-glm/PKGBUILD

glm: update to 0.9.8.5

---

mingw-w64-libuv/PKGBUILD

libuv: update to 1.20.2

---

mingw-w64-libdvdnav/PKGBUILD
mingw-w64-libdvdread/0001-no-undefined-on.all.patch
mingw-w64-libdvdread/PKGBUILD

Dvdnav libdvdread and libdvdnav - 6.0.0

---

mingw-w64-brotli/PKGBUILD

brotli: update to 1.0.4

---

mingw-w64-apr-util/PKGBUILD
mingw-w64-apr-util/fix-dll-build.patch

This updates apr-util to 1.6.1.

apr-util: update to 1.6.1

---

mingw-w64-python-beaker/PKGBUILD

This updates python-beaker to 1.9.1.

python-beaker: update to 1.9.1

---

mingw-w64-python-wheel/PKGBUILD

This updates python-wheel to 0.31.0.

python-wheel: update to 0.31.0

---

mingw-w64-python-json-rpc/PKGBUILD

add python-json-rpc (version 1.11.0)

---

mingw-w64-libgit2/PKGBUILD

This updates libgit2 to 0.27.0.

libgit2: update to 0.27.0

---

mingw-w64-cython/PKGBUILD

This updates cython to 0.28.2.

cython: update to 0.28.2

---

mingw-w64-gdbm/PKGBUILD
mingw-w64-gdbm/gdbm-1.10-zeroheaders.patch
mingw-w64-gdbm/gdbm-win32-support.patch

gdbm: update to 1.14.1

---

mingw-w64-python-ply/LICENSE
mingw-w64-python-ply/PKGBUILD

This adds python-ply (version 3.11).

add python-ply (version 3.11)

---

mingw-w64-libfilezilla/PKGBUILD

This updates libfilezilla to 0.12.2.

libfilezilla: update to 0.12.2

---

mingw-w64-libsass/PKGBUILD

This updates libsass to 3.5.4.

libsass: update to 3.5.4

---

mingw-w64-lapack/PKGBUILD

lapack: update to 3.8.0

---

mingw-w64-libuv/PKGBUILD

libuv: update to 1.20.3

---

mingw-w64-jsoncpp/PKGBUILD

This updates jsoncpp to 1.8.4 and ports it to meson.

jsoncpp-1.8.4

---

mingw-w64-python-attrs/PKGBUILD

This updates python-attrs to 18.1.0.

python-attrs: update to 18.1.0

---

mingw-w64-python-pystemmer/PKGBUILD

This adds python-pystemmer (version 1.3.0).

add python-pystemmer (version 1.3.0)

---

mingw-w64-python-pytz/PKGBUILD

This updates python-pytz to 2018.4.

python-pytz: update to 2018.4

---

mingw-w64-python-crcmod/PKGBUILD

This adds python-crcmod (version 1.7).

add python-crcmod (version 1.7)

---

mingw-w64-lmdb/PKGBUILD

lmdb: update to 0.9.22

---

mingw-w64-python-cx_Freeze/PKGBUILD

Fix https://github.com/anthony-tuininga/cx_Freeze/issues/324

Update cx_Freeze to 5.1.1

---

mingw-w64-libconfig/PKGBUILD

This updates libconfig to 1.7.2.

libconfig: update to 1.7.2

---

mingw-w64-python-pbr/PKGBUILD

This updates python-pbr to 4.0.3.

python-pbr: update to 4.0.3

---

mingw-w64-python-jinja/PKGBUILD

This updates python-jinja to 2.10.

python-jinja: update to 2.10

---

mingw-w64-gst-editing-services/PKGBUILD
mingw-w64-gst-libav/PKGBUILD
mingw-w64-gst-plugins-bad/PKGBUILD
mingw-w64-gst-plugins-base/PKGBUILD
mingw-w64-gst-plugins-good/PKGBUILD
mingw-w64-gst-plugins-ugly/PKGBUILD
mingw-w64-gstreamer/PKGBUILD

see https://github.com/Alexpux/MINGW-packages/issues/3705

gstreamer: specify package origin when building

---

mingw-w64-python-py/PKGBUILD

This updates python-py to 1.5.3.

python-py: update to 1.5.3

---

mingw-w64-python-genty/PKGBUILD

This adds python-genty (version 1.3.2).

add python-genty (version 1.3.2)

---

mingw-w64-python-mistune/PKGBUILD

This updates python-mistune to 0.8.3.

python-mistune: update to 0.8.3

---

mingw-w64-python-imagesize/PKGBUILD

This updates python-imagesize to 1.0.0.

python-imagesize: update to 1.0.0

---

mingw-w64-python-wrapt/PKGBUILD

This adds python-wrapt (version 1.10.11).

add python-wrapt (version 1.10.11)

---

mingw-w64-python-tornado/PKGBUILD

Please note I used here 4.5.3, as tornado 5.0.0 is not working properly yet. See [here](https://github.com/jupyter/notebook/issues/3397) more

New package: python-tornado

---

mingw-w64-python-progress/PKGBUILD

This adds python-progress (version 1.3).

add python-progress (version 1.3)

---

mingw-w64-python-more-itertools/PKGBUILD

This adds python-more-itertools (version 4.1.0).

add python-more-itertools (version 4.1.0)

---

mingw-w64-libnova/PKGBUILD
mingw-w64-libnova/libnova-remove-conflicting-definition.patch

This adds libnova (version 0.15.0).

add libnova (version 0.15.0)

---

mingw-w64-freealut/PKGBUILD

This adds freealut (version 1.1.0).

add freealut (version 1.1.0)

---

mingw-w64-libfreexl/PKGBUILD

This updates libfreexl to 1.0.5.

libfreexl: update to 1.0.5

---

mingw-w64-libidn2/PKGBUILD

This updates libidn2 to 2.0.5.

libidn2: update to 2.0.5

---

mingw-w64-python-prettytable/0001-Fix-column-spacing-with-xterm-reset-escape-sequence.patch
mingw-w64-python-prettytable/PKGBUILD

This adds python-prettytable (version 0.7.2).

add python-prettytable (version 0.7.2)

---

mingw-w64-icoutils/PKGBUILD

This updates icoutils to 0.32.3.

icoutils: update to 0.32.3

---

mingw-w64-libdiscid/PKGBUILD
mingw-w64-libdiscid/libdiscid-0.6.2-include-location.patch

This adds libdiscid (version 0.6.2).

add libdiscid (version 0.6.2)

---

mingw-w64-python-setuptools/PKGBUILD

This updates python-setuptools to 39.2.0.

python-setuptools: update to 39.2.0

---

mingw-w64-python-greenlet/PKGBUILD

This adds python-greenlet (version 0.4.13).

add python-greenlet (version 0.4.13)

---

mingw-w64-lapack/PKGBUILD

This enables cblas and lapacke for lapack.

lapack: enable cblas and lapacke

---

mingw-w64-nodejs/PKGBUILD

This important file was missing form the package somehow

nodejs: Add missing npm.cmd to the package

---

mingw-w64-glibmm/PKGBUILD

This updates glibmm to 2.56.0.

glibmm: update to 2.56.0

---

mingw-w64-bcunit/PKGBUILD

This adds bcunit (version 3.0.2).

add bcunit (version 3.0.2)

---

mingw-w64-git-lfs/PKGBUILD

This updates git-lfs to 2.4.1.

git-lfs: update to 2.4.1

---

mingw-w64-cairomm/PKGBUILD

This updates cairomm to 1.12.2.

cairomm: update to 1.12.2

---

mingw-w64-gdb/PKGBUILD

gdb: update to 8.1

---

mingw-w64-geos/PKGBUILD
mingw-w64-geos/geos-3.5.0.patch

geos: update to 3.6.2.

---

mingw-w64-laszip/PKGBUILD

laszip: update to 3.2.2.

---

mingw-w64-git-repo/PKGBUILD

This updates git-repo to 0.4.20.

git-repo: update to 0.4.20

---

mingw-w64-libvoikko/PKGBUILD

This adds libvoikko (version 4.1.1).

add libvoikko (version 4.1.1)

---

mingw-w64-python-pyasn1-modules/PKGBUILD
mingw-w64-python-pyasn1/PKGBUILD

python-pyasn1: Update to 0.4.2
python-pyasn1-modules: Update to 0.2.1

python-pyasn: Multiple updates

---

mingw-w64-live-media/PKGBUILD

This updates live-media to 2018.04.25.

live-media: update to 2018.04.25.

---

mingw-w64-globjects/PKGBUILD

This updates globjects to 1.1.0.

globjects: update to 1.1.0.

---

mingw-w64-gl2ps/PKGBUILD

gl2ps: update to 1.4.0

---

mingw-w64-python-kiwisolver/PKGBUILD

New package: python-kiwisolver (Version: 1.0.1)

---

mingw-w64-tor/PKGBUILD

tor: update to 0.3.3.6

---

mingw-w64-python-matplotlib/PKGBUILD
mingw-w64-python-matplotlib/setupext.py.patch

python-matplotlib: Update to 2.2.2

---

mingw-w64-python-asn1crypto/PKGBUILD

This updates python-asn1crypto to 0.24.0.

python-asn1crypto: update to 0.24.0.

---

mingw-w64-fftw/PKGBUILD

fftw: update to 3.3.8

---

mingw-w64-postgis/PKGBUILD
mingw-w64-postgis/pg_config

This adds the postgis package (version 2.4.4).

add postgis (version 2.4.4).

---

mingw-w64-x265/PKGBUILD

x265: update to 2.8.

---

mingw-w64-gnutls/PKGBUILD

gnutls: update to 3.6.2.

---

mingw-w64-bwidget/PKGBUILD

This updates bwidget to 1.9.12.

bwidget: update to 1.9.12

---

mingw-w64-python-tox/PKGBUILD

This adds python-tox (version 3.0.0).

add python-tox (version 3.0.0)

---

mingw-w64-p11-kit/PKGBUILD

This updates p11-kit to 0.23.12.

p11-kit: update to 0.23.12.

---

mingw-w64-faad2/PKGBUILD
mingw-w64-faad2/fix-mingw-build.patch

faad2: update to 2.8.8

---

mingw-w64-python-flaky/PKGBUILD

This adds python-flaky (version 3.4.0).

add python-flaky (version 3.4.0)

---

mingw-w64-python-lazy-object-proxy/PKGBUILD

This adds python-lazy-object-proxy (version 1.3.1).

add python-lazy-object-proxy (version 1.3.1)

---

mingw-w64-fcrackzip/PKGBUILD

This adds fcrackzip (version 1.0).

add fcrackzip (version 1.0).

---

mingw-w64-jpegoptim/PKGBUILD

This updates jpegoptim to 1.4.6.

jpegoptim: update to 1.4.6

---

mingw-w64-python-pbr/PKGBUILD

This updates python-pbr to 4.0.4.

python-pbr: update to 4.0.4

---

mingw-w64-boost/PKGBUILD
mingw-w64-boost/boost-1.50.0-fix-non-utf8-files.patch
mingw-w64-boost/boost-1.66.0-fix-qualifier.patch

boost: update to 1.67.0

---

mingw-w64-libxml++/PKGBUILD
mingw-w64-libxml++2.6/PKGBUILD

Also libxml++2.6: Update to 2.40.1

 libxml++: Update to 3.0.1

---

mingw-w64-aom-git/PKGBUILD
mingw-w64-ffmpeg/PKGBUILD

*building libaom as dll is not yet implemented

add aom package and enable av1 support in ffmpeg

---

mingw-w64-benchmark/PKGBUILD
mingw-w64-benchmark/benchmark-mingw.patch

This is required to build the latest version of grpc.

add benchmark (version 1.4.1)

---

mingw-w64-gsl/PKGBUILD

gsl: update to 2.5

---

mingw-w64-alembic/0001-alembic-1.7.8-fix-windows-build.patch
mingw-w64-alembic/0002-alembic-1.7.8-remove-msc_ver-and-fix-builtins-and-includes.patch
mingw-w64-alembic/PKGBUILD

This updates alembic to 1.7.8.

alembic: update to 1.7.8

---

mingw-w64-graphene/PKGBUILD

graphene: Update to 1.8.2

---

mingw-w64-libpsl/PKGBUILD

This adds libpsl (version 0.20.2).

add libpsl (version 0.20.2)

---

mingw-w64-dbus-c++/PKGBUILD
mingw-w64-dbus-c++/dbus-c++-0.9.0-mingw.patch
mingw-w64-dbus-c++/disable-threading.patch
mingw-w64-dbus-c++/fix-writechar.patch
mingw-w64-dbus-c++/gcc47.patch

This adds dbus-c++ (version 0.9.0).

add dbus-c++ (version 0.9.0)

---

mingw-w64-python-sphinx/PKGBUILD

This updates python-sphinx to 1.7.5.

python-sphinx: update to 1.7.5

---

mingw-w64-diffutils/PKGBUILD

difftools: Fix stat() issue

---

mingw-w64-nss/PKGBUILD

nss: update to 3.38

---

mingw-w64-gcc-git/0019-gcc-8-branch-Backport-patches-for-std-filesystem-from-master.patch
mingw-w64-gcc-git/PKGBUILD

[UNTESTED] gcc-git: Backport std::filesystem from GCC trunk.

---

mingw-w64-libuv/PKGBUILD
mingw-w64-libuv/fix-threads.patch

libuv: update to 1.21.0

---

mingw-w64-sip/0002-sip-fix-build.patch
mingw-w64-sip/PKGBUILD

sip: update to 4.19.9

---

mingw-w64-gcc-git/0019-gcc-8-branch-Backport-patches-for-std-filesystem-from-master.patch
mingw-w64-gcc-git/PKGBUILD

gcc-git: Backport more std::filesystem from master.

---

mingw-w64-quazip/PKGBUILD

quazip: update to 0.7.6

---

mingw-w64-aom/PKGBUILD

aom-git: update and fix build

---

mingw-w64-python-apipkg/PKGBUILD

This adds python-apipkg (version 1.4). It is a dependency of python-py.

add python-apipkg (version 1.4)

---

mingw-w64-python-iniconfig/PKGBUILD

This adds python-iniconfig (version 1.0.0). It is a dependency of
python-py.

add python-iniconfig (version 1.0.0)

---

mingw-w64-python-py/PKGBUILD

This updates python-py to 1.5.4 and adds new dependencies.

python-py: update to 1.5.4

---

mingw-w64-aspell-de/PKGBUILD
mingw-w64-aspell-en/PKGBUILD

aspell-en: Update to 2018.04.16
aspell-de: Update to 20161207

Aspell: multiple updates

---

mingw-w64-gdb/PKGBUILD
mingw-w64-gdb/gdb-py37-build-fix.patch

gdb: py37 build fix

---

mingw-w64-libmicrohttpd/PKGBUILD

Update libmicrohttpd to 0.9.59

Update libmicrohttpd to 0.9.59

---

mingw-w64-curl/PKGBUILD

curl: Fix missing dependency on libpsl

---

mingw-w64-python3-jupyter-notebook/PKGBUILD

python3-jupyter-notebook: Add building instruction

---

mingw-w64-libraw/PKGBUILD

This updates libraw to 0.19.0.

libraw: update to 0.19.0

---

mingw-w64-python-tox/PKGBUILD

This updates python-tox to 3.2.1.

python-tox: update to 3.2.1

---

mingw-w64-python-pluggy/PKGBUILD

This updates python-pluggy to 0.7.1.

python-pluggy: update to 0.7.1

---

mingw-w64-python-apipkg/PKGBUILD

This updates python-apipkg to 1.5.

python-apipkg: update to 1.5

---

mingw-w64-python-sqlalchemy/PKGBUILD

This updates python-sqlalchemy to 1.2.10.

python-sqlalchemy: update to 1.2.10

---

mingw-w64-python-pbr/PKGBUILD

This updates python-pbr to 4.2.0.

python-pbr: update to 4.2.0

---

mingw-w64-python-beautifulsoup4/PKGBUILD

This updates python-beautifulsoup4 to 4.6.3.

python-beautifulsoup4: update to 4.6.3

---

mingw-w64-xapian-core/PKGBUILD

This updates xapian-core to 1.4.7.

xapian-core: update to 1.4.7

---

mingw-w64-libdvdcss/PKGBUILD

This updates libdvdcss to 1.4.2.

libdvdcss: update to 1.4.2

---

mingw-w64-gc/PKGBUILD

gc: update to 7.6.8

---

mingw-w64-python-pip/PKGBUILD

This updates python-pip to 18.0.

python-pip: update to 18.0

---

mingw-w64-libsoup/PKGBUILD

This updates libsoup to 2.62.3.

libsoup: update to 2.62.3

---

mingw-w64-harfbuzz/PKGBUILD

This updates harfbuzz to 1.8.7.

harfbuzz: update to 1.8.7

---

mingw-w64-icu/PKGBUILD

icu: update to 62.1

---

mingw-w64-libgit2/PKGBUILD

This updates libgit2 to 0.27.4.

libgit2: update to 0.27.4

---

mingw-w64-lua/PKGBUILD

lua: update to 5.3.5

---

mingw-w64-openh264/PKGBUILD

This updates openh264 to 1.8.0.

openh264: update to 1.8.0

---

mingw-w64-isl/PKGBUILD

isl: update to 0.20

---

mingw-w64-dlfcn/PKGBUILD

dlfcn: update to 1.1.2

---

mingw-w64-cython/PKGBUILD

This updates cython to 0.28.5.

cython: update to 0.28.5

---

mingw-w64-file/PKGBUILD

file: update to 5.34

---

mingw-w64-npth/PKGBUILD

npth: update to 1.6

---

mingw-w64-libyaml/0001-Proper-mingw-YAML_DECLARE-definition.patch
mingw-w64-libyaml/0002-libyaml-no-undefined.patch
mingw-w64-libyaml/PKGBUILD

This updates libyaml to 0.2.1.

libyaml: update to 0.2.1

---

mingw-w64-vala/PKGBUILD
mingw-w64-vala/no-undefined.patch

vala: update to 0.40.8

---

mingw-w64-lpsolve/CMakeLists.txt
mingw-w64-lpsolve/PKGBUILD
mingw-w64-lpsolve/avoid_undefined_reference.patch
mingw-w64-lpsolve/lpsolveConfig.cmake.in

lpsolve is Mixed Integer Linear Programming (MILP) solver
cmake script was forked from
- https://github.com/PADrend/ThirdParty/blob/master/lpsolve-CMakeLists.txt
- https://github.com/PADrend/ThirdParty/blob/master/lpsolve-lpsolveConfig.cmake.in
ref:
- https://github.com/PADrend/ThirdParty/pull/2
- https://github.com/PADrend/ThirdParty/pull/3

lpsolve: add lpsolve

---

mingw-w64-python-pyasn1/PKGBUILD

This updates python-pyasn1 to 0.4.4.

python-pyasn1: update to 0.4.4

---

mingw-w64-zeromq/PKGBUILD

zeromq: update to 4.2.5

---

mingw-w64-libsoxr/PKGBUILD

This updates libsoxr to 0.1.3.

libsoxr: update to 0.1.3

---

mingw-w64-postgresql/PKGBUILD

This updates postgresql to 10.5.

postgresql: update to 10.5

---

mingw-w64-blosc/0001-blosc-install-dll-to-bin.patch
mingw-w64-blosc/PKGBUILD

This adds blosc (version 1.14.4).

add blosc (version 1.14.4)

---

mingw-w64-harfbuzz/PKGBUILD

This updates harfbuzz to 1.8.8.

harfbuzz: update to 1.8.8

---

mingw-w64-ccache/01-directory-separator.patch
mingw-w64-ccache/PKGBUILD

ccache: update to 3.4.2

---

mingw-w64-babl/PKGBUILD

babl: update to 0.1.56

---

mingw-w64-geos/PKGBUILD

geos: update to 3.6.3

---

mingw-w64-discount/PKGBUILD

This updates discount to 2.2.4.

discount: update to 2.2.4

---

mingw-w64-libimagequant/PKGBUILD

This updates libimagequant to 2.12.1.

libimagequant: update to 2.12.1

---

mingw-w64-python-setuptools/PKGBUILD

This updates python-setuptools to 40.1.0.

python-setuptools: update to 40.1.0

---

mingw-w64-dbus/PKGBUILD

dbus: update to 1.12.10

---

mingw-w64-poppler/PKGBUILD

This updates poppler to 0.67.0.

poppler: update to 0.67.0

---

mingw-w64-python-xlsxwriter/PKGBUILD

This updates python-xlsxwriter to 1.0.7.

python-xlsxwriter: update to 1.0.7

---

mingw-w64-armadillo/PKGBUILD

This updates armadillo to 9.100.5.

armadillo: update to 9.100.5

---

mingw-w64-libfilezilla/PKGBUILD

This updates libfilezilla to 0.13.0.

libfilezilla: update to 0.13.0

---

mingw-w64-opus-tools/PKGBUILD

This updates opus-tools to 0.1.10.

opus-tools: update to 0.1.10

---

mingw-w64-python-hypothesis/PKGBUILD

This updates python-hypothesis to 3.68.1.

python-hypothesis: update to 3.68.1

---

mingw-w64-expat/PKGBUILD

expat: update to 2.2.6

---

mingw-w64-python-hypothesis/PKGBUILD

This updates python-hypothesis to 3.68.2.

python-hypothesis: update to 3.68.2

---

mingw-w64-openssl/PKGBUILD

This updates openssl to 1.0.2.p.

openssl: update to 1.0.2.p

---

mingw-w64-zopfli/7554e4d34e7000b0595aa606e7d72357cf46ba86.patch
mingw-w64-zopfli/PKGBUILD
mingw-w64-zopfli/win32-fixes.patch

I had to include two patches to make this work.

zopfli - 1.0.2 package - attempt to fix.

---

mingw-w64-python-sqlalchemy/PKGBUILD

This updates python-sqlalchemy to 1.2.11.

python-sqlalchemy: update to 1.2.11

---

mingw-w64-ruby-pkg-config/PKGBUILD

This updates ruby-pkg-config to 1.3.1.

ruby-pkg-config: update to 1.3.1

---

mingw-w64-vala/PKGBUILD

vala: update to 0.40.9

---

mingw-w64-confuse/PKGBUILD

This updates confuse to 3.2.2.

confuse: update to 3.2.2

---

mingw-w64-python-packaging/PKGBUILD

This updates python-packaging to 17.1.

python-packaging: update to 17.1

---

mingw-w64-python-setuptools/PKGBUILD

This updates python-setuptools to 40.2.0.

python-setuptools: update to 40.2.0

---

mingw-w64-python-sphinx_rtd_theme/PKGBUILD

This updates python-sphinx_rtd_theme to 0.4.1.

python-sphinx_rtd_theme: update to 0.4.1

---

mingw-w64-python-sphinx/PKGBUILD

This updates python-sphinx to 1.7.7.

python-sphinx: update to 1.7.7

---

mingw-w64-libgsf/PKGBUILD
mingw-w64-libgsf/fix-mingw-build.patch

This updates libgsf to 1.14.44.

libgsf: update to 1.14.44

---

mingw-w64-libdatrie/PKGBUILD
mingw-w64-libthai/PKGBUILD

This adds libdatrie (version 0.2.12) and libthai (version 0.1.28), which depends on libdatrie.

add libdatrie (version 0.2.12) and libthai (version 0.1.28)

---

mingw-w64-libuv/PKGBUILD

libuv: update to 1.23.0

---

mingw-w64-python-numpy/PKGBUILD

This updates python-numpy to 1.15.1.

python-numpy: update to 1.15.1

---

mingw-w64-geany/PKGBUILD

geany: update to 1.33

---

mingw-w64-openvr/PKGBUILD

This updates openvr to 1.0.16.

openvr: update to 1.0.16

---

mingw-w64-PKGBUILD-templates/PKGBUILD.setup-py-python-pkg

Just a minor fix or two.  OOPS!!!

fix a typeo and copy LICENSE to LICENSE (not COPYING)

---

mingw-w64-libnumbertext/PKGBUILD
mingw-w64-libnumbertext/libnumbertext-updateautotools.patch

This adds libnumbertext (version 1.0).

add libnumbertext (version 1.0)

---

mingw-w64-python-dnspython/PKGBUILD
mingw-w64-python-email-validator/PKGBUILD
mingw-w64-python-email-validator/email-validator2-i686.install
mingw-w64-python-email-validator/email-validator2-x86_64.install
mingw-w64-python-email-validator/email-validator3-i686.install
mingw-w64-python-email-validator/email-validator3-x86_64.install
mingw-w64-python-faker/PKGBUILD
mingw-w64-python-faker/faker2-i686.install
mingw-w64-python-faker/faker2-x86_64.install
mingw-w64-python-faker/faker3-i686.install
mingw-w64-python-faker/faker3-x86_64.install
mingw-w64-python-text-unidecode/PKGBUILD

python-text-unidecode 1.2-2 - new package
python-email-validator 1.0.3 - new package
python-ukpostcodeparser 1.1.2 0 new package
python-dnspython 1.15.0 - new package

python-faker 0.9.0 and packages it depends upon for build and testing

---

mingw-w64-double-conversion/PKGBUILD
mingw-w64-double-conversion/fix-cmake-directory.patch

This adds double-conversion (version 3.0.0).

add double-conversion (version 3.0.0)

---

mingw-w64-python-flake8/4fcbcccf381ce0987faa297173e4008b0490918f.patch
mingw-w64-python-flake8/527af5c214ef0eccfde3dd58d7ea15e09c483bd3.patch
mingw-w64-python-flake8/PKGBUILD
mingw-w64-python-flake8/flake8-pycodestyle2.4-compat.patch
mingw-w64-python-flake8/flake8-pycodestyle2.4-new-checks.patch
mingw-w64-python-flake8/flake82-i686.install
mingw-w64-python-flake8/flake82-x86_64.install
mingw-w64-python-flake8/flake83-i686.install
mingw-w64-python-flake8/flake83-x86_64.install
mingw-w64-python-mccabe/PKGBUILD
mingw-w64-python-mccabe/fix-metadata.patch
mingw-w64-python-pycodestyle/PKGBUILD
mingw-w64-python-pycodestyle/pycodestyle2-i686.install
mingw-w64-python-pycodestyle/pycodestyle2-x86_64.install
mingw-w64-python-pycodestyle/pycodestyle3-i686.install
mingw-w64-python-pycodestyle/pycodestyle3-x86_64.install

python-pycodestyle - 2.4.0 - new package
python-mccabe 0.6.1 - new package

python-pyflake8 - 3.5.0 and packages that it depends upon

---

mingw-w64-python-pyzmq/001-mingw-python.patch
mingw-w64-python-pyzmq/PKGBUILD

This updates python-pyzmq to 17.1.2.

python-pyzmq: update to 17.1.2

---

mingw-w64-gnupg/PKGBUILD

gnupg: update to 2.2.10

---

mingw-w64-libssh/PKGBUILD

libssh: update to 0.8.2

---

mingw-w64-python-py/PKGBUILD

This updates python-py to 1.6.0.

python-py: update to 1.6.0

---

mingw-w64-ccache/PKGBUILD

ccache: update to 3.4.3

---

mingw-w64-python-xlsxwriter/PKGBUILD

This updates python-xlsxwriter to 1.1.0.

python-xlsxwriter: update to 1.1.0

---

mingw-w64-libarchive/0001-libarchive-3.3.3-bcrypt-fix.patch
mingw-w64-libarchive/PKGBUILD

This updates libarchive to 3.3.3.

libarchive: update to 3.3.3

---

mingw-w64-python-cvxopt/PKGBUILD

This updates python-cvxopt to 1.2.1.

python-cvxopt: update to 1.2.1

---

mingw-w64-gsettings-desktop-schemas/PKGBUILD

This updates gsettings-desktop-schemas to 3.28.1.

gsettings-desktop-schemas: update to 3.28.1

---

mingw-w64-python-atomicwrites/PKGBUILD

This updates python-atomicwrites to 1.2.1.

python-atomicwrites: update to 1.2.1

---

mingw-w64-python-attrs/PKGBUILD

This updates python-attrs to 18.2.0.

python-attrs: update to 18.2.0

---

mingw-w64-python-greenlet/PKGBUILD

This updates python-greenlet to 0.4.15.

python-greenlet: update to 0.4.15

---

mingw-w64-gtksourceview4/PKGBUILD

This updates gtksourceview4 to 4.0.3.

gtksourceview4: update to 4.0.3

---

mingw-w64-gcc-git/0019-gcc-8-branch-Backport-patches-for-std-filesystem-from-master.patch
mingw-w64-gcc-git/PKGBUILD

gcc-git: Update patch for std::filesystem.

---

mingw-w64-python-icu/PKGBUILD

This updates python-icu to 2.1.

python-icu: update to 2.1

---

mingw-w64-python-hypothesis/PKGBUILD

This updates python-hypothesis to 3.71.3.

python-hypothesis: update to 3.71.3

---

azure-pipelines.yml

This creates a mingw32 and a ming64 job running on Server 2012r2

Add support for Azure Pipelines. See #4396

---

mingw-w64-glm/PKGBUILD

glm: update to 0.9.9.2

---

mingw-w64-double-conversion/PKGBUILD

This updates double-conversion to 3.1.1.

double-conversion: update to 3.1.1

---

mingw-w64-libical/PKGBUILD

This updates libical to 3.0.4.

libical: update to 3.0.4

---

mingw-w64-sqlite3/PKGBUILD

This updates sqlite3 to 3.25.0.

sqlite3: update to 3.25.0

---

mingw-w64-python-setuptools/PKGBUILD

This updates python-setuptools to 40.3.0.

python-setuptools: update to 40.3.0

---

mingw-w64-python-tornado/PKGBUILD

This updates python-tornado to 5.1.1.

python-tornado: update to 5.1.1

---

mingw-w64-proj/PKGBUILD

proj: update to 5.2.0

---

mingw-w64-libfilezilla/PKGBUILD

This updates libfilezilla to 0.13.1.

libfilezilla: update to 0.13.1

---

mingw-w64-libuv/PKGBUILD

libuv: update to 1.23.1

---

mingw-w64-cmocka/PKGBUILD

cmocka: update to 1.1.2

---

mingw-w64-python-xlsxwriter/PKGBUILD

This updates python-xlsxwriter to 1.1.1.

python-xlsxwriter: update to 1.1.1

---

mingw-w64-python-reportlab/PKGBUILD

This updates python-reportlab to 3.5.8.

python-reportlab: update to 3.5.8

---

mingw-w64-python-openpyxl/PKGBUILD

This updates python-openpyxl to 2.5.7.

python-openpyxl: update to 2.5.7

---

mingw-w64-python-fonttools/PKGBUILD

This updates python-fonttools to 3.30.0.

python-fonttools: update to 3.30.0

---

mingw-w64-python-setuptools/PKGBUILD

This updates python-setuptools to 40.4.3.

python-setuptools: update to 40.4.3

---

mingw-w64-python-sqlalchemy/PKGBUILD

This updates python-sqlalchemy to 1.2.12.

python-sqlalchemy: update to 1.2.12

---

mingw-w64-python-sphinx/PKGBUILD

This updates python-sphinx to 1.8.1.

python-sphinx: update to 1.8.1

---

mingw-w64-sqlite3/PKGBUILD

This updates sqlite3 to 3.25.2.

sqlite3: update to 3.25.2

---

mingw-w64-brotli/PKGBUILD

brotli: update to 1.0.6

---

mingw-w64-arpack/PKGBUILD

arpack: update to 3.6.3

---

mingw-w64-apr/PKGBUILD

apr: update to 1.6.5

---

mingw-w64-libshout/01-libshout-tls-compile-with-OpenSSL-1.1.0.patch
mingw-w64-libshout/PKGBUILD

libshout: fix build with openssl 1.1

---

mingw-w64-libopusenc/PKGBUILD

opus-tools: Update to 0.2

---

mingw-w64-python-pywavelets/PKGBUILD

This updates python-pywavelets to 1.0.1.

python-pywavelets: update to 1.0.1

---

mingw-w64-kactivities-qt5/PKGBUILD
mingw-w64-kauth-qt5/PKGBUILD
mingw-w64-kcompletion-qt5/PKGBUILD
mingw-w64-kcrash-qt5/PKGBUILD
mingw-w64-kdoctools-qt5/PKGBUILD
mingw-w64-kdoctools-qt5/use_specified_perl.patch
mingw-w64-kfilemetadata-qt5/PKGBUILD
mingw-w64-kimageformats-qt5/PKGBUILD
mingw-w64-kjobwidgets-qt5/PKGBUILD
mingw-w64-knotifications-qt5/PKGBUILD
mingw-w64-kpackage-qt5/PKGBUILD
mingw-w64-syndication-qt5/PKGBUILD

Includes 2 new frameworks: knotifications and syndication

Update Tier 2 KF5 modules to 5.50

---

mingw-w64-libfilezilla/PKGBUILD

This updates libfilezilla to 0.14.0.

libfilezilla: update to 0.14.0

---

mingw-w64-kbookmarks-qt5/PKGBUILD
mingw-w64-kglobalaccel-qt5/PKGBUILD
mingw-w64-kiconthemes-qt5/PKGBUILD
mingw-w64-kio-qt5/PKGBUILD
mingw-w64-knewstuff-qt5/PKGBUILD
mingw-w64-kparts-qt5/PKGBUILD
mingw-w64-kservice-qt5/PKGBUILD
mingw-w64-ktextwidgets-qt5/PKGBUILD
mingw-w64-kwallet-qt5/PKGBUILD
mingw-w64-kxmlgui-qt5/PKGBUILD

... and add kbookmarks, kio, knewstuff, kparts and kwallet

Update KF5 Tier 3 frameworks

---

mingw-w64-python-rencode/PKGBUILD

Please let me know if this conforms. I used the template for a python module.
I would like to commit more of these. Do I do one big pull request or 1 at a time for review?

add python rencode

---

mingw-w64-PKGBUILD-common/kde-frameworks5
mingw-w64-breeze-icons-qt5/PKGBUILD
mingw-w64-editorconfig-core-c/PKGBUILD
mingw-w64-kdeclarative-qt5/PKGBUILD
mingw-w64-kdeclarative-qt5/enable-epoxy.patch
mingw-w64-kinit-qt5/PKGBUILD
mingw-w64-kirigami2-qt5/PKGBUILD
mingw-w64-ktexteditor-qt5/PKGBUILD
mingw-w64-plasma-framework-qt5/PKGBUILD

* breeze-icons
* kdeclarative
* kinit
* kirigami2
* ktexteditor (+ editorconfig-core-c)
* plasma-framework

Add new KF5 frameworks

---

mingw-w64-kate/PKGBUILD

Add kate and kwrite

---

mingw-w64-python-pyopengl/PKGBUILD

There is a warning in this one of a syntax error in python code but the build succeeds.
Might require a patch.

add python pyopengl

---

mingw-w64-alembic/0001-alembic-1.7.9-fix-windows-build.patch
mingw-w64-alembic/0002-alembic-1.7.9-remove-msc_ver-and-fix-builtins-and-includes.patch
mingw-w64-alembic/PKGBUILD

This updates alembic to 1.7.9.

alembic: update to 1.7.9

---

mingw-w64-cython/PKGBUILD

cython: update to 0.29

---

mingw-w64-python-distlib/PKGBUILD

This updates python-distlib to 0.2.8.

python-distlib: update to 0.2.8

---

mingw-w64-libnumbertext/PKGBUILD

This updates libnumbertext to 1.0.5.

libnumbertext: update to 1.0.5

---

mingw-w64-libgit2/PKGBUILD

This updates libgit to 0.27.5.

libgit: update to 0.27.5

---

mingw-w64-cego/PKGBUILD
mingw-w64-lfcbase/PKGBUILD
mingw-w64-lfcxml/PKGBUILD

lfcbase : Update to version 1.12.3
lfcxml : update to version 1.2.6
cego : update to version 2.42.4

This commit contains several updates :

---

mingw-w64-harfbuzz/PKGBUILD

harfbuzz: Update to 2.0.0

---

mingw-w64-file/PKGBUILD

file: update to 5.35

---

mingw-w64-zstd/PKGBUILD

zstd: update to 1.3.7

---

mingw-w64-go/PKGBUILD

go: Update to 1.11.1 --no patchs required

---

mingw-w64-ccache/PKGBUILD

ccache: update to 3.5

---

mingw-w64-libfilezilla/PKGBUILD

This updates libfilezilla to 0.15.0.

libfilezilla: update to 0.15.0

---

mingw-w64-go/PKGBUILD

So sorry to forget create origin windows build environment.

 go: Update to 1.11.1
