mingw-w64-python-wheel/PKGBUILD

This updates python-wheel to 0.32.2.

python-wheel: update to 0.32.2

---

mingw-w64-libvoikko/PKGBUILD

This updates libvoikko to 4.2.

libvoikko: update to 4.2

---

mingw-w64-zimg/PKGBUILD

zimg: update to 2.8

---

mingw-w64-gtk4/PKGBUILD
mingw-w64-gtk4/gtk4-i686.install
mingw-w64-gtk4/gtk4-x86_64.install

No need to build this, but this makes it easy to test new releases.

gtk4: Add new preview package (v3.94.0)

---

mingw-w64-libgcrypt/PKGBUILD

This updates libgcrypt to 1.8.4.

libgcrypt: update to 1.8.4

---

mingw-w64-python-babel/PKGBUILD

build separately from install
run tests
fix so pip can detect it's presence

python-babel - 2.6.0 - various fixes

---

mingw-w64-atkmm/PKGBUILD

atkmm: update to 2.28.0

---

mingw-w64-python2-astroid/PKGBUILD
mingw-w64-python3-astroid/PKGBUILD

python2-astroid - 1.6.5 - new package
python3-astroid - 2.0.4 - New package

mingw-w64-python-astroid packages - ulimately required for pylint

---

mingw-w64-python2-pylint/PKGBUILD
mingw-w64-python3-pylint/PKGBUILD

python2-pylint - 1.9.2 - new package
python3-pylint - 2.0.4 - new package

python-pylint - separate versions for Python2 and 3

---

mingw-w64-gtk2/0020-GDK-W32-Always-process-all-available-messages.patch
mingw-w64-gtk2/0021-GDK-W32-Ignore-autorepeated-key-presses-on-modifier-.patch
mingw-w64-gtk2/PKGBUILD

gtk2: backport some event handling patches fixing high CPU usage. Fixes #2407

---

mingw-w64-python-setuptools/PKGBUILD
mingw-w64-python-setuptools/setuptools2-i686.install
mingw-w64-python-setuptools/setuptools2-x86_64.install
mingw-w64-python-setuptools/setuptools3-i686.install
mingw-w64-python-setuptools/setuptools3-x86_64.install

Update to new version
fix easy-install script
fix some dependencies that are listed in requirements.txt including certifi and winse

python-setuptools - 40.6.2 -

---

mingw-w64-python-coverage/PKGBUILD

This updates python-coverage to 4.5.2.

python-coverage: update to 4.5.2

---

mingw-w64-libraw/PKGBUILD

This updates libraw to 0.19.1.

libraw: update to 0.19.1

---

mingw-w64-z3/001-mingw-fixes.patch
mingw-w64-z3/PKGBUILD

z3: update to 4.8.3

---

mingw-w64-cego/PKGBUILD
mingw-w64-lfcxml/PKGBUILD

Update lfcxml to version 1.2.9
Update cego to version 2.42.10

lfcxml + cego package update

---

mingw-w64-cython/PKGBUILD

This updates cython to 0.29.1.

cython: update to 0.29.1

---

mingw-w64-laszip/PKGBUILD

laszip: update to 3.2.8

---

mingw-w64-libmfx/PKGBUILD

libmfx: update to 1.25

---

mingw-w64-jansson/PKGBUILD

jansson: update to 2.12

---

mingw-w64-geos/PKGBUILD

geos: update to 3.7.1

---

mingw-w64-fdk-aac/PKGBUILD

This updates fdk-aac to 2.0.0.

fdk-aac: update to 2.0.0

---

mingw-w64-libpng/PKGBUILD

This updates libpng to 1.6.36.

libpng: update to 1.6.36

---

mingw-w64-blosc/PKGBUILD

blosc: update to 1.15.0

---

mingw-w64-vapoursynth/PKGBUILD

This updates vapoursynth to R45.1

vapoursynth: update to R45.1

---

mingw-w64-python-xlrd/PKGBUILD

Library for developers to extract data from Microsoft Excel (tm) spreadsheet files (mingw-w64)

Add mingw-w64-python-xlrd

---

mingw-w64-nim/PKGBUILD
mingw-w64-nimble/PKGBUILD

Nimble has not been updated for a long time and packages are not offered.

nimble: update to 0.9.0

---

mingw-w64-python-colour/PKGBUILD

The fantastic colour science library.  This is an official tarball release instead of git.  Thanks!!

add colour-science.org python library

---

mingw-w64-cppcheck/PKGBUILD

I didn't test this change but it maybe fixes the #4753

(Maybe) a fix for cppcheck->PCRE dependency issue

---

mingw-w64-arrow/PKGBUILD

This is a new recipe for Apache Arrow: https://arrow.apache.org/
Apache Arrow is a columnar format for efficient in-memory data analytics.
Apache Arrow defines data format and provides libraries to process data in the format.
Apache Arrow supports many languages but this recipe supports only C++ and C (GLib). C++ library includes Python integration.
`check` is disabled for now because Apache Arrow doesn't support running tests with MinGW build yet.

arrow: add

---

mingw-w64-gtk3/PKGBUILD
mingw-w64-gtk3/gtk3-i686.install
mingw-w64-gtk3/gtk3-x86_64.install

Stop writing a default settings.ini since gtk now has good defaults for it:
https://gitlab.gnome.org/GNOME/gtk/merge_requests/437

gtk3: Update to 3.24.2

---

mingw-w64-cython/PKGBUILD

This updates cython to 0.29.2.

cython: update to 0.29.2

---

mingw-w64-libgeotiff/PKGBUILD
mingw-w64-libgeotiff/libgeotiff_buildsys.patch

This updates libgeotiff to 1.4.3.

libgeotiff: update to 1.4.3

---

mingw-w64-zstd/PKGBUILD

zstd: update to 1.3.8

---

mingw-w64-wget/PKGBUILD

mingw-w64-wget: Update pcre2 dependency

---

mingw-w64-libidn2/PKGBUILD

This updates libidn2 to 2.1.0.

libidn2: update to 2.1.0

---

mingw-w64-libuv/PKGBUILD

libuv: update to 1.25.0

---

mingw-w64-ccache/PKGBUILD

ccache: update to 3.6

---

mingw-w64-libwebp/PKGBUILD

This updates libwebp to 1.0.2.

libwebp: update to 1.0.2

---

mingw-w64-arpack/PKGBUILD

arpack: update to 3.7.0

---

mingw-w64-cython/PKGBUILD

This updates cython to 0.29.3.

cython: update to 0.29.3

---

mingw-w64-libxml2/PKGBUILD

This updates libxml2 to 2.9.9.

libxml2: update to 2.9.9

---

mingw-w64-python-pluggy/PKGBUILD

This updates python-pluggy to 0.8.1.

python-pluggy: update to 0.8.1

---

mingw-w64-python-beautifulsoup4/PKGBUILD
mingw-w64-python-msgpack/PKGBUILD
mingw-w64-python-soupsieve/PKGBUILD
mingw-w64-python-sphinx-alabaster-theme/PKGBUILD
mingw-w64-python-sphinx_rtd_theme/PKGBUILD
mingw-w64-python-wrapt/PKGBUILD

* python-sphinx-alabaster-theme: Update to 0.7.12
* python-sphinx_rtd_theme: Update to 0.4.2
* python-msgpack: Update to 0.6.0
* python-beautifulsoup4: Update to 4.7.1
* python-soupsieve: Update to 1.7.2
* python-wrapt: Update to 1.11.1

Python updates

---

mingw-w64-python-keras/0001-change-backend-to-theano.patch
mingw-w64-python-keras/PKGBUILD

Add mingw-w64-python-keras package

---

mingw-w64-python-keras_applications/PKGBUILD

Reference implementations of popular deep learning models.

Add mingw-w64-python-keras_applications package

---

mingw-w64-x265/PKGBUILD

x265: update to 3.0

---

mingw-w64-python-faker/PKGBUILD

This updates python-faker to 1.0.2.

python-faker: update to 1.0.2

---

mingw-w64-bwidget/PKGBUILD

This updates bwidget to 1.9.13.

bwidget: update to 1.9.13

---

mingw-w64-mypaint-brushes2/PKGBUILD

The brush pack to be default in upcoming release of MyPaint 2.0 so this is fairly important

mypaint-brushes 2.0.1 released, new brush pack added

---

mingw-w64-libgit2/PKGBUILD

This updates libgit2 to 0.27.8.

libgit2: update to 0.27.8

---

mingw-w64-http-parser/PKGBUILD

This updates http-parser to 2.9.0.

http-parser: update to 2.9.0

---

mingw-w64-nss/PKGBUILD

nss: update to 3.42

---

mingw-w64-glog/PKGBUILD

Fixes https://github.com/Alexpux/MSYS2-packages/issues/960

glog: Fix libunwind dependency

---

mingw-w64-faudio/PKGBUILD

This provides an XAudio2 like api using SDL2 and ffmpeg (For wma decoding) a look over would be nice to make sure files are properly placed for the cmake config files.

Initial commit of FAudio package

---

mingw-w64-python-lz4/PKGBUILD
mingw-w64-python-pkgconfig/PKGBUILD

PKGBUILD for https://github.com/python-lz4/python-lz4
Tested and working on both x86_64 and i686.

add python-lz4 and python-pkgconfig

---

mingw-w64-python-sphinx/PKGBUILD

This updates python-sphinx to 1.8.4.

python-sphinx: update to 1.8.4

---

mingw-w64-sqlite3/PKGBUILD

This updates sqlite3 to 3.27.0.

sqlite3: update to 3.27.0

---

mingw-w64-babl/PKGBUILD

babl: update to 0.1.62

---

mingw-w64-libuv/PKGBUILD

libuv: update to 1.26.0

---

mingw-w64-libassuan/PKGBUILD

This updates libassuan to 2.5.3.

libassuan: update to 2.5.3

---

mingw-w64-libbluray/PKGBUILD

This updates libbluray to 1.1.0.

libbluray: update to 1.1.0

---

mingw-w64-xapian-core/PKGBUILD

This updates xapian-core to 1.4.10.

xapian-core: update to 1.4.10

---

mingw-w64-libgit2/PKGBUILD

This updates libgit2 to 0.28.1.

libgit2: update to 0.28.1

---

mingw-w64-SDL2_ttf/PKGBUILD

This updates SDL2_ttf to 2.0.15.

SDL2_ttf: update to 2.0.15

---

mingw-w64-libgit2-glib/Fix-vapi-generation-on-msys2.patch
mingw-w64-libgit2-glib/PKGBUILD

This updates libgit2-glib to 0.27.8.

libgit2-glib: update to 0.27.8

---

mingw-w64-file/PKGBUILD

file: update to 5.36

---

mingw-w64-pcre/PKGBUILD

pcre: update to 8.43

---

mingw-w64-sqlite3/PKGBUILD

This updates sqlite3 to 3.27.2.

sqlite3: update to 3.27.2

---

mingw-w64-armadillo/PKGBUILD

This updates armadillo to 9.200.7.

armadillo: update to 9.200.7

---

mingw-w64-libatomic_ops/PKGBUILD

This updates libatomic_ops to 7.6.10.

libatomic_ops: update to 7.6.10

---

mingw-w64-protobuf/PKGBUILD

This updates protobuf to 3.7.0.

protobuf: update to 3.7.0

---

mingw-w64-libwmf/PKGBUILD

This updates libwmf to 0.2.12.

libwmf: update to 0.2.12

---

mingw-w64-graphene/PKGBUILD

This updates graphene to 1.8.6.

graphene: update to 1.8.6

---

mingw-w64-libdvdread/PKGBUILD

This updates libdvdread to 6.0.1.

libdvdread: update to 6.0.1

---

mingw-w64-antlr4-runtime-cpp/PKGBUILD
mingw-w64-antlr4-runtime-cpp/antlr4-install-dll-to-bin.patch

This updates antlr4-runtime-cpp to 4.7.2.

antlr4-runtime-cpp: update to 4.7.2

---

mingw-w64-python-sphinx/PKGBUILD

This updates python-sphinx to 1.8.5.

python-sphinx: update to 1.8.5

---

mingw-w64-fltk/PKGBUILD

fltk: update to 1.3.5

---

mingw-w64-dlib/PKGBUILD

dlib: update to 19.17

---

mingw-w64-grantlee/PKGBUILD

A string template engine based on the Django template system and written in Qt5

grantlee - 5.1.0 - new package

---

mingw-w64-shapelib/PKGBUILD

This updates shapelib to 1.5.0.

shapelib: update to 1.5.0

---

mingw-w64-python-ldap/PKGBUILD

- bump version to 3.2.0
- take over maintainership

python-ldap 3.2.0

---

mingw-w64-libyaml/PKGBUILD

This updates libyaml to 0.2.2.

libyaml: update to 0.2.2

---

mingw-w64-kicad-doc/PKGBUILD
mingw-w64-kicad-footprints-git/PKGBUILD
mingw-w64-kicad-git/PKGBUILD
mingw-w64-kicad-git/glm_version_ok.patch
mingw-w64-kicad-packages3D-git/PKGBUILD
mingw-w64-kicad-symbols-git/PKGBUILD
mingw-w64-kicad-templates-git/PKGBUILD
mingw-w64-kicad/PKGBUILD
mingw-w64-kicad/glm_version_ok.patch

Update to release 5.1.0
Add depens (#4829)

kicad: Update to 5.1.0

---

mingw-w64-gcc-git/PKGBUILD

gcc-git: Enable GCC plugins.

---

mingw-w64-libepoxy/PKGBUILD

Hoping this setting will enable the static version to be built. I don't have windows so will need verified.

enable building as static library (untested)

---

mingw-w64-libzip/PKGBUILD

libzip: update to 1.5.2

---

mingw-w64-allegro/PKGBUILD

This updates allegro to 5.2.5.

allegro: update to 5.2.5

---

mingw-w64-jasper/PKGBUILD

This updates jasper to 2.0.16.

jasper: update to 2.0.16

---

mingw-w64-nss/PKGBUILD

nss: update to 3.43

---

mingw-w64-libuv/PKGBUILD

libuv: update to 1.27.0

---

mingw-w64-gtksourceview4/PKGBUILD

This updates gtksourceview4 to 4.2.0.

gtksourceview4: update to 4.2.0

---

mingw-w64-gtksourceview3/PKGBUILD

This updates gtksourceview3 to 3.24.10.

gtksourceview3: update to 3.24.10

---

mingw-w64-libsecret/0001-port-to.mingw.patch
mingw-w64-libsecret/PKGBUILD

This updates libsecret to 0.18.8. gtk-doc is added to makedepends so prepare() succeeds.

libsecret: update to 0.18.8

---

mingw-w64-python3/0000-make-_sysconfigdata.py-relocatable.patch
mingw-w64-python3/PKGBUILD
mingw-w64-python3/smoketests.py

Reverts msys2/MINGW-packages#5069

Revert "python3: Improve patching _sysconfigdata.py"

---

mingw-w64-python3/0000-make-_sysconfigdata.py-relocatable.patch
mingw-w64-python3/PKGBUILD
mingw-w64-python3/smoketests.py

Reverts msys2/MINGW-packages#5087

Revert "Revert "python3: Improve patching _sysconfigdata.py""

---

mingw-w64-libssh2/PKGBUILD

This updates libssh2 to 1.8.1.

libssh2: update to 1.8.1

---

mingw-w64-gnupg/PKGBUILD

gnupg: update to 2.2.14

---

mingw-w64-python-mako/PKGBUILD

This updates python-mako to 1.0.8.

python-mako: update to 1.0.8

---

mingw-w64-python-beaker/PKGBUILD

This updates python-beaker to 1.10.1.

python-beaker: update to 1.10.1

---

mingw-w64-physfs/PKGBUILD

physfs: update to 3.0.2

---

mingw-w64-blosc/PKGBUILD

blosc: update to 1.16.3

---

mingw-w64-gnupg/PKGBUILD

gnupg: update to 2.2.15

---

mingw-w64-cmocka/001-install-fixes.patch
mingw-w64-cmocka/PKGBUILD

cmocka: update to 1.1.5

---

mingw-w64-curl/0001-Make-cURL-relocatable.patch
mingw-w64-curl/0003-libpsl-static-libs.patch
mingw-w64-curl/PKGBUILD

curl: update to 7.64.1

---

mingw-w64-protobuf/PKGBUILD

This updates protobuf to 3.7.1.

protobuf: update to 3.7.1

---

mingw-w64-harfbuzz/PKGBUILD

This updates harfbuzz to 2.4.0.

harfbuzz: update to 2.4.0

---

mingw-w64-libgeotiff/PKGBUILD
mingw-w64-libgeotiff/libgeotiff_buildsys.patch

This updates libgeotiff to 1.5.1.

libgeotiff: update to 1.5.1

---

mingw-w64-cgal/PKGBUILD

cgal: update to 4.14

---

mingw-w64-jemalloc/PKGBUILD

This updates jemalloc to 5.2.0.

jemalloc: update to 5.2.0

---

mingw-w64-libvpx/0002-no-pthreads.mingw.patch
mingw-w64-libvpx/PKGBUILD

libvpx: update to 1.8.0

---

mingw-w64-squirrel/PKGBUILD
mingw-w64-squirrel/squirrel-3.1-1-cmake-name.patch

A light-weight scripting language that fits in the size, memory bandwidth, and real-time requirements of applications like video games

mingw-w64-squirrel - 3.1-1 = New package

---

mingw-w64-libbluray/PKGBUILD

This updates libbluray to 1.1.1.

libbluray: update to 1.1.1

---

mingw-w64-gpgme/0005-invoke-scripts-via-sh.patch
mingw-w64-gpgme/PKGBUILD
mingw-w64-gpgme/gpgme-fix-cpp-tests.patch
mingw-w64-gpgme/gpgmepp-portable-types.patch

gpgme: update to 1.13.0

---

mingw-w64-pixman/PKGBUILD

This updates pixman to 0.38.2.

pixman: update to 0.38.2

---

mingw-w64-wget/PKGBUILD

wget: update to 1.20.3

---

mingw-w64-atk/PKGBUILD

atk: update to 2.32.0

---

mingw-w64-gsasl/PKGBUILD
mingw-w64-gsasl/gsasl-avoid-conflicting-types.patch

This rebuilds gsasl against readline 8.

gsasl: rebuild against readline 8

---

mingw-w64-drmingw/PKGBUILD

This updates drmingw to 0.9.1.

drmingw: update to 0.9.1

---

mingw-w64-xxhash/PKGBUILD

xxhash: update to 0.7.0

---

mingw-w64-laszip/PKGBUILD

laszip: update to 3.4.0

---

mingw-w64-cmark/PKGBUILD

cmark: update to 0.29.0

---

mingw-w64-isl/PKGBUILD

isl: update to 0.21

---

mingw-w64-http-parser/PKGBUILD

This updates http-parser to 2.9.1.

http-parser: update to 2.9.1

---

mingw-w64-boost/PKGBUILD
mingw-w64-boost/boost-1.57.0-build-optflags.patch
mingw-w64-boost/boost-1.70.0-fix-python-install.patch

boost: update to 1.70.0

---

mingw-w64-poppler/PKGBUILD

This updates poppler to 0.75.0.

poppler: update to 0.75.0

---

mingw-w64-nlopt/PKGBUILD

nlopt: update to 2.6.1

---

mingw-w64-asciidoctor/PKGBUILD

This updates asciidoctor to 2.0.7.

asciidoctor: update to 2.0.7

---

mingw-w64-opus/PKGBUILD

opus: update to 1.3.1

---

mingw-w64-cython/PKGBUILD

This updates cython to 0.29.7.

cython: update to 0.29.7

---

mingw-w64-python-pillow/PKGBUILD

This updates python-pillow to 6.0.0.

python-pillow: update to 6.0.0

---

mingw-w64-python-setuptools/PKGBUILD

This updates python-setuptools to 41.0.0.

python-setuptools: update to 41.0.0

---

mingw-w64-python-jinja/PKGBUILD

This updates python-jinja to 2.10.1.

python-jinja: update to 2.10.1

---

mingw-w64-python-soupsieve/PKGBUILD

This updates python-soupsieve to 1.9.1.

python-soupsieve: update to 1.9.1

---

mingw-w64-python-xlsxwriter/PKGBUILD

This updates python-xlsxwriter to 1.1.5.

python-xlsxwriter: update to 1.1.5

---

mingw-w64-vala/PKGBUILD

vala: update to 0.44.3

---

mingw-w64-orc/PKGBUILD

orc: update to 0.4.29

---

mingw-w64-libpng/PKGBUILD

This updates libpng to 1.6.37.

libpng: update to 1.6.37

---

mingw-w64-libuv/PKGBUILD

libuv: update to 1.28.0

---

mingw-w64-gtkmm3/PKGBUILD

This updates gtkmm3 to 3.24.1.

gtkmm3: update to 3.24.1

---

mingw-w64-gnutls/0004-disable-broken-examples.patch
mingw-w64-gnutls/0005-remove-coverage-rules.patch
mingw-w64-gnutls/PKGBUILD

This updates gnutls to 3.6.7.1.

gnutls: update to 3.6.7.1

---

mingw-w64-libpsl/PKGBUILD

This updates libpsl to 0.21.0.

libpsl: update to 0.21.0

---

mingw-w64-zstd/PKGBUILD
mingw-w64-zstd/zstd-1.4.0-fileio-mingw.patch
mingw-w64-zstd/zstd-1.4.0-fix-build-pzstd.patch

zstd: update to 1.4.0

---

mingw-w64-cmake/0004-Implement-Qt5-static-plugin-support.patch
mingw-w64-cmake/PKGBUILD

cmake: update to 3.14.2

---

mingw-w64-pcre2/PKGBUILD

pcre2: update to 10.33

---

mingw-w64-libcdr/PKGBUILD
mingw-w64-libcdr/libcdr-0.1.5-remove-have-visibility-check.patch

libcdr: update to 0.1.5

---

mingw-w64-libcdio/PKGBUILD

This updates libcdio to 2.1.0.

libcdio: update to 2.1.0

---

mingw-w64-ruby/PKGBUILD

ruby: update to 2.6.3

---

mingw-w64-mruby/PKGBUILD

mruby: update to 2.0.1

---

mingw-w64-ffmpeg/PKGBUILD

ffmpeg: update to 4.1.3

---

mingw-w64-fluidsynth/PKGBUILD

This updates fluidsynth to 2.0.5.

fluidsynth: update to 2.0.5

---

mingw-w64-clang/0014-winpthreads-workaround.patch
mingw-w64-clang/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/5231

clang: Apply workaround for mingw-w64 pthreads bug

---

mingw-w64-http-parser/PKGBUILD

This updates http-parser to 2.9.2.

http-parser: update to 2.9.2

---

mingw-w64-libfilezilla/PKGBUILD

This updates libfilezilla to 0.16.0.

libfilezilla: Update to 0.16.0

---

mingw-w64-qbs/0004-Use-.dll.a-instead-of-.a-for-mingw-import-librar.1.4.patch
mingw-w64-qbs/0005-setup-toolchains-Pretend-msys-is-mingw.1.4.patch
mingw-w64-qbs/PKGBUILD

qbs: update to 1.13.0

---

mingw-w64-xmlsec/PKGBUILD

This updates xmlsec to 1.2.28.

xmlsec: update to 1.2.28

---

mingw-w64-laszip/PKGBUILD

laszip: update to 3.4.1

---

mingw-w64-cogl/PKGBUILD

cogl: update to 1.22.4

---

mingw-w64-ccache/01-directory-separator.patch
mingw-w64-ccache/PKGBUILD

ccache: update to 3.7

---

mingw-w64-nss/PKGBUILD

nss: update to 3.44

---

mingw-w64-discount/PKGBUILD
mingw-w64-discount/discount-mingw-building.patch

This updates discount to 2.2.6.

discount: update to 2.2.6

---

mingw-w64-gsettings-desktop-schemas/PKGBUILD

gsettings-desktop-schemas: Update to 3.32.0 and port to meson

---

mingw-w64-oniguruma/PKGBUILD

This updates oniguruma to 6.9.2.

oniguruma: update to 6.9.2

---

mingw-w64-gcc-git/0014-gcc-9-branch-clone_function_name_1-Retain-any-stdcall-suffix.patch
mingw-w64-gcc-git/PKGBUILD

gcc-git: Upgrade to GCC 9.

---

mingw-w64-libraqm/PKGBUILD

This updates libraqm to 0.6.0.

libraqm: update to 0.6.0

---

mingw-w64-libgsf/PKGBUILD

This updates libgsf to 1.14.46.

libgsf: update to 1.14.46

---

mingw-w64-asciidoctor/PKGBUILD

This updates asciidoctor to 2.0.9.

asciidoctor: update to 2.0.9

---

mingw-w64-crypto++/PKGBUILD

This updates crypto++ to 8.2.0.

crypto++: update to 8.2.0

---

mingw-w64-geos/PKGBUILD

geos: update to 3.7.2

---

mingw-w64-libiconv/0002-fix-cr-for-awk-in-configure.all.patch
mingw-w64-libiconv/PKGBUILD

This updates libiconv to 1.16.

libiconv: update to 1.16

---

mingw-w64-libgit2-glib/PKGBUILD

This updates libgit2-glib to 0.28.0.1.

libgit2-glib: update to 0.28.0.1

---

mingw-w64-tor/PKGBUILD

tor: update to 0.4.0.5

---

mingw-w64-libshout/0006-winsock.patch
mingw-w64-libshout/0007-includes.patch
mingw-w64-libshout/01-libshout-tls-compile-with-OpenSSL-1.1.0.patch
mingw-w64-libshout/PKGBUILD

This updates libshout to 2.4.2.

libshout: update to 2.4.2

---

mingw-w64-swig/001-relocate.patch
mingw-w64-swig/002-fix-python-find.patch
mingw-w64-swig/PKGBUILD

swig: update to 4.0.0

---

mingw-w64-python-kiwisolver/PKGBUILD

This updates python-kiwisolver to 1.1.0.

python-kiwisolver: update to 1.1.0

---

mingw-w64-openblas/PKGBUILD

This updates openblas to 0.3.6.

openblas: update to 0.3.6

---

mingw-w64-python-attrs/PKGBUILD

This updates python-attrs to 19.1.0.

python-attrs: update to 19.1.0

---

mingw-w64-gdb/PKGBUILD

gdb: update to 8.3

---

mingw-w64-libuv/PKGBUILD

libuv: update to 1.29.0

---

mingw-w64-t1utils/LICENSE
mingw-w64-t1utils/PKGBUILD
mingw-w64-t1utils/memmem-decl.patch

A collection of simple Type 1 font manipulation programs

mingw-w64-t1utils

---

mingw-w64-file/PKGBUILD

file: update to 5.37

---

mingw-w64-libsass/PKGBUILD

This updates libsass to 3.6.0.

libsass: update to 3.6.0

---

mingw-w64-sassc/PKGBUILD

sassc: update to 3.6.0

---

mingw-w64-proj/PKGBUILD

proj: update to 6.1.0

---

mingw-w64-codelite-git/001-include-winsock-header.patch
mingw-w64-codelite-git/002-mingw-use-wx-manifests.patch
mingw-w64-codelite-git/004-windows-headers-conflict.patch
mingw-w64-codelite-git/005-fix-sqlite3-find-and-build.patch
mingw-w64-codelite-git/011-use-std_string.patch
mingw-w64-codelite-git/012-define-wxCONTROL_NONE.patch
mingw-w64-codelite-git/013-fix-linking-libraries-names.patch
mingw-w64-codelite-git/014-fix-link-dup-error.patch
mingw-w64-codelite-git/015-remove-WXDLLIMPEXP_SDK-from-codelite_terminal.patch
mingw-w64-codelite-git/PKGBUILD

Update and add patch files.
Change to using git folder ${_realname}-git
codelite program opens and closes without run-time error; I have no idea on what else to check.
Tim S.

codelite-git: Fix building

---

mingw-w64-python-zipp/PKGBUILD

mingw-w64-python-zipp 0 0.5.1 - New package required for importlib

python-importlib-metadata 0 0.12 -  Update to latest version

---

mingw-w64-alembic/PKGBUILD

This updates alembic to 1.7.11.

alembic: update to 1.7.11

---

mingw-w64-python-pywavelets/PKGBUILD

This updates python-pywavelets to 1.0.3.

python-pywavelets: update to 1.0.3

---

mingw-w64-libgit2/PKGBUILD

This updates libgit2 to 0.28.2.

libgit2: update to 0.28.2

---

mingw-w64-libuv/PKGBUILD

libuv: update to 1.29.1

---

mingw-w64-glib2/PKGBUILD

glib2: update to 2.60.3

---

mingw-w64-curl/0001-Make-cURL-relocatable.patch
mingw-w64-curl/PKGBUILD

curl: update to 7.65.0

---

mingw-w64-p11-kit/0012-no-getuid.patch
mingw-w64-p11-kit/PKGBUILD

This updates p11-kit to 0.23.16.1.

p11-kit: update to 0.23.16.1

---

mingw-w64-quazip/PKGBUILD
mingw-w64-quazip/mingw-build.patch

quazip: update to 0.8

---

mingw-w64-libical/PKGBUILD

This updates libical to 3.0.5.

libical: update to 3.0.5

---

mingw-w64-glbinding/PKGBUILD
mingw-w64-glbinding/fix-proc-address.patch

This updates glbinding to 3.1.0.

glbinding: update to 3.1.0

---

mingw-w64-double-conversion/PKGBUILD

This updates double-conversion to 3.1.5.

double-conversion: update to 3.1.5

---

mingw-w64-harfbuzz/PKGBUILD

This updates harfbuzz to 2.5.0.

harfbuzz: update to 2.5.0

---

mingw-w64-libimagequant/PKGBUILD

This updates libimagequant to 2.12.3.

libimagequant: update to 2.12.3

---

mingw-w64-gcc-git/PKGBUILD

gcc-git: Package the 'plugin' directory.

---

mingw-w64-freetds/PKGBUILD

This updates freetds to 1.00.100.

freetds: update to 1.00.100

---

mingw-w64-libraqm/PKGBUILD

This updates libraqm to 0.7.0.

libraqm: update to 0.7.0

---

mingw-w64-libevent/PKGBUILD

This updates libevent to 2.1.10.

libevent: update to 2.1.10

---

mingw-w64-libidn2/PKGBUILD

This updates libidn2 to 2.2.0.

libidn2: update to 2.2.0

---

mingw-w64-cython/PKGBUILD

This updates cython to 0.29.8.

cython: update to 0.29.8

---

mingw-w64-openssl/PKGBUILD

This updates openssl to 1.1.1.c.

openssl: update to 1.1.1.c

---

mingw-w64-gnutls/PKGBUILD

gnutls: update to 3.6.8

---

mingw-w64-gnupg/PKGBUILD

gnupg: update to 2.2.16

---

mingw-w64-babl/PKGBUILD

babl: update to 0.1.64

---

mingw-w64-python-sqlalchemy/PKGBUILD

This updates python-sqlalchemy to 1.3.4.

python-sqlalchemy: update to 1.3.4

---

mingw-w64-python-fonttools/PKGBUILD
mingw-w64-python-fonttools/fonttools2-i686.install
mingw-w64-python-fonttools/fonttools2-x86_64.install
mingw-w64-python-fonttools/fonttools3-i686.install
mingw-w64-python-fonttools/fonttools3-x86_64.install

This updates python-fonttools to 3.42.0.

python-fonttools: update to 3.42.0

---

mingw-w64-libsodium/PKGBUILD

This updates libsodium to 1.0.18.

libsodium: update to 1.0.18

---

mingw-w64-harfbuzz/PKGBUILD

This updates harfbuzz to 2.5.1.

harfbuzz: update to 2.5.1

---

mingw-w64-protobuf/PKGBUILD

This updates protobuf to 3.8.0.

protobuf: update to 3.8.0

---

mingw-w64-gdb/PKGBUILD
mingw-w64-gdb/gdb-8.3-cache-dir.patch

... when not running from MSYS environment, and HOME is not set.

gdb: Fix cache dir resolving

---

mingw-w64-faudio/PKGBUILD

This updates `faudio` to `19.06`.

faudio: update to 19.06

---

mingw-w64-python-xlsxwriter/PKGBUILD

This updates python-xlsxwriter to 1.1.8.

python-xlsxwriter: update to 1.1.8

---

mingw-w64-python-win_inet_pton/PKGBUILD

This updates python-win_inet_pton to 1.1.0.

python-win_inet_pton: update to 1.1.0

---

mingw-w64-python-pysocks/PKGBUILD

This updates python-pysocks to 1.7.0.

python-pysocks: update to 1.7.0

---

mingw-w64-sqlcipher/PKGBUILD

This updates sqlcipher to 4.2.0.

sqlcipher: update to 4.2.0

---

mingw-w64-mesa/PKGBUILD
mingw-w64-mesa/msys2-mingw_w64-fixes.patch

Also improve the compatibility patch to make it easier to review.

Update Mesa3D 19.0.6

---

mingw-w64-python-fasteners/PKGBUILD

This updates python-fasteners to 0.15.

python-fasteners: update to 0.15

---

mingw-w64-python-json-rpc/PKGBUILD

This updates python-json-rpc to 1.12.1.

python-json-rpc: update to 1.12.1

---

mingw-w64-verilator/PKGBUILD

This updates verilator to 4.014.

verilator: update to 4.014

---

mingw-w64-libmicrohttpd/PKGBUILD

* Added support for debug build
* Added `check()` step.

libmicrohttpd: added more build options

---

mingw-w64-libmicrohttpd/PKGBUILD

libmicrohttpd: build for Win7+

---

mingw-w64-glib2/PKGBUILD

glib2: update to 2.60.4

---

mingw-w64-dbus/PKGBUILD

dbus: update to 1.12.16

---

mingw-w64-libshout/0007-includes.patch
mingw-w64-libshout/01-libshout-tls-compile-with-OpenSSL-1.1.0.patch
mingw-w64-libshout/PKGBUILD

This updates libshout to 2.4.3.

libshout: update to 2.4.3

---

mingw-w64-libarchive/PKGBUILD

This updates libarchive to 3.4.0.

libarchive: update to 3.4.0

---

mingw-w64-zimg/PKGBUILD

zimg: update to 2.9.1

---

mingw-w64-gpgme/PKGBUILD

gpgme: update to 1.13.1

---

mingw-w64-plplot/PKGBUILD

plplot: move qhull from makedepends to depends

---

mingw-w64-wxSVG/ChangeLog
mingw-w64-wxSVG/PKGBUILD

[wxSVG](http://wxsvg.sourceforge.net/) is a library handling [Scalable Vector Graphics (SVG)](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics) in [wxWidgets](https://www.wxwidgets.org/).
This is the first time I have created a package for MSYS2/MinGW. I used the [wxWidgets PKGBUILD file](https://github.com/msys2/MINGW-packages/blob/8120aa3b631c9c43df651904b461a524de237cdb/mingw-w64-wxWidgets/PKGBUILD) for reference. Please let me know if I have made any mistakes I need to correct.

New package: wxSVG

---

mingw-w64-python-jsonschema/PKGBUILD

Interestingly the sha256sums was also wrong?

jsonschema: move attr, pyrsistent and setuptools from makedepends to depends

---

mingw-w64-gsfont/PKGBUILD
mingw-w64-gsfont/font-i686.install
mingw-w64-gsfont/font-x86_64.install
mingw-w64-ttf-dejavu/PKGBUILD
mingw-w64-ttf-dejavu/font-i686.install
mingw-w64-ttf-dejavu/font-x86_64.install

ttf-dejavu - 2.37 - update font cache

gsfonts - 20180524 - update font cache

---

mingw-w64-gpgme/PKGBUILD

Build gpgme with glib

---

mingw-w64-openh264/PKGBUILD

This updates openh264 to 2.0.0.

openh264: update to 2.0.0

---

mingw-w64-filezilla/PKGBUILD

This includes filezilla since msys2 already carries libfilezilla

[Package] FileZilla

---

mingw-w64-unbound/PKGBUILD

This updates unbound to 1.9.2.

unbound: update to 1.9.2

---

mingw-w64-python-sqlalchemy/PKGBUILD

This updates python-sqlalchemy to 1.3.5.

python-sqlalchemy: update to 1.3.5

---

mingw-w64-gtk3/PKGBUILD

gtk3: update to 3.24.9

---

mingw-w64-libfilezilla/0001-libfilezilla-0.17.0-define-version.patch
mingw-w64-libfilezilla/PKGBUILD
mingw-w64-libfilezilla/libfilezilla.rc
mingw-w64-libfilezilla/manifest.xml

This updates libfilezilla to 0.17.0.

libfilezilla: update to 0.17.0

---

mingw-w64-expat/PKGBUILD

expat: update to 2.2.7

---

mingw-w64-dlfcn/PKGBUILD

dlfcn: update to 1.2.0

---

mingw-w64-groonga/PKGBUILD

Groonga is an opensource fulltext search engine.

Add mingw-w64-groonga package

---

mingw-w64-wxWidgets3.1/001-wxWidgets-3.0.2-relocate-prefix-in-bin-wx-config.patch
mingw-w64-wxWidgets3.1/002-wxWidgets-3.0.3-make-abicheck-non-fatal.patch
mingw-w64-wxWidgets3.1/005-wxWidgets-3.0.2-Remove-WX_LIBS_STATIC-from-m4.patch
mingw-w64-wxWidgets3.1/011-wxWidgets-3.1.2-Enable-wxUSE_GRAPHICS_DIRECT2D.patch
mingw-w64-wxWidgets3.1/PKGBUILD

wxWidgets version 3.1.1 is the latest development release of wxWidgets . I would not create a binary unless others request it.  I also have packages for wxWidgets3.0-git and wxWidgets-git; but, I am not sure you would want them. Tim S.

wxWidgets3.1: Add package

---

mingw-w64-dcraw/PKGBUILD

`dcraw` is a console tool for manipulation of raw image formats from digital cameras.

Add a new package - dcraw

---

mingw-w64-python-parso/PKGBUILD

This updates python-parso to 0.5.0.

python-parso: update to 0.5.0

---

mingw-w64-groonga/PKGBUILD

It requires rapidjson for builtin new feature.

groonga: update to Groonga 9.0.4

---

mingw-w64-SDL2_image/PKGBUILD

This updates SDL2_image to 2.0.5.

SDL2_image: update to 2.0.5

---

mingw-w64-proj/PKGBUILD

proj: update to 6.1.1

---

mingw-w64-docbook-xml/PKGBUILD
mingw-w64-docbook-xml/docbook-xml-i686.install
mingw-w64-docbook-xml/docbook-xml-x86_64.install
mingw-w64-docbook-xsl/0001-nons-add-back-old-uri-rewrite.patch
mingw-w64-docbook-xsl/PKGBUILD
mingw-w64-docbook-xsl/docbook-xsl-i686.install
mingw-w64-docbook-xsl/docbook-xsl-x86_64.install

docbook-xxml - add docbook5 schemas including 5.0.1 - try to fix catalog
docbook-xsl - add docbook-xsl-nons - try to fix catalog
Note that there still is an inconsistancy betwen //mingw64/bin/xmlcatalog and /usr/bin/xmlcatalog.  It's like this:
----
root@agnus2 MSYS /home/jpmugaas/exp/mingw-w64-docbook-xsl
D:/msys64/mingw64/share/xml/docbook/schema/5.0/docbook.nvdl
root@agnus2 MSYS /home/jpmugaas/exp/mingw-w64-docbook-xsl
/mingw64/share/xml/docbook/schema/5.0/docbook.nvdl
/mingw64/etc/xml/docbook-xml:97:  <rewriteSystem systemIdStartString="http://www.oasis-open.org/docbook/xml/5.0/docbook.nvdl" rewritePrefix="../../share/xml/docbook/schema/5.0/docbook.nvdl"/>
/mingw64/etc/xml/docbook-xml:98:  <rewriteURI uriStartString="http://www.oasis-open.org/docbook/xml/5.0/docbook.nvdl" …

docbook updates

---

mingw-w64-enchant/PKGBUILD

This updates enchant to 2.2.5.

enchant: update to 2.2.5

---

mingw-w64-zstd/PKGBUILD
mingw-w64-zstd/zstd-1.4.0-fileio-mingw.patch

zstd: update to 1.4.1

---

mingw-w64-python-xpra/PKGBUILD

xpra 2.5.3

---

mingw-w64-SDL2/PKGBUILD

SDL2: update to 2.0.10

---

mingw-w64-blosc/PKGBUILD

blosc: update to 1.17.0

---

mingw-w64-zstd/PKGBUILD

zstd: update to 1.4.2

---

mingw-w64-babl/PKGBUILD

babl: update to 0.1.68

---

mingw-w64-libimagequant/PKGBUILD

added .dll and .dll.a
added imagequant.pc for pkg-config

libimagequant - 2.12.5

---

mingw-w64-zimg/PKGBUILD

zimg: update to 2.9.2

---

mingw-w64-x265/PKGBUILD

x265: update to 3.1.2

---

mingw-w64-julia/0003-fix-CMAKE_GENERATOR_COMMAND-and-CMAKE_C_COMPILER.patch
mingw-w64-julia/0004-fix-base-floatfuncs.jl.patch
mingw-w64-julia/0007-Makefile.patch
mingw-w64-julia/0008-fix-i686-gcc-dll-name.patch
mingw-w64-julia/PKGBUILD

Try to compile julia under msys2.

Add mingw-w64-julia package

---

mingw-w64-julia/PKGBUILD

@Alexpux Sorry, my final pkgbuild file was not submitted to pr.

julia: remove libgcc_s_dw2-1.dll when packaging

---

mingw-w64-libevent/PKGBUILD

This updates libevent to 2.1.11.

libevent: update to 2.1.11

---

mingw-w64-flac/PKGBUILD

flac: update to 1.3.3

---

mingw-w64-vala/PKGBUILD

vala: update to 0.44.7

---

mingw-w64-libdazzle/0002-Install-to-bin-dir.patch
mingw-w64-libdazzle/PKGBUILD

libdazzle: Install on bin

---

mingw-w64-re2/PKGBUILD

Update to llatest version
build BOTH static and shared versions of re2

re2 - 20190801-

---

mingw-w64-julia/0009-find-modname-in-julia_dl-before-default-paths.patch
mingw-w64-julia/0010-fix-install-dir.patch
mingw-w64-julia/0011-donot-cp-LLVM.dll-when-USE_LLVM_SHLIB-disabled-on-WINNT.patch
mingw-w64-julia/PKGBUILD

Continue from https://github.com/msys2/MINGW-packages/pull/5679

julia: set `USE_LLVM_SHLIB = 0` and fix install dir

---

mingw-w64-pegtl/PKGBUILD

pegtl: update to 2.8.1

---

mingw-w64-xapian-core/PKGBUILD

This updates xapian-core to 1.4.12.

xapian-core: update to 1.4.12

---

mingw-w64-libwebp/PKGBUILD

Reverts msys2/MINGW-packages#5712

Revert "libwebp - enable experimental features"

---

mingw-w64-harfbuzz/PKGBUILD

This updates harfbuzz to 2.6.0.

harfbuzz: update to 2.6.0

---

mingw-w64-libgit2/PKGBUILD

This updates libgit2 to 0.28.3.

libgit2: update to 0.28.3

---

mingw-w64-postgis/PKGBUILD

This updates postgis to 2.5.3.

postgis: update to 2.5.3

---

mingw-w64-python-sqlalchemy/PKGBUILD

This updates python-sqlalchemy to 1.3.7.

python-sqlalchemy: update to 1.3.7

---

mingw-w64-blender/PKGBUILD

Reverts msys2/MINGW-packages#5729

Revert "Build 'bpy' module"

---

mingw-w64-ffcall/PKGBUILD

ffcall: update to 2.2

---

mingw-w64-graphene/PKGBUILD

This updates graphene to 1.10.0.

graphene: update to 1.10.0

---

mingw-w64-libsecret/0001-port-to.mingw.patch
mingw-w64-libsecret/PKGBUILD

This updates libsecret to 0.19.1.

libsecret: update to 0.19.1

---

mingw-w64-libusb/PKGBUILD

This updates libusb to 1.0.23.

libusb: update to 1.0.23

---

mingw-w64-enchant/PKGBUILD

This updates enchant to 2.2.6.

enchant: update to 2.2.6

---

mingw-w64-expat/PKGBUILD

expat: update to 2.2.8

---

mingw-w64-go/PKGBUILD

Aside: the PKGBUILD's quoting doesn't allow spaces in paths. I can submit a second PR to fix that.

go: Update to 1.13

---

mingw-w64-openssl/PKGBUILD

This updates openssl to 1.1.1.d.

openssl: update to 1.1.1.d

---

mingw-w64-libgcrypt/PKGBUILD

This updates libgcrypt to 1.8.5.

libgcrypt: update to 1.8.5

---

mingw-w64-atk/PKGBUILD

atk: update to 2.34.1

---

mingw-w64-libsoup/PKGBUILD

libsoup: add missing dep on brotli

---

mingw-w64-clang/0510-fix-CMake-when-LLDB_DISABLE_PYTHON-if-ON-and-ep.patch
mingw-w64-clang/PKGBUILD

See https://bugs.llvm.org/show_bug.cgi?id=43637

clang: fix lldb CMake when epydoc is present

---

mingw-w64-sqlite3/PKGBUILD

This updates sqlite3 to 3.30.1.

sqlite3: update to 3.30.1

---

mingw-w64-librsync/PKGBUILD

This updates librsync to 2.2.1 and adds static libraries.

librsync: update to 2.2.1

---

mingw-w64-libsass/PKGBUILD

This updates libsass to 3.6.2.

libsass: update to 3.6.2

---

mingw-w64-libunistring/PKGBUILD

libunistring: fix license

---

mingw-w64-geos/PKGBUILD

geos: update to 3.8.0

---

mingw-w64-gtksourceview4/PKGBUILD
mingw-w64-gtksourceview4/skip-tests.patch

building the tests is failing, so disabled for now

gtksourceview4: Update to 4.4.0; Port to meson

---

mingw-w64-groonga/PKGBUILD

Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>

groonga: Update to 9.0.9

---

mingw-w64-dbus/PKGBUILD

dbus: Port to Python 3

---

mingw-w64-dlib/PKGBUILD

Update dlib to 19.18. Also cause recompile with Python 3.8.

dlib: update to 19.18

---

mingw-w64-postgresql/PKGBUILD
mingw-w64-postgresql/postgresql-12.0-mingw-link.patch

Update to postgresql-12.0

---

mingw-w64-libvoikko/PKGBUILD

This updates libvoikko to 4.3.

libvoikko: update to 4.3

---

mingw-w64-mecab-naist-jdic/PKGBUILD

This package is required for mecab

WIP: mecab-naist-jdic: support mecab-naist-jdic 0.6.3b-20111013

---

mingw-w64-python-zipp/PKGBUILD

python-zipp: Depend on python-more-itertools

---

mingw-w64-libfilezilla/PKGBUILD
mingw-w64-libfilezilla/fix-syntax-error.patch

This updates libfilezilla to 0.19.0.

libfilezilla: update to 0.19.0

---

mingw-w64-libidn2/PKGBUILD

This updates libidn2 to 2.3.0.

libidn2: update to 2.3.0

---

mingw-w64-libepoxy/PKGBUILD

This updates libepoxy to 1.5.4.

libepoxy: update to 1.5.4

---

mingw-w64-gnupg/PKGBUILD

gnupg: update to 2.2.18

---

mingw-w64-python-psycopg2/PKGBUILD

${MINGW_PACKAGE_PREFIX}-postgresql>=8.4.1 added to depends as per  - https://github.com/msys2/MINGW-packages/issues/5979

psycopg2-2.8.4 - added validpgpkeys so I can build this.

---

mingw-w64-xapian-core/PKGBUILD

This updates xapian-core to 1.4.14.

xapian-core: update to 1.4.14

---

mingw-w64-libtasn1/PKGBUILD

This updates libtasn1 to 4.15.0.

libtasn1: update to 4.15.0

---

mingw-w64-mpv/PKGBUILD

mpv: add libplacebo dep; increment pkgrel

---

mingw-w64-parmetis/0001-mingw-w64-does-not-have-sys-resource-h.patch
mingw-w64-parmetis/0002-mingw-w64-do-not-use-reserved-double-underscored-names.patch
mingw-w64-parmetis/0003-WIN32-Install-RUNTIME-to-bin.patch
mingw-w64-parmetis/0004-METIS-GKLIB-location.patch
mingw-w64-parmetis/0005-find-MPI.patch
mingw-w64-parmetis/PKGBUILD

Parallel MPI version of the metis.

New package: parmetis

---

mingw-w64-python2-pygtk/005-atk-glib-libs.patch
mingw-w64-python2-pygtk/PKGBUILD

pygtk: fix the build with newer atk

---

mingw-w64-mesa/PKGBUILD

Disable Meson wrap generator until is required.

mingw-w64-mesa - 19.2.7

---

mingw-w64-ngraph-gtk/PKGBUILD

ngraph-gtk: new upstream release 6.08.02.

ngraph-gtk: Update to 6.08.02

---

mingw-w64-rhash/PKGBUILD
mingw-w64-rhash/fix-po-file.patch

rhash: update to 1.3.9

---

mingw-w64-mesa/PKGBUILD

Also add glapi shared library and OpenGL ES drivers.

mingw-w64-mesa: Switch to Meson build

---

mingw-w64-mesa/PKGBUILD
mingw-w64-mesa/llvmwrapgen.sh

around lib and include directories seeking. No functional change.

mingw-w64-mesa: Simplify LLVM Meson wrap generator

---

mingw-w64-glade3/PKGBUILD
mingw-w64-glade3/disable-yelp.patch

and work around itstools segfault by not building help files

glade3: disable Python support

---

mingw-w64-uasm/PKGBUILD

add mingw-w64-uasm package

---

mingw-w64-clang/PKGBUILD

clang: llvm depends on z3

---

mingw-w64-clang/0014-winpthreads-workaround.patch
mingw-w64-clang/PKGBUILD

- apply patch from:
https://github.com/llvm/llvm-project/commit/564481aebe18a723c9cfe9ea9ca5808771f7e9d8
- lld doesn't seem to hangs up anymore

fix for #6126, broken LLD

---

mingw-w64-wxWidgets/PKGBUILD

wxWidgets: don't build depend on Python 2

---

mingw-w64-tepl/PKGBUILD

See the two commits.
I’m the upstream maintainer of Tepl.

Tepl package: update and fix a problem

---

mingw-w64-libzip/PKGBUILD

libzip: update to 1.6.0

---

mingw-w64-python-xpra/PKGBUILD

Release notes for 3.0.6:
https://lists.devloop.org.uk/pipermail/shifter-users/2020-February/002497.html
3.0.5:
https://lists.devloop.org.uk/pipermail/shifter-users/2020-January/002479.html

xpra 3.0.6

---

mingw-w64-docbook-xsl/PKGBUILD
mingw-w64-docbook-xsl/docbook-xsl-i686.install
mingw-w64-docbook-xsl/docbook-xsl-x86_64.install

docbook-xsl: correct catalog directory

---

mingw-w64-libmypaint/PKGBUILD

libmypaint: update to 1.5.0

---

mingw-w64-helics/PKGBUILD

HELICS
Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS). HELICS provides an open-source, general-purpose, modular, highly-scalable co-simulation framework that runs cross-platform (Linux, Windows, and Mac OS X). It is not a modeling tool by itself, but rather an integration tool that enables multiple existing simulation tools (and/or multiple instances of the same tool), known as "federates," to exchange data during runtime and stay synchronized in time such that together they act as one large simulation, or "federation".
This package contains the libraries and executables to link with and run a helics based co-simulation.
Current version: 2.4.0
Upstream: https://github.com/GMLC-TDC/HELICS
Dependencies:  zeromq

New Package: helics

---

mingw-w64-xmake/PKGBUILD

I need fix some problems for v2.3.1 tar archive.

xmake: fix v2.3.1 shasum

---

mingw-w64-curl/0001-Make-cURL-relocatable.patch
mingw-w64-curl/PKGBUILD

curl: update to 7.69.0

---

mingw-w64-wxWidgets/PKGBUILD
mingw-w64-wxWidgets3.1/005-wxWidgets-3.1.3-Remove-WX_LIBS_STATIC-from-m4.patch
mingw-w64-wxWidgets3.1/011-wxWidgets-3.1.3-Allow-parsing-all-fractional-sizes-in-wxFont-descrip.patch
mingw-w64-wxWidgets3.1/023-wxWidgets-3.1.2-setup-wxUSE_GRAPHICS_DIRECT2D.patch
mingw-w64-wxWidgets3.1/PKGBUILD

wxWidgets: Add wxrc-${_wx_basever}.exe
wxWidgets3.1 update to version 3.1.3 and other minor changes.
Tim S.

wxWidgets and wxWidgets3.1 changes

---

mingw-w64-glibmm/PKGBUILD

fixes missing includes that breaks builds

glibmm: Update to 2.64.1

---

mingw-w64-gedit-plugins/PKGBUILD
mingw-w64-gedit/PKGBUILD

Note, I’m the upstream maintainer of gedit.

Update gedit and gedit-plugins, and simplify build instructions

---

mingw-w64-python-rst2pdf/PKGBUILD
mingw-w64-python-rst2pdf/rst2pdf-i686.install
mingw-w64-python-rst2pdf/rst2pdf-x86_64.install
mingw-w64-python-smartypants/PKGBUILD
mingw-w64-python-smartypants/fix-tests.patch
mingw-w64-python-smartypants/smartypants-i686.install
mingw-w64-python-smartypants/smartypants-x86_64.install

rst2pdf - 0.96 -
- added dependency on smartypants for consistancy with pip and pip database and Archlinux AUR
- added some docs for consistancy with Archlinux AUR
smartypants - 2.0.1
- new package required for rst2pdf

rst2pdf - 0.96 - added dependency on smartypants

---

mingw-w64-leptonica/PKGBUILD

* mingw-w64-leptonica/PKGBUILD:
- add check dependency package 'gnuplot'
- activate function 'check'

leptonica(1.79.0): activate check function

---

mingw-w64-qt5-static/0008-qt-5.3.0-win32-g-Add-QMAKE_EXTENSION_IMPORTLIB-defaulting-to-.patch
mingw-w64-qt5-static/PKGBUILD
mingw-w64-qt5/0008-qt-5.3.0-win32-g-Add-QMAKE_EXTENSION_IMPORTLIB-defaulting-to-.patch
mingw-w64-qt5/PKGBUILD

fix Qt5 CMake builds (fix #6333)

---

mingw-w64-librsvg/PKGBUILD

Merging this PR brings the package up to date.
Ref #6342

librsvg: Update to 2.48.2

---

mingw-w64-re2/PKGBUILD

Merging this PR brings the package up to date.
Ref #6342

re2: Update to 2020-04-01

---

mingw-w64-python-yaml/PKGBUILD

Merging this PR brings the package up to date.
Ref #6342

python-yaml: Update to 5.3.1

---

mingw-w64-jsoncpp/PKGBUILD

jsoncpp: Update to 1.9.2

---

mingw-w64-libplist/003-fix-py-soext.patch
mingw-w64-libplist/PKGBUILD

Fix the file extension of the C extension so Python can find it.
Fixes #6416

libplist: Fix the Python extension

---

mingw-w64-glew/PKGBUILD

fix @libgl@ in generated glew.pc

---

mingw-w64-freetype/PKGBUILD

New dependency added with the last release

freetype: Add missing brotli dependency

---

mingw-w64-librsvg/PKGBUILD

mainly libxml2, the rest is cleanup

librsvg: Add missing dependencies

---

mingw-w64-libgeotiff/PKGBUILD
mingw-w64-libgeotiff/libgeotiff_buildsys.patch

This updates libgeotiff to 1.6.0.

libgeotiff: update to 1.6.0

---

mingw-w64-arrow/PKGBUILD

Update Apache Arrow to version 0.17.1

---

mingw-w64-file/0001-file-5.38-mingw-build.patch
mingw-w64-file/PKGBUILD

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

Bump file and libmagic to latest version 5.38

---

mingw-w64-harfbuzz/PKGBUILD

harfbuzz: reinstate GRAPHITE2_STATIC workaround dropped with meson port

---

mingw-w64-vala/PKGBUILD

update Vala to 0.48.6

---

mingw-w64-sqlite3/PKGBUILD

This updates sqlite3 to 3.32.0.

sqlite3: update to 3.32.0

---

mingw-w64-pupnp/002-libupnp-win32.patch
mingw-w64-pupnp/005-backport-Fix-Windows-support-when-building-with-autotools.patch
mingw-w64-pupnp/006-backport-mediatomb-fix-but-place-it-differently.patch
mingw-w64-pupnp/007-backport-Fix-Windows-support-when-building-with-MinGW.patch
mingw-w64-pupnp/008-backport-Use-int64_t-instead-of-long-long.patch
mingw-w64-pupnp/PKGBUILD

I was able to install both 32 and 64 bit versions of package. I have no idea of how to test if they work.
See #6090
Tim S.

pupnp: Update to version 1.12.1

---

mingw-w64-binutils/PKGBUILD

20M instead of 30M.
I didn't increase pkgrel because it doesn't change anything in the products. Next build will benefit from it.

binutils: Use xz instead of bz2

---

mingw-w64-scalapack/0001-fix-fortran-mangling.patch
mingw-w64-scalapack/0002-set-proper-language.patch
mingw-w64-scalapack/0003-force-single-lib.patch
mingw-w64-scalapack/0004-fix-pc.patch
mingw-w64-scalapack/0005-disable-testing.patch
mingw-w64-scalapack/PKGBUILD

Introduced the scalapack package - a MPI-aware parallel lapack.

New package: scalapack

---

mingw-w64-coin/PKGBUILD
mingw-w64-coin/coin-4.0.0-use-cpack-off.patch
mingw-w64-soqt/PKGBUILD
mingw-w64-soqt/soqt-1.6.0-build-tests-on.patch
mingw-w64-soqt/soqt-1.6.0-use-cpack-off.patch

soqt: New package

---

mingw-w64-ffmpeg/PKGBUILD

Adds `libdav1d` as decoder option for av1

FFmpeg: Add dav1d

---

mingw-w64-msgpack-c/PKGBUILD

This updates msgpack-c to 3.3.0.

msgpack-c: update to 3.3.0

---

mingw-w64-libntlm/PKGBUILD

libntlm: update to 1.6

---

mingw-w64-libaacs/PKGBUILD

This updates libaacs to 0.10.0.

libaacs: update to 0.10.0

---

mingw-w64-ngspice/PKGBUILD

See release notes on http://ngspice.sourceforge.net/news.html

ngspice: Bump pkgver to 32

---

mingw-w64-ffmpeg/PKGBUILD

move aom to depends because we link dynamically now

ffmpeg: Update to 4.3

---

mingw-w64-gphoto2/PKGBUILD

gphoto2: add readline dependency

---

mingw-w64-helics/PKGBUILD

update HELICS to version 2.5.2

update HELICS to version 2.5.2

---

mingw-w64-go/PKGBUILD

Signed-off-by: Eric Lagergren <elagergren@spideroak-inc.com>

go: Update to 1.14.4

---

mingw-w64-aom/PKGBUILD

https://bugs.chromium.org/p/aomedia/issues/detail?id=2743#c5

aom: switch to new release tarball

---

mingw-w64-cargo-c/PKGBUILD
mingw-w64-cargo-c/fix-append_to_destdir.patch
mingw-w64-rav1e/PKGBUILD

"An AV1 encoder focused on speed and safety"

Add rav1e and cargo-c

---

mingw-w64-python-cx_Freeze/PKGBUILD

Hi, I'm a new maintainer of cx_Freeze. The URLs updated too.

python-cx_Freeze: Update to 6.2

---

mingw-w64-clang/0013-Add-Z3-to-system-libraries-list-if-enabled.patch
mingw-w64-clang/0106-fix-libunwind-extension.patch
mingw-w64-clang/0301-Fix-def-file-exporting-of-symbols-containing-periods.patch
mingw-w64-clang/0600-unwind-rename-__personality_routine-to-_Unwind_Personality_Fn.patch
mingw-w64-clang/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/6422
Fixes https://github.com/msys2/MINGW-packages/issues/6605
Fixes https://github.com/msys2/MINGW-packages/issues/6607
Libc++ build is based on scripts from https://github.com/mstorsjo/llvm-mingw

Few LLVM fixes

---

mingw-w64-nana/PKGBUILD

Already tested. Build project without any issues.

nana: Update to v1.7.4 (pkgver + sha256sums)

---

mingw-w64-innoextract/0001-fix-segfault-windows.patch
mingw-w64-innoextract/PKGBUILD

Related to:
https://github.com/dscharrer/innoextract/issues/76
https://github.com/dscharrer/innoextract/issues/99
https://github.com/dscharrer/innoextract/pull/114

Fix innoextract windows package.

---

mingw-w64-libproxy/008-fix-buffer-overflow.patch
mingw-w64-libproxy/PKGBUILD

https://github.com/libproxy/libproxy/pull/126

libproxy: Add new patch to fix buffer overflow

---

.github/workflows/main.yml

ci: bump msys2/setup-msys2 to v2

---

mingw-w64-gtkwave/PKGBUILD

gtkwave: update to 3.3.105

---

mingw-w64-libidn/0004-nfkc.c-Fixed-invalid-var-types.patch
mingw-w64-libidn/PKGBUILD

libidn: update to 1.36

---

mingw-w64-bmake/0004-add-windows-draft-configs.patch
mingw-w64-bmake/PKGBUILD

Otherwise any library builds will fail - our LD don't support -Bforcearchive.

Fix bmake package: Add Windows draft configs in mk/sys directory.

---

mingw-w64-gtk2/0023-gcc10-fix.patch
mingw-w64-gtk2/PKGBUILD

See https://gitlab.gnome.org/GNOME/gtk/-/issues/2958

gtk2: fix the build with gcc10

---

mingw-w64-json-c/002-library-version.patch
mingw-w64-json-c/PKGBUILD

json-c: update to 0.15

---

mingw-w64-harfbuzz/PKGBUILD

revert the cairo dep change since it's now fixed upstream

harfbuzz: Update to 2.7.0

---

mingw-w64-pelican/PKGBUILD
mingw-w64-pelican/pelican-i686.install
mingw-w64-pelican/pelican-x86_64.install

[Pelican](https://github.com/getpelican/pelican) is a useful static site generator.
Depend on:

pelican: New package

---

mingw-w64-gr/PKGBUILD

gr: Update to 0.51.2

---

mingw-w64-avr-binutils/01-avr-size.patch
mingw-w64-avr-binutils/PKGBUILD

Binutils targeting Atmel AVR microcontrollers.

New package: avr-binutils 2.35

---

mingw-w64-uncrustify/0001-cmake-install-docs.patch
mingw-w64-uncrustify/PKGBUILD

This is like clang-format tool. This is used in some project development, for example libmicrohttpd, openscad etc.

uncrustify: add package

---

mingw-w64-jq/PKGBUILD

jq: add missing dep on libwinpthread

---

mingw-w64-hub/PKGBUILD

Long time user, first time contributor... 
Please let me know if I screwed up!

hub 2.14.2

---

mingw-w64-fontconfig/0008-fix-font-search.patch
mingw-w64-fontconfig/PKGBUILD

fontconfig: backport upstream patch

---

mingw-w64-cpputest/PKGBUILD

Description: Unit testing and mocking framework for C and C++ (mingw-w64)
Fixes #6822

cpputest: add package

---

mingw-w64-mpc/PKGBUILD

mpc: update to 1.2.0

---

mingw-w64-curl/PKGBUILD

curl: update to 7.72.0

---

mingw-w64-sqlite3/PKGBUILD

This updates sqlite3 to 3.33.0.

sqlite3: update to 3.33.0

---

mingw-w64-libgsf/PKGBUILD
mingw-w64-libgsf/fix-windows-build.patch

This updates libgsf to 1.14.47.

libgsf: update to 1.14.47

---

mingw-w64-catch/PKGBUILD

catch: update to 2.13.0

---

mingw-w64-cfitsio/PKGBUILD
mingw-w64-cfitsio/mingw-cmake.patch

cfitsio: update to 3.48

---

mingw-w64-avr-binutils/PKGBUILD
mingw-w64-avr-gcc/PKGBUILD
mingw-w64-avr-gdb/PKGBUILD
mingw-w64-avr-libc/PKGBUILD

And also just tidying up the PKGBUILDs a little :)

Add package group mingw-w64-avr-toolchain

---

mingw-w64-binutils/0320-aslr-compat-base-addr.patch
mingw-w64-binutils/PKGBUILD

binutils: move the base addr above 4gb so we get full ASLR support if enabled

---

mingw-w64-wslay/PKGBUILD

Changes:
* Add verbose option in autoreconf command.
* Add quotes to source and build directories path.
* Make all recipes including man pages.
* Add the make dependencies required to make man pages, e.g. python-sphinx.
* Add a dirty hack to copy conf.py file to source directory.

wslay: update to 1.1.1

---

mingw-w64-groonga/PKGBUILD

We updated Groonga version to the latest.
Modify of #6783 has not been merged to master yet. So, this PR includes #6783.

groonga: Update to 10.0.6

---

mingw-w64-arm-none-eabi-binutils/PKGBUILD

Technically a new package, as it's not actually in the pacman repo.

Update arm-none-eabi-binutils to 2.35

---

mingw-w64-enchant/PKGBUILD

This updates enchant to 2.2.10.

enchant: update to 2.2.10

---

mingw-w64-openlibm/PKGBUILD

This updates openlibm to 0.7.1.

openlibm: update to 0.7.1

---

mingw-w64-freeimage/PKGBUILD
mingw-w64-freeimage/freeimage-libraw-0.20.patch
mingw-w64-imagemagick/PKGBUILD

Rebuilds for libraw

---

mingw-w64-scalapack/0004-fix-pc.patch
mingw-w64-scalapack/PKGBUILD

Fixed the extraneous dependency on lapack in the .pc file since the openblas itself provides this functionality.

scalapack: .pc dependency fix

---

mingw-w64-libgd/PKGBUILD
mingw-w64-libgd/upstream-622.patch

libgd: fix gd format support; switch to ninja

---

mingw-w64-python/PKGBUILD
mingw-w64-tk/009-esp-pointer-truncation.patch
mingw-w64-tk/010-rip-relative-address.patch
mingw-w64-tk/PKGBUILD

tk: fix issues on x64 with addresses over 4GB.

---

mingw-w64-gr/PKGBUILD

gr: Update to 0.52.0

---

mingw-w64-libheif/PKGBUILD
mingw-w64-libheif/initialize-img_format-and-fix-warnings.patch

libheif: update to 1.8.0

---

mingw-w64-stlink/PKGBUILD

Firmware programmer for STM32 STLINK v1/v2 protocol

Create stlink PKGBUILD

---

mingw-w64-gspell/PKGBUILD

gspell: Update to 1.8.4

---

mingw-w64-amtk/PKGBUILD

amtk: Update to 5.2.0

---

mingw-w64-gst-plugins-bad/0001-meson-fix-vulkan-detection.patch
mingw-w64-gst-plugins-bad/0002-fix-vulkan-mkenum.patch
mingw-w64-gst-plugins-bad/PKGBUILD
mingw-w64-shaderc/0001-fix-glslang-hlsl-linking-order.patch
mingw-w64-shaderc/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/6961

shaderc: add package, required for gst-plugins-bad

---

mingw-w64-v8/PKGBUILD

Missed a new include directory from the installation.

Add cppgc include directory to instalation

---

mingw-w64-mumps/0001-makefile.inc.patch
mingw-w64-mumps/PKGBUILD

Introduce a package for the MUMPS SLAE solver.
This package builds sequential, OpenMP and MPI library versions for all scalar types [sdcz].

New package: mumps

---

mingw-w64-scour/PKGBUILD

Add 'mv' command for the unusual git version tag.

scour: update to 0.38.1

---

mingw-w64-gdb/PKGBUILD
mingw-w64-gdb/gdb-windows-aslr-2.patch

Caused an error when trying to change the program from within GDB.
Fixes #7004

gdb: additional upstream patch to aslr support.

---

mingw-w64-winpthreads-git/PKGBUILD

Fix libwinpthread ignoring buildflags

---

mingw-w64-ncurses/002-ncurses-config-win-paths.patch
mingw-w64-ncurses/PKGBUILD

So it returns the same things as with pkg-config
Fixes #7025

ncurses: make ncursesw6-config output Windows paths

---

mingw-w64-riscv64-unknown-elf-binutils/PKGBUILD

Based mingw-w64-arm-none-eabi-binutils.

Add riscv64-unknown-elf-binutils

---

mingw-w64-scalapack/PKGBUILD

Made openblas a runtime dependency.

scalapack: dependencies fix

---

mingw-w64-riscv64-unknown-elf-newlib/PKGBUILD

Based mingw-w64-arm-none-eabi-newlib.

Add riscv64-unknown-elf-newlib

---

mingw-w64-cmake/PKGBUILD

not sure if this is wanted (therefore separately from #2513)
also not sure if this works to merge one after the other, but i’d be curious to find out

CMake tests

---

mingw-w64-chicken/PKGBUILD

Rebase of https://github.com/msys2/MINGW-packages/pull/3026

Add chicken scheme port file

---

mingw-w64-extra-cmake-modules/PKGBUILD

Update ECM to 5.74.0

---

mingw-w64-python-imageio/PKGBUILD

As per https://github.com/msys2/MINGW-packages/pull/7045#issuecomment-700726903

python-imageio: patch for freeimage lib search path

---

mingw-w64-librdkafka/PKGBUILD

From https://github.com/edenhill/librdkafka.
Note: the tests fail to load `libstdc++-6.dll`.

Add librdkafka version 1.5.0

---

mingw-w64-attica-qt5/PKGBUILD
mingw-w64-breeze-icons-qt5/PKGBUILD
mingw-w64-karchive-qt5/PKGBUILD
mingw-w64-kcodecs-qt5/PKGBUILD
mingw-w64-kconfig-qt5/PKGBUILD
mingw-w64-kcoreaddons-qt5/PKGBUILD
mingw-w64-kdbusaddons-qt5/PKGBUILD
mingw-w64-kdnssd-qt5/PKGBUILD
mingw-w64-kguiaddons-qt5/PKGBUILD
mingw-w64-kholidays-qt5/PKGBUILD
mingw-w64-ki18n-qt5/PKGBUILD
mingw-w64-kidletime-qt5/PKGBUILD
mingw-w64-kirigami2-qt5/PKGBUILD
mingw-w64-kitemmodels-qt5/PKGBUILD
mingw-w64-kitemviews-qt5/PKGBUILD
mingw-w64-kplotting-qt5/PKGBUILD
mingw-w64-kwidgetsaddons-qt5/PKGBUILD
mingw-w64-kwindowsystem-qt5/PKGBUILD
mingw-w64-solid-qt5/PKGBUILD
mingw-w64-sonnet-qt5/PKGBUILD
mingw-w64-syntax-highlighting-qt5/PKGBUILD
mingw-w64-threadweaver-qt5/PKGBUILD

Update Tier 1 KF5 frameworks to 5.74.0

---

mingw-w64-glib2/0001-Revert-glib-Use-g_getenv-everywhere-instead-of-geten.patch
mingw-w64-glib2/PKGBUILD

upstream issue: https://gitlab.gnome.org/GNOME/glib/-/issues/2225
Fixes #7118

glib: revert commit to fix hang when G_SLICE is set

---

mingw-w64-libdeflate/001-libdeflate-makefile-mingw-fix.patch
mingw-w64-libdeflate/PKGBUILD

This is to support future libtiff etc.
https://gitlab.com/libtiff/libtiff/-/merge_requests/158

libdeflate: New package

---

mingw-w64-libavro/001-libavro-1.10.0-fix-mingw-build.patch
mingw-w64-libavro/PKGBUILD

From https://github.com/apache/avro

Add libavro version 1.10.0

---

mingw-w64-argtable/PKGBUILD
mingw-w64-clustal-omega/PKGBUILD

Adding clustal-omega + dependency

---

mingw-w64-skyr-url/PKGBUILD

A C++ library that implements the [WhatWG URL specification](https://url.spec.whatwg.org/#url-class)
Based on https://aur.archlinux.org/packages/skyr-url-git/ , https://github.com/microsoft/vcpkg/blob/master/ports/skyr-url/portfile.cmake
#6452

New package:  skyr-url 1.7.5

---

mingw-w64-spooles/LICENSE
mingw-w64-spooles/PKGBUILD
mingw-w64-spooles/spooles.patch

Base on: https://aur.archlinux.org/packages/spooles/

Add new package: Spooles

---

mingw-w64-libserdes/001-libserdes-6.2.0-fix-mingw-build.patch
mingw-w64-libserdes/PKGBUILD
mingw-w64-libserdes/queue.h

From https://github.com/confluentinc/libserdes

Add libserdes version 6.2.0

---

mingw-w64-python-aiohttp/PKGBUILD
mingw-w64-python-async_generator/PKGBUILD
mingw-w64-python-dephell-markers/PKGBUILD
mingw-w64-python-dephell-pythons/PKGBUILD
mingw-w64-python-google-cloud-core/PKGBUILD
mingw-w64-python-ruamel.yaml.clib/PKGBUILD
mingw-w64-python-service_identity/PKGBUILD
mingw-w64-python-tabulate/PKGBUILD
mingw-w64-python-tqdm/PKGBUILD

New packages:
- python-async_generator
- python-dephell-markers
- python-dephell-pythons
- python-google-cloud-core
- python-ruamel.yaml.clib
- python-service_identity
- python-tabulate
Updated:
- python-aiohttp 3.7.1
- python-tqdm 4.51

More OpenAI dependencies ("dep hell" indeed, lol)

---

mingw-w64-qrupdate/PKGBUILD

qrupdate: cleanup, don't depend on svn, rebuild

---

mingw-w64-clang/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/7170

Link to libstdc++ instead of libc++

---

mingw-w64-libassuan/PKGBUILD

This updates libassuan to 2.5.4.

libassuan: update to 2.5.4

---

mingw-w64-darktable/PKGBUILD

darktable: Update to 3.2.1

---

mingw-w64-cjose/001-cjose-0.6.1-fix-mingw-build.patch
mingw-w64-cjose/PKGBUILD

From https://github.com/cisco/cjose

Add cjose version 0.6.1

---

mingw-w64-SDL/0001-sdl-config-win-paths.patch
mingw-w64-SDL/PKGBUILD
mingw-w64-SDL2/005-sdl-config-win-paths.patch
mingw-w64-SDL2/PKGBUILD

sdl(2)-config: return Windows paths

---

mingw-w64-gr/PKGBUILD

gr: Update to 0.53.0

---

mingw-w64-nanovg/PKGBUILD

bin the commit. There are no tags/releases, so that's all we can do.

nanovg: move to "stable"

---

mingw-w64-precice/PKGBUILD

https://precice.discourse.group/t/precice-and-mingw-packages/382/2

precice: Update PKGBUILD

---

mingw-w64-opencascade/PKGBUILD

1. Switch to ninja
2. Change order Shared <-> Static
3. Add flag: -DINSTALL_DIR_LAYOUT=Unix; repair install dir
4. Add optdepends

opencascade: Update PKGBUILD

---

mingw-w64-rtmidi/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/7265

rtmidi: Add package

---

mingw-w64-darktable/PKGBUILD
mingw-w64-darktable/ninja-build-fixes.patch

darktable: build with ninja

---

mingw-w64-ode/PKGBUILD

Adds a new package for the Open Dynamics Engine (ODE), a library for physics simulation and collision detection.

ode: Add package

---

mingw-w64-gnat_util/PKGBUILD
mingw-w64-gnatcoll/PKGBUILD
mingw-w64-gnatcoll/gmp.gpr
mingw-w64-gnatcoll/iconv.gpr
mingw-w64-gprbuild/0001-remove-binder-option.patch
mingw-w64-gprbuild/PKGBUILD
mingw-w64-langkit_support/PKGBUILD
mingw-w64-libadalang/PKGBUILD
mingw-w64-libgpr/PKGBUILD

Add various Ada libraries from AdaCore

---

mingw-w64-gexiv2/001-unicode-filenames.patch
mingw-w64-gexiv2/PKGBUILD

gexiv2: backport unicode filename fixes

---

.github/workflows/main.yml
mingw-w64-pkg-config/PKGBUILD
mingw-w64-pkgconf/PKGBUILD

Switch from pkg-config to pkgconf

---

mingw-w64-ffmpeg/0001-fix-srt.patch
mingw-w64-ffmpeg/PKGBUILD

ffmpeg: fix the build with newer libsrt

---

mingw-w64-graphviz/006-missing-libs.patch
mingw-w64-graphviz/007-broken-freeglut.patch
mingw-w64-graphviz/PKGBUILD

see https://github.com/msys2/MINGW-packages/commit/677cc00cfda2134ca3ab1f94297b681202cd0281#commitcomment-44578969

graphviz: more fixes

---

mingw-w64-ngraph-gtk/PKGBUILD

new upstream release version 6.08.08.

ngraph-gtk: Update to 6.08.08

---

mingw-w64-assimp/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/7360

assimp: Fix include dir in pkgconfig file.

---

mingw-w64-librsvg/PKGBUILD

This updates librsvg to 2.50.2.

librsvg: update to 2.50.2

---

mingw-w64-SDL2/PKGBUILD
mingw-w64-SDL2/SDL2-2.0.12-SDL_DISABLE_WINDOWS_IME.patch

https://github.com/Rust-SDL2/rust-sdl2/issues/1041

SDL_DISABLE_WINDOWS_IME

---

mingw-w64-libtorrent-rasterbar2/PKGBUILD

Following https://github.com/msys2/MINGW-packages/pull/7372, here is my first package pull request ever. @lazka, does it look A-OK to you ?

libtorrent-rasterbar2 package

---

mingw-w64-python-importlib-metadata/PKGBUILD

importlib-metadata: Update to 3.1.1

---

mingw-w64-icestorm/PKGBUILD

This PR adds package `icestorm`: https://github.com/YosysHQ/icestorm

icestorm: add 0.0

---

mingw-w64-gtk3/PKGBUILD

gtk3: Update to 3.24.24

---

mingw-w64-mtn/001-mtn-3.4.0-makefile.patch
mingw-w64-mtn/PKGBUILD

CLI movie thumbnail generator
https://gitlab.com/movie_thumbnailer/mtn/-/wikis/home

new package: mtn

---

mingw-w64-python-gsutil/PKGBUILD
mingw-w64-python-multidict/PKGBUILD
mingw-w64-python-tqdm/PKGBUILD
mingw-w64-python-trimesh/PKGBUILD

Updated:
- python-gsutil 4.56
- python-multidict 5.1
- python-tqdm 4.54.1
- python-trimesh 3.8.18

Openai dep updates

---

mingw-w64-openFPGALoader/PKGBUILD

Replacement for #7351 with a different source fork (a user's, instead of some org's).

openFPGALoader: add ed7e934

---

mingw-w64-tetgen/0001-fix-missing-install.patch
mingw-w64-tetgen/PKGBUILD

Base on: https://aur.archlinux.org/packages/tetgen/

new packages: tetgen

---

mingw-w64-gcc/0022-jit-port-libgccjit-to-Windows.patch
mingw-w64-gcc/0023-gcc-jit-Rename-libgccjit.dll-to-libgccjit-0.dll.patch
mingw-w64-gcc/PKGBUILD

gcc: build libgccjit

---

mingw-w64-lib3mf-1/PKGBUILD

Add lib3mf-1 package

---

mingw-w64-moab/PKGBUILD

https://sigma.mcs.anl.gov/moab-library/
https://bitbucket.org/fathomteam/moab/src/master/

New package: moab

---

mingw-w64-connect/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/7453

connect: Fix upstream source repository link.

---

mingw-w64-riscv64-unknown-elf-gcc/PKGBUILD
mingw-w64-riscv64-unknown-elf-newlib/PKGBUILD

Based on arm-none-eabi-gcc.
Also fixes libgloss_nano.a packaging in newlib.

Add mingw-w64-riscv64-unknown-elf-gcc 

---

mingw-w64-gst-plugins-bad/PKGBUILD
mingw-w64-webrtc-audio-processing/0001-disable-backtrace-exception-handling.patch
mingw-w64-webrtc-audio-processing/0002-pkgconfig-add-winmm.patch
mingw-w64-webrtc-audio-processing/0003-enable-lrint-mingw.patch
mingw-w64-webrtc-audio-processing/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/7327

gst-plugins-bad: Enable webrtcdsp plugin.

---

mingw-w64-python-black/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/7481

python-black: Fix python path in shebang.

---

mingw-w64-drmingw/PKGBUILD
mingw-w64-drmingw/gcc-10.2.0.patch

See: https://github.com/msys2/MINGW-packages/commit/200852c1fe3783876ecafddd4fd736a1d04c7c16#commitcomment-45324831

drwmingw: fix build with gcc 10

---

mingw-w64-cusp/PKGBUILD

Base on: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cusp

New package: cusp

---

mingw-w64-gdbm/PKGBUILD
mingw-w64-gdbm/gdbm-1.15-win32.patch

gdbm: update to 1.19

---

mingw-w64-superlu/0001-pc-fix.patch
mingw-w64-superlu/PKGBUILD
mingw-w64-superlu/all.tcl
mingw-w64-superlu/superlu.test
mingw-w64-superlu/tclbuildtest.tcl

Introduce the SuperLU sparse direct linear solver.

New package: superlu

---

mingw-w64-python-manimpango/PKGBUILD

Add manimpango, later used for [`manim`](https://github.com/manimcommunity/manim) as a dependency.

Add manimpango

---

mingw-w64-tklib-git/PKGBUILD
mingw-w64-tklib/PKGBUILD

Hope this is the right procedure for requesting a rebuild of a -git package.
Thanks.

tklib: rebuild

---

mingw-w64-tepl/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/7556

tepl: Update to 5.0.1

---

mingw-w64-libheif/002-pkg-config-add-dav1d-rav1e.patch
mingw-w64-libheif/PKGBUILD

* Fixes https://github.com/msys2/MINGW-packages/issues/7554
* Copied from this pull request https://github.com/strukturag/libheif/pull/408

libheif: Add dav1d and rav1e in pkgconfig file.

---

mingw-w64-nimble/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/7585

nimble: Update to 0.12.0

---

mingw-w64-libbotan/PKGBUILD

See https://github.com/randombit/botan/issues/2582.

libbotan: Disable thread_utils.

---

mingw-w64-mathgl/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/7636

mathgl: Enable various cmake build options.

---

mingw-w64-python-nuitka/PKGBUILD
mingw-w64-python-rsa/PKGBUILD
mingw-w64-python-tqdm/PKGBUILD
mingw-w64-youtube-dl/PKGBUILD

https://github.com/naveen521kk/msys2-updator got a small dependency resolver.

Update multiple packages

---

mingw-w64-serial-studio/PKGBUILD

This PR adds [Serial-Studio/Serial-Studio](https://github.com/Serial-Studio/Serial-Studio): a "*multi-purpose serial data visualization & processing program*".

serial-studio: add 1.0.8

---

mingw-w64-python-lark-parser/PKGBUILD
mingw-w64-python-tomlkit/PKGBUILD

Useful for python projects using PEP517, eg poetry.

 Add python-lark-parser and python-tomlkit 

---

mingw-w64-python-backcall/PKGBUILD
mingw-w64-python-fonttools/PKGBUILD
mingw-w64-python-wcwidth/PKGBUILD

python-fonttools: update to 4.18.2
python-wcwidth: update to 0.2.5
python-backcall: update to 0.2.0

update python-fonttools python-wcwidth python-backcall

---

mingw-w64-python-colorama/PKGBUILD
mingw-w64-python-ipython/PKGBUILD
mingw-w64-python-jedi/PKGBUILD
mingw-w64-python-prompt_toolkit/PKGBUILD
mingw-w64-python-ptyprocess/PKGBUILD
mingw-w64-python-pygments/PKGBUILD
mingw-w64-python-sympy/PKGBUILD
mingw-w64-python-traitlets/PKGBUILD
mingw-w64-python-virtualenv/PKGBUILD

- mingw-w64-python-colorama
- mingw-w64-python-ipython
- mingw-w64-python-jedi
- mingw-w64-python-prompt_toolkit
- mingw-w64-python-ptyprocess
- mingw-w64-python-pygments
- mingw-w64-python-sympy
- mingw-w64-python-traitlets
- mingw-w64-python-virtualenv
Dependencies are checked automatically...

update python packages

---

mingw-w64-python-attrs/PKGBUILD
mingw-w64-python-iniconfig/PKGBUILD
mingw-w64-python-more-itertools/PKGBUILD
mingw-w64-python-py/PKGBUILD
mingw-w64-python-pytest-cov/PKGBUILD

update pytest-cov and its dependencies

---

mingw-w64-python-cx_Freeze/PKGBUILD

cx_Freeze 6.5.2 - fix #7480

---

mingw-w64-audaspace/PKGBUILD

It links against the wrong Python

audaspace: rebuild

---

mingw-w64-cas-offinder/PKGBUILD

Homepage: https://github.com/snugel/cas-offinder

Add Cas-OFFinder

---

mingw-w64-python-setuptools-scm/0002-posix-path-to-win32-path.patch
mingw-w64-python-setuptools-scm/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/7262

setuptools-scm: Convert Posix path returned by git to win32 path

---

mingw-w64-ocaml/PKGBUILD

Fixed inconsistent package name without prefix.

ocaml: Fix depends

---

mingw-w64-recode/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/7842

recode: Update to 3.7.8

---

mingw-w64-serial-studio/PKGBUILD

The build error is arbitrary, as commented in #7682.

serial-studio: update to 1.0.11

---

mingw-w64-scour/PKGBUILD

Use only python.exe in shebang.

scour: Update to 0.38.2

---

mingw-w64-tixi3/0001-Fixed-fortran-compilation-if-cflags-were-set-before.patch
mingw-w64-tixi3/0002-Dont-build-and-install-the-examples.patch
mingw-w64-tixi3/0003-Fix-ctypes-DLL-loading-in-Python-3.8-new-policy.patch
mingw-w64-tixi3/PKGBUILD

mingw-w64 package for the small XML library interface tixi (https://github.com/DLR-SC/tixi) for version tixi3

tixi3: new package

---

mingw-w64-tixi/0001-Dont-build-and-install-the-examples.patch
mingw-w64-tixi/0002-Fix-ctypes-DLL-loading-in-Python-3.8-new-policy.patch
mingw-w64-tixi/PKGBUILD

mingw-w64 package for the samll XML library interface tixi (https://github.com/DLR-SC/tixi)

tixi: new package

---

mingw-w64-coin/PKGBUILD

For more info see https://github.com/coin3d/coin/issues/440

coin: Stub for mingw32 segfault

---

mingw-w64-lcms2/PKGBUILD

lcms2: update to 2.12

---

mingw-w64-gst-plugins-bad/0003-enable-mediafoundation-plugin.patch
mingw-w64-gst-plugins-bad/PKGBUILD

Add patch file from upstream's merge request:
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/1882

gst-plugins-bad: Enable mediafoundation plugin.

---

mingw-w64-atkmm236/PKGBUILD
mingw-w64-cairomm16/PKGBUILD
mingw-w64-glibmm268/PKGBUILD
mingw-w64-gtkmm4/PKGBUILD
mingw-w64-pangomm248/PKGBUILD

Related issue https://github.com/msys2/MINGW-packages/issues/7887

gtkmm4: Add package

---

mingw-w64-osgbullet-git/PKGBUILD
mingw-w64-osgearth/PKGBUILD
mingw-w64-osgocean-git/PKGBUILD
mingw-w64-python-pywin32/PKGBUILD
mingw-w64-sip/PKGBUILD

This should be the final PR of the sequence starting with #7931.

use splitpkg template in packages that fail to build

---

mingw-w64-qt5-static/PKGBUILD
mingw-w64-qt5/PKGBUILD

qt5: use splitpkg-wrapper template

---

mingw-w64-gtk4/PKGBUILD

This seems to work now (well vulkan is broken visually, but it builds)
See #7950

gtk4: build with everything enabled

---

mingw-w64-enca/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/7961

enca: Rebuild for recode update.

---

mingw-w64-serial-studio/PKGBUILD

Several enhancements were done upstream for improving UX on MSYS2. See Serial-Studio/Serial-Studio#6.
NOTE: CI failure is expected, it needs to be restarted if it fails.

serial-studio: update to 1.0.16

---

mingw-w64-yosys/PKGBUILD

This is a regular update for picking the changes done during the last 2 months.

yosys: update to 0.9.r10550.4e741adda

---

mingw-w64-openFPGALoader/PKGBUILD

A regular update for picking latest changes: https://twitter.com/GwenhaelG/status/1361218030181711873

openFPGALoader: update to 0.2.5

---

mingw-w64-gr/PKGBUILD

Hi!
gr-0.55.0 package.
Thank you.

gr: Update to 0.55.0

---

mingw-w64-libsidplayfp/PKGBUILD

A library to play Commodore 64 music files

Add libsidplayfp package

---

mingw-w64-winfile/001-winfile-10.1.4.0-fix-mingw.patch
mingw-w64-winfile/PKGBUILD

With patch from https://github.com/microsoft/winfile/pull/262 (by @Biswa96).

winfile: New package

---

mingw-w64-faudio/PKGBUILD

Changes:
* Use Ninja.
* Build static library also.

faudio: Update to 21.03

---

mingw-w64-gst-plugins-bad/PKGBUILD
mingw-w64-spandsp/0001-include-winsock.patch
mingw-w64-spandsp/0002-fix-export-define.patch
mingw-w64-spandsp/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/8040

gst-plugins-bad: Enable spandsp plugin.

---

mingw-w64-libgme/PKGBUILD

Build and install the static gme library too.
Also added zlib dependency.

[libgme] Add static library

---

mingw-w64-sidplayfp/PKGBUILD

The console frontend for libsidplayfp

Add sidplayfp package

---

mingw-w64-libcue/PKGBUILD

Build both static and shared libraries
Switch to Ninja build
Build for release
Install license file

Add libcue static lib

---

mingw-w64-gcc/0202-backport-2939b35.patch
mingw-w64-gcc/PKGBUILD

gcc: backport some more fixes

---

mingw-w64-tiledb/PKGBUILD

@Biswa96 Here is a new package which also depends on aws-sdk-cpp, so we can test if #8070 actually works. You can merge this after or together with #8070. 
cc @ihnorton

New package: TileDB

---

mingw-w64-python-glcontext/PKGBUILD
mingw-w64-python-mapbox-earcut/0001-Add-MINGW-support.patch
mingw-w64-python-mapbox-earcut/PKGBUILD
mingw-w64-python-moderngl/PKGBUILD

Add mapbox_earcut
Add glcontext
Signed-off-by: Naveen M K <naveen@syrusdark.website>

Add moderngl

---

mingw-w64-mpg123/PKGBUILD

mpg123: upgrade to 1.26.5

---

mingw-w64-gr/PKGBUILD

Update gr to 0.56.1

---

mingw-w64-libtomcrypt/0001-makefile-enable-no-undefined.patch
mingw-w64-libtomcrypt/PKGBUILD
mingw-w64-libtommath/0001-makefile-enable-no-undefined.patch
mingw-w64-libtommath/PKGBUILD

* libtommath: Fix pkgconfig file.
* Use .tar.xz source tarball.
* Use upstream PR as patch file to add -no-undefined option.
* Add PREFIX variable with make.
* libtomcrypt: Add package for firebird/libfbclient.

Fix libtommath, add libtomcrypt

---

mingw-w64-python-arrow/PKGBUILD
mingw-w64-python-binaryornot/PKGBUILD
mingw-w64-python-cookiecutter/PKGBUILD
mingw-w64-python-jinja2-time/PKGBUILD
mingw-w64-python-poyo/PKGBUILD
mingw-w64-python-slugify/PKGBUILD

Add python-cookiecutter

---

mingw-w64-python-aiohttp/PKGBUILD
mingw-w64-python-aiohttp/python-aiohttp-brotli.patch
mingw-w64-python-aiohttp/python-aiohttp-chardet-4.patch
mingw-w64-python-aiohttp/python-aiohttp-release-resources-pytest.patch

Check disabled because one test causes it to hang

aiohttp 3.7.4

---

mingw-w64-openFPGALoader/PKGBUILD

Just a regular version update.

openFPGALoader: update to 0.2.6

---

mingw-w64-libspatialite/01-fix-pkgconfig.patch
mingw-w64-libspatialite/PKGBUILD

libspatialite: Update to 5.0.1

---

mingw-w64-libtool/0014-Support-llvm-objdump-f-output.patch
mingw-w64-libtool/PKGBUILD

More info in https://github.com/msys2/CLANG-packages/issues/9

libtool: support `llvm-objdump -f` output

---

mingw-w64-jo/PKGBUILD

jo: add new package

---

mingw-w64-libtool/0014-Support-llvm-objdump-f-output.patch
mingw-w64-libtool/PKGBUILD

Details in https://github.com/msys2/MSYS2-packages/pull/2431

libtool: fix recent patch

---

mingw-w64-curl/PKGBUILD

curl: upgrade to v7.76.1

---

mingw-w64-breakpad-git/PKGBUILD

Depends on https://github.com/msys2/MSYS2-packages/pull/2448

breakpad: pin commit; fix checksums

---

mingw-w64-libsidplayfp/PKGBUILD

Update to last version plus some minor fixes

libsidplayfp: new patch version

---

mingw-w64-python-sphinx/PKGBUILD

Let's hope this works
Fixes #8422

python-sphinx: ignore docutils max version

---

mingw-w64-libgme/PKGBUILD
mingw-w64-libgme/game-music-emu_414e0d993548_22e5c689f33f.patch
mingw-w64-libgme/game-music-emu_86a449eec09d_013d4676c689.patch
mingw-w64-libgme/game-music-emu_b3d158a30492_414e0d993548.patch

Picked the following pull requests, already approved and merged, including a crasher:
https://bitbucket.org/mpyne/game-music-emu/pull-requests/24
https://bitbucket.org/mpyne/game-music-emu/pull-requests/25
https://bitbucket.org/mpyne/game-music-emu/pull-requests/26

libgme: cherry pick a few GBS fixes from upstream

---

mingw-w64-pastix/PKGBUILD
mingw-w64-pastix/metis-fix.patch

https://gitlab.inria.fr/solverstack/pastix/-/issues/53

pastix: fix metis find error

---

mingw-w64-python-google-auth-oauthlib/PKGBUILD

New package: python-google-auth-oauthlib

---

mingw-w64-ghdl/PKGBUILD

A regular update to GHDL, for picking several fixes (synthesis) and enhancements (VHPI and PSL).

ghdl: update to 1.0.0.r199.gda51617a

---

mingw-w64-v8/0000-add-mingw-main-code-changes.patch
mingw-w64-v8/0001-add-mingw-toolchain.patch
mingw-w64-v8/PKGBUILD

This patch includes a change to fetch the v8 source tar
from the github mirror in order to bring build time down.

[v8] Update to stable version 9.0.257.17

---

mingw-w64-headers-git/0003-crt-stdlib-Add-quick_exit-and-at_quick_exit-for-UCRT.patch
mingw-w64-headers-git/PKGBUILD

See https://github.com/msys2/MINGW-packages/issues/8425#issuecomment-826046147

mingw-w64: revert commit breaking the gcc build

---

mingw-w64-verilator/PKGBUILD

verilator: update to 4.202

---

mingw-w64-zeromq/001-testutil_different_signedness-fix.patch
mingw-w64-zeromq/002-unused.patch
mingw-w64-zeromq/PKGBUILD

Added patch to fix compilation with clang.
Added patch stuff from pupnp for ease of patching.

zeromq: update to 4.3.4

---

mingw-w64-akira/PKGBUILD
mingw-w64-elementary-icon-theme/0001-Avoid-xcursorgen.patch
mingw-w64-elementary-icon-theme/0002-hard-copy-symlinks.patch
mingw-w64-elementary-icon-theme/PKGBUILD
mingw-w64-granite/Build-on-windows.patch
mingw-w64-granite/PKGBUILD
mingw-w64-gtk-elementary-theme/PKGBUILD

Packages needed to run Akira on windows 
https://github.com/akiraux/Akira
- Review needed: 
- Is gtk-update-icon-cache needed? I see in other themes
- xcursorgen is not available so some cursors are not generated. Should I include a tar with generated sources (they are png files)

Akira 0.0.14

---

mingw-w64-libirecovery/PKGBUILD

Allows communicating with iOS devices in recovery mode.

libirecovery: add

---

mingw-w64-idevicerestore/010-o2.patch
mingw-w64-idevicerestore/PKGBUILD

doesn't build yet on clang cause of libzip.

idevicerestore: add

---

mingw-w64-libssh/010-lld.patch
mingw-w64-libssh/PKGBUILD

libssh: fix compilation with lld

---

mingw-w64-http-parser/PKGBUILD

http-parser: fix compilation with lld

---

mingw-w64-mxml/0001-autoconf-remove-options-for-clang.patch
mingw-w64-mxml/PKGBUILD

mxml: fix compilation with clang

---

mingw-w64-ccache/010-ucrt.patch
mingw-w64-ccache/PKGBUILD

Disable testing as it has some linking problem.

ccache: fix compilation with clang

---

mingw-w64-cargo-c/PKGBUILD

How can I update the checksum?
https://github.com/lu-zero/cargo-c/releases

cargo-c: update to 0.8.0

---

mingw-w64-assimp/PKGBUILD
mingw-w64-assimp/llvm-rc-workaround.patch
mingw-w64-aws-c-io/0001-include-errno-header.patch
mingw-w64-aws-c-io/PKGBUILD
mingw-w64-aws-sdk-cpp/PKGBUILD
mingw-w64-zziplib/PKGBUILD

Continue from previous pull request https://github.com/msys2/MINGW-packages/pull/8545

zziplib: Create static libraries.

---

mingw-w64-mpg123/PKGBUILD

mpg123: update to latest

---

mingw-w64-filezilla/0002-fix-mingw-compiler-detection.patch
mingw-w64-filezilla/PKGBUILD
mingw-w64-libfilezilla/PKGBUILD
mingw-w64-libgadu/PKGBUILD
mingw-w64-libmicrohttpd/PKGBUILD

Several more were turned up by the last autobuild run

package fixes for clang

---

mingw-w64-python-sphinx/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/8685
backport some commits

python-sphinx: fix with latest version of jinja

---

mingw-w64-hdf4/001-mingw.patch
mingw-w64-hdf4/PKGBUILD

Add -fallow-argument-mismatch flag for fortran compiler.

hdf4: Fix building with gcc 10.

---

mingw-w64-gimp/0006-ucrt-fixes.patch
mingw-w64-gimp/PKGBUILD

crashes on start though, see https://gitlab.gnome.org/GNOME/gimp/-/issues/6836#note_1107613

gimp: fix ucrt build

---

mingw-w64-libgit2-glib/Invalid-path-resolving-relative-path-on-windows.patch
mingw-w64-libgit2-glib/PKGBUILD

Paths with directories need to translate windows to unix paths to work

libgit2-glib: stage/unstage correctly on mingw

---

mingw-w64-partio/010-threads.patch
mingw-w64-partio/PKGBUILD

partio: fix compilation with lld

---

mingw-w64-libtiff/0001-fix-test-newline.patch
mingw-w64-libtiff/PKGBUILD

Also had to fix up some tests as mingw outputs CRLF on stdout

libtiff: update to 4.3.0 and re-enable jbig

---

mingw-w64-libusb/PKGBUILD
mingw-w64-stlink/0001-cmake-find-libusb.patch
mingw-w64-stlink/PKGBUILD

Fixes https://github.com/msys2/MINGW-packages/issues/8704

stlink: Update to 1.7.0

---

mingw-w64-freetype/001-missing-header.patch
mingw-w64-freetype/PKGBUILD

reported upstream: https://gitlab.freedesktop.org/freetype/freetype/-/issues/1058

freetype: fix missing ftcid.h

---

mingw-w64-alure/build.patch
mingw-w64-alure/mingw-build.patch
mingw-w64-alure2/PKGBUILD

fix alure 1 build and move alure2 it's own package

---

mingw-w64-python-distlib/PKGBUILD
mingw-w64-python-pip/0001-use-system-distlib.patch
mingw-w64-python-pip/PKGBUILD

Possibly it should be done for pip also
Fixes: https://github.com/msys2/MINGW-packages/issues/7607

distlib: build executables from source
