- mingw-w64-libthai/PKGBUILD
- mingw-w64-libthai/relocatable.patch
This assumes the DLL is in /bin
> libthai: make relocatable. Fixes #4629

- mingw-w64-kcmutils-qt5/PKGBUILD
- mingw-w64-kdewebkit-qt5/PKGBUILD
Unfortunately, Okteta and KDesignerPlugin can't be built because KDocTools errors with this message, but I was able to build the new KDEWebKit and KCMUtils dependencies
```
kf5.kdoctools: Error: Could not find kdoctools catalogs
```
> Additional KF5 packages

- mingw-w64-qt5-static/0056-qt-5.11-static_icu.patch
- mingw-w64-qt5-static/PKGBUILD
- mingw-w64-qt5/0056-qt-5.11-static_icu.patch
- mingw-w64-qt5/PKGBUILD
remove the s prefix which isn’t present with msys2
remove the d suffix because the debug symbol names are different and it wont link
(probably needs a compile definition to alter the headers)
> build qt5-static with icu

- mingw-w64-qt5-static/0052-qt-5.11-mingw-fix-link-qdoc-with-clang.patch
- mingw-w64-qt5-static/PKGBUILD
- mingw-w64-qt5/0052-qt-5.11-mingw-fix-link-qdoc-with-clang.patch
- mingw-w64-qt5/PKGBUILD
g++ reports libclangEdit as a malformed archive.
Maybe a wrongly coded error message or a bug within the linker but libclangEdit.a seems to have no issue at all by itself.
Linking against the specific file (\<full path\>/libclangEdit.a) solve the issue.
Easily, moving -lclangEdit down within the clang libraries list (this PR) solve the issue as well.
> qt5: fix 32 bit linking with clang 7.0 (#4593)

- mingw-w64-gettext/PKGBUILD
This makes xgettext find its data files (like .its rules)
Fixes #4392
> gettext: Build with --enable-relocatable. Fixes #4392

- mingw-w64-adwaita-icon-theme/PKGBUILD
This updates adwaita-icon-theme to 3.30.1.
> adwaita-icon-theme: update to 3.30.1

- mingw-w64-ngraph-gtk/PKGBUILD
ngraph-gtk: new upstream release (version 6.08.00).
> ngraph-gtk: new upstream release.

- mingw-w64-nghttp2/PKGBUILD
This updates nghttp2 to 1.35.0.
> nghttp2: update to 1.35.0

- mingw-w64-sqlcipher/01-fix_dep.diff
- mingw-w64-sqlcipher/02-fix-tcl-find.patch
- mingw-w64-sqlcipher/PKGBUILD
Upstream update to 4.4.0
Enable more extensions to match the sqlite3 package.
Remove the signing key as it is not used for the github archive.
see https://github.com/sqlcipher/sqlcipher/issues/291
> sqlcipher: update to 4.4.0

- mingw-w64-python-winkerberos/PKGBUILD
- mingw-w64-python-winkerberos/mingw-fixes.patch
This is for oslo-config and requests_kerberos that uses keystoneauth1 as part of an openstack solution.  This is also good in it's own right with requests_kerberos for Kerbose authentication support.  I have to add a lot of packages to fill in some gaps in prerequists that I found using /mingw64/bin/pip2 and /mingw64/pip3.  In addition, I suspect that OpenStack may become a big thing in for some types of cloud computing solutions.  A lot of that is done in python.
> Python winkerberos

- mingw-w64-python-xlwt/PKGBUILD
Library to create spreadsheet files compatible with MS Excel 97/2000/XP/2003 XLS files, on any platform (mingw-w64)
> Add mingw-w64-python-xlwt

- mingw-w64-armadillo/PKGBUILD
- mingw-w64-armadillo/armadillo-i686.install
- mingw-w64-armadillo/armadillo-x86_64.install
When using the unmodified library  I get "fatal error: C:/building/msys64/mingw64/include/hdf5.h: No such file or directory"; when trying to build example code. This patch fixes that error.
Tim S.
> armadillo: Fix hard coded path in armadillo_bits/config.hpp

- mingw-w64-libmypaint-git/PKGBUILD
- mingw-w64-mypaint-git/PKGBUILD
mypaint-git and libmypaint-git are now both at 2.x alpha
libmypaint2 should not conflict with libmypaint1.x
mypaint-git should depend on libmypaint-git and mypaint-brushes2
> mypaint2: prepare for dependency on brush package

- mingw-w64-kicad-doc/PKGBUILD
- mingw-w64-kicad-footprints-git/PKGBUILD
- mingw-w64-kicad-git/PKGBUILD
- mingw-w64-kicad-packages3D-git/PKGBUILD
- mingw-w64-kicad-symbols-git/PKGBUILD
- mingw-w64-kicad-templates-git/PKGBUILD
- mingw-w64-kicad/PKGBUILD
KiCad 5.0.2 Release
- update to version 5.0.2 all kicad footprints tempates symbols packages3D doc
- divided the base and library
- make kicad-meta for complex installation
- update git version, mix git and release allowed
limited build: glm<0.9.9.3, otherwise not compiled, boost 1.69 make problem, but last ok.
> kicad: update to version 5.0.2 & git

- mingw-w64-glib2/0001-Revert-tests-W32-ugly-fix-for-sscanf-format.patch
- mingw-w64-glib2/0001-disable-some-tests-when-static.patch
- mingw-w64-glib2/PKGBUILD
Two patches because we use USE_MINGW_ANSI_STDIO and static builds, both not tested upstream.
> glib: Update to 2.58.2

- mingw-w64-qt5-static/0052-qt-5.11-mingw-fix-link-qdoc-with-clang.patch
- mingw-w64-qt5-static/PKGBUILD
- mingw-w64-qt5/0052-qt-5.11-mingw-fix-link-qdoc-with-clang.patch
- mingw-w64-qt5/PKGBUILD
This is an hack to solve #4593: avoids manual intervention while building qt5 (mainly 32 bit version) with clang 7.0.
This workarounds an issue that seems related to latest binutils: libclangEdit.a archive content is extracted and used instead of the library
> qt5: workaround malformed archive issue on 32 bit linking (qdoc) with clang 7.0 (#4593)

- mingw-w64-darktable/PKGBUILD
Pls note that you need lensfun 0.3.2 to build this darktable. The latest lensfun is not compatible (yet) with darktable
> darktable: Update to 2.6.0

- mingw-w64-argon2/001-mingw-fix-install.patch
- mingw-w64-argon2/002-mingw-fix-src.patch
- mingw-w64-argon2/PKGBUILD
001-mingw-fix-install.patch - integrate my work so that argon2 patch can work on CygWin and MSYS2 if necessary
002-mingw-fix-src.patch - fix various issues in source-code related to prinf formatting, stdcall conventions,
> mingw-w64-argon - 20171227 - various reworks

- mingw-w64-python-bleach/PKGBUILD
- mingw-w64-python-jedi/PKGBUILD
- mingw-w64-python-more-itertools/PKGBUILD
- mingw-w64-python-soupsieve/PKGBUILD
- mingw-w64-python3-entrypoints/PKGBUILD
- mingw-w64-python3-jupyter-notebook/001-jupyter-notebook-MINGW.patch
- mingw-w64-python3-jupyter-notebook/PKGBUILD
- python-bleach: Update to 3.1.0
- python-entrypoints: Update to 0.3
- python-more-itertools: Update to 5.0.0 
- python-jupyter-notebook: Update to 5.7.4
- python-jedi: Update to 0.13.2
- python-soupsieve: Update to 1.7.0
> Python updates

- mingw-w64-vlc/PKGBUILD
libidn is needed from libvlccore.dll
> vlc: add missing dependency libidn

- mingw-w64-nghttp2/PKGBUILD
This updates nghttp2 to 1.36.0.
> nghttp2: update to 1.36.0

- mingw-w64-python-fonttools/PKGBUILD
This updates python-fonttools to 3.36.0.
> python-fonttools: update to 3.36.0

- mingw-w64-python-bcrypt/PKGBUILD
This updates python-bcrypt to 3.1.6.
> python-bcrypt: update to 3.1.6

- mingw-w64-python-setuptools-scm/PKGBUILD
This updates python-setuptools-scm to 3.2.0.
> python-setuptools-scm: update to 3.2.0

- mingw-w64-libgpg-error/PKGBUILD
This updates libgpg-error to 1.34.
> libgpg-error: update to 1.34

- mingw-w64-python-pip/PKGBUILD
Note that an obvious change is that you are now warned that Python 2x will be dropped in 2020.
> mingw-w64-python-pip - 19.0.1 - Update to latest release

- mingw-w64-libgpg-error/PKGBUILD
This updates libgpg-error to 1.35.
> libgpg-error: update to 1.35

- mingw-w64-python-py/PKGBUILD
remove vendered code and depend upon the appropriate packages
Fix tests so a warning is given for failure
Remove whitespace at end of line.
> python-py - 1,7.0 - build changes

- mingw-w64-python-setuptools/PKGBUILD
Remove vendered packages and rely upon packages we have.
added makedepends that match package package dependencies
Fix shebang in easy_install.
Add some lines from Arch.  See comments.
> python-setuptools - 40.7.1 - Update to latest version

- mingw-w64-python-pyopengl/PKGBUILD
* bump version to latest 'stable' release (that's what most Linux distro ship nowadays, not 3.1.0)
* remove unused functions in PKGBUILD
* discard unused SGIX bindings since they cause syntax errors with python3 ('async' is a keyword)
> bump pyopengl version + minor build fixes

- mingw-w64-python-dateutil/PKGBUILD
This updates python-dateutil to 2.8.0.
> python-dateutil: update to 2.8.0

- mingw-w64-python-nvidia-ml/PKGBUILD
The pull requests supersedes this buggy one: https://github.com/Alexpux/MINGW-packages/pull/4595 which you can reject and close.
The main differences are:
- use 2to3 to make the code python3 compatible
- I've actually tested the code on a system with an nvidia card - worked fine with both python2 and python3
- removed unused build code functions
- renamed the package (no need for "XXX-py" suffix when the package is already called "python-XXX")
Note: there is another github project which has ported the code to make it python3 compatible: https://github.com/fbcotter/py3nvml , but they've also added other functions. I felt it safer to go with the "official" nvidia source even if it meant using 2to3 to build with python3.
> add python-nvidia-ml

- mingw-w64-libgphoto2/PKGBUILD
Fixes #4951
Pls note you need doxygen doxygen-1.8.14-3 to build it, building with later/current version of doxygen fails.
> libgphoto2: move libtool to depends

- mingw-w64-poppler/PKGBUILD
download and run tests for poppler - passed at 100%
Set option SPLASH_CMYK
clarrified other CMake options for maintainence reasons
> poppler - 0.74.0 - Update to latest version

- mingw-w64-gcc-git/0019-gcc-8-branch-Backport-patches-for-std-filesystem-from-master.patch
- mingw-w64-gcc-git/PKGBUILD
The upstream code has been rewritten for Windows so this is going to be a huge change.
The patch, as its commit message says, is still generated with the following commands:
```
git cherry-pick 861db1097d3f 2fd48392d0a4 70fea18e0bbb d4fd5c4964cf
git checkout master -- libstdc++-v3/src/filesystem/  \
libstdc++-v3/include/bits/fs_\* libstdc++-v3/include/std/filesystem
```
However, the `git cherry-pick` now results in conflicts. Because all filesystem files will be overwritten by the `git checkout` anyway, the working tree is accepted (despite conflict markers) blindly with `git add -A && git cherry-pick --con`.
> gcc-git: Update filesystem patch.

- mingw-w64-libnfs/2.0.0-no-unefined.patch
- mingw-w64-libnfs/PKGBUILD
This updates libnfs to 4.0.0. Executables are also fixed to depend on the current dll version number.
> libnfs: update to 4.0.0

- mingw-w64-pango/0001-pango.pc-Make-gobject-2.0-a-non-private-requirement.patch
- mingw-w64-pango/PKGBUILD
Patch from upstream master
Fixes #4830
> pango: fix .pc file missing dependency on gobject

- mingw-w64-cmake/0001-Windows-Add-missing-stringapiset.h-include.patch
- mingw-w64-cmake/0004-Implement-Qt5-static-plugin-support.patch
- mingw-w64-cmake/0007-Do-not-generate-import-libs-for-exes.patch
- mingw-w64-cmake/0008-Output-line-numbers-in-callstacks.patch
- mingw-w64-cmake/PKGBUILD
I've ported the patches, as best I could. It compiles.
Now someone just needs to test it, to check if it works correctly. (how do you [test](https://github.com/Alexpux/MINGW-packages/issues/4866#issuecomment-454326420) it?)
@mingwandroid
@alexpux 
@JPeterMugaas ([ref](https://github.com/Alexpux/MINGW-packages/pull/4863))
(Perhaps review and tips/hints)
To apply the patches to the cmake-git-source (in case you want that), do this:
```bash
ls 000*   # view patches here
git clone --depth 1 --branch v3.13.3 https://gitlab.kitware.com/cmake/cmake.git cmake_3.13.3
cd                                                                              cmake_3.13.3
for x in ../000*; do
echo $x
git apply $x
echo ""
done
git diff  # view a single big patch
```
> [mingw-w64-cmake] port patches to cmake 3.13.3

- mingw-w64-cmake/PKGBUILD
- mingw-w64-libssh/PKGBUILD
Update cmake to 1.13.4 - This fixes an issue with Doxygen build module.
Update libssh to 0.8.7 - update to altest version and run some tests.
> Update both cmake and libssh.

- mingw-w64-python-cffi/PKGBUILD
While scanning new commits, I noticed `sha256sum` wasn't updated for this package, see e.g. #3785. The source that was downloaded depended entirely on `_revision`, which had never been changed in PKGBUILD, so an incorrectly labelled 1.10.0 is all that was ever pushed to repo.
The revision code is still needed due to the tarball's path structure. Changing the downloaded source to a tagged version prevents future updates from building unless `_revision` is updated along with `pkgver`.
> python-cffi: fix source download and rebuild

- mingw-w64-clblast/PKGBUILD
- mingw-w64-opencl-icd-git/01-OpenCL-icd-mingw.patch
- mingw-w64-opencl-icd-git/PKGBUILD
Two packages:
* **OpenCL-ICD**: this is an OpenCL ICD Loader, it compiles and installs an OpenCL shared and static library, subsequent OpenCL based libraries can link to the static version (this is also useful for Appveyor CI, which does not have OpenCL ICD at all).
* **CLBlast** package itself
> New package: CLBlast

- mingw-w64-mesa/PKGBUILD
Tests I made indicate that '${MINGW_PACKAGE_PREFIX}-clang' on its own encapsulates '${MINGW_PACKAGE_PREFIX}-gcc' and '${MINGW_PACKAGE_PREFIX}-zlib'.
Flex and bison are required. patch is used inside PKGBUILD so it has to be added too.
> mingw-w64-mesa: Clean-up dependencies and add a new GPG key

- mingw-w64-gdk-pixbuf2/PKGBUILD
This updates gdk-pixbuf2 to 2.38.1.
> gdk-pixbuf2: update to 2.38.1

- mingw-w64-double-conversion/PKGBUILD
This updates double-conversion to 3.1.2.
> double-conversion: update to 3.1.2

- mingw-w64-nghttp2/PKGBUILD
This updates nghttp2 to 1.37.0.
> nghttp2: update to 1.37.0

- mingw-w64-cmake/PKGBUILD
when running under mingw64.exe/mingw32.exe the pathes from the environment are
transformed into Windows pathes. As a result PKG_CONFIG_PATH because a Windows
path. When passed to the non-mingw pkg-config the path becomes invalid and is
not used properly.
To solve this the mingw pkg-config must be installed. It works with Windows
pathes as expected.
As a background to this issue, this was originally reported to cmake:
https://gitlab.kitware.com/cmake/cmake/issues/18980
> have the mingw64 pkg-config installed with cmake

- mingw-w64-python-xpra/PKGBUILD
For more information, see [xpra.org](https://xpra.org) and in particular this ticket: [1883: packaging for mingw64 / MSYS2](https://xpra.org/trac/ticket/1883)
> add mingw-w64-python-xpra

- mingw-w64-onigmo/PKGBUILD
Onigmo is a regular expressions library forked from Oniguruma. 
This package is different from Oniguruma.
> Add mingw-w64-onigmo package

- mingw-w64-corrade/PKGBUILD
- mingw-w64-magnum-integration/PKGBUILD
- mingw-w64-magnum-plugins/PKGBUILD
- mingw-w64-magnum/001-magnum-2019.01-fix-flextvk-on-i686.patch
- mingw-w64-magnum/PKGBUILD
[Magnum](https://magnum.graphics/) is a lightweight and modular C++ graphics middleware.
It depends on [Corrade](https://magnum.graphics/corrade/), a C++ utility library.
Also provided are plugins for Magnum, providing support for many audio, image, and scene formats.
I created the `PKGBUILD` files based on the official Arch Linux `PKGBUILD`s, and I built and tested them on both `MINGW32` and `MINGW64` shells.
@mosra, the creator of Corrade and Magnum, allowed me to submit the files to the MSYS2/MinGW repo in his stead.
> Add PKGBUILDs for Corrade and Magnum

- mingw-w64-libmatroska/PKGBUILD
This updates libmatroska to 1.5.0. The new version requires libebml version 1.3.7.
> libmatroska: update to 1.5.0

- mingw-w64-python3/0000-make-_sysconfigdata.py-relocatable.patch
- mingw-w64-python3/PKGBUILD
- mingw-w64-python3/smoketests.py
Add code at the end of `_sysconfigdata.py` that modifys `build_time_vars` at
module load time with python syntax.
Remove all the sed replaces from PKGBUILD because its hard to review and prone to breakage
Finally a test is added to detect syntax errors next time early on
Fixes https://github.com/msys2/MINGW-packages/issues/5048
> python3: Improve patching _sysconfigdata.py

- mingw-w64-mesa/PKGBUILD
- mingw-w64-mesa/msys2-mingw_w64-fixes.patch
as it's not used by MSYS2 Mingw-w64 build and its days are numbered anyway.
> mesa: Don't bother patching autools stuff

- mingw-w64-unbound/PKGBUILD
This updates unbound to 1.9.1.
Libtool is added to makedepends to allow build to succeed.
> unbound: update to 1.9.1

- mingw-w64-libgpg-error/PKGBUILD
This updates libgpg-error to 1.36.
> libgpg-error: update to 1.36

- mingw-w64-gdb-git/PKGBUILD
> gdb-git: Upgrade to track `gdb-8.3-branch`.

- mingw-w64-lib3mf/PKGBUILD
- mingw-w64-lib3mf/install_component.patch
Lib3MF is the reference implementation of the 3D Manufacturing Format file standard http://3mf.io (https://github.com/3MFConsortium/lib3mf)
Required for example openscad. Split packages on bin/dll and devel. Patch CMakeLists for this.
> Lib3mf: Add to version 1.8.1

- mingw-w64-libssh2/PKGBUILD
This updates libssh2 to 1.8.2.
> libssh2: update to 1.8.2

- mingw-w64-leptonica/PKGBUILD
This updates leptonica to 1.78.0. The pkg-config file is also fixed.
> leptonica: update to 1.78.0

- mingw-w64-openjpeg2/0002-cmake-files-destination.patch
- mingw-w64-openjpeg2/0003-versioned-dlls.mingw.patch
- mingw-w64-openjpeg2/0004-mingw-disable-java.patch
- mingw-w64-openjpeg2/0005-sock-jpip.all.patch
- mingw-w64-openjpeg2/PKGBUILD
Update  patches for new version and add a patch to disable the Java  opj_viewer .jar since we don't support Java.
> mingw-w64-openjpeg2 - 2.3.1 - - Update to latest version

- mingw-w64-libnotify/PKGBUILD
This updates libnotify to 0.7.8.
> libnotify: update to 0.7.8

- mingw-w64-libcroco/PKGBUILD
This updates libcroco to 0.6.13.
> libcroco: update to 0.6.13

- mingw-w64-source-highlight/3.1.4-no-undefined.patch
- mingw-w64-source-highlight/PKGBUILD
- mingw-w64-source-highlight/fix-zsh-highlighting-hangups.patch
0 add3.1.4-no-undefined.patch 0 from Cygwin  to make .DLL's
fix-zsh-highlighting-hangups.patch - from Archlinux to fix a problem they found
fbuild Documentation with Doxygen
fix depends so that building requires ${MINGW_PACKAGE_PREFIX}-ctags and ${MINGW_PACKAGE_PREFIX}-doxygen for documentation.  This is onlyr equired for builds.
> source-highlight-3.1.8-  - various improvements

- mingw-w64-gegl/001-gegl-0.4.14-win32-build.patch
- mingw-w64-gegl/002-gegl-0.4.14-libavutil.patch
- mingw-w64-gegl/PKGBUILD
This new version is required by the latest GIMP 2.10.10. The patches are from upstream, and will not be needed for subsequent releases. I made ffmpeg an optional dependency because it is a large install for just one plugin; also this is what Arch does.
> gegl: Update to 0.4.14, enable ffmpeg plugin

- mingw-w64-python3/2010-configure-have-inet-pton.patch
- mingw-w64-python3/PKGBUILD
- mingw-w64-python3/smoketests.py
HAVE_INET_PTON is hardcoded to 1 in the official Windows build. Since we use autotools
we need to make the check work on Windows.
This makes socket.inet_ntop() and socket.inet_pton() available like with the official build.
Fixes #5184
> python3: fix HAVE_INET_PTON configure check on Windows. Fixes #5184

- mingw-w64-python-lxml/PKGBUILD
This updates python-lxml to 4.3.3.
> python-lxml: update to 4.3.3

- mingw-w64-python-pyparsing/PKGBUILD
This updates python-pyparsing to 2.4.0.
> python-pyparsing: update to 2.4.0

- mingw-w64-python-psycopg2/PKGBUILD
This updates python-psycopg2 to 2.8.2.
> python-psycopg2: update to 2.8.2

- mingw-w64-python-sqlalchemy/PKGBUILD
This updates python-sqlalchemy to 1.3.2.
> python-sqlalchemy: update to 1.3.2

- mingw-w64-python-icu/001-icu-config.patch
- mingw-w64-python-icu/002-fix-mingw-build.patch
- mingw-w64-python-icu/PKGBUILD
This updates python-icu to 2.3. This now requires icu version 64 to build.
> python-icu: update to 2.3

- mingw-w64-adwaita-icon-theme/PKGBUILD
This updates adwaita-icon-theme to 3.32.0.
> adwaita-icon-theme: update to 3.32.0

- mingw-w64-glibmm/PKGBUILD
This updates glibmm to 2.60.0, which now requires a glib2 version of at least 2.60.0.
> glibmm: update to 2.60.0

- mingw-w64-glib2/PKGBUILD
gtk-doc disabled for now because it fails to link if an older glib
is installed.
Caused by https://github.com/msys2/MINGW-packages/issues/5146
> glib2: Update to 2.60.1

- mingw-w64-graphviz/PKGBUILD
Without this package executing `dot -c` results in
Warning: Could not load "C:\msys32\mingw32\bin\libgvplugin_neato_layout-6.dll" - The specified module could not be found.
Warning: Could not load "C:\msys32\mingw32\bin\libgvplugin_neato_layout-6.dll" - The specified module could not be found.
> graphviz: add missing dependency on gts. Fixes #5203

- mingw-w64-gtk3/PKGBUILD
This updates gtk3 to 3.24.8. This also fixes linking with libintl and libiconv libraries.
> gtk3: update to 3.24.8

- mingw-w64-glib-networking/PKGBUILD
This updates glib-networking to 2.60.1.
> glib-networking: update to 2.60.1

- mingw-w64-python3/0565-mingw-add-ModuleFileName-dir-to-PATH.patch
- mingw-w64-python3/PKGBUILD
This is also a problem with meson which tries to execute things in the build
directory using the build directory DLLs by prepending those to PATH.
Since meson uses a Python helper the PATH gets updated to include the
system prefix first which makes things link against the installed libraries
instead and fail because symbols are missing.
One of the reasons why this was added in the first place is that Python loads
C extensions in lib-dynload which then can't find the libraries in prefix
(e.g. "import tkinter") if it isn't in PATH.
By moving the prefix at the end of PATH we make both cases work.
Starting with Python 3.8 C extensions will no longer use PATH for loading
DLL dependencies, see https://github.com/python/cpython/pull/12302
so we will have to look into this again then.
> python3: append prefix to PATH instead of prepending it. Fixes #5146

- mingw-w64-sqlite3/PKGBUILD
This updates sqlite3 to 3.28.0.
> sqlite3: update to 3.28.0

- mingw-w64-meson/PKGBUILD
- mingw-w64-meson/color-term.patch
Only force colors in case we don't have a console attached so we know
we are not running in any of the CMDs.
Fixes #5044
> meson: Update to 0.50.1; don't enable colors in the legacy cmd, fixes #5044

- mingw-w64-tesseract-ocr/PKGBUILD
- mingw-w64-tesseract-ocr/fix_man_page_html.patch
This rebuilds tesseract-ocr against icu 64.1.
> tesseract-ocr: rebuild against icu 64.1

- mingw-w64-ducible/PKGBUILD
Builds from release tags. Please create binary package. Thanks.
> ducible: new package, replaces ducible-git

- mingw-w64-nghttp2/PKGBUILD
This updates nghttp2 to 1.38.0.
> nghttp2: update to 1.38.0

- mingw-w64-libcdio-paranoia/PKGBUILD
This updates libcdio-paranoia to 10.2+2.0.0.
> libcdio-paranoia: update to 10.2+2.0.0

- mingw-w64-python-setuptools/PKGBUILD
- mingw-w64-python2/2030-fix-msvc9-import.patch
- mingw-w64-python2/PKGBUILD
- mingw-w64-python3/2030-fix-msvc9-import.patch
- mingw-w64-python3/PKGBUILD
We currently patch setuptools itself to not import distutils.msvc9compiler,
which fails because it fails to detect the msvc version and falls back to an unsupported
version 6 and raises.
This doesn't help much in case setuptools is installed through pip which doesn't contain
the fix.
This fixes msvc9compiler.py instead to not fail on import but at the compiler instance creation,
i.e. the point where the version is actually used. The setuptools fix remains for now to make
updates easier.
Fixes #5155
> python: better compatibility with unpatched setuptools. Fixes #5155

- mingw-w64-qt-creator/PKGBUILD
This updates qt-creator to 4.9.0, which requires qbs 1.13.0.
> qt-creator: update to 4.9.0

- mingw-w64-geocode-glib/PKGBUILD
This updates geocode-glib to 3.26.1.
> geocode-glib-3.26.1

- mingw-w64-meson/0001-hacky-fix-for-splitting-paths-in-get_compiler_dirs.patch
- mingw-w64-meson/PKGBUILD
meson was using : to split a path list.
See https://github.com/mesonbuild/meson/issues/5386
> meson: fix static linking with system libs

- mingw-w64-itstool/PKGBUILD
- mingw-w64-itstool/pyscript2exe.py
- mingw-w64-itstool/reloc.patch
Various gnome related mingw packages makedepend on it and we only have
a cygwin version atm.
This in combination with the .exe wrapper makes it work with meson.
> Add itstool

- mingw-w64-gettext/200-tools-gnulib-define-installdir.patch
- mingw-w64-gettext/PKGBUILD
relocate() in gnulib-lib needs INSTALLDIR and INSTALLPREFIX to be
Windows paths so it can relocate the input.
Fix by removing INSTALLPREFIX from MSYS2_ARG_CONV_EXCL so it gets
converted when passed to the compiler and pass it to gnulib-lib,
and convert INSTALLPREFIX in gettext-tools/config.h manually.
Fixes #4392 (for real, hopefully)
> gettext: fix tools relocation support

- mingw-w64-ruby-hpricot/PKGBUILD
- mingw-w64-ruby-mustache/PKGBUILD
- mingw-w64-ruby-rdiscount/PKGBUILD
- mingw-w64-ruby-ronn/PKGBUILD
ruby-hpricot - 0.8.6- - final release version of hpricot - required by ruby-ronn
ruby-mustache - 1.1.0 - - New package required by ruby-ronn
ruby-rdiscount - 2.2.0.1 - new package required by ruby-ronn
> ruby-ronn - 0.7.3 and packages itit requires (please see notes)

- mingw-w64-boost/PKGBUILD
This removes the boost cmake config, which causes packages depending on boost to fail during building (cannot detect boost libraries using cmake config).
> boost: remove cmake config

- mingw-w64-unicorn/PKGBUILD
It builds fine with the mingw one.
> unicorn: drop unnecessary msys python2 dependency

- mingw-w64-jq/PKGBUILD
It's only used for the docs, but that needs ruby as well and we didn't build it.
Also update the checksum, the tarball was updated after the release:
https://github.com/stedolan/jq/issues/1773
> jq: drop unnecessary python2 dep

- mingw-w64-gexiv2/PKGBUILD
Also drops unnecessary python2 deps while at it.
#4956
> gexiv2: Update to 0.10.10; drop py2; Re-enable introspection. Fixes #4956

- mingw-w64-yasm/PKGBUILD
It builds fine with mingw python3, so let's use it.
> yasm: use python3 for the build

- mingw-w64-glib2/PKGBUILD
This updates glib2 to 2.60.2.
gtk-doc support is brought back.
> glib2: update to 2.60.2

- mingw-w64-glib-networking/PKGBUILD
This updates glib-networking to 2.60.2.
> glib-networking: update to 2.60.2

- mingw-w64-python-xpra/PKGBUILD
also adds an optional dependency on dnspython to get SSHFP support.
> xpra: update to 2.5.1

- mingw-w64-python3-cmd2/PKGBUILD
This updates python3-cmd2 to 0.9.12. python3-setuptools-scm is added to makedepends to fix build.
> python3-cmd2: update to 0.9.12

- mingw-w64-ruby/PKGBUILD
- mingw-w64-ruby/updpkgprovs
Added provides for the default gems and the bundled gems that are included as well as a script for updating them.  The idea is that as more gems get added, we could track dependencies or gems that are already included.  This is similar to what is being done with perl.  If ruby drops a gem from the bundle or default, we want to know in case a dependency is broken.  Some distributions actually package bundled gems separately.
> ruby - 2.6.3 - added provides.

- mingw-w64-libsoup/PKGBUILD
This updates libsoup to 2.66.2.
> libsoup: update to 2.66.2

- mingw-w64-qemu/PKGBUILD
Fixes issue with SDL2_image.dll not being found at startup.
> mingw-w64-qemu: qemu requires SDL2_image

- mingw-w64-gcc-git/PKGBUILD
Change pkgver function so the pkgver is 9.1.1.d20190515.c10.gbdc6c4d09ec.
And, used "gcc-git" as the git repo directory.
Tim S.
> gcc-git: Change pkgver function

- mingw-w64-x264-git/PKGBUILD
```
$ ntldd x264.exe
KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x01060000)
msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x01200000)
SHELL32.dll => C:\WINDOWS\SYSTEM32\SHELL32.dll (0x01200000)
USER32.dll => C:\WINDOWS\SYSTEM32\USER32.dll (0x01760000)
avcodec-58.dll => C:\msys64\mingw32\bin\avcodec-58.dll (0x01f00000)
avformat-58.dll => C:\msys64\mingw32\bin\avformat-58.dll (0x01200000)
avutil-56.dll => C:\msys64\mingw32\bin\avutil-56.dll (0x01060000)
libffms2-4.dll => not found
liblsmash-2.dll => C:\msys64\mingw32\bin\liblsmash-2.dll (0x01060000)
swscale-5.dll => C:\msys64\mingw32\bin\swscale-5.dll (0x01060000)
```
> x264: add missing ffms2 dep

- mingw-w64-dbus/PKGBUILD
This updates dbus to 1.12.14.
The license array is corrected as well from BSD to GPL and custom.
> dbus: update to 1.12.14

- mingw-w64-python3-sphinx/PKGBUILD
The web interface depends on it
> python3-sphinx: make pkgbase match the dirname

- mingw-w64-python-markdown-math/PKGBUILD
- mingw-w64-python-markdown/PKGBUILD
- mingw-w64-python-markups/PKGBUILD
python-markdown: - 3,1 - update to latest version
python-markdown-math - 0.6 - Math extension for Python-Markdown
python-markups - 3.0.0 - new package - Wrapper around various text markups
> python-package series for python-markups

- mingw-w64-gdb/PKGBUILD
This will remove the new default dependency of boost and source-highlight on GDB 8.3 release, by providing the configure switch `--enable-source-highlight=no` and removing source-highlight from the package dependencies.
Has been tested locally, GDB doesn't crash if boost dlls are missing.
(This time the PR should be correct)
> GDB 8.3 Disable Source Highlight

- mingw-w64-clang/PKGBUILD
Until now libLLVM.dll was built and installed, but not its import
library, which installation was disabled for uknnown reasons.
Fixes #5192.
> llvm: install libLLVM.dll.a

- mingw-w64-glib2/0002-add-and-use-g_get_console_charset.patch
- mingw-w64-glib2/PKGBUILD
Apply upstream patch from
https://gitlab.gnome.org/GNOME/glib/merge_requests/767
Makes sure output is printed to the console in the proper encoding instead of the systems 8-bit ANSII code page (which is used for the ANSII versions of win32 API functions, but usually does *not* match the console encoding, even for cmd.exe).
Works for MSYS2 shell (i.e. mintty) as well as native shells (cmd.exe and powershell).
> glib: fix console output encoding

- mingw-w64-opencv/PKGBUILD
As mentioned in #5361, opencv's python modules require ceres-solver at runtime. Since ceres-solver in turn requires eigen3, I replaced it in optdepends. I did not build test this, so putting it in makedepends as well is an assumption on my part.
> opencv: Update dependencies

- mingw-w64-oce/PKGBUILD
- mingw-w64-oce/unicode.patch
For some reason, opencascade developers thought that MINGW doesn't
support the windows-specific unicode extensions to fopen and friends
and thus use the non-unicode ones, making dealing with non-ASCII
filenames impossible.
This patch enables unicode fopen on MINGW.
> oce: support unicode filenames

- mingw-w64-gdb/PKGBUILD
- mingw-w64-gdb/gdb-8.3-lib-order.patch
Required when building with GCC 9.1, which defaults to version 0x0601.
> gdb: Fix link order on Windows

- mingw-w64-gdb/PKGBUILD
Sneaked in by mistake in 1b05bf47f31384f13a218dc4290cd4274e22889e.
> gdb: Restore default targets

- mingw-w64-python-pluggy/PKGBUILD
> python-pluggy: fix missing dep on python-importlib-metadata

- mingw-w64-lasem/002-no-undefined.patch
- mingw-w64-lasem/PKGBUILD
This updates `lasem` to `0.4.4` and adds a missing shared library.
> lasem: update to 0.4.4

- mingw-w64-flatbuffers/PKGBUILD
If CMAKE_BUILD_TYPE is missing, lib/cmake/flatbuffers/*-noconfig.cmake
are installed. They aren't used from other projects when other
projects use -DCMAKE_BUILD_TYPE=Release. Generally,
-DCMAKE_BUILD_TYPE=Release is used for package build. We already use
it in many packages:
$ grep CMAKE_BUILD_TYPE=Release */PKGBUILD | wc -l
164
If -DCMAKE_BUILD_TYPE=Release is specified,
lib/cmake/flatbuffers/*-release.cmake are installed. They are used from
other projects when other projects use -DCMAKE_BUILD_TYPE=Release.
> flatbuffers: Add missing -DCMAKE_BUILD_TYPE=Release

- mingw-w64-clang/0301-lld-mingw-flags.patch
- mingw-w64-clang/PKGBUILD
Upstream patch: https://reviews.llvm.org/D62876
> Clang/lld: Fix g++ arguments parsing

- mingw-w64-appstream-glib/PKGBUILD
Found when rebuilding annd with the command
"find pkg -type f -exec grep -nH "$(cygpath -m /)" {} \;"
> appstream-glib-0.7.15 - 2 f- fix bad path references in files.

- mingw-w64-python3-mallard-ducktype/PKGBUILD
- mingw-w64-python3-mallard-ducktype/mallard-ducktype3-i686.install
- mingw-w64-python3-mallard-ducktype/mallard-ducktype3-x86_64.install
- mingw-w64-yelp-tools/PKGBUILD
- mingw-w64-yelp-tools/yelp-no-symlinks.patch
- mingw-w64-yelp-xsl/PKGBUILD
python3-mallard-ducktype - 1.0.1 - New package - required to build yelp-xsl and for yelp-tools
yelp-xsl - 3.32.1 - New package - Style-sheets for yelp
yelp-tools - 3.32.1 - New package - Tools for creating Yelp Documentation
> Yelp Tools version for mingw

- mingw-w64-python-importlib-metadata/PKGBUILD
```python
$ python2 -c "import importlib_metadata"
File "<string>", line 1, in <module>
File "C:/msys64/mingw64/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 14, in <module>
from ._compat import (
File "C:/msys64/mingw64/lib/python2.7/site-packages/importlib_metadata/_compat.py", line 19, in <module>
from backports.configparser import ConfigParser
ImportError: No module named configparser
```
> python-importlib-metadata: fix missing configparser dep

- mingw-w64-libde265/001-fix-VPATH.patch
- mingw-w64-libde265/002-use-new-FFMPEG-enum-names.patch
- mingw-w64-libde265/PKGBUILD
- mingw-w64-libheif/PKGBUILD
[Libheif](https://github.com/strukturag/libheif), which requires [libde265](https://github.com/strukturag/libde265), is a codec library for Apple's .heic image files. Packages in mingw-w64 that can use it include GIMP, ImageMagick, and Krita.
@jernejs and @lillolollo may like to know about this being available.
> New packages libheif and libde265

- mingw-w64-osm-gps-map/PKGBUILD
It's pulling in python2/gtk2 but they are not used anymore.
> osm-gps-map: clean up dependencies

- mingw-w64-python-can/PKGBUILD
This updates python-can to 3.2.0.
> python-can: update to 3.2.0

- mingw-w64-libsigc++/PKGBUILD
This updates libsigc++ to 2.10.2.
> libsigc++: update to 2.10.2

- mingw-w64-nghttp2/PKGBUILD
This updates nghttp2 to 1.39.1.
> nghttp2: update to 1.39.1

- mingw-w64-pdcurses/003-fix-_bool-was-not-declared.patch
- mingw-w64-pdcurses/PKGBUILD
Prior to this patch, C++ programs that include pdcurses headers hit this error:
C:/MinGW/MSYS2/mingw64/include/pdcurses/curses.h:67:15: error: _bool was not declared in this scope; did you mean bool?
67 | # define bool _bool
|               ^~~~~
, which has been fixed by <https://sourceforge.net/p/pdcurses/code/ci/8e41f712184156fa4e0966c0c9b3b3fe0dc990be/>.
> pdcurses: Fix `_bool` is not declared error in C++.

- mingw-w64-clang/0306-lld-fix-static-lib.patch
- mingw-w64-clang/PKGBUILD
Upstream patches:
https://reviews.llvm.org/D60628
https://reviews.llvm.org/D58395
https://reviews.llvm.org/D58380
> lld: Fix exception handling in static libraries

- mingw-w64-python-wrapt/PKGBUILD
This updates python-wrapt to 1.11.2.
> python-wrapt: update to 1.11.2

- mingw-w64-gtk3/PKGBUILD
gtk-doc skipped for now since there is some argument passing issue
in meson or gtk-doc where gcc gets wrong args with '-DFOO="string"'.
> gtk3: Port to meson

- mingw-w64-python3/PKGBUILD
I needed to compile a debug-enabled Python 3 for a few client projects. On my machine this ended up failing to compile ctypes properly and thus the `check` phase of the build would fail.
The failure was explained in the build output:
```
building '_ctypes' extension
C:\msys64\mingw64\bin/x86_64-w64-mingw32-gcc.exe -Wno-unused-result -Wsign-compare -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -D_WIN32_WINNT=0x0601 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -D_WIN32_WINNT=0x0601 -DNDEBUG -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wno-cast-function-type -Werror=implicit-function-declaration -DPy_BUILD_CORE_MODULE -IC:/msys64/mingw64/lib/libffi-3.2.1/include -I. …
```
> python3: Fix compilation of ctypes module if dlfcn.h is present.

- mingw-w64-libsass/PKGBUILD
- mingw-w64-sassc/PKGBUILD
This updates libsass and sassc to 3.6.1.
> libsass and sassc: update to 3.6.1

- mingw-w64-gmic/0001-gmic-2.6.4-windows-build.patch
- mingw-w64-gmic/PKGBUILD
To add the G'MIC application to mingw64.
Works on my machine.
I've let some dependencies commented because I haven't found the way to check them: gomp, gdi32, IlmImf & Half.
> added gmic to mingw64

- mingw-w64-libssh2/PKGBUILD
This updates libssh2 to 1.9.0.
> libssh2: update to 1.9.0

- mingw-w64-python-jedi/PKGBUILD
This updates python-jedi to 0.14.0. Source is changed because of upstream using 3rd party typeshed submodule via git.
> python-jedi: update to 0.14.0

- mingw-w64-make/PKGBUILD
- mingw-w64-make/make-4.2.1-Makefile.am-gcc-only-link-libgnumake-1.dll.a.patch
This is my first commit here - I hope that it complies with your requirements and that a new `make` package version could be shipped soon.
* Fixes msys2/MSYS2-packages#978.
* Running `autoreconf -vfi` added.
* The `LDFLAGS` added to `Makefile.am` to have gcc generate `libgnumake.dll.a` are gcc-compliant only, but this should be sufficient for the compilation purposes here.  The flags are copied from `build_w32.bat` of the `make` package `PKGBUILD` calls for a non-`autoconf` build.
* The adjustments might be rolled over to the other `make` packages.  Happy to do that.
> mingw-w64-make(4.2.1): create libgnumake.dll.a when building with autoconf

- mingw-w64-python-mako/PKGBUILD
This updates python-mako to 1.0.13.
> python-mako: update to 1.0.13

- mingw-w64-python-pillow/PKGBUILD
- mingw-w64-python-pillow/dlopen-fix.patch
This updates python-pillow to 6.1.0.
> python-pillow: update to 6.1.0

- mingw-w64-make/PKGBUILD
- mingw-w64-make/make-4.2.1-Makefile.am-gcc-only-link-libgnumake-1.dll.a.patch
- mingw-w64-make/make-check-load-feature.mak
- mingw-w64-make/mk_temp.c
Addition to #5574:
1.  BugFix: Unlock GNU Make's dll load feature in the executable.
2.  BugFix: User-defined dll's for the dll load feature are linked against     the created import library libgnumake-1.dll.a which itself refers   to its associated executable.  The executable name is hardcoded in the     import library.  In order not to break the dll load feature, this implies     for the autotools build branch that in the installation process the     executable must not be renamed and autotools has to create the main     executable with our preferred name  (here: mingw32-make.exe).  Thus     the autotools package is to be informed about the new executable name     if different from 'make'.
3.  Update the build branch using build_w32.bat of the GNU Make package.     The standard …
> mingw-w64-make(4.2.1): bug fix to unlock GNU make's dll load feature (autotools build)

- mingw-w64-wxSVG/PKGBUILD
Simply adds `${MINGW_PACKAGE_PREFIX}-pkg-config` as build dependency.
> wxSVG: Add pkg-config as build dependency

- mingw-w64-gtk3/PKGBUILD
gtk ties the debug options to the build type, but since we use "plain" so that
the the makepkg CFLAGS get used we lose that.
Instead pass the CFLAGS manually.
See https://gitlab.gnome.org/GNOME/gtk/issues/2020
> gtk3: re-enable gtk debug features

- mingw-w64-gtk3/0002-Revert-Quartz-Set-the-popup-menu-type-hint-before-re.patch
- mingw-w64-gtk3/PKGBUILD
revert the upstream commit causing it for starters
See https://gitlab.gnome.org/GNOME/gtk/issues/2019
@Ede123
> gtk3: fix broken menu borders

- mingw-w64-protobuf-c/PKGBUILD
- mingw-w64-protobuf/PKGBUILD
This updates protobuf to 3.9.0 and protobuf-c to 1.3.2.
> protobuf and protobuf-c: update to 3.9.0 and 1.3.2

- mingw-w64-ghex/001-nohelp.patch
- mingw-w64-ghex/002-fread.patch
- mingw-w64-ghex/PKGBUILD
- mingw-w64-ghex/ghex-i686.install
- mingw-w64-ghex/ghex-x86_64.install
This updates ghex to 3.18.4, ports it to meson and removes adwaita-icon-theme from depends because gtk3 already depends on it.
> ghex: update to 3.18.4

- mingw-w64-mono/PKGBUILD
This put's the mono package on par with arch, tested compile on both x86_64 and i686, packages built locally.
> updated mono to 5.20.1.19 package.

- mingw-w64-python3-sphinx/PKGBUILD
> python3-sphinx: Add missing dependency

- mingw-w64-python3/2060-pass-gen-profile-ldflags.patch
- mingw-w64-python3/PKGBUILD
It gives a nice ~15-20% speedup with the pyperformance benchmarks.
Build time increases from ~10 minutes to ~20 minutes (pgo only would be ~15 minutes)
> python3: build with PGO+LTO

- mingw-w64-fontconfig/PKGBUILD
Build fails if [gperf](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-gperf) is not installed.
> fontconfig: add gperf as build dependency

- mingw-w64-pixman/PKGBUILD
Executes `${MINGW_PREFIX}/bin/ninja` instead of `ninja`.
*(not sure if I should add myself as contributor in `PKGBUILD` for such a small change)*
> pixman: ensure use of correct ninja executable

- mingw-w64-python-pip/PKGBUILD
- mingw-w64-python-pip/pip2-i686.install
- mingw-w64-python-pip/pip2-x86_64.install
- mingw-w64-python-pip/pip3-i686.install
- mingw-w64-python-pip/pip3-x86_64.install
This moves pip.exe from python2-pip to python3-pip and makes it the Python 3 version.
See #4950
> python-pip: Make pip.exe the Python 3 version

- mingw-w64-cmake/PKGBUILD
clarrifed dependencies including zstd, ncurses, xz, bzlib2
add support for mingw-w64-emacs including opt-depends
> cmak3 3.15.1 - update to latest version

- mingw-w64-gtk2/0022-icontheme-win32-detect-SVG-files-by-extension.patch
- mingw-w64-gtk2/PKGBUILD
As requested in #4046.
@Alexpux, shouldn't makedepends have `"${MINGW_PACKAGE_PREFIX}-gtk-doc"` instead of `"gtk-doc"`? You switched it long ago in 601f8e45d48f9d767afb2eac2e821b6b7d3f5280, but I'm not sure why, so I'll leave it to you.
> gtk2: add a patch to fix svg file detection

- mingw-w64-pango/002-font-fallback.patch
- mingw-w64-pango/PKGBUILD
This restores the support of optional font fallbacks.
> pango: backport font fallback list fix

- mingw-w64-pngquant/PKGBUILD
New package -  Command-line utility to quantize PNGs down to 8-bit paletted PNGs
> pngquant-2.1- 2.12.5

- mingw-w64-wxSVG/001-wxsvg-1.5.19-pkg-config.patch
- mingw-w64-wxSVG/PKGBUILD
Adds the line `Requires.private: pango, libexif` to `libwxsvg.pc.in` file for correct static linking using `pkg-config`.
**Note:** I also sent a patch/PR upstream.
> wxSVG: patch to add 'pango' & 'libexif' to 'Requires.private' in pkg-config file

- mingw-w64-clang/0305-lld-exception-handling.patch
- mingw-w64-clang/0307-lld-fix-whole-archive.patch
- mingw-w64-clang/PKGBUILD
Upstream patch: https://reviews.llvm.org/D65018
> lld: Backport TLS and whole-archive fixes

- mingw-w64-zeromq/PKGBUILD
mingw-w64-zeromq does include cppzmq but in a very old version. I updated this.
Note that zeromq 4.3.2 was released - but it would need to get patched to be compatible with mingw. So while we wait for this to happen, we can at least get a current version of the cpp wrapper included.
> update included cppzmq to 4.5.0 (zmq still is 4.3.1)

- mingw-w64-libdazzle/0001-windows-Build-pango_font_description_to_css-on-windo.patch
- mingw-w64-libdazzle/PKGBUILD
Needed for gitg 3.32.1 #5647
This is a patched version to access to utils avaliable in libdazzle to convert a font description into a css
> libdazzle: patched 1.0

- mingw-w64-libdazzle/0001-windows-Build-pango_font_description_to_css-on-windo.patch
- mingw-w64-libdazzle/PKGBUILD
Some removed headers are getting in the way, until https://gitlab.gnome.org/GNOME/libdazzle/merge_requests/37 is merged.
This upgrade to version 3.33.4 too
> Remove unneeded headers in libdazzle

- mingw-w64-python3-cmd2/PKGBUILD
This updates python3-cmd2 to 0.9.16.
> python3-cmd2: update to 0.9.16

- mingw-w64-julia/0010-fix-install-dir.patch
- mingw-w64-julia/PKGBUILD
Use libopenblas.dll instead of liblapack.dll; 
Open the test function; 
Install lib{c,llvm}calltest.dll to the bin directory.
> julia: Use libopenblas.dll instead of liblapack.dll; Open the test function; Install lib{c,llvm}calltest.dll to the bin directory.

- mingw-w64-dlib/001-python-binding.patch
- mingw-w64-dlib/PKGBUILD
Hi,
currently there is no python binding in mingw-w64-dlib package.
I think there are 3 different ways to add the missing binding:
1. include them in all inside the existing mingw-w64-dlib packages (e.g. OpenCV does this)
2. create a separate package script to create the individual python binding packages (e.g. zeromq does this)
3. extend the the existing package script to generate individual packages
In this PR I choose the third option, the package script will now create 6 packages:
mingw-w64-i686-dlib
mingw-w64-i686-python2-dlib
mingw-w64-i686-python3-dlib
mingw-w64-x86_64-dlib
mingw-w64-x86_64-python2-dlib
mingw-w64-x86_64-python3-dlib
@peterbud @Alexpux please review and make any changes you want. :)
> dlib: add python-dlib packages

- mingw-w64-groonga/PKGBUILD
001-fix-build.patch is also removed because this build issue was fixed
in upstream.
> groonga: update to 9.0.6

- mingw-w64-spatialite-tools/PKGBUILD
Added readline in spatialite-tools depends.
Binary package rebuild is required to address the readline:7->readline:8 upgrade.
Minor: fixed the license.
Ref: osmcode/libosmium#285.
> spatialite-tools: add readline in depends

- mingw-w64-python2/PKGBUILD
- mingw-w64-python3/PKGBUILD
Python 2 now has idle2, pydoc2 and 2to3-2.7
This also fixes the shebang line of the python3 scripts.
They contain backslashes which we need to escape for sed.
> python: Move idle, pydoc and 2to3 to python3

- mingw-w64-vapoursynth/PKGBUILD
Remove nasm from makedepends.
Ref: https://github.com/vapoursynth/vapoursynth/issues/460#issuecomment-516011740
> vapoursynth: update to R47.2

- mingw-w64-blender/PKGBUILD
Enabled building the bpy.pyd Python module, which should be useful for debugging Blender addons externally, as Blender's script debugging via internal Python console is rather lacking. While this builds, I'm not sure if Blender itself is built with it. Should this be a separate package?
> Build 'bpy' module

- mingw-w64-python3/PKGBUILD
This reverts commit a934b5a5d1d50e71d4f27e3036c0711e16b397e8.
python3 doesn't provide a virtualenv command
> Revert "python3: Replace python3-virtualenv package"

- mingw-w64-gdk-pixbuf2/PKGBUILD
This updates gdk-pixbuf2 to 2.38.2.
> gdk-pixbuf2: update to 2.38.2

- mingw-w64-libjpeg-turbo/PKGBUILD
This updates libjpeg-turbo to 2.0.3.
> libjpeg-turbo: update to 2.0.3

- mingw-w64-cppcheck/0010-change-language-files-path.patch
- mingw-w64-cppcheck/PKGBUILD
- Update 0010-change-language-files-path.patch to 1.89
- Use `FILESDIR` instead of `CFGDIR`, see:
https://github.com/danmar/cppcheck/commit/a17f2a6
- Install .qm files in subfolder 'lang' and not 'cfg/lang' any more.
- Use `MATCHCOMPILER=yes` instead of `SRCDIR=build`, see:
https://github.com/danmar/cppcheck/commit/1b4485a
Fixes warning `Makefile:10:`
`Usage of SRCDIR to activate match compiler is deprecated.`
`Use MATCHCOMPILER=yes instead.`
> cppcheck: update to 1.89

- mingw-w64-mesa/PKGBUILD
- mingw-w64-mesa/msys2-mingw_w64-fixes.patch
Now that Mingw posix flag has been fixed in mesa3d/mesa@88eb2a1f
things can be simplified:
- we no longer need to extra link shell32, uuid, version and ole32;
- we only need to alias mingw platform and link zlib to LLVM.
> Update Mesa3D to 19.2.0

- mingw-w64-libtool/0013-Allow-statically-linking-compiler-support-libraries-.patch
- mingw-w64-libtool/PKGBUILD
The previous patch for the same issue (in
fed7da94ad6ab2ca781ff71ea36564c0f2402f04) works fine for VLC, which
manually overrides "lt_cv_deplibs_check_method=pass_all" in their
configure.ac to get rid of this check in libtool in general.
To fix linking other projects without such existing workarounds
in their configure scripts, we need to patch libtool to allow
statically linking the compiler-rt builtins.
This patch is under discussion upstream at
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27866#65 (but doesn't
seem to be making any progress at the moment).
> Add another libtool patch for picking up compiler-rt builtins from clang

- mingw-w64-nspr/PKGBUILD
- mingw-w64-nspr/nspr-4.10.2_autotools.patch
- mingw-w64-nss/PKGBUILD
This updates nspr and nss to 4.22 and 3.46, respectively.
> nspr and nss: update to 4.22 and 3.46

- mingw-w64-libogg/PKGBUILD
- mingw-w64-libogg/libogg-1.3.4-versioned-dll-cmake.patch
This updates libogg to 1.3.4. Build is switched to cmake.
> libogg: update to 1.3.4

- mingw-w64-qt5/0039-qt-5.4.0-Make-it-possible-to-use-static-builds-of-Qt-with-CMa.patch
- mingw-w64-qt5/0042-qt-5.4.0-static-cmake-also-link-plugins-and-plugin-deps.patch
- mingw-w64-qt5/PKGBUILD
```
CMake Error at D:/msys64/mingw64/lib/cmake/Qt5UiTools/Qt5UiToolsConfig.cmake:283:
Parse error.  Expected a command name, got unquoted argument with text
"!!IF".
```
> qt5: Fix CMake config file regression

- mingw-w64-glib2/0001-gwinhttpvfs-Handle-g_get_prgname-returning-NULL.patch
- mingw-w64-glib2/PKGBUILD
See !5769
Reported upstream: https://gitlab.gnome.org/GNOME/glib/merge_requests/1152
> glib2: Fix critical in g_utf8_to_utf16()

- mingw-w64-ca-certificates/PKGBUILD
- mingw-w64-ca-certificates/certdata2pem.patch
- mingw-w64-ca-certificates/certdata2pem.py
Take certdata2pem.py from the ca-certificates-mozilla package in Arch
and apply our changes in an extra patch to make future updates easier.
I've compared the package results with Python 2 and Python 3 and they
are identical.
> ca-certificates: Port build to Python 3

- mingw-w64-geany-plugins/PKGBUILD
Also remove python2 dep and disable the Python plugin.
It's not ported to gtk3/python3 yet, so it wasn't used anyway.
Make that explicit by disabling it.
> geany-plugins: Update to 1.36; Remove Python 2 dep

- mingw-w64-libevent/PKGBUILD
Python isn't used during the build, only for the installed event_rpcgen.py
script, which supports both Python 2 and 3 for some time now.
And since our switch to python beaing python3 we were usign Python 3 anyway.
> libevent: Port to Python 3

- mingw-w64-libvirt/PKGBUILD
It only needs Python for the build, so move it to makedepends
Also adds -fstack-protector to fix the build, see
https://github.com/msys2/MINGW-packages-dev/pull/6
> libvirt: Port to Python 3

- mingw-w64-libimagequant/PKGBUILD
and remove private header files from package
This now matches the dev package on debian: https://packages.debian.org/sid/amd64/libimagequant-dev/filelist
> libimagequant: Fix include file location

- mingw-w64-corrade/001-corrade-2019.10-fix-corrademain-on-i686.patch
- mingw-w64-corrade/PKGBUILD
Since #5898 was merged too early, here's the patch and updated Corrade PKGBUILD to fix building of CorradeMain on i686.
> Corrade: add a patch to fix CorradeMain build on i686.

- mingw-w64-libvips/PKGBUILD
The following optional dependencies currently fail:
* ~~imagequant due to a missing pkgconfig file. If #5883 and #5888 are applied, libvips builds with it.~~
* matio is disabled due to https://github.com/msys2/MINGW-packages/issues/5758
* orc is disabled due to https://github.com/libvips/libvips/issues/1426
* openslide is not (yet) in MINGW-packages and therefore disabled
These dependencies are noncritical for libvips, so that I think the library can be merged without them enabled.
I tested the command line tools that come with libvips and I tested the package with [ruby-vips](https://github.com/libvips/ruby-vips) and [RubyInstaller](https://rubyinstaller.org).
The compiled tar file is named "vips" only, not "libvips". However I found it more clear to name the package "libvips", since the …
> Add vips image processing library

- mingw-w64-libvips/0001-Fix-dependency-to-introspect-program-on-Windows-MING.patch
- mingw-w64-libvips/PKGBUILD
This could previously fail in make parallel builds due to a wrong
file dependency like so:
```
x86_64-w64-mingw32-gcc -march=x86-64 -mtune=generic -O2 -pipe
-D__USE_MINGW_ANSI_STDIO=1 -pipe  ../../vips-8.8.3/libvips/introspect.c
-o introspect
../../vips-8.8.3/libvips/introspect.c:42:10: fatal error: vips/intl.h:
No such file or directory
42 | #include <vips/intl.h>
|          ^~~~~~~~~~~~~
compilation terminated.
make[3]: *** [<builtin>: introspect] Error 1
```
Fixes #5885
> libvips: Fix build with gobject-introspect enabled

- mingw-w64-yaml-cpp/PKGBUILD
It's not used during the build.
> yaml-cpp: remove the python2 dependency

- mingw-w64-twolame/0002-Add-missing-TL_API.patch
- mingw-w64-twolame/PKGBUILD
patch taken from debian
upstream issue: https://github.com/njh/twolame/pull/94
> twolame: fix missing export of twolame_encode_buffer_float32_interleaved

- mingw-w64-libsass/PKGBUILD
3.6.2 was broken and breaks the gtk build, 3.6.3 works again
> libsass: Update to 3.6.3

- mingw-w64-arrow/PKGBUILD
#5933 was failed by gRPC/Protobuf related crash.
gRPC update by ef22c59a13346fa69f8255b7b02be189803897f0 fixed the failure in #5933.
> arrow: Update to 0.15.1

- mingw-w64-metis/PKGBUILD
This adds PkgConfig support to help the dependant packages such as parmetis.
> metis: PkgConfig support

- mingw-w64-docbook-xml/PKGBUILD
- mingw-w64-docbook-xml/docbook-xml-i686.install
- mingw-w64-docbook-xml/docbook-xml-x86_64.install
- mingw-w64-docbook5-xml/PKGBUILD
- mingw-w64-docbook5-xml/docbook5-xml-i686.install
- mingw-w64-docbook5-xml/docbook5-xml-x86_64.install
- mingw-w64-opengl-man-pages/LICENSE
- mingw-w64-opengl-man-pages/PKGBUILD
- mingw-w64-w3c-mathml2/LICENSE
- mingw-w64-w3c-mathml2/PKGBUILD
- mingw-w64-w3c-mathml2/w3c-mathml2-i686.install
- mingw-w64-w3c-mathml2/w3c-mathml2-x86_64.install
docbook-xml - remove 5.x series (that's a total rewrite)
docbook5-xml - new package that includes docbook 5.0, 5.0.1, and 5.1
w3c-mathml2 - new package MathML XML scheme
opengl-man-pages - new package - opengl documentaiton (uses docbook5-xml, docbook 4.x) and we
Since opengl-man-pages builds, I'm assume that this works as it does use some of the old packaging stuff and I ddidn't see an error when testing xmlcat with the -v parameter.
> docbook package restructuring

- mingw-w64-universal-ctags-git/PKGBUILD
* --enable-iconv is now the default. No need to set it explicitly.
* rst2html3 was renamed to rst2html a few months ago.
> universal-ctags-git: Update to r7242

- mingw-w64-nlohmann-json/PKGBUILD
Rename to `nlohmann-json` to be consistence with Arch [package](https://aur.archlinux.org/packages/nlohmann-json/).
Update to 3.7.3 to fix latest bugs.
> nlohmann_json: Rename to nlohmann-json and update to 3.7.3

- mingw-w64-gtk4/0001-imcontextime-Add-missing-semicolon.patch
- mingw-w64-gtk4/PKGBUILD
Update to 3.96.0. The conflicts with files in gtk3 package are now gone (https://gitlab.gnome.org/GNOME/gtk/commit/5c31c721af45a3cf884575c41c5e14899b3a0c08). Also, the PKGBUILD changed a bit to follow the renaming from GTK+ to GTK.
Other changes:
- Changed to `--buildtype=plain` as done for the gtk3 package
- Disabled the `strip` build option
> Update mingw-w64-gtk4 package to 3.96.0

- mingw-w64-python-xpra/PKGBUILD
- version bump 
- fixes the launch scripts so it will correctly fallback to using the python2 build if that is the only version installed
> xpra 3.0.2

- mingw-w64-wineditline/005-fix-missing-extern-c.patch
- mingw-w64-wineditline/PKGBUILD
Fixes #6008
As I don't know how to integrate SVN sources, I instead supply the patch provided by @olafmandel in the mentioned issue.
> wineditline: Fix missing "extern c" in header

- mingw-w64-gtk3/0001-disable-sass-rebuild.patch
- mingw-w64-gtk3/0003-gtkwindow-Don-t-force-enable-CSD-under-Windows.patch
- mingw-w64-gtk3/PKGBUILD
This re-applies the CSD patch dropped due to a misunderstanding in the last commit.
Because gtk isn't buildable with libsass 3.6.3 due to libsass bugs disable the CSS
regeneration for now and use the one from the tarball.
> gtk3: disable forcing CSD again and skip sass rebuild due to broken libsass

- mingw-w64-python-pyopengl/PKGBUILD
- removes all the workarounds we had added for python 3.8 since those have now been merged
- adds a workaround for the missing `readme.rst` file containing the long description (which is not shown anywhere)
> pyopengl 3.1.3rc1

- mingw-w64-mpv/PKGBUILD
I don't know why, but when we use `pkg-config` of `MSYS2`, building of the package fails.
> mpv: fix build failed

- mingw-w64-mesa/PKGBUILD
- mingw-w64-mesa/llvmwrapgen.sh
In addition to updating to 19.2.6 this PR includes LLVM Meson wrap generator from #5977 with improvement to properly get LLVM RTTI status instead of hard-coding it. I chose to include it as it isn't bound to any Mesa3D version. I thought it's a good idea to get it done early so that switch to Meson later becomes less of a hassle.
Re-spin of #5983
> Mesa3D: Update to 19.2.6 and implement LLVM Meson wrap generator

- mingw-w64-groonga/PKGBUILD
I update Groonga's version in PKGBUILD.
Because upstream was update.
> groonga: update to Groonga 9.1.0

- mingw-w64-libplacebo/PKGBUILD
```
> cygcheck /mingw64/bin/libplacebo-21.dll
C:\msys64\mingw64\bin\libplacebo-21.dll
C:\msys64\mingw64\bin\libSPIRV-Tools.dll
...
> pacman -Qo /mingw64/bin/libSPIRV-Tools.dll
/mingw64/bin/libSPIRV-Tools.dll is owned by mingw-w64-x86_64-spirv-tools 2019.4-1
```
> libplacebo: add spirv-tools dep; increment pkgrel

- mingw-w64-librsvg/PKGBUILD
Primarily to fix https://gitlab.gnome.org/GNOME/librsvg/issues/525
> librsvg: update to version 2.46.4

- mingw-w64-python-xpra/PKGBUILD
simple version bump.
Link to the release notes: [xpra 3.0.3](https://lists.devloop.org.uk/pipermail/shifter-users/2019-December/002451.html)
> xpra 3.0.3

- mingw-w64-spdlog/001-spdlog-1.4.2-include-cassert.patch
- mingw-w64-spdlog/PKGBUILD
This required for binary compatibility since dependency `fmt` package updated.
The patch `001-spdlog-1.4.2-include-cassert.patch` required to fix https://github.com/gabime/spdlog/issues/1340.
> spdlog: Rebuild

- mingw-w64-gmic/0001-gmic-windows-build.patch
- mingw-w64-gmic/PKGBUILD
EDIT: gmic package update. The previous version failed with darktable.
I've tried commit --amend but this was bringing some of your previous changes sig ...
I've created a new commit. I hope that's ok.
> fix patch file - remove -std=c++11 -pedantic for windows

- mingw-w64-vala/002-use_time_s_functions_on_windows.mingw.patch
- mingw-w64-vala/PKGBUILD
Without this patch a simple program like this would not compile in a MINGW environment:
`void main () {
time_t original_time = time_t();
print( Time.local(original_time)
.to_string() );
}
`
> vala: patch for glib-2.0.vapigen that allows proper compilation of Time.local()

- mingw-w64-libmypaint-git/PKGBUILD
- mingw-w64-mypaint-git/PKGBUILD
Switch dependencies from Py2 to Py3 for *-git and libmypaint packages.
Add brush directory fix for the *-mypaint-git build.
Update maintainer contact info.
The Mypaint release package still relies on Py2, but the new release (which does not) should be out in late January.
~~MyPaint builds and runs fine w. Py3 on windows for the most part (the exception is png export, but it should be fixed within a day or two).~~
Edit: Actually, the png export does work, only the tests fail (...)
**Edit:** Alright, let's not update the info in the release packages for now.
> Update MyPaint packages (mypaint/libmypaint)[-git] to use Python 3

- mingw-w64-python3/3000-importlib-bootstrap-path-sep.patch
- mingw-w64-python3/PKGBUILD
- mingw-w64-python3/smoketests.py
The importlib bootstrap code hardcodes the path separators to use
as well (os.path doesn't exist yet). Check for MSYSTEM there and
adjust the separators.
This makes things like `module.__path__` use the same separator in all
places again and for example fixes pytest with MSYSTEM set.
Fixes #6035
> python3: fix wrong path separator in module paths with MSYSTEM set

- mingw-w64-neon/PKGBUILD
- mingw-w64-neon/neon-0.30.2-mingw-w64.patch
This removes the MSYS2 requirement for packages that don't need it.
> neon: Adding neon package to MINGW

- mingw-w64-python-setuptools/PKGBUILD
- mingw-w64-python2-setuptools/0001-mingw-python-fix.patch
- mingw-w64-python2-setuptools/0002-Allow-usr-bin-env-in-script.patch
- mingw-w64-python2-setuptools/0003-MinGW-w64-Look-in-same-dir-as-script-for-exe.patch
- mingw-w64-python2-setuptools/0004-dont-execute-msvc.patch
- mingw-w64-python2-setuptools/0005-execv-warning.patch
- mingw-w64-python2-setuptools/PKGBUILD
- mingw-w64-python2-setuptools/setuptools2-i686.install
- mingw-w64-python2-setuptools/setuptools2-x86_64.install
This adds back a python 2 version of setuptools but with all dependencies vendored
(the upstream default..). To allow users to install Python 2 packages we no longer
have in the repo etc which should help them transitioning.
This also adds conflicts between py2/3 setuptools because of the esy_install rename.
See #4993
> Add back python2-setuptools

- mingw-w64-tcl/004-use-system-zlib.mingw.patch
- mingw-w64-tcl/006-proper-implib-name.mingw.patch
- mingw-w64-tcl/PKGBUILD
- mingw-w64-tk/PKGBUILD
While packaging this warning is show:
==> WARNING: Package contains reference to $srcdir
> tcl, tk: update to 8.6.10

- mingw-w64-python2-pip/PKGBUILD
- mingw-w64-python2-pip/pip2-i686.install
- mingw-w64-python2-pip/pip2-x86_64.install
This adds back a Python 2 version of pip but with all dependencies vendored.
In combination with setuptools this allows users to install Python 2 packages
from pypi.
See #4993
> Add back python2-pip

- mingw-w64-python/0180-MINGW-init-system-calls.patch
- mingw-w64-python/3001-pathlib-path-sep.patch
- mingw-w64-python/PKGBUILD
- mingw-w64-python/smoketests.py
The second commit fixes a pathsep issue with pathlib (which I noticed because pytest has started using pathlib)
> python3: Update to 3.8.1

- mingw-w64-dlib/002-fix-opencv-in-19.19.patch
- mingw-w64-dlib/PKGBUILD
@Alexpux
This is a follow up to #6105. You did not give any reason why you turned down my PR, but I did what you asked me to do: Now dlib release 19.19 is used again and patches (taken from dlib github) are used to fix OpenCV compatibility. That patch can get removed once dlib 19.20 gets released.
I also included changes so the python-dlib package is build instead of python3-dlib.
> dlib: fix compatibility with opencv and drop python 2

- mingw-w64-zeromq/001-mingw-__except-fixes.patch
- mingw-w64-zeromq/PKGBUILD
As stated in the title the package was updated. That patches were taken from zeromq's repo and wont be needed in next release.
-------
Some additional notes:
There are actually 3 ZeroMQ projects:
libzmq (the zeromq C library)
cppzmq (the cpp binding, basically just 2 header files)
pyzmq (the python binding)
MSYS2 provides those in 2 packages:
zeromq = libzmq + cppzmq
python-pyzmq = pyzmq
I think there are some minor problems with this:
- the names of our packages neither match each other nor the names of the original project perfectly
- the zeromq package consists of two original projects, that get updated independently from each other, so we need keep track of both
- the zeromq package does not mention the cppzmq version number anywhere, only that of libzmq
Do you think any of those …
> zeromq: update to libzmq 4.3.2 and cppzmq 4.5.0

- mingw-w64-groonga/PKGBUILD
I update Groonga's version in PKGBUILD.
Because upstream was an update.
> groonga: update to Groonga 9.1.1

- mingw-w64-clang/0010-mbig-obj-for-all.patch
- mingw-w64-clang/0105-build-libclang-cpp-fix.patch
- mingw-w64-clang/PKGBUILD
- enable build of libclang-cpp
- allow multiple definitions while linking as it seems to be multiple definitions in
libLLVM.dll.a and all other libLVM*.a; to handle this properly one would need to
change the way the libs are built
- tested clang/clang++ by building a large project
> reduce mingw-w64-clang package size via dynamic linking #6072

- mingw-w64-clang/0010-mbig-obj-for-all.patch
- mingw-w64-clang/0105-build-libclang-cpp-fix.patch
- mingw-w64-clang/0901-openmp-kpm-lock.patch
- mingw-w64-clang/0902-libomp-weak-mingw.patch
- mingw-w64-clang/PKGBUILD
build clang-openmp library (#6102) 
- use uasm instead of masm to build the libomp .asm file 
- add uasm as dependency to the clang package (needed by openmp) 
- include the header having xbegin on mingw as well 
- don't use weak attribute on mingw 
- sed away the windows like /flag to -flag on the call to uasm
> build clang OpenMP

- mingw-w64-gcc-git/PKGBUILD
The GCC developers decided to migrate to Git, which means the old Git
mirror is now the official repo. The scheme of naming of branches has
changed in this process.
> gcc-git: Sync with the new GCC Git repo

- mingw-w64-rocksdb/PKGBUILD
This compiles rocksdb with RTTI support and in portable mode.
Portable mode is needed because otherwise the resulting binary might be unusable on older processors.
See https://bugs.archlinux.org/task/65093
> rocksdb: Update to 6.5.3 and tweak build settings

- mingw-w64-x264-git/0001-beautify-pc.all.patch
- mingw-w64-x264-git/PKGBUILD
I noticed that the build started failing because the patch no longer applies.
> mingw-w64-x264: fix patch for changes upstream

- mingw-w64-snappy/PKGBUILD
> snappy: update to 1.1.8

- mingw-w64-curl/PKGBUILD
cURL, starting with version 7.58, changed build settings around SSH support so that MinGW builds of cURL made since have scp and scftp protocols support disabled.
This commit re-enabled SSH support for MinGW builds.
Signed-off-by: François-Xavier MAURICARD <fxmauricard@gmail.com>
> mingw-w64-curl: Update PKGBUILD in order to build with libssh2.

- mingw-w64-pycairo/PKGBUILD
- mingw-w64-python2-pycairo/PKGBUILD
Also split the package because Python 2 support was dropped with 1.19
> pycairo: Update to 1.19.0

- mingw-w64-cmake/PKGBUILD
All files in the Modules tree end up packaged in the final build,
including these patch-generated backups.
A *failed* patch will still generate .rej and .orig artefacts, so this
should not introduce any workflow issues for any package developers.
> cmake: Don't generate .orig artefacts from patches

- mingw-w64-mesa/PKGBUILD
- mingw-w64-mesa/llvmwrapgen.sh
This should fix potential missing `libLLVM.dll` related errors with 19.3.2-1 and 19.3.3-1 when mingw-w64-llvm is not installed. Regression caused by #6098. That pull request naturally changed the output of `llvm-config --libnames` to be identical to `llvm-config --link-shared --libnames`.  To adapt to this behavior change, static libraries have to be explicitly requested with `llvm-config --link-static --libnames`. when needed This maintains compatibility with minngw-w64-llvm from before #6098 when `llvm-config --libnames` output matched `llvm-config --link-static --libnames`.
This pull request also adjusts Meson subproject wrap generator for LLVM (`llvmwrapgen.sh`) to lookup both static and shared libraries and flips Meson `--default-library` to `both` as requested a long time ago. It …
> mingw-w64-mesa: Build both static and shared

- mingw-w64-ttfautohint/PKGBUILD
This package is for **ttfautohint**, which is a set of automated hinting tools for TrueType fonts. It allows the user to manipulate the font hinting instructions embedded in TTF files. It is associated with the FreeType project. More information can be found here:
https://www.freetype.org/ttfautohint/
This package installs the following:
* The library and header files
* A command line tool called `ttfautohint.exe`
* A GUI tool called `ttfautohintGUI.exe`
It has the following dependencies:
* FreeType
* HarfBuzz
* Qt
I want to point out that the Qt dependency is quite large, with about a 1 GB download size and a 7 GB installation footprint. The Qt dependency is for the GUI tool only. If the user only wants to use the command line tool or the library, they will still need to have the Qt …
> Add new package mingw-w64-ttfautohint

- mingw-w64-python-importlib-metadata/PKGBUILD
- mingw-w64-python-packaging/PKGBUILD
- mingw-w64-python-pip/PKGBUILD
- mingw-w64-python-setuptools/PKGBUILD
- mingw-w64-python-six/PKGBUILD
- mingw-w64-python-urllib3/PKGBUILD
* python-packaging: Update to 20.1
* python-urllib3: Update to 1.25.8 
* python-six: Update to 1.14.0
* python-importlib-metadata: Update to 1.5.0
* python-setuptools: Update to 45.1.0
* python-pip: Update to 20.0.2
> Various Python updates

- mingw-w64-mecab/PKGBUILD
- mingw-w64-mecab/mecab-i686.install
- mingw-w64-mecab/mecab-x86_64.install
We need to use absolute path in Windows instead of absolute path in
MSYS2.
> mecab: adjust dicdir in mecabrc

- mingw-w64-gdb/PKGBUILD
If GDB is built with --enable-targets=all it should be able to connect
remotely and open core dumps from all target types.
But this change broke it for 32-bit build.
This partially reverts be921a6c47be60e25514032ba53835a98e4d5046.
> GDB: Fix support for 64-bit targets on 32-bit

- mingw-w64-gdb/PKGBUILD
> gdb: add missing dependency on xxhash

- mingw-w64-make/PKGBUILD
- mingw-w64-make/make-4.3_undef-HAVE_STRUCT_DIRENT_D_TYPE.patch
- mingw-w64-make/make-check-load-feature.mak
* mingw-w64-make/PKGBUILD:
- config: set arch to 'i686' 'x86_64', since batch build is supposed
for pure Windows builds.
- prepare: build with batch file build_w32.bat (instead of autotools,
- since autotools approach is not fully supported for Windows builds).
- overwrite default executable name 'gnumake' with 'mingw32-make'.
- cd to src dir of package to apply package patches, since the dir
structure was changed with make version 4.3.
- check: move check section in package to separate function check.
- use overall helper function defining the executable dir.
* mingw-w64-make/make-check-load-feature.mak:
- add CFLAGS the user can pass to the makefile on the command line
- simplify setting of default value of LIBS
> make: Update to 4.3

- mingw-w64-qca-qt5/PKGBUILD
- mingw-w64-qca-qt5/qca-mingw-link-to-release.patch
We only compile in release mode and worse: the Qt library itself is only
available in release mode. So we don't want to link to a (non-existing)
debug-library.
> qca: always link to release library

- mingw-w64-python-cx_Freeze/PKGBUILD
cx_Freeze version 6.1 has hard-coded `libffi-7.dll` in the source:
https://github.com/anthony-tuininga/cx_Freeze/pull/556/commits/648ce78f4bf00bf7e57e6a6558cabe7a419948eb
The problem is that MSYS2 ships `libffi-6.dll` instead.
This pkgrel bump fixes things using sed.
Note: this will break again when libffi is updated to `libffi-7.dll`. Not sure how to deal with this more properly.
> fix version of hard-coded libffi DLL

- mingw-w64-glib2/PKGBUILD
* gtk-doc build is broken, so disabled.
* pkg-config workaround no longer needed with newer meson
> glib: Update to 2.64.0

- mingw-w64-dav1d/PKGBUILD
Based on archlinux's PKBGUILD and also using the meson parts from one from @lazka
The dav1d.exe is linked to libdav1d.dll and works
Do I need a prepare function? I've set it to no-op for now
> dav1d: Add dav1d 0.5.2 PKGBUILD

- mingw-w64-ngraph-gtk/PKGBUILD
new upstream version of ngraph-gtk is released.
> * ngraph-gtk: new upstream release (version 6.08.04).

- mingw-w64-rust/0001-add-missing-libs.patch
- mingw-w64-rust/0004-unbundle-gcc.patch
- mingw-w64-rust/PKGBUILD
WARNING: It won't build if build path is too long.
> Update Rust to 1.41.1

- mingw-w64-gtk3/0004-Disable-low-level-keyboard-hook.patch
- mingw-w64-gtk3/PKGBUILD
The hook is used to intercept keyboard combos so gtk is able to trigger the AeroSnap-like functionality it implements as a replacement for real AeroSnap when client-side decorations (CSD) are used on a window.
However the keyboard hook causes significant performance issues, especially on startup of gtk3 apps (those are system-wide and *not* limited to the gtk3 app itself). Input performance can be continuously degraded for any console application that is attached to the gtk3 app, e.g. debuggers.
Loss of the keyboard combos in CSD windows seems to be acceptable considering the severe functional limitations the hook itself causes.
This is especially true as we [do not use CSD by default](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gtk3/0003-gtkwindow-Don-t-force-enable-CSD- …
> gtk3: disable low level keyboard hook

- mingw-w64-pygobject/PKGBUILD
- mingw-w64-python2-pygobject/PKGBUILD
The devel files move into the Python 3 version, which means using the
C API from Python 2 is no longer supported, kinda, but it will probably work anyway because 3.36 headers still work with Python 2.
Also update the Python 3 version to 3.36.0
> pygobject: Split into a Python 2 and Python 3 package

- mingw-w64-mesa/PKGBUILD
${MINGW_PACKAGE_PREFIX}-gcc requires ${MINGW_PACKAGE_PREFIX}-zlib;
${MINGW_PACKAGE_PREFIX}-zlib requires ${MINGW_PACKAGE_PREFIX}-bzip2
which in turn requires ${MINGW_PACKAGE_PREFIX}-gcc-libs.
> mingw-w64-mesa: Remove unnecessary dependency checks

- mingw-w64-vlc/PKGBUILD
- mingw-w64-vlc/vlc-i686.install
- mingw-w64-vlc/vlc-x86_64.install
Currently, when using the vlc installed by pacman, there's a chance
that vlc will pick the user's installed vlc's plugin instead of the
one installed by pacman
I'm not sure if all of the following are necessary
---
add glew to makedepends to fix missing `GL/glew.h`
Add dav1d as an av1 decoder
Add cyrus-sasl to fix missing `sasl/sasl.h`
Add post-install/upgrade vlc-cache-gen
Without running vlc-cache-gen, vlc complains about:
`main libvlc error: stale plugins cache: modified`
> vlc: Use binary-version to not conflict with a system installed vlc

- mingw-w64-glibmm/PKGBUILD
Fixes a second regression in the 2.64 branch that broke compilation of downstream projects, see https://gitlab.gnome.org/GNOME/glibmm/issues/71.
> glibmm: update to version 2.64.2

- mingw-w64-gspell/PKGBUILD
Note that I’m the upstream maintainer of gspell.
gspell doesn’t use GSettings, and it no longer depends on GtkSourceView
and the libxml2 (these deps were removed in gspell 0.2.2).
> gspell: update list of dependencies and package description

- mingw-w64-appstream-glib/PKGBUILD
Note that libsoup is required, but was listed two times.
git grep in appstream-glib sources gives no results for gtksourceview,
iso-codes and peas.
libarchive was missing.
> appstream-glib: update list of dependencies

- mingw-w64-gimp/PKGBUILD
It uses the old static bindings, not pygobject3
> gimp: fix dependency on pygobject

- mingw-w64-qbittorrent/PKGBUILD
replace source from .tar.gz to .tar.xz
> qbittorrent: update to 4.2.2

- mingw-w64-qt5-static/0044-qt-5.13-static-cmake-fix-default-libs.patch
- mingw-w64-qt5-static/PKGBUILD
- mingw-w64-qt5/0044-qt-5.13-static-cmake-fix-default-libs.patch
- mingw-w64-qt5/PKGBUILD
CMake 3.17 stops finding dll files for additional libraries trying to be found by Qt
replace expanding the list with the workaround that will be in 5.14.2 anyway
> fix qt5-static for CMake 3.17

- mingw-w64-openssl/PKGBUILD
1.1.1f is a 'bug fix only release', and reverts a breaking change introduced in 1.1.1e involving error handling.
See:
https://mta.openssl.org/pipermail/openssl-announce/2020-March/000168.html
> openssl: Update to 1.1.1f - fix for breaking change in 1.1.1e

- mingw-w64-imagemagick/PKGBUILD
Merging this PR resolves the following issues:
- Failed to build
ImageMagick source code package is here:
https://imagemagick.org/download/
> imagemagick: Update to 7.0.10-3

- mingw-w64-python-gmpy2/PKGBUILD
- mingw-w64-python-gmpy2/remove-wrong-msys2-checks.patch
> python-gmpy2: Fix import on 64 bit Windows

- FAIL_LIST.md
- mingw-w64-xmlada-gpl/PKGBUILD
because it breaks gprinstall run.
> Disable parallel installation of XmlAda

- mingw-w64-tesseract-ocr/PKGBUILD
Add `curl` and `libarchive` as dependencies.
Without these, `tesseract.exe` produces a misleading error:
```
... error while loading shared libraries: libtiff-5.dll ...
```
Fixes #6382
Note: Before making this pull request, I've recreated the package on a clean MinGW64, then installed it on another clean one (no dev tools), and all went well.
> tesseract-ocr: add missing dependencies

- mingw-w64-bootloadhid/PKGBUILD
https://www.obdev.at/products/vusb/bootloadhid.html
BootloadHID is a USB bootloader and accompanying flashing tool for Atmel AVR microcontrollers. It leverages the HID protocol to communicate, so there are no drivers or libraries necessary.
> New package: bootloadhid

- mingw-w64-catch/PKGBUILD
I can't say why the location of SelfText.exe changed, but it builds only with this change.
> catch: Update to 2.12.1

- mingw-w64-mesa/PKGBUILD
- mingw-w64-mesa/llvmwrapgen.sh
Other changes:
- link LLVM statically in response to #6353 disabling LLVM shared linking;
- use Meson builtin options to pass compiler and linker flags for
symbols stripping and SSSE3 optimization respectively;
- made it possible to build mingw-w64-mesa when llvm config is known to be
broken.
> mingw-w64-mesa: Update to 20.0.5

- mingw-w64-wxWidgets/PKGBUILD
See [wxSVG: Cannot Link Statically](https://github.com/msys2/MINGW-packages/issues/5601) for reason for using builtin library. This does not fix that issue; but, should help with that issue.
Tim S.
> wxWidgets update to 3.0.5 and use builtin libraries in Static library build

- mingw-w64-gdcm/0006-fix-build-with-poppler.patch
- mingw-w64-gdcm/PKGBUILD
1. apply this https://github.com/malaterre/GDCM/commit/be7d49cf3d13eafffdba801ba30e1c98202843a8 to build with `poppler 0.87`
2. add `docbook-xsl` to `makedepends` for building manpages
3. set `GDCM_BUILD_APPLICATIONS=ON` to build gdcm applications
> gdcm: fix build with poppler 0.87

- mingw-w64-asio/PKGBUILD
Compiling with `boost` disabled because it is default behavior.
For integration with `boost` we have asio library in `boost` package.
> asio: Update to 1.16.1

- mingw-w64-itk/PKGBUILD
1. update itk to 5.1.0
2. set `ITK_USE_SYSTEM_GDCM=ON`
see also https://github.com/msys2/MINGW-packages/issues/6449
> itk: update to 5.1.0 and fix build with gdcm

- mingw-w64-gcc-git/0020-libgomp-Don-t-hard-code-MS-printf-attributes.patch
- mingw-w64-gcc-git/PKGBUILD
Note there are a lot of other printf attributes that might need fixing.
But as they don't cause builds to fail, I decide to leave them alone.
Reference: https://gcc.gnu.org/pipermail/gcc-help/2020-May/138869.html
> gcc-git: Add patch for libgomp

- mingw-w64-meson/0001-Fix-builtin-check-in-has_function-with-GCC-10-on-Win.patch
- mingw-w64-meson/PKGBUILD
GCC 10 now provides __has_builtin() which leads to meson to skipping
a required mingw workaround.
See https://github.com/mesonbuild/meson/pull/7116 for a version of
this for meson master.
This fixes for example the glib build.
> meson: Fix has_function() returning false positives with GCC 10

- mingw-w64-appstream-glib/PKGBUILD
Not needed normally, there is already the gtk3 dependency.
The Arch Linux package does not have the gtk2 dep either, only the gtk3
dep:
https://www.archlinux.org/packages/extra/x86_64/appstream-glib/
> appstream-glib: remove gtk2 dependency

- mingw-w64-tepl/PKGBUILD
A *.vapi file is not generated by the Tepl library. Only the GIR
(GObject Introspection) is generated, which Vala can also use.
> tepl: remove vala from makedepends

- mingw-w64-glib2/0002-disable_glib_compile_schemas_warning.patch
- mingw-w64-glib2/PKGBUILD
- mingw-w64-glib2/gio-querymodules.hook.in
- mingw-w64-glib2/glib-compile-schemas.hook.in
- mingw-w64-glib2/glib2-i686.install
- mingw-w64-glib2/glib2-x86_64.install
This means we can remove all glib-compile-schemas install scripts in other
packages.
Also silences some annoying deprecation warnings like other distros while at it.
> glib: Add pacman hooks for gio-querymodules and glib-compile-schemas

- mingw-w64-libarchive/PKGBUILD
This was released a couple days ago.
This PR also adds a check to run the standard test ssuite  with make check 
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
> libarchive: update to version 3.4.3

- mingw-w64-mesa/PKGBUILD
Use runtime dependency autodetection as it's working properly now.
Dependencies wrappping precedence can change even between point releases
in Meson, as seen in 0.54.1 when Meson was using binary wraps and now in
0.54.2 it used runtime dependency autodetection and the way build is
configured hasn't changed since then.
Because both runtime dependency autodetection and binary wrap methods link
the gigantic mingw-w64-llvm statically and didn't add it as dependency,
we don't need to rebuild mesa.
> mingw-w64-mesa: Don't binary wrap and autodetect runtime dependency at the same time when linking LLVM

- mingw-w64-ngraph-gtk/PKGBUILD
new upstream release (version 6.08.05).
>  * ngraph-gtk: new upstream release (version 6.08.05).

- mingw-w64-boost/PKGBUILD
- mingw-w64-boost/boost-1.73.0-fix-locale-icu.patch
Fixes #6183. 
Looks like boost::locale and boost::regex ICU configurations are in conflict. So, fix to compile  boost::regex with ICU ([99ffbce](https://github.com/msys2/MINGW-packages/commit/99ffbce6bffe1eed97a9429368ad286a8e717ad9)) broke boost::locale usage of ICU. 
Build variables ICU_ICUUC_NAME, ICU_ICUDT_NAME and ICU_ICUIN_NAME are honored by boost::regex but ignored by boost::locale (see libs/regex/build/Jamfile.v2 and libs/locale/build/Jamfile.v2). ICU_LINK is used by boost::locale but setting it leads to error in boost::regex. 
Though more general fix would be to modify boost::locale Jamfile, working with boost build is a daunting task (at last for me). So I have used minimal approach -- disabled error on defined	 ICU_LINK in boost::regex (and checked that this variable is really …
> Fix Boost::locale compilation to use ICU backend

- mingw-w64-lcms2/PKGBUILD
Fixes a regression, re-released as same version, see https://github.com/mm2/Little-CMS/issues/219
Also use a newly provided smaller tarball w/o PDF docs
> lcms2: Force new build for re-release

- mingw-w64-aom/PKGBUILD
- mingw-w64-aom/fix-lib-dest.patch
- mingw-w64-libheif/PKGBUILD
aom now provides shared libs and libheif links against them.
I also switch cmake to ninja, seems to work fine.
> Update aom and libheif

- mingw-w64-python/PKGBUILD
- mingw-w64-python/smoketests.py
our sqlite has this feature enabled, and the official CPython is
also built this ways.
See https://docs.python.org/3.9/library/sqlite3.html#f1
Fixes #6592
> python: build with --enable-loadable-sqlite-extensions

- .github/workflows/main.yml
- README.md
Coming from https://github.com/msys2/MSYS2-packages/commit/dc1a2957f4018d9a95f8a8b80219b92f103758fb#r40206293:
- Name `main` is added to workflow `main.yml`.
- The workflow is slightly simplified.
- A shield is added to the README, which references the name of the workflow.
- Other shields are updated to use the same source and style.
- Shields are shown centered above the title of the README.
> ci: add name to 'main' GHA workflow, update shields/badges

- mingw-w64-gnucobol/PKGBUILD
additional:
* fixed sha256sums that were broken because of the http->https change in c213366c9e787c9698a7f405a579cb7043b41f2b
* disabled applying the formatwarning patch, seems to be not necessary any more
> gnucobol: update to 3.1 rc1

- README.md
.. obviously the pages have moved.
I suggest to adjust it to the working pages now, even when it seems to be not in the "final state" and is likely moved "out" of the "Old Wiki" to "Documentation" soon.
> update README with current documentation URL

- mingw-w64-gtk3/0006_fix_mouse_events.patch
- mingw-w64-gtk3/PKGBUILD
This prevents transparent top-level windows from intercepting mouse
events as often the case with screen capturing software, see
https://bugzilla.gnome.org/show_bug.cgi?id=780979
Applies the same patch that was added for gtk2 in
023eb8614b8f320563ecb625da334cd1392d430d
> gtk3: add patch from GIMP project (ported for gtk3)

- mingw-w64-ngspice/PKGBUILD
I discovered that the pkg-config file for the ngspice package was missing so I updated the PKGBUILD file accordingly.  Please let me know if there is anything else I need to do to get the merged.  Thanks in advance for the help.
> Fix missing ngspice pkg-config file.

- mingw-w64-gobject-introspection/PKGBUILD
We create an .exe launcher for it so the variable in the .pc file
no longer matched.
This is a problem because meson 0.55.0 has started to use the variable
to look up g-ir-scanner and fails.
Fixes #6677
> gobject-introspection: fix g_ir_scanner var in .pc file

- .github/workflows/main.yml
@lazka, I think that 2020-07-19 includes msys2/MSYS2-packages#2041, so the workflow can be slightly simplified.
> ci(gha): remove redundant keys

- mingw-w64-faudio/PKGBUILD
* Replace dependency ffmpeg to gstreamer
* Add glib2, gstreamer, gst-plugins-base as dependencies
* Use -DGSTREAMER instead of -DFFMPEG option for cmake
> faudio: udpate to 20.08

- mingw-w64-graphviz/PKGBUILD
It's an ancient version, but this is easier than updating.
Use a commit hash because the git tag was removed upstream.
Build with -fcommon which was the default before gcc 10.
> graphviz: fix the build

- mingw-w64-libusb-win32/01-mingw32-ddk-headers.patch
- mingw-w64-libusb-win32/PKGBUILD
This package is needed in order to build dfu-programmer without using libusb 1.0 - although it is possible, doing so would make it incompatible with the official release, as the MSYS2 dfu-programmer would be expecting the device to be using the WinUSB driver, while the release expects libusb0 (libusb-win32).
> New package: libusb-win32 1.2.6.0

- mingw-w64-bmake/0004-add-windows-draft-configs.patch
- mingw-w64-bmake/PKGBUILD
pkgrel=3: Fix Windows draft configs in mk/sys directory. Now all link operations should go through ${CC} compiler.
Related to https://github.com/msys2/MINGW-packages/issues/5859
> Fix mingw-w64-bmake package.

- mingw-w64-ngraph-gtk/PKGBUILD
new upstream release (version 6.08.06).
> * ngraph-gtk: new upstream release (version 6.08.06).

- mingw-w64-gprbuild-bootstrap-git/PKGBUILD
- mingw-w64-gprbuild/PKGBUILD
- mingw-w64-xmlada/PKGBUILD
As discussed in #6754, the `-gpl` suffix comes from the time when these packages were built from the sources of the `GNAT GPL` release. But the `GNAT GPL` release doesn't exist anymore, and the packages are now built from the GitHub repos.
This PR also updates `xmlada`, this is required for compatibility with GCC GNAT 10.
CC @juergenpf and @reznikmm
> Rename gprbuild-gpl, xmlada-gpl into gprbuild, xmlada

- mingw-w64-cfitsio/PKGBUILD
It would be great to compile cfitsio with
-D_LARGEFILE_SOURCE \
-D_FILE_OFFSET_BITS=64 \
if not, there is a limitation of FITS size.
> mingw-w64-cfitsio: Enable large file support for cfitsio

- .github/workflows/main.yml
- ci-build.sh
This makes the artifacts from available for download from GHA. This is very useful, for example when you want to download the binaries from a PR and run them locally.
> CI: store packages as GHA artifacts

- mingw-w64-vulkan-validation-layers/PKGBUILD
From #6799,
Changes are based on https://github.com/archlinux/svntogit-packages/blob/packages/vulkan-validation-layers/trunk/PKGBUILD
As a test I was able to compile [vkdevicechooser](https://github.com/aejsmith/vkdevicechooser) with both mingw64 and mingw32:
```
LDFLAGS=-static meson build-win64
meson compile -C build-win64
```
and
```
LDFLAGS='-static -Wl,--kill-at' meson build-win32
meson compile -C build-win32
```
> vulkan-validation-layers: Build layer support files

- mingw-w64-innoextract/0001-fix-segfault-windows.patch
- mingw-w64-innoextract/PKGBUILD
Update innoextract to 1.9. Get rid of patch. It merged to upstream in https://github.com/dscharrer/innoextract/commit/1381ebdab633d827faced1b994693deda05de98d
> Update innoextract to 1.9.

- mingw-w64-dfu-programmer/PKGBUILD
Turned libusb-win32 into a normal dependency - otherwise running dfu-programmer (without the libusb0 driver installed into System32 through eg. Zadig) crashes either with "error while loading shared libraries: libusb0.dll", or prints nothing at all. However, the device will still not be seen unless it has the libusb0 driver assigned, but this behaviour is expected and is the same as the official release.
> dfu-programmer: Fix libusb-win32 dependency

- mingw-w64-cninja/PKGBUILD
cninja is a software to make use of cmake easier and set sane cross-platform defaults to it.
> Add a cninja package

- .github/workflows/main.yml
This was inadvertently broken by https://github.com/msys2/MINGW-packages/commit/27375ed871235c8f03a6f641201eea8400451bac
> Fix for artifacts uploading

- mingw-w64-libhandy/PKGBUILD
Create the "mingw-w64-libhandy" package with the flag "-Dglade_catalog=enabled" to display the libhandy widgets in Glade.
> Update PKGBUILD for Glade

- mingw-w64-gcc/PKGBUILD
Existing package failed due to being signed with a different key.
List shamelessly lifted from https://github.com/archlinux/svntogit-packages/blob/6e8b5dac2553664eaac8e8f23555a85a99fb3045/trunk/PKGBUILD#L29-L32
> mingw-w64-gcc: Update validpgpkeys

- mingw-w64-cego/PKGBUILD
This is a sync patch to build cego with lfcbase-1.14.4 ( header was modified with 1.14.4 )
> cego : update to version 2.45.20

- mingw-w64-sox/PKGBUILD
SoX, the Swiss Army knife of sound processing programs.
http://sox.sourceforge.net/
The last official release of SoX is version 14.4.2 from 2015.
In the meantime, several bugs and CVE have been fixed.
Therefore use a git commit of current master for the package here:
https://sourceforge.net/p/sox/code/ci/784021f/
> Add sox package

- mingw-w64-binutils/1001-Change-the-default-characteristics-of-DLLs-built-by-.patch
- mingw-w64-binutils/1002-mingw-plugin-test-regressions-due-to-commit-514b4e19.patch
- mingw-w64-binutils/1003-Fixes-for-testsuite-failures-introduced-by-the-chang.patch
- mingw-w64-binutils/2000-Temporarily-revert-default-dll-characteristics.patch
- mingw-w64-binutils/PKGBUILD
As requested in https://github.com/msys2/MINGW-packages/pull/6902#issuecomment-683582287 here are those changes with an additional patch setting the DEFAULT_DLL_CHARACTERISTICS to 0.  This still leaves the change in default --enable-reloc-section.
I haven't tested this - my machine is still busy testing builds with the flags enabled, but CI builds passed.
> binutils: add upstream patches but revert DEFAULT_DLL_CHARACTERISTICS to 0

- mingw-w64-binutils/1001-Change-the-default-characteristics-of-DLLs-built-by-.patch
- mingw-w64-binutils/1002-mingw-plugin-test-regressions-due-to-commit-514b4e19.patch
- mingw-w64-binutils/1003-Fixes-for-testsuite-failures-introduced-by-the-chang.patch
- mingw-w64-binutils/PKGBUILD
I don't know that this is desired, but I wanted to get this out there in draft form because there seems to be some desire to test with ASLR on by default in binutils in #6674.
> binutils: add upstream patches changing PE defaults.

- mingw-w64-python/PKGBUILD
It crashes the build otherwise
> python: rebuild without high-entropy-va

- mingw-w64-arm-none-eabi-gcc/PKGBUILD
https://gitter.im/msys2/msys2?at=5f5533a849a1df0a12d16fe2
> arm-none-eabi-gcc: use default LDFLAGS for plugin.

- mingw-w64-gdb/PKGBUILD
- mingw-w64-gdb/gdb-windows-aslr.patch
Fixes #6941
Patch had to be adjusted to apply on 9.2.  It looks like more goodies for windows were added upstream than just this.
> gdb: apply upstream patch for rebasing aslr exes.

- mingw-w64-binutils/1001-Change-the-default-characteristics-of-DLLs-built-by-.patch
- mingw-w64-binutils/1002-mingw-plugin-test-regressions-due-to-commit-514b4e19.patch
- mingw-w64-binutils/1003-Fixes-for-testsuite-failures-introduced-by-the-chang.patch
- mingw-w64-binutils/1004-Pass-disable-reloc-section-on-PE-targets-for-PR-2566.patch
- mingw-w64-binutils/2000-Temporarily-revert-default-dll-characteristics.patch
- mingw-w64-binutils/2001-ld-option-to-move-default-bases-under-4GB.patch
- mingw-w64-binutils/2002-Don-t-crash-if-asked-to-create-an-empty-implib.patch
- mingw-w64-binutils/PKGBUILD
Fixes #6107 (most of the comments at least, the original report didn't give much to go on).
Also, added another upstream test patch, and turned my last patch into a
git-format one.
>> Just wondering. As we are importing many patches from upstream, how about using a git commit as source tarball for binutils?
>
> Are you talking about an upstream git commit, with whatever other changes might be pending for 2.36, or a branch on a fork with the desired patches cherry-picked on top of 2.35?
To maintain these patch series, I've got 2 branches going atm.  https://github.com/jeremyd2019/binutils-gdb/tree/backport-binutils-2_35 has upstream commits cherry-picked onto binutils 2.35 release tag.  https://github.com/jeremyd2019/binutils-gdb/tree/backport-binutils-2_35-revert-defaults is based on that …
> binutils: fix crash creating empty implib.

- mingw-w64-indent/PKGBUILD
- mingw-w64-indent/indent-2.2.12-disable-texinfo2man.patch
Add depends=("${MINGW_PACKAGE_PREFIX}-gettext") and
added indent-2.2.12-disable-texinfo2man.patch.
Also, added apply_patch_with_msg and del_file_exists.
> indent: Fix build and depends

- mingw-w64-sox/PKGBUILD
Update SoX to current commit of git master.
- Add dependency **`vo-amrwbenc`**. A check for vo-amrwbenc has been recently
added to configure of sox, see commit:
https://sourceforge.net/p/sox/code/ci/9abe8822/
- Add **`mingw-w64-libtool`** to `depends`, which is used by sox since:
https://sourceforge.net/p/sox/code/ci/0d44e15d/
- Move `pkgver()` earlier in the **`PKGBUILD`** file, before `prepare()`
> sox: update to 14.4.2.r3203.07de8a77

- mingw-w64-glslang/002-remove-deprecated-mingw-secure-api.patch
- mingw-w64-glslang/PKGBUILD
Changes:
* Add patch file to remove MINGW_HAS_SECURE_API define.
* Remove -Wno-switch compiler flag.
* Add CMAKE_INSTALL_LIBDIR option.
> glslang: Fix redefinition of snprintf_s

- mingw-w64-sox/PKGBUILD
This fixes several warnings concerning `PRIu64` and `PRIuPTR`, e.g.:
```console
warning: unknown conversion type character 'l' in format [-Wformat=]
warning: too many arguments for format [-Wformat-extra-args]
```
> sox: add -D__USE_MINGW_ANSI_STDIO=1 to CFLAGS

- mingw-w64-apr-util/002-add_mod-static.patch
- mingw-w64-apr-util/PKGBUILD
increase pkgrel to 2 .
**1**: Fix [#6631](https://github.com/msys2/MINGW-packages/issues/6631) change static link [mingw-w64-apr] library
**2**: Fix [#6886](https://github.com/msys2/MINGW-packages/issues/6886) rebuild `mingw-w64-apr-util` after fix <apr.h>
**3**: add module support
- apr_crypto_nss [need mingw-w64-nss]
- apr_crypto_openssl  [need mingw-w64-openssl]
- apr_ldap  [need mingw-w64-openldap]
- apr_dbm_gdbm  [need mingw-w64-gdbm]
- apr_dbd_odbc  [need mingw-w64-unixodbc]
- apr_dbd_sqlite3  [need mingw-w64-sqlite3] upgrade
- apr_dbd_mysql  [need mingw-w64-libmariadbclient]
- apr_dbd_pgsql  [need mingw-w64-postgresql]
> mingw-w64-apr-util: Fix [#6631], Fix [#6886], add [dbd, dbm, crypto] support

- mingw-w64-sox/PKGBUILD
This is an update to commit 9a95842.
Silence format warnings originating from usage of `PRIu64`
and `PRIuPTR` within `lsx_warn`, `lsx_debug` and `lsx_fail`, e.g.:
```console
warning: unknown conversion type character 'l' in format [-Wformat=]
warning: too many arguments for format [-Wformat-extra-args]
```
> sox: add -Wno-format to CFLAGS

- mingw-w64-ngraph-gtk/PKGBUILD
* ngraph-gtk: new upstream release (version 6.08.07).
> * ngraph-gtk: new upstream release (version 6.08.07).

- mingw-w64-v8/PKGBUILD
Removing -DV8_COMPRESS_POINTERS from pkg-config file cflags when
building 32 bit package.
Sorry I missed this one 😒, found out because my CI build failed:
[https://ci.appveyor.com/project/Kwizatz/aeongui-altq2](https://ci.appveyor.com/project/Kwizatz/aeongui-altq2)
> [v8] 32 bit builds do not support compressed pointers

- mingw-w64-arm-none-eabi-gdb/PKGBUILD
- mingw-w64-arm-none-eabi-gdb/gdb-7.12-dynamic-libs.patch
- mingw-w64-arm-none-eabi-gdb/gdb-9.1-lib-order.patch
- mingw-w64-arm-none-eabi-gdb/gdb-fix-tui-with-pdcurses.patch
- mingw-w64-arm-none-eabi-gdb/gdb-fix-using-gnu-print.patch
- mingw-w64-arm-none-eabi-gdb/gdb-home-is-userprofile.patch
- mingw-w64-arm-none-eabi-gdb/gdb-perfomance.patch
- mingw-w64-arm-none-eabi-gdb/python-configure-path-fixes.patch
PKGBUILD changed to a mash-up between 'mingw-w64-gdb' and
Arch Linux 'arm-none-eabi-gdb'
Fix Python dependency issues, and build dependencies
> Updated 'mingw-w64-arm-none-eabi-gdb' PKGBUILD

- mingw-w64-gnuplot/01-gnuplot.patch
- mingw-w64-gnuplot/PKGBUILD
This requires latest mingw-w64 headers and crt as of today.
> gnuplot: Enable d2d11 and prntvpt functions.

- mingw-w64-binutils/2003-Temporarily-revert-default-high-base.patch
- mingw-w64-binutils/PKGBUILD
It can still be enabled via --default-image-base-high
Fixes #7027 #7023
> binutils: default to <4GB image base for now

- mingw-w64-mumps/PKGBUILD
Redistributed dependencies to fix installation issue on a pristine MSYS2.
License fix.
> mumps: dependencies fix

- mingw-w64-winpthreads-git/PKGBUILD
Fixes #7043.
Draft until my gcc build gets far enough along to verify libstdc++ build.
> Filter -D__USE_MINGW_ANSI_STDIO=1 from CPPFLAGS.

- mingw-w64-gtkwave/PKGBUILD
A minor update, which fixes some issues with GHW formats (gtkwave/gtkwave#31, ghdl/ghdl#1478).
> gtkwave: update to 3.3.106

- mingw-w64-pkg-config/PKGBUILD
This was used to replace it 6 years ago, but makes it hard to test
pkgconf again.
I want to test it again to see if it's viable now.
> pkg-config: stop conflicting with pkgconf

- mingw-w64-luajit/PKGBUILD
I want to use "JIT compiler support for x64 in GC64 mode" feature implemented in 2.1.0-beta3:
https://luajit.org/ :
> LuaJIT 2.1.0-beta3 has been released
>
> ...
>
> This is the third beta release for the new v2.1 branch. Apart from various fixes, the major new features are JIT compiler support for x64 in GC64 mode, ARM64 and MIPS64.
I know that this is a beta release not a stable release.
But It seems that there is no plan to release a new stable version: https://github.com/LuaJIT/LuaJIT/issues/563
Can we use beta release in our repository?
> luajit: Update to 2.1.0-beta3

- mingw-w64-yices/PKGBUILD
- mingw-w64-yices2/PKGBUILD
`yices2` is an SMT solver like z3, but is (_much_) faster on some problems. I've tested `yices2` locally for months, although in the most recent version one of the regression tests fails, so I [disabled](https://github.com/msys2/MINGW-packages/compare/master...cr1901:yices2?expand=1#diff-7f5afad67b37bbeb62ae102e27581256R56) `make check`.
> Add yices2 SMT solver package.

- mingw-w64-arm-none-eabi-gcc/PKGBUILD
When built with the fixed import library from #7052, the imagebase workaround is no longer needed.
> arm-none-eabi-gcc: rebuild (without imagebase)

- mingw-w64-gmp/PKGBUILD
This was only required until gcc was rebuilt with the fixed import library from #7052.
> gmp: remove workaround --default-image-base-low

- mingw-w64-arm-none-eabi-newlib/PKGBUILD
Lower imagebase is no longer needed after #7052.
Not bumping pkgrel because the built gcc is not packaged.
> arm-none-eabi-newlib: remove workaround from gcc

- mingw-w64-python-aiohttp/.gitignore
- mingw-w64-python-aiohttp/PKGBUILD
- mingw-w64-python-google-auth/PKGBUILD
- mingw-w64-python-resampy/PKGBUILD
The following new packages added are dependent on the formerly committed tier 2 packages for OpenAI. There are more on the way than what is listed here, because I have to go back to previous tiers and add new dependencies.
- python-aiohttp
- python-google-auth
- python-resampy
> OpenAI deps tier 3

- mingw-w64-pyside2-qt5/001-pyside.patch
- mingw-w64-pyside2-qt5/PKGBUILD
- mingw-w64-shiboken2-qt5/003-llvm-paths.patch
- mingw-w64-shiboken2-qt5/004-shibokenmodule-name.patch
- mingw-w64-shiboken2-qt5/PKGBUILD
There is at least one license issue though. PySide2 is built with Qt Data Visualization module which is not available under LGPL. https://doc.qt.io/qt-5/qtmodules.html#qt-add-ons
The question is should I exclude it from build or mark the Pyside2 package with more restrictive "GPL".
> [do not merge] Fix shiboken2 and pyside2 build issues

- mingw-w64-gdb/PKGBUILD
This doubles the build time, but is useful for embedded developers.
> gdb: Add multiarch package

- mingw-w64-hexyl/PKGBUILD
`hexyl` is a simple hex viewer for the terminal. It uses a colored output to distinguish different categories of bytes (NULL bytes, printable ASCII characters, ASCII whitespace characters, other ASCII characters and non-ASCII).
https://github.com/sharkdp/hexyl
> hexyl: add hexyl

- mingw-w64-md4c/001-md4c-0.3.4-md2html-add-exe-suffix.patch
- mingw-w64-md4c/PKGBUILD
C Markdown parser implementation compliant to CommonMark specification.
Homepage: https://github.com/mity/md4c
> New package: md4c

- mingw-w64-p11-kit/0013-fix-reallocarray-decl.patch
- mingw-w64-p11-kit/PKGBUILD
The code in compat.h assumes that HAVE_DECL_REALLOCARRAY is defined
and 0, but with autotools it's just not defined, leading to reallocarray
not being declared.
One reason why this started crashing now might be our new linker hardening flags
leading to larger pointer values.
Hopefully fixes #7166
> p11-kit: fix "trust list" crashing

- mingw-w64-gtk3/PKGBUILD
This just contains the gtk-update-icon-cache binary which doesn't
depend on gtk itself and the pacman hooks for updating the cache.
This allows other packages to depend on it for getting the hooks without
having to depend on gtk3.
This mirrors what Arch Linux does.
> Add gtk-update-icon-cache package

- mingw-w64-libavro/002-libavro-1.10.0-add-threadsafe-option.patch
- mingw-w64-libavro/PKGBUILD
There's no need to rebuild dependent packages.
> libavro: add threadsafe option

- mingw-w64-bin2header/PKGBUILD
**Binary to Header**
*bin2header* is a command line tool. It takes any file as an argument and converts its binary data into a source header file for use in C/C++ applications. The data is stored as a character array.
Current version: 0.2.0
Upstream: https://github.com/AntumDeluge/bin2header
> New package: bin2header

- mingw-w64-msmpi/PKGBUILD
- mingw-w64-msmpi/mpi.c
Commit is intended to fix issue manifested in #6216
> msmpi: force / as file name separator in command line paths

- mingw-w64-gcc/0160-libbacktrace-seh.patch
- mingw-w64-gcc/PKGBUILD
Downstream: https://github.com/ianlancetaylor/libbacktrace/issues/43
Upstream: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96948, https://gcc.gnu.org/pipermail/gcc-patches/2020-September/553418.html
> Fix libbacktrace on mingw64

- .github/workflows/main.yml
The goal is to build various things also with pkgconf for a month or so, to find out if it is compatible enough with pkg-config, so we can switch.
> CI: add a job using pkgconf

- mingw-w64-python/2052-venv-creation-fixes.patch
- mingw-w64-python/PKGBUILD
Turns out Python uses the basename of the calling executable to
decide which launcher in the venv it uses to call pip with.
This means we have to copy all launchers we ship.
Use the non versioned launchers as src so the rewrite logic in venv
copies the venvlauncher variants.
Fixes #7227
> python: copy all python launchers into the venv

- mingw-w64-gprbuild/PKGBUILD
xmlada is statically linked and gprbuild doesn't need the compiler to run.
> mingw-w64-gprbuild: remove run dependencies

- mingw-w64-petsc/0001-mpi-detection-override.patch
- mingw-w64-petsc/PKGBUILD
This recipe builds {SDCZ} x {sequential, OpenMP and MPI} static and DLL PETSc builds (12 variants in total) with PkgConfig support.
> New package: petsc

- mingw-w64-libhandy/PKGBUILD
> libhandy: enable glade support

- mingw-w64-xmlada/PKGBUILD
Configure is not able to detect the ability to build shared libraries without the target set.
> mingw63-xmlada: fix build of shared libraries

- mingw-w64-mesa/PKGBUILD
- mingw-w64-mesa/llvmwrapgen.sh
Improvements
- Correct deprecation warnings with llvm, shared-glapi, gles1 and gles2 build options during build configuration
- Link LLVM dynamically.
Build fails on CI for now, but it should work as soon as LLVM 11.0.0-4 appears on repo.
> mingw-w64-mesa: Update to 20.2.2

- mingw-w64-solid3/PKGBUILD
- mingw-w64-solid3/disable-examples.patch
- mingw-w64-solid3/use-external-qhull.patch
Adds a new package for SOLID, a library for collision detection and distance computation of 3D meshes.
The last release does not have a tag, so I used the corresponding commit ID.
One patch enables the use of the QHull package over the included copy of an older Qhull version. The other one disables the examples, as these show compiler errors when enabling double-precision floating-point format for better accuracy. Corresponding patches are already submitted upstream but not merged yet.
> solid3: Add package

- mingw-w64-emacs/PKGBUILD
Improves JSON parsing speed, noticeable with some packages such as LSP.
> emacs: use jansson (native JSON support)

- mingw-w64-ghdl/PKGBUILD
Co-authored-by: Tim Stahlhut <stahta01@gmail.com>
This PR contributes an split package for GHDL: mcode on MINGW32, and LLVM on MINGW64. See #5757.
Close #6686
> ghdl: add split package

- mingw-w64-glib2/PKGBUILD
Also stop using buildtype=plain, as upstream sets various things based
on buildtype and we want to leave that up to upstream.
> glib: Update to 2.66.3

- mingw-w64-gr/PKGBUILD
We removed -git suffix from qhull-git by fd033db7ff110e747138223a65cc483f571445e8.
> gr: use qhull

- mingw-w64-cmake/PKGBUILD
Since pkgconf replaces pkg-config, let cmake depends on pkgconf
bzip2, xz, zlib, zstd are pulled in by libarchive, so I think it is not necessary to list them in dependencies
> cmake: update to 3.19.1, depends on pkgconf

- mingw-w64-pqp/PKGBUILD
Adds a new package for PQP, a library for performing proximity queries on 3D meshes.
The last release does not have a tag, so I used the corresponding commit ID.
> pqp: Add package

- mingw-w64-ffmpeg/PKGBUILD
- mingw-w64-ffmpeg/srt.patch
The patch directly comes from here: http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=7c59e1b0f285cd7c7b35fcd71f49c5fd52cf9315. It seems srt was updated and removed some deprecated constant.
I removed the pgp key check because it did not work on my end but I can add it again if someone explains me how it works ^^.
EDIT: without the patch it did not compile locally
> Ffmpeg: build both shared and static libs

- mingw-w64-boost/PKGBUILD
it's linking against some libraries it's not depending on and wasn't
built in our CI the last time. Try rebuilding here.
> boost: rebuild

- mingw-w64-gedit/0001-workaround-no-delayed-loading.patch
- mingw-w64-gedit/PKGBUILD
It's supposed to use delayed DLL loading, but that's not supported
by meson, so patch things to link normally.
Fixes #7322
> gedit: fix the DLL loading warning at the start 

- mingw-w64-python-black/PKGBUILD
- mingw-w64-python-google-cloud-core/PKGBUILD
- mingw-w64-python-pytest-asyncio/PKGBUILD
- mingw-w64-python-tqdm/PKGBUILD
- mingw-w64-python-trimesh/PKGBUILD
New:
- python-black: dependency for "lip2wav" AI, not sure why this fails build bot. It builds for me
- python-pytest-asyncio: for python-tqdm check
Updated:
- python-google-cloud-core 1.4.4
- python-tqdm 4.54
- python-trimesh 3.8.15
> OpenAI deps: moving from dirty branch

- mingw-w64-icesprog/PKGBUILD
Upon request, the maintainer of icesprog released a new git tag: https://github.com/wuxx/icesugar/issues/19. In this PR, the recipe is changed for retrieving a tarball, instead of using git.
/cc @Biswa96
> icesprog: get tarball instead of using git

- mingw-w64-python-autopxd2/PKGBUILD
- mingw-w64-python-zstandard/PKGBUILD
Tried to package the third party godot-python bindings, but it is messy. The dependencies consist of python-autopxd2 and python-zstandard, so I figured someone could use those if needed.
> godot-python deps

- mingw-w64-opencascade/0001-fix-compile-openvr.patch
- mingw-w64-opencascade/PKGBUILD
This PR update opencascade to version 7.5.0 and enable more opencascade dependencies to be used:
- ffmpeg
- freeimage
- rapidjson
- vtk
- openvr
- d3d
- tbb
gl2ps dependency was removed because opencascade does not use it anymore.
A lot of 3RDPARTY_* variable are defined to ensure the cmake build find the right lib in both static and shared build.
A patch has been made to fix a compilation error when using openvr.
Fix #7343 I guess.
What is the politics about the makefiles generator here ? Sometimes it uses MSYS Generator, sometimes ninja. So I do not know what should be used by default when creating packages.
> Update opencascade to version 7.5.0

- mingw-w64-fritzing/0001-Fix-libgit2-version-check-to-allow-building-with-ver.patch
- mingw-w64-fritzing/0002-Fix-casts-from-pointer-to-long-to-size_t-instead.patch
- mingw-w64-fritzing/0003-qmake-fixes-for-mingw.patch
- mingw-w64-fritzing/0004-Look-in-.-share-fritzing-from-bin-dir-on-mingw.patch
- mingw-w64-fritzing/PKGBUILD
- mingw-w64-fritzing/system-libgit2.patch
My first attempt at packaging something.
> The Fritzing application is an Electronic Design Automation software with a low entry barrier, suited for the needs of makers and hobbyists. It offers a unique real-life "breadboard" view, and a parts library with many commonly used high-level components. Fritzing makes it very easy to communicate about circuits, as well as to turn them into PCB layouts ready for production. It is particularly popular among Arduino and Raspberry Pi users, and is widely used in education and creative tinkering.
https://fritzing.org
https://github.com/fritzing/fritzing-app
Major ~~outstanding~~[solved](https://github.com/msys2/MINGW-packages/pull/7376#issuecomment-738217175) issue is that Fritzing cannot find its files out of the box.  This can be worked around by …
> New package: fritzing

- mingw-w64-dfu-util/PKGBUILD
Executing `dfu-util --help` fails if `*-libwinpthread-git` is not installed. See https://github.com/umarcor/MINGW-packages/runs/1509020890?check_suite_focus=true#step:4:73.
/cc @fauxpark
> dfu-util: libwinpthread is a dep

- mingw-w64-cmake/PKGBUILD
I assume that this was an oversight, as `cmake` is the only package I have that seems to have installed anything directly in `/mingw64/share/man{1,7}` instead of `/mingw64/share/man/man*`.
> Fix the install path for CMake’s man pages

- mingw-w64-libiptcdata/0001-libiptcdata-automake-remove-iptc-docs.patch
- mingw-w64-libiptcdata/PKGBUILD
Found that to compile RawTherapee one has to first compile libiptcdata [here][1]. What if we can provide libiptcdata as a package? /cc @Beep6581 @Desmis
[1]: https://rawpedia.rawtherapee.com/Windows#Download_and_build_libiptcdata
> libiptcdata: Add package, for RawTherapee.

- mingw-w64-iverilog/PKGBUILD
I got the test environment contaminated and I was mislead. This fixes iverilog's runtime deps.
> iverilog/deps: add bzip2, remove gcc-libs

- mingw-w64-parmetis/PKGBUILD
I don't know what the parmetis version does since it's broken.
So let's namespace for now.
Fixes #7220
> parmetis: namespace the mtest binary to avoid conflict with tfel

- mingw-w64-ecpprog/PKGBUILD
Replacement for #7349 with a different source fork (a user's, instead of some org's).
> ecpprog: add d654a4d

- mingw-w64-clang/PKGBUILD
Fixes issue #7256 
lldb includes a hardcoded PYTHONHOME set to where python was during building. As can be seen in [lldb output here](https://github.com/msys2/MINGW-packages/issues/7256#issue-738833113) it was D:/a/_temp/msys/msys64/mingw32/bin.
This change makes the embedded path relative to liblldb.lldb - i.e. not absolute to the D:\ drive from build machine. Another option could be to use the build option to disable embedding the  #PYTHONHOME which is standard on non-windows targets.
As a side note: I think lldb's build scripts doesn't set this correctly. In the sys.path in the mentioned lldb output the /msys64/mingw32/bin/lib/python3.8 should rather be /msys64/mingw32/lib/python3.8. Maybe this matches the official python installer where python lib is in folder in same directory as …
> Fix lldb's embedded PYTHONHOME

- mingw-w64-python-cachetools/PKGBUILD
- mingw-w64-python-google-auth/PKGBUILD
- mingw-w64-python-google-cloud-storage/PKGBUILD
- mingw-w64-python-gsutil/PKGBUILD
- mingw-w64-python-tifffile/PKGBUILD
Updated:
- python-cachetools 4.2
- python-google-auth 1.24
- python-google-cloud-storage 1.34
- python-gsutil 4.57
- python-tifffile 2020.12.8
> Openai dep updates

- mingw-w64-asciidoc/PKGBUILD
- mingw-w64-asciidoc/asciidoc.bat
It's allow to call `asciidoc` command from `cmd` or `subprocess.Popen(...)` via `python` like in [asciidoc reader](https://github.com/getpelican/pelican-plugins/blob/master/asciidoc_reader/asciidoc_reader.py#L20).
> asciidoc: Install asciidoc.bat

- mingw-w64-lua-luarocks/PKGBUILD
Should fix #7402 and #3434.
Arch-linux also add the following:
```
install -Dm644 luarocks.bash "$pkgdir/usr/share/bash-completion/completions/luarocks"
install -Dm644 luarocks.fish "$pkgdir/usr/share/fish/vendor_completions.d/luarocks.fish"
install -Dm644 luarocks.zsh "$pkgdir/usr/share/zsh/site-functions/_luarocks"
install -Dm644 luarocks-admin.bash "$pkgdir/usr/share/bash-completion/completions/luarocks-admin"
install -Dm644 luarocks-admin.fish "$pkgdir/usr/share/fish/vendor_completions.d/luarocks-admin.fish"
install -Dm644 luarocks-admin.zsh "$pkgdir/usr/share/zsh/site-functions/_luarocks-admin"
```
I have no idea what they are used for. Should I add them too ?
> Update luarocks to version 3.4.0

- mingw-w64-curl/PKGBUILD
I disable the signature checks temporarily because of CI errors
It can be restored later if wanted
> curl: update to 7.74.0

- mingw-w64-gdb/PKGBUILD
- mingw-w64-gdb/gdb-fix-array.patch
Backport fix from gdb-10-branch.
> gdb: Fix array subscript when upper bound is unknown

- mingw-w64-petsc/PKGBUILD
Added support for hwloc. In addition PT-Scotch gets disabled as it seems to conflict with ParMetis so these two partitioners are mutually exclusive.
> petsc: version bump

- mingw-w64-python-ldap3/PKGBUILD
Without this dependency, I get the error:
```python
import ldap3
...
from pyasn1.type.univ import OctetString, Integer, Sequence, Choice, SequenceOf, Boolean, Null, Enumerated, SetOf
ModuleNotFoundError: No module named 'pyasn1'
```
> python-ldap3: Add pyasn1 to depends

- mingw-w64-msmpi/PKGBUILD
- mingw-w64-msmpi/all.tcl
- mingw-w64-msmpi/hello_mpi.F
- mingw-w64-msmpi/hello_mpi.c
- mingw-w64-msmpi/hello_mpi.cpp
- mingw-w64-msmpi/hello_mpi.f90
- mingw-w64-msmpi/msmpi.sh
- mingw-w64-msmpi/msmpi.test
- mingw-w64-msmpi/tclbuildtest.tcl
- Install precompiled .mod files for FORTRAN90's USE statement.
- Add TclTest-based test suite to check for C, C++ and FORTRAN basic MPI build & run capability.
> msmpi: FORTRAN90's .mod files, test suite

- mingw-w64-ghdl/PKGBUILD
GHDL needs to be bumped, because the AST of libghdl went out of sync with the version available at the moment.
> ghdl: update to 0.37.0.r1123.g8ed35277

- mingw-w64-libtiff/PKGBUILD
Enable libdeflate, which is new and default in this release.
and webp, because it's default and it seems to work, so why not.
> libtiff: Update 4.2.0

- mingw-w64-lis/PKGBUILD
"Fixed MPI related bug in configure.ac (thanks to Carlo de Falco)."
> lis: Update to 2.0.29

- mingw-w64-nextpnr/PKGBUILD
This PR adds package `nextpnr` (a portable FPGA place and route tool): [YosysHQ/nextpnr](https://github.com/YosysHQ/nextpnr). It's added to group 'eda'.
Together with Yosys (#7534), it allows synthesising and implementing HDL designs targetting Lattice's ICE40 FPGAs. The GUI (based on Qt5) is enabled.
~~See YosysHQ/nextpnr#546 for a discussion about why `mingw32-make DESTDIR="${pkgdir}" install` is commented out and the assets are copied manually instead.~~
> nextpnr: add 0.0.r2859.5e53a182

- mingw-w64-ngraph-gtk/PKGBUILD
New upstream release (version 6.08.09).
> * ngraph-gtk: new upstream release (version 6.08.09).

- mingw-w64-pygobject/PKGBUILD
setuptools/distutils currently strip all debug info because it forwards build time flags from python, and meson is less of a mess than setuptools/distutils, so let's switch.
> pygobject: port to meson

- mingw-w64-nuspell/PKGBUILD
Extra unused dependencies are removed from PKGBUILD.
> nuspell: fix unused dependencies

- mingw-w64-zlib/01-zlib-1.2.11-1-buildsys.mingw.patch
- mingw-w64-zlib/PKGBUILD
* `-export-all` is not a valid flag, it should be `--export-all-symbols`
* lld does not accept a DLL when linking, it needs the import library
Some discussion at https://github.com/msys2/MINGW-packages/commit/eb8bd3f78fcf62c4adbf7e775e6149b51951d8b9#r45640675
> zlib: fix building with lld

- mingw-w64-tcl/009-fix-using-gnu-print.patch
- mingw-w64-tcl/PKGBUILD
ll and I64 work fine when __USE_MINGW_ANSI_STDIO is set.
We still remove the setting of __USE_MINGW_ANSI_STDIO=0 on Makefile,
since the rest our packages are built with __USE_MINGW_ANSI_STDIO=1.
See
https://core.tcl-lang.org/tcl/tktview/c9759399735f1979a2e7931fd9f00da20f2fbb7e
> tcl: remove unnecessary patch to stdio behavior

- mingw-w64-ghdl/PKGBUILD
- mingw-w64-yosys/PKGBUILD
Coming from #7569.
> * A fix was pushed to Yosys, which is related to building the ghdl-yosys-plugin frontend: [YosysHQ/yosys#2515](https://github.com/YosysHQ/yosys/pull/2515). That's not critical for the yosys package on MSYS2, but it's desirable to bump it.
> 
> * Python bindings in GHDL were reorganised and reworked to improve usability. Hence, the GHDL package is bumped.
> 
> * There is currently an annoying constraint that prevents users/contributors of MSYS2 from building the Yosys PKGBUILD alone. At the moment, it must be built at the same location where GHDL was built. Since GHDL is/was built in CI, Yosys can "only" be built in CI (unless GHDL is built and installed locally before). Find further details in [ghdl/ghdl#1570](https://github.com/ghdl/ghdl/issues/1570). This PR patches …
> update Yosys and GHDL

- mingw-w64-python/1700-cygpty-isatty.patch
- mingw-w64-python/1702-default-to-console-cp-for-cygpty.patch
- mingw-w64-python/PKGBUILD
In case of cygpty we want to fake a tty and at the same time make
Python behave as if it was attached to a console.
This improves two thing in that regard:
* Update the is_cygpty patch to cover more isatty() checks (likely
they were added since the patch was created)
* Default the stdio encoding to the console output encoding by default.
This is only in effect if stdout isn't redirected (then is uses the ANSI code page)
and no real console is used (then it forces utf-8). Python never considers the
case were isatty() and no console, so we have to add this.
This makes printing unicode work again in MSYS2 bash.
> python: cygpty hack improvements

- mingw-w64-cmdpack/PKGBUILD
cmdpack is a nifty little set of tools I've found use in for the past few years. Though prebuilt binaries exist for Windows, I preferred to have them built by my MinGW-w64/MSYS2 installation
> [Port] cmdpack

- mingw-w64-ffmpeg-python/PKGBUILD
- mingw-w64-python-pytest-mock/PKGBUILD
- mingw-w64-python-trimesh/PKGBUILD
Updated:
- ffmpeg-python: renamed from `python-ffmpeg-python` for less redundancy, reflects AUR package name
- python-pytest-mock 3.5
- python-trimesh 3.9.1
> OpenAI updates

- mingw-w64-rhash/PKGBUILD
This dependency is not present on Arch or Gentoo.
> rhash: remove makedepends on ruby

- mingw-w64-libffi/PKGBUILD
> libffi: disable symbol versioning

- mingw-w64-readline/PKGBUILD
> readline: fully spell out --export-all-symbols

- mingw-w64-liblo/PKGBUILD
http://liblo.sourceforge.net/
"liblo is an implementation of the Open Sound Control protocol for POSIX systems, started by Steve Harris and now maintained by Stephen Sinclair. It is released under the GNU Lesser General Public Licence version 2.1 or greater."
> [New Package] Add liblo

- mingw-w64-mxml/PKGBUILD
- mingw-w64-mxml/mxml-3.2.patch
https://www.msweet.org/mxml/
"Mini-XML is a tiny XML library that you can use to read and write XML and XML-like data files in your application without requiring large non-standard libraries. Mini-XML only requires an ANSI C compatible compiler (GCC works, as do most vendors’ ANSI C compilers) and a make program."
> [New Package] Add Mini-XML

- mingw-w64-adwaita-icon-theme/PKGBUILD
the build requires gtk-encode-symbolic-svg.exe
Fixes #7624
> adwaita-icon-theme: makedepend on gtk3

- mingw-w64-openFPGALoader/PKGBUILD
- Tags are now available, so git is not required.
- MSYS makefiles are used instead of MINGW, therefore, `mingw-w64-*-make` is not required.
> openFPGALoader: update to 0.2.1

- mingw-w64-tklib/PKGBUILD
The install script used on the previous package was defective and
ignored several files. Upstream fixed the problem.
The github mirror lags. Now we download the sources directly from
tcl-lang.org, which contains the central repository.
> tklib: update to fix install, download from tcl-lang.org

- mingw-w64-eccodes/PKGBUILD
- mingw-w64-eccodes/fix-mingw.patch
Add eccodes, which is ECMWF's GRIB and BUFR encoding/decoding library.
Github repo: https://github.com/ecmwf/eccodes
> eccodes: add eccodes package build

- mingw-w64-gtkwave/PKGBUILD
This PR updates gtkwave to 3.3.108. At the same time, instead of building the gtk2 version only, `*-gtk2` and `*-gtk3` packages are provided. Should `*-gtkwave` be set as an alias of one of those?
> gtkwave: update to 3.3.108 and add gtk3 package

- mingw-w64-python-pip/PKGBUILD
This PR updates pip to version 20.3.3 and removes patches that were fixed upstream.
> Update python-pip to 20.3.3

- mingw-w64-ghdl/PKGBUILD
The libraries included in the package were reworked upstream. Vendor library installation scripts were reworked too (tested on MSYS2, Git for Windows and Powershell, using the MSYS2 packages). This PR picks those enhancements.
> ghdl: update to 0.37.0.r1342.geeb25ef2

- mingw-w64-python-colour-science/PKGBUILD
Also align w/ template and remove `nosetests` (0 were being run) in favour of generic Python packaging check.
> python-colour-science: update to 0.3.16

- mingw-w64-parsec/PKGBUILD
Switch from git version to last main releas: https://bitbucket.org/icldistcomp/parsec/downloads/?tab=tags
> update: parsec to 3.0.2012

- mingw-w64-python-rawpy/PKGBUILD
RAW image processing for Python, a wrapper for libraw
No source available on [PyPi](https://pypi.org/project/rawpy/#files) for eventual pip install, only statically linked MSVC wheels.
> rawpy: new package, 0.16.0

- mingw-w64-ghdl/PKGBUILD
A fix was pushed, which prevents crashes (abortions) when loading shared libraries generated by GHDL, from Python.
Ref: https://github.com/ghdl/ghdl-cosim/actions/runs/514080866
> ghdl: update to 0.37.0.r1370.g7135caee

- mingw-w64-munt-mt32emu/PKGBUILD
- mingw-w64-munt/PKGBUILD
Package(s) for Munt.
The first commit is an all in one solution for the Munt project.
The second commit splits off the mt32emu library for people that just need the library and can do without all the QT5, glib2 and portaudio overhead. Several linux distros are also making use of the library like this.
Done as two commits so you can easily decide the course of action you want to take.
Fixing indentation, full url, depends vs makedepends and resubmitting a pull request
> Muntpackagefixed

- mingw-w64-cppcoro/PKGBUILD
- mingw64-w64-cppcoro/PKGBUILD
add support https://github.com/lewissbaker/cppcoro, this can be a header only library, for mingw64, std::experence must be replace, -fcoroutines compile flags must be open.
A built package come here.
[mingw-w64-x86_64-cppcoro-r385.69e5754-1-any.pkg.tar.zip](https://github.com/msys2/MINGW-packages/files/5893208/mingw-w64-x86_64-cppcoro-r385.69e5754-1-any.pkg.tar.zip)
msys/git (or git.exe) was need, but I don't konw how to enable it.
> add cppcoro library (header only)

- mingw-w64-ngraph-gtk/PKGBUILD
ngraph-gtk: new upstream release (version 6.08.09).
> ngraph-gtk: new upstream release (version 6.09.00).

- mingw-w64-openblas/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/7827
> openblas: Specify target CPU architecture to restrict advanced SIMD instructions.

- mingw-w64-scons/0002-fix-missing-man-pages.patch
- mingw-w64-scons/PKGBUILD
The ones it creates are broken and require some java tool we don't have.
> scons: don't install man pages

- mingw-w64-python/PKGBUILD
Not sure why it is there (git history doesn't help).
It results in Python remembering/passing it to setuptools when building extensions
which results in extensions never having debug symbols even if built with "--debug".
Just remove it.
> python: don't pass -s to LDFLAGS

- mingw-w64-clang/0201-Compiler-RT-Fix-profiler-building-with-MinGW-GCC.patch
- mingw-w64-clang/PKGBUILD
Supersedes #7753, with a functional change to make it worthwhile to churn such a large package.
Port of msys2/CLANG-packages#13 to MINGW-packages.  I have been running with this patch for a while.
/cc @mati865
> clang: libprofiler fix and package func tweaks

- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
My experiments with clang on aarch64 have been going well, I figured it was time to start getting changes reviewed for inclusion back into MINGW-packages.  These packages seemed like a good place to start, being moderately complicated (not like mingw-w64-clang!), but containing representative techniques.
The packages for the existing MINGW_INSTALLS should be unchanged.
If the MINGW_PACKAGE_PREFIX contains `-clang-` (a "clang prefix"), default to ucrt instead of msvcrt.  (This might also be a handy way to detect, say, `-ucrt-` in MINGW_PACKAGE_PREFIX for a gcc+ucrt variant).
If the CARCH is not i686 or x86_64, default WIN32_WINNT to 0xA00 (Windows 10), under the assumption that any new arches will not be relevant for any older versions.
Appropriate crt configure options for armv7 and …
> crt/headers/winpthreads: clang prefix handling

- mingw-w64-ghdl/PKGBUILD
After almost 20 years of development, GHDL 1.0.0 was tagged! :tada:
I didn't remove `pkgver()`, because I expect it to be required in future updates.
@lazka, is there any problem with releasing `1.0.0` and the next update being something such as `1.0.0.r75.g55555555`?
> ghdl: update to 1.0.0

- mingw-w64-libraw/LibRaw_force-openmp.patch
- mingw-w64-libraw/PKGBUILD
See https://github.com/LibRaw/LibRaw/pull/378#issuecomment-770166755
This takes only the relevant part of the upstream commit.
> libraw: force use of OpenMP

- mingw-w64-uasm/PKGBUILD
Change sources to git repo, pinned to same commit that the package was last built against.
Fix multiple definition errors linking by adding -fcommon to compiler flags.
Fixes #7893
Probably still needs some pkgver adjustment, not sure how to go about that on something that uses branches for versions instead of tags.
> uasm: fix build

- mingw-w64-pyqt3d/PKGBUILD
- mingw-w64-pyqt5-3d/PKGBUILD
New package for mingw-w64-pyqt3d very much copied from mingw-w64-python-pyqt5.
Tested and worked fine for me...<br>
Locally, I had to remove the --confirm-licence for sip-build though.
In this pull request, the flags are identical to those in the python-qt5 package.
> pyqt3d: new package

- mingw-w64-qt5-static/0310-fix-assimp-not-found.patch
- mingw-w64-qt5-static/PKGBUILD
- mingw-w64-qt5/PKGBUILD
since 5.15 it was chosen to build tls support via schannel
unfortunately this is broken in some cases
add a patch to mitigate that while keeping on using it
(from https://codereview.qt-project.org/c/qt/qtbase/+/333051)
sync up PKGBUILDs
> qt5-static: patch schannel

- mingw-w64-PKGBUILD-templates/mingw-w64-splitpkg-wrappers-1.0.template
- mingw-w64-brotli/PKGBUILD
- mingw-w64-bullet/PKGBUILD
- mingw-w64-capstone/PKGBUILD
- mingw-w64-dlib/PKGBUILD
- mingw-w64-gdb/PKGBUILD
- mingw-w64-gobject-introspection/PKGBUILD
- mingw-w64-hyphen/PKGBUILD
- mingw-w64-icu/PKGBUILD
- mingw-w64-libiconv/PKGBUILD
- mingw-w64-lua-bitop/PKGBUILD
- mingw-w64-lua-lpeg/PKGBUILD
- mingw-w64-lua-mpack/PKGBUILD
- mingw-w64-ocaml/PKGBUILD
- mingw-w64-openexr/PKGBUILD
- mingw-w64-pygobject2/PKGBUILD
- mingw-w64-qscintilla/PKGBUILD
- mingw-w64-scite/PKGBUILD
- mingw-w64-unicorn/PKGBUILD
- mingw-w64-winpthreads-git/PKGBUILD
- mingw-w64-wxWidgets3.1/PKGBUILD
This adds a template, `mingw-w64-splitpkg-wrappers`, to mingw-w64-PKGBUILD-templates, and converts a selection of small-ish packages to use it.  This was done by adding the line
```bash
```
to each PKGBUILD file, and then running
```bash
git diff --name-only | while IFS= read -r line; do
pushd `dirname $line`
makepkg-template --template-dir ../mingw-w64-PKGBUILD-templates/
popd
done
```
If this is an acceptable approach, I can do the remaining packages, split into CI-sized pull requests.
> Split package template

- mingw-w64-pkgconf/0007-list-all-leading-slash.patch
- mingw-w64-pkgconf/PKGBUILD
This fixes a `pkgconf`, observed in pkgconf/pkgconf#209, where the output of `pkgconf --list-all` would mistakenly print out package names with leading slashes, e.g.,
```
$ ./pkgconf.exe --list-all
/bzip2                         bzip2 - Lossless, block-sorting data compression
/expat                         expat - expat XML parser
...
```
This interferes with tools like `cabal-install`, which parse the output of `pkgconf --list-all` (or `pkg-config --list-all`) and assume that each line begins with an alphanumeric package name.
pkgconf/pkgconf#209 was fixed upstream in pkgconf/pkgconf#210, but it may be a while for another version of `pkgconf` is released (see https://github.com/pkgconf/pkgconf/pull/210#issuecomment-776663093). In the meantime, this incorporates the patch from …
> pkgconf: Remove leading slashes in --list-all output

- mingw-w64-clang/PKGBUILD
clang was already using this code, so this change effectively just adds the template comments
> clang: use splitpkg-wrappers template

- mingw-w64-OpenSceneGraph/PKGBUILD
- mingw-w64-osgQt/PKGBUILD
- mingw-w64-osgqtquick-git/PKGBUILD
- mingw-w64-osgworks-git/PKGBUILD
Added cyrus-sasl makedepends in OpenSceneGraph, as it failed to build due to missing header, by way of `libvncserver`.  Additional osg* packages failed to build, and will be included in the final PR which updates packages which fail to build.
> use splitpkg template in openscenegraph packages that build

- mingw-w64-libxml2/0027-decoding-segfault.patch
- mingw-w64-libxml2/PKGBUILD
https://gitlab.gnome.org/GNOME/libxml2/-/issues/64
https://github.com/msys2/MINGW-packages/issues/7955
I don't know if this fix is good, but it fixes the crash
and hopefully this gets fixed upstream.
Fixes #7955
> libxml2: backport an unmerged fix for a crash

- mingw-w64-python/1800-link-win-resource-files-and-build-pythonw.patch
- mingw-w64-python/PKGBUILD
instead of hardcoding it
Fixes #7948
> python: use AC_CHECK_TOOL for finding windres

- mingw-w64-clang/PKGBUILD
Split packages not defining a depends will fall back the global one
which I guess was not on purpose.
> clang: fix unnecessary gcc dependency on some split packages

- mingw-w64-cairo/0001-fix-font-names-in-pdf-output.patch
- mingw-w64-cairo/PKGBUILD
See https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/125
> cairo: fix issue with illegal font names in PDF output

- mingw-w64-iverilog/PKGBUILD
This should be just a regular update. However, I found that I was incorrectly using `12.0` as the base version. It should be `11.0`. Otherwise, when `12.0` is tagged, existing versions will be considered larger by `vercmp`.
Therefore, I decided to handle it here. What needs to be done so that this "downgrade" is acceptable?
> iverilog: update to 11.0.r8891.18e7406d

- mingw-w64-python-cryptography/0002-move-setuptools-rust-import.patch
- mingw-w64-python-cryptography/PKGBUILD
Don't fail _with_rust=no build for lack of setuptools-rust
rust doesn't support aarch64-pc-windows-gnu (msys2/CLANG-packages#28)
and it apparently hardcodes libgcc (msys2/CLANG-packages#29), so disable
it in all clang prefixes
> python-cryptography: fix _with_rust=no build

- mingw-w64-ffmpeg/PKGBUILD
This enables use of the SoX resampler.
More info: https://trac.ffmpeg.org/wiki/FFmpeg%20and%20the%20SoX%20Resampler
> ffmpeg: Add libsoxr dependency

- mingw-w64-libusbmuxd/001-2.0.2-Fix-windows-build.patch
- mingw-w64-libusbmuxd/PKGBUILD
The patch included is already submitted to upstream, backporting it to make version 2.0.2 compile on windows.
> libusbmuxd: Update to 2.0.2

- mingw-w64-libmpcdec/0001-install-config-win32-header.patch
- mingw-w64-libmpcdec/PKGBUILD
mpcdec.h includes config_win32.h file but it is not installed.
So, patch the Makefile.am file to install it.
Fixes https://github.com/msys2/MINGW-packages/issues/8014
> libmpcdec: Install config_win32.h file.

- mingw-w64-soqt/PKGBUILD
The missing -lSoQt part will be added to Libs section.
The missing -DSOQT_DLL part will be added to Cflags section.
> soqt: Fix SoQt.pc

- mingw-w64-coin/PKGBUILD
The missing -DCOIN_DLL part will be added to Cflags section.
> coin: Fix Coin.pc

- mingw-w64-gr/PKGBUILD
Manually generate version number otherwise CMake fails for not being git repository.
> gr: Use Ninja, fix version generation.

- mingw-w64-go/PKGBUILD
Updated mingw-w64-go to 1.16 . Tested with local projects, working fine.
Added simple check to test `gofmt` and `go build` like described [here](https://golang.org/doc/install/source?download=go1.16.src.tar.gz#testing).
> Updated mingw-w64-go package to 1.16

- mingw-w64-cmake/0009-Process-Fix-execute-error-handling-re-working-dir-on-windows.patch
- mingw-w64-cmake/PKGBUILD
Some folks have been hit by an error while building LLVM because of https://gitlab.kitware.com/cmake/cmake/-/issues/21439
> Backport fix for building git LLVM

- mingw-w64-libopenmpt/PKGBUILD
A mod player library, evolved from libmodplug and actively maintained.
I've included the command line frontend which adds extra dependency on portaudio, libsndfile and flac, can be removed if undesired.
> Add libopenmpt package 

- mingw-w64-libreplaygain/PKGBUILD
This is required to update musepack package to the more recent version (see issue #8014 )
> Add libreplaygain package

- mingw-w64-python-jaraco.path/PKGBUILD
- mingw-w64-python-pytest-checkdocs/PKGBUILD
- mingw-w64-python-pytest-enabler/PKGBUILD
- mingw-w64-python-pytest-shutil/PKGBUILD
- mingw-w64-python-pytest-virtualenv/PKGBUILD
Fixes the packages which failed to build in autobuild
on a side note, it seems weird that this CI over here doesn't check for these. `setuptools_scm` was installed in one package and is reused everywhere in this CI while not in the autobuild which seems to be weird, and needs to be fixed.
> Add more setuptools_scm dependency

- mingw-w64-openocd/PKGBUILD
Building not tested, I'm hoping for CI to verify it instead.
> openocd: Update to 0.11.0, add capstone dependency

- mingw-w64-ngraph-gtk/PKGBUILD
ngraph-gtk: new upstream release (version 6.09.00).
> ngraph-gtk: new upstream release (version 6.09.01).

- mingw-w64-gdal/PKGBUILD
Hmm there seems to be a problem with the new make or autoconf that is unrelated to this update. I confirmed that the same error appears when we try to rebuild the current gdal version.
```
m4/ax_lib_xerces.m4:37: AX_LIB_XERCES is expanded from...
configure.ac:4022: the top level
configure.ac:4046: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:4046: You should run autoupdate.
../autoconf-2.71/lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
m4/ax_lib_expat.m4:37: AX_LIB_EXPAT is expanded from...
configure.ac:4046: the top level
configure.ac:4069: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:4069: You should run autoupdate.
../autoconf-2.71/lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
m4/ax_lib_libkml.m4:48: AX_LIB_LIBKML is …
```
> gdal 3.2.2

- mingw-w64-sqlite3/PKGBUILD
The patch release `3.35.1` contains [bug](https://www.sqlite.org/src/info/1c24a659e6d7f3a1)  fix and documentation improvements.
> sqlite3: Update to 3.35.1

- mingw-w64-mbedtls/PKGBUILD
- mingw-w64-mbedtls/dll-location.patch
- mingw-w64-mbedtls/enable-features.patch
- mingw-w64-mbedtls/symlink-test.patch
Changes:
* Update patches.
* Use GitHub repo for source tarball.
* Use Ninja.
* Enable programs to build.
> mbedtls: Update to 2.26.0

- mingw-w64-arm-none-eabi-gcc/PKGBUILD
...Although it is only required at runtime. See #8099. Once again, maybe a too-straightforward patch, might need further investigation on the cause of said dependency.
> [arm-none-eabi-gcc] Add zstd as required dependency

- mingw-w64-sqlite3/PKGBUILD
* PKGBUILD:
- remove redundant configure flag '--enable-rtree' (implied by
'--enable-all')
- add CFLAG 'SQLITE_ENABLE_MATH_FUNCTIONS' introduced with 3.35.0 to
activate math functions in sqlite.exe
- add check function
> sqlite(3.35.1): amend config

- mingw-w64-igraph/0001-igraph-0.9.0-link-libm-only-when-needed.patch
- mingw-w64-igraph/PKGBUILD
* PKGBUILD
- upgrade to 0.9.0
- move mandatorily from build system autoconf to cmake
- use internal libraries to reduce package dependencies
- remove unneccessary make dependencies 'bison' and 'flex'
- fix link bug by removing explicit link against libm (using patch)
* 0001-igraph-0.9.0-link-libm-only-when-needed.patch
- patch checking if explicit link against libm is needed fixing link error
> igraph: Update to 0.9.0

- mingw-w64-ghdl/PKGBUILD
- mingw-w64-icestorm/PKGBUILD
- mingw-w64-iverilog/PKGBUILD
- mingw-w64-prjtrellis/PKGBUILD
- mingw-w64-serial-studio/PKGBUILD
- mingw-w64-verilator/PKGBUILD
- mingw-w64-yosys/PKGBUILD
In this PR several EDA tools are updated: verilator, ghdl, yosys, iverilog, icestorm, prjtrellis and serial-studio.
> Update several EDA tools

- .ci/ci-generate-srcinfo.py
- .github/workflows/main.yml
- README.md
- mingw-w64-wxWidgets3.1/PKGBUILD
Update the scripts used in CI, for avoiding warnings due to the deprecated MINGW_INSTALLS envvar.
> MINGW_INSTALLS is deprecated, use MINGW_ARCH instead

- mingw-w64-nextpnr/PKGBUILD
Due to the issues for building ECP5 deps on 32 bits (see #7568), in this PR the architecture is enabled on MINGW64 only. At the same time, the package is updated.
> nextpnr: enable ARCH 'ecp5' (prjtrellis) on MINGW64

- mingw-w64-zig/PKGBUILD
- Fix support for mingw libraries, but needs to depend on the [clang-cpp library](https://github.com/ziglang/zig/wiki/Troubleshooting-Build-Issues).
- ucrt64 support added
> Zig - mingw support fixed

- mingw-w64-python-build/PKGBUILD
- mingw-w64-python-faker/PKGBUILD
- mingw-w64-python-hypothesis/PKGBUILD
- mingw-w64-python-importlib-metadata/PKGBUILD
- mingw-w64-python-nuitka/PKGBUILD
- mingw-w64-python-numpy/PKGBUILD
- mingw-w64-python-pytest-checkdocs/PKGBUILD
- python-build: update to 0.3.1.post1
- python-faker: update to 7.0.0
- python-hypothesis: update to 6.8.3
- python-importlib-metadata: update to 3.9.1
- python-nuitka: update to 0.6.13.2
- python-numpy: update to 1.20.2
- python-pytest-checkdocs: update to 2.5.0
> Update Python Packages

- mingw-w64-binutils/0500-fix-weak-undef-symbols-after-image-base-change.patch
- mingw-w64-binutils/PKGBUILD
example: relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `strtoflt128'
Fixes #7023
> binutils: backport fix for "relocation truncated to fit" errors

- mingw-w64-ghdl/PKGBUILD
Update GHDL for providing synth option `raw-vhdl` (added a few days ago).
> ghdl: update to 1.0.0.r122.g1c17875a

- mingw-w64-opus/PKGBUILD
In theory Fixes https://github.com/msys2/MINGW-packages/issues/8240 as `-lssp` is at the end of `Libs.private:`
> opus: add lssp to the end of libs.private

- mingw-w64-boost/PKGBUILD
- mingw-w64-boost/boost-1.75-dont-set-msvcrt-version.patch
This is internal and in case it doesn't match the crt just wrong.
Fixes #8283
> boost: don't define __MSVCRT_VERSION__

- mingw-w64-openlibm/PKGBUILD
Fixed unresponsive outdated `url`.
> openlibm: Update to 0.7.5

- mingw-w64-ncurses/PKGBUILD
ncurses calls access() with X_OK in various places which isn't supported
on Windows. mingw-w64 ships with a wrapper which does if __USE_MINGW_ACCESS
is defined, so use that for now.
> ncurses: build with __USE_MINGW_ACCESS to fix the ucrt build

- .github/workflows/main.yml
See
https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/#expressions-in-jobcontinue-on-error
https://github.com/msys2/MINGW-packages/commit/4e952a7445daa0fb9df229ea61b69ccee3264d4a#r49357293
> CI: move continue-on-error from steps to job

- mingw-w64-cmake/PKGBUILD
This causes cmake to use system libs rather than bundled sources when it bootstraps itself.  This probably doesn't matter much, unless one of those libs has been patched for the system (as I need to do for libuv on aarch64).
Also disable some makedepends for ucrt and clang.  I guess I'm not the only one who hasn't gotten qt5 and emacs built 😜
> cmake: bootstrap using system libs.

- mingw-w64-libffi/0001-Fix-building-for-aarch64-windows-with-mingw-toolchai.patch
- mingw-w64-libffi/0002-Use-__builtin_ffs-instead-of-ffs-554.patch
- mingw-w64-libffi/0003-win64_armasm-Fix-the-spelling-of-ALIGN-553.patch
- mingw-w64-libffi/0004-arm-Fix-the-clang-specific-version-of-the-assembly-5.patch
- mingw-w64-libffi/PKGBUILD
This applies 4 upstream commits related to aarch64 mingw support.
> libffi: backport support for aarch64 mingw

- mingw-w64-libgcrypt/PKGBUILD
- mingw-w64-nettle/PKGBUILD
- mingw-w64-openssl/PKGBUILD
- mingw-w64-openssl/openssl-1.1.1-mingw-arm.patch
Arches can be added to case statements once assembly support is added.
Openssl is a little different, and specifically handles arm because it 'needs' to know 32 vs 64-bit.
> Disable assembly on new arches

- mingw-w64-swig/PKGBUILD
The swig docs say that the languages are only necessary to run the test
suite or build the examples, so move them from `makedepends` to
`checkdepends`.
So that `checkdepends` actually means something, add a check function to
run swig's test suite, which takes a long time and is expected to give errors.
Some thought could be given to expanding `checkdepends` in the future,
adding more languages, and also boost.
> swig: move languages to checkdepends.

- mingw-w64-icu/0024-mingw-no-Bsymbolic.patch
- mingw-w64-icu/PKGBUILD
- mingw-w64-libxml2/PKGBUILD
- mingw-w64-libxml2/libxml2-disable-version-script.patch
- mingw-w64-lua/PKGBUILD
- mingw-w64-lua/link-implib.patch
- mingw-w64-mpdecimal/PKGBUILD
- mingw-w64-sqlite3/Makefile.ext.in
- mingw-w64-sqlite3/PKGBUILD
- mpdecimal: remove `-fPIC`, unsupported on Windows. (I guess that's for clang, not lld.  Oops)  Fixes msys2/CLANG-packages#5
- sqlite3: remove `--no-undefined` linker option, which is unknown to lld on Windows (Windows doesn't allow undefined symbols in shared libraries)  Fixes msys2/CLANG-packages#10
- libxml2: patch out version script linker option, unsupported on Windows.  Fixes msys2/CLANG-packages#19
- lua: link to import library, lld does not support linking directly to a DLL.
- icu: remove `-Bsymbolic` linker flag, which lld on Windows does not accept.  It appears to be an ELF-specific option.  Fixes msys2/CLANG-packages#22
> fixes for LLD support

- mingw-w64-jemalloc/003-mingw-non-x86.patch
- mingw-w64-jemalloc/PKGBUILD
- mingw-w64-libuv/PKGBUILD
- mingw-w64-libuv/libuv-win-atomics-non-x86.patch
- mingw-w64-python-cffi/PKGBUILD
- mingw-w64-python-cffi/mingw-non-x86.patch
- mingw-w64-z3/005-fix-clang.patch
- mingw-w64-z3/PKGBUILD
- libuv: on Windows non-x86, use a gcc/clang atomic builtin instead of inline assembly.  Fixes msys2/CLANG-packages#16
- jemalloc: extend gcc/clang builtin options for LLP64 model.  Fixes msys2/CLANG-packages#18
- python-cffi: has a `__sync_synchronize` barrier, which is disabled on i386, x86_64 or WIN32.  ARM has a different memory model than x86, so remove the WIN32 exception and allow `__sync_synchronize` except on i386 or x86_64 (if it compiles).
- z3: some issue on Mac with XCode 5 caused them to disable intrinsics on clang.  They seem to be fine on Windows, and even required on i686, so remove the `__clang__` check.  Fixes msys2/CLANG-packages#27
> Use gcc/clang builtins/instrinsics

- mingw-w64-python-setuptools/0007-windows-arm64.patch
- mingw-w64-python-setuptools/PKGBUILD
- mingw-w64-python/4000-clang-arm64.patch
- mingw-w64-python/PKGBUILD
Many places check for the string 'GCC' in sys.version to identify a 'posix' build, so make Clang masquerade as GCC.  Also, Clang's __VERSION__ string is very long (including the git repo and commit hash), which caused python to truncate sys.version so that the `64-bit (AMD64)` or `(ARM64)` was missing.  Add some preprocessor hackery to generate a simple 3 part version number.
Speaking of `(ARM64)` tag, teach python-setuptools to recognize that and provide -arm64 variants of the launcher exes.
Remove anchor from regex for extracting version number from -v/--version output.  The presence of a git commit hash in LLD's ld -v output was confusing it.  This doesn't seem entirely safe, but solves the immediate problem.
set CC to clang on clang prefix, to enable python's configure tests to enable …
> python support for clang and arm64

- mingw-w64-libssh2/PKGBUILD
- mingw-w64-libssh2/fix-configure-ac.patch
- mingw-w64-libunistring/PKGBUILD
- mingw-w64-pcre/PKGBUILD
autoreconf in several packages to get updated libtool which supports clang.  Fixes msys2/CLANG-packages#9
> clang libtool fixes

- mingw-w64-qt5/PKGBUILD
according to the docs it's only needed for building qtwebkit which
is a different package.
> qt5: don't makedepend on ruby

- mingw-w64-github-cli/PKGBUILD
That was fast. The .0 version came out only yesterday...
And we may want to wait a couple of days, as [v1.9.2 might be needed soon, too](https://github.com/cli/cli/issues/3431).
[EDIT] @lazka [suggested](https://github.com/msys2/MINGW-packages/pull/8376#issuecomment-820988630) that it's not a burden to have a quick release cadence, so I'll mark this as ready to review.
> github cli v1.9.1

- mingw-w64-ripgrep/PKGBUILD
Uses git tag because tar fails with symlinks
> ripgrep: add ripgrep

- mingw-w64-freeimage/FreeImage-3.17.0_mingw-makefiles.patch
- mingw-w64-freeimage/PKGBUILD
don't hardcode the include prefix
> freeimage: ucrt fixes

- mingw-w64-argtable/PKGBUILD
This package defines an internal enum to `EOVERFLOW` which already exists. Simply renaming it fixes the build.
> argtable: fix build

- mingw-w64-boost/PKGBUILD
- mingw-w64-boost/boost-1.75-mingw-clang.patch
tools/build/engine/build.sh uses `gcc -dumpmachine` to determine the
CHOST, but clang reports <arch>-w64-windows-gnu not <arch>-w64-mingw32
like gcc.
Fixes msys2/CLANG-packages#24
> boost: detect windows-gnu as mingw

- mingw-w64-liblastfm/PKGBUILD
- mingw-w64-liblastfm/versioned-dlls-mingw.patch
The include dir and the library name should have a '5' suffix, see https://archlinux.org/packages/extra/x86_64/liblastfm-qt5/
This is what other software expect, i.e. Clementine player:
https://github.com/clementine-player/Clementine/blob/8258c78c0b930e2c227c35075b6ad4b2ac615f17/CMakeLists.txt#L84
> liblastfm: add proper suffix for the Qt5 version as done in Arch

- mingw-w64-ffmpeg/PKGBUILD
drops external libwavpack support (uses an internal one now):
https://github.com/FFmpeg/FFmpeg/commit/45070eec4c089b06947f07e25cdb1bc8b2102553
though some disagree: https://hydrogenaud.io/index.php?topic=120038.0
> ffmpeg: Update to 4.4

- mingw-w64-prjtrellis/PKGBUILD
Coming from #8414, it seems that the patch that @mati865 commented did already land in MSYS2. So, this update now works without ugly tweaks.
> prjtrellis: switch from gcc to clang

- mingw-w64-odt2txt/PKGBUILD
was not using ${MINGW_PACKAGE_PREFIX}
> odt2txt: fix messed up depends

- mingw-w64-clang/PKGBUILD
Fixes msys2/CLANG-packages#37.  May help msys2/CLANG-packages#34
> clang: enable sanitizers on clang prefix, and large-address-aware on 32-bit

- mingw-w64-gcc/PKGBUILD
- mingw-w64-libssp/PKGBUILD
- mingw-w64-libssp/libssp-Makefile
- mingw-w64-xapian-core/PKGBUILD
- mingw-w64-xapian-core/dont-set-msvcrt-version.patch
Provides gcc's libssp for clang prefixes.  Fixes msys2/CLANG-packages#40
Borrowed heavily from llvm-mingw.  Thanks to @mstorsjo!
My thought is that gcc-libs should provide libssp, and then packages that need it can depend on libssp (or makedepend if they link it statically).
gcc prefixes blow up trying to install the package as it conflicts with gcc files.  Don't know what if anything I can do about that.  I tried making it conflict with gcc-libs, but libc++ provides that so it conflicted with libc++ ☹️
> libssp: new package.

- mingw-w64-doxygen/PKGBUILD
Neither clang nor ucrt has qt5 available yet.
> doxygen: disable qt dependency/wizard on ucrt.

- mingw-w64-ucl/PKGBUILD
Another low-hanging -fPIC removal, for building with clang
> ucl: remove -fPIC

- mingw-w64-gobject-introspection/0028-no-rpath-on-nt.patch
- mingw-w64-gobject-introspection/PKGBUILD
lld does not recognize that argument, and it's an ELF thing anyway.
> gobject-introspection: don't use -rpath on nt

- mingw-w64-flac/Do-not-assume-that-sys-param.h-defines-MIN-and-MAX.patch
- mingw-w64-flac/PKGBUILD
flac expected that if sys/param.h exists, that it contains macros MIN and
MAX.  mingw-w64's doesn't appear to, so backport a commit that fixes
that assumption.
> flac: depend on libssp, and work around no MIN/MAX

- mingw-w64-opusfile/PKGBUILD
This package built for clang, but then opus-tools failed to build
because there was only a static libopusurl.
This will allow opus-tools to build under clang, if it is attempted again after this is merged.
> opusfile: autoreconf for clang

- mingw-w64-neon/PKGBUILD
- mingw-w64-neon/neon-0.31.2-configure-stdcall.patch
They were applying __stdcall to an implicitly declared function call.
Instead, include the header and call the function normally.
> neon: fix configure test for stdcall function

- mingw-w64-meson/0004-fix-gtk-doc.patch
- mingw-w64-meson/PKGBUILD
Unfortunately, meson parses -Wl,-rpath args itself to set the PATH, so I
couldn't keep it from generating them, I had to filter them out after it
did its handling.
This allows graphene and json-glib to build for me on clang64 (which failed in autobuild recently due to this issue)
> meson: don't pass rpath to gtk-doc on Windows

- mingw-w64-libgphoto2/PKGBUILD
- mingw-w64-libgphoto2/libgphoto2-configure-ws232.patch
I disabled the generation of internal documentation in the configure because it cause the build to fail.
> libgphoto2: Update to 2.5.27

- mingw-w64-pdcurses/004-link-implib.patch
- mingw-w64-pdcurses/PKGBUILD
Don't set LINK, it seems to confuse clang/lld, and defaults to $CC anyway
Link to import library, not DLL, for lld compatibility.
> pdcurses: fix building with clang

- mingw-w64-arm-none-eabi-gdb/PKGBUILD
- mingw-w64-cjson/PKGBUILD
- mingw-w64-gdb/PKGBUILD
- mingw-w64-libressl/PKGBUILD
A few more packages that need libssp, that I found in the last run through autobuild.
I also adjusted gdb so that it is not in the toolchain group on clang prefixes.  It should be perfectly safe to install on a clang prefix (unlike gcc or binutils), but lldb is the toolchain's debugger there.
> more libssp dependencies

- mingw-w64-ruby/0006-autoconf-set-msvcrt-ver-for-ucrt.patch
- mingw-w64-ruby/PKGBUILD
> ruby: Workaround for ucrt.

- mingw-w64-libdeflate/001-libdeflate-makefile-mingw-fix.patch
- mingw-w64-libdeflate/PKGBUILD
- mingw-w64-libpng/PKGBUILD
- mingw-w64-libtiff/PKGBUILD
libdeflate:
- Detect mingw as -windows-gnu in addition to -mingw
- Don't include -Wl,--add-stdcall-alias for clang (identified by -windows-gnu)
libpng:
- autoreconf for clang shared library
```diff
--- /dev/fd/63	2021-05-02 02:13:32.000000000 +0000
+++ /dev/fd/62	2021-05-02 02:13:32.000000000 +0000
@@ -1,5 +1,6 @@
/clang64/
/clang64/bin/
+/clang64/bin/libpng16-16.dll
/clang64/bin/libpng16-config
/clang64/bin/libpng-config
/clang64/bin/png2pnm.exe
@@ -18,7 +19,9 @@
/clang64/include/pnglibconf.h
/clang64/lib/
/clang64/lib/libpng.a
+/clang64/lib/libpng.dll.a
/clang64/lib/libpng16.a
+/clang64/lib/libpng16.dll.a
/clang64/lib/pkgconfig/
/clang64/lib/pkgconfig/libpng.pc
/clang64/lib/pkgconfig/libpng16.pc
```
libtiff:
- autoreconf for clang support
- disable libwebp dependency to break cycle. …
> libdeflate, libpng, libtiff: fix clang build

- mingw-w64-gphoto2/PKGBUILD
- mingw-w64-gphoto2/gphoto2-check-popt.patch
The ucrt64 build was failing because the gp-check-popt.m4 macro explicitly tests `MSYSTEM` to be `MINGW32` or `MINGW64`, but not for `UCRT64`. The check is done twice, once for the location of the `popt.h` header file, and once for the library path.
It results in `-I/usr/include` being added to the CPPFLAGS, which causes the compilation to fail. 
I fixed it by adding a test for `UCRT64` and now it works. 
But it is not very robust and will fail if another architecture is added (clang64?).
> gphoto2: Update to 2.5.27, fix ucrt64 build

- mingw-w64-libtiff/PKGBUILD
> libtiff: re-enable libwebp for clang

- mingw-w64-proj/PKGBUILD
This allows libgeotiff to build successfully for clang64
> proj: autoreconf for clang support

- mingw-w64-yaml-cpp/010-no-fPIC.patch
- mingw-w64-yaml-cpp/PKGBUILD
fPIC was causing issues. Fix by using the CMAKE variable instead.
> yaml-cpp: fix compilation with clang64

- mingw-w64-spice-server/PKGBUILD
- mingw-w64-spice/PKGBUILD
Hi,
thanks for your project! I have been working with msys2 since 2 months and I like your distribution. I also like your approach, which allows to get involved easily.
I created this package to run qemu based on msys2 with spice. A few days ago a newer version was released, I will work on it later. Using this package qemu can be run with spice. I use qemu/spice on Linux in my daily work and was happy to see, spice started supporting windows last year.
Sadly there is a bug in qemu, which influences the performance when activating qemu features spice needs.
This is my first package for msys2, but I hope it is acceptable. If there are any issues, I will fix them.
I had to deactivate main parts of test-qxl-parsing. I hope I can fix this in future. For some gstreamer plugins I defined …
> Initial version of package spice-server 0.14.3

- mingw-w64-clang/PKGBUILD
LLVM seems to expect `${CARCH}-w64-windows-gnu`, while `${MINGW_CHOST}` is `${CARCH}-w64-mingw32`
Fixes #8517
It may be better to remove setting LLVM_HOST_TRIPLE altogether, but I want to test a native aarch64 build first (and it'll be a while before my Pi is ready to do that) so proposing this in the meantime.
> clang: change LLVM_HOST_TRIPLE

- mingw-w64-libreplaygain/010-no-fpic.patch
- mingw-w64-libreplaygain/PKGBUILD
> libreplaygain: fix clang64 build

- mingw-w64-djvulibre/PKGBUILD
- mingw-w64-fftw/PKGBUILD
djvulibre: autoreconf for clang
fftw: disable quad precision build for clang (libquadmath is part of gcc)
> package fixes for clang

- mingw-w64-cairo/0030-ucrt-clang-fixes.patch
- mingw-w64-cairo/PKGBUILD
librsvg is only needed for tests which we don't build
> cairo: remove librsvg dep, fix ucrt build

- mingw-w64-pybind11/PKGBUILD
- mingw-w64-starpu/PKGBUILD
- pybind11: makedepends on python-sphinxcontrib-moderncmakedomain
- starpu: depends on libssp
> package dependency fixes

- mingw-w64-librime/PKGBUILD
boost brings in a dependency on icu, so this needs to link it too or
there are undefined symbols.
This failed for gcc as well as clang, I guess boost started pulling in
icu at some point after this was built?
> librime: link in icu

- mingw-w64-distorm/Makefile
- mingw-w64-distorm/PKGBUILD
llvm-strip doesn't want to strip .a files, and the PKGBUILD sets the 'strip' option anyway.
> distorm: remove -s option from install

- mingw-w64-mecab/PKGBUILD
clang claims to be able to link to it, but libtool reveals the truth
that libstdc++ doesn't exist for clang prefixes.
Fixes #8549
> mecab: don't explicitly link to libstdc++

- mingw-w64-cairomm/PKGBUILD
- mingw-w64-libsigc++3/PKGBUILD
This (make)depends on new msys2 package 'mm-common' (msys2/MSYS2-packages#2478) to succeed, since that
contains necessary autoconf macros.
> cairomm, libsigc++3 autoreconf for clang

- mingw-w64-baobab/0001-Build-GUI-application-on-windows.patch
- mingw-w64-baobab/0001-Fix-application-icon-name-in-baobab-main-window.ui.patch
- mingw-w64-baobab/PKGBUILD
Updates baobab to 40.0 and adds patches to fix icon and to build a Windows GUI application instead of a Windows TUI application.
> baobab: update to 40.0

- mingw-w64-leptonica/PKGBUILD
- mingw-w64-tesseract-ocr/PKGBUILD
- mingw-w64-tesseract-ocr/tesseract-no-as-needed.patch
leptonica: autoreconf for clang support
tesseract-ocr: remove `-Wl,--as-needed` linker flag 
according to mesonbuild/meson#4230 this flag and `-Wl,--no-undefined` are silently ignored by binutils LD, but they cause
errors on LLD so remove them.
Unfortunately this is not sufficient for tesseract-ocr to build under clang64, after these fixes it hits #8554
> leptonica, tesseract-ocr clang fixes

- mingw-w64-akira/Avoid-open-cmd-terminal-running-on-windows.patch
- mingw-w64-akira/PKGBUILD
As a GUI app, meson build system needs this flag to avoid opening a cmd terminal with app logs
> Akira: Avoid open cmd terminal running app

- mingw-w64-xalan-c/04-no-std-file.patch
- mingw-w64-xalan-c/PKGBUILD
libcxx as configured does not have std::FILE
> xalan-c: fix compilation with clang

- mingw-w64-helics/PKGBUILD
Update to the HELICS 2.7.0 release
> helics: Update to 2.7.0

- mingw-w64-qemu/PKGBUILD
As already discussed in https://github.com/msys2/MINGW-packages/issues/8567 here my PR for qemu 5.2.0
**Relocation of installation**
{MINGW_PREFIX}/bin/<QEMU_STUFF>
is splitted into
- {MINGW_PREFIX}/lib/qemu
- 	{MINGW_PREFIX}/share/man
- 	{MINGW_PREFIX}/share/locale
- 	{MINGW_PREFIX}/share/icons
- 	{MINGW_PREFIX}/share/applications
- 	{MINGW_PREFIX}/share/doc
- 	{MINGW_PREFIX}/share/licenses
- 	{MINGW_PREFIX}/share/qemu/firmware
Relevant binaries in 
{MINGW_PREFIX}/lib/qemu 
are invocated by identically named wrappers in
{MINGW_PREFIX}/bin
**New feature**
spice is included and can be used if optional dep spice (adds 150MiB extra) is installed
**Package split was not done**
qemu binary package adds 750MiB which includes 250MiB for GDI-doubles (e.g. qemu-system-x86_64.exe and its double …
> mingw-w64-qemu: Enable 5.2.0, spice support, refactor install locations, documentation

- mingw-w64-wxWidgets/004-wxWidgets-3.0-clang-windows-link.patch
- mingw-w64-wxWidgets/PKGBUILD
This is a squash of 2 upstream commits (the first was a failed attempt
to fix this).
> wxWidgets: backport clang on Windows linking fix.

- mingw-w64-qt6-base/PKGBUILD
Qt6 depends (optional) on firebird2 and postgresql which are broken on clang64.
> Fix building qt6 on clang64.

- mingw-w64-gtkwave/PKGBUILD
This PR updates GTKWave to 3.3.109.
At the same time, I had to switch the default back to GTK2, because the GTK3 is barely usable and several users were having a bad experience: gtkwave/gtkwave#61.
> gtkwave: update to 3.3.109

- mingw-w64-ghdl/PKGBUILD
This PR brings several recent updates to GHDL:
- Allow exporting Verilog from VHDL (for synthesis).
- Provide `libghw.dll` and `ghwdump` by default.
- The stack size was increased for the mcode (MINGW32) backend: ghdl/ghdl#1749.
> ghdl: update to 1.0.0.r257.g82665d42

- mingw-w64-emacs/PKGBUILD
Add upstream patch to fix build with latest mingw-w64-headers-git.
> emacs: Add upstream patch to fix build with latest mingw-w64-headers-git

- mingw-w64-clang/0011-nm-version-option.patch
- mingw-w64-clang/PKGBUILD
Fixes msys2/CLANG-packages#39
gnutls is having another issue now with LLVM 12 (which I'm attempting to track down now), but this does fix libidn which had the same nm-parsing issue.
The new gnutls issue is #8646, and the second commit on this PR fixes #8646.
> clang: patch to add version option to nm.

- mingw-w64-aws-c-common/PKGBUILD
Remove -fPIC compiler option for clang.
> aws-c-common: Update to 0.5.5

- mingw-w64-qemu/PKGBUILD
- mingw-w64-qemu/msys2.examples.tests.sh
- mingw-w64-qemu/msys2.readme.txt
Hi,
this PR updates from qemu 5.2.0 to 6.0.0
The new build and target file structure introduced with 5.2.0 was not touched. 
The packaging was simpified and hardenend: It relies more on standard (configure-script) than before, using its path-configurations. Only few folder moves are necessary to relocate misplaced dirs.
Most operations are done in $pkgdir now to use simple paths and to harden the operations
I introduced a msys2.readme.txt to communicate infos and problems and a msys2.examples.tests.sh give qemu examples and simplify testing for next release change. I don't know if this is acceptable, but in my opinion it would help.
As I documented in msys2.readme.txt, 
`qemu-system-x86_64 -accel whpx`
in qemu 6.0.0 leads to error messages like
```
WHPX: setting APIC emulation mode in the …
```
> Update to qemu 6.0.0, simplify and harden packaging, provide information and examples/tests

- mingw-w64-mpg123/PKGBUILD
As a follow up of the last update I've noticed that the configure script looks for SDL2 before the old SDL, so it would be better to upgrade the dependency
> mpg123: depend on SDL2 instead of SDL

- mingw-w64-gtkwave/PKGBUILD
As discussed in https://github.com/ghdl/ghdl/issues/1756, recently ghwdump was added to the GHDL package. The same binary was provided by package GTKWave already. Therefore, there is now a conflict that prevents users of these packages from updating their MSYS2 installations.
After getting feedback from GHDL and GTKWave maintainers and contributors, this PR removes the ghwdump binary from the GTKWave package.
> gtkwave: do not install ghwdump

- mingw-w64-qemu/PKGBUILD
- mingw-w64-qemu/msys2.examples.tests.sh
- mingw-w64-qemu/msys2.readme.txt
Build of qemu-6.0.0 fails on staging build because of switch to sphinx 4.0.1:
doc generation fails, because qemu-6.0.0 meson.build can't handle sphinx 4.0.1
qemu build fails because directory share/doc/qemu not created by doc generation
This is fixed by creating each dir in package with mkdir -p before moving/copying.
Other fixes are included as well.
> mingw-w64-qemu: Fix build with sphinx 4.0.1 and other fixes/enhancements

- mingw-w64-ngraph-gtk/PKGBUILD
new upstream release version 6.09.02.
> ngraph-gtk: new upstream release version 6.09.02.

- mingw-w64-qemu/PKGBUILD
- mingw-w64-qemu/msys2.examples.tests.sh
This PR bumps pkgrel to build once more after fix of https://github.com/msys2/MINGW-packages/issues/8685 finally reached the repository.
Additionally the examples I provided recently were improved: no more deprecations on execution and more information
> qemu: Bump for rebuild to reinclude docs after build dep fix

- mingw-w64-gtk-vnc/PKGBUILD
- mingw-w64-gtk-vnc/gvncviewer-1.2.0.patch
Turns out the expected application in the package was hidden like an easter egg
> gtk-vnc: Activate installation of expected but missing gvncviewer

- mingw-w64-github-cli/PKGBUILD
It was just released: https://github.com/cli/cli/releases/tag/v1.10.0
> gh: update to v1.10.0

- mingw-w64-dav1d/PKGBUILD
Only a single addition to the API, so backwards compatible (minor version change)
https://code.videolan.org/videolan/dav1d/-/commit/a98f5e6056568de9125c1fbb4f63f525b95e30b1
> dav1d: update to 0.9.0

- mingw-w64-poppler/010-clang.patch
- mingw-w64-poppler/PKGBUILD
clang doesn't like mismatching volatile pointers.
> poppler: fix compilation with clang

- mingw-w64-rust/PKGBUILD
> rust: depend on libxml2

- mingw-w64-libvirt/PKGBUILD
With mingw-w64-clang 12.0.0-5 that's all that's necessary.
> libvirt: depend on libssp

- mingw-w64-ffts/PKGBUILD
- mingw-w64-scopehal-apps/PKGBUILD
This PR adds [azonenberg/scopehal-apps](https://github.com/azonenberg/scopehal-apps): glscopeclient and other client applications for libscopehal. [azonenberg/scopehal](https://github.com/azonenberg/scopehal) is an oscilloscope / logic analyzer platform abstraction library. scopehal-apps depends on [anthonix/ffts](https://github.com/anthonix/ffts). Therefore, in this PR package ffts is added too.
Build instructions on MSYS2 are provided in https://www.antikernel.net/temp/glscopeclient-manual.pdf (sec 3.4.2).
I'm unsure about some decisions, so I'll mark this as a draft for now.
@azonenberg would you mind helping me answer the following questions?
- Are the `depends` and `makedepends` lists of scopehal-apps correct?
- ~~Why is FTTS built with `DENABLE_SHARED=ON`, if scopehal-apps uses the …
> add scopehal-apps

- mingw-w64-spice/PKGBUILD
Update to 0.15.0 includes
* Add C++ Flags
* Fix description
* Add more meaningful comments
* Don't deactivate failing tests, they are not executed on CI
* Harden base dirs
* Be verbose on copying
* Reduce build verbosity
* Cleanup script
> mingw-w64-spice: Update to 0.15.0

- .github/workflows/main.yml
For some reason it seems to have stopped being installed, so do it explicitly.
Fixes msys2/MSYS2-packages#2524
> ci: explicitly install pactoys-git

- mingw-w64-glibmm/PKGBUILD
- mingw-w64-glibmm/glibmm-2.66.1-no-export-deleted-methods.patch
Don't try to dllexport deleted methods.
https://gitlab.gnome.org/GNOME/glibmm/-/issues/92
> glibmm: fix build with clang

- mingw-w64-curl/PKGBUILD
adapt `_variant_config` to https://github.com/curl/curl/pull/6897
also separate static and shared builds because `0002-nghttp2-static.patch` only works with shared build disabled.  Fixes #8774
> curl: update to 7.77.0

- mingw-w64-cfitsio/PKGBUILD
3.48 > 3.450
MINGW32 & MINGW64 are stuck at the older version, while UCRT64 and CLANG64 have just the newer one built
> cfitsio: needs epoch

- mingw-w64-ngspice/PKGBUILD
- mingw-w64-ngspice/no-explicit-lstdc++.patch
This started out just being an autoreconf, but turned into a can of worms...
ngspice was trying to explicitly link in libstdc++, which causes issues with Clang prefix (which uses libc++ but pretends to have libstdc++) and libtool (that goes looking for the actual files, which it can't find).  The reason that ngspice probably does this is that libtool decided to link it as C instead of C++.  Work around this as documented in https://www.gnu.org/software/automake/manual/html_node/Libtool-Convenience-Libraries.html by inventing a "dummy" C++ source file that does not actually have to exist.
After that, for some reason it seemed to not try to link gdi32 and comdlg32 into static ngspice.exe.  Explicitly add them to LDADD.
That worked for Clang, but GCC decided to still complain about a couple …
> ngspice: fix clang build

- mingw-w64-python3.9/4010-MINGW-stack-reserve.patch
- mingw-w64-python3.9/PKGBUILD
https://bugs.python.org/issue40458 was happening on CLANG64 (test_pickle was crashing due to Windows stack overflow exception)
Also, get rid of no-longer-needed setting of CC and CXX for clang support (no longer needed after msys2/MSYS2-packages#2501)
> python3.9: reserve 2MB of stack space

- mingw-w64-indent/PKGBUILD
- mingw-w64-indent/indent-2.2.12-fix-file-read-loop.patch
Indent 2.2.12 would end up in an endless loop if indenting a file with CR/LF line endings.
This happens when the file is read, where all CR/LF line endings are converted to LF only. This results in fewer bytes read than the file size indicates. A while loop keeps trying to read the "missing" bytes, but read returns 0.
This fix stops the while loop when there is no more to read.
> indent: Fix endless file read loop

- mingw-w64-crt-git/0001-headers-add-AV1-support-to-dxva.h.patch
- mingw-w64-crt-git/PKGBUILD
- mingw-w64-headers-git/0001-headers-add-AV1-support-to-dxva.h.patch
- mingw-w64-headers-git/PKGBUILD
Adds a patch that is currently not in mingw-w64 nor wine for adding av1
decoding support via dxva. This is useful for FFmpeg to decode using
their hwaccel.
From https://www.winehq.org/pipermail/wine-devel/2020-September/173175.html and used in https://github.com/BtbN/FFmpeg-Builds/commit/0df2644223a5d3f775b4e25d027a3dc4446caefe
> mingw-w64-headers-git: add patch for av1 with dxva

- mingw-w64-libogg/PKGBUILD
Latest patch release: https://gitlab.xiph.org/xiph/ogg/-/tags/v1.3.5
> libogg: update to 1.3.5

- mingw-w64-breeze-icons-qt5/PKGBUILD
It needs python with lxml to build 24px icons.  Unfortunately once it's finding the right python, actually building the icons is failing with a file not found error.
```
File "C:/_/mingw-w64-breeze-icons-qt5/src/breeze-icons-5.75.0/generate-24px-versions.py", line 193, in <module>
sys.exit(main())
File "C:/_/mingw-w64-breeze-icons-qt5/src/breeze-icons-5.75.0/generate-24px-versions.py", line 174, in main
tree.write(file_destination, method="xml", pretty_print=True, exclusive=True)
File "src/lxml/etree.pyx", line 2057, in lxml.etree._ElementTree.write
File "src/lxml/serializer.pxi", line 746, in lxml.etree._tofilelike
File "src/lxml/serializer.pxi", line 813, in lxml.etree._create_output_buffer
File "src/lxml/serializer.pxi", line 803, in …
```
> breeze-icons-qt5: try to convince cmake to use mingw python

- mingw-w64-leptonica/PKGBUILD
@lazka Ok that the CLANG32 dependencies are not available? Or are they to be regenerated?
> leptonica: Upgrade to 1.18.1

- mingw-w64-wined3d/PKGBUILD
This should have been required for gcc 10, but is definitely required
for clang.
Note on `CLANG*` this requires mingw-w64-clang >= 12.0.0-6 for the fix for msys2/CLANG-packages#43
> wined3d: add -fcommon to CFLAGS

- mingw-w64-usql/PKGBUILD
checkdepends are only installed when check is going to be run, but the tests are built in build() regardless.
> usql: makedepends on checkdepends

- mingw-w64-ghdl/PKGBUILD
~~Just a regular update.~~
Update pyGHDL.dom, which provides a Document Object Model (DOM) for the VHDL language written in Python: [vhdl/pyVHDLModel](https://github.com/vhdl/pyVHDLModel).
> ghdl: update to 1.0.0.r348.g7d5c6c48

- mingw-w64-curl/0001-Make-cURL-relocatable.patch
The code to make cURL relocatable simplifies/normalizes paths, e.g. reducing multiple forward slashes to a single one.
This is okay in general, but at the beginning of the path, a double slash has a special meaning: it denotes a UNC path of the form
`//<host>/<path>`. It would therefore be a mistake to reduce those first two slashes to a single one: otherwise it would refer to the absolute path relative to the current directory's drive.
Original report: https://github.com/git-for-windows/git/issues/3266
So sad that I cannot Cc: the original author of the `pathtools.c` file. 😞
> curl: preserve UNC paths when normalizing/simplifying

- mingw-w64-verilator/0001-Fix-V3Hash-when-building-m32.patch
- mingw-w64-verilator/PKGBUILD
See verilator/verilator-announce#47.
> verilator: update to 4.204

- mingw-w64-ngraph-gtk/PKGBUILD
new upstream release version 6.09.03.
> ngraph-gtk: new upstream release version 6.09.03.

- mingw-w64-libxslt/0009-fix-xml2-config-check-in-configure.patch
- mingw-w64-libxslt/PKGBUILD
This new patch was applied upstream almost two years ago here:
https://gitlab.gnome.org/GNOME/libxslt/-/commit/90c34c8bb90e095a8a8fe8b2ce368bd9ff1837cc
Without the patch a clean UCRT64 build (no previously installed UCRT64 packages) fails with:
```
checking for x86_64-w64-mingw32-xml2-config... no
checking for xml2-config... /ucrt64/bin/xml2-config
configure: error: Could not find libxml2 anywhere, check ftp://xmlsoft.org/.
```
I verified, that the build issue is currently present on my local system as well as on github: https://github.com/larskanis/MINGW-packages/runs/2861341540?check_suite_focus=true
With this patch the build succeeds: https://github.com/larskanis/MINGW-packages/runs/2858716280?check_suite_focus=true
In addition to the build failure the current UCRT64 package …
> libxslt: Fix build failure and date/time issue in libxslt

- mingw-w64-clang/0014-llvm-rc-Don-t-rewrite-the-arch-in-the-default-triple.patch
- mingw-w64-clang/PKGBUILD
Fixes msys2/CLANG-packages#46
NOTE: this bug causes `CLANG32` to fail to build clang.  It can be built by first downgrading to 12.0.0-5.  @lazka how can this be handled?
> clang: llvm-rc don't rewrite default arch

- mingw-w64-mesa/PKGBUILD
Also explicitly disable CLonD3D12 just to be safe as build may fail in the future if Meson gains the ability to discover clang via cmake with MinGW like it does with MSVC.
> Update Mesa3D to 21.1.3

- mingw-w64-libtiff/PKGBUILD
CLANG32 and CLANGARM64 do not yet have libwebp.  Due to a circular
dependency between libwebp and libtiff, the dependency needs to be
disabled here to enable building.  While CLANGARM64 is not yet
attempting to build these packages, it seems to make sense to include it
here now.
Also enabled libtiff for CLANG32
> libtiff: disable libwebp dependency for new clang prefixes

- mingw-w64-python3.9/0097-Don-t-use-os.pathsep-to-find-EOF.patch
- mingw-w64-python3.9/PKGBUILD
- mingw-w64-python3.9/update-patches.sh
Fix a part of https://github.com/msys2/MINGW-packages/issues/8756
> python3.9: don't use os.pathsep for EOF

- mingw-w64-nextpnr/PKGBUILD
- mingw-w64-prjtrellis/PKGBUILD
- mingw-w64-yosys/PKGBUILD
This PR updates Yosys, prjtrellis and nextpnr. Since Yosys depends on GHDL, it is desirable to wait until that one is uploaded (https://packages.msys2.org/package/mingw-w64-x86_64-ghdl-llvm?repo=mingw64) before merging this PR. For that reason, I'll keep it as a draft.
> Update Yosys, prjtrellis and nextpnr

- mingw-w64-grpc/0003-abseil-Include-pthread-header.patch
- mingw-w64-grpc/PKGBUILD
- Remove `--disable-dynamicbase`/`--default-image-base-low` workaround for gcc (weak symbol issue was fixed in binutils)
- Define `STRSAFE_NO_DEPRECATE` to fix conflict with libc++
- Disable shared builds for clang prefix, as there's an attempt to use a TLS variable across DLL boundaries, which is not supported for clang (or visual studio for that matter).  See https://github.com/msys2/MINGW-packages/pull/8653#issuecomment-857408252
> grpc: fix clang build

- mingw-w64-grpc/PKGBUILD
`--disable-dynamicbase,--default-image-base-low` appear to still be required.
Fixes #8984
> grpc: add back LDFLAGS workarounds.

- mingw-w64-gtkwave/PKGBUILD
Note that ghwdump is now distributed with GHDL, so it was removed from the gtkwave `make install`.
> gtkwave: update to 3.3.110

- mingw-w64-aom/PKGBUILD
- mingw-w64-assimp/PKGBUILD
- mingw-w64-wxWidgets/PKGBUILD
- mingw-w64-wxWidgets3.1/PKGBUILD
- mingw-w64-xalan-c/PKGBUILD
This passed in CI on my fork.  The PR will give it another test in CI, and then hopefully it will work under autobuild.  (`aom` without these changes would succeed in CI but fail under autobuild.)
> try limiting clang32 to -j1 for packages known to have address space issues with lld

- mingw-w64-freetype/PKGBUILD
Breaks a circular dependency between freetype and harfbuzz.
Also added clang32 to mingw_arch at the same time
> freetype: disable harfbuzz on new clang prefixes.

- mingw-w64-libtiff/PKGBUILD
libwebp is now available there.
> libtiff: enable libwebp dependency for clang32

- mingw-w64-sip/PKGBUILD
My PKGBUILD knowledge is somewhat lacking, but it seems to me that sip should not `replace` sip4, as sip4 still exists as a package (and is necessary to build the latest release of wxPython at least).  Note that sip declares to `conflict` with sip4, but not vice-versa, hopefully that is ok.
Also, the current development branch of wxPython now depends on sip 5.5, so if/when this winds up being released we may need to resurrect the sip5 package, and then remove the `replaces` sip5 here as well.
> sip: remove replaces sip4, sip4 still exists as a package

- mingw-w64-perl/PKGBUILD
profile="/etc/profile.d/z-${_realname}-${MINGW_PACKAGE_PREFIX/mingw-w64-}.sh"
/etc/profile.d/z-perl-x86_64.sh exists in filesystem owned by mingw-w64-x86_64-perl.
> perl: Fix file conflicts

- mingw-w64-vcdimager/PKGBUILD
I have *no* idea how this built on CLANG64...
See also #9011
> vcdimager: disable version script on clang.

- mingw-w64-qt6-declarative/PKGBUILD
Also switch to cmake --build instead of calling ninja explicitly.
This package built successfully on my 8 logical processor machine, so no workaround for non-CI.
> qt6-declarative: limit to -j1 in CI for CLANG32

- mingw-w64-gdcm/0002-cmake-config-destination.patch
- mingw-w64-gdcm/0008-cmake-use-mingw-getopt.patch
- mingw-w64-gdcm/PKGBUILD
Use CMake to disable getopt linking conflict which replaces the multiple
definition workaround in 28016b68b3c7057c4cee10c66e48402f0396042b commit.
> gdcm: Fix build with clang, use ninja.

- mingw-w64-perl/007-use-winsock-socket-functions.patch
- mingw-w64-perl/008-ucrt-stdio-internals.patch
- mingw-w64-perl/PKGBUILD
Changes:
* Check mingw-w64 to disable the conflicting inet_pton and inet_ntop.
* Enable ip_mreq, ipv6_mreq and ip_mreq_source in Socket module.
* Remove the unneeded hunks for MSVC.
* Rebase patches.
> perl: Update winsock patch to add ip_mreq

- mingw-w64-gcc/0204-x86-Add-__cpuidex-and-include-guard-to-cpuid.h.patch
- mingw-w64-gcc/PKGBUILD
> gcc: backport patch for cpuid.h header guard

- mingw-w64-libvips/PKGBUILD
This removes the dependency to `opencl-icd` for two reasons:
- `opencl-icd` is not available in the UCRT64 repository
- I could not find any use of that library within libvips
I hope the UCRT64 build can be triggered that way (in addition to MINGW32+MINGW64).
> Update libvips to 8.11.2

- mingw-w64-gcc/0205-x86-Add-include-gard-to-cpuid.h.patch
- mingw-w64-gcc/PKGBUILD
Applies just the include guard parts of the patch from #9032, to avoid
the conflict with mingw-w64 defining `__cpuidex`.
> gcc: add include guard to cpuid.h

- mingw-w64-cmake/PKGBUILD
- mingw-w64-cmake/f90d15458a9a98180fcc95158f2ab5d2b1ad3152.patch
Merged upstream already, so it will probably be dropped in 3.22
> cmake: Add patch for findglut

- mingw-w64-gtk2/0023-gdkkeys-win32.c-fix-initialisation-of-key_state-in-u.patch
- mingw-w64-gtk2/PKGBUILD
- mingw-w64-gtk3/0005-gdkkeys-win32.c-fix-initialisation-of-key_state-in-u.patch
- mingw-w64-gtk3/PKGBUILD
Upstream issues: 
* https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3741/
* https://github.com/fontforge/fontforge/issues/4577
Definitely required for GTK2, GTK3 seems to deal with IMEs differently and avoids this particular code path, but the underlying GDK calls are still affected. 
e.g. to reproduce (this is against the 32 bit mingw builds - may be relevant because behaviour is dependent on uninitialised state):
* Set keyboard layout to the Japanese IME in half-width alphanumeric/direct input mode
* Open gtk-demo (GTK2 demo)
* Open the 'Dialog and Message boxes' demo
* Type some characters in the text boxes - observe half-width katakana instead of alphanumeric input
> GTK 2/3: Fix keyboard input when using IMEs

- mingw-w64-vala/PKGBUILD
This requires disabling building valadoc.
Also enabled clang32.
> vala: disable graphviz dependency for clang

- mingw-w64-gtk2/0024-gtk-update-icon-cache-rc-quote.patch
- mingw-w64-gtk2/PKGBUILD
- pass --disable-visibility to configure, fixes gdk linker errors
- patch gtk-update-icon-cache.rc generation to quote manifest filename
Fixes #8493 - it built locally, 🤞 for clang32 when it gets enabled.
> gtk2: fixes for clang

- mingw-w64-gcab/PKGBUILD
- mingw-w64-gtk-vnc/PKGBUILD
- mingw-w64-libgusb/PKGBUILD
- mingw-w64-libgusb/windows-lld-no-version-script.patch
Also, libgusb had a version script option that needed disabling.  Meson seems to expose some useful information so only disabled when on Windows and linker is ld.lld.  Note that my patch adds a meson warning:
```
WARNING: Project specifies a minimum meson_version '>=0.46.0' but uses features which were added in newer versions:
* 0.53.0: {'compiler.get_linker_id'}
```
It appears libgusb uses a python script (distributed with meson?) to generate its version script, so it should be possible to make it generate a def file too if someone were so inclined.
> gcab/gtk-vnc/libgusb: depend on libssp

- .github/workflows/main.yml
Per discussion on discord, most use their master branch to mirror
upstream, and do not need CI to run when they sync.
> CI: don't run on master branch on any fork.

- mingw-w64-fftw/PKGBUILD
Clang complains when trying to use sse2 intrinsics when sse2 is not enabled (like on -march=i686, aka pentium pro).
I don't know what other effects this might have, so I only did this on clang32, and I'm guessing there aren't too many non-sse2 machines running around to be bothered if this makes the whole library unable to run on them.
> fftw: enable sse2 for clang32
