msys2/MINGW-packages

.ci/ci-build.sh, .ci/ci-library.sh, mingw-w64-curl/PKGBUILD, mingw-w64-libssh2/PKGBUILD, mingw-w64-libssh2/fix-wincng-multiple.patch
openssl keeps the default name. The other packages have suffixes.
=> curl: Split package to openssl, winssl and gnutls

mingw-w64-ecpprog/PKGBUILD, mingw-w64-ghdl/PKGBUILD, mingw-w64-iverilog/PKGBUILD, mingw-w64-nextpnr/PKGBUILD, mingw-w64-prjtrellis/PKGBUILD, mingw-w64-scopehal-apps/PKGBUILD, mingw-w64-yosys/PKGBUILD
This PR updates several EDA packages at once.
I believe this is an interesting PR for triggering a corner case in CI:
MINGW64 is the only environment where all the tools can be built. Almost all of them are available on MINGW32. However, due to the order, yosys is not tested/built on MINGW32. Precisely, scopehal-apps is built before yosys, but it fails on MINGW32. Since yosys does not depend on scopehal-apps, it should be built regardless of the other one failing.
Similarly, on UCRT64, ghdl fails so all the packages scheduled after it are not tested/built.
I believe these issues are not relevant for the autobuilder, so this PR can be merged.
@Biswa96 with regard to msys2/MINGW-packages#8956, this is a practical example of why it might be desirable to bump packages one-by-one.
=> Update ghdl, yosys, prjtrellis, nextpnr, iverilog, scopehal-apps and ecpprog

mingw-w64-python-numpy/0011-dont-die-if-no-fcompiler.patch, mingw-w64-python-numpy/0012-clang-no-gcc-workaround.patch, mingw-w64-python-numpy/PKGBUILD
Disable BLAS and fortran.  Numpy states both are optional to build, but had an issue in their build scripts if fortran wasn't found.
Add an explicit clang check to a GCC bug workaround for GCC < 8.4, because clang pretends to be a really old GCC version (like 4.x).
We could conceivably use a different BLAS library, if there's a compatible one that doesn't require fortran, but I'm not familiar with them.
=> numpy: fix clang build

mingw-w64-python-numpy/PKGBUILD
The install was missing a few files, including `_numpyconfig.h`.  This is the only thing I can think of that could have caused it.
This does indeed seem to restore the missing files.  Sorry for the breakage, should have paid more attention to the files diff 🤦
=> numpy: remove --skip-build from install step

mingw-w64-perl-win32-api/0001-clang-as-defines.patch, mingw-w64-perl-win32-api/PKGBUILD
From #9179, `as` is really an alias of `clang` so it needs `-Wa,-defsym,...` rather than `-defsym ...`, and also needs `-c` to produce .o file.
=> perl-win32-api: fix build with clang

mingw-w64-file/PKGBUILD
was going to make a PR with a bunch of these, but it seems mingw-w64-file interferes with makepkg and libtool's usage of `file` expecting to be the msys variant.
=> file: autoreconf for clang

mingw-w64-qt6-tools/PKGBUILD
the Qt tools build against libclang-cpp
=> qt6-tools: Add clang as a runtime dependency

mingw-w64-petsc/PKGBUILD
This patch fixes the integration issue with depending packages such as SLEPc caused by switching to a single static library build.
@gharveymn This should (positively in the end) affect sundials.
=> petsc: remove build flavor suffixes from static libraries

mingw-w64-doctest/PKGBUILD
Hey there! This is my first MINGW package, but I've been using PKGBUILD as an AUR packager for years, and maintain doctest in (at least) Fedora and FreeBSD. Hopefully I've followed the guidelines at https://www.msys2.org/wiki/Creating-Packages; let's see what the CI has to say.
This is a C++ header-only unit testing framework. It's used by my project Notcurses (which I'm porting to MINGW as we speak), as well as Wayfire and a few other major ones.
=> initial mingw package of onqtam/doctest 2.4.6

mingw-w64-pyqt6-sip/PKGBUILD, mingw-w64-pyqt6/001-fix-undefined-reference-stat.patch, mingw-w64-pyqt6/PKGBUILD
Somehow the reference to QFileInfo::stat was missing from QtCore shared library.
The only way I have found to fix it is to remove its mention from the sip file.
=> [new-package] PyQt6 6.1.1

mingw-w64-freetds/PKGBUILD, mingw-w64-gc/PKGBUILD, mingw-w64-gtkmm/PKGBUILD, mingw-w64-gtksourceview2/PKGBUILD, mingw-w64-gtksourceviewmm2/PKGBUILD
These packages were missing dlls under clang64 that were present under mingw64, due to the version of libtool embedded in the source not knowing how to deal with llvm and clang.  `autoreconf -fiv` to update their copies of libtool.
gtksourceview2 was being difficult, apparently the newer `gnome-common` m4 macros for `GNOME_COMPILE_WARNINGS` wanted to turn on `-Werror=format-security`, but this package would fail with that.  After struggling trying to fix this, just turned warnings from "maximum" to "minimum" which disables this behavior.
=> autoreconf packages missing dlls, through G

mingw-w64-libopenmpt/PKGBUILD
Bugfix release
https://lib.openmpt.org/libopenmpt/2021/07/04/releases-0.5.10-0.4.22-0.3.31/
=> libopenmpt: update to 0.4.22

mingw-w64-xmlsec/03-fix-ms-configure-tests.patch, mingw-w64-xmlsec/PKGBUILD
looking at file diffs between clang64 and mingw64, noticed mscrypto and mscng were missing on clang.  The issue was that the configure tests were nesting a `main` function inside a `main` function, and clang didn't like that.  Remove the extraneous `main` function around the configure tests.
=> xmlsec: fix mscng/mscrypto configure tests

mingw-w64-spdylay/PKGBUILD
It appears to be required for autoreconf (don't know why this didn't fail in CI), but I checked the DLL and it doesn't depend on libxml2 at runtime.
=> spdylay: add makedepends on libxml2

mingw-w64-fltk/PKGBUILD
Like as [1.3.6](https://www.fltk.org/articles.php?L1754) the [1.3.7](https://www.fltk.org/articles.php?L1765) patch release has no any `ABI` changes (just for notes).
=> fltk: Update to 1.3.7

mingw-w64-clang/0018-llvm-rc-Allow-dashes-as-part-of-resource-name-strings.patch, mingw-w64-clang/0019-MinGW-Mark-a-number-of-library-functions-unavailable.patch, mingw-w64-clang/0317-LLD-COFF-Make-export-all-symbols-work-as-intended-fo.patch, mingw-w64-clang/PKGBUILD, mingw-w64-clang/README-patches.md
- Make -export-all-symbols work as intended for EXEs.  Fixes #9163 (llvm/llvm-project@9dbc4b09afd4427c2def829f0c8283f732e654a0)
- Allow dashes as part of resource name strings.  Fixes #9180, fixes #9130 (llvm/llvm-project@0a1683f8cc0df2889f1d86da7a795914f07e5599)
- Mark a number of library functions unavailable for mingw targets.  Fixes #9242 (llvm/llvm-project@c5638a7)
=> clang: backport a couple more patches

mingw-w64-postgresql/PKGBUILD, mingw-w64-postgresql/postgresql-13.1-Wl-stack.patch, mingw-w64-postgresql/postgresql-13.1-disable-wsa-invalid-event-static-assert.patch, mingw-w64-postgresql/postgresql-13.1-pgevent-def.patch
use `-Wl,--stack,` instead of `-Wl,--stack=`
comment out static assert on `WSA_INVALID_EVENT` that clang thought was not a compile-time constant.
copy pre-packaged pgevent.def instead of using the (broken) auto-generated version (see 
https://github.com/postgres/postgres/blob/64a1f225654f8866422010ff28e0d3384ae4c3af/src/bin/pgevent/README#L15-L18)
=> postgresql: fix clang build

mingw-w64-texlive-bin/PKGBUILD
Also, autoreconf in texk/chktex specifically because it didn't seem to happen with the top-level autoreconf.  Fixes #9256 
Fix building wrappers with clang, which wants to use import libraries rather than dlls directly.
=> texlive-bin: autoreconf for clang support

mingw-w64-ruby/0007-nm-use-full-options.patch, mingw-w64-ruby/PKGBUILD
`__builtin_setjmp`/`__builtin_longjmp` are only meant for internal exception handling usage IIRC, use mingw-w64's setjmp instead.
> The built-in versions are used internally by GCC’s libraries to implement exception handling on some targets. You should use the standard C library functions declared in <setjmp.h> in user code instead of the builtins.
Pass full options --extern-only and --defined-only to nm, llvm-nm doesn't accept the truncated variant.
=> ruby: fix clang build

mingw-w64-libftdi/PKGBUILD
Someone reported to me that the libftdi PKGBUILD script was failing during the `check` step and I was able to reproduce the issue. 
There is no 'check' target anymore in the Makefile for libftdi that is generate by CMake.  Also, I don't know of any easy way to run tests for libftdi.  CMake gives an error if I pass `-DBUILD_TESTS=ON` and I didn't bother to look into fixing it.
This pull request fixes the PKGBUILD script by removing the `check` function.
=> libftdi: Remove check() since it was failing

mingw-w64-openFPGALoader/PKGBUILD
A new release was tagged yesterday: https://github.com/trabucayre/openFPGALoader/releases/tag/v0.5.0. This is a regular bump.
/cc @trabucayre
=> openFPGALoader: update to 0.5.0

mingw-w64-groonga/PKGBUILD
This PR fixes the following error.
```
../../groonga-11.0.2/lib/window_function_executor.cpp:392:22: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
constexpr uint32_t unpack_source_id_record_id(uint64_t source_id) {
^
../../groonga-11.0.2/lib/window_function_executor.cpp:393:30: note: shift count 32 >= width of type 'unsigned long' (32 bits)
return source_id & ((1UL << 32) - 1);
^
../../groonga-11.0.2/lib/window_function_executor.cpp:393:30: warning: shift count >= width of type [-Wshift-count-overflow]
return source_id & ((1UL << 32) - 1);
^  ~~
```
=> groonga: fix clang64 build

mingw-w64-qt6-base/001-append-qt6-to-tools-to-remove-conflict-qt5-qt6.patch, mingw-w64-qt6-base/PKGBUILD, mingw-w64-qt6-tools/PKGBUILD
Rename some tools by appending "-qt6" to avoid conflict with qt5 (qt5-base)
=> Remove conflict between qt6-base and qt5 (qt5-base)

.ci/ci-build.sh, .github/workflows/main.yml
1- Sometimes a single PKGBUILD produce many packages, which make it not possible to remove an earlier (alphabetically) package before its dependent package, so that package will stay installed.
2- Ensure that the toolchain is installed in case the previous package is a part of it and get removed.
=> [CI] Remove packages from single PKGBUILD at once

mingw-w64-libglade/PKGBUILD
There's just one standalone python script, so just run 2to3 over it, and fix up mixed tabs and spaces indentation errors.
configure has an error about missing `GNOME_COMMON_INIT`, but it has that when gnome-common is installed too, so didn't add it to makedepends.
=> libglade: update for python3 support

mingw-w64-clang/0020-llvm-rc-Allow-specifying-language-with-a-leading-0x-.patch, mingw-w64-clang/0107-clang-MinGW-Let-the-last-of-mconsole-mwindows-have-e.patch, mingw-w64-clang/0318-LLD-MinGW-Accept-joined-format-for-stack.patch, mingw-w64-clang/0319-LLD-MinGW-Support-both-opt-value-and-opt-value-for-m.patch, mingw-w64-clang/0403-HACK-for-clang32-changing-time_t.patch, mingw-w64-clang/PKGBUILD, mingw-w64-clang/README-patches.md
- Removed switch for using `MSYS Makefiles` generator instead of `Ninja`.  Now that clang32 linking is more reliable this shouldn't be necessary anymore.
- backport patches to allow `--stack` and `--image-base` to work with = as well as space between them and their value
- backport patch to allow a later `-mconsole` to override `-mwindows`, for https://github.com/msys2/MINGW-packages/pull/9201#issuecomment-890403294
- backport patch to allow `0x` prefix to language ID on `llvm-rc` and `llvm-windres` command line, for #9253
- cleaned up cmake arg variables.  There were several, that were not entirely clear how they were used.  Now, there are 
- `common_cmake_args` are args common to all cmake invocations,
- `platform_config` are args specific to the main llvm build (generally …
=> Clang update 12.0.1-3

mingw-w64-libgnomecanvas/PKGBUILD
This was built for clang64 after libglade was available, but was missing DLLs.  Autoreconf to fix.
This is another old GTK2 library that no packages in the repo depend on, so may be a candidate for removal.  But, as long as it's here, it may as well build properly.
=> libgnomecanvas: autoreconf for clang

mingw-w64-qbittorrent/PKGBUILD
Trables to linking only with `clang32` [there](https://github.com/msys2/MINGW-packages/pull/9298/checks?check_run_id=3256506995#step:9:3153).
Can anyone fix this?
=> qbittorrent: Update to 4.3.7

mingw-w64-lerc/Lerc.pc.cmake, mingw-w64-lerc/PKGBUILD, mingw-w64-lerc/cmake_config_pc.patch
Yet another codec for libtiff, gdal...
Note: Added pc file matches output library and project name w/ capital "L" (followed e.g. OpenEXR.pc, OpenImageIO.pc etc).
=> lerc: new package

mingw-w64-qt6-tools/001-appending-qt6-to-remove-qt5-conflict.patch, mingw-w64-qt6-tools/PKGBUILD
I haven't bump the pkgrel as the package is not uploaded yet to the stable repos.
=> qt6-tools: remove conflict with qt5 (qt5-tools).

mingw-w64-octave/0001-binary-install-location.patch, mingw-w64-octave/PKGBUILD
This is the first time, I try to get a package added to MSYS2. So, I hope this is ok. Any feedback is very welcome.
GNU Octave is a high-level interpreted language, primarily intended for numerical computations. It provides capabilities for the numerical solution of linear and nonlinear problems, and for performing other numerical experiments. It also provides extensive graphics capabilities for data visualization and manipulation. Octave is normally used through its interactive command line interface, but it can also be used to write non-interactive programs. The Octave language is quite similar to Matlab so that most programs are easily portable.
See: https://www.octave.org
I hope that it is eligible to be included in MSYS2.
I tried to keep the `PKGBUILD` file in line with the ones I …
=> Add package "GNU Octave"

mingw-w64-graphviz/014-gdiplus-no-explicit-libstdc++.patch, mingw-w64-graphviz/015-cast-function-pointer-to-void-pointer.patch, mingw-w64-graphviz/016-makefile-dont-embed-build-system-path.patch, mingw-w64-graphviz/PKGBUILD
Depends on #9291
Fixes #9253 (inasmuch as a discussion can be fixed).
NOTE: This contains a patch to remove defining the default include search path for `gvpr`.  The old behavior wound up embedding an absolute Windows path in the binary, and doing so in a broken way that the compiler thought the backslashes were trying to escape characters!  With that define missing, the source defines it to `"."`, so it will by default only search the current directory for includes.  This would wind up matching what it did before, because the other default path entry was gobbledygook.  The *correct* fix would be to pull in mingw-w64-pathtools, and construct the default path entry relative to the exe.  I've already spent more time on graphviz than I was planning to, so I'll leave that for a future effort.
=> graphviz: fix for clang

mingw-w64-openldap/PKGBUILD
Depends on #9291
slapd has an archaic, byantine linking method that llvm does not
support.  Rather than trying to untangle that, just disable slapd on the
assumption that most consumers of the package only really care about the
library, and maybe the commandline tools, not the server.  #9299
=> openldap: disable building slapd on clang.

mingw-w64-ruby/0007-nm-use-full-options.patch, mingw-w64-ruby/PKGBUILD
This re-applies #9265, plus fixes #9273.
This cannot be merged until #9271 is fixed in mingw-w64 and rebuilt here.
=> ruby: fix clang64 and clang32

mingw-w64-mruby/PKGBUILD
Trying to work around a non-consistent error
```
C:/_/M/mingw-w64-mruby/src/build-x86_64-w64-mingw32/mrbgems/mruby-compiler/core/y.tab.c:70:9: warning: missing terminating '"' character [-Winvalid-pp-token]
#line 7 "mrbgems/mruby-compiler/core/parse.y
^
C:/_/M/mingw-w64-mruby/src/build-x86_64-w64-mingw32/mrbgems/mruby-compiler/core/y.tab.c:70:9: error: invalid filename for #line directive
```
Also passed `-v` so there's more build output to see what's going on.
Note I pushed and reverted a pkgrel=2 to test in autobuild, so this may need to wait for another autobuild run to clean up -2 results.
=> mruby: build with -j1

mingw-w64-python-tzdata/PKGBUILD
Required by the zoneinfo module in the stdlib, see https://github.com/msys2-contrib/cpython-mingw/issues/32
=> python-tzdata: add package

mingw-w64-smpeg/PKGBUILD, mingw-w64-smpeg/clang-libtool-tweak.patch, mingw-w64-smpeg2/PKGBUILD, mingw-w64-smpeg2/clang-libtool-tweak.patch
These do not work when updating their bundled libtool files with the newer ones from MSYS2-packages, so instead apply the minimal patch to let it use compiler-rt, and use `lt_cv_deplibs_check_method=pass_all` to work around the other clang issues with libtool.  Fixes #9317
Note CI fails building the source package, apparently because the sources are from svn.
=> smpeg{,2}: libtool hack

mingw-w64-coin/PKGBUILD, mingw-w64-coin/coin-4.0.0-exported-struct-needs-tag.patch
It was using a C-style idiom of `typedef struct {...} foo;` in C++, which clang
didn't like because they were also trying to export that struct.  Use
C++ style `struct foo {...};` instead.
=> coin: fix clang build

mingw-w64-ccache/010-ucrt.patch, mingw-w64-ccache/011-clang-iostream-unittest.patch, mingw-w64-ccache/PKGBUILD
A patch from #8603 was lost in #9290.  Resurrect it.
Also include <iostream> in test_Win32Util to fix a clang error linking unittest.exe (#8603 mentioned disabling the tests, but #9290 was nice enough to hook them up, so fix them instead).
=> ccache: resurrect patch fixing clang build

mingw-w64-wxWidgets/006-wxWidgets-3.0-Fix-c-11-narrowing-error.patch, mingw-w64-wxWidgets/PKGBUILD
add provides wxconfig and wx-config-3.0 script.
Edit: As a side effect the patch I added likely fixes clang32 build; but, since that code was in wxMediaCtrl it likely does not matter.
=> wxWidgets: Enable wxMediaCtrl and

mingw-w64-qt6-base/PKGBUILD
As long as it needed rebuilding anyway, get rid of some of the clang workarounds for missing packages which are now present.
=> qt6-base: enable dependencies for clang.

mingw-w64-texlive-bin/0004-mpxout-x64.patch, mingw-w64-texlive-bin/PKGBUILD
Package `mingw-w64-x86_64-texlive-bin`.
When MetaPost calls `mpx_cleandir` to delete temporary auxiliary files (e.g., from running TeX to format a label), it segfaults in `RtlEnterCriticalSection`. This doesn't affect the 32-bit binaries shipped by the TexLive project.
At line 3872 of "mpxout.w" (see <svn://tug.org/texlive/trunk/Build/source/texk/web2c/mplibdir/mpxout.w@58686>), `hFile` is declared as `long`. The handle returned by `_findfirst` is stored there and truncated. Then it is sign-extended and passed to `_findnext`. There is a segfault when it is first dereferenced, which happens in `RtlEnterCriticalSection`.
Presumably this could be fixed by changing `long` to `intptr_t` there, as in this PR, but this is **untested**, as I haven't managed to rebuild the package here.
To …
=> mpxout.w (mpx_cleandir): Fix _findfirst handle truncation on x86_64

mingw-w64-pyside2-qt5/PKGBUILD, mingw-w64-shiboken2-qt5/PKGBUILD
Based on archlinux implementation.
Fixes #8021
Closes #4507
=> pyside2-qt5 and shiboken2-qt5: Install egg-info

mingw-w64-qt5-pkgs/PKGBUILD, mingw-w64-qt5-tools/PKGBUILD
- qt5-base: missed to add md4c as a dependency.
- qt5-tool: snot all the makefiles installation destinations were fixed.
=> Fix some qt5 packages

mingw-w64-qt5-imageformats/0001-qmng-fix-build.patch, mingw-w64-qt5-imageformats/PKGBUILD, mingw-w64-qt6-imageformats/0001-qmng-fix-build.patch, mingw-w64-qt6-imageformats/PKGBUILD
Wondering why it was disabled for both qt5 and qt6. @MehdiChinoune Review please.
=> qt-imageformats: Enable libmng plugin

mingw-w64-qt5-quickcontrols2/PKGBUILD
Somehow, most of the files were not installed in the right destination.
=> qt5-quickcontrols2: Fix Installation destination

mingw-w64-clustal-omega/PKGBUILD
rebuild decided to fail due to it trying to call autoconf/automake during build.  Do an explicit autoreconf so the versions all match.
=> clustal-omega: autoreconf due to clang failures

mingw-w64-libosmscout/PKGBUILD
the last dependency update lost it, maybe this helps
=> libosmscout: depend on cairo

mingw-w64-opencascade/PKGBUILD, mingw-w64-osgQt/PKGBUILD, mingw-w64-osgqtquick-git/PKGBUILD, mingw-w64-vtk/PKGBUILD
- osgqt
- osgqtquick
- opencascade
- vtk
all of these packages are not available for ucrt64 and clang subsystems, just ignore the failure on those subsystems.
=> Update Qt5 reverse dependencies (4/n)

mingw-w64-octave/PKGBUILD
Like @gharveymn noticed in #9310, `mkoctfile` doesn't work with default settings and `octave.pc` leaks paths from the build system.
The proposed change fixes both issues for me.
Is it ok to configure with `CXX=${MINGW_CHOST}-g++` and Co. when building Octave? Most other PKGBUILD rules seem to use `CXX=${MINGW_PREFIX}/bin/g++`. Is there a particular reason for that?
=> octave: Fix mkoctfile with default settings. Fix pkgconfig files.

mingw-w64-bsdfprocessor/PKGBUILD
This package builds only on MINGW32/64. Ignore the failure on UCRT64 and CLANG32/64.
=> bsdfprocessor: update dependencies

mingw-w64-binutils/PKGBUILD, mingw-w64-binutils/reproducible-import-libraries.patch, mingw-w64-binutils/specify-timestamp.patch
It's a nice property to have.
They also use --enable-deterministic-archives, so do that too.
=> binutils: take reproducibility patches from debian

mingw-w64-crt-git/PKGBUILD, mingw-w64-crt-git/dlltool-temp-prefix.patch
also helps reproducibility
See https://github.com/msys2/MINGW-packages/issues/9363#issuecomment-899108764
=> crt: import patch from Debian to fix prefix collisions when using dlltool

mingw-w64-ttfautohint/PKGBUILD
libc++ has a header <version> and case-insensitive filesystem is causing
VERSION to be picked up instead.
=> ttfautohint: delete VERSION file for libc++

mingw-w64-crt-git/PKGBUILD
Packaging does one-time builds, so dependency information is not utilized.  On ARM64 building the dependency information for this package takes a really long time.
I don't think this is worth yet another rebuild, so not bumping pkgrel, but would be nice to have for future builds
=> crt-git: disable dependency tracking

mingw-w64-binutils/2004-bfd-Close-the-file-descriptor-if-there-is-no-archive.patch, mingw-w64-binutils/PKGBUILD
=> binutils: backport a fix for too many open FDs

mingw-w64-clang/0001-Use-posix-style-path-separators-with-MinGW.patch, mingw-w64-clang/PKGBUILD
llvm::sys::path::native previously replaced all `/` with `\`, but the patch intended to prefer `/` for MinGW missed this one.  Replace all separators with the preferred separator instead.  This fixes automake detecting that clang generates "gcc3"-style dependency makefile fragments.
Remove early build of shared libc++ for clang32.  This was a hack to recover from the changed `time_t` size, but the patched libc++ with both 32 and 64-bit `time_t` exports is in the repos now so it isn't necessary anymore.
I intend to leave the hack adding the extra 32-bit `time_t` export in libc++.dll until llvm 13 just in case, but all users of the symbol should already be rebuilt in the repo.
=> clang: make path::native use preferred separator

mingw-w64-arrow/0002-cast-initializer-list.patch, mingw-w64-arrow/PKGBUILD
Explicitly cast in initializer list to avoid C++11-narrowing error.
=> arrow: fix clang32 build.

mingw-w64-github-cli/PKGBUILD
For more details, see
https://github.blog/2021-08-24-github-cli-2-0-includes-extensions/
=> gh: upgrade to v2.0.0

mingw-w64-gtk3/PKGBUILD
There's a circular dependency involved, so I don't know if autobuild would be able to figure out to provide adwaita-icon-theme...
=> gtk3: clang32 depend on adwaita-icon-theme again

mingw-w64-fpm/PKGBUILD
This PR adds a PKGBUILD for the Fortran package manager ([fpm](https://github.com/fortran-lang/fpm)) a build system for Fortran projects.
Works with mingw32, mingw64 and ucrt64, but can't build with clang64 or clang32 due to missing `mingw-w64-*-gcc-fortran` make dependency.
=> Add new package: Fortran package manager (fpm)

.github/workflows/main.yml
These tools are not present in autobuild, and may cause confusion with the proper MINGW tools.
Fixes #9479
=> CI: don't install msys2-devel

mingw-w64-ngraph-gtk/PKGBUILD
new upstream release version 6.09.04.
=> ngraph-gtk: new upstream release version 6.09.04.

mingw-w64-octave/0002-mk-doc-cache-path.patch, mingw-w64-octave/0003-pkg-octave-binary.patch, mingw-w64-octave/PKGBUILD
As reported in #9310, installing an Octave package with `pkg install ...` currently fails.
The proposed changes should be fixing the issue (see `0003-pkg-octave-binary.patch`).
Patching that file of the tarball triggers the build system to re-build the documentation. That doesn't work currently (at least for me, see msys2/msys2-texlive#13).
The additional changes to the build rule and patch `0002-mk-doc-cache-path.patch` should work around that issue.
=> octave: Fix detection of octave binary when installing Octave packages.

mingw-w64-gtkspell3/PKGBUILD
no users and we are trying to get rid of gtk2
Fixes #9500
=> gtkspell3: drop gtk2 support

.ci/ci-build.sh
In #9502 it occurred to me that it would be useful to see package metadata in CI.  This diffs package info from the sync db and package info from the newly-built package file.
For an existing package, this looks like:
```diff
[36m[MSYS2 CI](B[m mingw-w64-qt5-pkgs: Package info diff for mingw-w64-clang-x86_64-qt5-base
--- /dev/fd/63	2021-08-31 19:41:26.000000000 +0000
+++ /dev/fd/62	2021-08-31 19:41:26.000000000 +0000
@@ -1,6 +1,5 @@
-Repository      : clang64
Name            : mingw-w64-clang-x86_64-qt5-base
-Version         : 5.15.2+kde+r94-4
+Version         : 5.15.2+kde+r96-1
Description     : A cross-platform application and UI framework (mingw-w64)
Architecture    : any
URL             : https://www.qt.io/
@@ -13,9 +12,11 @@
mingw-w64-clang-x86_64-postgresql
Conflicts With  : None …
```
=> CI: add a diff of package info to [diff] group

mingw-w64-extra-cmake-modules/PKGBUILD, mingw-w64-extra-cmake-modules/tar-force-local.patch, mingw-w64-kparts-qt5/PKGBUILD
It looks for GNU tar, and if found uses it instead of cmake tar functionality, in order to produce a "reproducible" tar file.  Unfortunately, GNU tar assumes a filename with a colon in it is a remote file (`host:path`), not a Windows drive letter (`X:\path`).  Pass the `--force-local` option to tell it not to make that assumption.
If somebody with an account with KDE wants to send that [upstream](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/kde-modules/KDEPackageAppTemplates.cmake), that'd be great.
=> extra-cmake-modules: pass --force-local to GNU tar

mingw-w64-codelite/PKGBUILD, mingw-w64-filezilla/PKGBUILD, mingw-w64-gnuplot/PKGBUILD, mingw-w64-plplot/PKGBUILD, mingw-w64-wxSVG/PKGBUILD
This change will make it easier to change to wxWidgets version 3.2 when it is released sometime this decade. Or to version 3.1.
I also added 'clang32' as a arch if missing.
Tim S.
=> Convert wxWidgets based packages to using single local variable to version of wxWidgets

mingw-w64-lasem/CVE-2013-7447.patch, mingw-w64-lasem/PKGBUILD, mingw-w64-lasem/install-mathml-headers.patch
2. Each toolcain gets it's own build files
3. mathml headers are now included for ruby-mathematical.  Uses patch from Alpine Linux.
4. "make check" testsuite is ran for testing.
=> lasem: 1. Added CVE-2013-7447.patch to fix an overflow.

mingw-w64-kirigami2-qt5/002-template-dllexport-static.patch, mingw-w64-kirigami2-qt5/PKGBUILD
Fix a pretty vexatious issue with a `dllexport`ed template class on clang.  Clang apparently treats a dllexport attribute on a template class as an implicit instantiation (over what template parameters?), which causes an error if there are then explicit specializations.  Instead, only export the member of the class that needs to be exported, which is actually the member being explicitly specialized.
Also add explicit specialization declarations, to satisfy a clang warning.
I originally thought moving the export from the class to the static member would result in different exports from the dll (the vtable, typeinfo, and destructor were being exported by GCC), but a diff of the export table of the mingw64 dll before and after this patch didn't show that.  Also, no dependent package actually …
=> kirigami2-qt5: fix clang build

.ci/ci-get-build-order.py, mingw-w64-perl/PKGBUILD
Not all PKGBUILDs source cleanly with `set -e` on (should they?):
```
mingw-w64-blender
mingw-w64-clang
mingw-w64-qt5-static
mingw-w64-rust
mingw-w64-zlib
```
That's because they make use of ternaries like
```
$([[ "$_variant" == "-shared" ]] && echo \
$([[ "$_system_assimp" == "yes" ]] && echo "${MINGW_PACKAGE_PREFIX}-assimp") \
$([[ "$_system_doubleconversion" == "yes" ]] && echo "${MINGW_PACKAGE_PREFIX}-double-conversion") \
...
```
Not sure if anyone has any strong thoughts on whether or not that matters.
=> Fix ci-get-build-order with some PKGBUILDs

mingw-w64-doctest/PKGBUILD, mingw-w64-ideviceinstaller/PKGBUILD, mingw-w64-libopenmpt-modplug/PKGBUILD, mingw-w64-pyqt6-sip/PKGBUILD, mingw-w64-pyqt6/PKGBUILD, mingw-w64-python-click-default-group/PKGBUILD, mingw-w64-python-cloup/PKGBUILD, mingw-w64-python-moderngl-window/PKGBUILD, mingw-w64-python-multipledispatch/PKGBUILD, mingw-w64-python-pyrr/PKGBUILD, mingw-w64-python-tzdata/PKGBUILD, mingw-w64-sqlitebrowser/PKGBUILD, mingw-w64-talkatu/PKGBUILD, mingw-w64-texlive-bin/PKGBUILD, mingw-w64-tzdata/PKGBUILD, mingw-w64-vala-language-server/PKGBUILD, mingw-w64-wwrando/PKGBUILD
These packages were being overlooked by my script to enable packages for clang32, as it only looked to add clang32 to mingw_arch, not add mingw_arch if it wasn't present.
Of course, nothing comes easy, so a couple of packages needed fixing to build:
* libopenmpt-modplug: autoreconf for clang
* pyqt6: use qmake6.exe instead of qmake.exe which isn't present
These are all enabled for clang32, except for texlive-bin, as it is indirectly blocked by lack of rust
=> add missing mingw_arch to PKGBUILDs

mingw-w64-ghostscript/PKGBUILD
This is fixing issue #6268 for me.
Change as proposed by @gharveymn there.
The output device "bbox" is working for me. .eps files created with "bbox" look good to me.
=> ghostscript: Always build basic output device "bbox".

mingw-w64-epstool/0001-mingw-buildrule.patch, mingw-w64-epstool/0002-buildorder.patch, mingw-w64-epstool/PKGBUILD
Add build rules for `epstool`.
I'd like to add that tool as an optional dependency to octave. It is needed to save .eps graphics with tight binding box. But octave doesn't re-build currently (missing OpenGL symbols IIUC).
I'll probably open an issue later when I better understand what is causing that.
For the time being, it would be nice if you could add the `epstool` package anyway.
=> epstool: Add new package

mingw-w64-libopenmpt/PKGBUILD
Update to libopenmpt 0.4.23 (security update)
https://lib.openmpt.org/libopenmpt/2021/08/22/security-updates-0.5.11-0.4.23-0.3.32/
=> libopenmpt: update to 0.4.23

mingw-w64-kimageformats-qt5/PKGBUILD, mingw-w64-libheif/PKGBUILD
Build pkgconfig file using autoconf because
CMake generates it without ${prefix} variable
=> libheif: Generate pkgconfig file with autoconf

mingw-w64-octave/PKGBUILD
This adds `epstool` to the list of optional dependencies of the octave package.
Octave doesn't currently compile (locally or using the CI) unless it is configured with `--enable-link-all-dependencies`. Without that flag, the compilation ends with a linking error (referring to import symbols to OpenGL functions).
I don't understand why it worked before without that flag or why it requires that flag now. But at least that is fixing the linking error for me. So, I just added that flag to the `PKGBUILD` rules.
=> octave: Add `epstool` as optional dependency.

mingw-w64-cairo/0031-remove-glyph-bounds-check.patch, mingw-w64-cairo/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/9618
=> cairo: Import patch to remove glyph bounds check

mingw-w64-flint/PKGBUILD
I'm not affiliated with the FLINT project, but got an OK from the primary maintainer to pop this up on MSYS. Relatively common math library that I can't find prebuilt for Windows anywhere.
The `makepkg-mingw` script fails on the 32-bit build, apparently due to a dirty build directory. Is that a problem for CI? I think it'd be solved with a `make clean` in whichever function is for cleanup (`package()`?).
=> flint: Add new package

mingw-w64-spice-gtk/002-export-symbols.patch, mingw-w64-spice-gtk/PKGBUILD
clang64 build currently fails with
```
[122/141] "clang" @src/libspice-client-glib-2.0-8.dll.rsp
FAILED: src/libspice-client-glib-2.0-8.dll 
"clang" @src/libspice-client-glib-2.0-8.dll.rsp
lld-link: error: C:/Qemu/tools/hyperv/src/msys2/pkg/mingw-w64-spice-gtk/src/spice-gtk-0.39/src/spice-glib-sym-file: unknown file type
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
I've tried to fix it by renaming spice-glib-sym-file to spice-glib-sym-file.def (also in meson.build), but this led to further errors.
As far as I've understood, -export-symbols is optional, because by default all symbols are exported.
The new patch removes the parts from meson.build, which add the -export-symbols to the linking command. 
I've …
=> spice-gtk: Enable clang64 build

mingw-w64-virt-viewer/001-rc-generation-fixes.patch, mingw-w64-virt-viewer/002-check-linker-pie-support.patch, mingw-w64-virt-viewer/PKGBUILD
Ran into an issue with llvm-windres: https://bugs.llvm.org/show_bug.cgi?id=51944.  They were already using `configure_file` on the rc file, so patched meson.build to sub in the paths to the files through that instead of trying to combine string constants.
=> virt-viewer: update to 10.0, which uses meson

mingw-w64-fritzing/0001-Fix-casts-from-pointer-to-long-to-size_t-instead.patch, mingw-w64-fritzing/0002-qmake-fixes-for-mingw.patch, mingw-w64-fritzing/0003-Look-in-.-share-fritzing-from-bin-dir-on-mingw.patch, mingw-w64-fritzing/PKGBUILD
Apparently the author is not being very good about keeping the github
repo up to date, and has not tagged the last few releases.  Commit hashes from https://aur.archlinux.org/packages/fritzing
=> Fritzing: update to 0.9.9

mingw-w64-opencascade/0002-GeomPlate_BuildAveragePlane-BasePlan-Don-t-set-yvect.patch, mingw-w64-opencascade/0003-BRepFill_Filling-WireFromList-We-can-t-assume-that-a.patch, mingw-w64-opencascade/0004-BRepFill_Filling-Curve-constraints-confused-by-impli.patch, mingw-w64-opencascade/0005-BRepFill_Filling-Don-t-even-attempt-to-build-with-em.patch, mingw-w64-opencascade/0006-BRepOffset_Tool-TryProject-Check-return-of-BRepLib-B.patch, mingw-w64-opencascade/0007-ChFi3d_Builder-PerformIntersectionAtEnd-Check-max-nu.patch, mingw-w64-opencascade/0008-Add-error-checking-to-chamfer-and-fillet-code.patch, mingw-w64-opencascade/PKGBUILD
Add the seven patches that the Debian Science Team is currently applying to the Buster package for OpenCASCADE. The first six are exactly the same patches that made it into the Buster release. The seventh has been updated to match the actual patch accepted to the upstream for OCCT 7.6. Most of the patches are courtesy of "blobfish <blobfish@gmx.com>". The last is courtesy of "Chris Hennes <chennes@gmail.com>" (me).
Ref 1:
https://salsa.debian.org/science-team/opencascade/-/tree/master/debian/patches
Ref 2:
http://git.dev.opencascade.org/gitweb/?p=occt.git;a=commitdiff;h=329e5df986519164083d78b28ae62d1a3b10fa6a
=> opencascade: Add patches from Debian Science Team

mingw-w64-ghdl/PKGBUILD, mingw-w64-nextpnr/PKGBUILD, mingw-w64-yosys/PKGBUILD
A regular update of some EDA tools.
Yosys 0.10 was released and a different versioning logic is used now (hardcoded instead of using `pkgver()`).
=> Update GHDL, Yosys and nextpnr

mingw-w64-fftw/PKGBUILD
> you can compile with--enable-avx and the code will still run on a CPU without AVX support
http://fftw.org/fftw3_doc/Installation-on-Unix.html#Installation-on-Unix
=> fftw: enable avx-128-fma/avx2/avx512

mingw-w64-libusb/PKGBUILD, mingw-w64-libusb/fix-dll-exports.patch
llvm's dlltool/lld do not support --add-stdcall-alias, but libusb already provided a .def file that said exactly what they wanted to be
exported from the DLL (and in fact regenerated their import lib from it).  Convince libtool to actually use that def file.
Also, remove no longer needed switch of platforms for dlltool.
Fixes #9706, fixes #9626 (which means aravis builds for CLANG32 after this fix)
=> libusb: fix dll exports on CLANG

mingw-w64-fpm/PKGBUILD
git is not required for the basic functionality of fpm.
cc @zoziha
=> Update fpm: move git to optdepends

mingw-w64-python-fypp/PKGBUILD
Adds package files for Python based preprocessor and meta-programming engine for Fortran (https://fypp.readthedocs.io/en/stable/)
=> Add python-fypp package build file

mingw-w64-libopenmpt/PKGBUILD
security update
https://lib.openmpt.org/libopenmpt/2021/10/04/security-updates-0.5.12-0.4.24-0.3.33/
=> libopenmpt: update to 0.4.24

mingw-w64-precice/PKGBUILD
- disable clang (for now)
- petsc don't have clang build because it depends on fortran lib, so we have to disable clang for now
=> precice: bump pkgrel

mingw-w64-gdal/002-dont-define-msvcrt-version.patch, mingw-w64-gdal/PKGBUILD
Don't define `__MSVCRT_VERSION__` to `0x0700` - that's the default for MINGW*, and is lower than 0x0E00 for UCRT, turning off some functions in the headers (like quick_exit and at_quick_exit).  Fixes #9617
=> gdal: fix UCRT build

mingw-w64-portmidi/PKGBUILD
Portmidi is no longer maintained as a standalone package,
but is maintained as part of the larger portmedia release.
=> Update portmidi with more recent portmedia release

mingw-w64-libuv/0001-winapi-fix-redefinition.patch, mingw-w64-libuv/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/9946
=> libuv: Fix redefinition error with mingw-w64 headers

mingw-w64-ghdl/PKGBUILD, mingw-w64-iverilog/PKGBUILD, mingw-w64-nextpnr/PKGBUILD, mingw-w64-scopehal-apps/PKGBUILD, mingw-w64-yosys/PKGBUILD
=> Update EDA tools GHDL, Yosys, NextPnR and Scopehal

mingw-w64-scintilla-gtk3/PKGBUILD, mingw-w64-scintilla-gtk3/scintilla.pc
```
Release 5.0.0
Released 5 March 2021.
First version that separates Lexilla from Scintilla. Each of the 3 projects now has a separate history page but history before 5.0.0 remains combined.
```
https://www.scintilla.org/ScintillaHistory.html
=> scintilla-gtk3: update to 5.1.3

mingw-w64-python-maturin/PKGBUILD
- needed by `pywinpty`
- lacks clang32 build coz `rust` don't build on clang32
=> new package: python-maturin

mingw-w64-python-typing-extensions/PKGBUILD
newer `astroid` requires `typing-extensions`
=> new package: python-typing-extensions

mingw-w64-python-pywin32/002-com-extensions-fix.patch, mingw-w64-python-pywin32/PKGBUILD
Remove infinite recursion from ThisAsIID method.  Disable a workaround
for broken header in Vista SDK that is not broken in MINGW-w64.
/cc @raedrizqie
=> pywin32: fix problematic patch

mingw-w64-libass/PKGBUILD
=> libass: autoreconf for clang

mingw-w64-matio/PKGBUILD, mingw-w64-osm-gps-map/PKGBUILD
After #10055, checked for more packages missing DLLs on Clang, and found a couple.
=> matio and osm-gps-map: autoreconf for clang

mingw-w64-mdloader/0001-incbin-mangle.patch, mingw-w64-mdloader/PKGBUILD
properly mangle global asm statement.  GCC doesn't care but apparently Clang does.
=> mdloader: fix clang32 build

mingw-w64-python-qtconsole/PKGBUILD
reverse dependency failure (spyder)
=> python-qtconsole: update to 5.2.0

mingw-w64-python-qstylizer/PKGBUILD
check failed because of reverse dependency (spyder)
=> python-qstylizer: fix versioning

mingw-w64-qt6-tools/001-appending-qt6-to-remove-qt5-conflict.patch, mingw-w64-qt6-tools/PKGBUILD
=> qt6-tools: Fix windeployqt searching for qmake instead of qmake6

mingw-w64-SDL2_mixer/0199-Fixed-use-after-free-in-music_fluidsynth.c.patch, mingw-w64-SDL2_mixer/PKGBUILD
https://www.fluidsynth.org/news/2021/01/23/sdl2-mixer-bug/
=> SDL2_mixer: fix use-after-free in music_fluidsynth.c

mingw-w64-glib2/PKGBUILD
=> glib2: Add libwinpthread to dependencies.

mingw-w64-qt6-base/008-enable-avx-support.patch, mingw-w64-qt6-base/PKGBUILD
It was blocked with MINGW/GCC 64bit due to AVX misalignment that should be fixed by #9998
=> qt6-base : Enable AVX Support

mingw-w64-scintilla-gtk3/PKGBUILD
They offer only the latest release to download. the oldest releases are unreachable.
=> scitilla-gtk3: update to 5.1.4

mingw-w64-ngraph-gtk/PKGBUILD
new upstream version 6.09.05 is  released.
=> ngraph-gtk: new upstream release version 6.09.05.

mingw-w64-python-platformdirs/PKGBUILD
this one needs to be updated too.. `pylint` depends on it
=> python-platformdirs: fix versioning

mingw-w64-asio/PKGBUILD
There's a bug fix in this version for an error detecting the availability of `std::aligned_alloc` when using libc++ that affects the clang64 and clang32 builds.
=> asio: Update to 1.21.0

mingw-w64-boost/PKGBUILD, mingw-w64-boost/aligned_alloc-backport.patch
=> boost: backport fix for aligned_alloc and clang 13

mingw-w64-vapoursynth/PKGBUILD
The plugins were moved to their own repos:
see: https://github.com/vapoursynth/vapoursynth/commit/67fa8c5
=> vapoursynth: update to R57

mingw-w64-openblas/009-cmake-Set-SUFFIX64-also-for-NOFORTRAN.patch, mingw-w64-openblas/PKGBUILD
Continuing from #9932.
This adds a version of OpenBLAS with 64-bit indexing in the form of a split package.
=> openblas: Create split package with 32-bit and 64-bit indexing

.github/workflows/main.yml
I don't know if this is worth having in the repo or not.  It can't be enabled, because github will wait for a runner even if no such runner exists.
=> CI: adjust workflow to be able to deal with a 'persistent' self-hosted ARM64 runner

mingw-w64-aws-sdk-cpp/0002-1810-backport-cmake-322-fix.patch, mingw-w64-aws-sdk-cpp/PKGBUILD
Fixes:
```
CMake Error at D:/a/_temp/msys64/mingw64/lib/cmake/AWSSDK/AWSSDKConfig.cmake:119 (while):
had incorrect arguments:
"NOT" "TEMP_NAME" "STREQUAL"
```
=> aws-sdk-cpp: fix for cmake 3.22

mingw-w64-qt5-3d/PKGBUILD, mingw-w64-qt6-3d/PKGBUILD
Before someone start complaining, It is just a hint. Look at the build log to be sure.
SSE2 is not enabled for 32 bits environments.
=> Qt5/6-3d: Enable SSE2

mingw-w64-arpack/0001-cmake-relocate-prefix.patch, mingw-w64-arpack/PKGBUILD
Changes:
* Enable ICB for arpack header files.
* Enable check function.
* Add patch file to relocate prefix.
* Use sed to replace MINGE_PREFIX with _IMPORT_PREFIX.
Fixes https://github.com/msys2/MINGW-packages/issues/10151
=> arpack: Fix cmake file to relocate prefix

mingw-w64-python-pydocstyle/PKGBUILD
preparing for `python-lsp-server`, needed by `spyder`
=> new package: python-pydocstyle

mingw-w64-libosmscout/PKGBUILD
They both install "bin/import.exe". I guess they should be marked as conflicting with each other.
See also PR #9931.
=> Mark "imagemagick" and "libosmscout" as conflicting packages.

mingw-w64-python-spyder-kernels/PKGBUILD
=> spyder-kernels: update to 2.2.0

mingw-w64-mesa/PKGBUILD
Also don't bother installing GCC on clang prefixes
=> mingw-w64-mesa/clang prefixes: Enable ZSTD compression

mingw-w64-python-ujson/PKGBUILD
At release [notes](https://github.com/ultrajson/ultrajson/releases/tag/4.3.0) told that `ARM64` enabled on `Windows`.
@lazka how to check it?
=> python-ujson: Update to 4.3.0

mingw-w64-openFPGALoader/PKGBUILD
openFPGALoader v0.6.0 was released: https://github.com/trabucayre/openFPGALoader/releases/tag/v0.6.0.
/cc @trabucayre
=> openFPGALoader: update to 0.6.0

mingw-w64-python-flit/PKGBUILD, mingw-w64-python-tomli/PKGBUILD
Otherwise, if building the same version as is already installed, pip
will not install the wheel into the pkgdir.
=> flit/tomli: make pip install ignore installed packages

mingw-w64-filezilla/PKGBUILD
On a fresh install, filezilla fails with
```
MINGW64 ~$ filezilla
C:/msys64/mingw64/bin/filezilla.exe: error while loading shared libraries: wxmsw30u_xrc_gcc_custom.dll: cannot open shared object file: No such file or directory
```
wxmsw30u_xrc_gcc_custom.dll resides in /mingw64/bin, but running filezilla in /mingw64/bin fails with
```
MINGW64 /mingw64/bin$ filezilla
C:/msys64/mingw64/bin/filezilla.exe: error while loading shared libraries: libsqlite3-0.dll: cannot open shared object file: No such file or directory
```
=> filezilla: fix missing dep sqlite3

mingw-w64-github-cli/PKGBUILD
For details, see https://github.com/cli/cli/releases/tag/v2.3.0
=> gh: update to v2.3.0

mingw-w64-gcc/PKGBUILD
=> gcc: Install a missing binary (g++-mapper-server)

mingw-w64-d-feet/PKGBUILD
* Remove shebang from d-feet python script.
* Remove redundant makedepends ninja.
Fixes https://github.com/msys2/MINGW-packages/issues/10248
=> d-feet: Update to 0.3.16

mingw-w64-libslirp/PKGBUILD
On performing tests for https://github.com/msys2/MINGW-packages/pull/10098 I realized that test case Qemu Advent Calendar 2020/14 failed (stucks in boot) because of a regression, which was introduced with version 4.6.1 while previously packaged version 4.4.0 workes fine.
Fortunately https://gitlab.freedesktop.org/slirp/libslirp/-/commit/d7fb54218424c3b2517aee5b391ced0f75386a5d solves this issue.
=> libslirp: fix bug in 4.6.1

mingw-w64-libopenmpt/PKGBUILD
New patch version with security fixes
https://lib.openmpt.org/libopenmpt/2021/12/05/security-updates-0.5.14-0.4.26-0.3.35/
=> libopenmpt: update to 0.4.26

mingw-w64-nextpnr/PKGBUILD, mingw-w64-openFPGALoader/PKGBUILD, mingw-w64-verilator/0001-Fix-MSWIN-compile-error-2681.patch, mingw-w64-verilator/PKGBUILD
openFPGALoader 0.6.1 and verilator 4.216 were released. By the way, the compiler used for building nextpnr is changed from gcc to clang.
=> EDA: update openFPGALoader and verilator

mingw-w64-openimageio/0020-set-import-prefix.patch, mingw-w64-openimageio/PKGBUILD
_IMPORT_PREFIX was overwritten by other targets. use _INSTALL_PREFIX instead.
Fixes #10263
=> openimageio: fix cmake config file

mingw-w64-qemu/PKGBUILD, mingw-w64-qemu/msys2.examples.tests.sh, mingw-w64-qemu/msys2.readme.txt
This PR intends to update qemu to 6.2.0.
https://gitlab.com/qemu-project/qemu/-/commit/984099911275cd4b703e0d9c35b37dd52928acdd fixes native msys2 build on qemu, so --cross-prefix is no longer needed to configure.
Because the first build is done by using prerelease sources, checksums will be added on final release.
=> qemu: Update to 6.2.0

mingw-w64-libmicrohttpd/PKGBUILD
llvm-dlltool does not support the -e flag.
=> libmicrohttpd: fix compilation with clang64

mingw-w64-slim-simulator/PKGBUILD
The source got updated for slim-simulator so I'd like to trigger a rebuild (BTW is there a way to do this automatically without a PR?). I've updated the sha256sums. Also, the developer has informed me that 32-bit builds are not supported so I've removed them from the mingw_arch vector.
=> slim-simulator: update mingw_arch (eliminate 32-bit). Also update source sha256sums.

mingw-w64-openblas/PKGBUILD
Use same condition for calling the actual build rule that is used for defining the package name for the 64-bit indexing version of OpenBLAS.
No rebuild is required currently. So, I didn't bump the `pkgrel`. I hope that is ok.
=> openblas: More consistent condition for 64-bit idx

mingw-w64-github-cli/PKGBUILD
For details, see https://github.com/cli/cli/releases/tag/v2.4.0
=> gh: update to v2.4.0

mingw-w64-libjaylink-git/010-socket.patch, mingw-w64-libjaylink-git/PKGBUILD, mingw-w64-libusb/010-cdecl.patch, mingw-w64-libusb/PKGBUILD
wrong type for socket.
I noticed there's actually an error in libusb where stdcall is used for a variadic function.
=> libjaylink-git: fix clang compilation

mingw-w64-libmicrohttpd/PKGBUILD
* Removed patches (integrated upstream)
* Enabled full testing (curl was fixed many versions ago)
* Upstream defaults to Vista+, no need for CPPFLAGS
=> mingw-w64-libmicrohttpd: update to 0.9.74

mingw-w64-python-flit/PKGBUILD, mingw-w64-python-py/PKGBUILD, mingw-w64-python-pygments-github-lexers/LICENSE, mingw-w64-python-pygments-github-lexers/PKGBUILD, mingw-w64-python-sphinxcontrib-github-alt/PKGBUILD
*) Use pyproject2setppy to compile flit
*) include documentation in dirhtml form and in man form
*) List all packages that were listed when I ran a bootstrap stcript
*) Upgrade python-py
*) Add new packages,  mingw-w64-python-pygments-github-lexers and mingw-w64-python-sphinxcontrib-github-alt to for syntax-highlighting in documentation
=> Upgrade flit

mingw-w64-ode/020-float.patch, mingw-w64-ode/PKGBUILD
Backported upstream patch.
Added clang32 where this was tested.
=> ode: fix compilation with clang

mingw-w64-MinHook/010-dlltool.patch, mingw-w64-MinHook/PKGBUILD
llvm-dlltool doesn't support the full versions of these options.
Also added clang32 (which this was tested on) and clangarm64.
=> MinHook: fix dlltool usage

mingw-w64-clutter-gtk/PKGBUILD
Speeds up compilation and removes need for autotools patch.
Added clang32 where this was compiled on.
=> clutter-gtk: compile with meson

mingw-w64-libopenmpt/PKGBUILD
New version
https://lib.openmpt.org/libopenmpt/2021/12/23/security-update-0.5.15-releases-0.4.27-0.3.36/
=> libopenmpt: update to 0.4.27

mingw-w64-mhook/010-char.patch, mingw-w64-mhook/PKGBUILD
=> mhook: fix compilation with clang

mingw-w64-silc-toolkit/PKGBUILD
Add clang32 support where this was tested.
=> silc-toolkit: fix compilation with clang

mingw-w64-octave/0006-sundials-6-check.patch, mingw-w64-octave/PKGBUILD
The added patch doesn't actually add support for the changed API in SUNDIALS 6. But it detects the new API and allows to still build Octave even if SUNDIALS in the new version is installed (by not using it at all).
This should be enough to no longer block PR #10370.
We'll try and add support for SUNDIALS 6 in upstream Octave in time for Octave 7 which is currently planned to be released at some time in early 2022.
I didn't yet bump the pkgrel because there's no need to rebuild Octave at this point in time. It should be bumped when SUNDIALS is updated to version 6.
=> Octave: Prepare to detect incompatible API of SUNDIALS 6.

mingw-w64-gdk-pixbuf2/PKGBUILD, mingw-w64-jbigkit/PKGBUILD
jbigkit uses libtool directly.  gdk-pixbuf2 uses tar to extract its source archive.
=> Makedepend tweaks

mingw-w64-ghdl/PKGBUILD, mingw-w64-nextpnr/PKGBUILD, mingw-w64-openFPGALoader/PKGBUILD, mingw-w64-prjtrellis/PKGBUILD, mingw-w64-yosys/PKGBUILD
This is a regular update of some EDA tools.
Although not critical, I saw it's complaining about the license of openFPGALoader: `message: mingw-w64-openFPGALoader: unformatted license ‘Apache-2.0’`. What is the proper string for that case?
=> EDA tools: ghdl, yosys, prjtrellis, nextpnr and openFPGALoader

mingw-w64-devcon-git/PKGBUILD
=> devcon-git: update and fix compilation

mingw-w64-gmp/PKGBUILD
from https://gmplib.org/manual/Build-Options:
> # CPU types
> In general, if you want a library that runs as fast as possible, you should configure GMP for the exact CPU type your system uses. However, this may mean the binaries won’t run on older members of the family, and might run slower on other members, older or newer. The best idea is always to build GMP for the exact machine type you intend to run it on.
[...]
**x86 family**: ‘i386’, ‘i486’, ‘i586’, ‘pentium’, ‘pentiummmx’, ‘pentiumpro’, ‘pentium2’, ‘pentium3’, ‘pentium4’, ‘k6’, ‘k62’, ‘k63’, ‘athlon’, ‘amd64’, ‘viac3’, ‘viac32’
**Other**: ‘arm’, ‘sh’, ‘sh2’, ‘vax’, 
CPUs not listed will use generic C code.
> # Generic C Build
>If some of the assembly code causes problems, or if otherwise desired, the generic C code can be selected …
=> GMP: optimized instructions for all x86 chips

mingw-w64-nlohmann-json/0001-fix-pkgconfig-files.patch, mingw-w64-nlohmann-json/PKGBUILD
Please review. @podsvirov
* Before:
```
Name: nlohmann_json
Description: JSON for Modern C++
Version: 3.10.4
Cflags: -I/ucrt64/include
```
* After:
```
prefix=/ucrt64
includedir=${prefix}/include
Name: nlohmann_json
Description: JSON for Modern C++
Version: 3.10.5
Cflags: -I${includedir}
```
=> nlohmann-json: Fix pkgconfig file

mingw-w64-curl/PKGBUILD
This way we remove a dependency on libwinpthreads.
=> curl: use native WIN32 threads

mingw-w64-gtk3/PKGBUILD
Contains an important [fix](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4327) for the upcoming Inkscape release and a [crash fix](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4326) for Horizon EDA.
I have compared this with the previous package and everything looks right to me 🙂
=> GTK3: update to 3.24.31+44+g0e09bb75b5

mingw-w64-mesa/PKGBUILD
Ref: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/12158
Also ${MINGW_PACKAGE_PREFIX}-pkg-config is part of ${MINGW_PACKAGE_PREFIX}-toolchain so don't bother installing it.
=> mingw-w64-mesa: Check driconf feature requirements

mingw-w64-iverilog/PKGBUILD, mingw-w64-nextpnr/PKGBUILD
nextpnr now requires openmp at runtime. This PR updates the recipe. By the way, nextpnr and iverilog are bumped.
=> EDA: fix nextpnr runtime deps; update nextpnr and iverilog

mingw-w64-gettext/0001-printf.c-guard-the-wprintf-functions-by-the-correct-.patch, mingw-w64-gettext/PKGBUILD
These functions are declared in `libintl.h`, but not included in `libintl-8.dll`. All programs that use gettext and also call `swprintf()` won't build. See e.g. [this build failure](https://github.com/git-for-windows/git-sdk-64/runs/4756702638?check_suite_focus=true#step:8:672).
Let's fix that.
Fun fact: in v0.19.8.1, those functions were included in the library, but not declared in the header.
In v0.21 the were _not_ included in the library, but they _were_ declared in the header.
So we're actually fixing a long-standing bug here.
=> gettext: do include the libintl_*wprintf() functions

mingw-w64-mesa/PKGBUILD
I can't believe nobody complained yet as this has been a problem since 67a20110.
=> mesa: libsystre is a required runtime dependency when built with regex

mingw-w64-bc/0001-use-rand-on-windows.patch, mingw-w64-bc/0002-fix-fix-libmath_h.patch, mingw-w64-bc/0003-use-binary-io.patch, mingw-w64-bc/PKGBUILD
Introduces 3 new patches
- 0001-use-rand-on-windows.patch replaces the usage of posix's `random()` with simple `rand()`
- 0002-fix-fix-libmath_h.patch prepends a shell script that lacks a shebang or .sh suffix with sh
- 0003-use-binary-io.patch fixes an issue where due to printf being in TEXT mode, the lines are trailed with `\r\n` instead of `\n` breaking ed along with an issue where due to the buffering, running
```bash
bc -l
warranty
```
doesn't print anything until you exited the program, unless you used winpty
I have no clue how it will interact with emacs as I don't know how emacs interacts with bc
=> bc: update to 1.07.1

mingw-w64-vapoursynth/0002-prevent-portable-python.patch, mingw-w64-vapoursynth/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10528 and Fixes https://github.com/msys2/MINGW-packages/issues/6630. Please review.
=> vapoursynth: Fix loading python module

mingw-w64-gettext/2001-gnulib-open-bug.patch, mingw-w64-gettext/2002-gnulib-open-bug.patch, mingw-w64-gettext/PKGBUILD
For example msgfmt and other tools would fail with "-o nul" which
previously worked.
Backport two gnulib patches which fix this regression.
Fixes #10520
=> gettext: fix error when passing "nul" as an output filename

mingw-w64-mesa/PKGBUILD
SPIRV tools is only used when building Microsoft CLC or clover with SPIR-V binary support. None of these build with MSYS2 due to libclc not being available and possibly other unknown reasons.
Vulkan validation layers is only used for debugging and it's not used specifically by Mesa3D.
=> mesa: Update to 21.3.4

mingw-w64-ghdl/PKGBUILD
I had to add `*-gcc-ada` as makedepends, because gnatmake would not be found otherwise. I thought that both makedepends and depends were installed before executing `build()`. Did the behaviour change?
=> ghdl: update to 1.0.0.r964.g70f3c162b

mingw-w64-uchardet/0001-fix-pkgconfig-files.patch, mingw-w64-uchardet/PKGBUILD
This enables relocated directories in pkg-config output. e.g. from
-I/mingw64/include/uchardet to -IC:/msys64/mingw64/include/uchardet
Also use ninja instead of make. And install license file.
Please review.
=> uchardet: Fix pkgconfig file

mingw-w64-prjtrellis/PKGBUILD
According to #10547, and tested by several users, using GCC instead of clang does fix the issues with an early check introduced in mingw-w64-crt. This PR changes prjtrellis not to use clang on the default where GCC is the default.
/cc @Biswa96 @stnolting @sylefeb
=> prjtrellis: don't force clang

mingw-w64-gcc/1001-Fix-freorder-blocks-and-partition-glitch-with-Window.patch, mingw-w64-gcc/1002-Properly-enable-freorder-blocks-and-partition-on-64-.patch, mingw-w64-gcc/PKGBUILD
as suggested here: https://github.com/msys2/MINGW-packages/pull/10589#issuecomment-1018478090
Both are already on the gcc-11 branch
=> gcc: backport some long-jump fixes

mingw-w64-libopenmpt/PKGBUILD
This update depends on merge request https://github.com/msys2/MINGW-packages/pull/10604 . After then that package is merged, the tests can be run again.
=> libopenmpt package was updated to 0.6.0 version.

mingw-w64-python-pysfcgal/PKGBUILD, mingw-w64-sfcgal/PKGBUILD
Hello!
I would like to propose two new packages into MSYS2: SFCGAL and pysfcgal.
Some words about SFCGAL:
> SFCGAL is a C++ wrapper library around CGAL with the aim of supporting ISO 19107:2013 and OGC Simple Features Access 1.2 for 3D operations.
SFCGAL provides standard compliant geometry types and operations, that can be accessed from its C or C++ APIs. PostGIS uses the C API, to expose some SFCGAL's functions in spatial databases (cf. PostGIS manual). 
http://www.sfcgal.org/
pysfcgal is the python binding of SFCGAL using cffi.
As it's my first PR here, a tiny description about me:
I'm the main maintainer/developer of SFCGAL and pysfcgal, and I'm also a (FreeBSD) package maintainer. I intend to make changes with each new version and if there are bugs.
=> new packages: sfcgal and pysfcgal

mingw-w64-libgcrypt/PKGBUILD
This updates libgcrypt to 1.10.0.
=> libgcrypt: update to 1.10.0

mingw-w64-armadillo/PKGBUILD
Depends on #10601. Replaces #10566. Fixes #10556.
=> armadillo: Use LAPACK from f2cblaslapack for clang builds.

mingw-w64-abseil-cpp/PKGBUILD
Description form [abseil.io](https://abseil.io/): "Abseil is an open source collection of C++ libraries drawn from the most fundamental pieces of Google’s internal codebase. "
PKGBUILD based on [archlinux](https://github.com/archlinux/svntogit-community/blob/packages/abseil-cpp/trunk/PKGBUILD) repository.
=> Add new abseil-cpp PKGBUILD

mingw-w64-mlpack/PKGBUILD
Testing hypothesis in #10649 that OpenMP will automatically be enabled if the dependency is supplied.
=> mlpack: enable openmp for clang builds

mingw-w64-openssl/PKGBUILD
=> openssl: Export CC and CXX before calling configure and make.

mingw-w64-python-installer/001-launcher-relative.patch, mingw-w64-python-installer/PKGBUILD
* always use python.exe in the launcher dir
* pass all build flags to cc
* set _CONSOLE macro when building the console version
* use installer for itself to install
=> python-installer: various fixes

mingw-w64-python-nuitka/PKGBUILD
[issue #10698 issuecomment-1031809109](https://github.com/msys2/MINGW-packages/issues/10698#issuecomment-1031809109)
python-nuitka: Add python-setuptools dependency
=> python-nuitka: Add python-setuptools dependency

mingw-w64-isl/PKGBUILD
isl.gforge.inria.fr is down.
See also:
https://github.com/niXman/mingw-builds/pull/570/commits/c0a872b60c9fea5a7149bdf17e58fbf186a65467
https://groups.google.com/g/isl-development/c/JGaMo2VUu_8
=> update url for mingw-w64-isl

mingw-w64-libunifex/PKGBUILD
Build [libunifex](https://github.com/facebookexperimental/libunifex).
"The 'libunifex' project is a prototype implementation of the C++ sender/receiver async programming model that is currently being considered for standardisation."
It's a little out of date — recent work on the standardization effort is being done at [wg21_p2300_std_execution](https://github.com/brycelelbach/wg21_p2300_std_execution) — but libunifex is a lot easier to compile.
Patches also [submitted](https://github.com/facebookexperimental/libunifex/pull/391) upstream.
=> libunifex: add package

mingw-w64-boost/PKGBUILD
Some libraries will added:
```console
2022-02-09T17:18:05.3661747Z  /mingw64/bin/libboost_math_tr1l-mt.dll
2022-02-09T17:18:05.3673859Z  /mingw64/bin/libboost_math_tr1-mt.dll
2022-02-09T17:18:05.3675776Z  /mingw64/bin/libboost_nowide-mt.dll
2022-02-09T17:18:05.3676521Z +/mingw64/bin/libboost_numpy39-mt.dll
2022-02-09T17:18:05.3677099Z  /mingw64/bin/libboost_prg_exec_monitor-mt.dll
2022-02-09T17:18:05.3677723Z  /mingw64/bin/libboost_program_options-mt.dll
2022-02-09T17:18:05.3678304Z  /mingw64/bin/libboost_python39-mt.dll
2022-02-09T17:18:05.3678775Z @@ -16350,6 +16351,8 @@
2022-02-09T17:18:05.3679653Z  /mingw64/lib/libboost_math_tr1-mt.dll.a
2022-02-09T17:18:05.3680233Z  /mingw64/lib/libboost_nowide-mt.a
2022-02-09T17:18:05.3680741Z  /mingw64/lib/libboost_nowide-mt.dll.a …
```
=> boost: Enable Boost.Python (NumPy)

mingw-w64-exiv2/PKGBUILD, mingw-w64-gmic/PKGBUILD, mingw-w64-iso-codes/PKGBUILD, mingw-w64-lcms2/PKGBUILD, mingw-w64-libaec/PKGBUILD, mingw-w64-libexif/PKGBUILD, mingw-w64-libraqm/PKGBUILD, mingw-w64-libusb/PKGBUILD, mingw-w64-openjpeg2/PKGBUILD, mingw-w64-pugixml/PKGBUILD, mingw-w64-python-imagecodecs/PKGBUILD, mingw-w64-python-imageio/PKGBUILD, mingw-w64-python-tifffile/PKGBUILD
Includes pugixml update to 1.12, lcms2 dependency cleanup, and adding missing licenses.
=> enable a few more clangarm64 packages

mingw-w64-gdb/PKGBUILD
When I tried to launch gdb on CLANG64 I got this message:
```
$ gdb makhber
D:/Programs/msys64/clang64/bin/gdb.exe: error while loading shared libraries: libunwind.dll: cannot open shared object file: No such file or directory
```
so I run ntldd
```
$ ntldd gdb
libreadline8.dll => D:\Programs\msys64\clang64\bin\libreadline8.dll (0x00000000004d0000)
libintl-8.dll => D:\Programs\msys64\clang64\bin\libintl-8.dll (0x00000000001d0000)
libpython3.9.dll => D:\Programs\msys64\clang64\bin\libpython3.9.dll (0x0000000001850000)
WS2_32.dll => C:\WINDOWS\SYSTEM32\WS2_32.dll (0x0000000001480000)
libmpfr-6.dll => not found
libgmp-10.dll => D:\Programs\msys64\clang64\bin\libgmp-10.dll (0x00000000004d0000)
libxxhash.dll => D:\Programs\msys64\clang64\bin\libxxhash.dll (0x00000000001d0000)
libc++.dll => …
```
=> gdb: add missing dependencies

mingw-w64-qt-creator/PKGBUILD, mingw-w64-qt-creator/qt-creator-6.0.2-qmldesigner-fix-32bit.patch
We have troubles when building 32-bit version.
`MINGW32`:
```console
C:/_/mingw-w64-qt-creator/src/qt-creator-opensource-src-6.0.2/src/plugins/qmldesigner/designercore/projectstorage/storagecache.h:78:28: error: 'constexpr QmlDesigner::StorageCache<Type, ViewType, IndexType, Storage, Mutex, compare, CacheEntry>::StorageCacheIndex::StorageCacheIndex(std::ptrdiff_t)' cannot be overloaded with 'constexpr QmlDesigner::StorageCache<Type, ViewType, IndexType, Storage, Mutex, compare, CacheEntry>::StorageCacheIndex::StorageCacheIndex(int)'
78 |         constexpr explicit StorageCacheIndex(std::ptrdiff_t id) noexcept
|                            ^~~~~~~~~~~~~~~~~
C:/_/mingw-w64-qt-creator/src/qt-creator-opensource-src-6.0.2/src/plugins/qmldesigner/designercore/projectstorage/storagecache.h:70:28: …
```
=> qt-creator: Update to 6.0.2

mingw-w64-adol-c/PKGBUILD
=> adol-c: add openmp dependency

mingw-w64-slim-simulator/PKGBUILD
This just updates `slim-simulator` to the newest version. Didn't require any changes except for the sha256sums of course.
=> slim-simulator: Update to version 3.7.1

mingw-w64-scotch/PKGBUILD
There is also a new version 7.0.1 available but it requires more skills (CMake support is now fully functional)
=> scotch: update to 6.1.3 

mingw-w64-ntldd-git/PKGBUILD
now that clang does not provide a gcc alias
=> ntldd-git: use $CC instead of gcc when building

mingw-w64-hid-bootloader-cli/01-libusb-compat-header.patch, mingw-w64-hid-bootloader-cli/PKGBUILD
This is a modified version of teensy_loader_cli (#6685) which also supports devices with LUFA's HID bootloader implementation.
=> New package: hid_bootloader_cli

mingw-w64-msmpi/PKGBUILD, mingw-w64-msmpi/mpi.c
=> msmpi: Replace gcc/g++ by cc/c++

mingw-w64-qbittorrent/002-winconf-prepare-env-for-mingw.patch, mingw-w64-qbittorrent/003-no-file-offset-bits-64.patch, mingw-w64-qbittorrent/PKGBUILD
* patches partly removed because of https://github.com/qbittorrent/qBittorrent/pull/15115
* remove workaround for boost which is patched in boost
* remove outdated comments
* add patch to disable _FILE_OFFSET_BITS which leads to macro clashes
=> qbittorrent: Update to 4.4.1

mingw-w64-qt6-base/PKGBUILD
qmake6 failed to run (#10813) because of this new dependency.
=> qt6-base: add runtime dependency on libb2

mingw-w64-openocd/001-stlink-fix-SIGSEGV-with-libusb-v1.0.25.patch, mingw-w64-openocd/PKGBUILD
By integrating a patch from OpenOCD upstream git repo.
The next OpenOCD release (probably v0.12.0) is going
to obviate this patch.
Only the OpenOCD stlink backend is affected by this,
and libusb versions 1.0.24 and older would also not
trigger the segfault.
=> Fix OpenOCD to work with libusb >= v1.0.25

mingw-w64-gcc/PKGBUILD
=> gcc: Move gcc import and static libraries under common sysroot

mingw-w64-SDL2_mixer/PKGBUILD
dllimport attribute is not added if FLAC__NO_DLL is defined.
Fixes https://github.com/msys2/MINGW-packages/issues/10869
=> sdl2_mixer: Fix static library and linking with FLAC

mingw-w64-python-requests/PKGBUILD
_Originally posted by @naveen521kk in https://github.com/msys2/MINGW-packages/issues/10673#issuecomment-1053557838_
Add missing dependency `python-charset-normalizer` for python-requests 2.27.1.
=> python-requests 2.27.1: add charset-normalizer as dependency

mingw-w64-rust/PKGBUILD
All tests are green (didn't test excluded ones but since we use LLVM without Rust patches they are unlikely to pass) for me locally in CLANG64 subsystem.
=> Upgrade Rust to 1.59

mingw-w64-python-coverage/PKGBUILD
This PR updates `***-python-coverage` from v6.2 to v6.3.2.
> **Note:**  
> The SHA256 was computed offline based on the downloaded `*.tar.gz` file.  
> Is there a way to get the official SHA256 from GitHub, so the *chain of trust* is not interrupted?  
> /cc @MehdiChinoune 
------------
Related issues:
* https://github.com/msys2/MINGW-packages/issues/10877
=> Bumped version of ***-python-coverage to v6.3.2.

mingw-w64-binutils/0001-Revert-check-thin-archive-element-file-size.patch, mingw-w64-binutils/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10860
=> binutils: Add patch for thin static libraries (fix #10860)

mingw-w64-lensfun/PKGBUILD
=> lensfun: let SSE/SSE2 be detected automatically

mingw-w64-openimageio/0021-clang-thread-api.patch, mingw-w64-openimageio/PKGBUILD
Checking out /clang64/include/c++/v1/__config_site, it seems the Win32 API is directly used for libc++ std::thread implementation rather than pthreads like it is the case for libstdc++
=> oiio: update to 2.2.20, fix clang

mingw-w64-ruby/0008-ucrt-32-win11-insns.patch, mingw-w64-ruby/PKGBUILD
Fixes #10896.  For now.  At least in the case I saw and tested.  This is some messed up code.
=> ruby: patch ucrtbase pattern for 32-bit on Win11/Server2022.

mingw-w64-crt-git/PKGBUILD, mingw-w64-headers-git/PKGBUILD, mingw-w64-tools-git/PKGBUILD, mingw-w64-winpthreads-git/PKGBUILD
instead of git am which requires a committer config
pkgver doesn't depend on HEAD, so this shouldn't change anything
=> mingw-w64: use git apply

mingw-w64-gtk3/PKGBUILD
Note: had to insert a little hack to avoid the 3.24.32.1 tag getting in the way. ~~Let's see if in the meantime it gets deleted in the upstream repo.~~ See https://gitlab.gnome.org/GNOME/gtk/-/tags
EDIT: Actually 3.24.32.1 is not the same as 3.24.32, so I think this PR is good to go
=> gtk3: update to 3.24.32

mingw-w64-python-pytest-shutil/PKGBUILD
and not path.py, which is only needed for Python <3.5
=> pytest-shutil: depend on python-path

.ci/ci-build.sh, .github/workflows/main.yml
This should be safer if there's something in the PKGBUILD that evaluates false.
Also, remove can-fail parameter from commented-out CLANGARM64 matrix entry, now that it is unused.
Ref: https://github.com/msys2/MINGW-packages/pull/10910#discussion_r820151645
=> CI: source PKGBUILD from a subshell

mingw-w64-smpeg/PKGBUILD
=> smpeg: move gtk2 to `optdepends`

mingw-w64-pango/PKGBUILD
Hi! I have a question for the msys2 maintainers. Consider the output of Meson at the configure stage:
```
$ MINGW_ARCH=mingw64 makepkg-mingw
==>  MINGW_ARCH: mingw64
-> Building mingw64...
==> Making package: mingw-w64-pango 1.50.5-1 (Mon Mar  7 14:25:45 2022)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Downloading pango-1.50.5.tar.xz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4191k  100 4191k    0     0   517k      0  0:00:08  0:00:08 --:--:--  390k
==> Validating source files with sha256sums...
pango-1.50.5.tar.xz ... Passed
==> Extracting sources...
-> Extracting …
```
=> pango: update to 1.50.5

mingw-w64-port-scanner/0001-use-CC-from-environment.patch, mingw-w64-port-scanner/PKGBUILD
The clang C compiler is no longer installed with the alias `gcc`. Adapt the build rules for that change.
=> port-scanner: Fix building with clang.

mingw-w64-slim-simulator/0001-Remove-Qt-version-check.patch, mingw-w64-slim-simulator/PKGBUILD
The check for the exact Qt version doesn't seem to be necessary. Usually, the Qt5 libraries are API compatible between minor updates.
If they are not, we'd need to rebuild all dependencies of Qt5 anyway (including slim-simulator).
Fixes #10952.
=> slim-simulator: Remove check for Qt version.

mingw-w64-clucene/010-pthread.patch, mingw-w64-clucene/020-gcc.patch, mingw-w64-clucene/PKGBUILD
Changed CXX_STANDARD to 98 as 11 requires stricter list initialization.
Switch to build with Ninja. Faster.
Added pthread patch for UCRT.
Added clang32 where this was tested.
=> clucene: fix compilation with clang

mingw-w64-nana/011-march.patch, mingw-w64-nana/PKGBUILD
Also solves the clamgarm64 build problem (no -march=native support)
=> nana: do not optimize for host

mingw-w64-onednn/PKGBUILD
We couldn't build documentation because there is no doxyrest.
https://github.com/oneapi-src/oneDNN/blob/v2.5.3/cmake/doc.cmake#L21
=> onednn: update to 2.5.3

.ci/ci-check.py
When the `check` job is run with multiple packages, `pip` might be uninstalled when one step is cleaned up with `pacman --remove -cns XXX`. See e.g., https://github.com/msys2/MINGW-packages/pull/9931#issuecomment-1065110743.
IIUC, this change re-installs `pip` when the next package is checked.
I'm not sure if this is the correct place for that. Comments much appreciated.
=> ci-check: Re-install pip if it was removed.

mingw-w64-python-beniget/PKGBUILD, mingw-w64-python-pythran/001-fix-default-config.patch, mingw-w64-python-pythran/PKGBUILD, mingw-w64-python-scipy/PKGBUILD, mingw-w64-xsimd/PKGBUILD
For some reason it accepts `config_fc ...` when building but rejects it when installing?
=> scipy: update to 1.8.0

.ci/ci-build.sh, .github/workflows/main.yml
This an initial work to check runtime dependencies at buildtime.
It checks runtime dependencies of all the `*.dll` and `*.exe` installed in `${MINGW_PREFIX}/bin`
Questions:
I think most of them are just extensions/plugins and their dependencies are mostly listed under `optdepends`.
Known issues:
the qt-svg commit is just a test, I will remove it before marking this PR as ready.
=> [CI] Check runtime dependencies

mingw-w64-libopenmpt/PKGBUILD
Security release:
* [Sec] Possible out-of-bounds write in malformed IT / XM / MPTM files using the internal LFO plugin. (r17076)
* [Sec] Possible out-of-bounds read when using Amiga BLEP interpolation with extremely high-pitched notes. (r17078, r17079)
https://lib.openmpt.org/libopenmpt/2022/03/13/security-updates-0.6.2-0.5.17-0.4.30-0.3.38/
=> libopenmpt: update to 0.6.2

mingw-w64-libxmp/PKGBUILD
I probably made a lot of mistakes. I don't play well with autotools and the latest release doesn't have Cmake yet. Only tested on MinGW64, relying on checks for the rest.
This has another optional dependency [unmo3](https://github.com/lclevy/unmo3), which we don't have yet.
It should be possible to add libxmp-lite later, if needed.
=> Add libxmp

.ci/ci-build.sh
Good:
- de-duplicate code
- No more need for `.ci-sequential` trick for conflicting split packages.
- Check their runtime dependencies independently.
Bad:
- Take more time because of repeated intall/uninstall
=> [CI] Install split packages separately.

mingw-w64-perl-math-int64/PKGBUILD, mingw-w64-perl-win32-api/PKGBUILD, mingw-w64-perl-win32-console/PKGBUILD, mingw-w64-perl-win32-shortcut/PKGBUILD, mingw-w64-perl-win32-winerror/PKGBUILD, mingw-w64-perl-win32api-registry/PKGBUILD, mingw-w64-perl/PKGBUILD
Perl's build system apparently keys off of CC being `gcc` to decide whether to use GCC or CL style options, and patching Perl to use `clang` results in an odd mix of GCC and CL style options when building modules.  Rather than digging into that mess, makedepend on gcc-compat package so that Perl can keep on using `gcc`.
=> perl (and C modules): makedepend on gcc-compat on clang

mingw-w64-doxygen/PKGBUILD
Disable wizard, to avoid needing qt5 just yet.
=> doxygen: enable for clangarm64

mingw-w64-postgresql/PKGBUILD, mingw-w64-postgresql/postgresql-14.0-use-mingw-setjmp-on-ucrt.patch
- Use `setjmp` instead of `__builtin_setjmp` on UCRT
- Improve winpty wrappers (based on github-cli)
- tests actually pass, so remove `|| true`
=> postgresql: update to 14.2

mingw-w64-dnslookup/PKGBUILD, mingw-w64-dnslookup/update-quic-go.patch
enable for clang32 and  clangarm64
=> dnslookup: fix build with go 1.18

mingw-w64-rrdtool/001-rrdtool-1.8.0-BUILD_DATE.patch, mingw-w64-rrdtool/PKGBUILD
Disable `BUILD_DATE`, which is currently broken [1]
- Add patch:
`001-rrdtool-1.8.0-BUILD_DATE.patch`
- Fixes segfault when running "rrdtool --help"
[1] https://github.com/oetiker/rrdtool-1.x/pull/1102#issuecomment-1075586404
=> rrdtool: Disable BUILD_DATE

mingw-w64-cgns/PKGBUILD
No package depends on cgns, so no need to rebuild anything.
=> cgns: update to 4.3.0

mingw-w64-rclone/PKGBUILD
enable for clang32
unfortunately clangarm64 failed with
```
.debug_frame+1MB: addpesym: could not map .debug_frame+1MB symbol with non .text or .rdata or .data section
.debug_frame+2MB: addpesym: could not map .debug_frame+2MB symbol with non .text or .rdata or .data section
```
so not enabling that.  (same error as https://github.com/msys2/MINGW-packages/pull/11069#issuecomment-1075774548)
=> rclone: depend on cc not gcc, makedepend on git

mingw-w64-libvips/PKGBUILD
Plus:
- update project URL
- add support for HEIC
- add support for AVIF
- add support for jpeg2000
- don't build the old vips7 API (saves a few kb)
- remove giflib (libvips now has its own GIF reader)
=> libvips: update to 8.12.2

mingw-w64-openblas/001-index64.patch, mingw-w64-openblas/PKGBUILD
`ctest` currently fails for the 64-bit indexing version on MINGW. That is because `long` is used in the C interface when calling the Fortran functions that use 64-bit integers. On Windows 64-bit, `long` is 32-bit wide.
This adds a patch that was proposed upstream (cherry-picked from reference-LAPACK).
=> openblas: Fix 64-bit indexing version on MINGW64.

mingw-w64-petsc/PKGBUILD
It also fix building on clang64, but without MPI which I failed to fix unfortunately.
=> petsc: update to 3.16.5

mingw-w64-darktable/001-define-libraw-win32-unicodepaths-libcxx.patch, mingw-w64-darktable/10662-libraw.patch, mingw-w64-darktable/10662.patch, mingw-w64-darktable/PKGBUILD
CLANG64 job failed:
```
ld.lld: error: undefined symbol: _setjmp
>>> referenced by C:/_/mingw-w64-darktable/src/darktable-3.8.1/src/common/imageio_jpeg.c:134
>>>               bin/CMakeFiles/lib_darktable.dir/common/imageio_jpeg.c.obj:(dt_imageio_jpeg_decompress_header)
>>> referenced by C:/_/mingw-w64-darktable/src/darktable-3.8.1/src/common/imageio_jpeg.c:200
>>>               bin/CMakeFiles/lib_darktable.dir/common/imageio_jpeg.c.obj:(dt_imageio_jpeg_decompress)
>>> referenced by C:/_/mingw-w64-darktable/src/darktable-3.8.1/src/common/imageio_jpeg.c:212
>>>               bin/CMakeFiles/lib_darktable.dir/common/imageio_jpeg.c.obj:(dt_imageio_jpeg_decompress)
>>> referenced 9 more times
```
Any idea how to fix it?
=> darktable: update to 3.8.1

mingw-w64-hiredis/0001-Add-static-library-target-and-cpack-support.patch, mingw-w64-hiredis/PKGBUILD
* Separate build directory.
* Build in release mode.
* Use ninja.
* Include a patch from master that adds static libs.
=> hiredis: update to 1.0.2 and improve build process

mingw-w64-netcdf/PKGBUILD
FindHDF5 from CMake is now fixed after I have backported a fix from https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7105
=> netcdf: Rebuild to fix generated cmake and pkgconfig files.

.ci/ci-get-build-order.py
This doesn't seem to be necessary after
6913cd7f417fe98b7db2fe7f7571bf71629a4c77, and causes issues with
packages that attempt to dynamically adjust their metadata.
See https://github.com/msys2/MINGW-packages/pull/11143#issuecomment-1086697564
=> CI: don't override MINGW_PACKAGE_PREFIX when getting build order.

.ci/ci-check.py
=> CI: run `pip check` with & without reverse-dependencies installed

mingw-w64-flang/0001-cast-cxx11-narrowing.patch, mingw-w64-flang/PKGBUILD, mingw-w64-mlir/PKGBUILD
Depends on #11087.
Updated patch to fix 32-bit build of flang.
Removed mlir from toolchain group on clang prefixes.  mlir seems to get errors building if an older version is installed, which is not good behavior for something in the toolchain group.  I don't believe there was a strong reason for it to be in the toolchain group in the first place, other than that it was in the clang split package originally and everything in there was.
=> mlir, flang: update to 14.0.0

mingw-w64-qt6-static/PKGBUILD
prune some makedepends that were only there due to messed up llvm cmake files, which have been cleaned up by building llvm projects separately.
turn on system harfbuzz.  It's already being pulled in via freetype, apparently, because I get
```
ld.lld: error: duplicate symbol: hb_font_funcs_create
>>> defined at libQt6BundledHarfbuzz.a(hb-font.cc.obj)
>>> defined at libharfbuzz.a(hb-font.cc.obj)
```
add -lusp10 to HARFBUZZ_DEPENDENCIES.  This is a system DLL import library, was getting a couple of undefined symbols when linking.
=> qt6-static: rebuild for llvm/clang 14 (and build fixes)

mingw-w64-python-sphinx/PKGBUILD, mingw-w64-python-sphinx_rtd_theme/PKGBUILD
I could do nothing about `docutils` dependency that has been already updated to 0.18.1
=> python-sphinx_rtd_theme: update to 1.0.0

mingw-w64-wxWidgets/008-wxWidgets-3.0-Add-msw-manifests-for-arm-and-arm64-platforms.patch, mingw-w64-wxWidgets/PKGBUILD
Last time when I enabled clangarm64, I added exe manifests for ARM and ARM64, but they are not actually installed because makefiles are not updated.
This breaks downstream like PCem. (Not sure why FileZilla is not affected, they supply their own manifests?)
3.1.x are fixed upstream on the new 3.1.6 version, so opened https://github.com/msys2/MINGW-packages/pull/11316 for the update.
=> wxWidgets: install arm manifests

mingw-w64-crt-git/PKGBUILD, mingw-w64-headers-git/PKGBUILD, mingw-w64-libmangle-git/PKGBUILD, mingw-w64-tools-git/PKGBUILD, mingw-w64-winpthreads-git/PKGBUILD, mingw-w64-winstorecompat-git/PKGBUILD
I would have updated the pkgver to 10.0.0 even, since this is the commit
officially tagged as v10.0.0, but this package is updated against git
commits so often that tweaking the pkgver function for one version
didn't seem worth the effort.
Take this opportunity to switch pkgver to using git describe, as doing
so when the more significant version numbers don't change would make the
new version compare lower.
The --long argument and sed pattern for git describe comes from the
CMake-git PKGBUILD template.
=> mingw-w64: update to 10.0.0

mingw-w64-gptfdisk/0001-makefile-Drop-g-compiler-flag-for-mingw-builds.patch, mingw-w64-gptfdisk/0002-makefile-Switch-to-building-shared-executables-for-m.patch, mingw-w64-gptfdisk/0003-makefile-Fix-the-sgdisk-rule-for-mingw-builds.patch, mingw-w64-gptfdisk/0004-makefile-Specify-std-c-14-for-mingw-builds.patch, mingw-w64-gptfdisk/0005-makefile-Avoid-absolute-path-in-CXX-for-mingw-builds.patch, mingw-w64-gptfdisk/0006-makefile-Omit-the-64-suffix-in-the-executable-names.patch, mingw-w64-gptfdisk/PKGBUILD
This adds a new package for mingw64: gptfdisk.
It includes text-mode partitioning tools that work on GUID Partition
Table (GPT) disks.
The following tools are included:
- gdisk.exe
- sgdisk.exe
- fixparts.exe
Signed-off-by: Bin Meng <bmeng.cn@gmail.com>
=> Add gptfdisk package 1.0.8

mingw-w64-arpack/0003-blas-lapack-pc.patch, mingw-w64-arpack/PKGBUILD
Don't override libraries that have already been (correctly) set by the corresponding cmake modules.
Libraries (in passed variable) might not start with "lib".
Fixes #11376.
=> ARPACK: Fix libraries for pkg-config file.

mingw-w64-qpdf/0003-install-rule.patch, mingw-w64-qpdf/PKGBUILD
I couldn't find out why It fails on CLANG64.
The library built successfully, but lld couldn't find it when linking programs.
=> qpdf: update to 10.6.3

mingw-w64-python-cppy/PKGBUILD, mingw-w64-python-kiwisolver/PKGBUILD
The latest versions of cppy and kiwisolver are 1.2.1 and 1.4.2, but they got built as unknown.
=> python-kiwisolver: update to 1.4.1

mingw-w64-rrdtool/001-rrdtool-1.8.0-BUILD_DATE.patch, mingw-w64-rrdtool/002-rrdtool-1.8.0-rrd_first.patch, mingw-w64-rrdtool/PKGBUILD
- Update patch to the upstream solution:
`001-rrdtool-1.8.0-BUILD_DATE.patch`
- Add patch:
`002-rrdtool-1.8.0-rrd_first.patch`
This fixes an integer overflow in `rrd_first()`, which appeared in
`mingw-w64-x86_64` and `mingw-w64-ucrt-x86_64` builds of rrdtool.
Remark: `mingw-w64-i686` was not affected.
=> rrdtool: Update and add patch

mingw-w64-lapack/PKGBUILD
Also correct the license in the package description.
The checks for CBLAS are failing. This is not a regression from this update but already happened (at least) with 3.10.0.
The other tests ("proper" BLAS, LAPACK) are passing.
Tbh, I don't understand the error messages (something about a missing file).
Is it ok to leave the checks in but ignore its result for the time being?
=> lapack: update to 3.10.1

mingw-w64-openblas/PKGBUILD
https://github.com/xianyi/OpenBLAS/pull/3539 used f2c on a current version of reference LAPACK with manual post-processing to add a version of netlib LAPACK that can be compiled without a Fortran compiler.
This PR adds those changes for the CLANG* environments.
The PR is pretty large and it is still marked as WIP. But it seems to be compiling without major problems in the CLANG64 and CLANG32 environments.
I tested in CLANG64 by compiling igraph linking to this patched version of OpenBLAS (instead of f2cblaslapack). It compiles correctly and passes all tests.
Looking forward, we could transition the packages that currently link to the BLAS/LAPACK libraries from f2cblaslapack to this modified version of OpenBLAS.
As an even longer term goal, would it be possible to establish some kind of …
=> OpenBLAS: Build C_LAPACK in CLANG* environments.

mingw-w64-suitesparse/PKGBUILD
The OpenBLAS including C_LAPACK for the CLANG* environments is in staging now. Packages that currently link with "our" f2cblaslapack can be transitioned to linking with OpenBLAS instead. That might result in a performance gain for those packages.
=> suitesparse: Link against OpenBLAS also in CLANG* environments.

mingw-w64-octave/PKGBUILD
This is only to unblock the build system in a case something similar to what happened in #11529 should occur again in the future. Nothing changed in the build rules that would actually affect the resulting binaries. No need to bump the pkgrel for this probably.
=> octave: Add timeout to configure step.

mingw-w64-armadillo/0003-superlu.patch, mingw-w64-armadillo/PKGBUILD
Build with SuperLU.
Correct license in description.
Use LAPACK in OpenBLAS also for CLANG* environments.
=> armadillo: update to 11.0.1

mingw-w64-ncurses/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11543
export was missing
=> ncurses: fix hack to not use nanosleep 

mingw-w64-qemu/PKGBUILD, mingw-w64-qemu/msys2.examples.tests.sh, mingw-w64-qemu/msys2.qemu-guest-agent.txt
Another qemu update cycle starting with RC0.
To enable compilation in clang, a small patch is necessary to get rid of
```
../qemu-7.0.0-rc0/qga/vss-win32/install.cpp:49:24: error: cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'
char *msg = NULL, *nul = strchr(text, '(');
^     ~~~~~~~~~~~~~~~~~
```
Will provide the patch to upstream ASAP
=> qemu: Update to 7.0.0

mingw-w64-openmp/002-hacks-for-static-linking.patch, mingw-w64-openmp/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10269
The first hunk could probably be upstreamed? The main usage for it is if CPPFLAGS is set with spaces inside, e.g. `-DFLAG=1 -DOTHER_FLAG=2` as its current line would result in `-DFLAG="1 -DOTHER_FLAG=2"`
For the second and third, I'm still not sure why static openmp is disabled on Windows, so I have no clue if they can be upstreamed or not
=> openmp: add hacks for compiling both shared and static builds

mingw-w64-openjpeg2/0006-openjpeg-2.1.0-stdcall-for-all-win.patch, mingw-w64-openjpeg2/PKGBUILD
This patch was disable in 8edfe204d937edf31b0310c6195de5a337c270b9 commit.
But it fixes static linking with 32 bit ffmpeg. Previously, the stdcall
decoration was only enabled in shared libs but not in static libs. So,
when OPJ_STATIC is enabled the ffmpeg configure fails to check function
without stdcall decoration in 32 bit environment.
=> openjepg2: Reapply stdcall for all library type

mingw-w64-msmpi/PKGBUILD
From the discussion in https://github.com/msys2/MINGW-packages/pull/11607
@mmuetzel @gharveymn @okhlybov
=> msmpi: Rename import library to .dll.a extension

mingw-w64-cmake/PKGBUILD
We change the default generator to ninja, so we should also
make sure it is always available.
Fixes #11620
=> cmake: depend on ninja

mingw-w64-python-hid/PKGBUILD
License install is commented out for now as it wasn't included in the manifest until recently (https://github.com/apmorton/pyhidapi/pull/44).
=> python-hid: new package

mingw-w64-openssl/18258.patch, mingw-w64-openssl/PKGBUILD
Some UB results in broken code starting with Clang 14. This only
affects the no-asm case, which is only used for our arm64 build.
This resulted in runtime errors such as:
```
19560:error:1012606B:elliptic curve routines:EC_POINT_set_affine_coordinates:point is not on curve:../openssl-1.1.1o/crypto/ec/ec_lib.c:813:
19560:error:100AF010:elliptic curve routines:ec_group_new_from_data:EC lib:../openssl-1.1.1o/crypto/ec/ec_curve.c:3083:
19560:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:../openssl-1.1.1o/crypto/ec/ec_curve.c:3159:
19560:error:100D7010:elliptic curve routines:eckey_pub_decode:EC lib:../openssl-1.1.1o/crypto/ec/ec_ameth.c:168:
19560:error:0B09407D:x509 certificate routines:x509_pubkey_decode:public key decode …
```
=> openssl: backport fix for broken EC code with clang 14

mingw-w64-ngraph-gtk/PKGBUILD
new upstream version 6.09.05 is  released.
=>  ngraph-gtk: new upstream release version 6.09.06.

mingw-w64-flang/PKGBUILD
It wasn't installable because it hard depends on clang 14.0.0.
Update and remove the overly strict version requirement.
=> flang: Update to 14.0.3

mingw-w64-meld3/1001-meld-build-fix-i18n-usage.patch, mingw-w64-meld3/1002-meld-import-emblem-new-from-evolution.patch, mingw-w64-meld3/PKGBUILD
After the adwaita-icon-theme 42.0 update, meld couldn't find `${MSYSTEM_PREFIX}/share/icons/Adwaita/8x8/legacy/emblem-new.png`, which messed up the GUI. This has already been fixed [in meld](https://gitlab.gnome.org/GNOME/meld/-/merge_requests/83). The upstream build fix corresponds to https://github.com/mesonbuild/meson/issues/9441. PR tested locally, see screenshots.
BTW, meson was looking for `desktop-file-validate`; it doesn't seem to use it though, so I didn't bother adding desktop-file-utils to `makedepends`. I'll leave that to the maintainers.
=> meld: Add upstream patches to fix building and GUI

mingw-w64-ffmpeg/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11514
Fixes https://github.com/msys2/MINGW-packages/issues/11515
Fixes https://github.com/msys2/MINGW-packages/issues/11538
Fixes https://github.com/msys2/MINGW-packages/issues/11539
=> ffmpeg: Add pkgconfig static flag for static library

mingw-w64-gcc/PKGBUILD
At least with mingw32 + dwarf-2 exceptions there can only be one libgcc in
process, or exceptions will no longer work. Since some of the gcc deps are
linked dynamically like gmp/zlib/zstd and those pull in libgcc we can't
allow libgcc to be linked statically. The default is "-static-libstdc++
-static-libgcc" for both, so we drop "-static-libgcc" here.
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105507#c3
----
And the reason why this only is a problem for ada is that the other GCC target languages currently don't use exceptions.
=> gcc: fix exceptions handling for ada with mingw32

mingw-w64-python-jsonschema/PKGBUILD
Also:
- Aligned closer to template
- Removed python-six dependency (https://github.com/python-jsonschema/jsonschema/commit/027feac3cd6d2970ec56d08c566cef66731b637e)
Only one test failing, not sure if it matters:
```
>       self.assertIn(f"{os.sep}someNonexistentFile.json'", error)
E       AssertionError: "/someNonexistentFile.json'" not found in "<urlopen error [WinError 2] The system cannot find the file specified: 'D:\\\\Git\\\\mingw-packages\\\\mingw-w64-python-jsonschema\\\\src\\\\someNonexistentFile.json'>"
```
=> python-jsonschema: update to 4.5.1

mingw-w64-tools-git/PKGBUILD
It defaults to /ucrt64/x86_64-w64-mingw32/include otherwise, which no
longer exists.
See #11547
=> mingw-w64-tools: set --with-widl-includedir to the default include dir

mingw-w64-cmake/0007-No-hardcoded-gcc-with-MINGW-or-MSYS-Makefiles.patch, mingw-w64-cmake/PKGBUILD
=> cmake: Remove hardcoded gcc/g++ from MinGW/MSYS Makefiles

mingw-w64-gcc/1001-libgomp-use-_aligned_free-in-gomp_aligned_free-if-ne.patch, mingw-w64-gcc/1002-libgomp-don-t-use-GOMP_USE_ALIGNED_WORK_SHARES-on-Wi.patch, mingw-w64-gcc/PKGBUILD
It has started to mix _aligned_malloc() with normal free() which
isn't supported on Windows and crashes.
This adds some temporary fixes. Upstream might fix this differently though,
we'll see.
Fixes #11729
=> gcc: fix libgomp crashing in various places

mingw-w64-wxWidgets3.1/001-wxWidgets-3.0.2-relocate-prefix-in-bin-wx-config.patch, mingw-w64-wxWidgets3.1/010-wxWidgets-3.1.6-Redo-manifest-filename-logic.patch, mingw-w64-wxWidgets3.1/PKGBUILD
Removed MSYSTEM guard in "wx-config.in",
the other option of adding all the other environments 
like CLANG64 was advised against in the prior PR.
Redo manifest filename logic in "wx/msw/wx.rc".
The prior manifest logic failed to work under Clang64;
When building samples during check.
Add replaces "wxmsw3.1-git" package.
Add "enable-graphics-d2d" to help support Code::Blocks IDE.
Enable check code to build DLL samples.
=> wxWidgets3.1: Update to version 3.1.6; and,

mingw-w64-kicad/PKGBUILD
Also, build in clang32 environment.
See: #11699
=> kicad: re-enable building support libraries

mingw-w64-glpk/PKGBUILD
According to package grokker, one symbol was removed with the update. So, rebuilding dependencies, too.
I took the opportunity to build python-cvxopt with OpenBLAS also for the CLANG environments. That might result in better performance on some operations.
=> glpk: update to 5.0

mingw-w64-wxWidgets/009-warn-for-compiler-abi-mismatch.patch, mingw-w64-wxWidgets/PKGBUILD
Adding that patch was proposed by @Biswa96 in #11759 (and before by @jeremyd2019 in #9913). Other distributions (e.g., Debian and ArchLinux) are using the same patch. So, I'd guess it might be save for MSYS2 as well.
Fixes #11759.
=> wxWidgets: suppress error about mismatching C++ ABI version

mingw-w64-python-qmk/PKGBUILD
Attempting to run `qmk` results in `Fatal error in launcher: U`. The appended Python script had the CI cygpath in its hashbang, but for some reason `makepkg-mingw` didn't pick up on it. I referenced python-jsonschema which also has an .exe launcher.
=> python-qmk: fix launcher crash

mingw-w64-highway/PKGBUILD
This should now be built the same way libjxl CI does it (they upgraded to 0.17 recently as well). @Biswa96 @novomesk @thebombzen @Jehan @ccicnce113424
Obviously, only libjxl master can benefit from this version for debundling, not the currently packaged 0.6.1...
=> highway: update to 0.17.0

mingw-w64-python-numpy/PKGBUILD
=> python-numpy: don't depend on openblas for clangarm64

mingw-w64-aws-sdk-cpp/PKGBUILD
Currently, the AWS SDK for C++ package does not support all features.
By including AWS lambda in the list of supported features, I will be able to use the package for my AWS lambda needs
=> aws-sdk-cpp: Add AWS lambda

mingw-w64-kicad-library/PKGBUILD, mingw-w64-kicad/PKGBUILD
Overhaul build rules.
This is also how ArchLinux packages KiCad:
https://github.com/archlinux/svntogit-community/blob/packages/kicad/trunk/PKGBUILD
https://github.com/archlinux/svntogit-community/blob/packages/kicad-library/trunk/PKGBUILD
This change would allow to, e.g., bump the pkgrel of the core application without the need to rebuild the huge support libraries.
See #11751.
=> kicad: separate build rules for core application and support libraries

mingw-w64-binutils/PKGBUILD
They were moved to a subdirectory in 047d1d662f (binutils: resolve
conflicts with headers and libs with gdb, Dec 2013). Since then, gdb and
binutils repositories were merged, and gdb does not install these headers
and libs at all, so there is no conflict.
Linux systems have bfd.h, libbfd.a and libiberty.a in include and lib, and
not in a subdirectory.
Also, placing them in a subdirectory requires the users to specify the lib
directory, and have non-portable #include statements (binutils/bfd.h on
MinGW, else bfd.h).
Keep the original locations as symbolic links to maintain backwards
compatibility.
=> binutils: Move include and libs back to native directories

mingw-w64-petsc/0002-openblas-clang.patch, mingw-w64-petsc/PKGBUILD, mingw-w64-slepc/PKGBUILD
Also, build with OpenBLAS in clang* environments.
=> petsc and slepc: update to 3.17.1

mingw-w64-gmsh/PKGBUILD, mingw-w64-med/PKGBUILD, mingw-w64-med/bin-dest.patch
Also slightly overhaul the build rule.
It is probably not strictly necessary to rebuild gmsh (its only depend package). But I took the opportunity to build it for clang32 and clang64.
=> med: update to 4.1.1

mingw-w64-doxygen/PKGBUILD
ucvector_resize() will not initialize the the vecotr otherwise and crash.
Not sure if this is a compiler bug, or something else.
Since this only happens with clang32 reduce to -O1 only there
(-O2 and -O3 crash)
Fixes #11787
=> doxygen: reduce optimization level for clang32 to avoid crashes

mingw-w64-libgphoto2/PKGBUILD
This reverts commit 5b286a621f2f20ad9e0c0bfd808383537bbe78c0.
Try again after #11789
=> Revert "libgphoto2: build without doxygen"

mingw-w64-boost/PKGBUILD, mingw-w64-boost/boost-1.79.0-fix-container-list-pair.patch
Upstream PR: https://github.com/boostorg/container/pull/222
Example:
```
boost::container::list<std::pair<int, int>> list;
```
```
.../boost/container/allocator_traits.hpp:403:11: error: invalid use of
incomplete type 'struct boost::container::dtl::pair<int, int>'
403 |    {  p->~T(); (void)p;  }
|       ~~~~^
In file included from .../boost/container/detail/node_alloc_holder.hpp:39,
from .../boost/container/list.hpp:34:
.../boost/container/detail/is_pair.hpp:59:8: note: declaration of 'struct boost::container::dtl::pair<int, int>'
59 | struct pair;
|        ^~~~
```
=> boost: Fix incomplete type error when using list with pair

mingw-w64-graphviz/PKGBUILD
We want to get rid of gtk2 eventually
=> graphviz: drop gtk2 dependency

mingw-w64-msmpi/PKGBUILD, mingw-w64-msmpi/mpi.c
A follow-up to #11794.
1. Thin archives tend to be fragile.
- Library stripping destroys thin archives.
- LLVM's AR seems to produce broken (empty) thin archives.
2. Fixing the `mpi**` drivers is not an option as *-Bdynamic* is a command line -wise option which affects all libraries that follow it, either explicitly specified or implicitly added by the linker. This effectively defeats production of statically linked MPI binaries with `mpi** -static` without severe drivers modifications.
3. No way to use *-Bdynamic* in .pc files for the same reason as in [2].
~~The bottom line: the best option is simply to have `.a` and `.dll.a` archives with the same contents and to let compiler pick the appropriate version based on the supplied options.~~
**UPD**
The `-l:` solution works for both GCC and …
=> msmpi: static linking fix

mingw-w64-avr-binutils/PKGBUILD, mingw-w64-avr-gcc/PKGBUILD, mingw-w64-avr-gdb/PKGBUILD, mingw-w64-avr-libc/PKGBUILD
Do we need to bump pkgrel to produce missing `ucrt64` build of `mingw-w64-avr-gcc`?
It build fine on my machine.
Disabled `mingw-w64-avr-gcc` for Clang because it fork-bombed my machine by recursively spawning tens of thousands compiler processes during: `checking whether compiler driver understands Ada...`
=> Standarize GNU AVR toolchain PKGBUILDs

mingw-w64-python-tomli/PKGBUILD, mingw-w64-python-tomli/install_wheel.py
install manually for bootstrapping
=> python-tomli: don't depend on python-build/installer

mingw-w64-cmake/0008-fix-find-mpi.patch, mingw-w64-cmake/PKGBUILD, mingw-w64-precice/0001-fix-include.patch, mingw-w64-precice/PKGBUILD
File streams are no longer implicitly defined when including `<istream>`. Include the correct header instead.
~Depends on #11844 for MPI.~ #11844 is included in this PR now.
Fixes #11839.
=> precice: fix building with gcc 12

mingw-w64-prjtrellis/PKGBUILD
Build from release tarball.
The memory footprint of `cc1plus` is too large during compilation of `PyTrellis.cpp`. It fails with `cc1plus.exe: out of memory allocating 65536 bytes`. Maybe something in GCC (or Boost?) changed since this was last compiled that makes it require too much memory now. When building in a MINGW64 environment, the memory footprint peaks at about 4.1 GiB. IIUC, the maximum memory footprint for one 32-bit process on Windows is 2 GiB. If the 32-bit executable would require approx. half as much memory as the 64-bit one, that would still be too much (and it looks like it *is* too much).
See also #11837.
@umarcor: Is this change ok?
Does it make sense to skip building the Python library on mingw32 and continue building the remainder? Is that still useful?
=> prjtrellis: no longer build Python library for mingw32

mingw-w64-pyqt-builder/001-mingw-python.patch, mingw-w64-pyqt-builder/PKGBUILD
=> pyqt-builder: remove extra output when queried variable is empty

mingw-w64-python/PKGBUILD, mingw-w64-python/update-patches.sh
Python now is compiled with `-O2` level optimization, which makes it obviously slower than official python compiled by MSVC with the max optimization level.
For a simple test:
``` python
from timeit import default_timer as timer
import os
def plus():
a = 0
for x in range(100000000):
a += 1
def minus():
a = 100000000
for x in range(100000000):
a -= 1
def multiply():
a = 1
for x in range(100000000):
a *= 1.00000003
def divide():
a = 1000000000
for x in range(100000000):
a /= 1.00000003
if __name__ == '__main__':
s = timer()
plus()
e = timer()
print('Plus:',round(100000000/(e-s)/1000000,2),'M/s')
s = timer()
minus()
e = timer()
print('Minus:',round(100000000/(e-s)/1000000,2),'M/s')
s = timer()
multiply()
e = timer()
print('Multiply:',round(100000000/(e-s)/1000000,2),'M/s')
s = timer() …
```
=> Python: Use `-O3` level optimization

mingw-w64-avr-binutils/PKGBUILD
```
error: failed to commit transaction (conflicting files)
mingw-w64-x86_64-avr-binutils: /mingw64/share/info/ctf-spec.info.gz exists in filesystem (owned by mingw-w64-x86_64-binutils)
Errors occurred, no packages were upgraded.
```
=> avr-binutils: fix file conflict

mingw-w64-fpm/PKGBUILD
Update for release at https://github.com/fortran-lang/fpm/releases/tag/v0.6.0
=> Update fpm to version 0.6.0

mingw-w64-avr-binutils/PKGBUILD
Fixing another (potential) conflict by placing libdep under an `avr` directory inside lib.
=> avr-binutils: set libdir

mingw-w64-libdeflate/002-pkg-config.patch, mingw-w64-libdeflate/PKGBUILD
The header file of libdeflate contains the following comment:
```
/*
* On Windows, if you want to link to the DLL version of libdeflate, then
* #define LIBDEFLATE_DLL.  Note that the calling convention is "stdcall".
*/
```
This PR adds a patch for the .pc file that reflects that requirement.
IIUC, the `-U` flag should undo the `-D` flag when linking statically.
This fixes a build error with GDAL.
=> libdeflate: fix dynamic linking using pkg-config

mingw-w64-osgworks-git/PKGBUILD
Also use ninja generator in build rule.
This prevent errors caused by the hardcoded paths in the .cmake file when re-building dependent packages (e.g., `osgbullet-git`) locally.
=> osgworks-git: support relocation

mingw-w64-github-cli/PKGBUILD
For details, see https://github.com/cli/cli/releases/tag/v2.13.0
=> gh: update to v2.13.0

mingw-w64-netcdf/0001-no-debug-libraries.patch, mingw-w64-netcdf/0002-no-file.patch, mingw-w64-netcdf/PKGBUILD
It looks like `errno` isn't set when file cannot be opened. Set it manually instead.
Fixes #11918.
Also fix some linker flags that get messed up if the detected debug library is the same as the release library.
=> netcdf: fix segfault if file cannot be opened

mingw-w64-emacs/001-ucrt.patch, mingw-w64-emacs/PKGBUILD
for both stdout and stderr fclose fail during atexit as if they
were already closed. the function in theory has a workaround for that
in that it will continue if errno is EBADF, but fclose doesn't set that
on Windows.
This shows at least what is missing/broken if upstream wants to have a look.
=> emacs: some hacky patches to make it work on ucrt64

mingw-w64-fftw/PKGBUILD
Fixes #10150.
Switching completely to a cmake based build rule isn't possible at this moment. It currently misses some options (e.g., options to switch on AVX-512 or build for quad precision among other things). But the missing files are already created on configuration with cmake. So, this doesn't add much to the total build time.
=> fftw: install missing .cmake files

mingw-w64-fzf/PKGBUILD
If `go test` in check(), it will fail. I guess it is because shell is not cmd.
```
?       github.com/junegunn/fzf [no test files]
--- FAIL: TestReplacePlaceholder (0.01s)
terminal_test.go:29: expected: echo ^"  foo'bar baz^", actual: echo '  foo'\''bar baz'
terminal_test.go:29: expected: echo ^"  foo'bar baz^", actual: echo '  foo'\''bar baz'
terminal_test.go:29: expected: echo ^"foo'bar baz^", actual: echo 'foo'\''bar baz'
terminal_test.go:29: expected: echo ^"foo'bar baz^", actual: echo 'foo'\''bar baz'
terminal_test.go:29: expected: echo ^"foo'bar baz^", actual: echo 'foo'\''bar baz'
terminal_test.go:29: expected: echo ^"  foo'bar baz^" ^"query^", actual: echo '  foo'\''bar baz' 'query'
terminal_test.go:29: expected: echo ^"foo'bar baz^" ^"FOO'BAR BAZ^"^"query 'string'^"^"foo'bar …
```
=> fzf: new package

mingw-w64-stxxl-git/PKGBUILD
* let cmake detect if gnu parallel is supported
* switch to std threads, to avoid build errors with clang+pthreads
(I hope this is ok?)
=> stxxl: fix the clang build

mingw-w64-gtksourceview3/PKGBUILD
this removes gtksourceview.xml. Arch does this too.
=> gtksourceview3: remove glade catalog to avoid conflict with gtksourceview4

mingw-w64-md4c/PKGBUILD
Simply adds build for static library to be included in package.
=> md4c: also build static library

mingw-w64-liblcf/PKGBUILD
Library to handle RPG Maker 2000/2003 and EasyRPG game data
- Homepage: https://easyrpg.org/
- Upstream: https://github.com/EasyRPG/liblcf
- Current version: 0.7.0
I don't think it is an issue, but I get the following output when building:
```
==> Tidying install...
-> Removing libtool files...
-> Purging unwanted files...
-> Stripping unneeded symbols from binaries and libraries...
...\mingw64\bin\objdump.exe: mingw64/include/lcf/config.h: file format not recognized
...\mingw64\bin\objdump.exe: mingw64/include/lcf/context.h: file format not recognized
...
```
For some reason, `objdump` wants to scan `.h` files.
=> New package: liblcf

mingw-w64-python-numpy/0013-fix-discovered-machar.patch, mingw-w64-python-numpy/PKGBUILD
Applied upstreamed [patch](https://github.com/numpy/numpy/pull/21815) that closes [issue](https://github.com/numpy/numpy/issues/21827).
=> python-numpy: Fix discovered MachAr

mingw-w64-curl/0004-more-static-fixes.patch, mingw-w64-curl/PKGBUILD
The patch is partly based on the one in MSYS-packages:
https://github.com/msys2/MSYS2-packages/blob/e687cc056aff2a98ad42f506102bb776af4e04d1/curl/0001-more-static-fixes.patch
Install license file.
Fixes #11953.
=> curl: fix .pc file for static linking

mingw-w64-gdb/0006-Fix-internal-error-when-printing-C-pointer-to-member.patch, mingw-w64-gdb/PKGBUILD
https://sourceware.org/bugzilla/show_bug.cgi?id=29294
Suggested-by: Tom de Vries <tdevries@suse.de>
=> GDB: Fix internal error when printing C++ pointer-to-member

mingw-w64-osgearth/0001-calling-convention.patch, mingw-w64-osgearth/PKGBUILD
The release tarball doesn't contain the git submodules. Checkout the tagged git commit instead.
Other than that, just a minor cleanup. And install the license.
=> osgearth: update to 3.3

mingw-w64-python-setuptools/0008-default-stdlib-distutils.patch, mingw-w64-python-setuptools/PKGBUILD
also default to stdlib distutils as the embedded one doesn't support mingw
=> python-setuptools: update to 62.6.0

mingw-w64-python-pillow/PKGBUILD
Promoted libraqm to required dependency, due to:
https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#libraqm-and-fribidi-linking
=> python-pillow: fix libraqm dependency

mingw-w64-OpenSceneGraph/PKGBUILD, mingw-w64-plplot/PKGBUILD, mingw-w64-spatialite-gui/PKGBUILD, mingw-w64-winsparkle/Makefile, mingw-w64-winsparkle/PKGBUILD
These changes make packages use wxWidgets 3.0.x instead of using the version returned by wx-config.
This is needed to prevent these four packages from using wxWidgets 3.2.0 when PR #12007 is applied.
Tim S.
=> Change packages to use wxWidgets 3.0.x

mingw-w64-github-cli/PKGBUILD
See https://github.com/cli/cli/releases/tag/v2.14.0 and https://github.com/cli/cli/releases/tag/v2.14.1 for details.
=> github-cli: upgrade to v2.14.1

mingw-w64-openshadinglanguage/0001-cmake-config.patch, mingw-w64-openshadinglanguage/PKGBUILD
There are two issues with the cmake config files of OSL:
1. One of the files is moved after it is installed. That leaves the cmake files pointing to the wrong locations.
2. A `sed` rule is used to replace the literal prefix of the build system with `${_IMPORT_PREFIX}`. But that variable isn't set in one of the .cmake files.
The file that is moved is a "module" library. IIUC, those are libraries that aren't meant to be linked to. But their symbols should be loaded on runtime. It looks like `cmake` installs those in the `lib` directory (not `bin`). Maybe, it does that for a reason. Instead of trying to change where `cmake` installs "module" libraries (which would probably also lead to consistent .cmake files), this change removes moving that library after it is installed.
It also adds a …
=> openshadinglanguage: fix cmake config files

mingw-w64-libc++/PKGBUILD
Since nobody wanted to work on manual stripping with `llvm-strip` lets just disable it. Size increase is only 0.75 MiB (all packages combined) and it might be also helpful for debugging.
Fixes https://github.com/msys2/MINGW-packages/issues/11553
=> Disable `strip` for libc++

mingw-w64-wxPython4.0/0003-Optionally-use-MinGW-toolchain.patch, mingw-w64-wxPython4.0/PKGBUILD
Add wax command line option `--no_msvc` to select a MinGW toolchain on Windows.
IIUC, this allows using more native build tools (instead of MSYS2/Cygwin tools).
See also this upstream PR: https://github.com/wxWidgets/Phoenix/pull/2211
=> wxPython4.0: fix building with MinGW toolchain

mingw-w64-python-distlib/003-launcher-secure-api-shim.patch, mingw-w64-python-distlib/PKGBUILD
By implementing _wdupenv_s() via _wgetenv_s() in case it isn't available.
We already do the same thing in python-installer.
See #12035
=> python-distlib: link launcher against msvcrt under MINGW32/64

mingw-w64-mathgl/001-fix-cmake-files.patch, mingw-w64-mathgl/PKGBUILD
This is the second time I have to pass `-DGLUT_glut_LIBRARY_RELEASE=${MINGW_PREFIX}/lib/libfreeglut.dll.a` to cmake to prevent it from picking `libglut.a` on `i686` environments.
Maybe building `libglut.a` should be disabled everywhere!
#437
#10915
=> mathgl: update to 8.0.1

mingw-w64-gobject-introspection/1001-resolve_windows_libs-add-llvm-support.patch, mingw-w64-gobject-introspection/PKGBUILD
g-i tries to lookup the DLL name based on the import lib but failed to
do so with clang. llvm-dlltool doesn't have an "--identify" option,
so parse "nm" output instead.
Fixes #11994
=> gobject-introspection: fix gir/typelib generation with llvm/clang

mingw-w64-libwmf/PKGBUILD
I can't see why it would be needed. let's see what CI says
=> libwmf: don't makedep on gtk2

mingw-w64-graphviz/PKGBUILD
pulls in gtk2, related to #11813
=> graphviz: drop libglade dep

mingw-w64-spice-gtk/PKGBUILD, mingw-w64-virt-viewer/PKGBUILD
the libcacard deps don't build on arm64 yet. I disabled clangarm64 in 5d2b28e684d4d5, this lets us revert that.
=> spice-gtk: disable smartcard support for clangarm64

mingw-w64-openFPGALoader/PKGBUILD
openFPGALoader v0.9.0 was released: https://github.com/trabucayre/openFPGALoader/releases/tag/v0.9.0
/c @trabucayre
=> openFPGALoader: update to 0.9.0

mingw-w64-python-maturin/001-fix-default-target-on-mingw-32bit.patch, mingw-w64-python-maturin/PKGBUILD, mingw-w64-python-pywinpty/PKGBUILD, mingw-w64-python-terminado/PKGBUILD, mingw-w64-python-tornado/PKGBUILD
I disabled CLANG32 in `python-pywinpty` and `python-terminado` because of the unavailability of `rust`.
=> python-tornado: update to 6.2.0

mingw-w64-pdcurses/PKGBUILD
note: This was just done online with a quick check of the sh256 sum, hope that it builds well and assume the version is good...
The [ChangeLog](https://github.com/Bill-Gray/PDCursesMod/blob/master/docs/HISTORY.md#pdcursesmod-434---2022-july-29) looks definitely quite useful!
=> update PDCursesMod 4.3.4

mingw-w64-readline/0002-event-hook.patch, mingw-w64-readline/PKGBUILD
When using the GUI of Octave (with `octave --gui`), the `conhost.exe` and `octave-gui.exe` processes load one thread to full capacity whilst doing nothing. When I attach a profiler to `octave-gui.exe` in this state, the majority of the execution time is spent by repeatedly calling `kbhit`.
This can be avoided with the proposed patch for `readline`. IIUC, it replaces the call to `kbhit` with native Windows API calls. If `readline` is built with this patch, the processor load of `octave-gui.exe` and `conhost.exe` goes down to virtually 0 whilst doing nothing in Octave.
I'm not the original author of this patch. But it is used for the Windows installer package of Octave since many years (at least since late 2013). And we didn't notice any adverse effects of it. So, I'd guess it should be …
=> readline: use Windows API for event hook

mingw-w64-python-cmd2/PKGBUILD, mingw-w64-python-cx-freeze/PKGBUILD, mingw-w64-python-flask/PKGBUILD, mingw-w64-python-markdown/PKGBUILD, mingw-w64-python-path/PKGBUILD, mingw-w64-python-pytest/PKGBUILD, mingw-w64-python-sphinx/PKGBUILD, mingw-w64-python-versioningit/PKGBUILD
https://github.com/python-cmd2/cmd2/blob/2.4.2/setup.py#L47
https://github.com/marcelotduarte/cx_Freeze/blob/v6.11.1/setup.cfg#L45
https://github.com/pallets/flask/blob/2.1.3/setup.py#L11
https://github.com/Python-Markdown/markdown/blob/master/setup.py#L77
https://github.com/jaraco/path/blob/v16.4.0/setup.cfg#L23
https://github.com/pytest-dev/pytest/blob/7.1.2/setup.cfg#L52
https://github.com/sphinx-doc/sphinx/blob/v5.1.1/setup.py#L30
https://github.com/jwodder/versioningit/blob/v2.0.0/setup.cfg#L54
The only two packages that still depends on it are:
https://github.com/rst2pdf/rst2pdf/blob/0.99/setup.py#L32
https://github.com/jaraco/pytest-checkdocs/blob/v2.7.1/setup.cfg#L23
=> Drop python-importlib-metadata dependency from some python packages

mingw-w64-python-importlib-metadata/PKGBUILD
I can't do nothing about `cx-freeze` dependency on `setuptools<61`.
=> python-importlib-metadata: update to 4.12.0

mingw-w64-python-scipy/PKGBUILD
The meson build seems to be missing it, so work around it letting
setuptools handle it.
=> scipy: install egg-info

mingw-w64-python-scipy/PKGBUILD
this way we don't need setuptools
See https://github.com/msys2/MINGW-packages/pull/12386#issuecomment-1201661997
=> scipy: install .egg-info from the sdist

mingw-w64-unifdef/PKGBUILD
The `unifdef` utility selectively processes conditional C preprocessor `#if` and `#ifdef` directives. It removes from a file both the directives and the additional text that they delimit, while otherwise leaving the file alone.
=> Added unifdef

mingw-w64-python-scipy/002-no-long-double-64.patch, mingw-w64-python-scipy/PKGBUILD
According to https://github.com/msys2/MINGW-packages/issues/12409
this leads to errors/crashes.
It also isn't there in the setuptools build.
Fixes #12409
=> python-scipy: don't set long-double-64

mingw-w64-binutils/3001-Fix-a-conflict-between-the-linker-s-need-to-rename-s.patch, mingw-w64-binutils/PKGBUILD
This usually got triggered when linking meson subprojects.
https://sourceware.org/bugzilla/show_bug.cgi?id=29389
@lb90 it's not clear to me if this depends on other patches? git was happy to merge without conflicts at least.
=> binutils: backport fix for "local symbol `0' has no section" errors

mingw-w64-sqlite3/PKGBUILD
And enable stripping again. It's unclear why it was disabled 9 years ago.
=> sqlite: Update to 3.39.2

mingw-w64-bin2header/PKGBUILD
Release info: https://github.com/AntumDeluge/bin2header/releases/tag/v0.3.0
=> bin2header: update to 0.3.0

mingw-w64-libavif/PKGBUILD, mingw-w64-libyuv/PKGBUILD, mingw-w64-python-xpra/PKGBUILD
Also removed the bogus `nasm` dependency and bumped `libyuv` version (+ enabled for clangarm64)
=> libavif: depend on libyuv, svt-av1

mingw-w64-inkscape/PKGBUILD, mingw-w64-inkscape/inkscape-1.0.1-unbundle.patch
Inkscape links with system cairo package by default. But the bundled
cairo adds APIs which are not present in system one. This may cause
unexpected crashes.
=> inkscape: Disable internal cairo dependency

mingw-w64-gsm/0001-adapt-makefile-to.mingw.patch, mingw-w64-gsm/0003-fix-ln.mingw.patch, mingw-w64-gsm/PKGBUILD
drop yasm, doesn't seem to be used.
=> gsm: Update to 1.0.22

mingw-w64-libdeflate/PKGBUILD
Just realized the cdecl patch was already there, so need yet to rebuild dependent packages...
=> libdeflate: update to 1.13

mingw-w64-wxwidgets3.2/PKGBUILD
And, add depends wxwidgets3.2-common to wxwidgets3.2-msw-cb_headers.
=> wxwidgets3.2: Change base-libs to common-libs

mingw-w64-superlu/PKGBUILD
```
==> Starting check()...
Test project C:/Dev/MINGW-packages/mingw-w64-superlu/src/build-CLANGARM64-static
Start  1: s_test_9_2_0_LA
1/24 Test  #1: s_test_9_2_0_LA ..................   Passed    0.03 sec
Start  2: s_test_9_2_10000000_LA
2/24 Test  #2: s_test_9_2_10000000_LA ...........   Passed    0.04 sec
Start  3: s_test_19_2_0_LA
3/24 Test  #3: s_test_19_2_0_LA .................   Passed    0.03 sec
Start  4: s_test_19_2_10000000_LA
4/24 Test  #4: s_test_19_2_10000000_LA ..........   Passed    0.03 sec
Start  5: s_test_2_0_SP
5/24 Test  #5: s_test_2_0_SP ....................   Passed    0.03 sec
Start  6: s_test_2_10000000_SP
6/24 Test  #6: s_test_2_10000000_SP .............   Passed    0.03 sec
Start  7: d_test_9_2_0_LA
7/24 Test  #7: d_test_9_2_0_LA ..................   Passed …
```
=> superlu: Enable aarch64 builds

mingw-w64-sqlcipher/PKGBUILD
Updates source code baseline to upstream SQLite 3.39.2
=> sqlcipher: update to 4.5.2

mingw-w64-clang/0011-MinGW-Don-t-currently-set-visibility-hidden-when-bui.patch, mingw-w64-clang/0012-COFF-Emit-embedded-exclude-symbols-directives-for-hi.patch, mingw-w64-clang/0301-LLD-COFF-Add-support-for-a-new-mingw-specific-embedd.patch, mingw-w64-clang/0302-LLD-MinGW-Implement-the-exclude-symbols-option.patch, mingw-w64-clang/PKGBUILD
In preparation for enabling all targets in LLVM 15 this must be merged first.
Tested with multi stage bootstrap: built CLANG64 version of this PGBUILD, installed resulting packages, built this PKGBUILD again (so this step built LLVM with patched LLVM), installed resulting packages.
Then I rebuilt libc++, mlir and flang, they do not crash so seems good to go.
=> Backport patches to support symbol visibility

mingw-w64-bin2header/PKGBUILD
https://github.com/AntumDeluge/bin2header/releases/tag/v0.3.1
=> bin2header: update to 0.3.1

mingw-w64-gtk2/PKGBUILD
We want to provide this command via the gtk-update-icon-cache package
which is currently built via gtk3 (maybe gtk4 in the future), so remove it
in gtk2 to avoid conflicts.
Also remove the dependency on the gtk-update-icon-cache package, since
gtk2 doesn't install any icons, so no need to trigger the cache hook.
See #12527
=> gtk2: remove gtk-update-icon-cache

mingw-w64-gtk3/PKGBUILD, mingw-w64-gtk3/gtk-update-icon-cache.script.in
It's the name downstream projects expect.
Keep the versioned name for backwards compat still.
Fixes #12527
=> gtk3: provide a gtk-update-icon-cache.exe

.github/workflows/main.yml
instead of adding from scratch.
staging would have been fine because it was added to pacman.conf unconditionally, but the grep for clangarm64 was matching the commented-out section.  Add grep `-x` option to match whole line only (so won't match commented-out section), and use sed to remove leading `# ` from start of section to first blank line.
=> CI: uncomment clangarm64 and staging from pacman.conf

mingw-w64-github-cli/PKGBUILD
See https://github.com/cli/cli/releases/tag/v2.14.4
=> gh: upgrade to v2.14.4

mingw-w64-tzdata/PKGBUILD
install leap-seconds.list like Arch
=> tzdata: Update to 2022b

mingw-w64-ogre3d/015-export-symbols-samples-plugin.patch, mingw-w64-ogre3d/PKGBUILD
=> ogre3d: Fix samples plugin not exporting symbols to be loaded by SampleBrowser

mingw-w64-inkscape/PKGBUILD, mingw-w64-inkscape/fix-detecting-mingw-aarch64.patch
Requires #12529  
I had to manually create `libmscms.a` to be able to finish compiling so work is required in the `crt-git` package. This time, unlike the DirectX files, `mscms.dll` does exist in Windows on ARM. 
@lazka You may have to undelete that tweet soon 😊
=> inkscape: Add aarch64 support 🏁

mingw-w64-libpng/PKGBUILD
Fixes #12688 
I haven't bump the `pkgrel` because I haven't added any patch, enable any feature or change any functionality.
=> libpng: Fix building on CLANG environements

mingw-w64-gegl/PKGBUILD
@Biswa96 @Alexpux I'm not sure if ruby and/or openmp are still deps (see https://www.gegl.org/build.html). I was able to build in aarch64 without either and just disabling the dep on lua. 
Should we remove dep on openmp and ruby?
There's not mention of openmp nor ruby on the meson configuration output, even in x64 builds:
```
gegl 0.4.38
Directories
prefix          : /clang64
libdir          : lib
GEGL docs
Reference       : False
Docs            : False
Optional features
Build workshop  : False
Introspection   : True
Vala support    : True
Optional build utilities
asciidoc        : True
dot             : False
pygobject       : False
source-highlight: False
w3m             : False
Optional dependencies
avlibs          : True
Cairo           : True
GDKPixbuf       : True
gexiv2          : …
```
=> gegl: Support aarch64 build

mingw-w64-podman/PKGBUILD
some commands require it an it needs to be built separately
=> podman: include win-sshproxy

mingw-w64-qwt/001-release-build.patch, mingw-w64-qwt/004-pkgconfig-file.patch, mingw-w64-qwt/PKGBUILD
Issue reported in https://sourceforge.net/p/qwt/bugs/353
If someone wants debug files we could add two new split packages `qwt-qt5-debug` and `qwt-qt6-debug`
=> qwt: Fix PkgConfig files with Qt6 and Don't generate debug files.

mingw-w64-wxSVG/PKGBUILD
- updates wxSVG to be built against wxWidgets 3.2
- changes package name to `wxsvg-wx3.2`
There are conflicts between wxWidgets packages, so multiple wxSVG packages cannot be built from a single `PKGBUILD` script. See: #12559
**Edit:** Until the wxWidgets version conflicts can be fixed, wxSVG can only be built against one version, or there would have to be unique `PKGBUILD` scripts for each version. See: [wxsvg_multi_pkgbuild](https://github.com/AntumDeluge/MINGW-packages/tree/wxsvg_multi_pkgbuild)
=> Build wxSVG against wxWidgets 3.2

mingw-w64-python-numba/PKGBUILD, mingw-w64-python-numba/setup.patch
numba 0.56.0 requires llvmlite>=0.39 which itself doesn't support any LLVM>11!
=> python-numba: update to 0.56.0

mingw-w64-rust/PKGBUILD
fixes https://github.com/msys2/MINGW-packages/issues/12569
=> rust: Add release description

mingw-w64-jasper/002-pkg-config-static.patch, mingw-w64-jasper/PKGBUILD
* Remove libheif from Requires.private field because it is not present as a dependency.
* Add prefix field to fix path relocation.
* Remove gcc_s from Libs.private because it is for gcc only.
=> jasper: Fix pkgconfig file

mingw-w64-libbotan/PKGBUILD
I just updated botan from 2.18.2 to 2.19.2 which was released on 2022-06-03
=> libbotan: Update to 2.19.2

mingw-w64-clang/0102-fix-emulated-tls.patch, mingw-w64-clang/PKGBUILD
See https://github.com/msys2/MINGW-packages/pull/12550#issuecomment-1228506687
and https://github.com/msys2/msys2-tests/pull/9
=> clang: Fix emulated TLS for libstdc++ envs

mingw-w64-vala/0010-fix-backslash-disaster.patch, mingw-w64-vala/PKGBUILD
Temporarily fix the backslash disaster until vala merges the patch and releases the next version.
See also:
[related issue](https://gitlab.gnome.org/GNOME/vala/-/issues/1353)
[related PR](https://gitlab.gnome.org/GNOME/vala/-/merge_requests/254)
=> Vala: fix backslash disaster

mingw-w64-opencv/PKGBUILD
vtk gained lots of new deps which aren't built yet there,
so let's disable it for now.
=> opencv: temporarily drop vtk support on aarch64

mingw-w64-github-cli/PKGBUILD
See https://github.com/cli/cli/releases/tag/v2.14.7 for details.
=> gh: update to v2.14.7

mingw-w64-darktable/003-disable-gamepad.patch, mingw-w64-darktable/PKGBUILD
Disable gamepad for now.
Fixes #12874
=> darktable: Fix building with the latest updates

mingw-w64-vulkan-loader/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/2673
=> vulkan-loader: Workaround dll name by copying to vulkan-1.dll

mingw-w64-openblas/PKGBUILD
See also: https://github.com/xianyi/OpenBLAS/issues/3740
Fixes #12857
=> openblas: Use less aggressive optimization with GCC-12.

mingw-w64-glib2/0004-disable-explicit-ms-bitfields.patch, mingw-w64-glib2/PKGBUILD
As noted here: https://github.com/msys2/MINGW-packages/pull/12776#issuecomment-1231211803
It seems this flag is not needed as it has been the default for many versions now. As such the patch in Transmission can be rendered unnecessary.
=> glib2: disable explicit `-mms-bitfields` in pkgconfig cflags

mingw-w64-opencv/PKGBUILD
In a cleaner msys2 installation, with `mingw-w64-x86_64-python-opencv 4.6.0-3` installed.
Run:
`python -c "import cv2"`
I get:
ImportError: DLL load failed while importing cv2: N▒o foi poss▒vel encontrar o m▒dulo especificado
After installing qt-base and vtk it works!
=> opencv: python bindings depends on qt5-base and vtk

mingw-w64-openblas/PKGBUILD
Use patch from upstream to limit the scope of `no-tree-vectorize` optimization to only the files that seem to be affected by the optimization issue in gcc-12 reported in #12857.
=> openblas: limit scope of `no-tree-vectorize` optimization

mingw-w64-s2geometry/0003-s2geometry-0.10.0-python-point-named-component.patch, mingw-w64-s2geometry/PKGBUILD
Upstream patch from https://github.com/google/s2geometry/pull/268
=> python-pywraps2: Named component accessors for S2Point

mingw-w64-openimagedenoise/002-Fix-building-with-TBB-2021.patch, mingw-w64-openimagedenoise/003-use-the-same-_cpuid-as-msvc.patch, mingw-w64-openimagedenoise/PKGBUILD
This is the latest package depending on `intel-tbb`
=> openimagedenoise: Fix building against TBB 2021

mingw-w64-qt6-imageformats/001-disable-finding-webp-from-cmake-config-files.patch, mingw-w64-qt6-imageformats/PKGBUILD
Fails!
Reverting #12598 makes it succeed.
=> qt6-imageformats: update to 6.3.2

mingw-w64-qt-creator/PKGBUILD
Updating to 8.0 since that made backporting easier
=> qt-creator: Update to 8.0 and backport llvm 15 and mingw-w64 build fixes

mingw-w64-mlir/0001-do-not-link-to-llvm-dylib.patch, mingw-w64-mlir/0002-Use-hidden-visibility-when-building-for-MinGW-with-Clang.patch, mingw-w64-mlir/PKGBUILD
MINGW64:
```
[1397/1397] Linking CXX shared library bin\libMLIR.dll
FAILED: bin/libMLIR.dll tools/mlir-shlib/libMLIR.dll.a 
cmd.exe /C "cd . && D:\M\msys64\mingw64\bin\clang++.exe -march=x86-64 -mtune=generic -O2 -pipe -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -ffunction-sections -fdata-sections -Werror=mismatched-tags -O3 -DNDEBUG  -pipe   -Wl,--gc-sections -shared -o bin\libMLIR.dll -Wl,--out-implib,tools\mlir-shlib\libMLIR.dll.a -Wl,--major-image-version,0,--minor-image-version,0 …
```
=> mlir: update to 15.0.0

mingw-w64-libc++/PKGBUILD
The header file `cxxabi.h` were moved from `libc++` to `libc++abi` which made many packages failed to build.
@mati865
=> libc++: merge libc++abi in libc++

mingw-w64-clang/0010-fix-system-libs-zstd.patch, mingw-w64-clang/PKGBUILD
For some reason it added an absolute path there instead of the library. Fix it with my limited cmake knowledge..
Fixes #13108
=> llvm: fix system libs for llvm-config

mingw-w64-python-cryptography/001-disable-abi3.patch, mingw-w64-python-cryptography/PKGBUILD
Fails to build on CLANG64, a similar issue occured before with GNU ld https://github.com/retep998/winapi-rs/issues/539, but I don't know/understand how It was solved.
I have encountered the same issue when updating starship.
@mati865
=> python-cryptography: update to 38.0.1

mingw-w64-extra-cmake-modules/PKGBUILD
Removed two years ago https://invent.kde.org/frameworks/extra-cmake-modules/-/merge_requests/7
=> ecm: remove dependency on png2ico

mingw-w64-dosbox/PKGBUILD, mingw-w64-iir/PKGBUILD
On GCC base environments the install size has increased a lot (3X~4X):
```diff
-Download Size   : 1292.46 KiB
-Installed Size  : 4271.22 KiB
-Packager        : CI (msys2/msys2-autobuild/3e28396a/1716885985)
-Build Date      : Wed, Jan 19, 2022  9:20:30 AM
-Validated By    : MD5 Sum  SHA-256 Sum  Signature
+Compressed Size : 1604.82 KiB
+Installed Size  : 154406.62 KiB
```
=> dosbox: update to 0.79.0

mingw-w64-libc++/PKGBUILD, mingw-w64-lldb/PKGBUILD, mingw-w64-openmp/PKGBUILD, mingw-w64-polly/PKGBUILD
This updates:
* libc++
* lldb
* openmp
* polly
Remaining are:
* libclc (still on 14.x so may need more effort)
* mlir (takes a while so better as its own pull request)
* flang (takes a while so better as its own pull request, after mlir)
=> update llvm packages to 15.0.1

mingw-w64-flang/PKGBUILD
Looks like CLANG64 still fails in CI, so will probably require manual building.  Might need to wait for @lazka before merging to avoid breakage in the queue.
=> flang: update to 15.0.1

.github/workflows/main.yml
Recently GHA started defining VCPKG_ROOT environment variable (https://github.com/actions/runner-images/pull/6192).
So unset it to not let it autodetected and interfere with our build jobs.
=> CI: unset VCPKG_ROOT

mingw-w64-imagemagick/001-7.0.4.1-relocate.patch, mingw-w64-imagemagick/PKGBUILD
* Use unix-like directory separator to prevent escaping character.
* Relocate paths with respect to DLL instead of calling executable. This helps to run executable from any directory.
Fixes https://github.com/msys2/MINGW-packages/issues/3444 @kmilos
=> imagemagick: Fix path relocation

mingw-w64-gcc/PKGBUILD
but still provide the .DLL.
In combination with #13405 this will make all rebuilds link the libssp stuff against the crt while keeping existing packages already linking against the .DLL working until we rebuild them.
This is an alternative to #13410
=> gcc: remove libssp static and import lib

mingw-w64-vlc/PKGBUILD
It was provided through libdsm
=> vlc: remove implicit dependency on libssp

mingw-w64-libgpg-error/PKGBUILD
This updates libgpg-error to 1.46.
=> libgpg-error: update to 1.46

mingw-w64-ninja/PKGBUILD, mingw-w64-qemu/PKGBUILD
Fails at packaging:
```
==> Starting package_mingw-w64-clang-x86_64-qemu()...
ninja: error: FindFirstFileExA(D:/M/msys64/clang64/bin/sphinx-build.EXE): The directory name is invalid.
make: *** [Makefile:162: run-ninja] Error 1
==> ERROR: A failure occurred in package_mingw-w64-clang-x86_64-qemu().
```
=> qemu: remove dependency on libssp

mingw-w64-crt-git/PKGBUILD
Up until now a full upgrade would result in libssp being updated to a version that only has the DLLs left, but the packages got removed from the repo now, so users upgrading after the removal will get a conflict with the now no-longer-in-the-repo package.
Replace/conflict with it so it gets automatically uninstalled on a system upgrade.
Fixes #13534
=> crt: replaces/conflicts libssp

mingw-w64-libgpg-error/PKGBUILD
This is required for old packages like libbdplus.
Fixes https://github.com/msys2/MINGW-packages/issues/13539
=> libgpg-error: Install gpg-error-config script explicitly

mingw-w64-waf/PKGBUILD
Currently, when running mingw64/waf on a default install, waf will use the default C and C++ compilers for the win32 platform configured in waf, which are [msvc, gcc, clang] and [msvc, g++, clang++].
This means that waf tries to use msvc first when compiling waf projects. This is not what the user want: instead, it should use the appropriate MinGW system compiler, eg gcc on mingw64.
This currently requires the user to work around the issue by systematically adding --check-c-compiler to point waf to the appropriate compiler depending on the MinGW system, eg gcc on mingw64.
This patch fixes the issue by changing the default C and C++ compiler order in waf, to move the corresponding MinGW compiler to the head of the list. For example, on the mingw32 and mingw64 architectures, gcc should be …
=> waf: default compilers to the corresponding package MinGW system

mingw-w64-libc++/PKGBUILD, mingw-w64-lldb/PKGBUILD, mingw-w64-mlir/PKGBUILD, mingw-w64-openmp/PKGBUILD, mingw-w64-polly/PKGBUILD
(except for flang, which takes too long).
We'll see if including mlir in this PR is too much for CI or not...
=> update llvm packages to 15.0.3

mingw-w64-openblas/PKGBUILD
this should no longer be required since #13666
=> openblas: remove -Os workaround for aarch64

mingw-w64-fftw/PKGBUILD
The cmake config files installed with the current release of the `fftw` package contain hardcoded paths to the staging directory:
```
set_property(TARGET FFTW3::fftw3 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(FFTW3::fftw3 PROPERTIES
IMPORTED_IMPLIB_RELEASE "C:/M/mingw-w64-fftw/src/build-MINGW64-double/libfftw3.dll.a"
IMPORTED_LOCATION_RELEASE "C:/M/mingw-w64-fftw/src/build-MINGW64-double/libfftw3.dll"
)
```
The result is that attempting to use this package in a CMakeLists file,
```
find_package(FFTW3 REQUIRED)
target_link_libraries(myproject_exe PRIVATE FFTW3::fftw3)
```
results in an error
```
*** No rule to make target 'C:/M/mingw-w64-fftw/src/build-MINGW64-double/libfftw3.dll.a', needed by 'room.exe'.  Stop.
```
There are sed scripts in our PKGBUILD that …
=> fftw: fix editing of cmake config files

mingw-w64-flac/PKGBUILD
https://xiph.org/flac/changelog.html
* No longer depends on nasm
* stack protector works now, so stop disabling it
=> flac: Update to 1.4.2

mingw-w64-mcfgthread/PKGBUILD
Recently, `-D_FORTIFY_SOURCE=2` has been added into the default CFLAGS. As thislibrary has to be built before the CRT, where those overflow checking routines have not been available, it is necessary to build without default flags.
=> mcfgthread: Add `!buildflags` in options

mingw-w64-gspell/PKGBUILD
gspell has changed several releases ago its iso-codes dependency to use icu instead.
=> gspell: remove no longer used iso-codes dependency

mingw-w64-highlight/001-fix-installation-prefix-and-destdir.patch, mingw-w64-highlight/002-fix-data-dir-stat.patch, mingw-w64-highlight/PKGBUILD
Didn't use the [latest (stable) version 4.2](https://gitlab.com/saalen/highlight/-/releases)'s `.zip`; went for commit SHA instead since no releases were made since [my upstream MinGW patches](https://gitlab.com/saalen/highlight/-/merge_requests/136).
=> [new-package] highlight 4.3

mingw-w64-unixodbc/PKGBUILD
Query the locale charset (also on Windows) instead of hardcoding the used encoding to GB18030 (see #12892).
The patch is heavily "inspired" by the localcharset module of gnulib.
Edit: For a motivation for these changes, please see the comments here: https://github.com/msys2/MINGW-packages/pull/12892#discussion_r961312024
=> unixodbc: get locale charset

.github/workflows/main.yml
It defaults to 1.8GB, bump it a bit so we can build
flang under clang64 which otherwise hits OOM
Use C: since we have 95GB free there and only 12GB on D:
=> CI: test building with a larger pagefile

mingw-w64-igraph/PKGBUILD
now that openblas is built with openmp support it should no longer be broken, see
https://github.com/msys2/MINGW-packages/pull/13267#issuecomment-1295254523
=> igraph: enable openmp support for mingw32 again

mingw-w64-gcc/PKGBUILD
Also provides a virtual package for Fortran Compiler "fc".
I have chosen `omp` because `openmp` is already the name of LLVM OpenMP.
Should we create a separate package `libgomp` or leave it as it is and make `gcc-libs` provides `omp`.
=> Create a virtual package for OpenMP - Part1

mingw-w64-flang/PKGBUILD
I have also copied flang-new to flang so It could be detected by CMake without setting `FC` env or `CMAKE_Fortran_COMPILER`.
=> Create a virtual package for Fortran Compiler.

mingw-w64-verilator/PKGBUILD
Verilator 5 was released: https://github.com/verilator/verilator-announce/issues/57
=> verilator: update to 5.002

mingw-w64-make/PKGBUILD, mingw-w64-make/make-4.3_undef-HAVE_STRUCT_DIRENT_D_TYPE.patch, mingw-w64-make/make-4.4-timestamps.patch
Fixes a critical regression between 4.3 and 4.4.
=> make[critical]: Fix bad timestamps on mingw32

mingw-w64-gcc/PKGBUILD
=> gcc: disable stack protector to unbreak libssp

mingw-w64-7zip/PKGBUILD
MSYS2 does offer the `p7zip` package. But it is an MSYS package (and therefore the executable is slower than it needs to be), and besides, the p7zip project seems to be abandoned since 2016.
In the meantime, the 7-Zip project itself added support for building the command-line tool on Linux, and we can use that very same setup to build a MINGW version, too. So let's do that.
Note that there is only a `7z.exe`, no `7za.exe`. That's because the 7-Zip project never bothered with a shared library ;-)
=> Add the `mingw-w64-7zip` package

mingw-w64-7zip/PKGBUILD, mingw-w64-7zip/clang-arm-target-fixes.patch
Add a temporary patch to change ARM64 target attributes to a format clang understands (clang should support the GCC format as of version 16, see https://github.com/msys2/MINGW-packages/pull/13894#issuecomment-1304319971).
Add another `-Wno-error` option, rather than trying to patch out `force_align_arg_pointer` attribute for non-x86.
=> 7zip: fix clangarm64 build

mingw-w64-openmp/D137168.patch, mingw-w64-openmp/PKGBUILD
And try to enable for clangarm64 again.
There is a report of potential brokenness here:
https://reviews.llvm.org/D137168#3909400
so we should be careful building things with it.
#13818
=> openmp: backport arm64 build fixes

mingw-w64-libc++/PKGBUILD, mingw-w64-lldb/PKGBUILD, mingw-w64-mlir/PKGBUILD, mingw-w64-openmp/PKGBUILD, mingw-w64-polly/PKGBUILD
except for flang which generally needs to be done on its own.  also, libclc is still at 14.0.6
=> llvm packages: update to 15.0.4

mingw-w64-libclc/PKGBUILD
This package was out of sync with the other llvm-project packages.  This brings it back up to date, and makes the format of the PKGBUILD a little closer.
I don't use libclc, and don't have a way to know if it works or not... It builds (but with a lot of warnings!)
=> libclc: update to 15.0.4

mingw-w64-ncurses/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/13958
=> ncurses: Use predefined variables in pkgconfig files

mingw-w64-github-cli/PKGBUILD
See https://github.com/cli/cli/releases/tag/v2.20.0 for details.
=> gh: upgrade to 2.20.0

mingw-w64-opencolorio/0003-fix-python-sitearch.patch, mingw-w64-opencolorio/0004-use-system-minizip.patch, mingw-w64-opencolorio/0005-Fix-Findminizip-ng.patch, mingw-w64-opencolorio/PKGBUILD
Reported upstream: https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/1724
Also sorted out deps.
=> ocio: fix python module install path

mingw-w64-openmp/PKGBUILD
We want "omp" to point to the "default openmp" package, but currently both gcc-libs and openmp provide it there.
=> openmp: provide "omp" only in clang envs

mingw-w64-libimagequant/PKGBUILD, mingw-w64-librsvg/PKGBUILD, mingw-w64-python-bcrypt/PKGBUILD, mingw-w64-python-cryptography/PKGBUILD, mingw-w64-python-pyopenssl/PKGBUILD
so users that have then installed get transferred to the new ones
=> Add conflicts/replaces for old non-rust clang32 packages

mingw-w64-python-lsp-server/0001-python-lsp-server-1.5.0-allow-newlest-depends.patch, mingw-w64-python-lsp-server/PKGBUILD
For example, version of the `autopep8` module currently is `2.0.0`.
=> python-lsp-server: Reallow newlest depends

mingw-w64-ffmpeg/PKGBUILD, mingw-w64-libavif/PKGBUILD, mingw-w64-libheif/PKGBUILD
Unfortunately, rav1e is still not available for clangarm64 because it makedepends on cargo-c, which has crates that it depends on that still depend on versions of other crates that don't yet support the new -gnullvm targets.
=> enable usage of rav1e for clang32 now that it's available

mingw-w64-gegl/PKGBUILD
just extract twice to work around the symlink issue
=> gegl: Update to 0.4.40

mingw-w64-iso-codes/PKGBUILD
* drop pgpkeys, there no longer is a signature file
* drop git makedep, we use a tarball
=> iso-codes: Update to 4.12.0

mingw-w64-readline/0002-event-hook.patch, mingw-w64-readline/0004-locale.patch, mingw-w64-readline/PKGBUILD
This fixes #14213 for me.
It looks like the issue was caused by part of the upstream patch 001. If I understand its intention correctly, the main goal is to have a valid fallback locale in case detecting it (with `setlocale`) fails. That should still be the case with the proposed change.
Also thank you to @lostbard for his hints in https://savannah.gnu.org/bugs/index.php?63400.
=> readline: Fix regression in patch 001

mingw-w64-mcfgthread/PKGBUILD
1. Attempting to join with the calling thread itself, which will always fail, no longer makes it non-joinable.
2. `_MCF_event_await_change()` now returns the current value of an event, which is a byte and is thus always non-negative, instead of zero. This is an ABI break if code checks for success by comparing the result with zero.
https://github.com/lhmouse/mcfgthread/releases/v1.3-ga.3
=> mcfgthread: Upgrade to v1.3-ga.3

mingw-w64-graphicsmagick/PKGBUILD
=> graphicsmagick: use omp metapackage, enable for clangarm64

mingw-w64-embree/PKGBUILD
Patches based on https://github.com/embree/embree/pull/412.
=> embree: enable clangarm64 support

mingw-w64-readline/0002-event-hook.patch, mingw-w64-readline/0004-locale.patch, mingw-w64-readline/PKGBUILD
Inputting non-ASCII characters doesn't work with the existing patches.
Use `ReadConsoleInputW` to get the Unicode codepoint of the entered key and convert it to the current ANSI codepage or to UTF-8 as appropriate.
Also, re-do handling of escape sequences.
This allows to enter non-ASCII characters at the CLI or in the GUI of Octave for me.
=> readline: Fix inputting non-ASCII characters.

mingw-w64-sse2neon/PKGBUILD
This is a SSE to NEON translation library, therefore clangarm64 only.
Needed by blender.
=> sse2neon: add package

mingw-w64-readline/0004-locale.patch, mingw-w64-readline/PKGBUILD
Like @lazka rightfully pointed out in msys2/MSYS2-packages/#3338, the POSIX locale variables (like `LC_CTYPE`) might not be set when the shell startup script from MSYS2 isn't used.
To determine whether readline should be using an UTF-8 locale, it is probably better to query the console codepage instead of using the return value of `setlocale (LC_CTYPE, (char *)NULL);` on Windows. The proposed PR is doing that.
With this change (and PR #14405), it is possible to enter non-ASCII characters at the Octave prompt also when starting the program with a double-click on `octave.exe` in `mingw64/bin` (i.e., when the shell startup script didn't run).
Sorry, this took a couple of attempts. But I hope we are getting there now.
=> readline: Support entering non-ASCII characters also with other shells

mingw-w64-octave/0001-console-codepage.patch, mingw-w64-octave/PKGBUILD
Unfortunately, I messed up the upstream commit. So, we need a slightly different change.
See also: msys2/MSYS2-packages#3338
=> octave: change console codepage to UTF-8

mingw-w64-kcompletion-qt5/PKGBUILD, mingw-w64-kdewebkit-qt5/PKGBUILD, mingw-w64-kiconthemes-qt5/PKGBUILD, mingw-w64-kitemviews-qt5/PKGBUILD, mingw-w64-kplotting-qt5/PKGBUILD, mingw-w64-ktextwidgets-qt5/PKGBUILD, mingw-w64-kwidgetsaddons-qt5/PKGBUILD, mingw-w64-kxmlgui-qt5/PKGBUILD
This install plugin directory in prefix/share/qt5/plugins instead of
prefix/lib/plugins. The prefix/share/qt5/plugins path is returned from
'qtpath --plugin-dir' command.
Fixes https://github.com/msys2/MINGW-packages/issues/10158
Similar as https://github.com/msys2/MINGW-packages/pull/4523
=> KF5: Fix plugin directory using template function

mingw-w64-readline/0002-event-hook.patch, mingw-w64-readline/PKGBUILD
Fixes #14484 for me.
Tested with Octave CLI, GUI, and with gdb.
=> readline: Fix escape sequence handling in callback mode.

mingw-w64-gnucobol/PKGBUILD
run the NIST85 tests ... currently only works if msys perl is first in PATH (fix from GC 3.2)
as this is only about the check definition and GC 3.2 is "in sight" a pull may not be necessary now
=>  GnuCOBOL package update

mingw-w64-suitesparse/PKGBUILD
Use upstream patch to fix linking the SPEX library with gcc.
Also, remove the Fortran compiler as a build dependency.
Remove `metis` from dependencies.
Remove unnecessary `cmake` flags.
=> suitesparse: build SPEX with GCC

mingw-w64-bscan-spi-bitstreams/PKGBUILD
JTAG-SPI proxy bitstreams to be used with the OpenOCD jtagspi flash driver
=> New package: bscan-spi-bitstreams

.github/ISSUE_TEMPLATE/bug_report.yml
There are two main changes:
* Description and reproduction steps are merged at the top, so users don't descripe the bug and then later on have to fill out the steps again, possibly writing the same things twice slightly differently. This flow feels more natural imo.
* Recomend "uname" instead of "cmd.exe /c ver", the later is tricky because of path conversion of "/c", and uname has the same info basically.
Preview: https://github.com/msys2/MINGW-packages/blob/752ef871dd33074c33257a5e37ac02b5e7a2b010/.github/ISSUE_TEMPLATE/bug_report.yml
=> bug_report template: try to simplify it a bit

mingw-w64-mcfgthread/PKGBUILD
1. Use `build-${MSYSTEM}` as build directories, like other packages.
2. Remove the useless `--target` for `configure`.
3. Add C++ tests.
For the record: Some i686 test programs on my Windows 10 machine fail because the result of `QueryPerformanceCounter()` occasionally goes backwards. It is of course unexpected but I don't know whether it's a Windows bug or normal behavior. All the x86_64 tests pass without such issues.
=> mcfgthread: Update to 1.4-ga.1

mingw-w64-curl/PKGBUILD
drop patch included upstream
remove old keys
=> curl: Update to 7.87.0

mingw-w64-octave/PKGBUILD, mingw-w64-suitesparse5/0001-mingw-w64-Use-a-not-lib-as-AR_TARGET-extension.patch, mingw-w64-suitesparse5/0002-mingw-w64-Set-SO_OPTS--shared-move-dlls-create-import-libs.patch, mingw-w64-suitesparse5/0003-mingw-w64-no-CUDA.patch, mingw-w64-suitesparse5/0004-mingw-w64-install-static-libs.patch, mingw-w64-suitesparse5/0005-suitesparse-5.8.1-skip-building-Mongoose-GraphBLAS.patch, mingw-w64-suitesparse5/0006-suitesparse-5.8.1-fix-mp-link-order.patch, mingw-w64-suitesparse5/PKGBUILD
This addresses #14658.
Most of the libraries in SuiteSparse have an API that can be categorized into two groups: One narrow indexing API and one wide indexing API. In version 5 and version 6, the narrow indexing API uses 32-bit integers. In version 5, the wide indexing API used 64-bit integers on 64-bit platforms and 32-bit integers on 32-bit platforms. In version 6, the wide indexing API uses 64-bit independent of the platform. That cannot work for 32-bit platforms. Indices must not be larger than `sizeof(void *)`. That means half of the API is broken on 32-bit platforms for those libraries.
Some libraries (e.g., SPQR) have only the wide indexing API. That means, they are completely broken on 32-bit platforms.
This PR adds a package that is basically the version of SuiteSparse as it was …
=> Add package for SuiteSparse 5

mingw-w64-ceres-solver/PKGBUILD, mingw-w64-python-cvxopt/PKGBUILD
Rebuild the packages with `suitesparse5` on 32-bit that (probably) use the broken API of `suitesparse`.
That leaves the other dependers of `suitesparse` that should probably also be rebuilt with `suitesparse5` on 32-bit to allow installing them in parallel with the packages that require `suitesparse5`.
See also the discussion in #14663.
=> ceres-solver, python-cvxopt: rebuild with suitesparse5 on 32-bit

mingw-w64-suitesparse/PKGBUILD
Large parts of the API of the libraries in SuiteSparse 6.x are broken on 32-bit.
We are building SuiteSparse 5 for 32-bit now. So, stop distributing the (broken) version for those targets.
This assumes that dependers on MINGW32 or CLANG32 will pick up `suitesparse5` (which also provides `suitesparse`). I'm not sure of this will actually be the case.
=> suitesparse: stop building for 32-bit

mingw-w64-gr/PKGBUILD
got errors like this:
```
[220/222] Building CXX object CMakeFiles/grplot.dir/lib/grm/grplot/util.cxx.obj
FAILED: CMakeFiles/grplot.dir/lib/grm/grplot/util.cxx.obj 
D:\M\msys64\clang64\bin\clang++.exe -DGR_STATIC_LIB -DHAVE_ZLIB -DMINGW_HAS_SECURE_API=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NEEDS_QMAIN -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DUNICODE -DWIN32 -DWIN64 -DWINVER=0x0A00 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_WIN32_WINNT=0x0A00 -D_WIN64 -IC:/_/mingw-w64-gr/src/build-CLANG64/grplot_autogen/include -IC:/_/mingw-w64-gr/src/gr-0.71.2/lib/grm/include -IC:/_/mingw-w64-gr/src/gr-0.71.2/lib/grm/src -IC:/_/mingw-w64-gr/src/gr-0.71.2/lib/gks -IC:/_/mingw-w64-gr/src/gr-0.71.2/lib/gr -IC:/_/mingw-w64-gr/src/gr-0.71.2/lib/gr3 -isystem D:/M/msys64/clang64/include/qt6/QtWidgets -isystem …
```
=> gr: update to 0.71.2

mingw-w64-gmp/PKGBUILD, mingw-w64-mpc/PKGBUILD, mingw-w64-mpfr/PKGBUILD
This is my last attempt to build shared libraries for mpfr and mpc.
I have proposed this change before but @jeremyd2019 said that we shloud keep gmp as it is and the issue comes from mpfr and mpc being too strict, but It turns out It wasn't the case and he was wrong about that.
I think building shared libraries should be prioritized over static ones, If there is a conflict. So if someone wants static mpfr and mpc then he should find the solution.
=> Favor shared over static for gmp to build shared for mpfr and mpc

mingw-w64-libc++/PKGBUILD
This leads to libc++ looking up GetSystemTimePreciseAsFileTime at runtime and continue working on Win7.
While we don't want to support win7 anymore, it's better to phase it out slowly and not right away at the toolchain libs level.
See https://github.com/msys2/MINGW-packages/pull/14452#issuecomment-1354606536
=> libc++: set _WIN32_WINNT to win7

mingw-w64-rust/0007-clang-subsystem.patch, mingw-w64-rust/0009-build-gnullvm-targets-natively.patch, mingw-w64-rust/0010-gnullvm-debuginfo-fix.patch, mingw-w64-rust/0011-disable-uac-for-installer.patch, mingw-w64-rust/0012-disable-miri.patch, mingw-w64-rust/PKGBUILD
The bash array _rust_conf was being used as a 'scalar' (for lack of a
better term), resulting in only the first item being interpolated,
losing the `--enable-vendor` option necessary for a -gnullvm target to
build due to necessary patches to the vendored sources.  Currently, only
clangarm64 uses a gnullvm target, so it was the only one affected.
Addresses https://github.com/msys2/MINGW-packages/pull/14592#issuecomment-1363332277
=> rust: fix clangarm64 build

mingw-w64-tcllib/PKGBUILD
Github mirror's hash changed, so updated package to use the same mirror as upstream (Arch) which has hash matching https://core.tcl-lang.org/tcllib/uv/tcllib-1.21.SHA256
=> tcllib: Add clangarm64 and update source archive

mingw-w64-octave/PKGBUILD
Revert back to forcing a downgrade to SuiteSparse 5. Octave uses parts of the API that are broken on 32-bit SuiteSparse 6.
=> octave: force downgrade to SuiteSparse 5 for 32-bit

mingw-w64-mesa/PKGBUILD
- Disable GLES and EGL as MSYS2 provides angleproject (#14803), a far superior implementation;
- Disable shared glapi as it's not needed without GLES and EGL;
- Stop building unit tests since they aren't packaged.
=>  mesa: Update to 22.3.2

mingw-w64-angleproject/PKGBUILD
This fixes part of #14803 by not packaging the OpenCL headers.
It's not clear at the moment how to resolve the conflict with the GLES and EGL libraries and headers from the mesa package. So, I just made the current conflict explicit.
It might be possible to remove that conflict again if it can be resolved somehow.
=> angleproject: don't package OpenCL headers

mingw-w64-mesa/PKGBUILD
Doing so asks for more package conflict trouble
=> mesa: Don't install DirectX Headers

mingw-w64-cargo-c/001-add-lib-prefix-on-windows-gnu.patch, mingw-w64-cargo-c/002-accept-windows-gnu-aarch64.patch, mingw-w64-cargo-c/PKGBUILD, mingw-w64-libimagequant/PKGBUILD, mingw-w64-rav1e/PKGBUILD
packages get bigger on GCC based env, It's not related to the patches because It's the same when rebuilding without any patch.
=> cargo-c: Enable aarch64 and add lib prefix to import library output name

mingw-w64-mkvtoolnix/PKGBUILD
I have disabled 32bit envs because I am going to drop 32bit from most of Qt6 packages.
=> mkvtoolnix: update to 73.0.0

mingw-w64-gspell/PKGBUILD
The gspell unit tests need to be installed in order to run successfully.
Otherwise they don't see the hunspell dictionaries (only the en_US one is required for the unit tests).
=> gspell: add --enable-installed-tests

mingw-w64-qt5-quickcontrols2/PKGBUILD
The only qt5 package that needs `MSYS2_ARG_CONV_EXCL='*'` to builds.
=> qt5-quickcontrols2: update to 5.15.8

mingw-w64-mlt/PKGBUILD, mingw-w64-shotcut/0001-fix-translation-on-msys2.patch, mingw-w64-shotcut/PKGBUILD
On Windows, shotcut loads translation files from the executable directory ($PREFIX/bin), also the translation files are not installed, and meant to be manually copied after build.
While MSYS2 uses a filesystem layout similar to *nix, with data files in $PREFIX/share.
So patch the initialization code to match.
=> Shotcut: fix translation, enable clang64 & clangarm64

mingw-w64-boost/PKGBUILD
Boost provides CMake configuration files. These files are the ultimate truth about how Boost libraries are to be compiled. It's better to rely on them, then on CMake provided FindBoost.cmake module. The latter can become stale, or it can contain bugs, which will make users dependent on the ability of CMake authors to fix it. Boost provided configuration files are always up-to-date and tested with the version we are installing.
=> Add back CMake configuration files

mingw-w64-tesseract-ocr/0001-check-msys2-tessdata-location.patch, mingw-w64-tesseract-ocr/PKGBUILD
Tesseract looks for `tessdata` in executable directory, but on msys2 data is located in `dirname(executable)/../share/tessdata` (`${MSYSTEM}/share/tessdata`), as a result if TESSDATA_PREFIX is not set appropirately, tesseract fails to perform ocr saying "Error opening data file".
This little patch simplifies using tesseract right out of msys2 tree.
=> check msys2 tessdata location

mingw-w64-libheif/PKGBUILD
Removed the pc file workaround, it's been dealt with upstream already.
=> libheif: update to 1.14.2

mingw-w64-readline/PKGBUILD
tells readline to use the PC variable from libtermcap instead of defining its own. This fixes the multiple definition error when attempting to statically link readline
Fixes https://github.com/msys2/MINGW-packages/issues/8105
I have not tested shared linking, but have tested with compiling mujs' master branch
=> readline: define NEED_EXTERN_PC for static linking

mingw-w64-rust/PKGBUILD
see https://blog.rust-lang.org/2023/01/10/cve-2022-46176.html
=> rust: update to 1.66.1

mingw-w64-boost/PKGBUILD, mingw-w64-boost/boost-1.81.0-honor-ICU_ICUxx_NAME-variables-in-remap-library.patch
The first attempt to add back CMake configuration files for boost failed because boost installer didn't honor ICU_ICUxx_NAME variables set in PKGBUILD. This commit reinstates CMake configuration files and incorporates a patch provided by Peter Dimov.
=> Add back boost CMake configuration files and fix #15021

mingw-w64-angleproject/001-add-mingw-toolchain.patch, mingw-w64-angleproject/003-angle-src-fixes.patch, mingw-w64-angleproject/PKGBUILD, mingw-w64-gn/004-add-arm64-arch.patch, mingw-w64-gn/PKGBUILD, mingw-w64-libepoxy/PKGBUILD
* Remove patch for adding D3D11_CLIP_OR_CULL_DISTANCE_COUNT symbol.
* Define ANGLE_PLATFORM_WINDOWS instead of _WIN32.
* Add arm64 target for mingw toolchain gn file.
* Use -msse3 flag for x86 and x86_64 only.
=> angle: Enable clangarm64

mingw-w64-gcc/0002-Relocate-libintl.patch, mingw-w64-gcc/0003-Windows-Follow-Posix-dir-exists-semantics-more-close.patch, mingw-w64-gcc/PKGBUILD
See https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=902c755930326cb4405672aa3ea13c35c653cbff
=> gcc: add workaround to fix build with newer mingw-w64

mingw-w64-openssl/002-relocation.patch, mingw-w64-openssl/PKGBUILD
openssl 3 added a new path from which DLLs can be loaded at runtime, currently the "legacy.dll".
This code path was missing the relocation support and looking for the CI build path instead, resulting in code that tried to load the legacy providers to fail (examples: python-cryptography, transmission)
It can also be reproduced via:
openssl list -provider legacy -providers
Add relocation support to MODULESDIR to fix this.
=> openssl: fix modulesdir relocation

mingw-w64-openocd/PKGBUILD
Since 0.12.0 no drivers in OpenOCD need libusb0 API, so remove the dependency.
=> openocd: remove libusb-compat dependency

mingw-w64-exiv2/PKGBUILD
some how qt6-static related to it, so it's better to have a static library
=> Add static library generation for libexiv2

mingw-w64-gi-docgen/PKGBUILD
Current version does not work and throws:
Fatal error in launcher: Unable to find an appended archive.
Fix this by disabling strip.
=> Disable stripping gi-docgen

.ci/ci-build.sh
this will shorten the build path by at least 10 letters `mingw-w64-`, for example for mingw-w64-qt6-static It will shorten path by 19 letters.
=> CI: shorten build path

mingw-w64-rocksdb/0001-disable-static-assert-ClockHandle-size.patch, mingw-w64-rocksdb/PKGBUILD
Fails to build on clang32 because It enables an SSE4.2 instruction unavailable on 32bit.
=> rocksdb: update to 7.9.2

mingw-w64-vigra/PKGBUILD
There seems to be an issue with python-nose during the configuration step of vigra that eventually leads to it being built without numpy:
```
-- Searching for Python numpy: ok
File "<string>", line 1, in <module>
File "C:/msys64/mingw64/lib/python3.10/site-packages/nose/__init__.py", line 1, in <module>
from nose.core import collector, main, run, run_exit, runmodule
File "C:/msys64/mingw64/lib/python3.10/site-packages/nose/core.py", line 11, in <module>
from nose.config import Config, all_config_files
File "C:/msys64/mingw64/lib/python3.10/site-packages/nose/config.py", line 68
except ConfigParser.Error, exc:
^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
-- Could NOT find Python nosetests ('import nose' failed)
[...] …
```
=> vigra: workaround for python-nose issue

mingw-w64-python-h5py/PKGBUILD
h5py has been updated to version 3.8.0, integrating some earlier patches:
https://github.com/h5py/h5py/releases/tag/3.8.0
xref: https://github.com/msys2/MINGW-packages/pull/15033
=> h5py: Update to version 3.8.0

mingw-w64-bcg729/PKGBUILD
Bcg729 is an opensource implementation of both encoder and decoder of the ITU G729 Annex A/B speech codec.
URL: https://github.com/BelledonneCommunications/bcg729
=> Add new package Bcg729

mingw-w64-glib2/0003-glib-spawn-win32.patch, mingw-w64-glib2/PKGBUILD
Backports the fix for https://gitlab.gnome.org/GNOME/glib/-/issues/2900
=> glib2: Fix g_spawn_*() in CLANG builds

mingw-w64-luajit/003-lua51-modules-paths.patch, mingw-w64-luajit/004-fix-default-cc.patch, mingw-w64-luajit/PKGBUILD
Since luajit is meant to be a drop-in replacement for lua5.1 it needs to support searching for modules in the same paths as lua5.1
Fixes https://github.com/msys2/MINGW-packages/issues/15245
```
luajit -e 'print(require("lgi")._VERSION)'
0.9.2
```
=> luajit: Fix cc and enhance modules search path with lua5.1 paths

mingw-w64-binutils/PKGBUILD, mingw-w64-binutils/bfd-real-fopen-handle-windows-nul.patch, mingw-w64-binutils/libiberty-unlink-handle-windows-nul.patch
`S_ISREG` doesn't work correctly for Windows nul device.
No need to add `\\.\` prefix twice when accessing Windows nul device.
This fixes https://github.com/msys2/MINGW-packages/issues/14725
I'm not a C programmer and not that familiar with msys2 ecosystem. Please let me know if I missed something.
=> binutils-handle-windows-nul

mingw-w64-wireshark/PKGBUILD
Once Wireshark 4.2 is released (probably around october) the package can be changed to follow the stable branch.
=> wireshark: Add package

mingw-w64-mpg123/PKGBUILD
and remove libtool files, as I doubt anything still needs them
=> mpg123: Update to 1.31.2

mingw-w64-qrupdate/PKGBUILD
Arch Linux also transitioned from the "classic" qrupdate (which is currently unmaintained) to qrupdate-ng:
https://github.com/archlinux/svntogit-community/blob/packages/qrupdate/trunk/PKGBUILD
The upstream build system changed from a Makefile to cmake rules. So, also update the build rules accordingly.
It currently doesn't build with LLVM Flang (because of missing _imag and some other math functions). But I hope the current build rules will allow to easily add `clang64` to the `mingw_arch`s in case it will compile with LLVM Flang 16 (or a later version).
Octave's test suite still passes with the updated package.
=> qrupdate: update to 1.1.5

mingw-w64-openssl/001-support-aarch64.patch, mingw-w64-openssl/003-backport-win-arm64-asm-support.patch, mingw-w64-openssl/PKGBUILD
Based on https://github.com/openssl/openssl/commit/b863e1e4c69068e4166bdfbbf9f04bb07991dd40, which seems to have been cherry-picked to the openssl-3.1 branch but not 3.0.
The armcap.c change did not apply cleanly to 3.0 (apparently it was not yet including `unistd.h`), so I updated that hunk of the patch.
```diff
diff -u b863e1e4c69068e4166bdfbbf9f04bb07991dd40.patch 003-backport-win-arm64-asm-support.patch
--- b863e1e4c69068e4166bdfbbf9f04bb07991dd40.patch      2023-01-30 17:30:30.269591000 -0800
+++ 003-backport-win-arm64-asm-support.patch    2023-01-30 17:12:24.855600100 -0800
@@ -72,23 +72,19 @@
move /Y \$@.i \$@
EOF
} elsif ($gen0 =~ m|^.*\.in$|) {
-diff --git a/crypto/armcap.c b/crypto/armcap.c
-index 0aa11baed4b9..a43f17304b02 100644
---- a/crypto/armcap.c
-+++ b/crypto/armcap.c …
```
=> openssl: backport ASM support for Windows on ARM64.

mingw-w64-tiled/0001-tiled-1.9.2-windows-layout.patch, mingw-w64-tiled/PKGBUILD
With [Tiled](https://www.mapeditor.org/) we can make and edit levels, that can be read by [pytmx](https://packages.msys2.org/base/mingw-w64-python-pytmx) and rendered by [pygame](https://packages.msys2.org/base/mingw-w64-python-pygame).
And looks like it's will be first package in distro that use [qbs](https://packages.msys2.org/base/mingw-w64-qbs) for make.
=> tiled: New package

mingw-w64-netcdf/PKGBUILD
The BYTERANGE feature is enabled by default in netCDF 4.9.1. It was disabled by default in version 4.9.0.
That feature doesn't compile with HDF5 1.14. (It uses parts of the API that changed between version 1.12 and 1.14, and hasn't been updated for the newer API yet.)
Disabling it now doesn't mean that we no longer build a feature that we had before. (We never built it afaict.) But it allows building the remainder of the new version.
=> netcdf: update to 4.9.1

mingw-w64-vala/PKGBUILD
This minor version has some specific fix for windows platform, [see also the vala's release note](https://gitlab.gnome.org/GNOME/vala/-/commit/fbf513c52806e253b3dde68f477e1eca8ac38cd1).
=> Vala: update to v0.56.4

mingw-w64-gmp/PKGBUILD, mingw-w64-gmp/do-not-use-dllimport.diff
GNU toolchains do not require `dllimport` when calling functions from DLLs. Having `dllimport` by default causes static linking to fail, observed when building GDB.
Signed-off-by: LIU Hao <lh_mouse@126.com>
(cherry picked from commit 91d231a51056c2c429e55ae1546794b93089bb64)
Signed-off-by: LIU Hao <lh_mouse@126.com>
=> gmp: Do not declare functions as `dllimport`

mingw-w64-x264/PKGBUILD
the latter depends on ffmpeg, ffms2 and l-smash which users of
the library don't need. This also allows us break some
dependency cyles with ffmpeg.
* remove the libwinpthread dependency which it doesn't
seem to use anymore.
* note that x264.exe statically links the encoder, so there
is no dependency to libx264 needed, but we add it anyway,
to avoid breaking existing users.
=> x264: split into libx264 and x264

mingw-w64-kicad/PKGBUILD, mingw-w64-waf/0001-timeout-at-wait-after-kill.patch, mingw-w64-waf/PKGBUILD, mingw-w64-wxPython/301-Revert-some-of-python-sip-changes.patch, mingw-w64-wxPython/PKGBUILD
This PR updates the wxWidgets dependency of Kicad to version 3.2.
To avoid conflicts, wxPython also needs to depend on wxWidgets 3.2 for this to work. The alpha tarball from which wxPython was built the last time is no longer available. So, I updated to the latest stable release wxPython (Phoenix) 4.2.0.
IIUC, these are the last dependers on wxWidgets 3.1. Afaict, that was (only) a development version that we needed intermediately to build some package (Kicad?). @MehdiChinoune already moved all other dependent packages to wxWidgets 3.2 afaict. `wxWidgets3.1` can probably be removed if this PR is merged. (I can also remove it as part of this PR if you prefer.)
`waf` (that is used as a build tool for wxPython) has troubles calling the `wx-config` shell script when using a mingw Python. It …
=> kicad: depend on wxWidgets 3.2

mingw-w64-ffmpeg/PKGBUILD
* sync pkgdesc from Arch
* remove default options
* remove commented out parts
* rav1e is available for clangarm64 now
* libsrt headers now use _WIN32, so remove the workaround
* disable stripping, leave it to makepkg
* don't exit on build errors, and don't enable verbose mode
=> ffmpeg: cleanups

mingw-w64-kicad/001-support-subrelease-field-in-wxwidgets.patch, mingw-w64-kicad/PKGBUILD
The upstream patch doesn't apply directly because some folder names changed.
=> kicad: support subrelease field in wxWidgets version number

mingw-w64-libbs2b/PKGBUILD
Needed to run autoreconf for aarch64 to build.
=> [libbs2b] Add support for clangarm64

mingw-w64-gdb/PKGBUILD
The real executable is in gdb/.libs/gdb.exe, gdb/gdb.exe executes it. Install it properly and copy from the install target.
=> gdb: fix multiarch package

mingw-w64-spooles/PKGBUILD, mingw-w64-spooles/spooles-1.patch
spooles: enable clang, new patch file from archlinux added because error occurs (clang):
```
transform.c:294:23: error: incompatible pointer to integer conversion passing 'void *' to
parameter of type 'int' [-Wint-conversion]
temp = IVinit(nfront, NULL) ;
^~~~
```
Patch from: https://aur.archlinux.org/cgit/aur.git/tree/spooles-1.patch?h=spooles
=> spooles: add new patch, enable clang

mingw-w64-opencascade/PKGBUILD
occ takes a huge time to build unneeded static libraries.
Dependent packages (kicad, gmsh and OSG) don't need them.
=> opencascade: Build static libraries only on MINGW64

mingw-w64-ffmpeg4.4/0001-get_cabac_inline_x86-Dont-inline-if-32-bit-clang-on-windows.patch, mingw-w64-ffmpeg4.4/0002-gcc-12.patch, mingw-w64-ffmpeg4.4/0003-fix-clang32-build.patch, mingw-w64-ffmpeg4.4/PKGBUILD, mingw-w64-ffmpeg4.4/c6fdbe26ef30fff817581e5ed6e078d96111248a.patch
The goal of this package is to provide ffmpeg 4.4.x and not conflict with ffmpeg 5.x etc.
Compared to the current 4.4 package this removes the frei0r-plugins dependency, since there is a dep cycle via frei0r-plugins -> opencv
edit:
```
depends=("${MINGW_PACKAGE_PREFIX}-ffmpeg4.4")
export PKG_CONFIG_PATH="${MINGW_PREFIX}/lib/ffmpeg4.4/pkgconfig:$PKG_CONFIG_PATH"
```
=> Add ffmpeg4.4

mingw-w64-blender/0037-build-with-ffmpeg4.4.patch, mingw-w64-blender/PKGBUILD
=> blender: build with ffmpeg4.4

mingw-w64-OpenSceneGraph/PKGBUILD, mingw-w64-OpenSceneGraph/ffmpeg4.4.patch
=> openscenegraph: build with ffmpeg 4.4

mingw-w64-gr/0001-support-mingw-wcstok.patch, mingw-w64-gr/PKGBUILD
likely broken before, but
https://github.com/mingw-w64/mingw-w64/commit/40134887fb81f5be451b5c4c uncovered it, resulting in a build error.
=> gr: adjust for wcstok changes in mingw-w64

mingw-w64-qt6-base/012-fix-unicode-definitions-in-cmake-interface.patch, mingw-w64-qt6-base/PKGBUILD
Also fixes the CFLAGS in the generated `Qt6Platform.pc` file.
See #15801.
=> qt6-base: Fix UNICODE definitions in cmake interface.

mingw-w64-pastix/PKGBUILD
Due to a bug on clang the fortran interface has been disabled (only for clang).
Error description: https://gitlab.inria.fr/solverstack/pastix/-/issues/59
=> pastix: enable clang64

mingw-w64-lua53/LICENSE, mingw-w64-lua53/PKGBUILD, mingw-w64-lua53/implib.patch, mingw-w64-lua53/lua.pc, mingw-w64-lua53/searchpath.patch
For a cross operating system project we needed a Lua 5.3 package (older Ubuntus do not ship Lua 5.4 yet). I don't know what the policy on version specific packages is but I thought it might be useful to some people. If you don't want to integrate the package, I can just close the PR and leave it here for future users to find.
Inspiration taken from the `mingw-w64-lua` and `mingw-w64-lua51` packages.
=> add package for Lua5.3

mingw-w64-gdb/PKGBUILD
It uses artifacts from gdb package, so they must match.
=> gdb: change multiarch dependency to match gdb exact version

mingw-w64-unicorn/001-bindings-python.patch, mingw-w64-unicorn/PKGBUILD
```bash
$ python -c 'import unicorn'
File "<string>", line 1, in <module>
File "C:/msys64/mingw64/lib/python3.10/site-packages/unicorn/__init__.py", line 4, in <module>
from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError, __version_
_
File "C:/msys64/mingw64/lib/python3.10/site-packages/unicorn/unicorn.py", line 114, in <module>
raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
```
=> unicorn: Fix python bindings library

mingw-w64-ghdl/PKGBUILD
Some months went by since we last updated it: #13819.
=> ghdl: update to 2.0.0.r1392.g19babff18

mingw-w64-creduce/PKGBUILD
upstream no longer uses it since
https://github.com/csmith-project/creduce/pull/164
=> creduce: drop dependency on perl-Sys-CPU

mingw-w64-octave/PKGBUILD
This should make octave compute faster. waiting for some tests from @mmuetzel
=> octave: link against openblas instead of lapack

mingw-w64-qrupdate/PKGBUILD
We are building qrupdate with OpenBLAS. However, pkgconf returns the following for it:
```
$ pkgconf --libs qrupdate
-lqrupdate -L/mingw64/lib -lblas -llapack
```
IIUC, this could lead to overlinking when linking the shared library. And probably worse, it could lead to the situation where downstream projects are effectively linking to a mixture of reference BLAS/LAPACK and OpenBLAS.
With the changes from this PR, pkgconf returns the following:
```
$ pkgconf --libs qrupdate
-lqrupdate
$ pkgconf --libs --static qrupdate
-lqrupdate -fopenmp -lopenblas
```
=> qrupdate: Require OpenBLAS in pkg-config file

mingw-w64-python-docutils/PKGBUILD, mingw-w64-python-docutils/pyscript2exe.py
and port to build/installer while at it
motivated by virt-manager calling them without an interpreter
The next docutils will have a central .exe launcher and the old scripts
will be deprecated, so this should fix itself over time.
=> python-docutils: create .exe launchers for all scripts

mingw-w64-python-xpra/PKGBUILD
xpra needs `python-gobject` to start.
`gstreamer` and `python-pyopengl-accelerate` are added to optional dependencies because xpra warns about that.
=> python-xpra: update dependencies.

mingw-w64-ruby/0009-windows-arm64.patch, mingw-w64-ruby/PKGBUILD
This is #13115, but only the patch
=> ruby: add clangarm64 patch (still broken)

mingw-w64-libvirt/PKGBUILD
Docs are required for virt-manager, reported by @1480c1
=> libvirt: Enable docs with meson workaround

mingw-w64-i2pd/0001-i2pd-makefile.patch, mingw-w64-i2pd/PKGBUILD
Note: we have added cmake support, but there is no install target for the configs and certificates, that's why `install` done manually.
Patch `0002-cmake-nonstatic.patch` included directly from repository and can be removed in next release.
=> i2pd: update to 2.47.0

mingw-w64-glib-networking/PKGBUILD
Upstream doesn't build any static libs and now fails for library=both, so disable it.
Upstream disabled environment proxy module support by default, this should be handled by libproxy anyway.
=> glib-networking: Update to 2.76.0

mingw-w64-usbredir/0001-fix-callback-call-conv.patch, mingw-w64-usbredir/PKGBUILD
This drops the static libs, but both users of this don't need them, so should be fine.
=> usbredir: Update to 0.13.0; port to meson

mingw-w64-swi-prolog/PKGBUILD
from what I see this isn't used and there is also no reference to it in the swi-prolog source.
=> swi-prolog: remove openjpeg dependency

mingw-w64-nasm/PKGBUILD
from the changelog:
Support for the rdf format has been discontinued and all the RDOFF utilities has been removed.
=> nasm: Update to 2.16.01

mingw-w64-opencascade/PKGBUILD
The env.bat file get confused with env command in shell. That fails to build qemu.
=> opencascade: Remove unnecessary batch scripts

mingw-w64-arrow/PKGBUILD, mingw-w64-grpc/001-fix-building-shared-libraries-with-clang.patch, mingw-w64-grpc/PKGBUILD
@mstorsjo Could you please investigate this one.
Disabling `disabling-relocation` and enabling `CMAKE_POSITION_INDEPENDENT_CODE` didn't fix building shared grpc++ libs.
=> grpc: update to 1.53.0

mingw-w64-libidn/PKGBUILD
gnu.org server is down, or at least some mirrors
upstream is aware
=> libidn: Update to 1.41

mingw-w64-fritzing/PKGBUILD
because it fails in the libgit2 rebuild
=> fritzing: rebuild

mingw-w64-libatomic_ops/001-fix-pkgconfig.patch, mingw-w64-libatomic_ops/PKGBUILD
I tried to build it
- buildflags
- !buildflags
- buildflags + "-mcx16"
- !builflags + "-mcx16"
It always fails with GCC x86_64, I have found many issues about it on GH and Bugzilla none of the is fixed!
=> libatomic_ops: update to 7.8.0

mingw-w64-starpu/0001-fix-callback-missing-stdcall.patch, mingw-w64-starpu/PKGBUILD
it rightfully complains the the callback calling convention doesn't match
=> starpu: fix 32bit build with clang v16

mingw-w64-flang/0005-Fix-c_long_double-value-on-mingw-aarch64.patch, mingw-w64-flang/PKGBUILD
@hmartinez82 Could you build it on clangarm64.
Please compile this file test.f90
```Fortran
program test
use iso_c_binding
print *, 'c_long_double =', c_long_double
end program
```
```
$flang test.f90 -o test
$./test
```
The output should be ` c_long_double= 8` on clangarm64
=> flang: Fix c_long_double value on aarch64

mingw-w64-python-numpy/0013-fix-4GiB-fwrites.patch, mingw-w64-python-numpy/PKGBUILD
Fixes #15856. See also pending [upstream PR](https://github.com/numpy/numpy/pull/23505).
=> python-numpy: fix infinite loop when writing > 4GiB

mingw-w64-gdb/0006-Handle-unwinding-from-SEGV-on-Windows.patch, mingw-w64-gdb/PKGBUILD
Fixes the issue described in https://gitlab.com/inkscape/inkscape/-/issues/4031#note_1231250877. GDB is unable to retrieve any information regarding the callstack of the debugged program. Hence one may think that a stack corruption is going on, but instead it's just a call of a NULL function pointer.
Also fix compilation with clang 16 as suggested by @mmuetzel. See https://discourse.llvm.org/t/clang-16-notice-of-potentially-breaking-changes/65562 for more info
Reference https://sourceware.org/pipermail/gdb-patches/2023-March/198196.html
=> gdb: add patch

mingw-w64-manim/PKGBUILD
this makes sure the executable generated from the installer actually works
currently, running `manim.exe` I get the error
```
$ manim
Fatal error in launcher: Unable to find an appended archive.
```
this PR fixes that error
=> manim: disable strip option

mingw-w64-python-os-win/PKGBUILD, mingw-w64-python-os-win/iscsidsc-optional.patch, mingw-w64-python-pymi/0001-pymi-fix-mingw-compiler-error.patch, mingw-w64-python-pymi/PKGBUILD
pymi is a dependency of os-win, which is a library from openstack for managing hyper-v.
Draft until the patches for mingw-w64 are applied and the packages are updated, not worth carrying a downstream patch over.
=> new packages python-pymi and python-os-win

mingw-w64-tme/PKGBUILD
Release Candidate 10 of version 0.12. The major update with this release is upgrade support to GTK4 as a front-end GUI host. GTK3 is still supported for backward compatibility. Various other bug fixes for compiling & running have been added as well.
=> tme: Update to 0.12rc10

mingw-w64-mcfgthread/PKGBUILD
TLS and per-thread exit callbacks are now functional in threads that have been created by other libraries, e.g. by CreateThread() or pthread_create(). (https://github.com/lhmouse/mcfgthread/issues/81)
=> mcfgthread: Update to v1.5-beta.1

mingw-w64-crt-git/PKGBUILD
this is required to use CFG (Control Flow Guard)
tests here: https://github.com/msys2/msys2-tests/pull/34
=> crt: enable cfguard for clang environments

mingw-w64-python-winsdk/PKGBUILD
I don't have an arm64 computer with Windows, so I couldn't test clangarm64.
=> python-winsdk: Enable building on all mingw arch

mingw-w64-kicad-doc/PKGBUILD, mingw-w64-kicad-library/PKGBUILD, mingw-w64-kicad/PKGBUILD
Remove the patches that have been applied/fixed upstream.
Downloading the libraries was rather unreliable from my end. And it took several attempts to get valid archives. Let's see how the CI will fare.
There will likely be a circular dependency between the main application and the libraries. It should be possible to build them in any order.
Is there a way to have a dependency only for *runtime* but not for *build time*? Like a "reverse makedepends"?
=> kicad: update to 7.0.2

mingw-w64-qemu/PKGBUILD, mingw-w64-qemu/msys2.examples.tests.sh
starting with first build on 8.0.0-rc0
the patches for clangarm64 are already included in source code of 8.0.0-rc and thus removed from build
=> qemu: update to 8.0.0

mingw-w64-clang/0005-Fix-Any-linker-error-with-multiple-compilers.patch, mingw-w64-clang/PKGBUILD, mingw-w64-clang/README-patches.md
reverts this change: https://github.com/llvm/llvm-project/commit/95b27b2a1e0e9fe0781ec76015b4016b9d04423d
fixes the Rust build, see https://github.com/msys2/MINGW-packages/pull/16847
=> clang: fix Any linker error with multiple compilers

mingw-w64-python-numpy/0013-fix-4GiB-fwrites.patch, mingw-w64-python-numpy/PKGBUILD
Whoops! My temporary patch in #16553 broke 32-bit, where `numpy->tofile()` could not write any array of bytes. This update applies to 64-bit only (including UCRT variants), pending upstream changes.
=> python-numpy: fix previous patch breaking 32-bit

mingw-w64-qt-creator/PKGBUILD
It fixes creating new projects and splitting windows.
fixes #16646
=> qt-creator: rebuild against Qt 6.5.0

mingw-w64-fortran-stdlib/PKGBUILD
[Fortran-stdlib](https://github.com/fortran-lang/stdlib) is a community standard library for fortran-lang.
1. `clang32`, `clang64`, and `clangarm64` are not supported because they do not have `gfortran`.
2. ~~Currently `ming64-w64-python-fypp` is invalid due to a unknown bug, so this PR uses `pip` to install `fypp`.~~
=> Add Fortran-stdlib PKGBUILD

mingw-w64-connect/0001-Make-it-relocatable.patch, mingw-w64-connect/PKGBUILD, mingw-w64-connect/pathtools.c, mingw-w64-connect/pathtools.h
Currently, the `connect.exe` program looks for its configuration in a hard-coded location: `/etc/connectrc`. This is not a proper Windows path, though, therefore it is interpreted as an absolute path on the current drive.
Let's adjust this by making `connect.exe` relocatable, i.e. letting it figure out where the pseudo-Unix `/etc/connectrc` actually is located in the current MSYS2 setup. This way, the configuration file _can_ be stored in `$MINGW_PREFIX/etc/connectrc`.
This addresses CVE-2023-29011, a vulnerability reported to the Git for Windows project. For full details about this CVE, see https://github.com/git-for-windows/git/security/advisories/GHSA-g4fv-xjqw-q7jm
=> connect: make it relocatable

mingw-w64-ghdl/PKGBUILD
This adds support for building with clang/llvm v16
=> ghdl: Update to 3.0.0.r147.g6c56631a7

mingw-w64-cglm/0001-cglm-include-fix-arm64.patch, mingw-w64-cglm/PKGBUILD
This fixes the following error
In file included from cglm-0.9.0/src/../include/cglm/simd/intrin.h:71:
clangarm64/lib/clang/16/include/arm64intr.h:12:15: fatal error: 'arm64intr.h' file not found
include_next <arm64intr.h>
^~~~~~~~~~~~~
@podsvirov
=> cglm: Fix aarch64 intrin headers

mingw-w64-gcc/PKGBUILD
For details see https://bugs.archlinux.org/task/71777 In theory this should speed up the builds, let's see..
also enable parallel install while at it, this was disabled 10 years ago without any comment
=> gcc: sync cflags/ldflags setup with Arch

mingw-w64-gcc/PKGBUILD
There are no packages in MSYS2 that use it for 7 months, and we don't ship an import library for it since then as well, so remove it.
This also makes it possible to build gcc with stack protector enabled.
=> gcc: Remove libssp-0.dll (v2)

mingw-w64-gcc/PKGBUILD
See https://github.com/msys2/MINGW-packages/pull/16968#issuecomment-1539038359
This partially reverts https://github.com/lazka/MINGW-packages/commit/518e217a129eeeb92e5090f1bb14deaf0ed70edf
It's unclear which parts of LDFLAGS/CFLAGS are breaking gcc, needs
investigating. -fstack-protector-strong could be one cause.
=> gcc: revert recent changes

mingw-w64-libgsf/PKGBUILD
* backport clang v16 fix for finding bzip2
* disable gtk-doc, broken somehow
* general cleanup
=> libgsf: rebuild

mingw-w64-flatbuffers/PKGBUILD
GCC crashes without any error message.
=> flatbuffers: update to 23.5.9

mingw-w64-nanodbc/0001-disable-werror.patch, mingw-w64-nanodbc/PKGBUILD
because failing to build because of deprecations is never a good idea
=> nanodbc: build without -Werror

mingw-w64-emacs/002-clang-fixes.patch, mingw-w64-emacs/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17117
Compiling with clang failed due to wait(2) function is not declared in
emcas sys/wait.h file. The following error is shown in config.log file
conftest.c:70:3: error: call to undeclared function 'wait'; ISO C99 and
later do not support implicit function declarations [-Wimplicit-function-declaration]
This adds the suggestion from https://lists.gnu.org/archive/html/help-gnu-emacs/2023-05/msg00107.html
=> emacs: Fix compiling with clang due to sys/wait.h

mingw-w64-gcc/0022-fix-radix-sort-on-32bit-platforms.patch, mingw-w64-gcc/2000-enable-rust.patch, mingw-w64-gcc/2001-fix-building-rust-on-mingw-w64.patch, mingw-w64-gcc/PKGBUILD
- Backport patch from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109670#c12
- Prepare for new gcc-rust package (disabled by default)
=> gcc: Fix exception handling on mingw32

mingw-w64-litehtml/PKGBUILD
I still don't understand how did the previous packages were built!
The source download `url` contains the `$pkgname` (`==${MINGW_PACKAGE_PREFIX}-litehtml`)!
=> litehtml: update to 0.7

mingw-w64-mcfgthread/PKGBUILD
https://github.com/lhmouse/mcfgthread/releases/tag/v1.5-ga.2
=> mcfgthread: Upgrade to 1.5.2

mingw-w64-qt5-static/0003-enable-avx-support.patch, mingw-w64-qt5-static/PKGBUILD
Reduce buildtime by using release build mode instead of release-and-debug which builds release and debug libraries separately hence the long buildtime. We did the same with qt6-static.
=> qt5-static: enable vulkan

mingw-w64-clang/PKGBUILD
the split happened in 87c0fcc23c4171e4fa7c23, so with 16.0.2-2
=> clang: make llvm-libs conflict with llvm before the split

mingw-w64-luajit/003-lua51-modules-paths.patch, mingw-w64-luajit/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/16618
This matches the module search path with luajit in Linux environment.
The paths can be retrieved using these two lua code
print("package.path: "..package.path)
print("package.cpath: "..package.cpath)
The paths were replaced like this
* package path:
- Removed:
C:\msys64\ucrt64\bin\lua\?.lua;
C:\msys64\ucrt64\bin\lua\?\init.lua;
- Added:
C:\msys64\ucrt64\bin\..\share\luajit-2.1.0-beta3\?.lua;
C:\msys64\ucrt64\bin\..\share\luajit-2.1.0-beta3\?\init.lua;
* package cpath:
- Removed:
C:\msys64\ucrt64\bin\?.dll;
C:\msys64\ucrt64\bin\loadall.dll
- Added:
C:\msys64\ucrt64\bin\..\lib\lua\5.1\loadall.dll
=> luajit: Fix module search path

mingw-w64-lua/0003-Fix-LUA_-DIR-for-MSYS2-FHS-layout.patch, mingw-w64-lua/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/16638
This removes paths which are duplicate and with double slashes.
Also the module search path is now same as in Linux environment.
The paths can be retrieved using these two lua code
print("package.path: "..package.path)
print("package.cpath: "..package.cpath)
The removed paths as like this
* package path:
C:\msys64\ucrt64\bin\..\share\lua\5.4\\?.lua;
C:\msys64\ucrt64\bin\..\share\lua\5.4\\?\init.lua;
* package cpath:
C:\msys64\ucrt64\bin\..\lib\lua\5.4\..\lib\lua\5.4\\?.dll
=> lua: Fix incorrect module search path

mingw-w64-lua53/PKGBUILD, mingw-w64-lua53/searchpath.patch
Fixes https://github.com/msys2/MINGW-packages/issues/16638
This removes paths which are duplicate and with double slashes.
Also the module search path is now same as in Linux environment.
The paths can be retrieved using these two lua code
print("package.path: "..package.path)
print("package.cpath: "..package.cpath)
The removed paths as like this
* package path:
C:\msys64\ucrt64\bin\..\share\lua\5.3\\?.lua;
C:\msys64\ucrt64\bin\..\share\lua\5.3\\?\init.lua;
* package cpath:
C:\msys64\ucrt64\bin\..\lib\lua\5.3\..\lib\lua\5.3\\?.dll
=> lua53: Fix incorrect module search path

mingw-w64-libilbm/PKGBUILD
This follows up #17329 to finish adding support for GIMP's new [AMIGA IFF image plug-in](https://gitlab.gnome.org/GNOME/gimp/-/merge_requests/897). 
This patch proposes adding the libilbm package to the MSYS2 repository, which is required to build the GIMP IFF plug-in on Windows now that libiff has been accepted.
As the libiff and libilbm repositories are structured the same, the PKGBUILD file is nearly identical to what @Biswa96 assisted me with for libiff (thanks again!)
I tested and was able to build the package with this locally - hopefully there are no new issues!
=> [New Package]: libilbm

mingw-w64-gpgme/0004-gpgme-find-gnupg.patch, mingw-w64-gpgme/0005-invoke-scripts-via-sh.patch, mingw-w64-gpgme/0008-no-py2.patch, mingw-w64-gpgme/0009-fix-broken-version.patch, mingw-w64-gpgme/0010-m4-check-python-exit-code.patch, mingw-w64-gpgme/0011-makefile-am-disable-tests.patch, mingw-w64-gpgme/PKGBUILD, mingw-w64-gpgme/gpgmepp-portable-types.patch
* Remove hunks which replace gpgme-config with shell, fixed in https://dev.gnupg.org/rMae9258fbf3b9d434495ef11fc184a91fe7c4ca57
* Check exit code for python disutils due to deprecation message.
* Disable python test due to this [Makefile:645: pubring-stamp] Error 2
=> gpgme: update to 1.20.0

mingw-w64-emacs/PKGBUILD
Redo of #17319. `_FORTIFY_SOURCE` breaks the emacs builds. 
Resolves #16413 #16375 and #16190.
=> emacs: Remove _FORTIFY_SOURCE from build options

mingw-w64-glib2/PKGBUILD
=> glib2: backport two fixes for non-ascii command line parsing

mingw-w64-cogl/PKGBUILD
It doesn't build with newer clang anymore.
Since it is unmaintained and has no users left, just drop it for clang.
=> cogl: clean up makedepends and drop clang builds

mingw-w64-spice/PKGBUILD
* Enable lz4 for all architectures.
* Add libcacard dependency.
=> spice: update to 0.15.2

mingw-w64-cargo-generate/PKGBUILD
Added an extra newline to the `.cargo/config.toml` addition because I encountered a project that already had such a file that didn't end with a newline.
=> cargo-generate: add aarch64 workaround for windows-targets 0.48.0

mingw-w64-spirv-tools/PKGBUILD
Fellow/match spirv-headers, spirv-cross versioning.
1.3.x are tagged more frequently that 202x ones.
=> spirv-tools: update to 1.3.2.250.0

mingw-w64-librsvg/PKGBUILD
successful CLANGARM64 CI run: https://github.com/msys2-arm/MINGW-packages/actions/runs/5158221708/jobs/9291622259
=> librsvg: add gnullvm workaround for windows-targets 0.48.0

mingw-w64-nodejs/0001-Skip-check-OS-version.patch, mingw-w64-nodejs/0006-Define-_WIN32_WINNT-in-node.gypi.patch, mingw-w64-nodejs/PKGBUILD
node fails with error:
```
Node.js is only supported on Windows 8.1, Windows Server 2012 R2, or higher.
Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this
check, but Node.js might not execute correctly. Any issues encountered on
unsupported platforms will not be fixed
```
Fix it by setting _WIN32_WINNT to Windows 8.1
=> nodejs: Fix executing error

mingw-w64-emscripten/PKGBUILD
this brings the source package size down from 3.2GB to 0.5GB
=> emscripten: don't use git for llvm and binaryen

mingw-w64-rust/0007-clang-subsystem.patch, mingw-w64-rust/PKGBUILD
see https://github.com/msys2/MINGW-packages/pull/17406
=> rust: rebuild 1.69.0 to work around clang issue with 1.70.0

mingw-w64-mesa/0001-Add-checks-for-NULL-dxil_validator.patch, mingw-w64-mesa/PKGBUILD
As of now we miss dxil.dll within msys2 installation. This is being addressed by https://github.com/msys2/MINGW-packages/pull/16643, but creating a package for dxil will take some time due to resolving redistribution concerns.
In a meanwhile this commit applies patch from mesa main branch to avoid a crash on missing dxil.dll. This allows some workflows to actually work, for example, vaon12 media workflows which don't require shader operations.
Issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/8718
Upstream: https://gitlab.freedesktop.org/mesa/mesa/-/commit/098342ce53f692b719dd3aeb876737ad886c37f0
=> mesa: apply patch to avoid crash on missing dxil.dll

mingw-w64-libva-utils/PKGBUILD
As of libva version 2.18.0 and mesa 23.1.1 it's required to set the following environment variables to be able to work with vaon12 driver:
```
$ export | grep LIBVA
declare -x LIBVA_DRIVERS_PATH="/mingw64/bin/"
declare -x LIBVA_DRIVER_NAME="libvaon12"
```
This will be fixed in the next versions of libva and mesa - patches for that already landed in upstream versions of these components.
With above environment variables set user should see something like this (output depends on actual HW capabilities, below is a snapshot from Interl Alderlake running Windows 11):
```
$ vainfo
Trying display: win32
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'libvaon12'
libva info: Trying to open C:/msys64/mingw64/bin/\libvaon12_drv_video.dll
libva info: Found …
```
=> libva-utils: add package

mingw-w64-soapyrtlsdr/PKGBUILD
Yep! MinGW now has a bunch of radio and signal processing libs to tinker with!
This may not be able to compile as it depends on a just merged package (`rtl-sdr`). See https://github.com/msys2/MINGW-packages/pull/17459
If build fails, I will relaunch whenever the package pops up at https://packages.msys2.org/base/mingw-w64-rtl-sdr. Another interesting link https://packages.msys2.org/queue.
Thanks!
=> soapyrtlsdr: Add version 0.3.3

mingw-w64-mesa/0002-meson-vaon12-fix-driver-file-name-for-mingw-build.patch, mingw-w64-mesa/PKGBUILD
Mesa requires explicit flags to enable named video codecs. With these enabled, user should see output similar to this on vainfo (actual list depends on HW capabilities, below is from Intel Alderlake):
```
$ LIBVA_DRIVERS_PATH=/mingw64/bin/ vainfo
Trying display: win32
libva info: VA-API version 1.18.0
libva info: Trying to open C:/msys64/mingw64/bin/\vaon12_drv_video.dll
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0
C:\msys64\mingw64\bin\vainfo.exe: VA-API version: 1.18 (libva 2.18.2)
C:\msys64\mingw64\bin\vainfo.exe: Driver version: Mesa Gallium driver 23.1.1 for D3D12 (Intel(R) Iris(R) Xe Graphics)
C:\msys64\mingw64\bin\vainfo.exe: Supported profile and entrypoints
VAProfileH264ConstrainedBaseline: VAEntrypointVLD …
```
=> mesa: enable h264dec,h264enc,h265dec,h265enc,vc1dec video-codecs

mingw-w64-llvm-14/PKGBUILD
Needed for building https://github.com/m-labs/artiq and https://git.m-labs.hk/M-Labs/artiq-zynq firmware, which targets RISCV32 and ARM32 respectively.
=> Add ARM and RISCV as targets to LLVM-14

mingw-w64-python-pyopengl-accelerate/PKGBUILD
`PyOpenGL` was updated to 3.1.7 in cd65d1a7efabec69153fc511542a8cdf5f87ce5e but this package was left behind at 3.1.6
The two packages should always be updated in tandem - perhaps a note should be added in `PyOpenGL`?
This PR also switches to using releases from pypi, as those exist, unlike the repository on github.
=> PyOpenGL-accelerate 3.1.7

mingw-w64-miniupnpc/PKGBUILD
man files are now correctly installed with cmake (https://github.com/miniupnp/miniupnp/commit/12f7201abe2e3b7d88aef0b098502bce956a4628)
=> miniupnpc: update to 2.2.5

mingw-w64-luajit/PKGBUILD
This fixes crashes on 32-bit build. MSYS explicitly disables SEH for 32-bit builds which breaks the unwinding code in luajit.
Fixes: #17042
=> luajit: disable unwind on 32-bit builds

mingw-w64-libipt/001-fix-import-lib-naming.patch, mingw-w64-libipt/PKGBUILD
Adding Intel(R) Processor Trace (Intel PT) Decoder Library; the intended use is adding that to GDB as a follow-up.
=> new package: libipt

mingw-w64-emacs/PKGBUILD
For now this is a draft to test whether the build succeeds, I lack the knowledge to set up the CI.
I might have found the optimization that breaks the native-compilation build, `-foptimize-sibling-calls`. See also https://debbugs.gnu.org/cgi/bugreport.cgi?bug=63365.
=> emacs: Re-enable native-compilation, disable -foptimize-sibling-calls

mingw-w64-emacs-pdf-tools-server/PKGBUILD
Two points of note:
- I did not find a way to verify the checksum, as it is not included in the [release](https://github.com/vedang/pdf-tools/releases/tag/v1.1.0) and there doesn't seem to be a way to [view it on Github](https://github.com/orgs/community/discussions/23512). I determined it from my locally downloaded copy. If this causes security concerns, please indicate how I should determine the checksum.
- The binary should be used together with v1.1.0 of the Emacs package as available via [NonGNU ELPA](https://elpa.nongnu.org/nongnu/pdf-tools.html) or [MELPA Stable](https://stable.melpa.org/#/pdf-tools) (the latter of which seems to still be stuck on v1.0.0 though). Discrepancies between the lisp package and the binary can otherwise [cause …
=> emacs-pdf-tools-server: update to 1.1.0

mingw-w64-ffmpeg/PKGBUILD, mingw-w64-ffmpeg4.4/PKGBUILD
Fixes:
error: incompatible function pointer types initializing 'PFN_vkDebugUtilsMessengerCallbackEXT'
for clang32 since clang v16
=> ffmpeg: rebuild and backport a build fix; enable svt-av1 for clangarm64

mingw-w64-sdl12-compat/0001-just-build-normal.patch, mingw-w64-sdl12-compat/0002-sdl-config-win-paths.patch, mingw-w64-sdl12-compat/PKGBUILD
try to build it as a normal library without -nostdlib -static-libgcc stuff, which breaks for example stack protector. I might be missing something though.
Also no "replaces" for now, until we are sure it can replace sdl1
=> Add sdl12-compat
