- .ci/ci-check.py
Fixes https://github.com/msys2/MINGW-packages/issues/8749
> ci-check: don't fail if pacman install failed

- mingw-w64-liblo/010-lld.patch
- mingw-w64-liblo/PKGBUILD
> liblo: fix compilation with lld

- mingw-w64-gr/PKGBUILD
> gr: update to 0.57.3

- mingw-w64-libidn2/PKGBUILD
- mingw-w64-libpsl/PKGBUILD
- mingw-w64-libunistring/PKGBUILD
- mingw-w64-nghttp2/PKGBUILD
Try to address #8724 by separating static and shared builds
> Fix static libunistring and rebuild libidn2 and libpsl

- mingw-w64-libgpg-error/PKGBUILD
- mingw-w64-nettle/PKGBUILD
> Updates: nettle, libgpg-error

- mingw-w64-vlc/PKGBUILD
- mingw-w64-vlc/vlc-CLANG64.install
- mingw-w64-vlc/vlc-MINGW32.install
- mingw-w64-vlc/vlc-MINGW64.install
- mingw-w64-vlc/vlc-UCRT64.install
- mingw-w64-vlc/vlc-i686.install
- mingw-w64-vlc/vlc-x86_64.install
add one for each environ; set PATH in them
> vlc: fix the install scripts

- mingw-w64-leptonica/PKGBUILD
MINGW64: All tests succeeded.
* PKGBUILD:
- remove redundant OPTION
> leptonica: Upgrade to 1.81.0

- mingw-w64-helics/PKGBUILD
Update to the HELICS 2.7.1 release
> helics: Update to 2.7.1

- mingw-w64-texlive-bin/0003-runscript-always-quote-args.patch
- mingw-w64-texlive-bin/PKGBUILD
fixes https://github.com/msys2/MINGW-packages/issues/8821
possibly should be upstreamed, will do it soon.
> texlive-bin: fix launchers

- mingw-w64-shared-mime-info/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/8865
> shared-mime-info: Update to 2.1

- mingw-w64-libpcap/0001-cmake-install-rpcapd-bindir.patch
- mingw-w64-libpcap/0002-cmake-keep-lib-prefixed-dll.patch
- mingw-w64-libpcap/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/8866
> libpcap: Add package.

- mingw-w64-python-colored-traceback/PKGBUILD
- mingw-w64-python-intervaltree/PKGBUILD
- mingw-w64-python-plumbum/PKGBUILD
- python-colored-traceback
- python-intervaltree
- python-plumbum
> pwntools deps

- mingw-w64-aom/PKGBUILD
- mingw-w64-aom/f19edfa.diff
special thanks to @1480c1 for creating the patch for upstream
> aom: Backport a patch to allow clang to compile this release.

- mingw-w64-aspell-en/PKGBUILD
- mingw-w64-aspell/0002-printf.mingw.patch
- mingw-w64-aspell/0003-no-undefined-on.mingw.patch
- mingw-w64-aspell/0004-reloc.mingw.patch
- mingw-w64-aspell/0005-w32-home.all.patch
- mingw-w64-aspell/0006-abort.mingw.patch
- mingw-w64-aspell/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/6538
> aspell: Update to 0.60.8

- mingw-w64-dosbox/PKGBUILD
- mingw-w64-munt-mt32emu/PKGBUILD
(the more modern https://github.com/dosbox-staging/dosbox-staging fork to be exact)
> Add dosbox

- mingw-w64-openFPGALoader/PKGBUILD
See https://github.com/trabucayre/openFPGALoader/releases/tag/v0.3.0.
> openFPGALoader: update to 0.3.0

- mingw-w64-scopehal-apps/PKGBUILD
> scopehal-apps: update to 0.0.0.r1213.g5855e49

- mingw-w64-bat/PKGBUILD
- mingw-w64-dust/PKGBUILD
https://github.com/sharkdp/bat
> new package bat and dust

- mingw-w64-openFPGALoader/PKGBUILD
See https://github.com/trabucayre/openFPGALoader/releases/tag/v0.4.0.
> openFPGALoader: update to 0.4.0

- mingw-w64-libcdio/PKGBUILD
I have *no* idea how this built on CLANG64...
> libcdio: disable version script on clang.

- .github/workflows/main.yml
Now that there is one, use it and potentially reduce load on repo.msys2.org
> CI: use mirrorlist for clang32.

- mingw-w64-github-cli/PKGBUILD
> github-cli: update to v1.12.1

- mingw-w64-python3.9/0103-squash-Fixup-.rc-handling.patch
- mingw-w64-python3.9/0104-squash-Set-MS_DLL_ID.patch
- mingw-w64-python3.9/0107-squash-fix-srcdir-builddir.patch
- mingw-w64-python3.9/PKGBUILD
for https://github.com/msys2-contrib/cpython-mingw/pull/12
> Update Python 3.9

- mingw-w64-libmysofa/001-mingw-dont-use-nuget.patch
- mingw-w64-libmysofa/002-fix-exports.patch
- mingw-w64-libmysofa/003-install-import-library.patch
- mingw-w64-libmysofa/004-fix-dllexport-attribute.patch
- mingw-w64-libmysofa/005-add-cflag-private-for-staticlib.patch
- mingw-w64-libmysofa/PKGBUILD
The idea is shamelessly copied/stolen from https://github.com/msys2/MINGW-packages/pull/8606
Pinging some bots @jeremyd2019 @neheb @ZachBacon
> libmysofa: Update to 1.2, use ninja

- mingw-w64-vala-language-server/PKGBUILD
Release vala-language-server 0.48.3
> Vala-language-server 0.48.3

- mingw-w64-rust/0007-clang-subsystem.patch
- mingw-w64-rust/0008-disable-self-contained.patch
- mingw-w64-rust/PKGBUILD
> Rust fixes

- mingw-w64-rust/PKGBUILD
Spotted in https://github.com/msys2/MINGW-packages/pull/9086#pullrequestreview-698700893
> Remove duplicated sections in Rust PKGBUILD

- mingw-w64-aom/PKGBUILD
- mingw-w64-assimp/PKGBUILD
- mingw-w64-qt6-base/PKGBUILD
- mingw-w64-qt6-declarative/PKGBUILD
- mingw-w64-wxWidgets/PKGBUILD
- mingw-w64-wxWidgets3.1/PKGBUILD
- mingw-w64-xalan-c/PKGBUILD
mingw-w64-clang-12.0.0-8 should no longer require these
> remove clang32 hacks for CI

- mingw-w64-ffmpeg/PKGBUILD
- mingw-w64-l-smash/0001-remove-version-script.patch
- mingw-w64-l-smash/PKGBUILD
- mingw-w64-openal/PKGBUILD
- mingw-w64-x264/PKGBUILD
and fix compiling of l-smash for clang by patching it's configure script for clang environments only.
> [Road to clang ffmpeg] 

- mingw-w64-gst-plugins-bad/PKGBUILD
- mingw-w64-gtk4/PKGBUILD
> gst-plugins-bad: split into libs and plugins

- mingw-w64-gtksourceview5/001-missing-include.patch
- mingw-w64-gtksourceview5/PKGBUILD
> Add GtkSourceView 5.0

- mingw-w64-librsvg/0006-fix-vapigen-deps.patch
- mingw-w64-librsvg/PKGBUILD
> librsvg: fix build with newer gdk-pixbuf

- mingw-w64-openimageio/0020-set-import-prefix.patch
- mingw-w64-openimageio/PKGBUILD
> openimageio: set _IMPORT_PREFIX

- mingw-w64-glib2/0003-GWin32Mount-Don-t-use-SHGetFileInfoW-for-icons.patch
- mingw-w64-glib2/0004-GWin32Mount-Don-t-use-SHGetFileInfoW-for-mount-displ.patch
- mingw-w64-glib2/PKGBUILD
> glib2: backport some Windows improvements

- mingw-w64-poppler-qt6/010-clang.patch
- mingw-w64-poppler-qt6/PKGBUILD
Just an experiment for this issue https://github.com/msys2/MINGW-packages/issues/9126
> poppler-qt6: Add package

- mingw-w64-petsc/PKGBUILD
Version bump.
Also added the build flavor suffix description.
> petsc: version bump

- mingw-w64-mpg123/PKGBUILD
Update to latest release: http://mpg123.com/#20210712
> mpg123: update to 1.28.2

- mingw-w64-svt-av1/PKGBUILD
https://gitlab.com/AOMediaCodec/SVT-AV1
Seems restricted to x86_64
> svt-av1: new package

- mingw-w64-sundials/0001-sundials-link-errors.patch
- mingw-w64-sundials/0002-sundials-missing-export.patch
- mingw-w64-sundials/0003-sundials-use-default-installdirs.patch
- mingw-w64-sundials/0004-sundials-superlu_dist-manual-index-size.patch
- mingw-w64-sundials/0005-sundials-superlu_dist-test-link-errors.patch
- mingw-w64-sundials/0006-sundials-petsc-integration.patch
- mingw-w64-sundials/PKGBUILD
We currently have the CVODE subproject, but not the main SUNDIALS project. The SUNDIALS project is used by GNU Octave, for example.
Please take a look at the check function and comment it out if needed. The tests for MPI require an executable which I'm not sure potential automatic build systems will have.
This is my first attempt at packaging, so maybe look a bit more carefully for mistakes.
> sundials: New package

- mingw-w64-dbus-glib/PKGBUILD
> dbus-glib: update to 0.112

- mingw-w64-cmake/0005-Default-to-ninja-generator.patch
- mingw-w64-cmake/PKGBUILD
It defaults to msvc/nmake otherwise which in MSYS2 is never a good default imo.
> cmake: default to ninja

- mingw-w64-enet/001-no-undefined.patch
- mingw-w64-enet/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/9184
> enet: Update to 1.3.17

- mingw-w64-github-cli/PKGBUILD
> gh: update to v1.13.1

- mingw-w64-moab/0000-fix.patch
- mingw-w64-moab/PKGBUILD
Update PKGBUILD
Delete 0000-fix.patch
Add files via upload
> moab: update

- mingw-w64-v8/0000-add-mingw-main-code-changes.patch
- mingw-w64-v8/0001-add-mingw-toolchain.patch
- mingw-w64-v8/0002-gn-ninja-deletes-objs-workaround.patch
- mingw-w64-v8/PKGBUILD
Just a regular stable version update.
> [v8] Update to 9.1.269.39

- mingw-w64-libgda/006-Use-goocanvas-3.0.patch
- mingw-w64-libgda/007-Use-single-header-with-GtkSource.patch
- mingw-w64-libgda/008-lemon-fix-segfault.patch
- mingw-w64-libgda/PKGBUILD
Changes:
* Check for goocanvas 3.0
* Replace old gtksourceview headers
* Fix segfault in lemon
> libgda: Fix ucrt build

- mingw-w64-sqlitebrowser/0001-sqlitebrowser-install.patch
- mingw-w64-sqlitebrowser/0002-sqlitebrowser-linking.patch
- mingw-w64-sqlitebrowser/PKGBUILD
Qt gui for sqlite
first packaging attempt, comments are requested
> New package: sqlitebrowser

- mingw-w64-python-pandas/PKGBUILD
Tested build and functionality - no issues encountered.
> Update pandas to 1.3.1

- mingw-w64-binutils/0010-bfd-Increase-_bfd_coff_max_nscns-to-65279.patch
- mingw-w64-binutils/0110-binutils-mingw-gnu-print.patch
- mingw-w64-binutils/0600-Change-uint-to-unsigned.patch
- mingw-w64-binutils/2001-ld-option-to-move-default-bases-under-4GB.patch
- mingw-w64-binutils/2002-Allow-spaces-in-the-name-of-the-external-preprocesso.patch
- mingw-w64-binutils/PKGBUILD
rebased patches; removed the ones in the release; backported one build fix from upstream
> binutils: Update to 2.37

- mingw-w64-premake/0001-contrib-curl-pollfd-conflict.patch
- mingw-w64-premake/0002-fix-for-mingw.patch
- mingw-w64-premake/0003-bootstrap-use-nix-commands.patch
- mingw-w64-premake/PKGBUILD
A complete re-write of the PKGBUILD file /cc @martell
> premake: Update to 5.0.0-alpha16

- mingw-w64-arrow/0001-detect-version-script-flag.patch
- mingw-w64-arrow/PKGBUILD
> arrow: Disable --version-script for clang

- mingw-w64-python-cx-freeze/0000-backport-to-support-clang
- mingw-w64-python-cx-freeze/PKGBUILD
> cx_Freeze 6.7 - support for clang

- .ci/ci-build.sh
This PR change the way ci build packages.
Previously the ci sort the packages by dependency and then build them
one after another. The upside of that approach is to be able to build
dependent packages within the same job, the downsides is that approach
makes it impossible to build conflicting packages within the same job,
and also doesn't offer a clean environment to build the independent packages.
With this approach we uninstall every package after a successful build
while adding a local (ci) repository from where the following packages
can install their dependencies. This approach will allow to build conflicting
packages within the same job and offering a clean environment to build
the independent packages, so we can discover missing make-dependencies.
> Allow building conficting packages by the same CI

- mingw-w64-aravis/PKGBUILD
Split packages for low-level library+tools and GStreamer plugin and GUI viewer.
> Update aravis version, modularize, minimize deps

- mingw-w64-github-cli/PKGBUILD
See https://github.com/cli/cli/releases/tag/v1.14.0
> gh: update to v1.14.0

- mingw-w64-libspatialite/0002-use-win32-mutex-locks.patch
- mingw-w64-libspatialite/0003-headers-gaiaconfig-remove-triplet.patch
- mingw-w64-libspatialite/PKGBUILD
@revelator @podsvirov @jeroen Review please.
> libspatialite: Fix build for clang

- mingw-w64-libsidplayfp/PKGBUILD
- mingw-w64-sidplayfp/PKGBUILD
Update both library and frontend to latest upstream.
> Update libsidplayfp and sidplayfp

- mingw-w64-tzdata/PKGBUILD
See https://github.com/msys2-contrib/cpython-mingw/issues/32
> tzdata: new package

- mingw-w64-mruby/PKGBUILD
> mruby: touch y.tab.c to try to avoid bison

- mingw-w64-SDL_mixer/PKGBUILD
- mingw-w64-SDL_mixer/non-void-return-value.patch
> SDL_config: return a value from a non-void function

- mingw-w64-mruby/PKGBUILD
- mingw-w64-mruby/proper-line-statements.patch
Fix mangling of #line statements, which were losing their closing double quotes.  Fixes #9325 ?  🙏
> mruby: fix rewriting of #line statements

- mingw-w64-glib2/0005-Backport-GWin32AppInfo-fixes.patch
- mingw-w64-glib2/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/9283
> glib2: backport GWin32AppInfo fixes

- mingw-w64-mumps/PKGBUILD
Added description of the build flavor suffix.
> mumps: version bump

- mingw-w64-libftdi/0001-cmake-fix-libdir.patch
- mingw-w64-libftdi/PKGBUILD
> libftdi: Fix libdir in pkgconfig

- mingw-w64-qt6-5compat/PKGBUILD
> qt6-5compat: Enable QtGraphicalEffects plugin with qt6-declarative

- mingw-w64-qt5-multimedia/0001-fix-wmf-plugin.patch
- mingw-w64-qt5-multimedia/PKGBUILD
> qt5-multimedia: Enable WMF plugin

- mingw-w64-cgal/PKGBUILD
- mingw-w64-cmake/PKGBUILD
- mingw-w64-djview/PKGBUILD
- mingw-w64-doxygen/PKGBUILD
- mingw-w64-qwt/001-separate-debug-info-build.patch
- mingw-w64-qwt/PKGBUILD
- cgal
- djview
- doxygen
- cmake
- qwt
> Update Qt5 reverse dependencies (1/n)

- mingw-w64-gpgme/PKGBUILD
- mingw-w64-gr/PKGBUILD
- mingw-w64-grantlee/PKGBUILD
- mingw-w64-graphviz/PKGBUILD
- mingw-w64-jom/PKGBUILD
- mingw-w64-liblastfm/PKGBUILD
- mingw-w64-libosmscout/PKGBUILD
- mingw-w64-munt/PKGBUILD
- mingw-w64-nextpnr/PKGBUILD
- gpgme
- gr
- graphviz
- grantlee
- jom
- liblastfm
- munt
- libosmscout
- nextpnr
> Update Qt5 reverse dependencies (2/n)

- mingw-w64-cppcheck/PKGBUILD
- mingw-w64-fritzing/PKGBUILD
- mingw-w64-pinentry/PKGBUILD
- mingw-w64-poppler/PKGBUILD
- cppcheck
- fritzing
- poppler
- pinentry
> Update Qt5 reverse dependencies (3/n)

- mingw-w64-libexodus/PKGBUILD
This provides also .dll library
> libexodus: switch from old Makefile to cmake

- mingw-w64-qbs/PKGBUILD
- mingw-w64-qt-creator/PKGBUILD
- mingw-w64-quarter/PKGBUILD
- mingw-w64-quazip/PKGBUILD
- mingw-w64-qxmpp/PKGBUILD
- mingw-w64-simple-mail/PKGBUILD
- mingw-w64-soqt/PKGBUILD
- mingw-w64-sqlitebrowser/PKGBUILD
- mingw-w64-ttfautohint/PKGBUILD
- mingw-w64-xpdf/PKGBUILD
- quarter
- quazip
- qbs
- qt-creator
- qxmpp
- simple-mail
- sqlite-browser
- soqt
- ttfautohint
- xpdf
> Update Qt5 reverse dependencies (5/n) 

- mingw-w64-pyqt5-3d/PKGBUILD
- mingw-w64-pyqt5/PKGBUILD
- mingw-w64-qscintilla/PKGBUILD
I have disabled qtwebkit for pyqt5, until we resolve the failure in #9374
> Update dependencies for PyQt5 and QScintilla

- mingw-w64-mathgl/PKGBUILD
- mingw-w64-tulip/PKGBUILD
- mingw-w64-wkhtmltopdf-git/PKGBUILD
- mingw-w64-zeal/PKGBUILD
All of these packages depend on qtwebkit, so they will fail on clang subsystems
> Update dependencies for some qt5-dependent packages.

- .github/workflows/main.yml
- mingw-w64-talkatu/PKGBUILD
> talkatu: new package

- mingw-w64-doxygen/0002-fix-warning-msvc-pragma.patch
- mingw-w64-doxygen/0003-remove-git-version-from-bins.patch
- mingw-w64-doxygen/PKGBUILD
> doxygen: Remove git hash from binaries

- mingw-w64-newton-dynamics/0003-fix-newton-h.patch
- mingw-w64-newton-dynamics/PKGBUILD
This fix has been committed in newton main repository but no new version yet.
> Update newton-dynamics: fix compile error in Newton.h

- mingw-w64-ngspice/PKGBUILD
A new release was published.
/cc @holvo
> ngspice: update to 35

- mingw-w64-qt5-static/0016-qt-5.8.0-win32-g++-use-qpa-genericunixfontdatabase.patch
- mingw-w64-qt5-static/PKGBUILD
- mingw-w64-qt5-static/qt5-CLANG32.install
- mingw-w64-qt5-static/qt5-CLANG64.install
- mingw-w64-qt5-static/qt5-CLANGARM64.install
- mingw-w64-qt5-static/qt5-MINGW32.install
- mingw-w64-qt5-static/qt5-MINGW64.install
- mingw-w64-qt5-static/qt5-UCRT64.install
pull in all the changes from the qt5 package
> qt5-static: sync with shared version

- mingw-w64-ngspice/PKGBUILD
@umarcor As discussed here https://github.com/msys2/MINGW-packages/pull/9442
> ngspice: Install shared libraries with make

- mingw-w64-qwt/PKGBUILD
> qwt: Fix qwt.prf file.

- mingw-w64-roswell/PKGBUILD
Common Lisp environment setup Utility.
> roswell: new package

- mingw-w64-qemu/PKGBUILD
> qemu: use llvm-ar and llvm-ranlib for clang

- mingw-w64-ffts/0001-CMake-Pretend-clang-is-gcc.patch
- mingw-w64-ffts/0002-CMake-Install-dll-in-bindir.patch
- mingw-w64-ffts/0003-CMake-Install-pkgconfig-file.patch
- mingw-w64-ffts/PKGBUILD
- mingw-w64-scopehal-apps/0001-glscopeclient-Check-WIXPATH-before-creating-MSI-inst.patch
- mingw-w64-scopehal-apps/PKGBUILD
@umarcor Review please. Also someone please check the pkgconfig file.
> ffts: Fix clang build

- mingw-w64-ghdl/PKGBUILD
- mingw-w64-iverilog/PKGBUILD
- mingw-w64-nextpnr/PKGBUILD
- mingw-w64-yosys/PKGBUILD
Improve the pkgver() of some packages, according to https://github.com/msys2/MINGW-packages/pull/9485/commits/0df9467c8fd22d30ef9f8aac1fce56836832b0af.
> improve pkgver

- .github/workflows/main.yml
${{ github.ref }} equal to `refs/heads/branch` if the event is "push" and It is equal to `refs/pull/#pr/megre` for a pull-request.
> [GHA] Cancel previous workflows in the same branch/pull-request

- mingw-w64-highway/PKGBUILD
Will be required for JPEG XL etc
> highway: new package

- mingw-w64-snappy/0001-cmake-add-pkgconfig.patch
- mingw-w64-snappy/PKGBUILD
- mingw-w64-snappy/snappy.pc.in
Please check if the pkgconfig file is correct.
> snappy: Update to 1.1.9, use Ninja

- mingw-w64-qt5/PKGBUILD
> qt5-debug: switch to new debug packages

- mingw-w64-gr/PKGBUILD
Thanks for your MINGW maintenance.
> gr: Update to 0.59.0

- mingw-w64-python-rst2pdf/PKGBUILD
> python-rst2pdf: add some missing deps

- mingw-w64-serial-studio/PKGBUILD
Version 1.0.21 was tagged (Serial-Studio/Serial-Studio#68). This is a regular update.
/cc @alex-spataru
> serial-studio: update to 1.0.21

- mingw-w64-zimg/PKGBUILD
> zimg: update to 3.0.3

- .ci/ci-get-build-order.py
If a package being built depends on a split package, ci-get-build-order would return the split package name, not the original directory name it started with, which may be different.  I don't know if this happens in MINGW-packages, but it was the case with curl/libcurl in MSYS2-packages.
Fixes msys2/MSYS2-packages#2634
/cc @jtanx
> CI: track package directory in ci-get-build-order.py

- .ci/ci-build.sh
- .ci/ci-library.sh
> CI: merge with MSYS2-packages

- .ci/ci-library.sh
https://github.com/msys2/MSYS2-packages/pull/2635#discussion_r702816246
> CI: don't fail if no packages changed

- mingw-w64-python-nuitka/PKGBUILD
*UPDATE*: from 0.6.16.4 to 0.6.16.5
> python-nuitka: Update to 0.6.16.5

- mingw-w64-openlibm/01-mingw-build.patch
- mingw-w64-openlibm/02-mingw-clang-symbol.patch
- mingw-w64-openlibm/03-mingw-importlib-install.patch
- mingw-w64-openlibm/04-mingw-aarch64.patch
- mingw-w64-openlibm/PKGBUILD
I had a productive time with upstream, and got openlibm building for MINGW there, and got them an MSYS2 CI that builds and runs tests successfully.  Sync our package with the results of that.
> openlibm: update with upstream patches

- mingw-w64-plplot/PKGBUILD
> plplot: Fix building on clang subsystems

- mingw-w64-postgis/PKGBUILD
> postgis: Fix building on ucrt64 and clang subsystems

- mingw-w64-wget2/PKGBUILD
- mingw-w64-wget2/configure-ac-use-srcdir.patch
- mingw-w64-wget2/mingw-dllexport.patch
No shared libs on clang subsystems!
@jeremyd2019 any idea?
> [new-package] wget2 2.0.0

- mingw-w64-pkgconf/0001-pkgconf_pkg_parser_value_set-fix-code-path-ordering-.patch
- mingw-w64-pkgconf/PKGBUILD
See https://github.com/msys2/MINGW-packages/issues/9602
> pkgconf: revert an upstream commit causing a regression

- mingw-w64-pulseaudio/0001-remove-assert-pid_t-mismatch.patch
- mingw-w64-pulseaudio/0002-meson-check-version-script.patch
- mingw-w64-pulseaudio/0003-Fix-pointer-to-integer-cast-warnings.patch
- mingw-w64-pulseaudio/PKGBUILD
Thanks to @1480c1 🙇 without whom this would not be possible. Please review and test the package. If the clang version script workaround is correct I can upstream it.
> pulseaudio: Add package

- mingw-w64-python/0116-decimal-backport-build-fixes.patch
- mingw-w64-python/0117-smoketests-test-that-_decimal-exists.patch
- mingw-w64-python/PKGBUILD
> python: fix missing _decimal module

- mingw-w64-cmark/PKGBUILD
> cmark: update to 0.30.2

- mingw-w64-helics/PKGBUILD
Update to the HELICS 2.8.0 release
> helics: Update to 2.8.0

- mingw-w64-libheif/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/9694
> libheif: restore flag

- mingw-w64-libraqm/PKGBUILD
This updates libraqm to 0.7.2.
> libraqm: update to 0.7.2

- mingw-w64-qt-creator/PKGBUILD
- mingw-w64-qt-creator/qt-creator-5.0.1-fix-library-archive-path.patch
Recreated #9665 for [Hacktoberfest](https://hacktoberfest.digitalocean.com/). Can anybody add label `hacktoberfest-accepted` to this `PR`?
Install `Devel` component.
Closes #9664.
> qt-creator: Update to 5.0.2

- mingw-w64-python-unidecode/PKGBUILD
Hi. I'm Participant of the [Hacktoberfest](https://hacktoberfest.digitalocean.com/). Can anybody add label `hacktoberfest-accepted` to this `PR`?
> python-unidecode: Update to 1.3.0

- mingw-w64-python-feedgenerator/PKGBUILD
I'm Participant of the [Hacktoberfest](https://hacktoberfest.digitalocean.com/). Can anybody add label `hacktoberfest-accepted` to this `PR`?
> python-feedgenerator: Update to 1.9.2

- mingw-w64-jansson/PKGBUILD
> jansson: update to 2.14

- mingw-w64-precice/PKGBUILD
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=precice
> precice: update and a little unification with the arch linux version 

- mingw-w64-python-pywin32/001-compile-and-setup-fixes.patch
- mingw-w64-python-pywin32/002-com-extensions-fix.patch
- mingw-w64-python-pywin32/003-win32-extensions-fix.patch
- mingw-w64-python-pywin32/004-isapi-fix.patch
- mingw-w64-python-pywin32/005-swig-fix.patch
- mingw-w64-python-pywin32/PKGBUILD
-Disable clang build
-Disable adsi module coz adsiid stub is incomplete
-Link to static gcc, stdc++ and winpthread to avoid dll import error issue
> pywin32: Update to b302

- mingw-w64-opencascade/0009-sse2-detetction-gcc.patch
- mingw-w64-opencascade/PKGBUILD
> Update opencascade to 7.5.3 and try to fix installed .cmake 

- mingw-w64-texlive-bin/0005-texk-dvipdfm-x-Don-t-copy-libtool-wrapper.patch
- mingw-w64-texlive-bin/0006-dvisvgm-Fix-for-gcc11.patch
- mingw-w64-texlive-bin/PKGBUILD
Fixes https://github.com/msys2/msys2-texlive/issues/18
> texlive-bin: fix extractbb.exe and related

- mingw-w64-open62541/PKGBUILD
> Add open62541 package

- mingw-w64-qt6-scxml/001-appending-qt6-to-remove-qt5-conflict.patch
- mingw-w64-qt6-scxml/PKGBUILD
> qt6-scxml: remove conflict with qt5-scxml

- mingw-w64-wget/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/9959
> wget: Remove metalink option

- mingw-w64-rust/PKGBUILD
> rust: update to 1.56.1

- .github/workflows/main.yml
> Fix `main` workflow: pactoys-git -> pactoys

- .github/workflows/main.yml
> CI: Change MSYS2 default Installation location

- mingw-w64-python-imageio/PKGBUILD
Also misc sync w/ Python template
> python-imageio: update to 2.10.1

- mingw-w64-octave/PKGBUILD
Update to new upstream release.
> octave: update to 6.4.0

- mingw-w64-gcc/PKGBUILD
- mingw-w64-gcc/vmov-alignment.patch
Fix for https://github.com/msys2/MSYS2-packages/issues/1209
> workaround for AVX misalignment issue for pass-by-value arguments

- mingw-w64-zxing-cpp/PKGBUILD
squash merge commit: https://github.com/msys2/MINGW-packages/pull/9962
> add package: mingw-w64-zxing-cpp

- mingw-w64-benchmark/PKGBUILD
- mingw-w64-double-conversion/PKGBUILD
- mingw-w64-fmt/PKGBUILD
- mingw-w64-snappy/PKGBUILD
- mingw-w64-uriparser/PKGBUILD
For only the packages that export cmake files.
> Install static library before the shared one.

- mingw-w64-python-lsp-black/PKGBUILD
> new package: python-lsp-black

- mingw-w64-python-statsd/PKGBUILD
`jupyter-nbviewer` requires `statsd`
> new package: python-statsd

- mingw-w64-python-pyls-spyder/PKGBUILD
> new package: python-pyls-spyder

- mingw-w64-python-graphviz/PKGBUILD
newer `pylint` have `graphviz` as optdepends
> new package: python-graphviz

- mingw-w64-eog/005-content-type-to-mime-type-conversion.patch
- mingw-w64-eog/PKGBUILD
this fixes #9969
problem reported to upstream
https://gitlab.gnome.org/GNOME/eog/-/merge_requests/112
https://gitlab.gnome.org/GNOME/eog/-/issues/214
> fix eog cant open directories with images

- mingw-w64-python-keyring/PKGBUILD
failed on reverse dependency (spyder)
this is good to go..
> python-keyring: fix versioning

- mingw-w64-openscad/002-openscad-2021-remove-print-polyhedron.patch
- mingw-w64-openscad/PKGBUILD
> openscad: Rebuild with CGAL 5.3

- mingw-w64-python-astroid/PKGBUILD
> python-astroid: update to 2.8.4

- mingw-w64-python-elasticsearch/PKGBUILD
`jupyter-nbviewer` requires `elasticsearch`
> new package: python-elasticsearch

- mingw-w64-openblas/008-export-only-shared-library.patch
- mingw-w64-openblas/PKGBUILD
> OpenBLAS: Fix cmake exported targets.

- mingw-w64-python-pylint/PKGBUILD
waiting for `astroid` and `platformdirs`
> python-pylint: update to 2.11.1

- mingw-w64-spatialindex/0001-mingw-fixes.patch
- mingw-w64-spatialindex/PKGBUILD
https://archlinux.org/packages/community/x86_64/spatialindex/
Required for python-rtree (not sure if that works..)
> Add spatialindex

- mingw-w64-gtk4/0001-GdkWin32-Remove-the-global-screen-offset.patch
- mingw-w64-gtk4/PKGBUILD
Looks like many people are hitting issues that are fixed by https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4104:
* https://gitlab.gnome.org/GNOME/gtk/-/issues/4348
* https://gitlab.gnome.org/GNOME/gtk/-/issues/4471
* https://gitlab.gnome.org/GNOME/gtk/-/issues/1477
Better add a fix now instead of waiting for the next GTK 4.4.x release.
> GTK4: Add patch

- mingw-w64-cmake/0006-fix-clang32-crash.patch
- mingw-w64-cmake/PKGBUILD
See #10152
Unclear what a difference this makes, but it fixes the crash.
> cmake: work around crash

- mingw-w64-python-dateutil/PKGBUILD
This is my first contribution to this project. Please let me know if there is need for more to get this package updated. Thx.
> python-dateutil: Update to 2.8.2

- mingw-w64-python-autopep8/PKGBUILD
preparing for `python-lsp-server`
> new package: python-autopep8

- mingw-w64-fpm/PKGBUILD
Use a cleaner bootstrapping mechanism and download bootstrap version in sources.
> Update fpm to version 0.5.0

- mingw-w64-lis/PKGBUILD
They reuploaded the same file on 18/11!
> lis: update sha256sums and enable complex

- mingw-w64-virglrenderer/0001-Virglrenderer-on-Windows-and-macOS.patch
- mingw-w64-virglrenderer/PKGBUILD
As requested in  #10144 
With minor modifications in https://github.com/kjliew/qemu-3dfx/blob/master/virgil3d/MINGW-packages/PKGBUILD
Tests won't compile because of missing iovec
> virglrenderer: New Package

- mingw-w64-vapoursynth/0001-wrong-arguments-to-Mem32-constructor.patch
- mingw-w64-vapoursynth/PKGBUILD
> vapoursynth: fix clang32 build

- mingw-w64-fossil/PKGBUILD
- mingw-w64-sqlite3/PKGBUILD
~~Waiting for sqlite 3.37...~~
*UPDATE*: Meet sqlite 3.37 and fossil 2.17!
> Update sqlite to 3.37 and fossil to 2.17

- mingw-w64-ghdl/PKGBUILD
- mingw-w64-iverilog/PKGBUILD
- mingw-w64-nextpnr/PKGBUILD
- mingw-w64-scopehal-apps/PKGBUILD
- mingw-w64-serial-studio/PKGBUILD
- mingw-w64-yosys/PKGBUILD
A regular update of several EDA tools.
> Update EDA tools

- mingw-w64-python-skia-pathops/PKGBUILD
- mingw-w64-skia/.gitignore
- mingw-w64-skia/0001-add-mingw-toolchain.patch
- mingw-w64-skia/0002-gn-ninja-deletes-objs-workaround.patch
- mingw-w64-skia/0003-dont-download-prebuild-gn.patch
- mingw-w64-skia/0004-add-mingw-toolchain-skia.patch
- mingw-w64-skia/0005-fix-dwrite-function-mingw.patch
- mingw-w64-skia/0006-add-missing-limits.patch
- mingw-w64-skia/0007-add-mingw-toolchain-build.patch
- mingw-w64-skia/0008-dont-undef-CLSID_WICImagingFactory-on-mingw.patch
- mingw-w64-skia/0009-remove-as-needed-from-ldflags.patch
- mingw-w64-skia/PKGBUILD
- mingw-w64-skia/harfbuzz.gn
- mingw-w64-skia/icu.gn
- mingw-w64-skia/skia.pc
- mingw-w64-skia/zlib.gn
most patches related to gn are from the v8 package.
I need this for https://pypi.org/project/skia-pathops/
> skia: new package

- mingw-w64-PKGBUILD-templates/PKGBUILD.python-pyproject2setuppy.sh
- mingw-w64-python-pyproject2setuppy/PKGBUILD
- mingw-w64-python-tomli-w/PKGBUILD
- mingw-w64-python-tomli/PKGBUILD
new package
mingw-w64-python-tomli
rewrote to use pyproject2setuppy
mingw-w64-python-tomli-w
new package
> mingw-w64-python-pyproject2setuppy -

- mingw-w64-fgsl/PKGBUILD
- mingw-w64-gsl/PKGBUILD
- mingw-w64-gstreamer/PKGBUILD
- mingw-w64-inkscape/PKGBUILD
- mingw-w64-mathgl/PKGBUILD
- mingw-w64-ngraph-gtk/PKGBUILD
- mingw-w64-python-cvxopt/PKGBUILD
dll name changed -> rebuild:
```
gstreamer
inkscape
mathgl
ngraph-gtk
python-cvxopt
```
> gsl: update to 2.7.1

- mingw-w64-librsvg/0001-fix-stdout-to-file.patch
- mingw-w64-librsvg/0002-win32-libs.patch
- mingw-w64-librsvg/PKGBUILD
> librsvg: Fix redirecting stdout to file

- mingw-w64-winpty/PKGBUILD
- mingw-w64-winpty/winpty-0.4.3-mingw-fix.patch
need this for `python-pywinpty`
> new package: winpty

- mingw-w64-tbb/001-fix-build-with-mingw.patch
- mingw-w64-tbb/002-do-not-copy-lib.patch
- mingw-w64-tbb/003-fix-win32-defs.patch
- mingw-w64-tbb/PKGBUILD
Arch Linux package : https://archlinux.org/packages/testing/x86_64/tbb/
> [new-package] tbb 2021.4.0

- mingw-w64-pango/533.patch
- mingw-w64-pango/PKGBUILD
See https://gitlab.gnome.org/GNOME/pango/-/merge_requests/533
I could have excluded the new test 🙂
> Pango: add patch

- mingw-w64-ncurses/003-restore-static-builds-without-macro.patch
- mingw-w64-ncurses/PKGBUILD
- mingw-w64-ncurses/ncurses-6.3-pkgconfig.patch
> ncurses: fixes

- mingw-w64-libpng/PKGBUILD
Can confirm this builds correctly on my arm64 device 👍🏼
> libpng: enable for clangarm64

- mingw-w64-glib2/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10211
> glib2: Fix linking with static library

- mingw-w64-qt5-webchannel/PKGBUILD
> qt5-webchannel: move to KDE fork

- mingw-w64-grpc/0001-abseil-Fix-compiler-warnings.patch
- mingw-w64-grpc/0003-abseil-Include-pthread-header.patch
- mingw-w64-grpc/PKGBUILD
* Rebase abseil patches.
* Update abseil version to 20211102.0.
* Remove automake and autoconf from makedepends.
> grpc: update to 1.43.0

- mingw-w64-gdl/PKGBUILD
> gdl: update to 3.40.0

- mingw-w64-nana/010-thread.patch
- mingw-w64-nana/PKGBUILD
clang says this boost stuff is ambiguous. Just remove it.
Cleaned up the PKGBUILD. Switched to Ninja for faster compilation.
> nana: fix compilation with clang

- mingw-w64-scdoc/PKGBUILD
- mingw-w64-vala-language-server/PKGBUILD
> scdoc: Add package for vala-language-server

- mingw-w64-python-lsp-server/PKGBUILD
- mingw-w64-python-spyder/PKGBUILD
- mingw-w64-python-spyder/spyder-requirements-fix.patch
python-lsp-server: update to 1.3.3
> python-spyder: update to 5.2.1

- mingw-w64-geany/0003-export.patch
- mingw-w64-geany/PKGBUILD
Add patch to fix compilation with clang.
> geany: update to 1.38.0

- mingw-w64-python-lief/PKGBUILD
- mingw-w64-python-lief/lief.patch
I depend on this package for the next version of cx_Freeze.
> LIEF 0.11.5 - new package

- mingw-w64-opencollada/010-fix-unordered.patch
- mingw-w64-opencollada/PKGBUILD
> opencollada: fix compilation with clang

- mingw-w64-gegl/PKGBUILD
> gegl: update to 0.4.34

- mingw-w64-sdcv/001-sdcv-0.5.3-fix-mingw-build.patch
- mingw-w64-sdcv/PKGBUILD
- updated test scripts for XDG under mingw
- stat -> stat64/stat32 for mingw ifdefs
- c++11 -> gnu++20
-  cleanup test dicts after tests run
> sdcv: new package

- mingw-w64-libcello-git/PKGBUILD
> libcello-git: update

- mingw-w64-hclient-git/PKGBUILD
> hclient-git: update

- mingw-w64-libass/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/8817. Please review.
> libass: Fix static library

- mingw-w64-cccl/PKGBUILD
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
> cccl: update to 1.2

- mingw-w64-gnutls/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10430
> gnutls: Fix static library

- mingw-w64-libmicrohttpd/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10429. Please Review.
> libmicrohttpd: Fix static library

- mingw-w64-wb32-dfu-updater_cli/PKGBUILD
Add wb32-dfu-updater_cli util.
> Add wb32-dfu-updater_cli util

- mingw-w64-libzip/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10483
> libzip: Fix zstd entry in pkgconfig file

- mingw-w64-pdf2djvu/001-cxx17-for-poppler.patch
- mingw-w64-pdf2djvu/PKGBUILD
> pdf2djvu: build with C++17

- mingw-w64-gflags/0001-fix-link-library.patch
- mingw-w64-gflags/0002-fix-static-libs.patch
- mingw-w64-gflags/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/7086. Please review.
> gflags: Fix linking library and static libs

- mingw-w64-gtest/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/5113. Please review.
> gtest: Add static library

- mingw-w64-hexchat/0001-meson-add-winpthread.patch
- mingw-w64-hexchat/0002-fix-plugin-search.patch
- mingw-w64-hexchat/0003-meson-remove-wbemcore.patch
- mingw-w64-hexchat/PKGBUILD
> hexchat: Add packages

- mingw-w64-inkscape/PKGBUILD
- mingw-w64-lib2geom/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10393
> lib2geom: Add package for Inkscape

- mingw-w64-autotools/PKGBUILD
- mingw-w64-libbacktrace/PKGBUILD
- mingw-w64-uhttpmock/PKGBUILD
needs staging to be done first
> Use autoconf-wrapper where needed

- mingw-w64-totem-pl-parser/002-meson-check-version-script.patch
- mingw-w64-totem-pl-parser/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/pull/10561
> totem-pl-parser: Fix clang build

- mingw-w64-ebook-tools/PKGBUILD
- mingw-w64-ebook-tools/crash-fix.patch
Fixes https://github.com/msys2/MINGW-packages/issues/10563
> ebook-tools: Add package

- mingw-w64-libxml2/0028-work-around-lxml-api-abuse.patch
- mingw-w64-libxml2/PKGBUILD
> libxml2: backport fix for lxml

- mingw-w64-vapoursynth/0003-no-registry-setup-py.patch
- mingw-w64-vapoursynth/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10528
> vapoursynth: use setup.py for building python extension

- mingw-w64-libxml2/0029-xml2-config-win-paths.patch
- mingw-w64-libxml2/PKGBUILD
- mingw-w64-libxslt/0010-xslt-config-win-paths.patch
- mingw-w64-libxslt/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10577
> libxml2: Fix xml2-config to return Windows style path

- mingw-w64-poco/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10594
> poco: Build static libraries

- mingw-w64-portaudio/0002-cmake-add-cpp-binding.patch
- mingw-w64-portaudio/CMakeLists.txt
- mingw-w64-portaudio/PKGBUILD
- mingw-w64-portaudio/portaudiocpp.pc.in
Fixes https://github.com/msys2/MINGW-packages/pull/10604
> portaudio: Build C++ binding with CMake

- mingw-w64-amf-headers/0001-prevent-some-redefinition.patch
- mingw-w64-amf-headers/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10618
> amf-headers: Fix some redefinition errors

- mingw-w64-gtk3/PKGBUILD
> gtk3: Update

- mingw-w64-geoipupdate/001-relocate.patch
- mingw-w64-geoipupdate/PKGBUILD
So we can drop the unsupported geoip2-database
> Add geoipupdate package

- mingw-w64-libusb/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/8178
> libusb: update to 1.0.25

- mingw-w64-ffmpeg/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10637. Please review.
> ffmpeg: Add svt-av1 for x86_64

- mingw-w64-python-installer/PKGBUILD
> Add python-installer package

- mingw-w64-opencl-headers/PKGBUILD
- mingw-w64-opencl-icd/PKGBUILD
Update PKGBUILD
Update PKGBUILD
> opencl: update 2022.01.04

- mingw-w64-ffmpeg/PKGBUILD
As requested here https://github.com/msys2/MINGW-packages/issues/10637
> ffmpeg: Add zimg dependency

- mingw-w64-python-ford/PKGBUILD
- mingw-w64-python-markdown-include/PKGBUILD
- mingw-w64-python-md-environ/PKGBUILD
- add package for [python-ford](https://github.com/Fortran-FOSS-Programmers/ford)
- add dependency [python-markdown-include](https://github.com/cmacmackin/markdown-include/)
- add dependency [python-md-environ](https://github.com/cmacmackin/md-environ/)
> Add package for Ford documentation generator

- mingw-w64-xa65/0001-make-fix-predefined-variables.patch
- mingw-w64-xa65/PKGBUILD
Remove predefined CC variable for clang /cc @drfiemost
> xa65: Fix build with clang

- mingw-w64-ffmpeg/PKGBUILD
> FFmpeg: Add rav1e dependency

- mingw-w64-tiledb/0001-spdlog-external-fmt-library.patch
- mingw-w64-tiledb/PKGBUILD
> tiledb: Update to 2.6.2

- mingw-w64-sundials/PKGBUILD
> sundials: Update to 6.1.0

- mingw-w64-fontforge/PKGBUILD
- mingw-w64-fontforge/fontforge-doc-no-warn-error.patch
> fontforge: Add package

- mingw-w64-vmaf/PKGBUILD
> vmaf: Add package

- mingw-w64-sundials/PKGBUILD
It looks like they fixed the bug in SUNDIALSConfig.cmake, so I've removed the fix for that.
> sundials: Update to 6.1.1

- mingw-w64-libarchive/PKGBUILD
- mingw-w64-libb2/PKGBUILD
libarchive - update to latest version, depend upon libb2 for blake hashes
libb2 - new package
> updates to libarchive

- mingw-w64-flashrom/PKGBUILD
Initial pkgbuild for flashrom.
See discussion here:
https://github.com/msys2/MINGW-packages/issues/10405
> initial recipe for flashrom

- mingw-w64-glbinding/PKGBUILD
- mingw-w64-libgdiplus/PKGBUILD
- mingw-w64-mesa/PKGBUILD
- mingw-w64-pupnp/PKGBUILD
- mingw-w64-unixodbc/PKGBUILD
> Fix conflicts with mingw-w64

- mingw-w64-freerdp/PKGBUILD
> freerdp: add missing dependency

- mingw-w64-ois/PKGBUILD
also remove DXSDK_DIR, builds without it
> ois: build with ninja

- mingw-w64-openal/PKGBUILD
remove references to ${MINGW_PREFIX}/${MINGW_CHOST}
> openal: rebuild

- mingw-w64-assimp/PKGBUILD
Fix ${MINGW_PREFIX}/${MINGW_CHOST} path to the new location
> assimp: rebuild

- mingw-w64-gl2ps/PKGBUILD
Fix reference to libm
Port to ninja while at it
> gl2ps: rebuild

- mingw-w64-flashrom/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/pull/10773
> flashrom: Fix version reporting with upstream source tarball

- mingw-w64-python-llvmlite/PKGBUILD
- mingw-w64-python-llvmlite/llvm-12.0.patch
- mingw-w64-python-numba/PKGBUILD
> Update numba and llvmlite

- mingw-w64-librsvg/PKGBUILD
> librsvg: update to 2.52.6

- mingw-w64-expat/PKGBUILD
> expat: update to 2.4.5

- mingw-w64-pyside6/001-fix-building-on-mingw.patch
- mingw-w64-pyside6/PKGBUILD
- mingw-w64-shiboken6/001-fix-building-on-mingw.patch
- mingw-w64-shiboken6/PKGBUILD
> [new-package] pyside6 6.2.3

- mingw-w64-libsoup3/PKGBUILD
> libsoup3: Add package for gst-plugins-good

- .github/workflows/main.yml
Fails when there is nothing to run
> [CI] Fix check job

- mingw-w64-expat/PKGBUILD
> expat: update to 2.4.6

- mingw-w64-jack2/0001-wscript-remove-hardcoded-includedir.patch
- mingw-w64-jack2/0002-fix-pkgconfig-file.patch
- mingw-w64-jack2/0003-relocate-plugins-libdir.patch
- mingw-w64-jack2/0004-relocate-jackd-path.patch
- mingw-w64-jack2/PKGBUILD
- mingw-w64-qjackctl/0001-cmake-fix-install-dir.patch
- mingw-w64-qjackctl/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/6117
> jack2: Add package

- mingw-w64-moab/0001-no-fortran.patch
- mingw-w64-moab/PKGBUILD
Also add necessary runtime dependencies.
> moab: enable clang

- mingw-w64-python-colour-science/PKGBUILD
- mingw-w64-python-imageio/PKGBUILD
> python-colour-science: update to 0.4.0

- mingw-w64-ag/0010-clang-getpagesize.patch
- mingw-w64-ag/PKGBUILD
> ag: fix compilation with clang

- mingw-w64-libjxl/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/9670
> libjxl: Add package

- mingw-w64-lensfun/PKGBUILD
> lensfun: build Release

- mingw-w64-glsl-optimizer-git/PKGBUILD
- mingw-w64-hlsl2glsl-git/PKGBUILD
set epoch since this decreases the revision count
> hlsl2glsl, glsl-optimizer: use git apply

- mingw-w64-python-pyzmq/001-mingw-python.patch
- mingw-w64-python-pyzmq/002-mingw-win-compat.patch
- mingw-w64-python-pyzmq/PKGBUILD
> python-pyzmq: Update to 22.3.0

- mingw-w64-expat/PKGBUILD
> expat: update to 2.4.7

- .ci/ci-build.sh
- .github/workflows/main.yml
> Make clang jobs in CI fatal

- mingw-w64-qt5-tools/PKGBUILD
> qt5-tools: fix commit hash

- mingw-w64-hugo/PKGBUILD
> hugo: Add package

- mingw-w64-python-pipenv/PKGBUILD
- mingw-w64-python-virtualenv-clone/PKGBUILD
Add pipenv, and its depended package virtualenv-clone
> Pipenv: Add package

- mingw-w64-unrar/0001-fix-makefile.patch
- mingw-w64-unrar/0002-fix-redefinition.patch
- mingw-w64-unrar/0003-workaround-comsupp-library.patch
- mingw-w64-unrar/PKGBUILD
> unrar: Add package

- mingw-w64-cmake/0006-Fix-find-wxwidgets.patch
- mingw-w64-cmake/PKGBUILD
- mingw-w64-wxWidgets/001-wxWidgets-3.0.2-relocate-prefix-in-bin-wx-config.patch
- mingw-w64-wxWidgets/PKGBUILD
> cmake: Fix Finding wxWidgets

- mingw-w64-libbluray/PKGBUILD
> Fix libbluray.a link against libxml2.dll.a

- mingw-w64-bmake/0006-ffs.patch
- mingw-w64-bmake/PKGBUILD
> bmake: fix clang compilation

- mingw-w64-SDL/PKGBUILD
This fixes clangarm64 build
Please review @jeremyd2019 @kmilos
> sdl: build from git

- .ci/ci-build.sh
This ensure comparing data with the one from official databases (unless it is from staging!)
> CI: Fix listing diff

- mingw-w64-python3.10/0132-Build-venvlauncher.exe-from-PC-launcher.c.patch
- mingw-w64-python3.10/0133-PC-launcher.c-Use-function-available-in-original-msv.patch
- mingw-w64-python3.10/0134-Add-a-test-for-checking-the-new-launchers.patch
- mingw-w64-python3.10/PKGBUILD
add patches from https://github.com/msys2-contrib/cpython-mingw/pull/82
> python3.10: update patches

- mingw-w64-pango/PKGBUILD
> pango: split docs to a separate package

- mingw-w64-rclone/PKGBUILD
This creates base rclone executable package as well as its embeddable build in form of dynamic library.
> New package: rclone

- mingw-w64-wb32-dfu-updater_cli/PKGBUILD
Update wb32-dfu-updater_cli version to 1.0.0.
> Version update

- mingw-w64-gegl/PKGBUILD
Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>
> mingw-w64-gegl Prefer pkgconf

- mingw-w64-pdal/PKGBUILD
I couldn't package 2.3.0 because it fails to build.
I will update it to the final release once It's released, but It is needed to build VTK 9.1
> pdal: 2.4.0 (new-package)

- mingw-w64-sqlite3/PKGBUILD
This reduces package size in half.
Please review. @podsvirov
> sqlite3: split docs to a separate package

- mingw-w64-xa65/PKGBUILD
> xa65: update to 2.3.13

- mingw-w64-aalib/0001-Apply-patch-for-MSYS2.patch
- mingw-w64-aalib/0002-configure-src-tweak-Windows-link-flags.patch
- mingw-w64-aalib/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11115
> aalib: Add package for gimp

- mingw-w64-expat/PKGBUILD
> expat: update to 2.4.8

- mingw-w64-zlib/01-zlib-1.2.11-1-buildsys.mingw.patch
- mingw-w64-zlib/04-fix-largefile-support.patch
- mingw-w64-zlib/PKGBUILD
> zlib: update to 1.2.12

- mingw-w64-appstream-glib/PKGBUILD
- mingw-w64-cantarell-fonts/PKGBUILD
- mingw-w64-gsettings-desktop-schemas/PKGBUILD
- mingw-w64-gst-plugins-good/PKGBUILD
- mingw-w64-libvirt/003-docs-fix-template-matching-in-page-xsl.patch
- mingw-w64-libvirt/PKGBUILD
- mingw-w64-virt-viewer/003-fix-arm64-link.patch
- mingw-w64-virt-viewer/PKGBUILD
- mingw-w64-yajl/02-fix-tests.patch
- mingw-w64-yajl/PKGBUILD
Contributes to https://github.com/msys2/MINGW-packages/pull/11143
> Package updates in preparation for spice clangarm64

- mingw-w64-libarchive/0002-fix-openssl-library-check.patch
- mingw-w64-libarchive/PKGBUILD
Please review. Fixes https://github.com/msys2/MINGW-packages/issues/11157
> libarchive: Fix openssl library check

- mingw-w64-glib2/0003-gspawn-backport.patch
- mingw-w64-glib2/PKGBUILD
> glib: backport fix for gspawn regression

- mingw-w64-rav1e/PKGBUILD
> rav1e: Use cargo.lock from upstream

- mingw-w64-gtk4/1.patch
- mingw-w64-gtk4/PKGBUILD
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4608
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4627
> GTK4: Backport patches

- mingw-w64-ghdl/PKGBUILD
- mingw-w64-icestorm/PKGBUILD
- mingw-w64-iverilog/PKGBUILD
Bumping a bunch of EDA tools...
> EDA tools: icestorm, iverilog and ghdl

- mingw-w64-allegro/PKGBUILD
Please review. Fixes https://github.com/msys2/MINGW-packages/issues/11438
> allegro: Fix dependencies

- mingw-w64-prjtrellis/PKGBUILD
> prjtrellis: 1.0.r1033.3ae21cf

- mingw-w64-python-labelme/PKGBUILD
- mingw-w64-python-matplotlib/PKGBUILD
- mingw-w64-python-natsort/PKGBUILD
`matplotlib` is already at `3.3.4>=3.3`
> python-labelme: update to 5.0.1

- mingw-w64-python-jsonschema/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11463
> python-jsonschema: disable stripping

- mingw-w64-heimdall/0001-fix-clang.patch
- mingw-w64-heimdall/PKGBUILD
> heimdall: Fix clang build

- mingw-w64-pango/PKGBUILD
> pango: backports

- mingw-w64-rtaudio/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11471
> rtaudio: Add package

- mingw-w64-lldb-mi/PKGBUILD
Please review. Fixes https://github.com/msys2/MINGW-packages/issues/11479
> lldb-mi: Add package

- mingw-w64-python-configargparse/PKGBUILD
- mingw-w64-python-fprettify/PKGBUILD
- add formatter [fprettify](https://github.com/pseewald/fprettify)
- add dependency [ConfigArgParse](https://github.com/bw2/configargparse)
> Add package for fprettify

- mingw-w64-zimg/PKGBUILD
> zimg: update to 3.0.4

- mingw-w64-libarchive/PKGBUILD
> libarchive: Fix pkgconfig file for static linking

- mingw-w64-srt/PKGBUILD
@msink Please review. Fixes https://github.com/msys2/MINGW-packages/issues/11513
> srt: Fix name conflict with md5 functions

- mingw-w64-x264/0003-pkgconfig-add-Cflags-private.patch
- mingw-w64-x264/PKGBUILD
> x264: Add Cflags.private in pkgconfig file

- mingw-w64-svt-av1/0001-pkgconfig-add-Cflags-private.patch
- mingw-w64-svt-av1/PKGBUILD
> svt-av1: Build static libraries

- mingw-w64-raylib/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11565
> raylib: Add package

- mingw-w64-python-fastjsonschema/PKGBUILD
- mingw-w64-python-jupyter-nbformat/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11568
> python-fastjsonschema: Add package for python-jupyter-nbformat

- mingw-w64-python/PKGBUILD
- mingw-w64-python3.10/PKGBUILD
> python: rebuild against ncurses shared lib

- mingw-w64-kicad-doc/PKGBUILD
Please merge this and kicad: Update to 5.1.12 #11512
Tim S.
> kicad-doc: Update to 5.1.12

- mingw-w64-sundials/PKGBUILD
> sundials: upgrade to 6.2.0

- mingw-w64-texlive-core/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/9418
> texlive: fix `context.exe` and related launchers

- mingw-w64-libclc/0001-cmake-copy-instead-symlink.patch
- mingw-w64-libclc/PKGBUILD
- mingw-w64-spirv-llvm-translator/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11600
> libclc: Add package

- mingw-w64-clang/PKGBUILD
> clang: Update to 14.0.3

- mingw-w64-SDL2_ttf/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11644
> SDL2_ttf: Fix pkgconfig file for static linking

- mingw-w64-advancecomp/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11649
> advancecomp: Add package

- mingw-w64-python-argcomplete/PKGBUILD
This package is required by `python-milc`, it works but not out of the box: https://github.com/kislyuk/argcomplete#git-bash-support
> python-argcomplete: new package

- mingw-w64-ngspice/PKGBUILD
> ngspice: update to 36

- mingw-w64-openshadinglanguage/PKGBUILD
- mingw-w64-openshadinglanguage/llvm14.patch
Fixes https://github.com/msys2/MINGW-packages/issues/11096 @jeremyd2019 @revelator
> openshadinglanguage: update to 1.11.17.0

- mingw-w64-rav1e/PKGBUILD
Currently says `prefix=/usr/local`
> rav1e: fix .pc file

- mingw-w64-fd/PKGBUILD
> fd: new package

- mingw-w64-libfreexl/PKGBUILD
Try to handle part of failing https://github.com/msys2/MINGW-packages/pull/11614
> libfreexl: reconfigure to enable clangarm64

- mingw-w64-libjxl/0001-cmake-fix-plugin-install.patch
- mingw-w64-libjxl/0002-pkgconfig-add-Cflags-private.patch
- mingw-w64-libjxl/0003-cmake-remove-static-suffix.patch
- mingw-w64-libjxl/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11697
> libjxl: Enable gimp and gdk-pixbuf2 plugins

- mingw-w64-bottom/PKGBUILD
The hotkey cannot work in mintty. But can work in conhost.
> bottom: new package

- mingw-w64-junitparser/PKGBUILD
Used in conjunction with google-test and other unit test frameworks that output in junit form
> junitparser: add new package

- mingw-w64-gnutls/PKGBUILD
this time without any weak symbol breakage
#11743
> gnutls: Update to 3.7.6 (v2)

- mingw-w64-keystone/0003-python-load-dll-from-prefix.patch
- mingw-w64-keystone/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11742
> keystone: Build python module

- mingw-w64-dsdp/PKGBUILD
Might lead to better performance for some operations.
> dsdp: link against OpenBLAS also in CLANG* environments

- mingw-w64-python-soundfile/0001-fix-libsndfile-dll.patch
- mingw-w64-python-soundfile/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11780
> python-soundfile: Fix libsndfile dll

- mingw-w64-gdu/PKGBUILD
`go test` seem cannot pass in windows, but the binary file compiled is same as 
the release of the author.
> gdu: new package

- mingw-w64-wxWidgets3.1/PKGBUILD
Use disable-permissive and use "build-${MSYSTEM}"
instead of "build-${CARCH}". And, change "mv" to "cp"
with "rm".
> wxWidgets3.1: Update to version 3.1.7; and,

- mingw-w64-libxml2/PKGBUILD
See https://github.com/msys2/MINGW-packages/issues/10515#issuecomment-1149519926
> Python byte compile - part 3

- mingw-w64-python-setuptools/PKGBUILD
this makes bootstrapping too complicated
> setuptools: revert switch to PEP517

- mingw-w64-python-tomli/PKGBUILD
- mingw-w64-python-wheel/PKGBUILD
- mingw-w64-python-wheel/install_wheel.py
In case of wheel the launcher is missing when we just unpack,
so add a bootstrap flag which we can turn off once everything
is built.
> Add a bootstrap flag to tomli and wheel

- mingw-w64-freeglut/004-pkg-config.patch
- mingw-w64-freeglut/PKGBUILD
> freeglut: fix static flags in .pc file

- mingw-w64-opencolorio/010-openimageio-cmake.patch
- mingw-w64-opencolorio/PKGBUILD
> opencolorio: fix linking issues

- mingw-w64-pdal/0001-fileutils.patch
- mingw-w64-pdal/PKGBUILD
Also add a patch that fixes issues with function prototypes that don't match. See this existing report upstream: https://github.com/PDAL/PDAL/pull/3778
> pdal: update to 2.4.2

- mingw-w64-armadillo/PKGBUILD
Minor overhaul of the build rules to make them more similar to the template.
> armadillo: update to 11.2.0

- mingw-w64-libheif/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11869
> libheif: Fix issue with dav1d decoding

- mingw-w64-sip/PKGBUILD
> sip: depends on setuptools

- mingw-w64-libexodus/PKGBUILD
- mingw-w64-libexodus/cmake-fix.patch
cmake complains that it gets too many arguments for if, so quote.
also add gfortran
> libexodus: try to fix the build

- mingw-w64-python-installer/001-launcher-relative.patch
- mingw-w64-python-installer/103.patch
- mingw-w64-python-installer/PKGBUILD
the prefix PR was rebased, so the patch here was just refreshed from there.
> python-installer: Update to 0.5.1

- mingw-w64-verilator/0001-src-bisonpre-specify-utf-8-encoding.patch
- mingw-w64-verilator/PKGBUILD
- https://github.com/verilator/verilator-announce/issues/54
- https://github.com/verilator/verilator/pull/3471
> verilator: update to 4.224

- mingw-w64-speex/PKGBUILD
- mingw-w64-speexdsp/PKGBUILD
move to git archives since there is no release tarball
> speex: Update to 1.2.1

- mingw-w64-ripgrep/PKGBUILD
> ripgrep: update to 13.0.0

- mingw-w64-osgocean-git/004-fftw3-no-version-suffix.patch
- mingw-w64-osgocean-git/PKGBUILD
Pin to a commit.
Fix detecting FFTW library.
Use Ninja generator.
Depends on #11919.
> osgocean: update to r164

- mingw-w64-scrcpy/PKGBUILD
Refer <https://github.com/Genymobile/scrcpy/blob/master/BUILD.md>
> scrcpy: new package

- mingw-w64-texlive-bin/PKGBUILD
Fixes https://github.com/msys2/msys2-texlive/issues/17
> WIP: texlive-bin: enable aleph engine

- mingw-w64-lua/PKGBUILD
> lua: Update to 5.4.4

- mingw-w64-lua-luarocks/0001-luarocks_msys2_mingw_w64.patch
- mingw-w64-lua-luarocks/PKGBUILD
Update Luarocks to version 3.9.0
> luarocks: Update to 3.9.0

- mingw-w64-isl/PKGBUILD
- update url
- enable shared library
> isl: update to 0.25

- mingw-w64-libgphoto2/PKGBUILD
Sorry @lazka I missed this one, can you please fast-track?
> libgphoto2: fix post-install

- mingw-w64-armadillo/0003-build-hdf5-wrappers.patch
- mingw-w64-armadillo/PKGBUILD
Probably an accidental change upstream.
Fixes #12019.
> armadillo: build HDF5 wrappers

- mingw-w64-babl/002-meson-lower-case.patch
- mingw-w64-babl/PKGBUILD
Also fix segmentation fault on i686.
> babl: update to 0.1.92

- mingw-w64-youtube-dl/PKGBUILD
Closes https://github.com/msys2/MSYS2-packages/pull/2983
> youtube-dl: fix bash completion

- mingw-w64-minidump-stackwalk/PKGBUILD
A maintained alternative to minidump_stackwalk from breakpad
> Add minidump-stackwalk

- mingw-w64-github-cli/PKGBUILD
See https://github.com/cli/cli/releases/tag/v2.14.3
> gh: upgrade to v2.14.3

- mingw-w64-lcov/001-mingw-lcov1.12-handle-equals-signs.patch
- mingw-w64-lcov/002-mingw-lcov1.12-fix-undef-behaviour.patch
- mingw-w64-lcov/003-mingw-lcov-win32.patch
- mingw-w64-lcov/PKGBUILD
restoring it, now using MINGW_PREFIX in perl interpreter
> Update lcov to 1.16

- mingw-w64-spirv-llvm-translator/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/12306
> spirv-llvm-translator: Add static library

- mingw-w64-ninja/PKGBUILD
- mingw-w64-ninja/obey-term-envvar.patch
... such as one-line progress messages, color, etc.
> ninja: use $TERM to decide when to use fancy output

- mingw-w64-libnatpmp/0001-shared-lib-and-install.patch
- mingw-w64-libnatpmp/PKGBUILD
Apparently natpmp.h includes this file too...
> libnatpmp: add missing header

- mingw-w64-python-spyder/PKGBUILD
Because I can't launch spyder without this dependencies
> spyder: More dependencies

- mingw-w64-assimp/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/11959
> assimp: Build with RelWithDebInfo build type

- mingw-w64-openvdb/PKGBUILD
All the patches were merged in https://github.com/AcademySoftwareFoundation/openvdb/pull/1342
> openvdb: update to 9.1.0

- mingw-w64-libpanel/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/12432
> libpanel: Add package

- mingw-w64-python/PKGBUILD
Rebuild python to fix issue [#11733](https://github.com/msys2/MINGW-packages/issues/11733)
> Rebuild python to fix issue #11733

- mingw-w64-codelite/017-unnest-StringHashOptionalCase-and-StringCompareOptio.patch
- mingw-w64-codelite/PKGBUILD
And, add patch file to fix compiler errors.
> codelite: Update to use new wxWidgets 3.0 split packages

- mingw-w64-python-bottle/PKGBUILD
- mingw-w64-python-conan/0001-Loosened-node-semver-version-requirement.patch
- mingw-w64-python-conan/PKGBUILD
- mingw-w64-python-node-semver/PKGBUILD
- mingw-w64-python-patch-ng/PKGBUILD
- mingw-w64-python-pluginbase/PKGBUILD
[Conan](https://conan.io/) is a popular package manager for C/C++ applications written in Python. This PR adds support for Conan and its dependencies.
> Added packages for Conan and dependencies

- mingw-w64-opencore-amr/PKGBUILD
> opencore-amr: Udpate to 0.1.6

- mingw-w64-libclc/PKGBUILD
Building this extra because there were build errors last time.
> libclc: Update to 14.0.6

- mingw-w64-python-conan/PKGBUILD
> conan: stopped build machine python path leaking into installation

- mingw-w64-ogre3d/021-aarch64.patch
- mingw-w64-ogre3d/PKGBUILD
> ogre3d: Add aarch64 support

- mingw-w64-opencv/0018-aarch64-fp16-mingw.patch
- mingw-w64-opencv/PKGBUILD
> opencv: Add aarch64 support

- mingw-w64-darktable/002-aarch64-mingw.patch
- mingw-w64-darktable/PKGBUILD
It has been a long road!
Depends on #12525
> darktable: Add aarch64 support

- mingw-w64-gdk-pixbuf2/0004-build-all-loaders-plus-gdi.patch
- mingw-w64-gdk-pixbuf2/PKGBUILD
> gdk-pixbuf2: Update to 2.42.9

- mingw-w64-lokalize/0001-lokalize-22.04.3-disable-doc.patch
- mingw-w64-lokalize/0002-lokalize-22.04.3-fix-cast.patch
- mingw-w64-lokalize/PKGBUILD
Disabled documentation build because:
```
kf.doctools.core: Error: Could not find kdoctools catalogs
```
like in #10620
> lokalize: New package

- mingw-w64-qt5-activeqt/PKGBUILD
- mingw-w64-qt5-imageformats/PKGBUILD
- mingw-w64-qt5-multimedia/PKGBUILD
- mingw-w64-qt5-pkgs/PKGBUILD
- mingw-w64-qt5-svg/PKGBUILD
- mingw-w64-qt5-tools/PKGBUILD
- mingw-w64-qt5-translations/PKGBUILD
> qt5: update to 5.15.5 - Part1

- mingw-w64-argon2/PKGBUILD
- mingw-w64-dcadec/PKGBUILD
- mingw-w64-http-parser/PKGBUILD
- mingw-w64-libxslt/PKGBUILD
- mingw-w64-lua51/PKGBUILD
- mingw-w64-lv2/PKGBUILD
- mingw-w64-odt2txt/PKGBUILD
- mingw-w64-pngquant/PKGBUILD
- mingw-w64-rtmpdump-git/PKGBUILD
- mingw-w64-tolua/PKGBUILD
> Remove hardcoded CC variable

- mingw-w64-lensfun/PKGBUILD
Upstream missed backporting this
> lensfun: handle uncaught exception

- mingw-w64-v8/0001-add-mingw-toolchain.patch
- mingw-w64-v8/PKGBUILD
try fixing https://github.com/msys2/MINGW-packages/issues/12568
> v8: try fixing build

- mingw-w64-podman/PKGBUILD
This provides a podman and docker command, + man pages and auto complete
and runs docker containers via WSL2
It only builds for 64bit here
> Add podman

- mingw-w64-python-qmk/PKGBUILD
<https://github.com/qmk/qmk_cli/releases/tag/1.1.1>
> Bump python-qmk to 1.1.1

- mingw-w64-osslsigncode/0001-fix-install-destination.patch
- mingw-w64-osslsigncode/PKGBUILD
Whivh is the recommended path to install bash completion?
> osslsigncode: update to 2.5

- mingw-w64-libimagequant2/PKGBUILD
> Add libimagequant2 for clang32 and clangarm64

- mingw-w64-hunspell/PKGBUILD
This updates hunspell to 1.7.1.
> hunspell: update to 1.7.1

- mingw-w64-granite7/PKGBUILD
see https://archlinux.org/todo/granite-70/
> [new-package] granite 7.0.0

- mingw-w64-i2pd/0001-i2pd-makefile.patch
- mingw-w64-i2pd/PKGBUILD
* Updated i2pd package to version 2.43.0
* Updated Makefiles patch file
> i2pd: update to 2.43.0

- mingw-w64-yuview/PKGBUILD
> [new-package] yuview 2.13

- mingw-w64-libatomic_ops/PKGBUILD
This updates libatomic_ops to version 7.6.14.
> libatomic_ops: update to 7.6.14

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/package_request.yml
- .github/ISSUE_TEMPLATE/update_request.yml
I think we need more steps to verify in "bug report".
> Add issue templates

- mingw-w64-kinit-qt5/PKGBUILD
- mingw-w64-kjs-qt5/PKGBUILD
- mingw-w64-plasma-framework-qt5/PKGBUILD
`kdoctools` fails to run.
see #10620
> kde-frameworks: update to 5.97.0 - Part3

- mingw-w64-kimageformats-qt5/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/12880
> kimageformats-qt5: Enable libjxl plugin

- mingw-w64-libheif/PKGBUILD
Note: Removed patches that already present in new release.
> libheif: Update to 1.13.0

- mingw-w64-cairo/0001-Fix-scaled_glyph-hash-lookup-on-Win64.patch
- mingw-w64-cairo/PKGBUILD
See https://gitlab.freedesktop.org/cairo/cairo/-/issues/586
Not sure if we want to point to a newer commit instead. Let me know!
> Cairo: Backport patch to fix a memory leak

- mingw-w64-chafa/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/12968
> chafa: Add package

- mingw-w64-onefetch/PKGBUILD
> onefetch: Add package

- mingw-w64-libwebp/0001-mingw-cmake-output.patch
- mingw-w64-libwebp/PKGBUILD
> libwebp: switch to CMake

- mingw-w64-lokalize/PKGBUILD
```shell
==> Verifying source file signatures with gpg...
lokalize-22.08.1.tar.xz ... FAILED (unknown public key BB463350D6EF31EF)
==> ERROR: One or more PGP signatures could not be verified!
```
@Biswa96 can you solve this?
> lokalize: Update to 22.08.1

- mingw-w64-sed/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/12996
> sed: update to 4.8

- mingw-w64-mesa/1001-gallivm-move-to-new-pass-manager-to-handle-coroutine.patch
- mingw-w64-mesa/PKGBUILD
backport some required build fixes from upstream
> mesa: rebuild against llvm-15

- mingw-w64-spirv-llvm-translator/PKGBUILD
switch to the llvm 15 git branch
> spirv-llvm-translator: build against llvm15

- mingw-w64-python-qtpy/001-restore-qtwebkit-support.patch
- mingw-w64-python-qtpy/PKGBUILD
@podsvirov could you test this.
> qtpy: restore qtwebkit support

- mingw-w64-python-cfgv/PKGBUILD
- mingw-w64-python-identify/PKGBUILD
- mingw-w64-python-nodeenv/PKGBUILD
- mingw-w64-python-pre-commit/PKGBUILD
> add python-pre-commit

- mingw-w64-highfive/PKGBUILD
> highfive: Fix installation

- mingw-w64-clang/0011-List-memrchr-as-unavailable-on-Windows.patch
- mingw-w64-clang/PKGBUILD
Reported on Discord: https://discord.com/channels/792780131906617355/814785640667152404/1020919880083578922
> Fix memrchr issue with LLVM 15

- mingw-w64-gnucobol/PKGBUILD
- mingw-w64-gnucobol/cobenv.cmd
* separated pkgver and _realver
* use VPATH builds instead of copying the source directory for each arch
* updated cobenv.cmd matching newer GC versions (allowing to call a command directly)
> GnuCOBOL package update

- mingw-w64-libgusb/PKGBUILD
> libgusb: update to 0.4.0

- mingw-w64-python-bcrypt/001-disable-abi3.patch
- mingw-w64-python-bcrypt/PKGBUILD
> python-bcrypt: update to 4.0.0

- mingw-w64-qt6-multimedia/PKGBUILD
> qt6-multimedia: Enable ffmpeg

- mingw-w64-mdbook/PKGBUILD
> mdbook: New package

- mingw-w64-ruc/0002-ruc-2.4.3-gnu-install-dirs.patch
- mingw-w64-ruc/0003-ruc-2.4.3-libruc-prefix.patch
- mingw-w64-ruc/0004-ruc-2.4.3-codegen-env.patch
- mingw-w64-ruc/PKGBUILD
> ruc: New package

- mingw-w64-ruc-vm/0001-ruc-vm-1.2-gnu-install-dirs.patch
- mingw-w64-ruc-vm/0002-ruc-vm-1.2-libruc-vm-prefix.patch
- mingw-w64-ruc-vm/PKGBUILD
> ruc-vm: New package

- mingw-w64-chmlib/0001-chmlib-allow-ffs-win32.patch
- mingw-w64-chmlib/PKGBUILD
- mingw-w64-kdegraphics-mobipocket/PKGBUILD
- mingw-w64-khtml-qt5/PKGBUILD
- mingw-w64-libkexiv2/PKGBUILD
- mingw-w64-okular/PKGBUILD
Pwease, review this pull request 👶
> okular: Add package

- mingw-w64-arm-none-eabi-newlib/PKGBUILD
> arm-none-eabi-newlib: update to 4.2.0.20211231

- mingw-w64-libmysofa/002-fix-exports.patch
- mingw-w64-libmysofa/004-fix-dllexport-attribute.patch
- mingw-w64-libmysofa/PKGBUILD
This updates libmysofa to version 1.3.
> update libmysofa to 1.3

- mingw-w64-wasm-pack/PKGBUILD
> wasm-pack: New package

- mingw-w64-pkgconf/0001-pkgconf_pkg_parser_value_set-fix-code-path-ordering-.patch
- mingw-w64-pkgconf/PKGBUILD
There have been regressions/behaviour changes resulting in build errors.
Let's revert until we figure out more.
See https://github.com/msys2/MINGW-packages/issues/13390
> Revert pkgconf

- mingw-w64-kqtquickcharts/0001-kqtquickcharts-22.08.1-fix-prefix.patch
- mingw-w64-kqtquickcharts/PKGBUILD
> kqtquickcharts: New package

- mingw-w64-opus/PKGBUILD
> opus: don't link against libssp

- mingw-w64-ktouch/0001-ktouch-22.08.1-fix-x11.patch
- mingw-w64-ktouch/PKGBUILD
> ktouch: New package

- mingw-w64-cargo-local-registry/PKGBUILD
> cargo-local-registry: New package

- mingw-w64-imath/PKGBUILD
> imath: fix cmake-config files

- mingw-w64-libsndfile/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/13548
> libsndfile: Remove samplerate < SF_MAX_SAMPLERATE requirement

- mingw-w64-igraph/PKGBUILD
> igraph: update to 0.10.2

- mingw-w64-librsvg/PKGBUILD
> librsvg: Update to 2.55.1

- mingw-w64-leveldb/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/13659
> leveldb: Build shared library

- mingw-w64-flac/PKGBUILD
> flac: Update to 1.4.1

- mingw-w64-highs/PKGBUILD
Upstream doesn't support 32-bit platforms.
https://github.com/ERGO-Code/HiGHS/issues/769#issuecomment-1093837739
> highs: Add new package

- mingw-w64-kitemmodels-qt5/PKGBUILD
- mingw-w64-kitemmodels-qt5/remove-lib-prefix.patch
Resolve https://github.com/msys2/MINGW-packages/issues/13698
> fix qml plugin from kitemmodels installed to incorrect dir

- mingw-w64-arm-none-eabi-gcc/PKGBUILD
> arm-none-eabi-gcc: update to 12.2.0

- mingw-w64-oh-my-posh/PKGBUILD
A prompt theme engine for any shell. See also [**Home | Oh My Posh**](https://ohmyposh.dev/)
> New package recommend: oh-my-posh

- .ci/ci-check.py
- .github/workflows/main.yml
Successful job: https://github.com/msys2/MINGW-packages/actions/runs/3339632319/jobs/5528999265
> WIP: Try fixing the ci-check action

- mingw-w64-openblas/PKGBUILD
- mingw-w64-openblas/openblas.install
> openblas: build with openmp support

- mingw-w64-curl/0002-nghttp2-static.patch
- mingw-w64-curl/PKGBUILD
instead of reverting the commits causing it
> curl: backport build fix

- mingw-w64-plasma-framework-qt5/001-use-gzip-instead-7z.patch
- mingw-w64-plasma-framework-qt5/002-cmake-remove-lib-prefix.patch
- mingw-w64-plasma-framework-qt5/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/7393
> plasma-framework: Remove lib prefix from plugin name

- mingw-w64-onevpl-cpu/0001-disable-mingw-workaround.patch
- mingw-w64-onevpl-cpu/0002-bootstrap-fix-ffmpeg-command.patch
- mingw-w64-onevpl-cpu/0003-cmake-remove-unknown-options.patch
- mingw-w64-onevpl-cpu/0004-cmake-add-bcrypt-lib.patch
- mingw-w64-onevpl-cpu/PKGBUILD
- mingw-w64-onevpl/0001-fix-pkgconfig-file.patch
- mingw-w64-onevpl/0002-cmake-install-vars-sh.patch
- mingw-w64-onevpl/0003-cmake-fix-32bit-install.patch
- mingw-w64-onevpl/PKGBUILD
> onevpl: Add package

- mingw-w64-tbb/001-fix-using-TBB-with-Debug-build-type.patch
- mingw-w64-tbb/PKGBUILD
> tbb: Fix using tbb when defining TBB_USE_DEBUG

- mingw-w64-kirigami-addons-qt5/PKGBUILD
Resolve https://github.com/msys2/MINGW-packages/issues/13799
BTW, should I replace the "Maintainer" comment header to myself? If the answer is yes, then what's the policy to update the package? Do I need to follow any extra setup (e.g. email to notify outdated?) to maintain this package?
> kirigami-addons: New package

- mingw-w64-imagemagick/002-fix-unicode-filepath.patch
- mingw-w64-imagemagick/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/13658
> imagemagick: Enable unicode support in magick command

- mingw-w64-python-hunter/PKGBUILD
- mingw-w64-python-importlib-metadata/PKGBUILD
- mingw-w64-python-invoke/PKGBUILD
- mingw-w64-python-jupyter-nbviewer/PKGBUILD
- mingw-w64-python-openpyxl/PKGBUILD
- mingw-w64-python-py2exe/PKGBUILD
- mingw-w64-python-qmk/PKGBUILD
- mingw-w64-python-qstylizer/PKGBUILD
- mingw-w64-python-requests-unixsocket/PKGBUILD
> Remove python-pip from makedepends

- mingw-w64-python/PKGBUILD
See https://github.com/msys2/MINGW-packages/pull/13941
> python: build with --large-address-aware

- mingw-w64-python-pymupdf/0001-setup-add-mingw.patch
- mingw-w64-python-pymupdf/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/13940
> python-pymupdf: Add package

- mingw-w64-rust/0007-clang-subsystem.patch
- mingw-w64-rust/0011-disable-uac-for-installer.patch
- mingw-w64-rust/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/9091
> Build Rust in Clang32 subsystem

- mingw-w64-gdcm/0009-link-to-iconv.patch
- mingw-w64-gdcm/PKGBUILD
- mingw-w64-itk/PKGBUILD
> itk: Fix building

- mingw-w64-python-spyder/PKGBUILD
To launch `spyder` the #13955  will be useful too.
> python-spyder: Restore shebang line

- mingw-w64-mesa/008-fix-clang32-def-gen-part1.patch
- mingw-w64-mesa/009-fix-clang32-def-gen-part2.patch
- mingw-w64-mesa/010-fix-radv-build.patch
- mingw-w64-mesa/011-fix-clover-i686-build-part1.patch
- mingw-w64-mesa/012-fix-clover-i686-build-part2.patch
- mingw-w64-mesa/013-strip-clover-filename-prefix.patch
- mingw-w64-mesa/014-strip-clover-filename-suffix.patch
- mingw-w64-mesa/PKGBUILD
- Re-enabled build on clang32;
- re-enabled RADV build;
- enabled clover on i686.
Credit @lygstate  for patches
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19610
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19653
> mesa: Update to 22.2.3

- mingw-w64-gdb/PKGBUILD
- mingw-w64-readline/0001-sigwinch.patch
- mingw-w64-readline/0002-event-hook.patch
- mingw-w64-readline/0003-fd_set.patch
- mingw-w64-readline/PKGBUILD
Update patches and fix build issue on MinGW.
Also fix building gdb with readline 8.2.
> readline: update to 8.2-001

- mingw-w64-dcmtk/002-properly-detect-canonical-host.patch
- mingw-w64-dcmtk/PKGBUILD
- mingw-w64-openimageio/PKGBUILD
Fixes #14043 
Do we really need all those *_tests.exe ?
> dcmtk: fix clang32 build

- mingw-w64-cppwinrt/0001-cppwinrt-include-vector.patch
- mingw-w64-cppwinrt/0002-cppwinrt-patch-winmd.patch
- mingw-w64-cppwinrt/0003-winmd-include-utility.patch
- mingw-w64-cppwinrt/PKGBUILD
See https://github.com/mstorsjo/llvm-mingw/issues/307
> cppwinrt: Add package

- mingw-w64-abseil-cpp/0002-abseil-Remove-librt-library.patch
- mingw-w64-abseil-cpp/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/pull/11519
> abseil-cpp: Fix linker option in pkgconfig file

- mingw-w64-clang/PKGBUILD
https://discourse.llvm.org/t/llvm-15-0-5-release/66616
plus a backport:
https://github.com/llvm/llvm-project/issues/55023#issuecomment-1320967497
> llvm: Update to 15.0.5 + fix backport

- mingw-w64-emacs-pdf-tools-server/PKGBUILD
- Update package to 1.0.0
- Include licence and documentation files in package
> Emacs PDF Tools updates

- mingw-w64-pycairo/PKGBUILD
* spdx license
* update compileall call, newer python can create optimized pyc
> pycairo: Update to 1.23.0

- mingw-w64-gn/001-build-fixes.patch
- mingw-w64-gn/002-add-missing-header.patch
- mingw-w64-gn/PKGBUILD
preparing for v8 and qtwebengine..
> gn: new package

- mingw-w64-adol-c/PKGBUILD
also enable openmp for clangarm64 while at it.. let's see.
See https://github.com/msys2/MINGW-packages/issues/13783
> adol-c: use new openmp virtual package

- mingw-w64-gmic/PKGBUILD
> gmic: use omp metapackage

- mingw-w64-xz/PKGBUILD
> xz: update to 5.2.9

- mingw-w64-glib2/PKGBUILD
> glib2: Update to 2.74.3

- mingw-w64-cpr/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/14314
> cpr: Add package

- mingw-w64-xmlsec/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/4528
> xmlsec: Fix static library

- mingw-w64-tme/PKGBUILD
The Machine Emulator, or tme, is a program that provides a general- purpose framework for computer emulation.  The first machine that tme could emulate was the Sun 2/120, one of the first widely available Sun workstations. Other emulations include the Sun 3/150, SPARCstation 2, and UltraSPARC 1.
> tme: New package for The Machine Emulator 0.12rc9

- mingw-w64-blender/PKGBUILD
- mingw-w64-blender/blender-CLANGARM64.install
Sorry about this, hopefully third time's a charm!
> blender: add clangarm64 to mingw_arch

- mingw-w64-qt5-quickcontrols2/PKGBUILD
> qt5-quickcontrols2: rebuild

- mingw-w64-grep/PKGBUILD
gnulib detection is broken
Fixes #14472
> grep: force disable weak symbols

- mingw-w64-swi-prolog/02-unix-style-directory-structure.patch
- mingw-w64-swi-prolog/03-semweb-ntriples.patch
- mingw-w64-swi-prolog/04-semweb-turtle.patch
- mingw-w64-swi-prolog/PKGBUILD
> swipl: update to version 9.0.2

- mingw-w64-qt5-pkgs/0027-qt-5.7.0-qdbus-manager-quit.patch
- mingw-w64-qt5-pkgs/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10158
Fixes https://github.com/msys2/MINGW-packages/issues/13198
/cc @revelator @lb90
Credits goes to @naksyl who suggested the patch in the above mentioned issue 🤗
> qt5-base: Fix zombie processes due to qt dbus

- mingw-w64-libunibreak/PKGBUILD
New optional dep for libass, so give it a try
> Add libunibreak

- mingw-w64-SDL2/PKGBUILD
> SDL2: Update o 2.26.1

- mingw-w64-mpc/PKGBUILD
mpc.h:287:35: error: unknown type name 'FILE'
> mpc: backport fix for undefined FILE

- mingw-w64-gegl/PKGBUILD
Related to https://github.com/msys2/MINGW-packages/issues/13783
> gegl: use omp metapackage

- mingw-w64-openblas/PKGBUILD
Related to https://github.com/msys2/MINGW-packages/issues/13783
> openblas: use omp metapackage

- mingw-w64-python-click/PKGBUILD
> python-click: Add documentation

- mingw-w64-7zip/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/14637
> 7zip: Build 7z.dll

- mingw-w64-7zip/PKGBUILD
- mingw-w64-7zip/clang-arm-target-fixes.patch
Addresses https://github.com/msys2/MINGW-packages/pull/14639#issuecomment-1357848517
> 7zip: fix arm64 build

- mingw-w64-PKGBUILD-templates/PKGBUILD.meson-tarball.sh
Please review and feel free to merge.
> PKGBUILD-templates: Mention setup option with meson

- mingw-w64-skia/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/14585
> skia: Add headers file from modules

- mingw-w64-angleproject/004-add-missing-d3d11-macro.patch
- mingw-w64-angleproject/PKGBUILD
Fixes #14665 
- enable d3d11
- removes khr header
- fix license type
> angleproject: enable d3d11

- mingw-w64-python-jinja/PKGBUILD
> python-jinja: Add documentation

- mingw-w64-angleproject/002-buildflags-fixes.patch
- mingw-w64-angleproject/003-angle-src-fixes.patch
- mingw-w64-angleproject/004-add-missing-d3d11-macro.patch
- mingw-w64-angleproject/PKGBUILD
- update the version to trigger CI rebuild
- rebase some patches
> angleproject: version bump

- mingw-w64-dlfcn/PKGBUILD
- mingw-w64-ffmpeg/PKGBUILD
- mingw-w64-vid.stab/0002-disable-sse-on-arm.patch
- mingw-w64-vid.stab/PKGBUILD
Enable frei0r for ffmpeg on clang* as well since that seems to be available now.
> enable dlfcn and vid.stab on clangarm64

- mingw-w64-gmsh/0001-fix-link-lib-name.patch
- mingw-w64-gmsh/PKGBUILD
Also rebase patch that no longer applied.
> gmsh: update to 4.11.1

- mingw-w64-shfmt/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/14486
> shfmt: Add package

- mingw-w64-libpsl/PKGBUILD
> libpsl: build static and shared separately.

- mingw-w64-git-lfs/PKGBUILD
which breaks things, see
https://github.com/msys2/MINGW-packages/issues/15005
> git-lfs: revert upstream change

- mingw-w64-mold/001-support-mingw.patch
- mingw-w64-mold/PKGBUILD
> [new-package] mold 1.9.0

- mingw-w64-bzip3/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/15017
> bzip3: Add package

- mingw-w64-boost/PKGBUILD
See https://github.com/msys2/MINGW-packages/issues/15021
> boost: revert #14790

- mingw-w64-python-msgpack/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/15040
> python-msgpack: Fix building cython module

- mingw-w64-clang/PKGBUILD
- mingw-w64-flang/PKGBUILD
- mingw-w64-libc++/PKGBUILD
- mingw-w64-libclc/PKGBUILD
- mingw-w64-lldb/PKGBUILD
- mingw-w64-mlir/PKGBUILD
- mingw-w64-openmp/PKGBUILD
- mingw-w64-polly/PKGBUILD
hope the CI doesn't time out...
> llvm: Update to 15.0.7

- mingw-w64-vulkan-headers/PKGBUILD
- mingw-w64-vulkan-loader/PKGBUILD
https://trac.ffmpeg.org/ticket/10115
> vulkan-headers/loader: update to 1.3.238

- mingw-w64-zxing-cpp/PKGBUILD
- the library can do way more than decode QRCodes
- the project moved to a new home recently
> zxing-cpp: update description and source URL

- mingw-w64-libva/0001-add-lib-prefix-def.patch
- mingw-w64-libva/PKGBUILD
- mingw-w64-mesa/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/14856
> libva: add package

- mingw-w64-openmp/PKGBUILD
See https://github.com/llvm/llvm-project/issues/60220 and potentially #15220
> openmp: more aarch64 backports

- mingw-w64-python-ipython/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/15249
> ipython: Fix executables by removing setuptools commands

- mingw-w64-quazip/PKGBUILD
> quazip: Fix cmake files

- mingw-w64-libkml/PKGBUILD
- mingw-w64-zlib/PKGBUILD
> libkml: rebuild

- mingw-w64-gw/PKGBUILD
> GW: update to v0.5

- mingw-w64-breeze-qt5/PKGBUILD
Required to support themes in KDE applications.
Thanks to Techie-Guy in Discord for reporting the issue while using Kate ❤️
> breeze-qt5: Add package

- mingw-w64-qgis/PKGBUILD
based on #10852
Fails to build because of some errors about some `dll_export`ed functions declared as `thread_local`.
> [new-package] qgis 3.28.3

- mingw-w64-7zip/PKGBUILD
@dscho Would you like to review this change please?
> 7zip: Remove hard-coded path in the install command

- mingw-w64-seacas/PKGBUILD
> seacas: update to 

- .ci/ci-build.sh
- .ci/ci-library.sh
- .github/workflows/main.yml
I've never found it particular helpful and usually just ignored it.
One could argue that it could be improved to do what we want, but I personally don't want to write that in bash.
> [RFC] CI: remove saneman

- mingw-w64-libidn2/PKGBUILD
> libidn2: Update to 2.3.4 (v2)

- mingw-w64-portsmf/001-portsmf-shared.patch
- mingw-w64-portsmf/002-ptr-arithm-64bits.patch
- mingw-w64-portsmf/PKGBUILD
That pointer arithmetic is **old**!
> New package: portsmf

- mingw-w64-portsmf/PKGBUILD
set version to 0.1 to match the pkgconf file
> portsmf: move to new git upstream

- mingw-w64-binutils/3001-try-fix-compare_section-abort.patch
- mingw-w64-binutils/PKGBUILD
> binutils: try to work around msvc lib linking regression

- mingw-w64-nodejs/0025-Fix-globalPrefix-on-mingw.patch
- mingw-w64-nodejs/0103-node-gyp-support-mingw-toolchain.patch
- mingw-w64-nodejs/PKGBUILD
> nodejs: fix node-gyp

- mingw-w64-armadillo/PKGBUILD
Also use the package description from its .pc file.
> armadillo: update to 11.4.4

- mingw-w64-gimp/PKGBUILD
See https://gitlab.gnome.org/GNOME/gimp/-/issues/9132
> gimp: backport a fix for newer cairo

- mingw-w64-cubew/PKGBUILD
for SCORE-P https://www.vi-hps.org/projects/score-p/
> add new package: Cubew

- mingw-w64-cubelib/PKGBUILD
for SCORE-P https://www.vi-hps.org/projects/score-p/
> add new package: Cubelib

- mingw-w64-gimp3/PKGBUILD
> gimp3: backport cairo fix

- mingw-w64-qt6-base/PKGBUILD
https://www.qt.io/blog/security-advisory-qt-sql-odbc-driver-plugin
> qt6-update: apply CVE-2023-24607-qtbase-6.4.diff

- mingw-w64-gnucobol/PKGBUILD
- mingw-w64-gnucobol/cobenv.sh
and added version output to cobenv
> update GnuCOBOL to 3.2-rc2

- mingw-w64-qdia/0001-qdia-0.32-fix-version.patch
- mingw-w64-qdia/PKGBUILD
Patch was applied upstream in https://github.com/sunderme/qdia/pull/1
> qdia: Fix version

- mingw-w64-qbittorrent/002-winconf-prepare-env-for-mingw.patch
- mingw-w64-qbittorrent/PKGBUILD
the patched section was removed upstream
> qbittorrent: Update to 4.5.1

- mingw-w64-ncurses/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/10434
> ncurses: update to 6.4.20230211

- mingw-w64-python-wordcloud/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/15454
> python-wordcloud: Add package

- mingw-w64-python-pycares/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/15453
> python-pycares: Add package

- mingw-w64-ngspice/PKGBUILD
- mingw-w64-opencascade/0014-aarch64-mm_alloc.patch
- mingw-w64-opencascade/PKGBUILD
The two remaining deps for KiCAD
> opencascade, ngspice: Add aarch64 builds

- mingw-w64-robin-hood-hashing/PKGBUILD
Will be used by `vulkan-validation-layer`.
> robin-hood-hashing: Add package

- mingw-w64-opencascade/PKGBUILD
> opencascade: build against ffmpeg 4.4

- mingw-w64-audaspace/0100-mingw-relocate.patch
- mingw-w64-audaspace/0102-mingw-python.patch
- mingw-w64-audaspace/PKGBUILD
refresh patches
swtich to ninja
switch to git tag archive
This new release also fixes the build with ffmpeg 5
> audaspace: Update to 1.4.0

- mingw-w64-frontistr/PKGBUILD
For some reason It changed After merging!
> frontistr: Fix sha256sums

- mingw-w64-krita/001-mingw-interface-conflict.patch
- mingw-w64-krita/002-exiv2-missing-wpath.patch
- mingw-w64-krita/004-qt5-qguiapplication.patch
- mingw-w64-krita/005-no-installer.patch
- mingw-w64-krita/PKGBUILD
Depends on https://github.com/msys2/MINGW-packages/pull/15911
> [new-package] krita: Add build recipe for ucrt64, mingw64, clang64 and clangarm64

- mingw-w64-gnutls/PKGBUILD
guile bindings have been removed
> gnutls: Update to 3.8.0

- mingw-w64-paraview/001-dll-export-some-vtk-functions.patch
- mingw-w64-paraview/002-link-vtk-to-pdalcpp.patch
- mingw-w64-paraview/PKGBUILD
@hmartinez82 Could you please test building it on clangarm64.
Fixes #15964
> paraview: 5.11.0

- mingw-w64-opencv/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/15750
> opencv: Enable gstreamer support

- mingw-w64-libtermkey/0001-make-remove-demos-sources.patch
- mingw-w64-libtermkey/PKGBUILD
- mingw-w64-libvterm/0001-make-remove-bin-sources.patch
- mingw-w64-libvterm/PKGBUILD
- mingw-w64-neovim/0001-cmake-disable-bundling.patch
- mingw-w64-neovim/PKGBUILD
> neovim: Add package

- mingw-w64-gtk4/0001-combobox-Avoid-extra-queue_resize.patch
- mingw-w64-gtk4/PKGBUILD
> gtk4: fix combobox popups

- mingw-w64-lapack/PKGBUILD
Not sure if we should really bump the pkgrel already. The existing packages shouldn't be changing.
Please, let me know and I'll revert that part.
> lapack: Prepare for compilation with LLVM Flang.

- mingw-w64-wxwidgets3.2/PKGBUILD
> wxwidgets3.2: Do not define -mthreads in CLANGARM64 builds

- mingw-w64-rust/0012-revert-install-llvm-tools.patch
- mingw-w64-rust/0013-revert-lib-host-symlink.patch
- mingw-w64-rust/PKGBUILD
reverts https://github.com/rust-lang/rust/pull/105559/commits/23a34c18f7b2ce8b20fed717ef48e2be1776246b
reverts https://github.com/rust-lang/rust/commit/6f0fc2fd337757a02fa0d948e78638d66a46f518
> rust: update to 1.68.0 (bis)

- mingw-w64-ca-certificates/PKGBUILD
> ca-certificates: Update to 20230311

- mingw-w64-trilinos/PKGBUILD
fails to build/link on mingw32
> trilinos: update to 14.0.0

- mingw-w64-hdf5/PKGBUILD
- mingw-w64-hdf5/hdf5-fix-static-lib.patch
Fixes https://github.com/msys2/MINGW-packages/issues/15449
> hdf5: Fix static linking with curl

- mingw-w64-crypto++/PKGBUILD
Remove GNUmakefile patching, we use cmake now
> crypto++: Update to 8.7.0

- mingw-w64-gtk3/PKGBUILD
Includes fixes for:
* https://gitlab.com/inkscape/inkscape/-/issues/4031
* https://gitlab.gnome.org/GNOME/gtk/-/issues/5678
> gtk3: update to 3.24.37+22+gf1b6556aac

- mingw-w64-gtk3/0005-meson-fix-linker-flags-pkgconfig.patch
- mingw-w64-gtk3/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/16362
> gtk3: Fix linker flags in pkgconfig

- mingw-w64-openpgl/003-Fix-building-on-mingw-w64-aarch64.patch
- mingw-w64-openpgl/PKGBUILD
> openpgl: Fix building on aarch64

- mingw-w64-libplacebo/PKGBUILD
> libplacebo: Update to 5.264.1

- mingw-w64-at-spi2-core/0001-fix-typo.patch
- mingw-w64-at-spi2-core/0002-skip-libltdl.patch
- mingw-w64-at-spi2-core/PKGBUILD
atk upstream is now part of at-spi2-core
> atk: Update to 2.48.0

- mingw-w64-nim/0003-Fix-library-path.patch
- mingw-w64-nim/0004-Fix-nimrtl-dll-name.patch
- mingw-w64-nim/0007-Fix-openssl-dll-name.patch
- mingw-w64-nim/PKGBUILD
- mingw-w64-nimble/PKGBUILD
> nim: Update to 1.6.12

- mingw-w64-cmake/PKGBUILD
see https://gitlab.kitware.com/cmake/cmake/-/issues/24642
> cmake: Fix failure to build QGIS

- mingw-w64-supertux/0001-cmake-disable-dependencies-paths.patch
- mingw-w64-supertux/0002-cmake-fix-linking-order.patch
- mingw-w64-supertux/0003-include-missing-header.patch
- mingw-w64-supertux/0004-cmake-fix-iconv-check.patch
- mingw-w64-supertux/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/16491
> supertux: Add package

- mingw-w64-qoi/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/16558
> qoi: Add package

- mingw-w64-cmake/0003-fix-finding-openssl-on-mingw.patch
- mingw-w64-cmake/PKGBUILD
This should fix building qt6-static
> cmake: Fix finding OpenSSL on MINGW

- mingw-w64-typst/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/16612
> typst: Add package

- mingw-w64-qt5-virtualkeyboard/PKGBUILD
> qt5-virtualkeyboard: Fix building

- mingw-w64-python-winsdk/PKGBUILD
I only built it and tested it on `clang64`
> python-winsdk: Add package

- mingw-w64-openxr/001-use-def-file-on-mingw-w64.patch
- mingw-w64-openxr/002-libname-def-file.patch
- mingw-w64-openxr/PKGBUILD
* Use the OpenXR-SDK-Source repository which has the api_layers directory.
* Add DEF with source list to export proper APIs.
Fixes https://github.com/msys2/MINGW-packages/issues/16837
> openxr: Build api layers

- mingw-w64-qbittorrent/004-unixy-install.patch
- mingw-w64-qbittorrent/005-no-invalid-redef.patch
- mingw-w64-qbittorrent/PKGBUILD
> qbittorrent: use qt6 if possible

- mingw-w64-knotifyconfig-qt5/PKGBUILD
- mingw-w64-konsole/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/16581
> konsole: Add package

- mingw-w64-rust/0007-clang-subsystem.patch
- mingw-w64-rust/0012-revert-install-llvm-tools.patch
- mingw-w64-rust/PKGBUILD
see https://blog.rust-lang.org/2023/04/20/Rust-1.69.0.html
> rust: update to 1.69.0

- mingw-w64-tcl/012-tcl-add-pkgconfig-file.patch
- mingw-w64-tcl/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/16814
> tcl: Add pkgconfig file

- mingw-w64-geoipupdate/001-relocate.patch
- mingw-w64-geoipupdate/002-change-defaults-dirs.patch
- mingw-w64-geoipupdate/PKGBUILD
~@lazka What kind of issue `001-relocate.patch` (https://github.com/msys2/MINGW-packages/commit/7b265868a43e61a766d1263836a50cfdfc143d1b) was supposed to fix?
Could you test this one.~
> geoipupdate: update to 5.0.4

- mingw-w64-source-highlight/PKGBUILD
- mingw-w64-source-highlight/source-highlight-gcc11.patch
Fixes https://github.com/msys2/MINGW-packages/pull/17027
Fixes https://github.com/msys2/MINGW-packages/issues/17026
Fixes https://github.com/msys2/MINGW-packages/issues/7928
> source-highlight: Rebuild for boost update

- mingw-w64-libheif/PKGBUILD
- mingw-w64-libwebp/PKGBUILD
> libheif: update to 1.16.1

- mingw-w64-ntldd/PKGBUILD
> ntldd-git: rename to ntldd

- mingw-w64-unibilium/PKGBUILD
> unibilium: rebuild

- mingw-w64-gitg/PKGBUILD
> gitg: rebuild

- mingw-w64-gcab/0001-skip-git.patch
- mingw-w64-gcab/PKGBUILD
as it will fail if there is no git repo
> gcab: avoid calling git in the meson build script

- mingw-w64-gst-plugins-bad/PKGBUILD
- mingw-w64-gst-plugins-good/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17038
> Split gtk and opencv gstreamer plugins into separate packages

- mingw-w64-clang/PKGBUILD
- mingw-w64-spirv-llvm-translator/PKGBUILD
Make a dedicated package with the LLVM runtime libraries.
Inspired by https://archlinux.org/packages/extra/x86_64/llvm-libs/
> llvm-libs: new package

- mingw-w64-gst-plugins-rs/PKGBUILD
In my previous PR, I did not notice that some plugins (e.g. the GTK4 plugin) were being skipped. This PR is supposed to fix that issue.
> gst-plugins-rs: Fix some plugins not included

- mingw-w64-xa65/0001-make-fix-predefined-variables.patch
- mingw-w64-xa65/PKGBUILD
Version 2.3.14 (7 February 2023)
> Update xa65 to latest version

- mingw-w64-helix/PKGBUILD
@mati865 any idea how to pass CFLAGS to cargo?
> helix: update to 23.05

- mingw-w64-libxslt/PKGBUILD
> libxslt: Update to 1.1.38

- mingw-w64-tme/PKGBUILD
Corrections to keyboard handling and some build fixes. Added automated machine building script. Finding modules without having to set environment variables.
> tme: Update to 0.12rc11

- mingw-w64-ffmpeg4.4/PKGBUILD
> ffmpeg4.4: Update to 4.4.4

- mingw-w64-lua/0001-When-running-Win32-version-of-luac-on-mintty-or-othe.patch
- mingw-w64-lua/0002-Add-Wl-out-implib-liblua.dll.a-to-AR.patch
- mingw-w64-lua/0003-Fix-LUA_-DIR-for-MSYS2-FHS-layout.patch
- mingw-w64-lua/PKGBUILD
- mingw-w64-lua/link-implib.patch
Fixes https://github.com/msys2/MINGW-packages/issues/17220
> lua: update to 5.4.6

- mingw-w64-texlive-bin/0004-add-missing-includes-dvisvgm.patch
- mingw-w64-texlive-bin/PKGBUILD
see https://tug.org/pipermail/tldistro/2023q2/000463.html
the other patch is a cherry-pick from https://github.com/mgieseki/dvisvgm/commit/b16a8d1c452d809118ceade4d2e8c6f9dfce48ac
> texlive-bin: update LuaTeX

- mingw-w64-unittest-cpp/0001-cmake-fix-version.patch
- mingw-w64-unittest-cpp/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17297
> unittest-cpp: Fix missing version in pkgconfig file

- mingw-w64-binutils/0001-improve-speed-of-computing-checksums-coff.patch
- mingw-w64-binutils/0003-make-ar-faster.patch
- mingw-w64-binutils/0004-add-section-caches-to-coff_data_type.patch
- mingw-w64-binutils/PKGBUILD
Upstreamed patches by @oltolm.
See also #16095.
I used those patches since a couple of days locally. And they don't seem to break anything for me.
> binutils: Cherry-pick some patches to improve link performance.

- mingw-w64-angleproject/003-angle-src-fixes.patch
- mingw-w64-angleproject/PKGBUILD
Rebuild after #17163 to fix #16971
> angleproject: rebuild

- mingw-w64-lua53/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17337
> lua53: Use cc instead of gcc

- mingw-w64-gdb/PKGBUILD
update by version and sha adjustment (possibly more to come if CI doesn't work)
> mingw-w64-gdb update to 13.2

- mingw-w64-cargo-c/PKGBUILD
@hmartinez82 Could you please test building it on clangarm64. last time 0.9.18 failed to build.
> cargo-c: update to 0.9.19

- mingw-w64-qt6-multimedia/PKGBUILD
> qt6-multimedia: change ffmpeg to required dependency

- mingw-w64-64tass/PKGBUILD
Initial package attempt of the 64tass assembler.
> Package 64tass 1.58.2974

- mingw-w64-fxc2/PKGBUILD
> fxc2: Update to r19.807d26f

- mingw-w64-python-fastapi/PKGBUILD
> python-fastapi: New package

- mingw-w64-lcms2/0001-disable-def-exports.patch
- mingw-w64-lcms2/PKGBUILD
Resolves https://github.com/msys2/MINGW-packages/issues/17360
> lcms2: disable exports via def file

- mingw-w64-qemu/PKGBUILD
> qemu: Update to 8.0.2

- mingw-w64-python-pygad/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17371
> python-pygad: Add package

- mingw-w64-nettle/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17410
> nettle: update to 3.9.1

- mingw-w64-emscripten/PKGBUILD
- mingw-w64-emscripten/emscripten-CLANG64.install
- mingw-w64-emscripten/emscripten-UCRT64.install
based on ArchLinux recipe.
Not tested.
> [new-package] emscripten 3.1.39

- mingw-w64-libdatrie/PKGBUILD
- mingw-w64-libthai/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/pull/17392
> libdatrie, libthai: Add docs package

- mingw-w64-cmake/PKGBUILD
As discussed in https://matrix.to/#/!KcLVgQvsWqZARtzJOs:gitter.im/$uUbSXHy3fYntHU-9ppJFR84wuE2SnZMpwORFRFYPemE
> cmake: split docs in separate package

- mingw-w64-python-llvmlite/PKGBUILD
Instead of https://github.com/msys2/MINGW-packages/pull/17370
> Update llvmlite to 0.40.1rc1

- mingw-w64-clang/0006-COFF-Remove-misleading-and-unclear-comments.-NFC.patch
- mingw-w64-clang/0007-llvm-dlltool-Clarify-parameters-simplify-ArgList-usa.patch
- mingw-w64-clang/0008-llvm-dlltool-Ignore-the-temp-prefix-option.patch
- mingw-w64-clang/0009-llvm-dlltool-Implement-the-no-leading-underscore-opt.patch
- mingw-w64-clang/PKGBUILD
- mingw-w64-clang/README-patches.md
- mingw-w64-libc++/PKGBUILD
\+ a backport for an issue affecting meson: https://github.com/mesonbuild/meson/issues/11642#issuecomment-1586524670
> clang: Update to 16.0.5

- mingw-w64-rapidjson/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17530
> rapidjson: Fix path relocation in cmake files

- mingw-w64-ghex/PKGBUILD
Fixes https://github.com/msys2/MINGW-packages/issues/17560
> ghex: Enable introspection support

- mingw-w64-directxmath/PKGBUILD
- mingw-w64-directxtex/PKGBUILD
the release tags are not pkgver compatible
> directxtex, directxmath: fix version scheme

- mingw-w64-sonixflasher/PKGBUILD
[sonixflasher](https://github.com/SonixQMK/SonixFlasherC)  integration for mingw
> add sonixflasher package
